-- Study together: friend codes, shared progress, friend requests.
-- Run once in the Supabase SQL editor (Dashboard → SQL → New query → paste → Run).
-- Safe to re-run: every statement is idempotent.
--
-- ---------------------------------------------------------------------------------------------
-- THE PRIVACY SHAPE, AND WHY IT IS THREE TABLES
--
-- `progress` (the existing sync table) holds EVERYTHING: every flashcard, every day of the plan
-- log, every setting. Friends must never be able to read a byte of it, so nothing here touches
-- it. Instead the app copies a handful of numbers it is willing to share into `stats`, and only
-- those numbers are ever visible to anyone else.
--
-- `profiles` and `stats` are separate for one specific reason: to add a friend you must be able
-- to look someone up by their code BEFORE you are friends, and Postgres row-level security
-- grants whole rows, not columns. So the lookup table holds only a display name and a code
-- (nothing private), and the numbers live in a second table that accepted friends alone can read.
--
--   profiles     name + friend code       → any signed-in user may read (that is the lookup)
--   stats        hours, streak, phase     → owner and ACCEPTED friends only
--   friendships  who is connected to whom → only the two people involved
--
-- A friend code is deliberately not an email. Letting anyone query "is this email registered?"
-- turns the app into an email-existence oracle; a random code you choose to hand out does not.
-- ---------------------------------------------------------------------------------------------

-- ---------- profiles: the public-to-signed-in-users nameplate ----------
create table if not exists public.profiles (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  handle       text unique not null,          -- the friend code, e.g. 'K7M2QX'
  display_name text not null default '',
  created_at   timestamptz not null default now(),
  constraint handle_shape check (handle ~ '^[A-Z0-9]{6}$')
);

alter table public.profiles enable row level security;

-- Readable by any signed-in user: this IS the friend-code lookup, and the row holds no progress
-- data. Deliberately NOT readable by anon — a logged-out scraper gets nothing.
drop policy if exists "profiles readable by signed-in" on public.profiles;
create policy "profiles readable by signed-in" on public.profiles
  for select to authenticated using (true);

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own" on public.profiles
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- friendships: one row per connection ----------
-- Stored as an unordered pair kept in a canonical order (a < b) so "A added B" and "B added A"
-- can never both exist. `requester` records who asked, which is what decides who may accept.
create table if not exists public.friendships (
  id         bigint generated by default as identity primary key,
  user_a     uuid not null references auth.users(id) on delete cascade,
  user_b     uuid not null references auth.users(id) on delete cascade,
  requester  uuid not null references auth.users(id) on delete cascade,
  status     text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  constraint ordered_pair check (user_a < user_b),
  constraint no_self check (user_a <> user_b),
  unique (user_a, user_b)
);

create index if not exists friendships_a on public.friendships (user_a);
create index if not exists friendships_b on public.friendships (user_b);

alter table public.friendships enable row level security;

drop policy if exists "friendships visible to both" on public.friendships;
create policy "friendships visible to both" on public.friendships
  for select to authenticated using (auth.uid() in (user_a, user_b));

-- You may only create a request you are part of, and only as the requester. `status` is forced to
-- 'pending' here so nobody can insert a pre-accepted friendship and read someone's stats uninvited.
drop policy if exists "friendships request" on public.friendships;
create policy "friendships request" on public.friendships
  for insert to authenticated
  with check (auth.uid() in (user_a, user_b) and auth.uid() = requester and status = 'pending');

-- Only the person who DIDN'T ask may accept. Without the requester check, the sender could
-- accept their own request and let themselves in.
drop policy if exists "friendships accept" on public.friendships;
create policy "friendships accept" on public.friendships
  for update to authenticated
  using (auth.uid() in (user_a, user_b) and auth.uid() <> requester)
  with check (auth.uid() in (user_a, user_b) and auth.uid() <> requester);

-- Either side can walk away at any time — that also serves as "decline".
drop policy if exists "friendships remove" on public.friendships;
create policy "friendships remove" on public.friendships
  for delete to authenticated using (auth.uid() in (user_a, user_b));

-- An RLS policy sees the old row in USING and the new row in WITH CHECK, but it cannot compare
-- the two — so a policy alone cannot say "you may change the status but not who this is with".
-- Without this grant, B (accepting A's request) could swap A out for an unsuspecting C and read
-- C's stats: the check "am I still in the pair?" would still pass. Column privileges close it.
revoke update on public.friendships from authenticated;
grant update (status) on public.friendships to authenticated;

-- ---------- stats: the handful of numbers you agree to share ----------
-- Everything here is an aggregate. No card, no sentence, no text you have read, nothing that
-- says WHAT you studied — only how much, how consistently, and how far along the plan you are.
create table if not exists public.stats (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  hours       numeric(8,1) not null default 0,     -- total logged hours
  week_min    integer      not null default 0,     -- minutes in the last 7 days
  streak      integer      not null default 0,     -- consecutive days practised
  phase       smallint     not null default 0,     -- 0..6, the plan phase they are in
  cards       integer      not null default 0,     -- flashcards in their collection
  last_active date,                                -- last day anything was completed
  updated_at  timestamptz  not null default now()
);

alter table public.stats enable row level security;

-- The whole point: your own row, plus the rows of people you have BOTH agreed to connect with.
-- `friendships` policies never reference `stats`, so there is no policy recursion here.
drop policy if exists "stats own and friends" on public.stats;
create policy "stats own and friends" on public.stats
  for select to authenticated using (
    auth.uid() = user_id
    or exists (
      select 1 from public.friendships f
      where f.status = 'accepted'
        and ((f.user_a = auth.uid() and f.user_b = stats.user_id)
          or (f.user_b = auth.uid() and f.user_a = stats.user_id))
    )
  );

drop policy if exists "stats insert own" on public.stats;
create policy "stats insert own" on public.stats
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "stats update own" on public.stats;
create policy "stats update own" on public.stats
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------------------------
-- Checking it works, from the SQL editor (which runs as a superuser and BYPASSES RLS — so these
-- only prove the tables exist). To test the policies properly, sign in as two different accounts
-- in the app: B should see A's stats only after B accepts, and never see A's `progress` row.
-- ---------------------------------------------------------------------------------------------
-- select count(*) from public.profiles;
-- select count(*) from public.friendships;
-- select count(*) from public.stats;
