#!/usr/bin/env python3
"""Where the reference grammar and Maknuune disagree, the grammar wins.

Maknuune is a lexicon: excellent coverage, one citation form per entry, and no comment on
which of two competing vowellings a Palestinian actually says. Lingualism's *Palestinian
Arabic Verbs* is a conjugation grammar: fewer verbs, but each one is a full paradigm chosen
and annotated by people describing spoken Palestinian. For how a verb is CONJUGATED, the
grammar is the better authority — so its principal parts override the lexicon's here.

Only the two principal parts are recorded (perfect 3ms + imperfect 3ms, in the app's own
romanization) plus a short note in our words. Everything else — the 30 cells of each
paradigm, the Arabic, the harakat — is regenerated by pipeline/conjugate.py from those two
facts, exactly as it is for every other verb. Nothing from the book is reproduced.

To add one: read the book's table, copy its húwwa perfect and húwwa imperfect
romanizations, and add a row. `python3 pipeline/apply_book_overrides.py` then rebuilds the
affected paradigms in app/data/verbs.js without needing the lexicon.
"""

# Key on (root, form, the lexicon's own perfect) — root+form alone is NOT unique. ع.م.ل Form I
# holds both عِمِل "do/make" and مَعْمَل "play in dirt", and keying loosely overwrote the second
# with the first the moment this was first run.
OVERRIDES = {
    ('ع.م.ل', 'I', '3imil'): {
        'past': '3amal', 'pres': 'yi3mal',
        'past_ar': 'عَمَل', 'pres_ar': 'يِعْمَل',
        # The book prints عَمَل and flags the kasra version as a minority variant; Maknuune
        # happened to record only that variant, which is what the app had been showing.
        'note': 'The book conjugates this with fatha (3amal). Some speakers say عِمِل instead.',
    },
    ('ك.ذ.ب', 'I', 'kizib'): {
        'past': 'kazab', 'pres': 'yikzib',
        'past_ar': 'كَذَب', 'pres_ar': 'يِكْذِب',
        # Surfaced by book_sweep.py: the book's table (p99) conjugates kázab; Maknuune
        # recorded the kasra variant. Same عمل pattern — the grammar wins on conjugation.
        'note': 'The book conjugates this with fatha (kazab). Some speakers say كِذِب instead.',
    },
}

# Records SUPERSEDED by an override. Maknuune sometimes carries the same verb twice — كذب
# exists both as the comma-alternation record (kazab,kadhab) and as kizib. The override
# turns kizib into the book's kazab with a full paradigm; shipping the comma twin as well
# would list the same verb twice, so it is dropped, not silently but here, by name.
DROP = {
    ('ك.ذ.ب', 'I', 'kazab,kadhab'),
}

def override_for(root, form, past_caphi):
    """The lexicon's own perfect is part of the key, so an override can only ever hit the
    one entry it was written for."""
    return OVERRIDES.get((str(root), str(form), str(past_caphi)))
