#!/usr/bin/env python3
"""جزيرة الكنز — Treasure Island, retold in spoken Palestinian, graded to intermediate.

Robert Louis Stevenson died in 1894; the novel (1883) is public domain. This is a retelling from
the plot, not a translation of any edition.

WHY IT EARNS A PLACE. It is told in the FIRST PERSON by a boy roughly the age of a beginner's
confidence, and that is worth a lot pedagogically: شفت، كنت، خفت، ما عرفت. A learner reading
Sindbad or Kalila is reading about people; reading Jim, they are rehearsing the forms they will
actually use to tell their own day. It is also the most plot-driven book on the shelf — the
chapter endings pull, which is what gets someone to read thirty of them.

LEVEL. Written near the intermediate story baseline (32.5 characters a sentence), like Sindbad and
Kalila. Past-tense first-person narration with real connectors, dialogue carrying the tension, one
clause at a time.

A NOTE ON THE VILLAIN. Silver is not simplified into a monster. Half of what makes the book work
is that Jim likes him and cannot stop liking him, and that reads at B1 as easily as it does in
English — the ambivalence is in what people say, not in complicated syntax.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_treasure.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, book

BOOK_ID = 'treasure'
BOOK_TITLE = {'en': 'Treasure Island', 'ar': 'جزيرة الكنز'}

# (english title, arabic title, [paragraph, ...])
#
# SECOND EDITION (2026-09-03). The first edition was three paragraphs a chapter — a plot summary
# in Jim's voice. Same thirty chapters and titles, now written as chapters: the inn, the
# voyage, the island and the stockade with their scenes and their talk, and Silver given room
# to be liked.
CHAPTERS = [
 ('The Old Sea-Dog', 'البحري العجوز', [
  P(('اسمي جيم هوكينز، وهاي قصتي مع الكنز.', "My name is Jim Hawkins, and this is my story with the treasure."),
    ('أهلي كان عندهم نزل زغير عالبحر، اسمه الأدميرال بنبو.', "My family had a small inn by the sea, called the Admiral Benbow."),
    ('أبوي كان مريض، وأمي كانت بتشتغل كل إشي.', "My father was ill, and my mother did all the work."),
    ('وأنا كنت ولد، بساعد بالمطبخ وبراقب الطريق.', "And I was a boy, helping in the kitchen and watching the road.")),
  P(('بيوم، إجا رجل كبير بالعمر، وعلى كتفه صندوق بحر.', "One day, an old man came, with a sea chest on his shoulder."),
    ('كان طويل وقوي، ووجهه فيه ندبة كبيرة زرقا.', "He was tall and strong, and his face had a big blue scar."),
    ('شعره أبيض ومربوط، وتيابه وسخة.', "His hair was white and tied back, and his clothes were dirty."),
    ('وقف قدام النزل وتطلع عالبحر طويل.', "He stood in front of the inn and looked at the sea for a long time."),
    ('وبعدين قال: هون منيح. بدي أوضة.', "And then he said: this is good. I want a room."),
    ('رمى قطعة ذهب عالطاولة وقال: لما تخلص، قولوا لي.', "He threw a gold piece on the table and said: when it runs out, tell me.")),
  P(('سكن عندنا شهور، وما حكى عن حاله أبداً.', "He stayed with us for months, and never spoke about himself."),
    ('كل يوم كان يطلع عالصخر بمنظاره، ويتطلع عالبحر.', "Every day he went up onto the rocks with his spyglass, and looked out at the sea."),
    ('وبالليل كان يشرب روم ويغني أغاني بحارة.', "And at night he drank rum and sang sailors' songs."),
    ('كان يغني: خمستاشر زلمة على صندوق الميت.', "He would sing: fifteen men on the dead man's chest."),
    ('يوهوهو وقنينة روم.', "Yo ho ho and a bottle of rum."),
    ('الناس كانوا يخافوا منه، وبنفس الوقت يحبوا يسمعوا قصصه.', "People were afraid of him, and at the same time loved to hear his stories."),
    ('قصص عن مشانق وعواصف وناس بيمشوا عالخشبة.', "Stories of gallows and storms and men walking the plank."),
    ('وكان الكل يسميه: الكابتن.', "And everyone called him: the Captain.")),
  P(('بيوم أخدني عالجنب وأعطاني مصاري.', "One day he took me aside and gave me money."),
    ('قال: كل شهر بعطيك هيك، وإنت راقب الطريق.', "He said: every month I give you this, and you watch the road."),
    ('إذا شفت بحري بإجر وحدة، تعال قول لي فوراً.', "If you see a sailor with one leg, come and tell me at once."),
    ('سألته: مين هو؟ ما جاوب.', "I asked him: who is he? He did not answer."),
    ('بس من يومها صرت أحلم بالبحري أبو إجر وحدة.', "But from that day I dreamed of the one-legged sailor."),
    ('كان يجي بالليل، بشكل تاني كل مرة، ويركض ورايي.', "He came at night, in a different shape every time, and ran after me."),
    ('وما كنت أعرف إني رح أشوفه بالحقيقة، وقريب.', "And I did not know that I would see him in real life, and soon."))]),

 ('Black Dog', 'الكلب الأسود', [
  P(('بيوم شتوي بارد، أبوي كان مريض كتير.', "One cold winter day, my father was very ill."),
    ('وأنا كنت لحالي بالنزل.', "And I was alone at the inn."),
    ('الكابتن طلع يمشي عالشط، زي كل صبح.', "The Captain had gone out to walk on the shore, as he did every morning."),
    ('فتح الباب، ودخل زلمة ما شفته قبل.', "The door opened, and a man I had never seen came in."),
    ('كان شاحب وسمين، وناقص منه إصبعين من إيده الشمال.', "He was pale and fat, and two fingers were missing from his left hand."),
    ('ما كان شكله بحري، بس كان فيه إشي من البحر.', "He did not look like a sailor, but there was something of the sea about him.")),
  P(('طلب كاسة روم، وسألني: هاي الطاولة لصاحبي بيلي؟', "He ordered a glass of rum, and asked me: is this table for my friend Billy?"),
    ('قلت له: ما بعرف بيلي. عنا واحد اسمه الكابتن.', "I told him: I do not know any Billy. We have someone called the Captain."),
    ('قال: الكابتن؟ عنده ندبة على خده، صح؟', "He said: the Captain? He has a scar on his cheek, right?"),
    ('قلت: صح.', "I said: right."),
    ('ضحك ضحكة ما عجبتني، وقال: هاد بيلي. وين هو؟', "He laughed a laugh I did not like, and said: that is Billy. Where is he?"),
    ('قلت: طالع يمشي، ورح يرجع قريب.', "I said: he is out walking, and he will be back soon."),
    ('قال: منيح. بستناه هون. رح يفرح فيّ.', "He said: good. I will wait for him here. He will be glad to see me."),
    ('وقعد ورا الباب، بمكان ما بيبان منه.', "And he sat behind the door, in a place where he could not be seen.")),
  P(('بعد شوي، دخل الكابتن.', "A little later, the Captain came in."),
    ('مشى لطاولته، وما شاف الزلمة.', "He walked to his table, and did not see the man."),
    ('قال الزلمة من وراه: بيلي.', "The man said from behind him: Billy."),
    ('الكابتن التفت، ووجهه صار أبيض زي الحيط.', "The Captain turned, and his face went as white as the wall."),
    ('قال: الكلب الأسود!', "He said: Black Dog!"),
    ('قال الزلمة: هو أنا. الكلب الأسود إجا يزور صاحبه القديم بيلي.', "The man said: it is me. Black Dog has come to visit his old friend Billy."),
    ('قال الكابتن: طيب، شو بدك؟', "The Captain said: fine, what do you want?"),
    ('قال الكلب الأسود: نحكي. بس الأول، يا ولد، اطلع برا.', "Black Dog said: to talk. But first, boy, get out.")),
  P(('طلعت، بس وقفت ورا الباب وسمعت.', "I went out, but I stood behind the door and listened."),
    ('بالأول كانوا يحكوا واطي، وما فهمت غير كلمات.', "At first they talked low, and I understood only words."),
    ('وبعدين علا الصوت، وسمعت الكابتن يصرخ: لا، لا، لا!', "And then the voices rose, and I heard the Captain shout: no, no, no!"),
    ('وبعدين صار صوت كراسي، وصوت سيوف.', "And then there was the sound of chairs, and the sound of swords."),
    ('فتحت الباب وشفت الاتنين واقفين، وبإيد كل واحد سيف.', "I opened the door and saw the two standing, a sword in each one's hand."),
    ('الكلب الأسود كان بينزف من كتفه.', "Black Dog was bleeding from his shoulder."),
    ('هرب من الباب، وركض عالطريق، واختفى.', "He fled out the door, ran up the road, and disappeared."),
    ('والكابتن وقف مكانه، ومسك الحيط، ووقع عالأرض.', "And the Captain stood where he was, held the wall, and fell to the floor."))]),

 ('The Black Spot', 'النقطة السودا', [
  P(('ركضت وناديت أمي، وجبنا الدكتور ليفزي.', "I ran and called my mother, and we fetched Doctor Livesey."),
    ('الدكتور كان زلمة هادي ونضيف، وما بيخاف من حدا.', "The doctor was a calm, clean man, who feared no one."),
    ('فحص الكابتن وقال: هاي مش جرح. هاي جلطة من الرم.', "He examined the Captain and said: this is no wound. This is a stroke from the rum."),
    ('لما فاق الكابتن، قال له الدكتور: كاسة روم كمان، وبتموت.', "When the Captain came to, the doctor told him: one more glass of rum, and you die."),
    ('قال الكابتن: أنا بموت بلا روم.', "The Captain said: I die without rum."),
    ('قال الدكتور: هاد قرارك.', "The doctor said: that is your decision.")),
  P(('بالليل، ناداني الكابتن على أوضته.', "At night, the Captain called me to his room."),
    ('قال: يا جيم، إنت الوحيد اللي بصدقه.', "He said: Jim, you are the only one I believe."),
    ('الكلب الأسود مش لحاله. في كتار، وكلهم بدهم صندوقي.', "Black Dog is not alone. There are many, and they all want my chest."),
    ('سألته: وليش بدهم صندوقك؟', "I asked him: and why do they want your chest?"),
    ('قال: لأنه أنا كنت المساعد الأول عند فلينت.', "He said: because I was Flint's first mate."),
    ('فلينت، أخطر قرصان بالبحر، وأنا الوحيد اللي بيعرف مكانه.', "Flint, the most dangerous pirate on the sea, and I am the only one who knows his place."),
    ('إذا إجوا وأعطوني النقطة السودا، اركض للدكتور.', "If they come and give me the black spot, run to the doctor."),
    ('سألته: شو النقطة السودا؟', "I asked him: what is the black spot?"),
    ('قال: إنذار. يعني إجا وقتك.', "He said: a warning. It means your time has come.")),
  P(('وبنفس الأسبوع، مات أبوي.', "And that same week, my father died."),
    ('كنت مشغول بالحزن، ونسيت الكابتن وصندوقه.', "I was taken up with grief, and forgot the Captain and his chest."),
    ('بس بيوم بعد الجنازة، كنت واقف عالباب.', "But one day after the funeral, I was standing at the door."),
    ('وشفت واحد جاي عالطريق.', "And I saw someone coming up the road."),
    ('كان أعمى، ماشي بعصاية، ولابس عباية كبيرة.', "He was blind, walking with a stick, and wearing a big cloak."),
    ('قال: في حدا هون يساعد أعمى مسكين؟', "He said: is there anyone here to help a poor blind man?"),
    ('مديت إيدي، ومسكها بقوة زي الحديد.', "I held out my hand, and he grabbed it with a grip like iron."),
    ('قال بصوت تاني: وديني عند الكابتن، وإلا بكسر إيدك.', "He said in a different voice: lead me to the Captain, or I break your arm.")),
  P(('دخلت فيه على الكابتن، وقلبي بيدق.', "I brought him in to the Captain, my heart pounding."),
    ('لما شافه الكابتن، حاول يوقف، وما قدر.', "When the Captain saw him, he tried to stand, and could not."),
    ('قال الأعمى: خليك قاعد يا بيلي. مد إيدك.', "The blind man said: stay seated, Billy. Hold out your hand."),
    ('حط ورقة بإيد الكابتن، وطلع بسرعة.', "He put a paper in the Captain's hand, and left quickly."),
    ('وعصايته بتدق على الطريق.', "His stick tapping on the road."),
    ('الكابتن فتح الورقة، وشاف نقطة سودا.', "The Captain opened the paper, and saw a black spot."),
    ('وتحتها مكتوب: عندك لحد الساعة عشرة الليلة.', "And beneath it was written: you have until ten o'clock tonight."),
    ('قال: عشرة! عنا ست ساعات. يا جيم، رح نقلب عليهم.', "He said: ten! We have six hours. Jim, we will turn the tables on them."),
    ('وقف، ومسك صدره، ووقع.', "He stood, clutched his chest, and fell."),
    ('وهالمرة ما فاق.', "And this time he did not wake."))]),

 ('The Sea Chest', 'صندوق البحر', [
  P(('حكيت لأمي كل إشي، وما كان عنا وقت نبكي.', "I told my mother everything, and we had no time to cry."),
    ('قالت: هاد الزلمة كان مديون لنا، والمصاري بصندوقه.', "She said: this man owed us money, and the money is in his chest."),
    ('وأنا ما رح أترك أصحابه ياخدوا اللي إلنا.', "And I will not let his friends take what is ours."),
    ('ركضنا عالقرية نطلب مساعدة، بس الناس خافوا.', "We ran to the village to ask for help, but the people were afraid."),
    ('كلمة فلينت كانت كافية إنه ما حدا يطلع معنا.', "The word Flint was enough for no one to come with us."),
    ('قالت أمي: طيب، بنروح لحالنا.', "My mother said: fine, we go alone.")),
  P(('رجعنا عالنزل بالعتمة، وسكرنا الباب.', "We went back to the inn in the dark, and locked the door."),
    ('الكابتن كان مرمي عالأرض زي ما تركناه.', "The Captain was lying on the floor as we had left him."),
    ('أخدت المفتاح من رقبته، وطلعنا على أوضته.', "I took the key from around his neck, and we went up to his room."),
    ('الصندوق كان قديم، وعليه حرف ب محروق.', "The chest was old, with the letter B burned into it."),
    ('فتحناه: تياب، وبوصلة، ومسدسين، وقطعة فضة.', "We opened it: clothes, a compass, two pistols, a piece of silver."),
    ('وتحت كل هاد، كيس مصاري، ورزمة أوراق ملفوفة بقماش.', "And under all that, a bag of money, and a bundle of papers wrapped in cloth.")),
  P(('أمي بلشت تعد المصاري، عملة عملة.', "My mother began counting the money, coin by coin."),
    ('قالت: بس اللي إلنا، ولا قرش زيادة.', "She said: only what is ours, and not a penny more."),
    ('كانت المصاري من كل بلاد الدنيا، وكانت بطيئة.', "The coins were from every country in the world, and she was slow."),
    ('وأنا واقف عالشباك، وقلبي بحلقي.', "And I stood at the window, my heart in my throat."),
    ('وفجأة سمعت صوت. طق، طق، طق، على الطريق.', "And suddenly I heard a sound. Tap, tap, tap, on the road."),
    ('عصاية الأعمى.', "The blind man's stick.")),
  P(('الصوت وصل عالباب. وبعدين حدا جرب المقبض.', "The sound reached the door. And then someone tried the handle."),
    ('الباب كان مسكر، والأعمى وقف، وبعدين مشى.', "The door was locked, and the blind man stood, and then walked away."),
    ('قلت: يا ماما، خدي كل الكيس وخلينا نطلع!', "I said: mother, take the whole bag and let us go!"),
    ('قالت: لا. بس اللي إلنا.', "She said: no. Only what is ours."),
    ('وبعدين سمعنا صفير من بعيد، وصوت رجال كتار بيركضوا.', "And then we heard a whistle from afar, and the sound of many men running."),
    ('قالت أمي: طيب. خد الأوراق، وأنا بأخد اللي عديته.', "My mother said: fine. Take the papers, and I take what I have counted."),
    ('وطلعنا من الباب الخلفي، بالعتمة.', "And we went out the back door, into the dark."))]),

 ('The Blind Man', 'الأعمى', [
  P(('كان الضباب تقيل، والقمر لسا ما طلع.', "The fog was thick, and the moon had not yet risen."),
    ('ركضنا لحد الجسر الزغير، وأمي قالت: ما بقدر أكمل.', "We ran as far as the little bridge, and my mother said: I cannot go on."),
    ('وقعت جنب الجسر، وأنا سحبتها تحته.', "She collapsed beside the bridge, and I dragged her under it."),
    ('كنا قريبين من النزل، نسمع كل إشي ونشوف.', "We were close to the inn, hearing and seeing everything."),
    ('وشفت سبعة أو تمانية رجال جايين بالركض، والأعمى بالنص.', "And I saw seven or eight men coming at a run, with the blind man in the middle.")),
  P(('كان الأعمى يصرخ: اكسروا الباب!', "The blind man was shouting: break the door down!"),
    ('كسروا الباب، وفاتوا، وسمعنا صوتهم من جوا.', "They broke the door, went in, and we heard their voices from inside."),
    ('واحد صرخ: بيلي ميت!', "One shouted: Billy is dead!"),
    ('صرخ الأعمى: فتشوه! واطلعوا عالصندوق!', "The blind man shouted: search him! And go up to the chest!"),
    ('وبعد شوي، صرخ واحد من الشباك: حدا فتح الصندوق قبلنا!', "And a little later, one shouted from the window: someone opened the chest before us!"),
    ('قال الأعمى: المصاري موجودة؟', "The blind man said: is the money there?"),
    ('قال: المصاري موجودة، بس أوراق فلينت مش موجودة.', "He said: the money is there, but Flint's papers are not."),
    ('صرخ الأعمى: الولد! الولد أخدها! دوروا عليه!', "The blind man screamed: the boy! The boy took them! Look for him!")),
  P(('صاروا يدوروا بكل مكان، ويكسروا كل إشي.', "They began searching everywhere, breaking everything."),
    ('وأنا تحت الجسر، ما بتنفس.', "And I was under the bridge, not breathing."),
    ('وبعدين سمعنا صفير من فوق التلة. مرة، ومرتين.', "And then we heard a whistle from the top of the hill. Once, and twice."),
    ('قال واحد: هاد إنذار! لازم نهرب!', "One said: that is the alarm! We must run!"),
    ('قال الأعمى: ما بنهرب! الولد قريب! دوروا!', "The blind man said: we do not run! The boy is close! Search!"),
    ('بس الرجال ما سمعوه. ركضوا كل واحد لجهة.', "But the men did not listen to him. They ran, each his own way."),
    ('وضل الأعمى لحاله بنص الطريق، بيضرب بعصايته وبيصرخ عليهم.', "And the blind man was left alone in the middle of the road, striking with his stick and screaming at them.")),
  P(('وبهاللحظة سمعنا خيل جاية من التلة.', "And in that moment we heard horses coming from the hill."),
    ('كانوا جنود الجمارك، إجوا لأنه واحد من القرية بلغهم.', "They were the customs officers, come because someone from the village had reported."),
    ('الأعمى سمع الخيل، وارتبك، وركض للجهة الغلط.', "The blind man heard the horses, panicked, and ran the wrong way."),
    ('وقع تحت أول حصان، وما قام.', "He fell under the first horse, and did not get up."),
    ('طلعت من تحت الجسر، وناديت عالجنود.', "I came out from under the bridge, and called to the officers."),
    ('قلت: الأوراق معي. لازم أوصلها للدكتور ليفزي.', "I said: the papers are with me. I must get them to Doctor Livesey."),
    ('وركبت ورا واحد منهم، وطرنا بالليل.', "And I climbed up behind one of them, and we flew through the night."))]),

 ('The Captain’s Papers', 'أوراق الكابتن', [
  P(('الدكتور ما كان ببيته. كان عند السكوير تريلوني، بالبيت الكبير.', "The doctor was not at home. He was with Squire Trelawney, at the big house."),
    ('السكوير كان زلمة طويل وغني، وصوته عالي، وبيحب المغامرات.', "The squire was a tall, rich man, with a loud voice, who loved adventures."),
    ('لما دخلت، كانوا قاعدين جنب النار، وقدامهم أكل.', "When I came in, they were sitting by the fire, with food before them."),
    ('حكيت لهم كل إشي من الأول.', "I told them everything from the beginning."),
    ('وحطيت الرزمة عالطاولة.', "And I put the bundle on the table.")),
  P(('قال الدكتور: فلينت؟ سمعت عنه؟', "The doctor said: Flint? Have you heard of him?"),
    ('قال السكوير: سمعت عنه؟ كان أخطر قرصان بالدنيا!', "The squire said: heard of him? He was the most dangerous pirate in the world!"),
    ('وكل واحد بيعرف إنه دفن كنز بمكان ما.', "And everyone knows he buried a treasure somewhere."),
    ('إذا هاي الأوراق بتقول وين، يا دكتور، أنا بجهز سفينة بكرا.', "If these papers say where, doctor, I fit out a ship tomorrow."),
    ('قال الدكتور: خلينا نفتحها الأول.', "The doctor said: let us open them first."),
    ('وفتح الرزمة بسكينته.', "And he opened the bundle with his knife.")),
  P(('كان فيها دفتر وورقة مختومة.', "In it there was a notebook and a sealed paper."),
    ('الدفتر كان حسابات: تواريخ ومبالغ وأسماء سفن.', "The notebook was accounts: dates and sums and the names of ships."),
    ('وجنب كل مبلغ، صليب زغير.', "And beside every sum, a small cross."),
    ('قال الدكتور: كل صليب سفينة غرقوها، وكل مبلغ حصته.', "The doctor said: every cross is a ship they sank, and every sum his share."),
    ('وبعدين فتح الورقة المختومة.', "And then he opened the sealed paper."),
    ('كانت خريطة جزيرة.', "It was a map of an island.")),
  P(('الجزيرة طولها تسعة ميل، وفيها تلات تلال.', "The island was nine miles long, with three hills."),
    ('وعليها تلات صلبان بالحبر الأحمر.', "And on it three crosses in red ink."),
    ('وجنب واحد مكتوب: الكنز هون.', "And beside one was written: the treasure here."),
    ('وتحت الخريطة تعليمات بخط فلينت.', "And under the map, directions in Flint's hand."),
    ('قفز السكوير وقال: بكرا بروح على بريستول!', "The squire jumped up and said: tomorrow I go to Bristol!"),
    ('بعشرة أيام بيكون عنا سفينة، وبعدها بنطلع كلنا.', "In ten days we will have a ship, and then we all set out."),
    ('إنت يا دكتور، وأنا، وجيم كولد للسفينة.', "You, doctor, and I, and Jim as cabin boy."),
    ('قال الدكتور: بروح معك. بس بشرط واحد.', "The doctor said: I will go with you. But on one condition."),
    ('ما تحكي لحدا عن الخريطة. ولا كلمة.', "You tell no one about the map. Not a word."),
    ('قال السكوير: أنا؟ أنا قبر!', "The squire said: me? I am a grave!"),
    ('وضحك الدكتور، لأنه كان بيعرفه.', "And the doctor laughed, because he knew him."))]),

 ('To Bristol', 'على بريستول', [
  P(('العشرة أيام صاروا أسابيع، والدكتور راح على لندن.', "The ten days became weeks, and the doctor went to London."),
    ('وأنا ضليت بالبيت الكبير، أحلم بالجزيرة.', "And I stayed at the big house, dreaming of the island."),
    ('كنت أفتح الخريطة كل يوم، وأمشي عليها بإصبعي.', "I opened the map every day, and walked over it with my finger."),
    ('وبعدين إجا مكتوب من السكوير من بريستول.', "And then a letter came from the squire in Bristol.")),
  P(('كتب: السفينة جاهزة! اسمها هيسبانيولا، وهي أحلى سفينة بالميناء.', "He wrote: the ship is ready! Her name is the Hispaniola, and she is the finest ship in the harbour."),
    ('اشتريتها بسعر منيح، والكل بيحكي عن رحلتنا.', "I bought her at a good price, and everyone is talking about our voyage."),
    ('كتب كمان: صعب لاقيت بحارة، بس الحظ ساعدني.', "He also wrote: it was hard to find sailors, but luck helped me."),
    ('قابلت بالميناء واحد إجره وحدة، اسمه جون سيلفر.', "I met a man in the harbour with one leg, named John Silver."),
    ('كان طباخ بحر، وخسر إجره بخدمة الوطن.', "He was a sea cook, and lost his leg in the service of his country."),
    ('وهو اللي جاب لي كل الطاقم، ناس بتعرف البحر.', "And he is the one who found me the whole crew, men who know the sea."),
    ('يلا يا جيم، تعال بسرعة!', "Come, Jim, come quickly!")),
  P(('قريت المكتوب مرتين. إجر وحدة.', "I read the letter twice. One leg."),
    ('تذكرت الكابتن، وخوفه، وأحلامي.', "I remembered the Captain, his fear, and my dreams."),
    ('بس قلت لحالي: في بحارة كتار بإجر وحدة.', "But I said to myself: there are many sailors with one leg."),
    ('والسكوير قال إنه زلمة منيح.', "And the squire said he is a good man."),
    ('تاني يوم رحت وودعت أمي بالنزل.', "The next day I went and said goodbye to my mother at the inn."),
    ('كانت رجعت فتحته، وفيه ولد جديد بيساعدها.', "She had reopened it, and there was a new boy helping her."),
    ('وبكيت، لأني شفت ولد تاني بمكاني.', "And I cried, because I saw another boy in my place.")),
  P(('سافرت بالعربية طول الليل.', "I travelled by coach all night."),
    ('ولما فقت، كنا ببريستول، وشميت ريحة البحر والقطران.', "And when I woke, we were in Bristol, and I smelled the sea and the tar."),
    ('السكوير كان لابس زي كابتن، وواقف قدام فندق عالميناء.', "The squire was dressed like a captain, standing in front of an inn on the harbour."),
    ('قال: وصلت! والدكتور وصل مبارح! بكرا بنبحر!', "He said: you have arrived! And the doctor arrived yesterday! Tomorrow we sail!"),
    ('وأعطاني ورقة، وقال: روح وصلها لجون سيلفر، بدكان المنظار.', "And he gave me a note, and said: go and deliver this to John Silver, at the Spy-glass."))]),

 ('The Sign of the Spy-glass', 'دكان جون سيلفر', [
  P(('دكان المنظار كان مقهى زغير على الميناء.', "The Spy-glass was a small tavern on the harbour."),
    ('وعلى بابه منظار كبير.', "And over its door hung a big spyglass."),
    ('كان مليان بحارة، وصوت وضحك ودخان.', "It was full of sailors, noise and laughter and smoke."),
    ('وقفت عالباب، وخفت أفوت.', "I stood at the door, afraid to go in."),
    ('وبعدين شفته.', "And then I saw him."),
    ('كان طويل وقوي، ووجهه كبير ومبتسم.', "He was tall and strong, with a big smiling face."),
    ('وإجره الشمال مقطوعة من الفخد.', "And his left leg was cut off at the thigh."),
    ('وكان يتحرك على عكازه بين الطاولات زي طير.', "And he moved on his crutch between the tables like a bird.")),
  P(('من أول نظرة، فهمت إنه هاد مش الكابتن.', "From the first look, I understood that this was no Captain."),
    ('الكابتن كان وسخ وحزين ومخيف.', "The Captain had been dirty and sad and frightening."),
    ('وهاد نضيف، وضحوك، وصوته حلو.', "And this one was clean, and cheerful, and his voice was pleasant."),
    ('قلت: إنت السيد سيلفر؟', "I said: are you Mr. Silver?"),
    ('قال: أنا هو، يا ولدي. وإنت لازم تكون جيم، ولد السفينة الجديد!', "He said: I am he, my boy. And you must be Jim, the new cabin boy!"),
    ('ومد إيده الكبيرة وسلم عليّ.', "And he held out his big hand and greeted me.")),
  P(('وبنفس اللحظة، واحد من الزباين قام وركض عالباب.', "And in that same moment, one of the customers got up and ran for the door."),
    ('عرفته من أول نظرة: الكلب الأسود.', "I knew him at first glance: Black Dog."),
    ('صرخت: امسكوه! هاد الكلب الأسود!', "I shouted: catch him! That is Black Dog!"),
    ('صرخ سيلفر: مين؟ الكلب شو؟ هاري، الحقه!', "Silver shouted: who? Black what? Harry, after him!"),
    ('وقام واحد وركض وراه، بس رجع بلا إشي.', "And one man got up and ran after him, but came back with nothing."),
    ('قال سيلفر: راح. بمقهاي! أنا بحكي للسكوير بنفسي.', "Silver said: he is gone. In my tavern! I will tell the squire myself."),
    ('وحكى وحكى عن الكلب الأسود وعن الظلم اللي صار.', "And he talked and talked about Black Dog and the injustice of it.")),
  P(('طلعنا سوا عالميناء، وهو بيحكي لي عن السفن.', "We went out together onto the harbour, and he told me about the ships."),
    ('كان يعرف كل سفينة، وكل علم، وكل حكاية.', "He knew every ship, every flag, every story."),
    ('وكان يضحك، ويضحكني.', "And he laughed, and made me laugh."),
    ('قلت بقلبي: هاد أحسن رفيق بحر بالدنيا.', "I said to myself: this is the best shipmate in the world."),
    ('ولما وصلنا عند السكوير، قال: أنا جيم، شفت شو صار.', "And when we reached the squire, he said: I am Jim, I saw what happened."),
    ('وحكى القصة زي ما صارت، بالضبط.', "And he told the story as it had happened, exactly."),
    ('وقال الدكتور بعد ما طلع: هاد الزلمة معه حق.', "And the doctor said after he left: this man is in the right."),
    ('قال السكوير: أنا حكيت، جون كنز.', "The squire said: I said so, John is a treasure."))]),

 ('Powder and Arms', 'البارود والسلاح', [
  P(('طلعنا عالسفينة بالليل، وكانت فعلاً حلوة.', "We went aboard at night, and she really was beautiful."),
    ('ووقف يستنانا عالسطح كابتن السفينة، اسمه سمولت.', "And waiting for us on deck stood the ship's captain, named Smollett."),
    ('كان زلمة جاد، ووجهه ما بيضحك.', "He was a serious man, whose face did not smile."),
    ('قال: يا سكوير، بدي أحكي معك بالكابينة، وقدام الدكتور.', "He said: squire, I want to speak with you in the cabin, in front of the doctor."),
    ('نزلنا، وقال سمولت: أنا مش مبسوط من هالرحلة.', "We went down, and Smollett said: I am not happy with this voyage.")),
  P(('قال السكوير: وليش؟', "The squire said: and why?"),
    ('قال الكابتن: لأني ما بعرف وين رايحين.', "The captain said: because I do not know where we are going."),
    ('وكل بحار بالميناء بيعرف أكتر مني.', "And every sailor in the harbour knows more than I do."),
    ('بيقولوا إنه في خريطة، وكنز، وإن الخريطة عندك.', "They say there is a map, and a treasure, and that the map is with you."),
    ('احمر وجه السكوير، وقال: أنا ما حكيت لحدا!', "The squire went red, and said: I told no one!"),
    ('قال الدكتور بهدوء: حدا حكى.', "The doctor said calmly: someone talked."),
    ('قال الكابتن: وبعدين، الطاقم. أنا ما اخترتهم.', "The captain said: and then, the crew. I did not choose them."),
    ('ومساعدي الأول، السيد آرو، بيشرب، والبحارة ما بيحترموه.', "And my first mate, Mr. Arrow, drinks, and the sailors do not respect him.")),
  P(('قال السكوير: يعني شو بدك؟', "The squire said: so what do you want?"),
    ('قال الكابتن: تلات أشيا.', "The captain said: three things."),
    ('البارود والسلاح ينحط تحت كابينتنا، مش قدام.', "The powder and arms go under our cabin, not forward."),
    ('رجالك، اللي إنت جبتهم بنفسك، يناموا جنبنا.', "Your men, the ones you brought yourself, sleep beside us."),
    ('والخريطة ما حدا يشوفها، ولا أنا.', "And the map, no one sees it, not even me."),
    ('قال الدكتور: يعني إنت خايف من تمرد.', "The doctor said: you mean you fear a mutiny."),
    ('قال الكابتن: أنا ما بقول إشي. أنا بقول خليكم جاهزين.', "The captain said: I say nothing. I say be ready.")),
  P(('السكوير كان غضبان، بس الدكتور وافق على كل إشي.', "The squire was angry, but the doctor agreed to everything."),
    ('وطلعنا نشتغل كلنا طول الليل، ننقل البراميل والبنادق.', "And we all went up to work through the night, moving the barrels and the guns."),
    ('وجون سيلفر إجا من الميناء، ولما شاف، قال: شو هاد؟', "And John Silver came from the harbour, and when he saw, said: what is this?"),
    ('قال الكابتن: أوامري. روح عالمطبخ.', "The captain said: my orders. Go to the galley."),
    ('قال سيلفر: أمرك يا كابتن. وراح.', "Silver said: aye, captain. And he went."),
    ('وبعدها همس السكوير: ما بحب هالكابتن.', "And afterwards the squire whispered: I do not like this captain."),
    ('والدكتور قال: أنا بحبه، لأنه مش عم يحاول يعجبنا.', "And the doctor said: I like him, because he is not trying to please us."))]),

 ('The Voyage', 'الرحلة', [
  P(('أبحرنا مع الفجر، والميناء كله بيودعنا.', "We sailed at dawn, with the whole harbour seeing us off."),
    ('سيلفر وقف عالسطح وقاد الغنية.', "Silver stood on deck and led the song."),
    ('خمستاشر زلمة على صندوق الميت.', "Fifteen men on the dead man's chest."),
    ('والبحارة كلهم ردوا: يوهوهو وقنينة روم.', "And the sailors all answered: yo ho ho and a bottle of rum."),
    ('وأنا وقفت عالمقدمة، وشفت البر بيبعد.', "And I stood at the bow, and watched the land grow distant."),
    ('وفكرت بالنزل، وبأمي، وبالكابتن الميت اللي غنى نفس الغنية.', "And I thought of the inn, and my mother, and the dead Captain who had sung the same song.")),
  P(('الرحلة كانت طويلة، بس ما صار فيها إشي كبير، إلا إشي واحد.', "The voyage was long, but nothing much happened, except one thing."),
    ('السيد آرو، المساعد الأول، كان دايماً سكران.', "Mr. Arrow, the first mate, was always drunk."),
    ('ما حدا عرف من وين بيجيب الشراب.', "No one knew where he got the drink."),
    ('لأنه الكابتن سكر كل الشراب.', "Because the captain had locked all of it away."),
    ('وبليلة عاصفة، اختفى.', "And one stormy night, he disappeared."),
    ('قال الكابتن: وقع بالبحر. ما حدا رح يفتقده.', "The captain said: he fell into the sea. No one will miss him."),
    ('وصار البحار الكبير، جوب أندرسون، مكانه.', "And the boatswain, Job Anderson, took his place.")),
  P(('أما سيلفر، فكان ملك السفينة.', "As for Silver, he was king of the ship."),
    ('كان يطبخ، ويغني، ويحكي، والبحارة يحبوه ويسمعوا كلامه.', "He cooked, sang, talked, and the sailors loved him and heeded his word."),
    ('وكان عنده ببغا، اسمه الكابتن فلينت.', "And he had a parrot, named Captain Flint."),
    ('كان يصرخ: قطع الذهب، قطع الذهب!', "It would screech: pieces of eight, pieces of eight!"),
    ('قال لي: هاد الطير عمره ميتين سنة، وشاف كل شر بالدنيا.', "He told me: this bird is two hundred years old, and has seen every evil in the world."),
    ('وأنا كنت أقعد بالمطبخ ساعات، وهو يحكي لي عن البحار.', "And I would sit in the galley for hours, while he told me about the seas."),
    ('كان يقول: إنت ذكي يا جيم. إنت بتشبهني لما كنت زغير.', "He would say: you are clever, Jim. You are like me when I was young."),
    ('وكنت أفرح.', "And I was glad.")),
  P(('الكابتن سمولت كان ساكت، وما بيحب الفوضى.', "Captain Smollett was quiet, and did not like disorder."),
    ('والسكوير كان يعطي البحارة تفاح وشراب بكل مناسبة.', "And the squire gave the sailors apples and drink at every occasion."),
    ('كان في برميل تفاح مفتوح عالسطح، لمين بده.', "There was an open barrel of apples on deck, for anyone who wanted."),
    ('وبليلة، قبل ما نوصل بيوم، رحت آخد تفاحة.', "And one night, a day before we arrived, I went to take an apple."),
    ('البرميل كان تقريباً فاضي، فنزلت جواته لأوصل لآخر تفاحة.', "The barrel was almost empty, so I climbed inside to reach the last apple."),
    ('وقعدت جوا بالعتمة، ونمت شوي.', "And I sat inside in the dark, and dozed a little."),
    ('وفقت على صوت. حدا قعد جنب البرميل وبلش يحكي.', "And I woke to a voice. Someone had sat down beside the barrel and begun to talk."))]),

 ('What I Heard in the Apple Barrel', 'اللي سمعته بالبرميل', [
  P(('كان صوت سيلفر.', "It was Silver's voice."),
    ('بس مش الصوت اللي بعرفه. صوت بارد، بلا ضحك.', "But not the voice I knew. A cold voice, without laughter."),
    ('كان بيحكي مع بحار شاب، اسمه دك.', "He was talking with a young sailor, named Dick."),
    ('قال سيلفر: أنا كنت مع فلينت. أنا كنت مسؤول البارود عنده.', "Silver said: I was with Flint. I was his powder man."),
    ('والأعمى بيو كان معنا، وبيلي بونز.', "And blind Pew was with us, and Billy Bones."),
    ('كلهم ماتوا فقرا، وأنا معي مصاري بالبنك.', "They all died poor, and I have money in the bank."),
    ('لأني ذكي.', "Because I am clever.")),
  P(('قال دك: وأنا؟ شو بصير معي؟', "Dick said: and me? What becomes of me?"),
    ('قال سيلفر: إنت معنا. سيد الحظ، هيك بنسمي حالنا.', "Silver said: you are with us. Gentlemen of fortune, that is what we call ourselves."),
    ('ولما نوصل عالجزيرة، ونطلع الكنز، كل واحد بياخد حصته.', "And when we reach the island, and dig up the treasure, everyone takes his share."),
    ('قال دك: والكابتن؟ والسكوير؟ والدكتور؟', "Dick said: and the captain? And the squire? And the doctor?"),
    ('قال سيلفر: خليهم يوصلونا. بحاجتهم يقودوا السفينة.', "Silver said: let them get us there. We need them to sail the ship."),
    ('وبعدين، لما يصير الكنز عالسفينة، بنشوف.', "And then, when the treasure is on the ship, we will see."),
    ('قال دك: يعني بنقتلهم؟', "Dick said: you mean we kill them?"),
    ('قال سيلفر: الميتين ما بيعضوا.', "Silver said: dead men do not bite.")),
  P(('كنت جوا البرميل، وما بتنفس، وقلبي بيدق زي طبل.', "I was inside the barrel, not breathing, my heart beating like a drum."),
    ('هاد الزلمة اللي كنت بحبه.', "This was the man I had loved."),
    ('هاد اللي كان يقول إني بشبهه.', "The one who said I was like him."),
    ('وإجا واحد تالت، إسرائيل هاندز، الملاح.', "And a third came, Israel Hands, the coxswain."),
    ('قال هاندز: يا جون، لحد إيمتى بدنا نستنى؟ أنا زهقت من الكابتن.', "Hands said: John, how long do we wait? I am sick of the captain."),
    ('قال سيلفر: لحد ما أقول أنا. آخر لحظة ممكنة.', "Silver said: until I say. The last moment possible."),
    ('قال هاندز: والولد؟ جيم؟', "Hands said: and the boy? Jim?"),
    ('قال سيلفر: الولد بحبه. بس لما يوصل وقته، بياخد حصته زي الباقي.', "Silver said: I like the boy. But when his time comes, he takes his share like the rest.")),
  P(('قال سيلفر: يلا يا دك، جيب لي تفاحة من البرميل.', "Silver said: come on, Dick, get me an apple from the barrel."),
    ('وأنا قلت: خلص، انتهيت.', "And I said: it is over, I am finished."),
    ('بس هاندز قال: تفاح؟ خلينا نشرب روم.', "But Hands said: apples? Let us drink rum."),
    ('وراح دك يجيب الرم، وقعدوا يشربوا.', "And Dick went to fetch rum, and they sat drinking."),
    ('وبنفس اللحظة، صرخ واحد من فوق: أرض! أرض!', "And in that same moment, someone shouted from above: land! Land!"),
    ('وركض الكل عالمقدمة، وأنا طلعت من البرميل واختلطت فيهم.', "And everyone ran to the bow, and I climbed out of the barrel and mixed in among them."),
    ('وشفت الجزيرة، أول مرة، بالقمر.', "And I saw the island, for the first time, in the moonlight."),
    ('تلات تلال، وضباب، وشجر أسود.', "Three hills, and mist, and black trees."))]),

 ('Council of War', 'مجلس الحرب', [
  P(('الكابتن سمولت فتح الخريطة، بس نسخة بلا الصلبان الحمر.', "Captain Smollett opened the map, but a copy without the red crosses."),
    ('وسأل سيلفر: بتعرف هالجزيرة؟', "And he asked Silver: do you know this island?"),
    ('قال سيلفر: أكيد، يا كابتن. مرقت عليها مرة، مع سفينة تجار.', "Silver said: certainly, captain. I passed it once, on a merchant ship."),
    ('وحكى عن المرسى، وعن المي الحلوة، وعن الطقس.', "And he told about the anchorage, the fresh water, the weather."),
    ('وكان صوته دافي وضحوك، زي دايماً.', "And his voice was warm and laughing, as always."),
    ('وأنا واقف جنبه، وبدي أهرب من ريحة الكذب.', "And I stood beside him, wanting to flee the smell of the lie.")),
  P(('لما فضي السطح، رحت للدكتور.', "When the deck emptied, I went to the doctor."),
    ('قلت له: لازم أحكي معك بالكابينة.', "I said to him: I must speak with you in the cabin."),
    ('نزلنا، والسكوير والكابتن معنا.', "We went down, with the squire and the captain."),
    ('وحكيت كل كلمة سمعتها بالبرميل.', "And I told every word I had heard in the barrel."),
    ('لما خلصت، ما حدا حكى.', "When I finished, no one spoke."),
    ('وبعدين قال الكابتن للسكوير: كنت معك حق. أنا كنت غلطان.', "And then the captain said to the squire: you were right. I was wrong."),
    ('قال السكوير: لا. إنت اللي كنت معك حق، وأنا الغبي.', "The squire said: no. You were the one who was right, and I the fool."),
    ('وهاد الطباخ، أنا اللي جبته.', "And this cook, I am the one who brought him.")),
  P(('قال الكابتن: خلينا نعد.', "The captain said: let us count."),
    ('إحنا سبعة: تلاتة منكم، وأنا، وتلاتة من رجال السكوير.', "We are seven: three of you, myself, and three of the squire's men."),
    ('وهم تسعتعشر.', "And they are nineteen."),
    ('بس مش كلهم معه أكيد. في ناس بيتترددوا.', "But surely not all are with him. Some are hesitating."),
    ('قال الدكتور: وشو نعمل؟', "The doctor said: and what do we do?"),
    ('قال الكابتن: منكمل زي ما إحنا.', "The captain said: we go on as we are."),
    ('إذا رجعنا هلق، بيهجموا فوراً. إذا كملنا، بيستنوا الكنز.', "If we turn back now, they attack at once. If we go on, they wait for the treasure."),
    ('والوقت معنا.', "And time is on our side.")),
  P(('قال الدكتور: وجيم؟', "The doctor said: and Jim?"),
    ('قال الكابتن: جيم أهم واحد فينا.', "The captain said: Jim is the most important one among us."),
    ('البحارة ما بيهتموا فيه، وهو بيسمع كل إشي.', "The sailors pay him no attention, and he hears everything."),
    ('يا جيم، خليك مع سيلفر زي قبل، وعينك مفتوحة.', "Jim, stay with Silver as before, and keep your eyes open."),
    ('قلت: أمرك يا كابتن.', "I said: aye, captain."),
    ('بس بقلبي كنت خايف كتير.', "But in my heart I was very afraid."),
    ('سبعة ضد تسعتعشر، وأنا واحد من السبعة.', "Seven against nineteen, and I was one of the seven."))]),

 ('The Island', 'الجزيرة', [
  P(('بالصبح، وصلنا قدام الجزيرة، وكانت غير اللي بالليل.', "In the morning, we lay off the island, and it was different from the night."),
    ('شجر رمادي، وصخر أصفر، وتلال شكلها غريب.', "Grey trees, yellow rock, and hills of a strange shape."),
    ('أعلى تلة كانت زي منظار، وعشان هيك اسمها تلة المنظار.', "The highest hill was like a spyglass, which is why its name was Spy-glass Hill."),
    ('ما كان في ريح، والسفينة كانت واقفة، والشمس حامية.', "There was no wind, the ship lay still, and the sun was hot."),
    ('ومن أول لحظة، كرهت الجزيرة.', "And from the first moment, I hated the island.")),
  P(('البحارة صاروا عصبيين.', "The sailors grew edgy."),
    ('ما كانوا يسمعوا الأوامر.', "They did not obey orders."),
    ('كانوا يحكوا بصوت عالي، ويتطلعوا عالبر.', "They talked loudly, and looked at the shore."),
    ('الكابتن شاف الخطر، وقال للسكوير:', "The captain saw the danger, and said to the squire:"),
    ('إذا ضلوا عالسفينة، بيتمردوا اليوم.', "If they stay on the ship, they mutiny today."),
    ('وقرر يخليهم ينزلوا عالبر بعد الظهر.', "And he decided to let them go ashore in the afternoon."),
    ('قال: خليهم يركضوا بالجزيرة زي الأولاد. وسيلفر بيروح معهم عشان يهديهم.', "He said: let them run about the island like children. And Silver goes with them to keep them calm."),
    ('لأنه سيلفر كمان ما بده التمرد يصير قبل الكنز.', "Because Silver too did not want the mutiny before the treasure.")),
  P(('نزل تلاتعشر بحار بمركبين، وسيلفر معهم.', "Thirteen sailors went down in two boats, and Silver with them."),
    ('وضل ستة عالسفينة، كلهم من رجاله.', "And six stayed on the ship, all of them his men."),
    ('وأنا، ما بعرف ليش، عملت أغبى إشي بحياتي.', "And I, I do not know why, did the stupidest thing of my life."),
    ('نطيت بآخر مركب، بلا ما حدا يشوفني.', "I jumped into the last boat, without anyone seeing me."),
    ('قلت: بدي أشوف الجزيرة.', "I said: I want to see the island."),
    ('لما وصلنا، صرخ سيلفر: جيم! جيم!', "When we landed, Silver shouted: Jim! Jim!"),
    ('بس أنا كنت قفزت ودخلت الشجر وركضت.', "But I had jumped out and gone into the trees and run."))]),

 ('Ashore', 'عالشط', [
  P(('ركضت لحد ما ما عدت أسمع صوتهم.', "I ran until I could no longer hear their voices."),
    ('ووقفت بغابة، ولأول مرة بحياتي، كنت لحالي بمكان جديد.', "And I stopped in a wood, and for the first time in my life, I was alone in a new place."),
    ('شجر ما بعرفه، وطيور ما بعرفها، وحية زغيرة رفعت راسها.', "Trees I did not know, birds I did not know, and a small snake raised its head."),
    ('وبعدين وصلت على مستنقع، ومن ورا الشجر، سمعت أصوات.', "And then I reached a marsh, and from beyond the trees, I heard voices."),
    ('صوت سيلفر، وصوت تاني، لبحار اسمه توم.', "Silver's voice, and another, of a sailor named Tom."),
    ('زحفت وقربت، واستخبيت ورا شجرة.', "I crawled closer, and hid behind a tree.")),
  P(('كان سيلفر بيحكي بصوته الدافي.', "Silver was speaking in his warm voice."),
    ('يا توم، إنت زلمة منيح، وأنا بحبك.', "Tom, you are a good man, and I like you."),
    ('تعال معنا. الباقي كلهم معنا.', "Come with us. All the rest are with us."),
    ('قال توم: يا جون، أنا بحبك كمان، بس أنا مش خاين.', "Tom said: John, I like you too, but I am no traitor."),
    ('أنا بموت قبل ما أخون الكابتن.', "I die before I betray the captain."),
    ('وبنفس اللحظة، من بعيد، سمعنا صرخة.', "And in that same moment, from afar, we heard a scream."),
    ('صرخة واحدة، طويلة، وبعدين ولا إشي.', "One scream, long, and then nothing."),
    ('قال توم: شو هاد؟', "Tom said: what was that?"),
    ('قال سيلفر بهدوء: هاد؟ هاد آلان، على ما أظن.', "Silver said calmly: that? That is Alan, I suppose."),
    ('آلان كان بحار تاني، رفض ينضم لهم.', "Alan was another sailor, who had refused to join them.")),
  P(('توم فهم.', "Tom understood."),
    ('قال: آلان! الله يرحمه. وإنت، يا جون سيلفر، إنت شيطان.', "He said: Alan! God rest him. And you, John Silver, you are a devil."),
    ('اقتلني إذا بتقدر. أنا رايح.', "Kill me if you can. I am going."),
    ('ودار ظهره ومشى.', "And he turned his back and walked away."),
    ('سيلفر مسك عكازه، ورماه بكل قوته.', "Silver seized his crutch, and threw it with all his strength."),
    ('ضرب توم بظهره، ووقع.', "It struck Tom in the back, and he fell."),
    ('وسيلفر نط عليه على إجر وحدة، زي القرد، وطعنه مرتين.', "And Silver leapt on him on one leg, like a monkey, and stabbed him twice.")),
  P(('ما عرفت كيف ما صرخت.', "I do not know how I did not scream."),
    ('الدنيا لفت حواليّ، والشجر صار يدور.', "The world spun around me, and the trees began to turn."),
    ('ولما رجعت أشوف، كان سيلفر واقف، بيمسح سكينته على العشب.', "And when I could see again, Silver was standing, wiping his knife on the grass."),
    ('وبعدين صفر بصفارة، وعرفت إنه بينادي الباقي.', "And then he blew a whistle, and I knew he was calling the others."),
    ('ركضت. ركضت بلا ما أعرف لوين.', "I ran. I ran without knowing where."),
    ('وكل ما أركض، أفكر: أنا ميت. سيلفر بيعرف إني سمعت.', "And as I ran I thought: I am dead. Silver knows I heard."),
    ('وفجأة، وقف قدامي إشي من ورا شجرة.', "And suddenly, something stepped in front of me from behind a tree."),
    ('مش زلمة ومش حيوان. إشي بيتحرك بسرعة، وبيختفي.', "Not a man and not an animal. Something moving fast, and vanishing."))]),

 ('The Man of the Island', 'رجل الجزيرة', [
  P(('وقفت مكاني، وما عرفت أركض لوين.', "I stopped where I was, and did not know which way to run."),
    ('ورايي القتلة، وقدامي هالإشي.', "Behind me the murderers, and before me this thing."),
    ('وبعدين طلع من ورا الشجرة، ونزل على ركبه، ومد إيديه.', "And then it came out from behind the tree, and dropped to its knees, and held out its hands."),
    ('كان زلمة.', "It was a man."),
    ('شعره طويل وأسود، وجلده محروق من الشمس.', "His hair was long and black, his skin burned by the sun."),
    ('وتيابه قطع قماش مربوطة.', "And his clothes were rags tied together."),
    ('وعيونه بتلمع، زي واحد ما شاف بني آدم من سنين.', "And his eyes shone, like someone who had not seen a human being in years.")),
  P(('قال: مين إنت؟', "He said: who are you?"),
    ('قلت: جيم.', "I said: Jim."),
    ('قال: جيم، جيم. أنا بن غون. أنا بن غون المسكين.', "He said: Jim, Jim. I am Ben Gunn. I am poor Ben Gunn."),
    ('صار لي تلات سنين ما حكيت مع حدا.', "It has been three years since I spoke with anyone."),
    ('قلت: تلات سنين؟ غرقت سفينتك؟', "I said: three years? Was your ship wrecked?"),
    ('قال: لا. تركوني هون. هيك بيعملوا بالخاين.', "He said: no. They left me here. That is what they do with a traitor."),
    ('وحكى عن الجبنة. قال: بتحلم بالجبنة؟ أنا بحلم فيها كل ليلة.', "And he talked about cheese. He said: do you dream of cheese? I dream of it every night.")),
  P(('وبعدين سألني: هاي سفينة فلينت؟', "And then he asked me: is that Flint's ship?"),
    ('قلت: فلينت ميت. بس رجاله معنا عالسفينة.', "I said: Flint is dead. But his men are with us on the ship."),
    ('قال: في واحد بإجر وحدة؟', "He said: is there one with one leg?"),
    ('قلت: سيلفر.', "I said: Silver."),
    ('ارتجف بن غون كله، ومسك إيدي.', "Ben Gunn shook all over, and grabbed my hand."),
    ('قال: إذا سيلفر بعتك، أنا ميت. بس إنت مش من رجاله، صح؟', "He said: if Silver sent you, I am dead. But you are not one of his men, right?"),
    ('وحكيت له كل القصة.', "And I told him the whole story."),
    ('سمع، وبعدين ضحك، وقال: أنا كنت مع فلينت لما دفن الكنز.', "He listened, and then laughed, and said: I was with Flint when he buried the treasure.")),
  P(('قال: كنت بسفينة تانية، ورجعت أدور على الكنز مع رجالي.', "He said: I was on another ship, and came back to look for the treasure with my men."),
    ('اتناعشر يوم دورنا، وما لقينا. فزعلوا مني، وتركوني.', "Twelve days we searched, and did not find. So they turned on me, and left me."),
    ('بس أنا بن غون، وأنا ذكي.', "But I am Ben Gunn, and I am clever."),
    ('وغمز لي، وقال: روح قول للسكوير: بن غون بده يرجع على بيته.', "And he winked at me, and said: go and tell the squire: Ben Gunn wants to go home."),
    ('وبده حصة، وعنده مركب زغير عمله بإيده، تحت الصخرة البيضا.', "And he wants a share, and he has a little boat he made with his own hands, under the white rock."),
    ('وبهاللحظة، سمعنا صوت مدفع من السفينة.', "And in that moment, we heard a cannon from the ship."),
    ('قال بن غون: بلشت الحرب.', "Ben Gunn said: the war has begun."))]),

 ('The Ship Abandoned', 'السفينة المتروكة', [
  P(('هاد الجزء من القصة حكاه لي الدكتور بعدين.', "This part of the story the doctor told me later."),
    ('لأني ما كنت موجود.', "Because I was not there."),
    ('لما نزل البحارة عالجزيرة، قعدوا التلاتة يفكروا.', "When the sailors went ashore, the three of them sat thinking."),
    ('الدكتور، والسكوير، والكابتن.', "The doctor, the squire, and the captain."),
    ('ستة من رجال سيلفر عالسفينة، وإحنا ستة ومعنا الأسلحة.', "Six of Silver's men on the ship, and we six with the weapons."),
    ('قال الدكتور: بدي أنزل عالبر وأشوف الخريطة على الطبيعة.', "The doctor said: I want to go ashore and see the map against the ground."),
    ('لأنه عالخريطة كان في قلعة خشب مرسومة، قريبة من المي.', "Because on the map there was a wooden stockade drawn, close to the water.")),
  P(('نزل الدكتور مع هنتر، واحد من رجال السكوير.', "The doctor went down with Hunter, one of the squire's men."),
    ('ولقوا القلعة: بيت خشب قوي، حواليه سور من جذوع.', "And they found the stockade: a strong log house, a fence of trunks around it."),
    ('وجنبه نبع مي.', "And a spring beside it."),
    ('قال الدكتور: هون منقدر نصمد شهور.', "The doctor said: here we could hold out for months."),
    ('وبنفس اللحظة سمعوا الصرخة من بعيد. صرخة آلان.', "And in that same moment they heard the scream from afar. Alan's scream."),
    ('قال الدكتور: خلص. رجعنا عالسفينة. جيم بالجزيرة، والله يساعده.', "The doctor said: that is it. Back to the ship. Jim is on the island, and God help him.")),
  P(('رجعوا عالسفينة، وقرروا: بنترك السفينة، وبنروح عالقلعة.', "They went back to the ship, and decided: we abandon the ship, and go to the stockade."),
    ('لأنه عالسفينة، سيلفر رح يرجع بتلاتعشر زلمة، وإحنا بنخسر.', "Because on the ship, Silver would return with thirteen men, and we would lose."),
    ('حملوا المركب بأكل وبارود وبنادق، وراحوا مرة، ورجعوا مرة.', "They loaded the boat with food and powder and guns, and went once, and came back once."),
    ('والستة عالسفينة يتفرجوا، وما بيعرفوا شو يعملوا.', "And the six on the ship watched, not knowing what to do."),
    ('وبآخر رحلة، طلع الكابتن ووقف على السطح.', "And on the last trip, the captain came up and stood on the deck."),
    ('قال: يا أبراهام غراي، أنا بعرف إنك زلمة منيح. أنا بعطيك تلاتين ثانية.', "He said: Abraham Gray, I know you are a good man. I give you thirty seconds."),
    ('وبعد لحظة صمت، صار صوت خناقة.', "And after a moment's silence, there was the sound of a fight."),
    ('وطلع غراي راكض، ووجهه مجروح.', "And Gray came running, his face cut."),
    ('قال: أنا معك يا كابتن.', "He said: I am with you, captain.")),
  P(('نزلوا بالمركب، ستة رجال وأكل وبارود.', "They went down into the boat, six men and food and powder."),
    ('وكان المركب تقيل، والمي وصلت لحافته.', "And the boat was heavy, and the water reached its edge."),
    ('والجزر كان بيسحبهم بعيد عن القلعة.', "And the ebb was pulling them away from the stockade."),
    ('وبعدين قال الكابتن: المدفع.', "And then the captain said: the cannon."),
    ('عالسفينة كان في مدفع، ورجال سيلفر بيلفوه باتجاههم.', "On the ship there was a cannon, and Silver's men were turning it toward them."),
    ('السكوير رفع بندقيته، وأطلق على اللي بيحشي المدفع.', "The squire raised his gun, and fired at the one loading the cannon."),
    ('وأصابه.', "And he hit him."),
    ('بس المدفع ضرب.', "But the cannon fired."),
    ('القذيفة مرقت فوق روسهم، والموج قلب المركب.', "The ball passed over their heads, and the wave overturned the boat."),
    ('وطلعوا عالشط، مبلولين، وبلا نص الأكل، وبلا نص البارود.', "And they came up on the shore, soaked, without half the food, and without half the powder."))]),

 ('The Last Boat', 'آخر مركب', [
  P(('طلعوا من المي وركضوا للقلعة، والصوت من ورا الشجر بيقرب.', "They came out of the water and ran for the stockade, with the noise behind the trees growing nearer."),
    ('رجال سيلفر كانوا سمعوا المدفع، وجايين.', "Silver's men had heard the cannon, and were coming."),
    ('قال الكابتن: يا سكوير، إنت أحسن رامي. خليك بالآخر.', "The captain said: squire, you are the best shot. Stay at the rear."),
    ('ووصلوا عالسور، والقتلة طلعوا من الشجر.', "And they reached the fence, and the killers came out of the trees."),
    ('كانوا سبعة، وجوب أندرسون قدامهم.', "They were seven, with Job Anderson at their head.")),
  P(('صار إطلاق نار من الجهتين.', "There was firing from both sides."),
    ('واحد من القتلة وقع، والباقي هربوا للشجر.', "One of the killers fell, and the rest fled into the trees."),
    ('بس قبل ما يهربوا، رصاصة جات من ورا.', "But before they fled, a bullet came from behind."),
    ('وأصابت توم ريدروث، خادم السكوير القديم.', "And it struck Tom Redruth, the squire's old servant."),
    ('حملوه لجوا القلعة، وكان بيعرف إنه رح يموت.', "They carried him inside the stockade, and he knew he was going to die."),
    ('قال للسكوير: أنا رايح يا سيدي. سامحني إذا غلطت بإشي.', "He said to the squire: I am going, sir. Forgive me if I ever did wrong."),
    ('والسكوير بكى، وباس إيده.', "And the squire wept, and kissed his hand."),
    ('ومات ريدروث بعد شوي.', "And Redruth died a little later.")),
  P(('الكابتن طلع من جيبه علم إنجليزي، وعلقه فوق القلعة.', "The captain took an English flag from his pocket, and hung it over the stockade."),
    ('قال: هاي قلعتنا، وهاد علمنا.', "He said: this is our fort, and this is our flag."),
    ('وبعدين قعد يعد.', "And then he sat counting."),
    ('أكل لعشر أيام، ومي من النبع، وبارود لمعركة أو معركتين.', "Food for ten days, water from the spring, powder for a battle or two."),
    ('وقال: جيم ضاع. يمكن مات. بس يمكن لا.', "And he said: Jim is lost. Perhaps dead. But perhaps not."),
    ('وبعدين بدأ المدفع من السفينة يضرب عالقلعة.', "And then the cannon from the ship began firing at the stockade."),
    ('القذايف كانت تمرق فوق، وتوقع بالشجر، وما تعمل إشي.', "The balls passed over, fell into the trees, and did nothing."),
    ('قال الكابتن: خليهم يضيعوا بارودهم.', "The captain said: let them waste their powder.")),
  P(('وبالمسا، لما هدي المدفع، سمعوا صوت من برا السور.', "And in the evening, when the cannon quietened, they heard a voice from outside the fence."),
    ('صوت بيقول: دكتور! سكوير! هاد أنا! جيم!', "A voice saying: doctor! Squire! It is me! Jim!"),
    ('ركض الدكتور للباب، وأنا نطيت من فوق السور.', "The doctor ran to the door, and I jumped over the fence."),
    ('وكنت حي، وكنت جعان، وكنت أهم إشي: معي خبر.', "And I was alive, and hungry, and most important: I had news."),
    ('قلت: في زلمة عالجزيرة اسمه بن غون.', "I said: there is a man on the island named Ben Gunn."),
    ('قال الكابتن: كمل الأكل الأول، وبعدين احكي.', "The captain said: finish eating first, and then talk."),
    ('وهيك خلص أول يوم عالجزيرة.', "And so ended the first day on the island."))]),

 ('The First Day’s Fighting', 'أول يوم قتال', [
  P(('أكلت زي ما ما أكلت بحياتي، وبعدين حكيت.', "I ate as I had never eaten in my life, and then I talked."),
    ('حكيت عن سيلفر وتوم، وعن بن غون، ومركبه تحت الصخرة البيضا.', "I told about Silver and Tom, about Ben Gunn, and his boat under the white rock."),
    ('قال الدكتور: بن غون؟ ما بعرف إذا مجنون ولا عاقل.', "The doctor said: Ben Gunn? I do not know whether he is mad or sane."),
    ('قال الكابتن: زلمة صار له تلات سنين لحاله، بيكون الاتنين.', "The captain said: a man three years alone will be both."),
    ('وقال السكوير: بس إذا عنده مركب، فهاد أهم من الكنز.', "And the squire said: but if he has a boat, that matters more than the treasure.")),
  P(('الليل كان طويل.', "The night was long."),
    ('الكابتن قسمنا نوبات: اتنين بيراقبوا، والباقي بيناموا.', "The captain divided us into watches: two on guard, the rest asleep."),
    ('وأنا ما قدرت أنام.', "And I could not sleep."),
    ('كل ما أسكر عيني، أشوف سيلفر بيمسح سكينته.', "Every time I closed my eyes, I saw Silver wiping his knife."),
    ('من بعيد، كنا نسمع القتلة بيغنوا حول النار.', "From afar, we could hear the killers singing around their fire."),
    ('صوتهم كان سكران، والغنية نفسها: يوهوهو وقنينة روم.', "Their voices were drunk, and the song the same: yo ho ho and a bottle of rum."),
    ('قال غراي: هاد الرم من السفينة. رح يشربوا لحد الصبح.', "Gray said: that is the rum from the ship. They will drink till morning."),
    ('قال الكابتن: أحسن. السكران ما بيصيب.', "The captain said: better. A drunk man cannot aim.")),
  P(('مع الفجر، صار أول قتال.', "With the dawn came the first fighting."),
    ('تلاتة من رجال سيلفر قربوا من السور، يمكن يجربوا حظهم.', "Three of Silver's men came near the fence, perhaps to try their luck."),
    ('السكوير وغراي أطلقوا مرة وحدة.', "The squire and Gray fired once."),
    ('واحد وقع، والتاني اتنين ركضوا للشجر وهم بيصرخوا.', "One fell, and the other two ran for the trees, shouting."),
    ('واللي وقع، ما قام.', "And the one who fell did not get up."),
    ('قال الكابتن: صاروا خمستعشر.', "The captain said: they are fifteen now."),
    ('وقال الدكتور: وإحنا لسا سبعة، بجيم.', "And the doctor said: and we are still seven, with Jim.")),
  P(('وبعدين رجع الهدوء، والشمس طلعت، والجزيرة صارت حامية.', "And then the quiet returned, the sun rose, and the island grew hot."),
    ('قعدنا كلنا جوا القلعة، والذباب حوالينا.', "We all sat inside the stockade, with the flies around us."),
    ('والريحة من الجثة برا.', "And the smell from the body outside."),
    ('قال السكوير: كم يوم بنقدر نضل هيك؟', "The squire said: how many days can we stay like this?"),
    ('قال الكابتن: عشرة. وبعدين بنموت من الجوع، ولا بنطلع نقاتل.', "The captain said: ten. And then we die of hunger, or go out and fight."),
    ('قال الدكتور: أو بيوصلنا بن غون.', "The doctor said: or Ben Gunn reaches us."),
    ('وطلع الدكتور من القلعة، ببندقيته، وراح بالشجر.', "And the doctor left the stockade, with his gun, and went into the trees."),
    ('قال: رايح أدور على مجنون.', "He said: I am going to look for a madman."))]),

 ('The Garrison in the Stockade', 'الحامية بالقلعة', [
  P(('صرنا ستة بالقلعة، والشغل كتير.', "We were six in the stockade, and the work was much."),
    ('الكابتن حط لكل واحد شغلة.', "The captain gave everyone a job."),
    ('هنتر وجويس بيجيبوا حطب، وغراي بيراقب.', "Hunter and Joyce fetched wood, and Gray kept watch."),
    ('والسكوير بينضف البنادق.', "And the squire cleaned the guns."),
    ('وأنا بطبخ، وبجيب مي من النبع.', "And I cooked, and fetched water from the spring."),
    ('وكل ساعة الكابتن يطلع ويتطلع عالسفينة بالمنظار.', "And every hour the captain went out and looked at the ship through the spyglass."),
    ('السفينة كانت مرسية مكانها، وعليها علم أسود.', "The ship lay at anchor where she was, with a black flag flying.")),
  P(('قال الكابتن: راح أحسن مركب ركبته بحياتي.', "The captain said: there goes the best ship I ever sailed."),
    ('وقال السكوير: بنرجعها.', "And the squire said: we will get her back."),
    ('قال الكابتن: كيف؟ إحنا ستة وهم خمستعشر.', "The captain said: how? We are six and they are fifteen."),
    ('وأنا سمعت، وفكرت بمركب بن غون تحت الصخرة البيضا.', "And I heard, and thought of Ben Gunn's boat under the white rock."),
    ('وما حكيت.', "And I said nothing.")),
  P(('بعد الظهر، رجع الدكتور، ووجهه مبسوط.', "In the afternoon, the doctor returned, his face pleased."),
    ('قال: لقيت بن غون. قعدنا سوا ساعة.', "He said: I found Ben Gunn. We sat together for an hour."),
    ('هو مجنون، وهو عاقل، وهو رح يساعدنا.', "He is mad, and he is sane, and he will help us."),
    ('قال السكوير: وبده حصة؟', "The squire said: and he wants a share?"),
    ('قال الدكتور: بده ألف جنيه، وطريق عالبيت.', "The doctor said: he wants a thousand pounds, and a way home."),
    ('قال السكوير: بيصير.', "The squire said: it can be done."),
    ('وقال الدكتور: بس ما حكى لي وين مركبه. قال: للولد بس.', "And the doctor said: but he did not tell me where his boat is. He said: only for the boy.")),
  P(('وبعد شوي، صار صوت من برا السور.', "And a little later, there was a sound from outside the fence."),
    ('صوت سيلفر: يا اللي جوا! هدنة! هدنة!', "Silver's voice: you inside! A truce! A truce!"),
    ('وشفناه، واقف عند الشجر، وبإيده قماش أبيض على عصا.', "And we saw him, standing by the trees, with a white cloth on a stick in his hand."),
    ('وجنبه واحد تاني، رافع إيديه.', "And beside him another man, his hands raised."),
    ('قال الكابتن: كلكم لجوا. ما حدا يطلع.', "The captain said: everyone inside. No one goes out."),
    ('وصرخ: مين إنت وشو بدك؟', "And he shouted: who are you and what do you want?"),
    ('رد سيلفر: الكابتن سيلفر، يا سيدي، جاي يعرض شروط.', "Silver answered: Captain Silver, sir, come to offer terms."),
    ('قال الكابتن سمولت: الكابتن سيلفر؟ ما بعرف واحد هيك.', "Captain Smollett said: Captain Silver? I know no one by that name."),
    ('وضحك سيلفر، وقال: الرجال اختاروني. بعد ما تركتنا إنت.', "And Silver laughed, and said: the men chose me. After you deserted us."))]),

 ('Silver’s Embassy', 'سيلفر بيجي يحكي', [
  P(('قال الكابتن: إذا بدك تحكي، تعال. بس لحالك.', "The captain said: if you want to talk, come. But alone."),
    ('وإجا سيلفر، على عكازه، وتسلق السور بصعوبة.', "And Silver came, on his crutch, and climbed the fence with difficulty."),
    ('ما حدا ساعده.', "No one helped him."),
    ('وقعد على الرمل قدام الباب، والكابتن وقف قدامه.', "And he sat on the sand before the door, and the captain stood over him."),
    ('قال سيلفر: يا كابتن، إنت عملت منيح مبارح. واحد من رجالي انقتل بالليل، وهو نايم.', "Silver said: captain, you did well yesterday. One of my men was killed in the night, in his sleep."),
    ('قال الكابتن: أنا ما بعت حدا.', "The captain said: I sent no one."),
    ('وأنا فهمت: بن غون.', "And I understood: Ben Gunn.")),
  P(('قال سيلفر: خلينا نحكي بالمفيد.', "Silver said: let us talk sense."),
    ('إحنا بدنا الكنز، وإنتو بدكم حياتكم.', "We want the treasure, and you want your lives."),
    ('أعطونا الخريطة. وأنا بحلف: بنقسم الأكل معكم، وبنبعت لكم سفينة لما نوصل.', "Give us the map. And I swear: we share the food with you, and we send you a ship when we reach port."),
    ('أو، إذا بدكم، بتركبوا معنا وبنزلكم بأول ميناء.', "Or, if you like, you sail with us and we put you off at the first port."),
    ('وكان صوته دافي، ومعقول، وحلو.', "And his voice was warm, and reasonable, and pleasant."),
    ('ولو ما شفته يقتل توم، كنت صدقته.', "And had I not seen him kill Tom, I would have believed him.")),
  P(('الكابتن سمولت ما رد فوراً.', "Captain Smollett did not answer at once."),
    ('حط تبغ بغليونه، وشعله، وشرب منه.', "He put tobacco in his pipe, lit it, and drew on it."),
    ('وبعدين قال: خلصت؟', "And then he said: are you finished?"),
    ('قال سيلفر: هاي آخر كلمة. بعدها، رصاص.', "Silver said: that is my last word. After it, bullets."),
    ('قال الكابتن: طيب. اسمع كلمتي.', "The captain said: fine. Hear my word."),
    ('إذا إجيتوا واحد واحد بلا سلاح، بحطكم بالسلاسل.', "If you come one by one without arms, I put you in chains."),
    ('وبوديكم على إنجلترا لمحاكمة عادلة.', "And I take you to England for a fair trial."),
    ('غير هيك، ما في إشي.', "Other than that, there is nothing."),
    ('ما معكم سفينة، لأنه ما بتعرفوا تقودوها. وما معكم كنز، لأنه ما بتعرفوا وينه.', "You have no ship, because you cannot sail her. And no treasure, because you do not know where it is."),
    ('وهاي آخر كلمة مني، وبالمرة الجاية، بضربك برصاصة.', "And that is my last word, and next time, I shoot you.")),
  P(('وجه سيلفر تغير.', "Silver's face changed."),
    ('صار أحمر، وعينه ضاقت، وصار يشبه الزلمة اللي شفته بالغابة.', "It went red, his eyes narrowed, and he came to look like the man I had seen in the wood."),
    ('قال: ساعدوني أقوم.', "He said: help me up."),
    ('ما حدا تحرك.', "No one moved."),
    ('زحف عالرمل لحد ما وصل عالسور، ومسك عمود، وقام.', "He crawled on the sand until he reached the fence, grabbed a post, and got up."),
    ('وقال: بعد ساعة، بفوت على قلعتكم زي برميل روم.', "And he said: in an hour, I come into your fort like a barrel of rum."),
    ('واللي بيموت منكم، بيكون محظوظ.', "And whoever of you dies will be the lucky one."),
    ('وبصق، وطلع من السور، واختفى بالشجر.', "And he spat, and went over the fence, and vanished into the trees."))]),

 ('The Attack', 'الهجوم', [
  P(('الكابتن دار علينا وقال: خلال ساعة بيهجموا.', "The captain turned to us and said: within the hour they attack."),
    ('إحنا أقل، بس عنا سور، وبيت، وبنادق.', "We are fewer, but we have a fence, a house, and guns."),
    ('وحط كل واحد بمكانه: واحد على كل جهة.', "And he put every man in his place: one on each side."),
    ('وأنا وهنتر عالباب، نحمل البنادق ونحشيها.', "And Hunter and I at the door, carrying and loading the guns."),
    ('والشمس صارت حامية، والصمت أطول ساعة بحياتي.', "And the sun grew hot, and the silence was the longest hour of my life."),
    ('وبعدين صرخ جويس: بيجوا!', "And then Joyce shouted: they are coming!")),
  P(('صارت رصاصات من كل الجهات مرة وحدة.', "Bullets came from every side at once."),
    ('ما حدا انصاب، بس الخشب طار حوالينا.', "No one was hit, but the wood flew around us."),
    ('ومن الجهة الشمالية، طلع من الشجر سبعة رجال بيركضوا للسور.', "And from the north side, seven men came out of the trees running for the fence."),
    ('أطلقنا، ووقع اتنين، وخمسة تسلقوا السور.', "We fired, two fell, and five climbed the fence."),
    ('وجوب أندرسون الكبير قدامهم، يصرخ: عليهم يا رجال!', "And big Job Anderson at their head, shouting: at them, lads!"),
    ('واحد فات من الشباك ومسك بندقية هنتر وضربه فيها على راسه.', "One came through the window, grabbed Hunter's gun and struck him on the head with it."),
    ('وواحد تاني دخل من الباب على الدكتور.', "And another came in the door at the doctor.")),
  P(('صرخ الكابتن: برا! برا! قاتلوهم برا!', "The captain shouted: out! Out! Fight them outside!"),
    ('ومسكت سيف وطلعت من الباب، وما بعرف كيف.', "And I grabbed a cutlass and went out the door, I do not know how."),
    ('قدامي أندرسون، رافع سيفه، وبده ينزله على راسي.', "Before me was Anderson, his cutlass raised, about to bring it down on my head."),
    ('ما فكرت. نطيت عالجنب، ووقعت عالرمل، وتدحرجت.', "I did not think. I jumped aside, fell on the sand, and rolled."),
    ('ولما قمت، كان الدكتور قتله بضربة سيف.', "And when I got up, the doctor had killed him with a stroke of his cutlass."),
    ('وغراي كان قتل تاني، والسكوير تالت من الشباك.', "And Gray had killed a second, and the squire a third from the window."),
    ('واللي ضلوا، هربوا للشجر.', "And those that remained fled into the trees.")),
  P(('كل إشي خلص بدقيقة.', "It was all over in a minute."),
    ('خمسة من القتلة ماتوا حول القلعة، واتنين هربوا.', "Five of the killers lay dead around the stockade, and two had fled."),
    ('بس هنتر كان مغمى عليه من الضربة.', "But Hunter was unconscious from the blow."),
    ('وجويس انقتل برصاصة بالراس.', "And Joyce had been shot through the head."),
    ('والكابتن كان مصاب برصاصتين، بكتفه وبإجره.', "And the captain had been hit by two bullets, in the shoulder and the leg."),
    ('الدكتور عالجه، وقال: رح يعيش، بس ما رح يقاتل.', "The doctor treated him, and said: he will live, but he will not fight."),
    ('قال الكابتن: صاروا تسعة. وإحنا؟', "The captain said: they are nine now. And we?"),
    ('قال الدكتور: أربعة بيقدروا يقاتلوا. وجيم.', "The doctor said: four who can fight. And Jim."),
    ('وهنتر مات بالليل، وما فاق.', "And Hunter died in the night, and never woke."))]),

 ('I Slip Away', 'بهرب لحالي', [
  P(('بعد الظهر، طلع الدكتور مرة تانية من القلعة.', "In the afternoon, the doctor left the stockade a second time."),
    ('معه بندقيته، والخريطة.', "With him his gun, and the map."),
    ('قال غراي: الدكتور جن؟ رايح عند القتلة؟', "Gray said: has the doctor gone mad? Going to the killers?"),
    ('قلت: لا. رايح عند بن غون.', "I said: no. Going to Ben Gunn."),
    ('وحسدته، لأنه بالبرا في هوا وشجر، وهون ريحة دم وحرارة.', "And I envied him, because outside there was air and trees, and here the smell of blood and heat."),
    ('وبلشت أفكر فكرة.', "And I began to think of an idea."),
    ('فكرة غبية، زي فكرتي بالمركب.', "A stupid idea, like my idea with the boat.")),
  P(('الفكرة كانت: أروح عالصخرة البيضا، وألاقي مركب بن غون.', "The idea was: go to the white rock, and find Ben Gunn's boat."),
    ('كنت عارف إنه ما حدا رح يسمح لي، فما سألت.', "I knew no one would allow me, so I did not ask."),
    ('حطيت بجيبي خبز وبسكوت، وأخدت مسدسين وبارود.', "I put bread and biscuit in my pockets, and took two pistols and powder."),
    ('ولما كان الكل مشغول، طلعت من فوق السور من الجهة التانية.', "And when everyone was busy, I went over the fence on the far side."),
    ('وركضت.', "And I ran."),
    ('هاي تاني مرة بهرب. وهالمرة أنا عارف إنها غلط.', "This was the second time I ran away. And this time I knew it was wrong."),
    ('بس كنت ولد، وكان بدي أعمل إشي.', "But I was a boy, and I wanted to do something.")),
  P(('مشيت عالشط، من ورا الشجر، لحد ما شفت السفينة.', "I walked along the shore, behind the trees, until I saw the ship."),
    ('كانت مرسية بالخليج، وجنبها مركب زغير.', "She lay at anchor in the bay, with a small boat beside her."),
    ('وفيه اتنين من القتلة.', "And in it two of the killers."),
    ('كانوا بيصرخوا على بعض، وسكرانين.', "They were shouting at each other, and drunk."),
    ('وعالسفينة، شفت هاندز، الملاح، وواحد تاني.', "And on the ship, I saw Hands, the coxswain, and another."),
    ('كملت للصخرة البيضا، وكانت الشمس عم تغيب.', "I went on to the white rock, and the sun was setting."),
    ('وتحت الصخرة، بحفرة مغطاية بجلد ماعز، لقيت المركب.', "And under the rock, in a hollow covered with goatskin, I found the boat.")),
  P(('كان أغرب مركب شفته بحياتي.', "It was the strangest boat I had ever seen."),
    ('خشب وجلد، مدور، وزغير، بيحمل واحد بس.', "Wood and skin, round, and small, carrying one man only."),
    ('بن غون عمله بإيده، وبتلات سنين.', "Ben Gunn had made it with his own hands, over three years."),
    ('وقعدت جنبه واستنيت العتمة، وأكلت خبز.', "And I sat beside it and waited for the dark, and ate bread."),
    ('وفكرت: إذا قطعت حبل مرساة السفينة، بتنجرف عالشط، وبتخرب.', "And I thought: if I cut the ship's anchor rope, she drifts onto the shore, and is wrecked."),
    ('والقتلة بلا سفينة، بيصيروا أضعف.', "And the killers without a ship become weaker."),
    ('ولما صار الليل أسود، حملت المركب ونزلت عالمي.', "And when the night was black, I carried the boat and went down to the water."))]),

 ('The Ebb-Tide Runs', 'الجزر بيسحب', [
  P(('المركب الزغير كان يدور مع كل موجة، وما يمشي دغري.', "The little boat spun with every wave, and would not go straight."),
    ('بس التيار كان رايح باتجاه السفينة، وحملني.', "But the current was going toward the ship, and carried me."),
    ('وصلت لحبل المرساة، ومسكته.', "I reached the anchor rope, and grabbed it."),
    ('كان مشدود زي وتر، من قوة التيار.', "It was taut as a bowstring, from the force of the current."),
    ('لو قطعته مرة وحدة، كان ضربني وقلب المركب.', "Had I cut it all at once, it would have struck me and overturned the boat."),
    ('فاستنيت لحد ما رخى شوي مع الموج، وقصيت خيط خيط.', "So I waited until it slackened a little with the swell, and cut strand by strand.")),
  P(('ومن فوق، من الكابينة، كنت أسمع صوتين.', "And from above, from the cabin, I could hear two voices."),
    ('هاندز والتاني، سكرانين، وبيتخانقوا.', "Hands and the other, drunk, and fighting."),
    ('صوت كاسات بتنكسر، وصوت شتايم.', "The sound of glasses breaking, and the sound of curses."),
    ('وعالشط، نار القتلة الكبيرة، وغنيتهم من بعيد.', "And on the shore, the killers' big fire, and their song from afar."),
    ('وأنا بالنص، بمركب من جلد، وبإيدي سكين.', "And I in the middle, in a boat of skin, a knife in my hand."),
    ('وقصيت آخر خيط.', "And I cut the last strand.")),
  P(('السفينة تحررت، وبلشت تدور على مهل مع التيار.', "The ship came free, and began slowly to turn with the current."),
    ('والمركب الزغير انسحب معها، ولزق فيها.', "And the little boat was pulled along with her, and clung to her side."),
    ('ومديت إيدي ومسكت حبل بيتدلى من السفينة، ما بعرف ليش.', "And I reached out and caught a rope hanging from the ship, I do not know why."),
    ('وتسلقت شوي، وطليت من شباك الكابينة.', "And I climbed a little, and looked in at the cabin window."),
    ('هاندز والتاني كانوا ماسكين ببعض من رقابهم.', "Hands and the other were at each other's throats."),
    ('وأنا نزلت بسرعة قبل ما يشوفوني.', "And I dropped quickly before they saw me.")),
  P(('وبعدين صار الإشي اللي ما فكرت فيه.', "And then came the thing I had not thought of."),
    ('التيار زاد، والسفينة والمركب انجروا سوا للبحر المفتوح.', "The current grew stronger, and the ship and the boat were dragged together toward the open sea."),
    ('مش عالشط، زي ما خططت، بل لبرا.', "Not onto the shore, as I had planned, but outward."),
    ('وسمعت القتلة عالشط بيصرخوا، بس بعيد.', "And I heard the killers on the shore shouting, but far away."),
    ('والمركب الزغير صار يدور، ويدور، والموج بيعلى.', "And the little boat began to spin, and spin, and the waves rose."),
    ('تمددت بقاع المركب، ومسكت جوانبه، وسكرت عيني.', "I lay down in the bottom of the boat, held its sides, and closed my eyes."),
    ('وقلت: إذا بدي أموت، بموت هون.', "And I said: if I am to die, I die here."),
    ('ونمت. ما بعرف كيف، بس نمت.', "And I slept. I do not know how, but I slept."))]),

 ('The Cruise of the Coracle', 'رحلة المركب الصغير', [
  P(('فقت والشمس طالعة، والمركب بيرقص على موج كبير.', "I woke with the sun up, and the boat dancing on big waves."),
    ('كنت بعيد عن الجزيرة، بجنوبها، والتيار بيسحبني حواليها.', "I was far from the island, to its south, and the current was carrying me around it."),
    ('وكنت عطشان أكتر من أي إشي.', "And I was thirstier than anything."),
    ('كل ما أحاول أجدف، المركب يدور ويعبي مي.', "Every time I tried to paddle, the boat spun and took on water."),
    ('فتعلمت: ما تقاوم الموج. خليه يحملك.', "So I learned: do not fight the waves. Let them carry you."),
    ('وشوي شوي، الموج قربني للشط.', "And little by little, the waves brought me nearer the shore.")),
  P(('وبعدين شفتها.', "And then I saw her."),
    ('هيسبانيولا، ماشية بأشرعتها، بلا حدا يقودها.', "The Hispaniola, sailing under her canvas, with no one steering."),
    ('كانت تروح يمين، وتروح شمال، زي سكران.', "She went right, and went left, like a drunk man."),
    ('والأشرعة تفرقع، والدفة حرة.', "And the sails flapped, and the helm swung free."),
    ('قلت: هاندز والتاني نايمين أو ميتين.', "I said: Hands and the other are asleep or dead."),
    ('وإذا وصلت لها، بترجع لنا السفينة.', "And if I reach her, the ship comes back to us.")),
  P(('كانت جاية باتجاهي، مرة تقرب ومرة تبعد.', "She was coming my way, now nearer, now farther."),
    ('وأنا جدفت بكل قوتي، وعطشان، والشمس بتحرق.', "And I paddled with all my strength, thirsty, the sun burning."),
    ('وفجأة لفت الريح، وإجت السفينة عليّ دغري.', "And suddenly the wind shifted, and the ship came straight at me."),
    ('شفت مقدمتها فوق راسي، عالية زي بيت.', "I saw her bow above my head, high as a house."),
    ('ونطيت. مسكت حبل الشراع الأمامي، وتعلقت.', "And I jumped. I caught the rope of the foresail, and hung on."),
    ('وتحتي، المركب الزغير انسحق تحت السفينة، واختفى.', "And beneath me, the little boat was crushed under the ship, and vanished."),
    ('وما عاد إلي طريق رجعة.', "And I had no way back.")),
  P(('تسلقت لفوق ووقعت عالسطح.', "I climbed up and fell onto the deck."),
    ('السطح كان فاضي، وفيه دم، وقناني فاضية.', "The deck was empty, with blood on it, and empty bottles."),
    ('والاتنين كانوا هناك.', "And the two were there."),
    ('واحد مرمي على ظهره، وإيديه مفتوحة، وميت.', "One lying on his back, his arms spread, dead."),
    ('والتاني، هاندز، قاعد جنب الحيط.', "And the other, Hands, sitting against the bulwark."),
    ('راسه على صدره، ووجهه أصفر.', "His head on his chest, and his face yellow."),
    ('كل موجة كانت تحرك الميت، وهاندز ما يتحرك.', "Every wave moved the dead man, and Hands did not move."),
    ('وبعدين فتح هاندز عينه، وتطلع فيّ.', "And then Hands opened his eyes, and looked at me."),
    ('وقال: روم.', "And he said: rum."))]),

 ('I Strike the Jolly Roger', 'بنزل علم القراصنة', [
  P(('نزلت عالكابينة، وكان كل إشي مكسور ومقلوب.', "I went down to the cabin, and everything was broken and overturned."),
    ('لقيت قنينة روم، وجبتها لهاندز، وشربت أنا مي.', "I found a bottle of rum, brought it to Hands, and drank water myself."),
    ('وأكلت بسكوت، ولأول مرة من يومين، حسيت إني حي.', "And I ate biscuit, and for the first time in two days, I felt alive."),
    ('هاندز شرب نص القنينة، وقال: آه. هاد اللي كنت بحاجته.', "Hands drank half the bottle, and said: ah. That is what I needed."),
    ('وسألته: إنت مجروح؟', "And I asked him: are you wounded?"),
    ('قال: اللي كان معي جرحني بفخدي. وهو مات. وأنا لا.', "He said: the one with me stabbed me in the thigh. And he died. And I did not.")),
  P(('وبعدين قلت له: يا سيد هاندز، أنا هلق كابتن هالسفينة.', "And then I said to him: Mr. Hands, I am the captain of this ship now."),
    ('وأول أمر: بنزل هالعلم الأسود.', "And my first order: I take down this black flag."),
    ('رحت عالسارية، ونزلت علم القراصنة، ورميته بالبحر.', "I went to the mast, lowered the pirate flag, and threw it into the sea."),
    ('قلت: يحيا الملك! وراح الكابتن سيلفر!', "I said: God save the king! And so much for Captain Silver!"),
    ('هاندز تطلع فيّ، وضحك ضحكة زغيرة.', "Hands looked at me, and gave a small laugh."),
    ('قال: طيب يا كابتن هوكينز. وهلق شو بدك تعمل؟', "He said: fine, Captain Hawkins. And now what do you want to do?")),
  P(('قلت: بدي أوصل السفينة للخليج الشمالي، وأوقفها عالشط.', "I said: I want to take the ship to the north inlet, and beach her on the shore."),
    ('لأنه ما بقدر أرجع للمرسى القديم، القتلة هناك.', "Because I cannot go back to the old anchorage; the killers are there."),
    ('قال هاندز: وإنت بتعرف تقود سفينة؟', "Hands said: and do you know how to sail a ship?"),
    ('قلت: لا.', "I said: no."),
    ('قال: أنا بعرف. بس مجروح.', "He said: I do. But I am wounded."),
    ('إنت بتعطيني أكل وشراب ومنديل لجرحي.', "You give me food and drink and a cloth for my wound."),
    ('وأنا بقول كيف تقودها.', "And I say how to sail her."),
    ('وعينه كانت بتتطلع فيّ بطريقة ما حبيتها.', "And his eyes were looking at me in a way I did not like."),
    ('بس ما كان عندي خيار.', "But I had no choice.")),
  P(('وهيك صرنا اتنين نقود السفينة: أنا بإيدي، وهو بلسانه.', "And so the two of us sailed the ship: I with my hands, he with his tongue."),
    ('يمين شوي. شمال شوي. شد الحبل. رخي.', "Right a little. Left a little. Haul the rope. Ease off."),
    ('والسفينة سمعت، ومشت زي ما بدنا.', "And the ship obeyed, and went as we wished."),
    ('وشوي شوي، لفينا حول الجزيرة، ووصلنا عالشمال.', "And little by little, we rounded the island, and reached the north."),
    ('وهاندز قاعد، وبيشرب، وبيتطلع فيّ.', "And Hands sat, drinking, watching me."),
    ('وأنا عارف إنه بيفكر بإشي.', "And I knew he was thinking of something."),
    ('بس كنت مبسوط كتير.', "But I was very happy."),
    ('لأني كنت قائد سفينة، وعمري أربعتعشر سنة.', "Because I was the master of a ship, and I was fourteen years old."))]),

 ('Israel Hands', 'إسرائيل هاندز', [
  P(('قبل ما ندخل الخليج، قال هاندز: يا جيم، بدي إشي.', "Before we entered the inlet, Hands said: Jim, I want something."),
    ('في نبيذ بالكابينة. الرم قوي عليّ. جيب لي نبيذ.', "There is wine in the cabin. The rum is too strong for me. Fetch me wine."),
    ('ما صدقته.', "I did not believe him."),
    ('واحد زي هاندز ما بيطلب نبيذ بدل روم.', "A man like Hands does not ask for wine instead of rum."),
    ('قلت: طيب. ونزلت عالكابينة، وخلعت جزمتي، وطلعت من الشباك التاني، وتفرجت.', "I said: fine. And I went down to the cabin, took off my shoes, came up through the other hatch, and watched.")),
  P(('هاندز قام، وهو بيتوجع، وزحف عالسطح.', "Hands got up, in pain, and crawled across the deck."),
    ('وصل لحبل ملفوف، وطلع منه سكين طويلة، وحطها بجيبه.', "He reached a coil of rope, took out a long knife, and put it in his pocket."),
    ('وزحف ورجع لمكانه، وقعد زي ما كان.', "And he crawled back to his place, and sat as before."),
    ('فهمت كل إشي.', "I understood everything."),
    ('هو بده يوصل السفينة عالشط، وبعدين يقتلني.', "He wanted the ship on the shore, and then to kill me."),
    ('وأنا بده إياني حي لحد ما نوصل.', "And he wanted me alive until we got there."),
    ('يعني عندي وقت لحد الشط.', "So I had time until the shore.")),
  P(('رجعت بالنبيذ، وأعطيته ياه، وعملت حالي ما شفت إشي.', "I came back with the wine, gave it to him, and pretended I had seen nothing."),
    ('ودخلنا الخليج، والريح معنا، والشط بيقرب.', "And we entered the inlet, the wind with us, the shore drawing near."),
    ('هاندز قال: هلق، يمين! كل اليمين!', "Hands said: now, right! Hard right!"),
    ('لفيت الدفة، والسفينة مالت، ودخلت بالرمل بصوت كبير.', "I turned the helm, the ship heeled, and ran into the sand with a great noise."),
    ('والصدمة رمتني عالأرض.', "And the shock threw me to the ground."),
    ('ولما رفعت راسي، كان هاندز واقف فوقي، والسكين بإيده.', "And when I raised my head, Hands was standing over me, the knife in his hand.")),
  P(('نطيت عالجنب، وركضت، وهو ورايي.', "I leapt aside, and ran, and he came after me."),
    ('لفينا حول السارية مرة ومرتين، زي لعبة أولاد.', "We went round the mast once and twice, like a children's game."),
    ('بس هو مجروح وبطيء، وأنا سريع.', "But he was wounded and slow, and I was fast."),
    ('وطلعت مسدس من جيبي، وسحبت، وما ضرب. البارود مبلول.', "And I pulled a pistol from my pocket, and pulled the trigger, and it did not fire. The powder was wet."),
    ('فتسلقت السارية، لفوق، لحد ما ما قدر يلحقني.', "So I climbed the mast, upward, until he could not follow."),
    ('وهناك، بالهوا، حشيت المسدسين ببارود ناشف.', "And there, in the air, I loaded the two pistols with dry powder."),
    ('وهاندز تحتي، بيتطلع لفوق، وبيفكر.', "And Hands beneath me, looking up, thinking.")),
  P(('قال: يا جيم، أنا خسرت. أنا مش محظوظ.', "He said: Jim, I have lost. I am not lucky."),
    ('صعب على واحد زيي إنه يستسلم لولد، بس بستسلم.', "It is hard for a man like me to give up to a boy, but I give up."),
    ('وكان يحكي، وإيده بتتحرك ورا ظهره.', "And he was talking, and his hand was moving behind his back."),
    ('وفجأة رمى السكين.', "And suddenly he threw the knife."),
    ('حسيت ضربة بكتفي.', "I felt a blow in my shoulder."),
    ('وسمعت المسدسين بيضربوا، الاتنين، بلا ما أقصد.', "And I heard both pistols fire, without meaning to."),
    ('وهاندز وقع من السفينة، بالمي، وغاص، وما طلع.', "And Hands fell from the ship, into the water, and sank, and did not come up."),
    ('وأنا معلق بالسارية، والسكين مسمرة كتفي بالخشب.', "And I hung on the mast, the knife pinning my shoulder to the wood."))]),

 ('Pieces of Eight', 'قطع الذهب', [
  P(('كان الدم بينزل على إيدي، وكنت خايف كتير.', "The blood was running down my arm, and I was very afraid."),
    ('بس لما شديت، فهمت إن السكين ماسكة جلدي بس.', "But when I pulled, I understood the knife was holding only my skin."),
    ('وشديت مرة وحدة، وتحررت، والألم كان أقل من الخوف.', "And I pulled once, and was free, and the pain was less than the fear."),
    ('نزلت عالكابينة، وعالجت جرحي بإيدي.', "I went down to the cabin, and dressed my wound myself."),
    ('ورميت الميت التاني بالبحر، ورا هاندز.', "And I threw the other dead man into the sea, after Hands."),
    ('وصارت السفينة إلي، أنا لحالي.', "And the ship was mine, mine alone.")),
  P(('كانت الشمس عم تغيب، والسفينة مايلة عالرمل، بس سليمة.', "The sun was setting, and the ship lay heeled on the sand, but whole."),
    ('نزلت بالمي لحد الخصر، ووصلت عالشط.', "I went down into the water up to my waist, and reached the shore."),
    ('وقلت: هلق برجع للقلعة، وبقول لهم: السفينة إلنا.', "And I said: now I go back to the stockade, and tell them: the ship is ours."),
    ('ويمكن يسامحوني على هروبي.', "And perhaps they forgive me for running away."),
    ('ومشيت بالجزيرة بالعتمة، ساعات.', "And I walked through the island in the dark, for hours."),
    ('والقمر طلع، وشفت القلعة، وما كان فيها نار.', "And the moon rose, and I saw the stockade, and there was no fire in it."),
    ('قلت: نايمين. وهاد غلط، الكابتن ما بيترك بلا حراسة.', "I said: they are asleep. And that is wrong; the captain never leaves it unguarded.")),
  P(('تسلقت السور، وزحفت للبيت، وفت من الباب على إيدي وركبي.', "I climbed the fence, crawled to the house, and went in the door on hands and knees."),
    ('كان في ناس نايمين، بيشخروا.', "There were people asleep, snoring."),
    ('وقلت: بفاجئهم، وبضحكوا.', "And I said: I will surprise them, and they will laugh."),
    ('وبهاللحظة، صرخ صوت حاد بالعتمة:', "And in that moment, a sharp voice screeched in the dark:"),
    ('قطع الذهب! قطع الذهب! قطع الذهب!', "Pieces of eight! Pieces of eight! Pieces of eight!"),
    ('ببغا سيلفر.', "Silver's parrot.")),
  P(('قام الكل مرة وحدة.', "Everyone got up at once."),
    ('وسمعت صوت سيلفر يصرخ: مين هناك؟', "And I heard Silver's voice shout: who is there?"),
    ('ركضت للباب، ووقعت بحضن واحد.', "I ran for the door, and fell into the arms of a man."),
    ('مسكني، وشعل واحد تاني ضو.', "He held me, and another struck a light."),
    ('وشفت: القلعة مليانة قراصنة.', "And I saw: the stockade was full of pirates."),
    ('ستة رجال، وسيلفر بالنص، على عكازه.', "Six men, and Silver in the middle, on his crutch."),
    ('ولا واحد من أصحابي.', "And not one of my friends."),
    ('قال سيلفر: جيم هوكينز! يا الله! إجا يزورنا.', "Silver said: Jim Hawkins! Well, well! Come to visit us."))]),

 ('In the Enemy’s Camp', 'بمعسكر العدو', [
  P(('قعدت عالأرض، وسيلفر قدامي، وحواليّ رجاله.', "I sat on the floor, Silver before me, his men around me."),
    ('قال سيلفر: يا جيم، أنا دايماً حبيتك. إنت بتشبهني.', "Silver said: Jim, I always liked you. You are like me."),
    ('أصحابك تركوك. الدكتور قال: الولد؟ ما بدنا ياه.', "Your friends left you. The doctor said: the boy? We do not want him."),
    ('قلت: كذب.', "I said: a lie."),
    ('قال سيلفر: مبارح إجا الدكتور بعلم أبيض.', "Silver said: yesterday the doctor came with a white flag."),
    ('وقال: خلص، السفينة راحت.', "And he said: it is over, the ship is gone."),
    ('وأعطانا القلعة، والأكل، وشرط واحد: ما نلحقهم.', "And he gave us the stockade, the food, and one condition: we do not follow them."),
    ('وراحوا. وما بعرف لوين.', "And they went. And I do not know where.")),
  P(('ما فهمت، بس سكت.', "I did not understand, but kept silent."),
    ('قال سيلفر: فإنت معنا، ولا ضدنا.', "Silver said: so you are with us, or against us."),
    ('اختار.', "Choose."),
    ('وحسيت إنه لازم أحكي، وإلا بموت من الخوف.', "And I felt I must speak, or die of fear."),
    ('فقلت: أنا اللي كنت بالبرميل، وسمعت كل كلمة.', "So I said: I was the one in the apple barrel, and I heard every word."),
    ('وأنا اللي قطعت حبل السفينة، وقتلت هاندز.', "And I am the one who cut the ship's rope, and killed Hands."),
    ('والسفينة بمكان ما بتعرفوه، وما رح تشوفوها.', "And the ship is in a place you do not know, and you will not see her."),
    ('اقتلوني إذا بدكم، أو خلوني حي، وبشهد لكم بالمحكمة.', "Kill me if you like, or keep me alive, and I testify for you in court.")),
  P(('صار صمت.', "There was silence."),
    ('وبعدين قام واحد وهو بيسحب سكين، وقال: أنا بقتله.', "And then one got up drawing a knife, and said: I will kill him."),
    ('قال سيلفر: خليك مكانك.', "Silver said: stay where you are."),
    ('أنا الكابتن هون. واللي بيلمس الولد، بيقاتلني.', "I am captain here. And whoever touches the boy fights me."),
    ('صار رجاله يتهامسوا، ويتطلعوا فيه.', "His men began whispering, and looking at him."),
    ('وقال واحد: بدنا نحكي برا.', "And one said: we want to talk outside."),
    ('وطلعوا الستة، وتركوني مع سيلفر لحالنا.', "And the six went out, and left me alone with Silver.")),
  P(('قال سيلفر بصوت واطي: يا جيم، إنت قريب من الموت.', "Silver said in a low voice: Jim, you are close to death."),
    ('وأنا كمان. رجالي بدهم يطردوني، لأني حميتك.', "And so am I. My men want to throw me out, because I protected you."),
    ('بس اسمع: أنا بحميك، وإنت بتحمي جون سيلفر من المشنقة.', "But listen: I protect you, and you protect John Silver from the gallows."),
    ('قلت: بعمل اللي بقدر عليه.', "I said: I do what I can."),
    ('قال: اتفقنا.', "He said: agreed."),
    ('وبعدين قال، وهو بيتطلع بالنار:', "And then he said, looking into the fire:"),
    ('الدكتور أعطاني إشي كمان، غير القلعة.', "The doctor gave me something else, besides the stockade."),
    ('أعطاني الخريطة.', "He gave me the map."),
    ('وطلعها من جيبه، وأنا ما فهمت إشي.', "And he took it from his pocket, and I understood nothing."))]),

 ('The Black Spot Again', 'النقطة السودا كمان مرة', [
  P(('رجع الستة، وواحد منهم قدام، وبإيده ورقة.', "The six came back, one of them in front, with a paper in his hand."),
    ('قال سيلفر: تعال يا جورج. أنا بعرف القانون.', "Silver said: come, George. I know the rules."),
    ('حط الورقة بإيد سيلفر، وقال: النقطة السودا.', "He put the paper in Silver's hand, and said: the black spot."),
    ('سيلفر فتحها، وضحك.', "Silver opened it, and laughed."),
    ('قال: قطعتوها من إنجيل! يا مجانين! هاد فأل شؤم.', "He said: you cut it from a Bible! You fools! That is bad luck."),
    ('وقرا: مخلوع. وقال: وليش، يا جورج؟', "And he read: deposed. And he said: and why, George?")),
  P(('قال جورج: أربع أسباب.', "George said: four reasons."),
    ('خربت الرحلة. وتركت العدو يطلع من القلعة. وما هجمت عليهم.', "You ruined the voyage. You let the enemy leave the stockade. You did not attack them."),
    ('والولد. حميت الولد.', "And the boy. You protected the boy."),
    ('قال سيلفر: طيب. أنا برد.', "Silver said: fine. I answer."),
    ('مين خرب الرحلة؟ إنتو، لما ما استنيتوا لحد ما أقول.', "Who ruined the voyage? You, when you did not wait until I gave the word."),
    ('ومين خسر السفينة؟ إنتو، اللي تركتوها بلا حراسة.', "And who lost the ship? You, who left her unguarded."),
    ('والولد؟ الولد رهينة. هو آخر ورقة معنا.', "And the boy? The boy is a hostage. He is our last card.")),
  P(('وقال: والقلعة؟ ليش اتفقت مع الدكتور؟', "And he said: and the stockade? Why did I make terms with the doctor?"),
    ('عشان هاد.', "For this."),
    ('ورمى الخريطة عالأرض.', "And he threw the map on the floor."),
    ('نطوا عليها كلهم، زي القطط على فار.', "They all leapt on it, like cats on a mouse."),
    ('الصلبان الحمر، والتعليمات بخط فلينت.', "The red crosses, and the directions in Flint's hand."),
    ('صرخوا: الخريطة! خريطة فلينت!', "They shouted: the map! Flint's map!"),
    ('وقال جورج: طيب... بس كيف بنطلع بالكنز بلا سفينة؟', "And George said: fine... but how do we get away with the treasure without a ship?"),
    ('قال سيلفر: هاد شغلي. أنا كابتن ولا لا؟', "Silver said: that is my business. Am I captain or not?"),
    ('وصرخوا كلهم: سيلفر! سيلفر كابتن!', "And they all shouted: Silver! Silver for captain!")),
  P(('بالصبح، إجا الدكتور عالقلعة، زي كل يوم، يعالج الجرحى.', "In the morning, the doctor came to the stockade, as he did every day, to treat the wounded."),
    ('وشافني، ووجهه تغير، بس ما حكى.', "And he saw me, and his face changed, but he said nothing."),
    ('عالج المرضى، وبعدين قال: بدي أحكي مع الولد.', "He treated the sick, and then said: I want to speak with the boy."),
    ('سيلفر قال: جيم، بتحلف إنك ما بتهرب؟', "Silver said: Jim, do you swear you will not run?"),
    ('حلفت.', "I swore."),
    ('وطلعنا برا السور، أنا والدكتور.', "And we went outside the fence, the doctor and I."),
    ('قال الدكتور: يا جيم، ليش هربت؟', "The doctor said: Jim, why did you run away?"),
    ('وحكيت له كل إشي، والسفينة، وهاندز.', "And I told him everything, the ship, and Hands."),
    ('قال: السفينة! يا جيم، كل مرة بتنقذنا.', "He said: the ship! Jim, every time you save us."),
    ('وقال: هلق اهرب معي.', "And he said: now run away with me."),
    ('قلت: حلفت لسيلفر.', "I said: I swore to Silver."),
    ('وسكت الدكتور، وقال: طيب. إنت زلمة.', "And the doctor was silent, and said: fine. You are a man."))]),

 ('The Treasure Hunt', 'البحث عن الكنز', [
  P(('طلعنا ندور على الكنز، كلنا، وأنا مربوط بحبل بسيلفر.', "We set out to hunt the treasure, all of us, and I was tied to Silver by a rope."),
    ('كانوا فرحانين، وبيغنوا، ومعهم معاول وأكل.', "They were happy, and singing, with picks and food."),
    ('والدكتور قال لي قبل ما نطلع: خليك جنب سيلفر. لا تبعد عنه.', "And the doctor had said to me before we left: stay beside Silver. Do not leave him."),
    ('وما فهمت ليش.', "And I did not understand why."),
    ('التعليمات كانت: شجرة طويلة على كتف تلة المنظار.', "The directions were: a tall tree on the shoulder of Spy-glass Hill."),
    ('وطلعنا التلة، والشمس حامية، وسيلفر بيتعب على عكازه.', "And we climbed the hill, the sun hot, Silver labouring on his crutch.")),
  P(('وبنص الطريق، صرخ واحد.', "And halfway up, one of them cried out."),
    ('لقى تحت شجرة هيكل عظمي لبني آدم.', "He had found under a tree the skeleton of a man."),
    ('كان ممدد، وإيديه فوق راسه، بخط مستقيم.', "It lay stretched out, its arms above its head, in a straight line."),
    ('قال سيلفر: هاد مش صدفة. هاد سهم.', "Silver said: this is no accident. This is a pointer."),
    ('فلينت حطه هيك، عشان يدل عالطريق.', "Flint laid him so, to show the way."),
    ('وقال واحد بصوت بيرجف: فلينت. كان ياخد ستة معه، وبيرجع لحاله.', "And one said in a shaking voice: Flint. He would take six with him, and come back alone."),
    ('وهاد واحد من الستة.', "And this is one of the six.")),
  P(('كملوا، بس بلا غنا.', "They went on, but without singing."),
    ('وبعدين، من ورا الشجر، إجا صوت.', "And then, from behind the trees, came a voice."),
    ('صوت رفيع بيغني: خمستاشر زلمة على صندوق الميت.', "A thin voice singing: fifteen men on the dead man's chest."),
    ('وقفوا كلهم، ووجوههم صارت بيضا.', "They all stopped, and their faces went white."),
    ('قال واحد: هاد فلينت!', "One said: that is Flint!"),
    ('والصوت صرخ: دارْبي ماكغرو! جيب لي روم يا داربي!', "And the voice cried: Darby McGraw! Fetch me rum, Darby!"),
    ('وهاي كانت آخر كلمات فلينت قبل ما مات.', "And those had been Flint's last words before he died."),
    ('صار الرجال يرجفوا، وواحد قال: بنرجع.', "The men began to shake, and one said: we go back."),
    ('بس سيلفر قال: هاد مش شبح. الأشباح ما إلها صدى. وهاد إله صدى.', "But Silver said: this is no ghost. Ghosts have no echo. And this has an echo."),
    ('وبعدين قال: أنا بعرف هالصوت. هاد بن غون!', "And then he said: I know this voice. That is Ben Gunn!"),
    ('وضحكوا كلهم، لأنه بن غون ما حدا بيخاف منه.', "And they all laughed, because no one was afraid of Ben Gunn.")),
  P(('وصلوا على الشجرة الكبيرة، وركضوا لقدام.', "They reached the big tree, and ran ahead."),
    ('وسيلفر بيسحبني وراه، وعينه بتلمع، ووجهه مش وجه صاحب.', "And Silver dragged me after him, his eyes shining, and his face was not a friend's face."),
    ('وبعدين وقفوا كلهم، عند حفرة.', "And then they all stopped, at a pit."),
    ('حفرة كبيرة، قديمة، وفيها عصا معول مكسورة، وصناديق مفتوحة.', "A big pit, old, with a broken pick handle in it, and open crates."),
    ('وفاضية.', "And empty."),
    ('الكنز راح. حدا أخده من زمان.', "The treasure was gone. Someone had taken it long ago."),
    ('سيلفر تطلع فيها ثانية.', "Silver looked into it for a second."),
    ('وبعدين حط بإيدي مسدس، وهمس: خليك جاهز.', "And then he put a pistol in my hand, and whispered: be ready."),
    ('وغير وجهه مرة تانية، ووقف جنبي، ضد رجاله.', "And his face changed again, and he stood beside me, against his men.")),
  P(('الستة طلعوا من الحفرة، ووجوههم سودا من الغضب.', "The six climbed out of the pit, their faces black with rage."),
    ('قال جورج: هاد سيلفر! هو اللي كان بيعرف! هو والولد!', "George said: it is Silver! He was the one who knew! He and the boy!"),
    ('ورفع مسدسه.', "And he raised his pistol."),
    ('وبنفس اللحظة، صارت تلات رصاصات من الشجر.', "And in that same moment, three shots came from the trees."),
    ('جورج وقع بالحفرة، وواحد تاني وقع جنبه، والباقي هربوا.', "George fell into the pit, another fell beside him, and the rest fled."),
    ('وطلع من الشجر الدكتور، وغراي، وبن غون، والبنادق بتدخن.', "And out of the trees came the doctor, and Gray, and Ben Gunn, their guns smoking."),
    ('قال سيلفر: يا دكتور! جيتوا بالوقت. أنا وجيم كنا رح نموت.', "Silver said: doctor! You came in time. Jim and I were about to die."),
    ('وقال بن غون، وهو بيضحك: أنا. أنا اللي أخدت الكنز. من تلات سنين.', "And Ben Gunn said, laughing: me. I am the one who took the treasure. Three years ago."),
    ('وهو بمغارتي، كله.', "And it is in my cave, all of it.")),
  P(('وهيك فهمت كل إشي.', "And so I understood everything."),
    ('الدكتور عرف من بن غون إن الكنز مش بمكانه.', "The doctor had learned from Ben Gunn that the treasure was not in its place."),
    ('فأعطى سيلفر الخريطة، لأنها صارت ورقة فاضية.', "So he gave Silver the map, because it had become an empty paper."),
    ('وأعطاه القلعة، لأنه المغارة أحسن، وفيها الكنز.', "And gave him the stockade, because the cave was better, and the treasure was in it."),
    ('وحملنا الذهب للسفينة أيام، كيس ورا كيس.', "And we carried the gold to the ship for days, sack after sack."),
    ('وسيلفر كان يشتغل معنا، ويضحك.', "And Silver worked with us, and laughed."),
    ('وكان يقول: يا جيم، إحنا الاتنين نجونا.', "And he would say: Jim, the two of us survived."),
    ('وبآخر ليلة قبل ما نوصل لأول ميناء، اختفى سيلفر.', "And on the last night before we reached the first port, Silver vanished."),
    ('ومعه كيس ذهب، وببغاه.', "And with him a sack of gold, and his parrot."),
    ('وأنا ما زعلت، وما عرفت ليش.', "And I was not sorry, and I did not know why."),
    ('ولحد اليوم، بحلم بالجزيرة.', "And to this day, I dream of the island."),
    ('وبسمع الببغا بيصرخ: قطع الذهب، قطع الذهب!', "And I hear the parrot screeching: pieces of eight, pieces of eight!"))]),
]

if __name__ == '__main__':
    raise SystemExit(book(BOOK_ID, BOOK_TITLE, 'intermediate', CHAPTERS, shelf=13,
              meta={'work': 'Treasure Island', 'author': 'Robert Louis Stevenson',
                    'year': '1883', 'status': 'public domain'}))
