#!/usr/bin/env python3
"""جحا — forty short tales, retold in spoken Palestinian, graded to beginner.

Juha (Nasreddin Hoja in Turkish, Goha in Egyptian) is folk material: centuries old, anonymous,
retold in every language between Morocco and Central Asia. Public domain by age — there is no
author to credit and no edition being translated. These are retellings from the traditional
plots, written for graded reading.

WHY THIS IS THE RIGHT FIRST BEGINNER BOOK. The tales run three to eight sentences, they repeat
their own frame (جحا راح…، جحا قال…، جاره سأله…), and they live in markets and kitchens and on a
donkey — so A1 vocabulary comes from the material rather than from restraint. And they are funny,
which is what gets a beginner to read the next one.

Written to the numbers pipeline/bookshelf_check.py measures: sentences under ~25 Arabic characters,
present and simple past, no subordination stacked more than one deep, and the same small cast
(جحا، جاره، الحمار، السوق، القاضي) recurring so vocabulary is reinforced instead of just met.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_juha.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, book

BOOK_ID = 'juha'
BOOK_TITLE = {'en': 'Juha', 'ar': 'جحا'}

# (english title, arabic title, [paragraph, ...])
#
# SECOND EDITION (2026-09-03). The same forty tales and titles, told out at the same beginner
# register — the frame repeated (جحا راح، جحا قال، جاره سأله), one clause a sentence — with the
# setup and the back-and-forth given their room, and the last line still the joke.
CHAPTERS = [
 ('The Donkey and the Neighbour', 'الحمار والجار', [
  P(('جحا كان عنده حمار.', "Juha had a donkey."),
    ('حمار زغير، ورمادي.', "A small, grey donkey."),
    ('وكان بيحبه كتير.', "And he loved it a lot."),
    ('كل يوم بيطعميه.', "Every day he fed it."),
    ('وبيغسله.', "And washed it."),
    ('وبيحكي معه.', "And talked to it.")),
  P(('بيوم، إجا جاره.', "One day, his neighbour came."),
    ('ودق الباب.', "And knocked."),
    ('وقال: يا جحا، بدي الحمار اليوم.', "And said: Juha, I want the donkey today."),
    ('بدي أروح عالسوق.', "I want to go to the market."),
    ('جحا ما بده يعطيه.', "Juha did not want to give it to him."),
    ('الجار بيضرب الحمير.', "The neighbour beats donkeys.")),
  P(('قال جحا: يا خسارة.', "Juha said: what a pity."),
    ('الحمار مش هون.', "The donkey is not here."),
    ('راح عالسوق مع ابني.', "It went to the market with my son."),
    ('من الصبح.', "This morning."),
    ('قال الجار: يا خسارة.', "The neighbour said: what a pity."),
    ('ولف عشان يروح.', "And turned to leave.")),
  P(('وبهاي اللحظة، صار صوت.', "And in that moment, there was a sound."),
    ('من ورا البيت.', "From behind the house."),
    ('هيـهاااو!', "Hee-haaw!"),
    ('الحمار نهق.', "The donkey brayed."),
    ('الجار وقف.', "The neighbour stopped."),
    ('وقال: يا جحا!', "And said: Juha!"),
    ('أنا بسمع الحمار!', "I hear the donkey!"),
    ('هو بالبيت!', "It is at home!")),
  P(('جحا تطلع فيه.', "Juha looked at him."),
    ('وحط إيده على قلبه.', "And put his hand on his heart."),
    ('وقال: يا زلمة.', "And said: man."),
    ('عيب عليك.', "Shame on you."),
    ('أنا جارك من عشرين سنة.', "I have been your neighbour for twenty years."),
    ('بتصدق الحمار، ولا بتصدقني؟', "Do you believe the donkey, or do you believe me?"))]),

 ('The Coat at the Feast', 'الكبوت بالعزيمة', [
  P(('واحد غني عمل عزيمة.', "A rich man gave a feast."),
    ('وعزم كل الناس.', "And invited everyone."),
    ('وعزم جحا.', "And invited Juha."),
    ('جحا راح.', "Juha went."),
    ('بلبسه القديم.', "In his old clothes."),
    ('لأنه ما عنده غيره.', "Because he had no others.")),
  P(('دخل جحا.', "Juha went in."),
    ('ما حدا سلم عليه.', "No one greeted him."),
    ('ما حدا قال: أهلاً.', "No one said: welcome."),
    ('ما حدا قعّده.', "No one seated him."),
    ('وقف عند الباب.', "He stood by the door."),
    ('والناس بتاكل.', "And the people ate."),
    ('وطلع.', "And he left.")),
  P(('رجع عالبيت.', "He went home."),
    ('وفتح الصندوق.', "And opened the chest."),
    ('وطلع كبوت.', "And took out a coat."),
    ('كبوت جديد، وحلو.', "A new, handsome coat."),
    ('من أيام العرس.', "From his wedding days."),
    ('ولبسه.', "And put it on."),
    ('ورجع عالعزيمة.', "And went back to the feast.")),
  P(('دخل جحا.', "Juha went in."),
    ('والكل قام.', "And everyone stood up."),
    ('قالوا: أهلاً يا جحا!', "They said: welcome, Juha!"),
    ('تفضل يا جحا!', "This way, Juha!"),
    ('وقعّدوه بالصدر.', "And seated him at the head."),
    ('وحطوا قدامه الأكل.', "And put the food before him."),
    ('لحمة، ورز، وحلو.', "Meat, rice, sweets.")),
  P(('جحا ما أكل.', "Juha did not eat."),
    ('مد كم الكبوت.', "He held out the coat's sleeve."),
    ('وحطه بالصحن.', "And put it in the plate."),
    ('وقال: كول يا كبوتي.', "And said: eat, my coat."),
    ('كول.', "Eat."),
    ('الناس سكتوا.', "The people fell silent."),
    ('سألوه: شو عم تعمل يا جحا؟', "They asked him: what are you doing, Juha?"),
    ('قال: الأكل للكبوت.', "He said: the food is for the coat."),
    ('مش إلي.', "Not for me."),
    ('أنا إجيت قبل شوي.', "I came a little while ago."),
    ('وما حدا شافني.', "And no one saw me."))]),

 ('The Pot That Gave Birth', 'الطنجرة اللي ولدت', [
  P(('جحا بده يطبخ لضيوف.', "Juha wanted to cook for guests."),
    ('وطنجرته زغيرة.', "And his pot was small."),
    ('راح لجاره.', "He went to his neighbour."),
    ('وقال: أعطيني طنجرتك الكبيرة.', "And said: give me your big pot."),
    ('يوم واحد بس.', "Just one day."),
    ('الجار أعطاه.', "The neighbour gave it.")),
  P(('بعد يومين، جحا رجعها.', "Two days later, Juha returned it."),
    ('وجواتها طنجرة زغيرة.', "And inside it, a small pot."),
    ('قال الجار: شو هاي؟', "The neighbour said: what is this?"),
    ('قال جحا: طنجرتك ولدت.', "Juha said: your pot gave birth."),
    ('عندي.', "At my house."),
    ('هاي بنتها.', "This is her daughter."),
    ('الجار ضحك.', "The neighbour laughed."),
    ('وأخد التنتين.', "And took both."),
    ('وقال: جحا مجنون.', "And said: Juha is mad.")),
  P(('بعد أسبوع، جحا رجع.', "A week later, Juha came back."),
    ('قال: بدي الطنجرة كمان مرة.', "He said: I want the pot again."),
    ('الجار أعطاه بسرعة.', "The neighbour gave it quickly."),
    ('وقال بقلبه: يمكن تولد كمان.', "And said to himself: maybe it gives birth again."),
    ('ومر يوم.', "And a day passed."),
    ('ويومين.', "And two."),
    ('وأسبوع.', "And a week."),
    ('والطنجرة ما رجعت.', "And the pot did not come back.")),
  P(('راح الجار لجحا.', "The neighbour went to Juha."),
    ('قال: وين طنجرتي؟', "He said: where is my pot?"),
    ('جحا حط إيده على راسه.', "Juha put his hand on his head."),
    ('وقال: الله يرحمها.', "And said: God rest her."),
    ('ماتت.', "She died."),
    ('قال الجار: ماتت؟', "The neighbour said: died?"),
    ('الطناجر ما بتموت!', "Pots do not die!"),
    ('قال جحا: غريب.', "Juha said: strange."),
    ('صدقت إنها بتولد.', "You believed she gives birth."),
    ('وما بتصدق إنها بتموت؟', "And you do not believe she dies?"))]),

 ('The Smell of the Food', 'ريحة الأكل', [
  P(('كان في رجل فقير.', "There was a poor man."),
    ('معه خبزة يابسة.', "He had a dry loaf."),
    ('وقعد جنب دكان أكل.', "And sat beside a food shop."),
    ('الدكان فيه لحمة مشوية.', "The shop had grilled meat."),
    ('وريحتها طيبة.', "And it smelled good."),
    ('الفقير أكل خبزه.', "The poor man ate his bread."),
    ('وهو بيشم الريحة.', "While smelling the smell."),
    ('وقال: أطيب خبزة أكلتها.', "And said: the best bread I ever ate.")),
  P(('صاحب الدكان شافه.', "The shopkeeper saw him."),
    ('وطلع عليه.', "And came out to him."),
    ('وقال: ادفع.', "And said: pay."),
    ('قال الفقير: أدفع شو؟', "The poor man said: pay for what?"),
    ('أنا ما أكلت من عندك.', "I ate nothing of yours."),
    ('قال صاحب الدكان: شميت ريحة أكلي.', "The shopkeeper said: you smelled my food."),
    ('والريحة إلها ثمن.', "And the smell has a price."),
    ('وصاروا يتخانقوا.', "And they began to quarrel.")),
  P(('راحوا عند القاضي.', "They went to the judge."),
    ('والقاضي كان جحا.', "And the judge was Juha."),
    ('جحا سمع القصة.', "Juha heard the story."),
    ('وقال: صحيح.', "And said: true."),
    ('الريحة إلها ثمن.', "The smell has a price."),
    ('صاحب الدكان فرح.', "The shopkeeper was pleased."),
    ('والفقير خاف.', "And the poor man was afraid.")),
  P(('جحا أخد كيس مصاري.', "Juha took a bag of coins."),
    ('وهزه.', "And shook it."),
    ('قدام صاحب الدكان.', "In front of the shopkeeper."),
    ('طق، طق، طق.', "Clink, clink, clink."),
    ('وقال: سمعت صوت المصاري؟', "And said: did you hear the sound of the money?"),
    ('قال: سمعت.', "He said: I heard."),
    ('قال جحا: خلص.', "Juha said: done."),
    ('صوت المصاري، بدفع ريحة الأكل.', "The sound of money pays for the smell of food."),
    ('روحوا.', "Go."))]),

 ('Riding to Market', 'رايحين عالسوق', [
  P(('جحا وابنه راحوا عالسوق.', "Juha and his son went to the market."),
    ('والحمار معهم.', "And the donkey with them."),
    ('جحا ركب الحمار.', "Juha rode the donkey."),
    ('والولد مشى جنبه.', "And the boy walked beside him."),
    ('ومرقوا على ناس.', "And they passed some people."),
    ('والناس حكوا.', "And the people talked."),
    ('قالوا: شوفوا!', "They said: look!"),
    ('الأب راكب.', "The father is riding."),
    ('والولد ماشي وتعبان.', "And the boy is walking and tired."),
    ('حرام.', "Shame.")),
  P(('جحا نزل.', "Juha got down."),
    ('وركّب ابنه.', "And put his son on."),
    ('ومشى هو.', "And walked himself."),
    ('ومرقوا على ناس تانيين.', "And they passed other people."),
    ('قالوا: شوفوا!', "They said: look!"),
    ('الولد راكب.', "The boy is riding."),
    ('وأبوه كبير وماشي.', "And his old father is walking."),
    ('عيب.', "Disgraceful.")),
  P(('جحا ركب مع ابنه.', "Juha got on with his son."),
    ('التنين عالحمار.', "Both on the donkey."),
    ('ومرقوا على ناس تانيين.', "And they passed other people."),
    ('قالوا: شوفوا!', "They said: look!"),
    ('اتنين على حمار زغير.', "Two on a small donkey."),
    ('مسكين الحمار.', "Poor donkey."),
    ('رح يموت.', "It will die.")),
  P(('جحا وابنه نزلوا.', "Juha and his son got down."),
    ('ومشوا التنين.', "And both walked."),
    ('والحمار ماشي قدامهم، فاضي.', "And the donkey walked ahead of them, empty."),
    ('ومرقوا على ناس تانيين.', "And they passed other people."),
    ('قالوا: شوفوا!', "They said: look!"),
    ('معهم حمار، وماشيين!', "They have a donkey, and they are walking!"),
    ('مجانين.', "Madmen.")),
  P(('جحا وقف.', "Juha stopped."),
    ('وتطلع بابنه.', "And looked at his son."),
    ('وقال: يا ابني.', "And said: my son."),
    ('تعلم من اليوم.', "Learn from today."),
    ('مهما تعمل، في حدا رح يحكي.', "Whatever you do, someone will talk."),
    ('فاعمل اللي بدك.', "So do what you want."))]),

 ('The Key in the Light', 'المفتاح بالضوء', [
  P(('بالليل، جحا رجع عالبيت.', "At night, Juha came home."),
    ('وحط إيده بجيبه.', "And put his hand in his pocket."),
    ('والمفتاح مش موجود.', "And the key was not there."),
    ('دور بجيبه التاني.', "He looked in his other pocket."),
    ('مش موجود.', "Not there."),
    ('قال: ضيعت المفتاح.', "He said: I have lost the key.")),
  P(('وراح عالشارع.', "And he went into the street."),
    ('تحت الضوء.', "Under the lamp."),
    ('وقعد يدور.', "And began searching."),
    ('عالأرض.', "On the ground."),
    ('بين الحجار.', "Among the stones."),
    ('ساعة كاملة.', "A whole hour.")),
  P(('إجا جاره.', "His neighbour came."),
    ('وقال: شو بتعمل يا جحا؟', "And said: what are you doing, Juha?"),
    ('قال جحا: بدور على مفتاحي.', "Juha said: looking for my key."),
    ('قال الجار: بساعدك.', "The neighbour said: I will help you."),
    ('وقعد يدور معه.', "And began searching with him."),
    ('ساعة كمان.', "Another hour."),
    ('وما لقوا شي.', "And they found nothing.")),
  P(('قال الجار: يا جحا.', "The neighbour said: Juha."),
    ('وين وقع المفتاح بالزبط؟', "Where exactly did the key fall?"),
    ('قال جحا: جوا البيت.', "Juha said: inside the house."),
    ('بالأوضة.', "In the room."),
    ('قال الجار: جوا البيت؟', "The neighbour said: inside the house?"),
    ('وليش عم ندور هون؟', "Then why are we searching here?"),
    ('قال جحا: لأنه هون في ضوء.', "Juha said: because here there is light."),
    ('وجوا عتمة.', "And inside it is dark."))]),

 ('Three Days of Bread', 'خبز تلات أيام', [
  P(('جحا راح عالفرن.', "Juha went to the bakery."),
    ('واشترى خبز.', "And bought bread."),
    ('خبز كتير.', "A lot of bread."),
    ('لتلات أيام.', "For three days."),
    ('وحطه عالطاولة.', "And put it on the table."),
    ('وراح ينام.', "And went to bed.")),
  P(('الصبح، فاق.', "In the morning, he woke."),
    ('وراح عالطاولة.', "And went to the table."),
    ('والخبز ناقص.', "And the bread was less."),
    ('نص الخبز راح.', "Half the bread was gone."),
    ('قال جحا: في فار بالبيت.', "Juha said: there is a mouse in the house."),
    ('وراح عالسوق.', "And went to the market."),
    ('وجاب قطة.', "And brought a cat."),
    ('قطة زغيرة.', "A small cat.")),
  P(('وبالمسا، حط خبز.', "And in the evening, he put out bread."),
    ('وحط صحن لبن للقطة.', "And put out a plate of yoghurt for the cat."),
    ('وقال: الليلة، الفار بيموت.', "And said: tonight, the mouse dies."),
    ('وراح ينام.', "And went to bed."),
    ('مرتاح.', "At ease.")),
  P(('الصبح، فاق.', "In the morning, he woke."),
    ('والخبز ناقص.', "And the bread was less."),
    ('واللبن ناقص.', "And the yoghurt was less."),
    ('والقطة نايمة، وبطنها كبير.', "And the cat asleep, with a big belly."),
    ('قال جحا: يا الله.', "Juha said: good Lord."),
    ('مبارح كان عندي فار.', "Yesterday I had a mouse."),
    ('وهلق عندي فار وقطة.', "And now I have a mouse and a cat."))]),

 ('The Sermon', 'الخطبة', [
  P(('أهل القرية إجوا لجحا.', "The village people came to Juha."),
    ('قالوا: إنت رجل عاقل.', "They said: you are a wise man."),
    ('اخطب فينا يوم الجمعة.', "Give us a sermon on Friday."),
    ('قال جحا: طيب.', "Juha said: fine."),
    ('ويوم الجمعة، الجامع كان مليان.', "And on Friday, the mosque was full."),
    ('وجحا وقف قدامهم.', "And Juha stood before them.")),
  P(('وقال: يا ناس.', "And said: people."),
    ('بتعرفوا شو بدي أحكي؟', "Do you know what I am going to say?"),
    ('قالوا: لأ.', "They said: no."),
    ('ما بنعرف.', "We do not know."),
    ('قال جحا: ولا أنا.', "Juha said: nor do I."),
    ('سلامتكم.', "Good day to you."),
    ('ونزل، وراح.', "And came down, and left."),
    ('والناس استغربوا.', "And the people were puzzled.")),
  P(('الجمعة الجاية، رجع.', "The next Friday, he came back."),
    ('وقال: بتعرفوا شو بدي أحكي؟', "And said: do you know what I am going to say?"),
    ('الناس كانوا جاهزين.', "The people were ready."),
    ('قالوا: أي! بنعرف!', "They said: yes! We know!"),
    ('قال جحا: منيح.', "Juha said: good."),
    ('إذا بتعرفوا، ليش أحكي؟', "If you know, why should I speak?"),
    ('ونزل، وراح.', "And came down, and left.")),
  P(('الجمعة التالتة، الناس عملوا خطة.', "The third Friday, the people made a plan."),
    ('نص بيقولوا بنعرف.', "Half say we know."),
    ('ونص بيقولوا ما بنعرف.', "And half say we do not."),
    ('وجحا سأل: بتعرفوا شو بدي أحكي؟', "And Juha asked: do you know what I am going to say?"),
    ('النص الأول قال: بنعرف!', "The first half said: we know!"),
    ('والنص التاني قال: ما بنعرف!', "And the second half said: we do not!"),
    ('قال جحا: عظيم.', "Juha said: excellent."),
    ('اللي بيعرف، يحكي للي ما بيعرف.', "Those who know, tell those who do not."),
    ('ونزل، وراح.', "And came down, and left."))]),

 ('Carrying the Door', 'شايل الباب', [
  P(('جحا بده يسافر.', "Juha wanted to travel."),
    ('للمدينة.', "To the city."),
    ('يومين.', "For two days."),
    ('وأمه كانت خايفة.', "And his mother was worried."),
    ('قالت: البيت فاضي.', "She said: the house will be empty."),
    ('وفي حرامية.', "And there are thieves."),
    ('قال جحا: لا تخافي.', "Juha said: do not worry.")),
  P(('قالت أمه: يا جحا.', "His mother said: Juha."),
    ('دير بالك عالباب.', "Mind the door."),
    ('الباب أهم شي.', "The door is the most important thing."),
    ('لا تتركه.', "Do not leave it."),
    ('قال جحا: طيب يا ماما.', "Juha said: fine, mother."),
    ('ما بتركه.', "I will not leave it."),
    ('وراحت أمه عند أختها.', "And his mother went to her sister's.")),
  P(('جحا وقف قدام الباب.', "Juha stood in front of the door."),
    ('وفكر.', "And thought."),
    ('كيف بدير بالي عليه، وأنا مسافر؟', "How do I mind it, when I am travelling?"),
    ('وإجت له فكرة.', "And an idea came to him."),
    ('قلع الباب.', "He took the door off."),
    ('وحمله على ظهره.', "And carried it on his back."),
    ('ومشى.', "And walked.")),
  P(('مشى بالباب كل الطريق.', "He walked with the door all the way."),
    ('للمدينة.', "To the city."),
    ('والناس بيتطلعوا.', "And people stared."),
    ('سألوه: يا جحا!', "They asked him: Juha!"),
    ('ليش شايل باب؟', "Why are you carrying a door?"),
    ('قال جحا: أمي قالت لي.', "Juha said: my mother told me."),
    ('دير بالك عالباب.', "Mind the door."),
    ('وأنا بدير بالي.', "And I am minding it."),
    ('شوفوا، هو معي.', "See, it is with me."))]),

 ('The Ring in the Well', 'الخاتم بالبير', [
  P(('جحا راح يجيب مي من البير.', "Juha went to fetch water from the well."),
    ('ونزل الدلو.', "And lowered the bucket."),
    ('وسحبه.', "And pulled it up."),
    ('وشرب.', "And drank."),
    ('وبعدين تطلع بإيده.', "And then looked at his hand."),
    ('الخاتم مش موجود.', "The ring was not there."),
    ('وقع بالبير.', "It had fallen in the well.")),
  P(('البير عميق.', "The well was deep."),
    ('والمي بعيدة.', "And the water far down."),
    ('وعتمة.', "And dark."),
    ('جحا تطلع فيه.', "Juha looked into it."),
    ('وفكر.', "And thought."),
    ('وراح عالبيت.', "And went home."),
    ('وجاب صحن لبن.', "And brought a plate of yoghurt."),
    ('وكبه بالبير.', "And poured it in the well.")),
  P(('جاره شافه.', "His neighbour saw him."),
    ('وقال: يا جحا!', "And said: Juha!"),
    ('شو عم تعمل؟', "What are you doing?"),
    ('قال جحا: عم أعمل لبن.', "Juha said: I am making yoghurt."),
    ('قال الجار: بالبير؟', "The neighbour said: in the well?"),
    ('قال جحا: بالبير.', "Juha said: in the well."),
    ('قال الجار: يا مجنون.', "The neighbour said: you madman."),
    ('البير ما بيصير لبن!', "A well does not turn into yoghurt!")),
  P(('جحا تطلع بالجار.', "Juha looked at the neighbour."),
    ('وقال: بعرف.', "And said: I know."),
    ('بس تخيل.', "But imagine."),
    ('إذا صار؟', "If it did?"),
    ('بير كامل لبن.', "A whole well of yoghurt."),
    ('والجار سكت.', "And the neighbour was silent."),
    ('وراح.', "And left."),
    ('وجحا ضل يفكر بالخاتم.', "And Juha kept thinking about the ring."))]),

 ('Counting the Donkeys', 'عد الحمير', [
  P(('جحا اشترى حمير.', "Juha bought donkeys."),
    ('عشرة.', "Ten."),
    ('من السوق.', "From the market."),
    ('وبده يوديهم عالبيت.', "And wanted to take them home."),
    ('ركب على واحد.', "He got on one."),
    ('والباقي مشوا وراه.', "And the rest walked behind him.")),
  P(('بالطريق، عدهم.', "On the way, he counted them."),
    ('واحد، اتنين، تلاتة...', "One, two, three..."),
    ('تسعة.', "Nine."),
    ('قال جحا: تسعة؟', "Juha said: nine?"),
    ('أنا اشتريت عشرة!', "I bought ten!"),
    ('وخاف.', "And he panicked."),
    ('ونزل عن الحمار.', "And got off the donkey."),
    ('وعد كمان مرة.', "And counted again."),
    ('عشرة.', "Ten.")),
  P(('قال: الحمد لله.', "He said: thank God."),
    ('وركب.', "And got on."),
    ('وعد.', "And counted."),
    ('تسعة.', "Nine."),
    ('ونزل.', "And got off."),
    ('وعد.', "And counted."),
    ('عشرة.', "Ten."),
    ('ركب، تسعة.', "On, nine."),
    ('نزل، عشرة.', "Off, ten.")),
  P(('جحا وقف بالطريق.', "Juha stood in the road."),
    ('وفكر طويل.', "And thought a long time."),
    ('وقال: فهمت.', "And said: I understand."),
    ('لما بركب، حمار بيروح.', "When I ride, a donkey goes."),
    ('ولما بنزل، بيرجع.', "And when I get off, it comes back."),
    ('فالمشي أحسن.', "So walking is better."),
    ('ومشى للبيت.', "And he walked home."),
    ('والحمير عشرة.', "And the donkeys were ten."))]),

 ('The Cold Night', 'الليلة الباردة', [
  P(('كان الشتا.', "It was winter."),
    ('وبرد كتير.', "And very cold."),
    ('وجحا قاعد بالمقهى.', "And Juha sat in the café."),
    ('وقال: البرد ما بيخوفني.', "And said: the cold does not frighten me."),
    ('واحد سمعه.', "Someone heard him."),
    ('وقال: براهنك.', "And said: I bet you."),
    ('ليلة كاملة برا.', "A whole night outside."),
    ('بلا نار.', "Without a fire."),
    ('إذا قدرت، بعزمك على عشا.', "If you can, I treat you to dinner."),
    ('قال جحا: قبلت.', "Juha said: accepted.")),
  P(('وبالليل، جحا وقف برا.', "And at night, Juha stood outside."),
    ('بالساحة.', "In the square."),
    ('بلا نار.', "Without a fire."),
    ('والبرد بيقطع.', "And the cold was cutting."),
    ('ساعة، وساعتين.', "An hour, two hours."),
    ('وطول الليل.', "And all night."),
    ('وجحا واقف.', "And Juha stood."),
    ('وبيرجف.', "Shivering.")),
  P(('الصبح، إجا الرجل.', "In the morning, the man came."),
    ('وقال: قضيت الليل؟', "And said: you spent the night?"),
    ('قال جحا: قضيته.', "Juha said: I did."),
    ('قال الرجل: وما شفت نار؟', "The man said: and you saw no fire?"),
    ('قال جحا: نار لا.', "Juha said: no fire."),
    ('بس شفت شمعة.', "But I saw a candle."),
    ('بشباك بعيد.', "In a far window."),
    ('قال الرجل: شمعة!', "The man said: a candle!"),
    ('يعني تدفيت فيها!', "So you warmed yourself by it!"),
    ('خسرت.', "You lost."),
    ('ما بعزمك.', "No dinner.")),
  P(('بعد يومين، جحا عزم الرجل.', "Two days later, Juha invited the man."),
    ('على عشا.', "To dinner."),
    ('والرجل إجا.', "And the man came."),
    ('وقعد.', "And sat."),
    ('واستنى.', "And waited."),
    ('ساعة، وساعتين.', "An hour, two hours."),
    ('والأكل ما إجا.', "And the food did not come."),
    ('راح عالمطبخ.', "He went to the kitchen."),
    ('ولقى طنجرة كبيرة.', "And found a big pot."),
    ('معلقة فوق شمعة.', "Hanging over a candle."),
    ('قال: شو هاد؟', "He said: what is this?"),
    ('قال جحا: الشمعة اللي بتدفي زلمة، بتطبخ أكل.', "Juha said: a candle that warms a man can cook a dinner."))]),

 ('Which Half', 'أي نص', [
  P(('واحد إجا لجحا.', "A man came to Juha."),
    ('وقال: إنت رجل عالم.', "And said: you are a learned man."),
    ('عندي سؤال.', "I have a question."),
    ('قال جحا: اسأل.', "Juha said: ask."),
    ('قال الرجل: الدنيا نصها ليل.', "The man said: the world is half night."),
    ('ونصها نهار.', "And half day."),
    ('ليش؟', "Why?")),
  P(('جحا فكر.', "Juha thought."),
    ('وفكر.', "And thought."),
    ('وحك راسه.', "And scratched his head."),
    ('وقال: ما بعرف.', "And said: I do not know."),
    ('الرجل زعل.', "The man was upset."),
    ('قال: ما بتعرف؟', "He said: you do not know?"),
    ('إنت عالم!', "You are a scholar!"),
    ('العالم لازم يعرف كل شي!', "A scholar must know everything!")),
  P(('قال جحا: لا.', "Juha said: no."),
    ('العالم ما بيعرف كل شي.', "A scholar does not know everything."),
    ('قال الرجل: وشو بيعرف؟', "The man said: then what does he know?"),
    ('قال جحا: بيعرف شي واحد.', "Juha said: he knows one thing."),
    ('قال الرجل: شو؟', "The man said: what?"),
    ('قال جحا: بيعرف إمتى يقول: ما بعرف.', "Juha said: he knows when to say: I do not know."))]),

 ('The Long Way Home', 'الطريق الطويل', [
  P(('جحا رجع من السوق.', "Juha came back from the market."),
    ('بالليل.', "At night."),
    ('والعتمة قوية.', "And the dark was deep."),
    ('ما في قمر.', "There was no moon."),
    ('ومشى.', "And he walked."),
    ('ومشى.', "And walked.")),
  P(('وبعد ساعة، شاف شجرة.', "And after an hour, he saw a tree."),
    ('شجرة كبيرة.', "A big tree."),
    ('وقال: أنا مرقت من هون.', "And said: I passed here before."),
    ('وكمل.', "And went on."),
    ('وبعد ساعة، نفس الشجرة.', "And after an hour, the same tree."),
    ('قال جحا: أنا بلف.', "Juha said: I am going in circles."),
    ('بالعتمة.', "In the dark.")),
  P(('قعد جحا تحت الشجرة.', "Juha sat under the tree."),
    ('وقال: بستنى الصبح.', "And said: I will wait for morning."),
    ('بالصبح بشوف الطريق.', "In the morning I will see the road."),
    ('وسند راسه عالشجرة.', "And leaned his head on the tree."),
    ('ونام.', "And slept."),
    ('نوم عميق.', "A deep sleep.")),
  P(('فاق على صوت ديك.', "He woke to the sound of a rooster."),
    ('والشمس طالعة.', "And the sun was up."),
    ('وفتح عينه.', "And opened his eyes."),
    ('وشاف بيت.', "And saw a house."),
    ('بيته.', "His house."),
    ('كان نايم قدام بابه.', "He had been sleeping in front of his own door."),
    ('قال جحا: عجيب.', "Juha said: amazing."),
    ('أقرب طريق للبيت هو النوم.', "The shortest way home is sleep."))]),

 ('Salt and Wool', 'الملح والصوف', [
  P(('جحا بيبيع ملح.', "Juha sold salt."),
    ('بيحمله على حماره.', "He carried it on his donkey."),
    ('من الضيعة للمدينة.', "From the village to the town."),
    ('والطريق فيها نهر.', "And the road had a river in it."),
    ('نهر زغير.', "A small river."),
    ('والحمار بيعبره.', "And the donkey crossed it.")),
  P(('بيوم، الحمار وقع بالنهر.', "One day, the donkey fell in the river."),
    ('والملح داب.', "And the salt dissolved."),
    ('كله.', "All of it."),
    ('والحمار قام.', "And the donkey got up."),
    ('والحمل خفيف.', "And the load was light."),
    ('والحمار مبسوط.', "And the donkey was pleased."),
    ('وجحا زعلان.', "And Juha was upset.")),
  P(('المرة الجاية، وصلوا للنهر.', "The next time, they reached the river."),
    ('والحمار وقع.', "And the donkey fell."),
    ('بالقصد.', "On purpose."),
    ('والملح داب.', "And the salt dissolved."),
    ('والحمار مبسوط.', "And the donkey was pleased."),
    ('وجحا فهم.', "And Juha understood."),
    ('وقال: طيب.', "And said: fine.")),
  P(('المرة الجاية، جحا حمل صوف.', "The next time, Juha loaded wool."),
    ('مش ملح.', "Not salt."),
    ('صوف كتير، وخفيف.', "A lot of wool, and light."),
    ('ووصلوا للنهر.', "And they reached the river."),
    ('والحمار وقع.', "And the donkey fell."),
    ('بالقصد.', "On purpose."),
    ('والصوف شرب المي.', "And the wool drank the water."),
    ('وصار تقيل.', "And became heavy."),
    ('تقيل كتير.', "Very heavy."),
    ('والحمار قام بصعوبة.', "And the donkey got up with difficulty."),
    ('وقال جحا: كل شغلة إلها وقتها.', "And Juha said: every trick has its day."))]),

 ('The Borrowed Cooking', 'الطبخة المستعارة', [
  P(('جارة جحا دقت الباب.', "Juha's neighbour knocked at the door."),
    ('وقالت: يا جحا.', "And said: Juha."),
    ('عندك ملح؟', "Do you have salt?"),
    ('قال جحا: عندي.', "Juha said: I have."),
    ('وأعطاها.', "And gave her some."),
    ('وراحت.', "And she left.")),
  P(('بعد شوي، رجعت.', "A little later, she came back."),
    ('وقالت: عندك زيت؟', "And said: do you have oil?"),
    ('قال جحا: عندي.', "Juha said: I have."),
    ('وأعطاها.', "And gave her some."),
    ('وبعد شوي، رجعت.', "And a little later, she came back."),
    ('وقالت: عندك بصل؟', "And said: do you have onions?"),
    ('وأعطاها.', "And he gave her some."),
    ('وبعدين رز.', "And then rice."),
    ('وبعدين لحمة.', "And then meat."),
    ('وبعدين حطب.', "And then firewood.")),
  P(('وجحا بيعطي.', "And Juha kept giving."),
    ('وبيسكت.', "And kept quiet."),
    ('وبالمسا، الجارة إجت.', "And in the evening, the neighbour came."),
    ('وهي مبسوطة.', "Pleased."),
    ('وقالت: يا جحا.', "And said: Juha."),
    ('الأكل جاهز.', "The food is ready."),
    ('بتحب تاكل معنا؟', "Would you like to eat with us?")),
  P(('قال جحا: أكيد.', "Juha said: certainly."),
    ('وقام.', "And got up."),
    ('وقالت الجارة: كرم منك.', "And the neighbour said: how kind of you."),
    ('قال جحا: مش كرم.', "Juha said: not kindness."),
    ('هاد أكلي.', "This is my food."),
    ('الملح إلي، والزيت إلي.', "The salt is mine, and the oil is mine."),
    ('والبصل، والرز، واللحمة، والحطب.', "And the onions, the rice, the meat, the wood."),
    ('إنتِ بس طبختيه.', "You only cooked it."))]),

 ('The Fur Coat in Summer', 'الفروة بالصيف', [
  P(('بعز الصيف.', "In the height of summer."),
    ('والشمس حامية.', "And the sun blazing."),
    ('والناس بتعرق.', "And people sweating."),
    ('وجحا ماشي بالسوق.', "And Juha walking in the market."),
    ('لابس فروة.', "Wearing a fur coat."),
    ('فروة تقيلة.', "A heavy fur coat.")),
  P(('الناس ضحكوا.', "The people laughed."),
    ('قالوا: يا جحا!', "They said: Juha!"),
    ('فروة بالصيف؟', "A fur coat in summer?"),
    ('مش حر عليك؟', "Are you not hot?"),
    ('قال جحا: لا.', "Juha said: no."),
    ('قالوا: كيف؟', "They said: how?"),
    ('قال جحا: الفروة سميكة.', "Juha said: the fur is thick."),
    ('بتمنع الحر يفوت.', "It stops the heat getting in.")),
  P(('وإجا الشتا.', "And winter came."),
    ('والبرد قوي.', "And the cold was sharp."),
    ('والناس بترجف.', "And people shivered."),
    ('وجحا ماشي بالسوق.', "And Juha walking in the market."),
    ('لابس نفس الفروة.', "Wearing the same fur coat.")),
  P(('الناس قالوا: يا جحا.', "The people said: Juha."),
    ('بالصيف قلت إنها بتمنع الحر.', "In summer you said it keeps out the heat."),
    ('وهلق شتا.', "And now it is winter."),
    ('قال جحا: صحيح.', "Juha said: true."),
    ('بتمنع الحر يفوت.', "It stops the heat getting in."),
    ('وبتمنع الدفا يطلع.', "And stops the warmth getting out."),
    ('فروة عاقلة.', "A sensible coat."))]),

 ('The Debt', 'الدين', [
  P(('جحا استلف مصاري.', "Juha borrowed money."),
    ('من رجل بالسوق.', "From a man in the market."),
    ('وقال: برجعها بعد شهر.', "And said: I will return it in a month."),
    ('ومر الشهر.', "And the month passed."),
    ('وجحا ما معه.', "And Juha had nothing."),
    ('ولا قرش.', "Not a penny.")),
  P(('الرجل إجا عالبيت.', "The man came to the house."),
    ('ودق الباب.', "And knocked."),
    ('وصرخ: يا جحا!', "And shouted: Juha!"),
    ('مصاريي!', "My money!"),
    ('جحا سمع.', "Juha heard."),
    ('وقال لمرته: قولي له مش هون.', "And told his wife: tell him I am not here."),
    ('وتخبى ورا الباب.', "And hid behind the door.")),
  P(('مرته فتحت.', "His wife opened."),
    ('وقالت: جحا مش بالبيت.', "And said: Juha is not at home."),
    ('راح عالمدينة.', "He went to the city."),
    ('الرجل ما صدق.', "The man did not believe."),
    ('وتطلع من الشباك.', "And looked through the window."),
    ('وشاف جحا.', "And saw Juha."),
    ('ورا الباب.', "Behind the door.")),
  P(('صرخ الرجل: يا جحا!', "The man shouted: Juha!"),
    ('أنا بشوفك!', "I can see you!"),
    ('إنت ورا الباب!', "You are behind the door!"),
    ('جحا طلع راسه.', "Juha put his head out."),
    ('وقال: بتشوفني؟', "And said: you can see me?"),
    ('قال الرجل: بشوفك!', "The man said: I see you!"),
    ('قال جحا: طيب.', "Juha said: fine."),
    ('وبكرا لما أموت، بتشوفني كمان؟', "And tomorrow when I die, will you see me too?"))]),

 ('The Old Tree', 'الشجرة القديمة', [
  P(('جحا صار كبير بالعمر.', "Juha had grown old."),
    ('شعره أبيض.', "His hair white."),
    ('وظهره منحني.', "And his back bent."),
    ('وبيوم، راح عالحقل.', "And one day, he went to the field."),
    ('ومعه شتلة زيتون.', "With an olive sapling."),
    ('وحفر.', "And dug."),
    ('وزرعها.', "And planted it.")),
  P(('جاره شافه.', "His neighbour saw him."),
    ('وضحك.', "And laughed."),
    ('وقال: يا جحا.', "And said: Juha."),
    ('شجرة زيتون؟', "An olive tree?"),
    ('الزيتون بده عشرين سنة.', "Olives take twenty years."),
    ('عشان يطعمي.', "To bear fruit."),
    ('وإنت كبير.', "And you are old."),
    ('مش رح تاكل منها.', "You will not eat from it.")),
  P(('جحا وقف.', "Juha stood up."),
    ('ومسح إيده.', "And wiped his hands."),
    ('وتطلع بالجار.', "And looked at the neighbour."),
    ('وقال: صحيح.', "And said: true."),
    ('مش رح آكل منها.', "I will not eat from it."),
    ('قال الجار: فليش بتزرعها؟', "The neighbour said: then why plant it?")),
  P(('قال جحا: لما كنت زغير، أكلت زيتون.', "Juha said: when I was young, I ate olives."),
    ('من شجر ما زرعته.', "From trees I did not plant."),
    ('زرعه ناس قبلي.', "People before me planted them."),
    ('وماتوا.', "And died."),
    ('وأنا أكلت.', "And I ate."),
    ('وهلق أنا بزرع.', "And now I plant."),
    ('وحدا غيري رح ياكل.', "And someone else will eat."),
    ('هيك الدنيا.', "That is how the world goes."))]),

 ('The Broken Jar', 'الجرة المكسورة', [
  P(('جحا عنده جرة.', "Juha had a jar."),
    ('جرة كبيرة، للمي.', "A big jar, for water."),
    ('وبيوم، قال لابنه: روح عالبير.', "And one day, he said to his son: go to the well."),
    ('وجيب مي.', "And fetch water."),
    ('وأعطاه الجرة.', "And gave him the jar."),
    ('والولد أخدها.', "And the boy took it.")),
  P(('وقبل ما يطلع، جحا وقفه.', "And before he left, Juha stopped him."),
    ('وضربه كف.', "And slapped him."),
    ('كف قوي.', "A hard slap."),
    ('والولد بكى.', "And the boy cried."),
    ('وقال: ليش يا بابا؟', "And said: why, father?"),
    ('أنا ما عملت شي!', "I did nothing!"),
    ('قال جحا: روح جيب المي.', "Juha said: go and fetch the water.")),
  P(('الجيران شافوا.', "The neighbours saw."),
    ('وزعلوا.', "And were upset."),
    ('قالوا: يا جحا!', "They said: Juha!"),
    ('ليش ضربته؟', "Why did you hit him?"),
    ('الولد ما عمل شي.', "The boy did nothing."),
    ('الجرة سليمة.', "The jar is whole."),
    ('هاد ظلم.', "That is unjust.")),
  P(('قال جحا: اسمعوا.', "Juha said: listen."),
    ('لما تنكسر الجرة، بتنكسر.', "When the jar breaks, it is broken."),
    ('والضرب بعدها، ما بينفع.', "And a slap afterwards does no good."),
    ('ما بيرجع الجرة.', "It does not bring back the jar."),
    ('فبضربه قبل.', "So I slap him before."),
    ('عشان ينتبه.', "So he takes care."),
    ('والجرة تضل سليمة.', "And the jar stays whole."))]),

 ('Both Are Right', 'التنين على حق', [
  P(('جحا صار قاضي.', "Juha became a judge."),
    ('بالقرية.', "In the village."),
    ('وبيوم، إجا له اتنين.', "And one day, two men came to him."),
    ('بيتخانقوا.', "Quarrelling."),
    ('على أرض.', "Over land."),
    ('قال جحا: احكوا.', "Juha said: speak."),
    ('واحد واحد.', "One at a time.")),
  P(('الأول حكى.', "The first spoke."),
    ('قال: الأرض إلي.', "He said: the land is mine."),
    ('أبوي زرعها.', "My father farmed it."),
    ('وجدي زرعها.', "And my grandfather farmed it."),
    ('وحكى كتير.', "And he spoke at length."),
    ('وجحا سمع.', "And Juha listened."),
    ('وقال: معك حق.', "And said: you are right.")),
  P(('التاني حكى.', "The second spoke."),
    ('قال: لا، الأرض إلي.', "He said: no, the land is mine."),
    ('اشتريتها.', "I bought it."),
    ('ومعي ورقة.', "And I have a paper."),
    ('وحكى كتير.', "And he spoke at length."),
    ('وجحا سمع.', "And Juha listened."),
    ('وقال: وإنت كمان معك حق.', "And said: and you are right too.")),
  P(('مرة جحا كانت قاعدة.', "Juha's wife was sitting there."),
    ('ورا الباب.', "Behind the door."),
    ('وسمعت.', "And heard."),
    ('وقالت: يا جحا!', "And said: Juha!"),
    ('شو هالحكم؟', "What kind of judgement is that?"),
    ('ما بيصير التنين على حق!', "Both cannot be right!"),
    ('جحا فكر شوي.', "Juha thought a moment."),
    ('وقال: وإنتِ كمان معك حق.', "And said: and you are right too."))]),

 ('The Heavy Basket', 'السلة التقيلة', [
  P(('جحا راح عالسوق.', "Juha went to the market."),
    ('واشترى سلة.', "And bought a basket."),
    ('سلة كبيرة.', "A big basket."),
    ('مليانة خضار.', "Full of vegetables."),
    ('وتقيلة.', "And heavy."),
    ('وحماره واقف برا.', "And his donkey stood outside.")),
  P(('جحا ركب الحمار.', "Juha got on the donkey."),
    ('وحمل السلة.', "And lifted the basket."),
    ('وحطها على راسه.', "And put it on his head."),
    ('هو راكب.', "He riding."),
    ('والسلة على راسه.', "And the basket on his head."),
    ('والحمار ماشي.', "And the donkey walking.")),
  P(('واحد شافه.', "Someone saw him."),
    ('وقال: يا جحا.', "And said: Juha."),
    ('ليش السلة على راسك؟', "Why is the basket on your head?"),
    ('حطها عالحمار.', "Put it on the donkey."),
    ('جحا قال: لا.', "Juha said: no."),
    ('قال الرجل: ليش؟', "The man said: why?")),
  P(('قال جحا: الحمار مسكين.', "Juha said: the poor donkey."),
    ('هو شايلني.', "It is carrying me."),
    ('وأنا تقيل.', "And I am heavy."),
    ('حرام أثقل عليه أكتر.', "It would be cruel to load it more."),
    ('فالسلة بحملها أنا.', "So I carry the basket myself."),
    ('والرجل سكت.', "And the man was silent."),
    ('وراح يفكر.', "And went off thinking."))]),

 ('Nine Months', 'تسع شهور', [
  P(('جار جحا كان مستعجل.', "Juha's neighbour was in a hurry."),
    ('دايماً مستعجل.', "Always in a hurry."),
    ('وبيوم، طلب من جحا شغلة.', "And one day, he asked Juha for a job."),
    ('يصلح له باب.', "To fix a door for him."),
    ('قال جحا: طيب.', "Juha said: fine."),
    ('وبلش.', "And began.")),
  P(('تاني يوم، الجار إجا.', "The next day, the neighbour came."),
    ('قال: خلصت؟', "He said: finished?"),
    ('قال جحا: لسا.', "Juha said: not yet."),
    ('تالت يوم، الجار إجا.', "The third day, the neighbour came."),
    ('قال: خلصت؟', "He said: finished?"),
    ('قال جحا: لسا.', "Juha said: not yet."),
    ('قال الجار: إمتى بتخلص؟', "The neighbour said: when will you finish?")),
  P(('قال جحا: بتسع شهور.', "Juha said: in nine months."),
    ('قال الجار: تسع شهور؟!', "The neighbour said: nine months?!"),
    ('هاي شغلة يومين!', "This is a two-day job!"),
    ('باب!', "A door!"),
    ('قال جحا: بعرف.', "Juha said: I know."),
    ('قال الجار: فليش تسع شهور؟', "The neighbour said: then why nine months?")),
  P(('قال جحا: يا جاري.', "Juha said: neighbour."),
    ('الله خلق الدنيا بستة أيام.', "God made the world in six days."),
    ('بس الولد، بده تسع شهور.', "But a child takes nine months."),
    ('كل شي حلو، بده تسع شهور.', "Everything good takes nine months."),
    ('وبابك بدي ياه حلو.', "And I want your door to be good."))]),

 ('The Guest Who Stayed', 'الضيف اللي ضل', [
  P(('ضيف إجا عند جحا.', "A guest came to Juha."),
    ('من بلد بعيد.', "From a far country."),
    ('وجحا فرح.', "And Juha was glad."),
    ('وذبح دجاجة.', "And killed a chicken."),
    ('وأكلوا.', "And they ate."),
    ('وحكوا لنص الليل.', "And talked till midnight.")),
  P(('تاني يوم، الضيف ضل.', "The next day, the guest stayed."),
    ('وجحا طبخ.', "And Juha cooked."),
    ('تالت يوم، الضيف ضل.', "The third day, the guest stayed."),
    ('وجحا طبخ.', "And Juha cooked."),
    ('رابع يوم، الضيف ضل.', "The fourth day, the guest stayed."),
    ('وما في دجاج.', "And there were no chickens left."),
    ('وجحا سكت.', "And Juha was silent.")),
  P(('وبالمسا، جحا صار يحكي.', "And in the evening, Juha began to talk."),
    ('عن السمك.', "About fish."),
    ('قال: السمك حلو.', "He said: fish is nice."),
    ('بس بعد تلات أيام، ريحته بتصير بشعة.', "But after three days, it smells bad."),
    ('والضيف زي السمك.', "And a guest is like fish."),
    ('بعد تلات أيام، بيريح.', "After three days, he should go."),
    ('الضيف ضحك.', "The guest laughed."),
    ('وقال: أنا مش سمك.', "And said: I am not a fish.")),
  P(('قال جحا: بعرف.', "Juha said: I know."),
    ('إنت مش سمك.', "You are not a fish."),
    ('قال الضيف: فليش بتحكي عن السمك؟', "The guest said: then why talk about fish?"),
    ('قال جحا: لأني جعان.', "Juha said: because I am hungry."),
    ('والدجاج خلص.', "And the chickens are finished."),
    ('والضيف فهم.', "And the guest understood."),
    ('وراح تاني يوم.', "And left the next day."))]),

 ('Which Is Older', 'مين أكبر', [
  P(('الناس بالمقهى تخانقوا.', "The people in the café were arguing."),
    ('على سؤال.', "Over a question."),
    ('الشمس أهم، ولا القمر؟', "Is the sun more important, or the moon?"),
    ('نص قالوا الشمس.', "Half said the sun."),
    ('ونص قالوا القمر.', "And half said the moon."),
    ('وقالوا: نسأل جحا.', "And they said: let us ask Juha.")),
  P(('جحا إجا.', "Juha came."),
    ('وسمع السؤال.', "And heard the question."),
    ('وفكر.', "And thought."),
    ('وشرب قهوته.', "And drank his coffee."),
    ('وفكر كمان.', "And thought some more."),
    ('وقال: القمر.', "And said: the moon.")),
  P(('نص الناس فرحوا.', "Half the people cheered."),
    ('ونص زعلوا.', "And half were upset."),
    ('قالوا: ليش القمر؟', "They said: why the moon?"),
    ('الشمس أكبر!', "The sun is bigger!"),
    ('والشمس بتدفي!', "And the sun warms!"),
    ('قال جحا: صحيح.', "Juha said: true."),
    ('بس اسمعوا.', "But listen.")),
  P(('قال جحا: القمر بيطلع بالليل.', "Juha said: the moon comes out at night."),
    ('وبالليل، الدنيا عتمة.', "And at night, the world is dark."),
    ('وإحنا محتاجين ضوء.', "And we need light."),
    ('والشمس بتطلع بالنهار.', "And the sun comes out by day."),
    ('وبالنهار، الدنيا ضوء.', "And by day, the world is light."),
    ('فشو لزومها؟', "So what is it for?"),
    ('والناس سكتوا.', "And the people fell silent."))]),

 ('The Mirror', 'المراية', [
  P(('جحا راح عالمدينة.', "Juha went to the city."),
    ('وشاف بالسوق شي بيلمع.', "And saw in the market something shining."),
    ('مراية.', "A mirror."),
    ('ما شاف مراية بحياته.', "He had never seen a mirror in his life."),
    ('واشتراها.', "And he bought it."),
    ('وجابها عالبيت.', "And brought it home.")),
  P(('وفتحها.', "And opened it."),
    ('وتطلع فيها.', "And looked in it."),
    ('وشاف رجل.', "And saw a man."),
    ('رجل كبير بالعمر.', "An old man."),
    ('شعره أبيض.', "His hair white."),
    ('ولحيته طويلة.', "And his beard long."),
    ('قال جحا: مين هاد؟', "Juha said: who is this?")),
  P(('وخاف.', "And he was frightened."),
    ('وسكر المراية.', "And shut the mirror."),
    ('وراح لمرته.', "And went to his wife."),
    ('وقال: في زلمة بالمراية.', "And said: there is a man in the mirror."),
    ('زلمة كبير.', "An old man."),
    ('ما بعرفه.', "I do not know him."),
    ('تعالي شوفي.', "Come and see.")),
  P(('مرته إجت.', "His wife came."),
    ('وفتحت المراية.', "And opened the mirror."),
    ('وتطلعت.', "And looked."),
    ('وشافت مرا.', "And saw a woman."),
    ('مرا كبيرة بالعمر.', "An old woman."),
    ('وصرخت: يا جحا!', "And cried: Juha!"),
    ('مش بس زلمة!', "Not only a man!"),
    ('في مرا كمان!', "There is a woman too!"),
    ('ومين هاي؟', "And who is she?"))]),

 ('The Wrong Grave', 'القبر الغلط', [
  P(('جحا مشى بالليل.', "Juha was walking at night."),
    ('برا القرية.', "Outside the village."),
    ('والطريق فاضية.', "And the road was empty."),
    ('وسمع أصوات.', "And he heard voices."),
    ('ناس جايين.', "People coming."),
    ('وخاف.', "And he was afraid."),
    ('قال: يمكن حرامية.', "He said: maybe thieves.")),
  P(('وشاف حفرة.', "And he saw a hole."),
    ('حفرة عالطريق.', "A hole by the road."),
    ('زي القبر.', "Like a grave."),
    ('ونزل فيها.', "And he got into it."),
    ('وتمدد.', "And lay down."),
    ('وسكر عينه.', "And closed his eyes."),
    ('وما تحرك.', "And did not move.")),
  P(('الناس وصلوا.', "The people arrived."),
    ('وشافوا الحفرة.', "And saw the hole."),
    ('وشافوا جحا.', "And saw Juha."),
    ('وقالوا: مين هاد؟', "And said: who is this?"),
    ('وشو بيعمل هون؟', "And what is he doing here?"),
    ('جحا فتح عين وحدة.', "Juha opened one eye."),
    ('وقال: أنا ميت.', "And said: I am dead.")),
  P(('الناس ضحكوا.', "The people laughed."),
    ('قالوا: ميت؟', "They said: dead?"),
    ('والميت بيحكي؟', "And does a dead man talk?"),
    ('قال جحا: بيحكي.', "Juha said: he talks."),
    ('قالوا: إمتى؟', "They said: when?"),
    ('قال جحا: إذا كان جعان.', "Juha said: if he is hungry."),
    ('والناس ضحكوا أكتر.', "And the people laughed more."),
    ('وأعطوه خبز.', "And gave him bread."))]),

 ('The Egg', 'البيضة', [
  P(('جحا ماشي بالطريق.', "Juha was walking along the road."),
    ('وشاف بيضة.', "And saw an egg."),
    ('بيضة عالأرض.', "An egg on the ground."),
    ('ورفعها.', "And picked it up."),
    ('وحطها بإيده.', "And held it in his hand."),
    ('وصار يفكر.', "And began to think.")),
  P(('قال: من هاي البيضة، بتطلع دجاجة.', "He said: from this egg, a hen comes."),
    ('والدجاجة بتبيض.', "And the hen lays eggs."),
    ('بيض كتير.', "A lot of eggs."),
    ('ومن البيض، دجاج.', "And from the eggs, hens."),
    ('دجاج كتير.', "A lot of hens."),
    ('وببيع الدجاج.', "And I sell the hens.")),
  P(('وبالمصاري، بشتري خروف.', "And with the money, I buy a sheep."),
    ('والخروف بيصير خرفان.', "And the sheep becomes sheep."),
    ('وببيع الخرفان.', "And I sell the sheep."),
    ('وبشتري بقرة.', "And buy a cow."),
    ('وبعدين أرض.', "And then land."),
    ('وبعدين بيت.', "And then a house."),
    ('وبصير غني!', "And I become rich!"),
    ('ورفع إيده بالهوا.', "And he raised his hand in the air.")),
  P(('والبيضة وقعت.', "And the egg fell."),
    ('عالأرض.', "On the ground."),
    ('وانكسرت.', "And broke."),
    ('وجحا تطلع فيها.', "And Juha looked at it."),
    ('وقال: يا خسارة.', "And said: what a pity."),
    ('راحت الدجاجة.', "The hen is gone."),
    ('والخرفان، والبقرة، والبيت.', "And the sheep, the cow, the house."),
    ('راحت كل مصاريي.', "All my money is gone."))]),

 ('Teaching the Donkey', 'تعليم الحمار', [
  P(('الحاكم كان عنده حمار.', "The ruler had a donkey."),
    ('وكان بيحبه.', "And he loved it."),
    ('وبيوم، نادى جحا.', "And one day, he called Juha."),
    ('وقال: يا جحا.', "And said: Juha."),
    ('إنت رجل عالم.', "You are a learned man."),
    ('علّم حماري يقرا.', "Teach my donkey to read.")),
  P(('جحا تطلع بالحمار.', "Juha looked at the donkey."),
    ('وتطلع بالحاكم.', "And looked at the ruler."),
    ('وقال: طيب.', "And said: fine."),
    ('بس بحاجة وقت.', "But I need time."),
    ('قال الحاكم: قديش؟', "The ruler said: how long?"),
    ('قال جحا: عشر سنين.', "Juha said: ten years."),
    ('قال الحاكم: طيب. عشر سنين.', "The ruler said: fine. Ten years."),
    ('وإذا ما قرا، بقطع راسك.', "And if it does not read, I cut off your head.")),
  P(('جحا طلع.', "Juha went out."),
    ('والناس ركضوا عليه.', "And the people ran to him."),
    ('قالوا: يا جحا! إنت مجنون!', "They said: Juha! You are mad!"),
    ('الحمار ما بيقرا!', "A donkey cannot read!"),
    ('بعد عشر سنين، بيقطع راسك!', "In ten years, he cuts off your head!")),
  P(('جحا ضحك.', "Juha laughed."),
    ('وقال: عشر سنين طويلة.', "And said: ten years is a long time."),
    ('وبعشر سنين، بيصير كتير شي.', "And in ten years, a lot happens."),
    ('يا بيموت الحاكم.', "Either the ruler dies."),
    ('يا بيموت الحمار.', "Or the donkey dies."),
    ('يا بموت أنا.', "Or I die."),
    ('ومين بيقطع راس مين؟', "And who cuts off whose head?"))]),

 ('The Fastest Way', 'أسرع طريق', [
  P(('واحد غريب وقف جحا.', "A stranger stopped Juha."),
    ('بالطريق.', "On the road."),
    ('وقال: يا عمي.', "And said: uncle."),
    ('قديش بدي وقت؟', "How long do I need?"),
    ('عشان أوصل عالبلد.', "To reach the town."),
    ('جحا تطلع فيه.', "Juha looked at him."),
    ('وما رد.', "And did not answer.")),
  P(('الرجل سأل كمان مرة.', "The man asked again."),
    ('قديش بدي وقت؟', "How long do I need?"),
    ('وجحا ما رد.', "And Juha did not answer."),
    ('الرجل زعل.', "The man was annoyed."),
    ('وقال: أطرش.', "And said: deaf."),
    ('ومشى.', "And walked on.")),
  P(('مشى الرجل شوي.', "The man walked a little."),
    ('عشر خطوات، عشرين.', "Ten steps, twenty."),
    ('وجحا بيتفرج عليه.', "And Juha watched him."),
    ('وبعدين صرخ: يا رجل!', "And then shouted: hey, man!"),
    ('بساعتين!', "Two hours!"),
    ('الرجل وقف.', "The man stopped."),
    ('ولف.', "And turned.")),
  P(('وقال: ساعتين؟', "And said: two hours?"),
    ('وليش ما حكيت من الأول؟', "Why did you not say so at first?"),
    ('قال جحا: كيف بحكي؟', "Juha said: how could I?"),
    ('لازم أشوف كيف بتمشي.', "I had to see how you walk."),
    ('إنت بتمشي بطيء.', "You walk slowly."),
    ('فساعتين.', "So two hours."))]),

 ('The Two Ends', 'الطرفين', [
  P(('جحا طلع على شجرة.', "Juha climbed a tree."),
    ('بده حطب.', "He wanted firewood."),
    ('وقعد على غصن.', "And sat on a branch."),
    ('غصن كبير.', "A big branch."),
    ('وأخد المنشار.', "And took the saw."),
    ('وبلش يقص الغصن.', "And began sawing the branch."),
    ('من جهة الشجرة.', "On the tree side."),
    ('وهو قاعد عالطرف التاني.', "While sitting on the other end.")),
  P(('مر واحد تحت الشجرة.', "A man passed under the tree."),
    ('وتطلع لفوق.', "And looked up."),
    ('وقال: يا جحا!', "And said: Juha!"),
    ('إنت قاعد عالغصن.', "You are sitting on the branch."),
    ('وبتقصه.', "And sawing it."),
    ('رح توقع!', "You will fall!"),
    ('جحا قال: روح لحالك.', "Juha said: go about your business."),
    ('أنا بعرف شغلي.', "I know my work."),
    ('والرجل مشى.', "And the man walked on.")),
  P(('وجحا كمل.', "And Juha went on."),
    ('قص، وقص.', "Sawed, and sawed."),
    ('والغصن انكسر.', "And the branch broke."),
    ('وجحا وقع.', "And Juha fell."),
    ('عالأرض.', "To the ground."),
    ('وقعد، وتطلع حواليه.', "And sat up, and looked around."),
    ('وقال: الرجل عرف!', "And said: the man knew!"),
    ('قبل ما أوقع!', "Before I fell!")),
  P(('وقام جحا.', "And Juha got up."),
    ('وركض ورا الرجل.', "And ran after the man."),
    ('ومسكه.', "And caught him."),
    ('وقال: إنت بتعرف الغيب!', "And said: you know the future!"),
    ('عرفت إني رح أوقع.', "You knew I would fall."),
    ('قول لي إمتى بموت!', "Tell me when I will die!"),
    ('والرجل هرب.', "And the man fled."))]),

 ('The Bag of Onions', 'كيس البصل', [
  P(('جحا راح عالسوق.', "Juha went to the market."),
    ('واشترى بصل.', "And bought onions."),
    ('كيس كبير.', "A big sack."),
    ('وحمله على ظهره.', "And carried it on his back."),
    ('والطريق للبيت طويلة.', "And the road home was long."),
    ('والكيس تقيل.', "And the sack was heavy.")),
  P(('مشى جحا شوي.', "Juha walked a little."),
    ('وتعب.', "And grew tired."),
    ('ووقف.', "And stopped."),
    ('وحط الكيس.', "And put the sack down."),
    ('وفتحه.', "And opened it."),
    ('وعد البصلات.', "And counted the onions."),
    ('واحد، اتنين، تلاتة...', "One, two, three..."),
    ('وحمله، ومشى.', "And picked it up, and walked.")),
  P(('وبعد شوي، وقف كمان.', "And a little later, he stopped again."),
    ('وعد البصلات.', "And counted the onions."),
    ('وحمله، ومشى.', "And picked it up, and walked."),
    ('ووقف، وعد.', "And stopped, and counted."),
    ('كل شوي.', "Every little while."),
    ('وواحد كان ماشي وراه.', "And someone was walking behind him."),
    ('وبيتفرج.', "And watching.")),
  P(('قال الرجل: يا جحا.', "The man said: Juha."),
    ('ليش بتعد البصل؟', "Why do you count the onions?"),
    ('كل شوي؟', "Every little while?"),
    ('حدا بيسرق منه؟', "Is someone stealing from it?"),
    ('قال جحا: لا.', "Juha said: no."),
    ('بس كل ما بعد، بنسى إني تعبان.', "But every time I count, I forget I am tired."),
    ('وبقدر أكمل.', "And I can go on."))]),

 ('Two Dinners', 'عزيمتين', [
  P(('جحا انعزم على عشا.', "Juha was invited to dinner."),
    ('عند جاره الأول.', "At his first neighbour's."),
    ('يوم الخميس.', "On Thursday."),
    ('وفرح.', "And he was glad."),
    ('وبعدين إجا جاره التاني.', "And then his second neighbour came."),
    ('وعزمه على عشا.', "And invited him to dinner."),
    ('يوم الخميس كمان.', "On Thursday too."),
    ('نفس الليلة.', "The same night.")),
  P(('جحا فكر.', "Juha thought."),
    ('على وين بروح؟', "Where do I go?"),
    ('الأول بيطبخ لحمة.', "The first cooks meat."),
    ('والتاني بيطبخ دجاج.', "And the second cooks chicken."),
    ('وأنا بحب الاتنين.', "And I love both."),
    ('وقال: بروح عالاتنين.', "And said: I will go to both.")),
  P(('يوم الخميس، راح عالأول.', "On Thursday, he went to the first."),
    ('وأكل لحمة.', "And ate meat."),
    ('كتير.', "A lot."),
    ('وقال: عندي شغلة.', "And said: I have an errand."),
    ('وطلع.', "And left."),
    ('وراح عالتاني.', "And went to the second."),
    ('وأكل دجاج.', "And ate chicken."),
    ('كتير.', "A lot.")),
  P(('ورجع عالبيت.', "And he went home."),
    ('بطيء.', "Slowly."),
    ('وبطنه كبير.', "His belly big."),
    ('وبيوجعه.', "And aching."),
    ('وما نام كل الليل.', "And he did not sleep all night."),
    ('وبالصبح قال: تعلمت.', "And in the morning he said: I have learned."),
    ('عزيمة وحدة أحسن من عزيمتين.', "One dinner is better than two."))]),

 ('The Neighbour Who Never Returns', 'الجار اللي ما بيرجّع', [
  P(('جار جحا كان بيستعير.', "Juha's neighbour borrowed things."),
    ('كل يوم شي.', "Something every day."),
    ('وما بيرجع.', "And never returned them."),
    ('استعار المنشار.', "He borrowed the saw."),
    ('وما رجعه.', "And did not return it."),
    ('استعار الحبل.', "He borrowed the rope."),
    ('وما رجعه.', "And did not return it."),
    ('استعار السلم.', "He borrowed the ladder."),
    ('وما رجعه.', "And did not return it.")),
  P(('وجحا ساكت.', "And Juha said nothing."),
    ('مستحي يطلب.', "Too shy to ask."),
    ('وبيوم، الجار إجا.', "And one day, the neighbour came."),
    ('وقال: يا جحا.', "And said: Juha."),
    ('بدي حمارك.', "I want your donkey."),
    ('يوم واحد.', "One day."),
    ('جحا تطلع فيه.', "Juha looked at him.")),
  P(('وقال: يا خسارة.', "And said: what a pity."),
    ('الحمار مش هون.', "The donkey is not here."),
    ('مسافر.', "It is away."),
    ('قال الجار: مسافر؟', "The neighbour said: away?"),
    ('لوين؟', "Where to?"),
    ('قال جحا: لعندك.', "Juha said: to your place.")),
  P(('قال الجار: لعندي؟', "The neighbour said: to my place?"),
    ('ليش؟', "Why?"),
    ('قال جحا: راح يجيب أغراضي.', "Juha said: to fetch my things."),
    ('المنشار، والحبل، والسلم.', "The saw, the rope, the ladder."),
    ('لما يرجع، بعطيك ياه.', "When it comes back, I lend it to you."),
    ('والجار احمر.', "And the neighbour went red."),
    ('وراح.', "And left."),
    ('ورجع بعد ساعة.', "And came back an hour later."),
    ('ومعه المنشار، والحبل، والسلم.', "With the saw, the rope, and the ladder."))]),

 ('The Sweetest Thing', 'أحلى إشي', [
  P(('الناس قعدوا بالمقهى.', "The people sat in the café."),
    ('وسألوا جحا.', "And asked Juha."),
    ('شو أحلى شي بالدنيا؟', "What is the sweetest thing in the world?"),
    ('جحا فكر.', "Juha thought."),
    ('وقال: العسل.', "And said: honey."),
    ('الناس ضحكوا.', "The people laughed.")),
  P(('قال واحد: لا.', "One said: no."),
    ('المصاري أحلى.', "Money is sweeter."),
    ('قال تاني: لا.', "Another said: no."),
    ('الحب أحلى.', "Love is sweeter."),
    ('قال تالت: لا.', "A third said: no."),
    ('النوم أحلى.', "Sleep is sweeter."),
    ('وتخانقوا.', "And they argued.")),
  P(('وقال واحد: والصحة يا جحا؟', "And one said: and health, Juha?"),
    ('مش الصحة أحلى شي؟', "Is health not the sweetest thing?"),
    ('جحا هز راسه.', "Juha shook his head."),
    ('وقال: لا.', "And said: no."),
    ('الناس استغربوا.', "The people were surprised."),
    ('قالوا: ليش؟', "They said: why?")),
  P(('قال جحا: العسل شي بالدنيا.', "Juha said: honey is a thing in the world."),
    ('والمصاري شي بالدنيا.', "And money is a thing in the world."),
    ('والنوم شي بالدنيا.', "And sleep is a thing in the world."),
    ('بس الصحة، مش شي بالدنيا.', "But health is not a thing in the world."),
    ('الصحة هي الدنيا.', "Health is the world."),
    ('بلاها، ما في دنيا.', "Without it, there is no world."))]),

 ('The Empty Purse', 'الجزدان الفاضي', [
  P(('بالليل، حرامي فات على بيت جحا.', "At night, a thief got into Juha's house."),
    ('من الشباك.', "Through the window."),
    ('بالعتمة.', "In the dark."),
    ('وصار يدور.', "And began searching."),
    ('بالخزانة.', "In the cupboard."),
    ('وتحت السرير.', "And under the bed."),
    ('وبالصناديق.', "And in the boxes."),
    ('وما لقى شي.', "And found nothing.")),
  P(('جحا فاق.', "Juha woke."),
    ('وسمع الحرامي.', "And heard the thief."),
    ('وما خاف.', "And was not afraid."),
    ('قام من السرير.', "He got out of bed."),
    ('وراح جنبه.', "And went beside him."),
    ('وصار يدور معه.', "And began searching with him."),
    ('بالعتمة.', "In the dark."),
    ('بهدوء.', "Quietly.")),
  P(('الحرامي حس بحدا.', "The thief sensed someone."),
    ('ولف.', "And turned."),
    ('وشاف جحا.', "And saw Juha."),
    ('وخاف.', "And was frightened."),
    ('وقال: مين إنت؟', "And said: who are you?"),
    ('قال جحا: صاحب البيت.', "Juha said: the owner of the house."),
    ('قال الحرامي: وشو بتعمل؟', "The thief said: and what are you doing?")),
  P(('قال جحا: بساعدك.', "Juha said: helping you."),
    ('قال الحرامي: بتساعدني؟', "The thief said: helping me?"),
    ('قال جحا: أي.', "Juha said: yes."),
    ('أنا بدور بهالبيت كل يوم.', "I search this house every day."),
    ('بالنهار.', "By day."),
    ('وما بلاقي شي.', "And find nothing."),
    ('بلكي بالليل بيبان.', "Maybe at night something turns up."),
    ('والحرامي طلع من الشباك.', "And the thief went out the window."),
    ('وهو بيضحك.', "Laughing."))]),

 ('The Wise Fool', 'المجنون العاقل', [
  P(('ولاد الحي كانوا يضحكوا على جحا.', "The neighbourhood boys used to laugh at Juha."),
    ('كل يوم.', "Every day."),
    ('بيقولوا: جحا غبي.', "They said: Juha is stupid."),
    ('وعندهم لعبة.', "And they had a game."),
    ('بيعطوه قرشين.', "They offered him two coins."),
    ('واحد كبير.', "One big."),
    ('وواحد زغير.', "And one small."),
    ('وبيقولوا: خد واحد.', "And said: take one.")),
  P(('وجحا بياخد الزغير.', "And Juha took the small one."),
    ('كل مرة.', "Every time."),
    ('والولاد بيضحكوا.', "And the boys laughed."),
    ('بيقولوا: شفتوا؟', "They said: you see?"),
    ('غبي!', "Stupid!"),
    ('ما بيعرف الكبير من الزغير!', "He cannot tell big from small!"),
    ('وبيرجعوا تاني يوم.', "And they came back the next day.")),
  P(('وبيوم، واحد كبير شاف.', "And one day, a grown man saw."),
    ('وزعل عالولاد.', "And was upset with the boys."),
    ('وأخد جحا عالجنب.', "And took Juha aside."),
    ('وقال: يا جحا.', "And said: Juha."),
    ('القرش الكبير بيسوى أكتر.', "The big coin is worth more."),
    ('خد الكبير.', "Take the big one."),
    ('لا تخليهم يضحكوا عليك.', "Do not let them laugh at you.")),
  P(('جحا ضحك.', "Juha laughed."),
    ('وقال: بعرف.', "And said: I know."),
    ('قال الرجل: فليش بتاخد الزغير؟', "The man said: then why take the small one?"),
    ('قال جحا: فكر.', "Juha said: think."),
    ('لو أخدت الكبير مرة، بيبطلوا يلعبوا.', "If I took the big one once, they would stop playing."),
    ('وما بضل آخد ولا قرش.', "And I would get no coins at all."),
    ('هيك، بآخد قرش كل يوم.', "This way, I get a coin every day."),
    ('من عشر سنين.', "For ten years now."))]),

 ('The Letter', 'المكتوب', [
  P(('واحد إجا لجحا.', "A man came to Juha."),
    ('وقال: إنت بتعرف تكتب.', "And said: you can write."),
    ('اكتب لي مكتوب.', "Write me a letter."),
    ('لأخوي بالمدينة.', "To my brother in the city."),
    ('جحا قال: ما بقدر.', "Juha said: I cannot."),
    ('قال الرجل: ليش؟', "The man said: why?")),
  P(('قال جحا: إجري بتوجعني.', "Juha said: my leg hurts."),
    ('الرجل استغرب.', "The man was puzzled."),
    ('وقال: إجرك؟', "And said: your leg?"),
    ('شو دخل إجرك بالكتابة؟', "What has your leg to do with writing?"),
    ('إنت بتكتب بإيدك.', "You write with your hand."),
    ('مش بإجرك.', "Not your leg.")),
  P(('قال جحا: صحيح.', "Juha said: true."),
    ('بكتب بإيدي.', "I write with my hand."),
    ('بس خطي بشع.', "But my handwriting is awful."),
    ('ما حدا بيقراه.', "No one can read it."),
    ('غيري أنا.', "Except me.")),
  P(('قال الرجل: يعني؟', "The man said: meaning?"),
    ('قال جحا: يعني بكتب المكتوب.', "Juha said: meaning I write the letter."),
    ('وأخوك ما بيقدر يقراه.', "And your brother cannot read it."),
    ('فلازم أمشي لعنده.', "So I must walk to him."),
    ('للمدينة.', "To the city."),
    ('وأقراه له.', "And read it to him."),
    ('وإجري بتوجعني.', "And my leg hurts."),
    ('فما بقدر.', "So I cannot."))]),

 ('The Full Moon', 'القمر البدر', [
  P(('جحا وصاحبه قعدوا برا.', "Juha and his friend sat outside."),
    ('بالليل.', "At night."),
    ('على السطح.', "On the roof."),
    ('والقمر بدر.', "And the moon was full."),
    ('كبير، وأبيض.', "Big, and white."),
    ('وصاروا يتطلعوا فيه.', "And they gazed at it."),
    ('طويل.', "For a long time.")),
  P(('قال صاحبه: يا جحا.', "His friend said: Juha."),
    ('القمر حلو.', "The moon is beautiful."),
    ('قال جحا: حلو.', "Juha said: beautiful."),
    ('قال صاحبه: وكل شهر بيصير بدر.', "His friend said: and every month it becomes full."),
    ('وبعدين بيصغر.', "And then it shrinks."),
    ('وبيختفي.', "And disappears."),
    ('وبيرجع جديد.', "And comes back new.")),
  P(('قال صاحبه: عندي سؤال.', "His friend said: I have a question."),
    ('القمر القديم.', "The old moon."),
    ('لما يختفي.', "When it disappears."),
    ('وين بيروح؟', "Where does it go?"),
    ('شو بيصير فيه؟', "What becomes of it?"),
    ('جحا فكر.', "Juha thought."),
    ('وتطلع بالسما.', "And looked at the sky.")),
  P(('وشاف النجوم.', "And saw the stars."),
    ('نجوم كتيرة.', "Many stars."),
    ('زغيرة، وبتلمع.', "Small, and shining."),
    ('وقال: فهمت.', "And said: I understand."),
    ('القمر القديم بياخدوه.', "They take the old moon."),
    ('وبيكسروه.', "And break it up."),
    ('قطع زغيرة.', "Into little pieces."),
    ('وبيعملوا منه نجوم.', "And make stars from it."))]),

 ('Everyone Is a Little Right', 'كل واحد شوي على حق', [
  P(('جحا صار كبير كتير.', "Juha grew very old."),
    ('شعره أبيض.', "His hair white."),
    ('وظهره منحني.', "His back bent."),
    ('وعينه ضعيفة.', "His eyes weak."),
    ('والناس بيحبوه.', "And the people loved him."),
    ('وبيوم، اجتمعوا حواليه.', "And one day, they gathered around him.")),
  P(('وقالوا: يا جحا.', "And said: Juha."),
    ('عشت عمر طويل.', "You have lived a long life."),
    ('وشفت كتير.', "And seen a lot."),
    ('وضحكت كتير.', "And laughed a lot."),
    ('قول لنا.', "Tell us."),
    ('شو تعلمت؟', "What have you learned?")),
  P(('جحا فكر.', "Juha thought."),
    ('وشرب قهوته.', "And drank his coffee."),
    ('وقال: تعلمت تلات أشيا.', "And said: I have learned three things."),
    ('الأول: أنا ما بعرف كتير.', "The first: I do not know much."),
    ('وكل ما بكبر، بعرف أقل.', "And the older I get, the less I know."),
    ('والناس ضحكوا.', "And the people laughed.")),
  P(('قال جحا: التاني.', "Juha said: the second."),
    ('اللي بيضحك، بيعيش أطول.', "Whoever laughs lives longer."),
    ('واللي بيزعل، بيموت مرتين.', "And whoever frets dies twice."),
    ('والناس ضحكوا.', "And the people laughed."),
    ('قال جحا: والتالت.', "Juha said: and the third."),
    ('الحمار بيفهم أكتر من صاحبه.', "The donkey understands more than its master."),
    ('بس بيسكت.', "But keeps quiet."),
    ('والناس ضحكوا كتير.', "And the people laughed a lot."),
    ('وجحا ضحك معهم.', "And Juha laughed with them."),
    ('وكل واحد فيهم كان شوي على حق.', "And every one of them was a little right."))]),
]

if __name__ == '__main__':
    raise SystemExit(book(BOOK_ID, BOOK_TITLE, 'beginner', CHAPTERS, unit='Tale', unit_ar='حكاية', shelf=1,
              meta={'work': 'the Juha / Nasreddin folk tales', 'author': 'traditional',
                    'year': 'medieval', 'status': 'public domain — folk material, no known author'}))
