#!/usr/bin/env python3
"""خرافات إيسوب — thirty fables, retold in spoken Palestinian, graded to beginner.

Aesop's fables are ancient and anonymous in any practical sense — public domain by age, with no
edition being translated. These are retellings from the traditional plots.

WHY THIS SITS BESIDE JUHA. The animal-fable shape is already familiar to an Arabic learner from
كليلة ودمنة, and the plots are known in English, so nothing is spent on working out what happens
— all of the attention goes to the Arabic. Where Juha teaches the rhythm of everyday speech, these
teach the rhythm of narrative: a setup, a turn, a line at the end.

Written against what pipeline/bookshelf_check.py measures, and tighter than Juha was on its first
pass: sentences at or under ~25 Arabic characters, one clause each, a small recurring cast of
animals (ثعلب، أسد، فار، ذيب، غراب) so the same words come back fable after fable.

Each fable ends on its moral as a separate short sentence rather than a clause tacked onto the
action — which keeps the last line quotable and the sentence length down at the same time.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_aesop.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, emit_book

BOOK_ID = 'aesop'
BOOK_TITLE = {'en': "Aesop's Fables", 'ar': 'خرافات إيسوب'}

# (english title, arabic title, [paragraph, ...])
#
# SECOND EDITION (2026-09-03). Same thirty fables and titles, each told out in full at the same
# beginner register — short sentences, one clause each, the moral as its own last line — with
# the setup, the talk and the turn given their room instead of a line apiece.
CHAPTERS = [
 ('The Oak and the Reed', 'السنديانة والقصبة', [
  P(('على شط النهر، كان في سنديانة.', "On the river bank, there was an oak."),
    ('سنديانة كبيرة وقوية.', "A big, strong oak."),
    ('وجنبها قصبة.', "And beside it, a reed."),
    ('قصبة رفيعة وطويلة.', "A thin, tall reed."),
    ('كل يوم، الريح بتيجي.', "Every day, the wind came."),
    ('والقصبة بتنحني.', "And the reed bent."),
    ('والسنديانة ما بتتحرك.', "And the oak did not move.")),
  P(('بيوم، السنديانة ضحكت.', "One day, the oak laughed."),
    ('قالت: شوفي حالك!', "It said: look at yourself!"),
    ('كل ريح بتنحني لها.', "You bow to every wind."),
    ('إنتِ ضعيفة.', "You are weak."),
    ('أنا قوية.', "I am strong."),
    ('أنا ما بنحني لحدا.', "I bow to no one.")),
  P(('قالت القصبة: صحيح.', "The reed said: true."),
    ('أنا بنحني.', "I bend."),
    ('بس بعد الريح، بقوم.', "But after the wind, I stand up."),
    ('قالت السنديانة: هاد ضعف.', "The oak said: that is weakness."),
    ('قالت القصبة: يمكن.', "The reed said: perhaps."),
    ('وسكتت.', "And fell silent.")),
  P(('بالليل، إجت عاصفة.', "At night, a storm came."),
    ('عاصفة كبيرة، ما شافوا زيها.', "A big storm, like none they had seen."),
    ('القصبة انحنت لحد الأرض.', "The reed bent to the ground."),
    ('والسنديانة وقفت.', "And the oak stood."),
    ('وقفت، ووقفت.', "It stood, and stood."),
    ('وبعدين، صار صوت كبير.', "And then, there was a great sound."),
    ('السنديانة انكسرت.', "The oak broke."),
    ('ووقعت بالنهر.', "And fell into the river.")),
  P(('بالصبح، الريح راحت.', "In the morning, the wind was gone."),
    ('القصبة قامت.', "The reed stood up."),
    ('وتطلعت حواليها.', "And looked around."),
    ('السنديانة مش موجودة.', "The oak was not there."),
    ('اللي بينحني ما بينكسر.', "What bends does not break."))]),

 ('The Fox and the Grapes', 'الثعلب والعنب', [
  P(('كان في ثعلب جعان.', "There was a hungry fox."),
    ('مشى بالحقل كل الصبح.', "He walked in the field all morning."),
    ('ما لقى أكل.', "He found no food."),
    ('وبعدين شاف كرمة.', "And then he saw a vine."),
    ('وعالكرمة، عنب.', "And on the vine, grapes."),
    ('عنب كبير، ولونه أحمر.', "Big grapes, red in colour."),
    ('بس العنب عالي.', "But the grapes were high up.")),
  P(('قال الثعلب: سهلة.', "The fox said: easy."),
    ('نط مرة.', "He jumped once."),
    ('ما وصل.', "He did not reach."),
    ('نط مرتين.', "He jumped twice."),
    ('ما وصل.', "He did not reach."),
    ('رجع لورا، وركض، ونط.', "He went back, ran, and jumped."),
    ('ما وصل.', "He did not reach.")),
  P(('قعد الثعلب عالأرض.', "The fox sat on the ground."),
    ('كان تعبان.', "He was tired."),
    ('وتطلع عالعنب.', "And looked at the grapes."),
    ('والعنب بيلمع بالشمس.', "And the grapes shone in the sun."),
    ('قال: مرة كمان.', "He said: once more."),
    ('ونط، وما وصل.', "And he jumped, and did not reach."),
    ('وشاف عصفور بيتفرج عليه.', "And he saw a bird watching him.")),
  P(('قام الثعلب.', "The fox got up."),
    ('ونفض حاله.', "And shook himself."),
    ('ومشى.', "And walked off."),
    ('وقال بصوت عالي: العنب حامض.', "And said out loud: the grapes are sour."),
    ('ما بدي ياه.', "I do not want them."),
    ('والعصفور ضحك.', "And the bird laughed."),
    ('اللي ما بيقدر عليه، بيعيبه.', "What a person cannot get, he finds fault with."))]),

 ('The Tortoise and the Hare', 'السلحفاة والأرنب', [
  P(('الأرنب كان أسرع واحد بالغابة.', "The hare was the fastest one in the forest."),
    ('وكان بيعرف.', "And he knew it."),
    ('كل يوم بيقول: أنا أسرع واحد.', "Every day he said: I am the fastest."),
    ('وبيضحك على البطيئين.', "And laughed at the slow ones."),
    ('وأبطأ واحد بالغابة، السلحفاة.', "And the slowest in the forest was the tortoise."),
    ('بيوم، قال لها: يا سلحفاة!', "One day, he said to her: tortoise!"),
    ('إنتِ بتمشي ولا واقفة؟', "Are you walking or standing still?")),
  P(('قالت السلحفاة: بمشي.', "The tortoise said: I am walking."),
    ('وبوصل.', "And I arrive."),
    ('قال الأرنب: بتوصلي؟', "The hare said: you arrive?"),
    ('يلا نتسابق.', "Come, let us race."),
    ('قالت السلحفاة: طيب.', "The tortoise said: fine."),
    ('كل الحيوانات إجت تتفرج.', "All the animals came to watch."),
    ('والثعلب قال: واحد، اتنين، تلاتة!', "And the fox said: one, two, three!")),
  P(('الأرنب ركض زي الريح.', "The hare ran like the wind."),
    ('بدقيقة، صار بعيد.', "In a minute, he was far away."),
    ('تطلع لورا.', "He looked back."),
    ('السلحفاة لسا عند البداية.', "The tortoise was still at the start."),
    ('قال: هاي مش سباق.', "He said: this is no race."),
    ('بنام شوي.', "I will sleep a little."),
    ('وقعد تحت شجرة.', "And sat under a tree."),
    ('ونام.', "And slept.")),
  P(('السلحفاة مشيت.', "The tortoise walked."),
    ('خطوة، وخطوة، وخطوة.', "Step, and step, and step."),
    ('ما وقفت.', "She did not stop."),
    ('ما تطلعت لورا.', "She did not look back."),
    ('مرقت جنب الأرنب.', "She passed the hare."),
    ('وهو نايم.', "And he was asleep."),
    ('وكملت.', "And went on.")),
  P(('الأرنب فاق.', "The hare woke."),
    ('وتطلع عالطريق.', "And looked at the road."),
    ('السلحفاة عند النهاية!', "The tortoise was at the finish!"),
    ('ركض بكل قوته.', "He ran with all his strength."),
    ('بس السلحفاة وصلت أول.', "But the tortoise arrived first."),
    ('والحيوانات كلها صفقت.', "And all the animals clapped."),
    ('اللي بيمشي على مهله، بيوصل.', "Slow and steady wins the race."))]),

 ('The Lion and the Mouse', 'الأسد والفار', [
  P(('الأسد كان نايم تحت شجرة.', "The lion was sleeping under a tree."),
    ('وفار زغير مرق من جنبه.', "And a little mouse passed beside him."),
    ('الفار ما شاف الأسد.', "The mouse did not see the lion."),
    ('وركض على ظهره.', "And ran over his back."),
    ('الأسد فاق.', "The lion woke."),
    ('ومسك الفار بإيده.', "And caught the mouse in his paw."),
    ('وفتح تمه.', "And opened his mouth.")),
  P(('قال الفار: لا! لا تاكلني!', "The mouse said: no! Do not eat me!"),
    ('أنا زغير.', "I am small."),
    ('ما بشبعك.', "I will not fill you."),
    ('خليني أعيش.', "Let me live."),
    ('ويمكن بيوم، بساعدك.', "And perhaps one day, I help you."),
    ('الأسد ضحك.', "The lion laughed."),
    ('قال: إنت؟ بتساعدني أنا؟', "He said: you? Help me?")),
  P(('بس الأسد كان شبعان.', "But the lion was full."),
    ('وكان مبسوط.', "And he was in a good mood."),
    ('فتح إيده.', "He opened his paw."),
    ('وقال: روح.', "And said: go."),
    ('والفار ركض.', "And the mouse ran."),
    ('وقال: شكراً! ما بنسى!', "And said: thank you! I will not forget!")),
  P(('بعد أسبوع، الأسد وقع بشبكة.', "A week later, the lion fell into a net."),
    ('شبكة صيادين.', "A hunters' net."),
    ('حاول يطلع.', "He tried to get out."),
    ('ما قدر.', "He could not."),
    ('الحبال قوية.', "The ropes were strong."),
    ('وزعق.', "And he roared."),
    ('زعق لحد ما سمعته كل الغابة.', "He roared until the whole forest heard.")),
  P(('والفار سمع.', "And the mouse heard."),
    ('وركض عالأسد.', "And ran to the lion."),
    ('وقال: أنا هون.', "And said: I am here."),
    ('وبلش يقص الحبال بأسنانه.', "And began cutting the ropes with his teeth."),
    ('حبل، وحبل، وحبل.', "Rope, and rope, and rope."),
    ('والأسد طلع.', "And the lion got out."),
    ('قال: إنت زغير، بس ساعدتني.', "He said: you are small, but you helped me."),
    ('الزغير كمان بيفيد.', "The small one is useful too."))]),

 ('The Fox and the Stork', 'الثعلب واللقلق', [
  P(('الثعلب عزم اللقلق على الغدا.', "The fox invited the stork to lunch."),
    ('قال: تعال بكرا.', "He said: come tomorrow."),
    ('عندي شوربة طيبة.', "I have good soup."),
    ('اللقلق فرح.', "The stork was glad."),
    ('وإجا تاني يوم.', "And came the next day."),
    ('والثعلب حط الشوربة بصحن.', "And the fox put the soup in a plate."),
    ('صحن مسطح، وواسع.', "A flat, wide plate.")),
  P(('الثعلب أكل بلسانه.', "The fox ate with his tongue."),
    ('لحس، ولحس، وشبع.', "He licked, and licked, and was full."),
    ('واللقلق حاول.', "And the stork tried."),
    ('منقاره طويل.', "His beak is long."),
    ('ما قدر ياكل من الصحن.', "He could not eat from the plate."),
    ('والثعلب قال: ما عجبتك الشوربة؟', "And the fox said: you do not like the soup?"),
    ('وضحك.', "And laughed."),
    ('واللقلق رجع جعان.', "And the stork went home hungry.")),
  P(('بعد يومين، اللقلق عزم الثعلب.', "Two days later, the stork invited the fox."),
    ('قال: تعال بكرا.', "He said: come tomorrow."),
    ('عندي سمك طيب.', "I have good fish."),
    ('الثعلب فرح.', "The fox was glad."),
    ('وإجا تاني يوم.', "And came the next day."),
    ('واللقلق حط السمك بجرة.', "And the stork put the fish in a jar."),
    ('جرة طويلة، ورقبتها ضيقة.', "A tall jar, with a narrow neck.")),
  P(('اللقلق أكل بمنقاره.', "The stork ate with his beak."),
    ('أكل، وأكل، وشبع.', "He ate, and ate, and was full."),
    ('والثعلب حاول.', "And the fox tried."),
    ('راسه كبير.', "His head is big."),
    ('ما فات بالجرة.', "It did not fit in the jar."),
    ('واللقلق قال: ما عجبك السمك؟', "And the stork said: you do not like the fish?"),
    ('والثعلب سكت.', "And the fox was silent."),
    ('زي ما بتعامل، بتتعامل.', "As you treat others, you are treated."))]),

 ('The Fisherman and the Little Fish', 'الصياد والسمكة الزغيرة', [
  P(('صياد فقير قعد عالبحر.', "A poor fisherman sat by the sea."),
    ('رمى الشبكة.', "He cast the net."),
    ('واستنى.', "And waited."),
    ('ساعة، وساعتين، وتلاتة.', "An hour, two, three."),
    ('ولا سمكة.', "Not one fish."),
    ('وبالآخر، حس بشي.', "And at last, he felt something."),
    ('وسحب الشبكة.', "And pulled in the net.")),
  P(('كان فيها سمكة وحدة.', "In it was one fish."),
    ('سمكة زغيرة كتير.', "A very small fish."),
    ('قد الإصبع.', "The size of a finger."),
    ('والسمكة حكت.', "And the fish spoke."),
    ('قالت: يا صياد، أنا زغيرة.', "It said: fisherman, I am small."),
    ('ما فيّ لحم.', "There is no meat on me."),
    ('ارميني بالبحر.', "Throw me back in the sea.")),
  P(('قالت السمكة: بعد سنة، بكبر.', "The fish said: in a year, I grow."),
    ('بصير سمكة كبيرة.', "I become a big fish."),
    ('ووقتها تعال وصيدني.', "And then come and catch me."),
    ('بتشبع منّي أنا وعيلتك.', "You and your family will be full from me."),
    ('الصياد سمع.', "The fisherman listened."),
    ('وتطلع بالسمكة.', "And looked at the fish."),
    ('وفكر.', "And thought.")),
  P(('وقال: لا.', "And said: no."),
    ('إنتِ بإيدي هلق.', "You are in my hand now."),
    ('والسمكة الكبيرة بالبحر.', "And the big fish is in the sea."),
    ('يمكن بتيجي، ويمكن لا.', "Maybe it comes, maybe not."),
    ('وحطها بالسلة.', "And put it in the basket."),
    ('وراح عالبيت.', "And went home."),
    ('عصفور بالإيد، ولا عشرة عالشجرة.', "A bird in the hand is worth ten in the tree."))]),

 ('The Dove and the Ant', 'الحمامة والنملة', [
  P(('نملة كانت عطشانة.', "An ant was thirsty."),
    ('راحت عالنهر تشرب.', "She went to the river to drink."),
    ('نزلت على حجر.', "She climbed down onto a stone."),
    ('والحجر كان مبلول.', "And the stone was wet."),
    ('وزحلقت.', "And she slipped."),
    ('ووقعت بالمي.', "And fell into the water."),
    ('والمي أخدتها.', "And the water carried her off.")),
  P(('النملة صرخت.', "The ant cried out."),
    ('بس صوتها زغير.', "But her voice is small."),
    ('ما حدا سمعها.', "No one heard her."),
    ('إلا حمامة.', "Except a dove."),
    ('الحمامة كانت على شجرة.', "The dove was in a tree."),
    ('وشافت النملة بالمي.', "And saw the ant in the water."),
    ('قطعت ورقة من الشجرة.', "She picked a leaf from the tree."),
    ('ورمتها بالمي.', "And dropped it in the water.")),
  P(('الورقة نزلت جنب النملة.', "The leaf landed beside the ant."),
    ('والنملة تسلقت عليها.', "And the ant climbed onto it."),
    ('والورقة وصلت للشط.', "And the leaf reached the bank."),
    ('والنملة نزلت.', "And the ant got off."),
    ('وقالت: شكراً يا حمامة.', "And said: thank you, dove."),
    ('والحمامة قالت: ولا يهمك.', "And the dove said: it is nothing.")),
  P(('بعد أيام، إجا صياد.', "Days later, a hunter came."),
    ('شاف الحمامة عالشجرة.', "He saw the dove in the tree."),
    ('ورفع بندقيته.', "And raised his gun."),
    ('الحمامة ما شافته.', "The dove did not see him."),
    ('بس النملة شافته.', "But the ant saw him."),
    ('وركضت على إجره.', "And ran up his leg."),
    ('وعضته.', "And bit him."),
    ('الصياد صرخ.', "The hunter cried out."),
    ('والحمامة سمعت، وطارت.', "And the dove heard, and flew away."),
    ('المعروف بيرجع.', "A kindness comes back."))]),

 ('The Stag at the Pool', 'الغزال والبركة', [
  P(('غزال إجا يشرب من بركة.', "A stag came to drink from a pool."),
    ('والمي كانت صافية.', "And the water was clear."),
    ('شاف حاله بالمي.', "He saw himself in the water."),
    ('زي المراية.', "Like a mirror."),
    ('وشاف قرونه.', "And saw his antlers."),
    ('قرون كبيرة، وحلوة.', "Big, beautiful antlers."),
    ('قال: شو أحلى قروني!', "He said: how lovely my antlers are!")),
  P(('وبعدين شاف إجريه.', "And then he saw his legs."),
    ('إجرين رفيعين، وطويلين.', "Thin, long legs."),
    ('قال: بس إجريّ!', "He said: but my legs!"),
    ('شو أبشعهم!', "How ugly they are!"),
    ('رفيعين زي العصي.', "Thin as sticks."),
    ('يا ريت إجريّ زي قروني.', "If only my legs were like my antlers.")),
  P(('وبنفس اللحظة، سمع صوت.', "And in that same moment, he heard a sound."),
    ('كلاب.', "Dogs."),
    ('كلاب صيد، جاية عليه.', "Hunting dogs, coming at him."),
    ('الغزال ركض.', "The stag ran."),
    ('ركض بإجريه الرفيعين.', "He ran on his thin legs."),
    ('وركض أسرع من الكلاب.', "And ran faster than the dogs."),
    ('والكلاب صارت بعيد.', "And the dogs fell far behind.")),
  P(('ودخل الغابة.', "And he entered the forest."),
    ('والشجر كتيف.', "And the trees were thick."),
    ('وقرونه علقت بالأغصان.', "And his antlers caught in the branches."),
    ('شد، وشد.', "He pulled, and pulled."),
    ('ما طلعت.', "They did not come free."),
    ('والكلاب وصلت.', "And the dogs arrived."),
    ('وقال الغزال: إجريّ خلصتني.', "And the stag said: my legs saved me."),
    ('وقروني قتلتني.', "And my antlers killed me."),
    ('الحلو مش دايماً المفيد.', "The beautiful is not always the useful."))]),

 ('The Peacock and the Crane', 'الطاووس والكركي', [
  P(('الطاووس فتح ديله.', "The peacock spread his tail."),
    ('ديل كبير، وفيه كل الألوان.', "A big tail, with every colour in it."),
    ('أخضر، وأزرق، وذهبي.', "Green, blue, gold."),
    ('وكان واقف بالشمس.', "And he stood in the sun."),
    ('ومر الكركي.', "And the crane passed."),
    ('طير رمادي، طويل، وبسيط.', "A grey bird, tall, and plain.")),
  P(('قال الطاووس: شوف ديلي.', "The peacock said: look at my tail."),
    ('وشوف ريشك.', "And look at your feathers."),
    ('ريشك رمادي.', "Your feathers are grey."),
    ('زي التراب.', "Like dust."),
    ('أنا ملك الطيور.', "I am the king of birds."),
    ('وإنت ولا شي.', "And you are nothing.")),
  P(('الكركي ما زعل.', "The crane was not upset."),
    ('قال: صحيح.', "He said: true."),
    ('ريشك أحلى من ريشي.', "Your feathers are lovelier than mine."),
    ('بس خليني أسألك سؤال.', "But let me ask you a question."),
    ('بتقدر تطير؟', "Can you fly?"),
    ('الطاووس سكت.', "The peacock was silent.")),
  P(('قال الكركي: أنا بطير.', "The crane said: I fly."),
    ('بطير فوق الغيم.', "I fly above the clouds."),
    ('وبشوف الدنيا كلها.', "And see the whole world."),
    ('وإنت بتمشي بالحديقة.', "And you walk in the garden."),
    ('وبتفتح ديلك.', "And spread your tail."),
    ('وفتح جناحاته.', "And he opened his wings."),
    ('وطار.', "And flew."),
    ('الشكل شي، والفايدة شي تاني.', "Looks are one thing, and use is another."))]),

 ('The Wolf and the Crane', 'الذيب والكركي', [
  P(('الذيب أكل بسرعة.', "The wolf ate fast."),
    ('أكل زي دايماً.', "He ate as he always does."),
    ('وعظمة علقت بحلقه.', "And a bone stuck in his throat."),
    ('ما قدر يبلع.', "He could not swallow."),
    ('ما قدر يحكي منيح.', "He could not speak well."),
    ('وخاف.', "And he was afraid."),
    ('وراح يدور على مساعدة.', "And went looking for help.")),
  P(('كل الحيوانات خافت منه.', "All the animals were afraid of him."),
    ('ما حدا قرب.', "No one came near."),
    ('إلا الكركي.', "Except the crane."),
    ('قال الذيب: يا كركي، منقارك طويل.', "The wolf said: crane, your beak is long."),
    ('طلع العظمة من حلقي.', "Take the bone out of my throat."),
    ('وبعطيك هدية كبيرة.', "And I give you a big gift.")),
  P(('الكركي خاف.', "The crane was afraid."),
    ('بس الهدية كبيرة.', "But the gift was big."),
    ('وحط راسه بتم الذيب.', "And he put his head in the wolf's mouth."),
    ('راسه كله.', "His whole head."),
    ('ومسك العظمة بمنقاره.', "And gripped the bone in his beak."),
    ('وسحبها.', "And pulled it out."),
    ('والذيب تنفس.', "And the wolf breathed.")),
  P(('قال الكركي: خلص.', "The crane said: done."),
    ('وهلق الهدية.', "And now the gift."),
    ('الذيب ضحك.', "The wolf laughed."),
    ('قال: هدية؟', "He said: gift?"),
    ('راسك كان بتمي.', "Your head was in my mouth."),
    ('وطلع سليم.', "And it came out whole."),
    ('هاي الهدية.', "That is the gift."),
    ('ومشى.', "And walked off."),
    ('اللي بيساعد الشرير، ما بيستنى شكر.', "Whoever helps the wicked should expect no thanks."))]),

 ('The Town Mouse and the Country Mouse', 'فار المدينة وفار الضيعة', [
  P(('فار الضيعة عايش بحقل.', "The country mouse lived in a field."),
    ('بيته زغير، تحت شجرة.', "His house was small, under a tree."),
    ('بياكل قمح، وشعير، وجذور.', "He ate wheat, barley, roots."),
    ('وبيوم، زاره ابن عمه.', "And one day, his cousin visited him."),
    ('فار المدينة.', "The town mouse."),
    ('لابس منيح، وريحته حلوة.', "Well dressed, and smelling sweet."),
    ('وفار الضيعة فرح كتير.', "And the country mouse was very glad.")),
  P(('حط له كل اللي عنده.', "He put out everything he had."),
    ('قمح، وشعير، وجذور، وحبة جوز.', "Wheat, barley, roots, a walnut."),
    ('فار المدينة أكل شوي.', "The town mouse ate a little."),
    ('وقال: هاد أكل؟', "And said: this is food?"),
    ('يا ابن عمي، إنت عايش زي النملة.', "Cousin, you live like an ant."),
    ('تعال معي عالمدينة.', "Come with me to the town."),
    ('وشوف الأكل الحقيقي.', "And see real food.")),
  P(('راحوا سوا عالمدينة.', "They went together to the town."),
    ('بالليل.', "At night."),
    ('ودخلوا بيت كبير.', "And entered a big house."),
    ('وعالطاولة، كل شي.', "And on the table, everything."),
    ('جبنة، وخبز أبيض، وعسل، وفواكه، وكعك.', "Cheese, white bread, honey, fruit, cake."),
    ('فار الضيعة ما صدق عينه.', "The country mouse could not believe his eyes."),
    ('وبلش ياكل.', "And began to eat.")),
  P(('وفجأة، انفتح الباب.', "And suddenly, the door opened."),
    ('ودخل ناس.', "And people came in."),
    ('والفارين ركضوا، وتخبوا بشق.', "And the two mice ran, and hid in a crack."),
    ('والناس راحوا.', "And the people left."),
    ('ورجعوا ياكلوا.', "And they went back to eating."),
    ('وفجأة، قطة.', "And suddenly, a cat."),
    ('قطة كبيرة، وعينها بتلمع.', "A big cat, with shining eyes."),
    ('والفارين ركضوا للشق كمان مرة.', "And the two mice ran to the crack again."),
    ('وقلبهم بيدق.', "Their hearts pounding.")),
  P(('قال فار الضيعة: خلص.', "The country mouse said: enough."),
    ('أنا راجع.', "I am going home."),
    ('قال فار المدينة: ليش؟', "The town mouse said: why?"),
    ('شفت الأكل؟', "Did you see the food?"),
    ('قال فار الضيعة: شفت.', "The country mouse said: I saw."),
    ('وشفت القطة.', "And I saw the cat."),
    ('أكلي قليل، بس بآكله بهدوء.', "My food is little, but I eat it in peace."),
    ('ورجع عالحقل.', "And went back to the field."),
    ('لقمة بأمان، أحسن من عزيمة بخوف.', "A crust in peace is better than a feast in fear."))]),

 ('The Boastful Traveller', 'المسافر المفشخر', [
  P(('رجل رجع من سفر طويل.', "A man came back from a long journey."),
    ('وقعد بالمقهى.', "And sat in the café."),
    ('وصار يحكي.', "And began to talk."),
    ('يحكي عن البلاد اللي شافها.', "To talk of the countries he had seen."),
    ('وعن الأشياء اللي عملها.', "And the things he had done."),
    ('وكل قصة أكبر من اللي قبلها.', "And every story bigger than the one before.")),
  P(('قال: بمصر، سبحت النيل كله.', "He said: in Egypt, I swam the whole Nile."),
    ('وبالهند، صارعت نمر.', "And in India, I wrestled a tiger."),
    ('وبجزيرة رودس، نطيت نطة.', "And on the island of Rhodes, I made a jump."),
    ('أطول نطة بالتاريخ.', "The longest jump in history."),
    ('عشرة أمتار!', "Ten metres!"),
    ('والناس كلها شافتني.', "And everyone saw me."),
    ('وصفقوا.', "And clapped.")),
  P(('الناس بالمقهى سكتوا.', "The people in the café were silent."),
    ('واحد قال: عشرة أمتار؟', "One said: ten metres?"),
    ('قال المسافر: عشرة.', "The traveller said: ten."),
    ('ولو كنتوا برودس، كنتوا شفتوا.', "And had you been in Rhodes, you would have seen."),
    ('في شهود هناك.', "There are witnesses there."),
    ('كتار.', "Many.")),
  P(('وقام رجل عجوز من الزاوية.', "And an old man got up from the corner."),
    ('وقال: ليش رودس؟', "And said: why Rhodes?"),
    ('هون كمان في أرض.', "There is ground here too."),
    ('ورسم خط بعصايته عالأرض.', "And he drew a line on the ground with his stick."),
    ('وقال: هاي رودس.', "And said: this is Rhodes."),
    ('نط.', "Jump."),
    ('والمسافر سكت.', "And the traveller was silent."),
    ('وما نط.', "And did not jump."),
    ('الفعل بيبين، والحكي بيطير.', "Deeds show, and talk flies away."))]),

 ('The Frog and the Ox', 'الضفدع والثور', [
  P(('ضفدع عايش ببركة زغيرة.', "A frog lived in a small pond."),
    ('وكان أكبر ضفدع بالبركة.', "And he was the biggest frog in the pond."),
    ('وكان فخور.', "And he was proud."),
    ('كل يوم بيقول: أنا أكبر واحد.', "Every day he said: I am the biggest."),
    ('والضفادع الزغار بيصدقوا.', "And the little frogs believed him."),
    ('وبيوم، إجا ثور يشرب.', "And one day, an ox came to drink.")),
  P(('الضفادع الزغار شافوا الثور.', "The little frogs saw the ox."),
    ('وركضوا للضفدع الكبير.', "And ran to the big frog."),
    ('قالوا: شفنا حيوان!', "They said: we saw an animal!"),
    ('كبير! أكبر منك بكتير!', "Big! Much bigger than you!"),
    ('الضفدع الكبير زعل.', "The big frog was upset."),
    ('قال: أكبر مني؟', "He said: bigger than me?"),
    ('مستحيل.', "Impossible.")),
  P(('وأخد نفس عميق.', "And he took a deep breath."),
    ('ونفخ حاله.', "And puffed himself up."),
    ('وصار أكبر.', "And became bigger."),
    ('قال: هيك؟', "He said: like this?"),
    ('قالوا: لا. أكبر.', "They said: no. Bigger."),
    ('ونفخ كمان.', "And he puffed more."),
    ('قال: هيك؟', "He said: like this?"),
    ('قالوا: لا. أكبر بكتير.', "They said: no. Much bigger.")),
  P(('ونفخ الضفدع.', "And the frog puffed."),
    ('ونفخ.', "And puffed."),
    ('ونفخ.', "And puffed."),
    ('وصار زي البالون.', "And became like a balloon."),
    ('وقال: هيـ...', "And said: like th..."),
    ('وانفجر.', "And burst."),
    ('اللي بيقلد الكبير، بيخرب حاله.', "Whoever imitates the great destroys himself."))]),

 ('The Farmer and the Snake', 'الفلاح والحية', [
  P(('كان الشتا قاسي.', "The winter was harsh."),
    ('والتلج بكل مكان.', "And snow everywhere."),
    ('وفلاح ماشي عالطريق.', "And a farmer walking on the road."),
    ('وشاف حية عالأرض.', "And he saw a snake on the ground."),
    ('حية مجمدة من البرد.', "A snake frozen with cold."),
    ('ما بتتحرك.', "Not moving."),
    ('تقريباً ميتة.', "Nearly dead.")),
  P(('الفلاح وقف.', "The farmer stopped."),
    ('وقال: مسكينة.', "And said: poor thing."),
    ('رح تموت من البرد.', "It will die of cold."),
    ('ورفعها.', "And picked it up."),
    ('وحطها جوا قميصه.', "And put it inside his shirt."),
    ('على صدره.', "On his chest."),
    ('عشان تدفى.', "So it would warm up.")),
  P(('ومشى.', "And walked on."),
    ('والحية دفيت.', "And the snake warmed."),
    ('وبلشت تتحرك.', "And began to move."),
    ('وفاقت.', "And woke."),
    ('وشافت إنها على صدر رجل.', "And saw it was on a man's chest."),
    ('وعملت اللي بتعمله الحيات.', "And did what snakes do."),
    ('عضته.', "It bit him.")),
  P(('الفلاح وقع.', "The farmer fell."),
    ('والسم بجسمه.', "The poison in his body."),
    ('وقال، وهو بيموت:', "And said, dying:"),
    ('أنا دفيتك.', "I warmed you."),
    ('وإنتِ عضيتيني.', "And you bit me."),
    ('قالت الحية: أنا حية.', "The snake said: I am a snake."),
    ('وإنت كنت بتعرف.', "And you knew it."),
    ('الشرير ما بيتغير بالمعروف.', "The wicked do not change for kindness."))]),

 ('The Ass and His Masters', 'الحمار وأصحابه', [
  P(('حمار كان بيشتغل عند بستاني.', "A donkey worked for a gardener."),
    ('شغل صعب.', "Hard work."),
    ('يحمل مي، وتراب، وخضار.', "Carrying water, earth, vegetables."),
    ('من الصبح للمسا.', "From morning to evening."),
    ('وأكل قليل.', "And little food."),
    ('والحمار زهق.', "And the donkey grew sick of it."),
    ('وقال: يا رب، أعطيني صاحب تاني.', "And said: Lord, give me another master.")),
  P(('وباعه البستاني لفخاري.', "And the gardener sold him to a potter."),
    ('والفخاري حمله طين.', "And the potter loaded him with clay."),
    ('طين تقيل، ومبلول.', "Heavy, wet clay."),
    ('وجرار كبيرة.', "And big jars."),
    ('أتقل من المي والخضار.', "Heavier than the water and vegetables."),
    ('والحمار قال: هاد أسوأ.', "And the donkey said: this is worse."),
    ('يا رب، أعطيني صاحب تاني.', "Lord, give me another master.")),
  P(('وباعه الفخاري لدباغ.', "And the potter sold him to a tanner."),
    ('الدباغ بيشتغل بالجلود.', "The tanner works with hides."),
    ('جلود الحيوانات الميتة.', "The hides of dead animals."),
    ('والحمار شاف الجلود.', "And the donkey saw the hides."),
    ('وشم الريحة.', "And smelled the smell."),
    ('وفهم.', "And understood.")),
  P(('قال الحمار: يا ويلي.', "The donkey said: woe is me."),
    ('عند البستاني، كنت أشتغل.', "With the gardener, I worked."),
    ('وعند الفخاري، كنت أتعب.', "With the potter, I toiled."),
    ('وهون، لما أموت، بيدبغ جلدي.', "And here, when I die, he tans my hide."),
    ('يا ريتني ضليت عند الأول.', "If only I had stayed with the first."),
    ('اللي بيغير كتير، بيخسر أكتر.', "Whoever changes too often loses the more."))]),

 ('The Goose and the Golden Eggs', 'الوزة وبيض الدهب', [
  P(('فلاح ومرته عندهم وزة.', "A farmer and his wife had a goose."),
    ('وزة عادية، بيضا.', "An ordinary goose, white."),
    ('وبيوم، الوزة باضت.', "And one day, the goose laid an egg."),
    ('والفلاح راح ياخد البيضة.', "And the farmer went to take the egg."),
    ('ووقف.', "And stopped."),
    ('البيضة تقيلة.', "The egg was heavy."),
    ('وصفرا، وبتلمع.', "And yellow, and shining."),
    ('دهب.', "Gold.")),
  P(('الفلاح ركض لمرته.', "The farmer ran to his wife."),
    ('قال: شوفي!', "He said: look!"),
    ('بيضة دهب!', "A golden egg!"),
    ('وباعوها بالسوق.', "And they sold it at the market."),
    ('بمصاري كتير.', "For a lot of money."),
    ('وتاني يوم، بيضة تانية.', "And the next day, another egg."),
    ('دهب.', "Gold."),
    ('وتالت يوم، تالتة.', "And the third day, a third.")),
  P(('كل يوم بيضة.', "Every day an egg."),
    ('وكل يوم مصاري.', "And every day money."),
    ('والفلاح صار غني.', "And the farmer became rich."),
    ('بيت جديد، وأرض، وخيل.', "A new house, land, horses."),
    ('بس ما كان مبسوط.', "But he was not content."),
    ('قال: بيضة وحدة كل يوم.', "He said: one egg every day."),
    ('بطيء.', "Slow."),
    ('أكيد جوا الوزة، دهب كتير.', "Surely inside the goose, there is a lot of gold.")),
  P(('قالت مرته: لا.', "His wife said: no."),
    ('خليها.', "Leave her."),
    ('قال الفلاح: بدي الدهب كله.', "The farmer said: I want all the gold."),
    ('هلق.', "Now."),
    ('وأخد سكين.', "And took a knife."),
    ('ودبح الوزة.', "And killed the goose."),
    ('وفتحها.', "And opened her."),
    ('وجواها، ولا شي.', "And inside, nothing."),
    ('وزة عادية.', "An ordinary goose."),
    ('وما عاد في بيض.', "And there were no more eggs."),
    ('الطمع بيخسر كل شي.', "Greed loses everything."))]),

 ('The Dog and His Reflection', 'الكلب وخياله', [
  P(('كلب سرق قطعة لحمة.', "A dog stole a piece of meat."),
    ('من عند اللحام.', "From the butcher's."),
    ('قطعة كبيرة.', "A big piece."),
    ('وركض.', "And ran."),
    ('واللحام ركض وراه.', "And the butcher ran after him."),
    ('بس الكلب أسرع.', "But the dog was faster."),
    ('ووصل للنهر.', "And reached the river.")),
  P(('كان في جسر زغير.', "There was a small bridge."),
    ('والكلب مشى عليه.', "And the dog walked across it."),
    ('واللحمة بتمه.', "The meat in his mouth."),
    ('وتطلع لتحت.', "And he looked down."),
    ('وشاف بالمي كلب.', "And saw in the water a dog."),
    ('وبتم الكلب، لحمة.', "And in the dog's mouth, meat."),
    ('لحمة كبيرة.', "Big meat."),
    ('أكبر من لحمته.', "Bigger than his.")),
  P(('قال الكلب: بدي هاي كمان.', "The dog said: I want that too."),
    ('ونبح.', "And barked."),
    ('عشان يخوف الكلب التاني.', "To frighten the other dog."),
    ('ولما فتح تمه، وقعت اللحمة.', "And when he opened his mouth, the meat fell."),
    ('وقعت بالنهر.', "It fell into the river."),
    ('والنهر أخدها.', "And the river took it.")),
  P(('والكلب تطلع بالمي.', "And the dog looked at the water."),
    ('الكلب التاني راح.', "The other dog was gone."),
    ('واللحمة التانية راحت.', "And the other meat was gone."),
    ('كان هو.', "It had been himself."),
    ('خياله بالمي.', "His reflection in the water."),
    ('ورجع عالبيت جعان.', "And he went home hungry."),
    ('اللي بيطمع بالكل، بيخسر اللي معه.', "Whoever grasps at everything loses what he has."))]),

 ('The Old Man and Death', 'الرجل الكبير والموت', [
  P(('رجل كبير بالعمر كان بيجمع حطب.', "An old man was gathering firewood."),
    ('بالغابة.', "In the forest."),
    ('وجمع حزمة كبيرة.', "And gathered a big bundle."),
    ('وحملها على ظهره.', "And carried it on his back."),
    ('ومشى.', "And walked."),
    ('والطريق طويلة.', "And the road was long."),
    ('والحزمة تقيلة.', "And the bundle was heavy.")),
  P(('وظهره بيوجعه.', "And his back hurt."),
    ('وإجريه بتوجعه.', "And his legs hurt."),
    ('والشمس حامية.', "And the sun was hot."),
    ('ووقف.', "And he stopped."),
    ('ورمى الحزمة عالأرض.', "And threw the bundle on the ground."),
    ('وقعد عليها.', "And sat on it."),
    ('وبكى.', "And wept.")),
  P(('وقال: يا رب.', "And said: Lord."),
    ('شو هالحياة؟', "What is this life?"),
    ('شغل، وتعب، وجوع.', "Work, and toil, and hunger."),
    ('وما حدا بيساعدني.', "And no one helps me."),
    ('يا موت، تعال.', "Death, come."),
    ('خدني.', "Take me."),
    ('خلصني.', "Release me.")),
  P(('والموت إجا.', "And Death came."),
    ('وقف قدامه.', "It stood before him."),
    ('وقال: ناديتني؟', "And said: you called me?"),
    ('أنا هون.', "I am here."),
    ('شو بدك؟', "What do you want?"),
    ('والرجل خاف.', "And the man was afraid."),
    ('وقام بسرعة.', "And got up quickly."),
    ('وقال: بدك... بدك تساعدني.', "And said: I want... I want you to help me."),
    ('ارفع لي الحزمة على ظهري.', "Lift the bundle onto my back for me."),
    ('الكل بيطلب الموت، وما حدا بده ياه.', "Everyone calls for death, and no one wants it."))]),

 ('The Two Travellers and the Bear', 'المسافرين والدب', [
  P(('صاحبين كانوا مسافرين.', "Two friends were travelling."),
    ('بالغابة.', "Through the forest."),
    ('وقالوا: إحنا أصحاب.', "And they said: we are friends."),
    ('إذا صار شي، بنساعد بعض.', "If anything happens, we help each other."),
    ('وحلفوا.', "And they swore it."),
    ('ومشوا.', "And walked on.")),
  P(('وفجأة، من بين الشجر، دب.', "And suddenly, from among the trees, a bear."),
    ('دب كبير.', "A big bear."),
    ('الصاحب الأول ركض.', "The first friend ran."),
    ('وتسلق شجرة.', "And climbed a tree."),
    ('بسرعة.', "Fast."),
    ('وما تطلع لورا.', "And did not look back."),
    ('والصاحب التاني ما لحق.', "And the second friend did not make it.")),
  P(('التاني وقع عالأرض.', "The second fell to the ground."),
    ('وعمل حاله ميت.', "And pretended to be dead."),
    ('ما تنفس.', "He did not breathe."),
    ('ما تحرك.', "He did not move."),
    ('والدب إجا.', "And the bear came."),
    ('وشمه.', "And sniffed him."),
    ('شم وجهه، وأذنه.', "Sniffed his face, and his ear."),
    ('والدببة ما بتاكل الميت.', "And bears do not eat the dead."),
    ('والدب راح.', "And the bear left.")),
  P(('نزل الأول من الشجرة.', "The first came down from the tree."),
    ('وضحك.', "And laughed."),
    ('قال: شفتك مع الدب.', "He said: I saw you with the bear."),
    ('حط تمه على أذنك.', "He put his mouth to your ear."),
    ('شو قال لك؟', "What did he tell you?"),
    ('قال التاني: قال لي نصيحة.', "The second said: he gave me advice."),
    ('قال: لا تسافر مع صاحب بيتركك بالخطر.', "He said: do not travel with a friend who leaves you in danger."),
    ('الصاحب بيبين بالضيق.', "A friend shows in hard times."))]),

 ('The Crow and the Pitcher', 'الغراب والجرة', [
  P(('كان الصيف حار.', "The summer was hot."),
    ('وما في مطر من شهور.', "And no rain for months."),
    ('والنهر نشف.', "And the river had dried."),
    ('وغراب كان عطشان.', "And a crow was thirsty."),
    ('عطشان كتير.', "Very thirsty."),
    ('وطار، ودور.', "And he flew, and searched."),
    ('وما لقى مي.', "And found no water.")),
  P(('وبعدين شاف جرة.', "And then he saw a pitcher."),
    ('جرة قدام بيت.', "A pitcher in front of a house."),
    ('ونزل عليها.', "And landed on it."),
    ('وتطلع جواها.', "And looked inside."),
    ('في مي!', "There was water!"),
    ('بس شوي.', "But only a little."),
    ('بقاع الجرة.', "At the bottom of the pitcher.")),
  P(('الغراب حط منقاره.', "The crow put in his beak."),
    ('ما وصل.', "It did not reach."),
    ('والجرة ضيقة.', "And the pitcher was narrow."),
    ('ما بيقدر يدخل راسه.', "He could not get his head in."),
    ('حاول يقلبها.', "He tried to tip it over."),
    ('تقيلة.', "Too heavy."),
    ('وقعد الغراب، وفكر.', "And the crow sat, and thought.")),
  P(('وشاف حجار زغار عالأرض.', "And he saw little stones on the ground."),
    ('وأخد حجر بمنقاره.', "And took a stone in his beak."),
    ('ورماه بالجرة.', "And dropped it in the pitcher."),
    ('والمي طلعت شوي.', "And the water rose a little."),
    ('وأخد حجر تاني.', "And took another stone."),
    ('ورماه.', "And dropped it."),
    ('والمي طلعت شوي.', "And the water rose a little."),
    ('حجر، وحجر، وحجر.', "Stone, and stone, and stone."),
    ('والمي وصلت لفوق.', "And the water reached the top."),
    ('وشرب الغراب.', "And the crow drank."),
    ('العقل بيوصل وين القوة ما بتوصل.', "Wit reaches where strength cannot."))]),

 ('The Bundle of Sticks', 'حزمة العصي', [
  P(('رجل عجوز عنده أربع أولاد.', "An old man had four sons."),
    ('والأولاد دايماً بيتخانقوا.', "And the sons were always quarrelling."),
    ('على الأرض، وعالمصاري، وعلى كل شي.', "Over the land, over money, over everything."),
    ('والأب زعلان.', "And the father was sad."),
    ('قال: لما أموت، بيتفرقوا.', "He said: when I die, they will scatter."),
    ('وبيضيعوا.', "And be lost.")),
  P(('وبيوم، ناداهم.', "And one day, he called them."),
    ('وجاب حزمة عصي.', "And brought a bundle of sticks."),
    ('حزمة مربوطة بحبل.', "A bundle tied with a rope."),
    ('وقال للأول: اكسرها.', "And said to the first: break it."),
    ('الأول حاول.', "The first tried."),
    ('بكل قوته.', "With all his strength."),
    ('ما انكسرت.', "It did not break.")),
  P(('وأعطاها للتاني.', "And gave it to the second."),
    ('ما انكسرت.', "It did not break."),
    ('وللتالت، وللرابع.', "And to the third, and the fourth."),
    ('ما انكسرت.', "It did not break."),
    ('قالوا: مستحيل.', "They said: impossible."),
    ('الحزمة قوية كتير.', "The bundle is too strong.")),
  P(('الأب فك الحبل.', "The father untied the rope."),
    ('وأعطى كل واحد عصا.', "And gave each one a stick."),
    ('وقال: اكسروها.', "And said: break them."),
    ('وكل واحد كسر عصاه.', "And each one broke his stick."),
    ('بسهولة.', "Easily."),
    ('قال الأب: شفتوا؟', "The father said: you see?"),
    ('مع بعض، ما حدا بيكسركم.', "Together, no one breaks you."),
    ('لحالكم، بتنكسروا وحدة وحدة.', "Alone, you break one by one."),
    ('بالاتحاد قوة.', "In unity there is strength."))]),

 ('Belling the Cat', 'جرس القطة', [
  P(('الفيران ببيت كبير كانوا خايفين.', "The mice in a big house were afraid."),
    ('من القطة.', "Of the cat."),
    ('القطة بتيجي بلا صوت.', "The cat comes without a sound."),
    ('وبتمسك واحد.', "And catches one."),
    ('كل يوم.', "Every day."),
    ('والفيران ما بيعرفوا إيمتى.', "And the mice never know when."),
    ('فعملوا اجتماع.', "So they held a meeting.")),
  P(('قال فار: لازم نعمل شي.', "One mouse said: we must do something."),
    ('قال تاني: نهرب من البيت.', "Another said: we leave the house."),
    ('قالوا: لا. البيت فيه أكل.', "They said: no. The house has food."),
    ('قال تالت: نحارب القطة.', "A third said: we fight the cat."),
    ('قالوا: لا. القطة أقوى.', "They said: no. The cat is stronger."),
    ('وسكتوا.', "And fell silent.")),
  P(('وقام فار زغير.', "And a young mouse got up."),
    ('وقال: عندي فكرة.', "And said: I have an idea."),
    ('المشكلة إنها بتيجي بلا صوت.', "The problem is that she comes without a sound."),
    ('فبنحط على رقبتها جرس.', "So we put a bell on her neck."),
    ('ولما تتحرك، الجرس بيرن.', "And when she moves, the bell rings."),
    ('وبنسمعها، وبنهرب.', "And we hear her, and run."),
    ('والفيران صفقوا.', "And the mice clapped."),
    ('قالوا: فكرة عظيمة!', "They said: a great idea!")),
  P(('وقام فار كبير بالعمر.', "And an old mouse got up."),
    ('وقال: فكرة عظيمة.', "And said: a great idea."),
    ('بس عندي سؤال.', "But I have a question."),
    ('مين بده يحط الجرس؟', "Who is going to put on the bell?"),
    ('وصار صمت.', "And there was silence."),
    ('وتطلع كل فار بالتاني.', "And every mouse looked at the next."),
    ('وما حدا رد.', "And no one answered."),
    ('الحكي سهل، والعمل صعب.', "Talking is easy, and doing is hard."))]),

 ('The Fox and the Crow', 'الثعلب والغراب', [
  P(('غراب لقى قطعة جبنة.', "A crow found a piece of cheese."),
    ('جبنة كبيرة، وطيبة.', "A big, good piece of cheese."),
    ('أخدها بمنقاره.', "He took it in his beak."),
    ('وطار على شجرة.', "And flew up into a tree."),
    ('ووقف على غصن عالي.', "And sat on a high branch."),
    ('عشان ياكلها بهدوء.', "To eat it in peace."),
    ('وتحت الشجرة، مر ثعلب.', "And beneath the tree, a fox passed.")),
  P(('الثعلب شم الجبنة.', "The fox smelled the cheese."),
    ('وتطلع لفوق.', "And looked up."),
    ('وشاف الغراب.', "And saw the crow."),
    ('وفكر.', "And thought."),
    ('وقال بصوت حلو: يا غراب!', "And said in a sweet voice: crow!"),
    ('شو أحلى ريشك!', "How beautiful your feathers are!"),
    ('أسود، وبيلمع.', "Black, and shining."),
    ('إنت أحلى طير بالغابة.', "You are the loveliest bird in the forest.")),
  P(('الغراب سمع.', "The crow listened."),
    ('وفرح.', "And was pleased."),
    ('وقال الثعلب: بس في شي واحد.', "And the fox said: but there is one thing."),
    ('بيقولوا إنه صوتك مش حلو.', "They say your voice is not beautiful."),
    ('أنا ما بصدق.', "I do not believe it."),
    ('غني لي شوي.', "Sing for me a little."),
    ('وبعرف إذا صحيح.', "And I will know if it is true.")),
  P(('الغراب فتح منقاره.', "The crow opened his beak."),
    ('وقال: كااااع!', "And said: caaaw!"),
    ('والجبنة وقعت.', "And the cheese fell."),
    ('والثعلب مسكها.', "And the fox caught it."),
    ('وقال: صوتك حلو.', "And said: your voice is lovely."),
    ('بس عقلك زغير.', "But your brain is small."),
    ('ومشى بالجبنة.', "And walked off with the cheese."),
    ('اللي بيمدحك كتير، بده شي.', "Whoever praises you too much wants something."))]),

 ("The Donkey in the Lion's Skin", 'الحمار بجلد الأسد', [
  P(('حمار لقى جلد أسد.', "A donkey found a lion's skin."),
    ('جلد كامل، بالراس والديل.', "A whole skin, with the head and the tail."),
    ('تركه صياد بالغابة.', "A hunter had left it in the forest."),
    ('والحمار لبسه.', "And the donkey put it on."),
    ('وتطلع بالمي.', "And looked in the water."),
    ('وشاف أسد.', "And saw a lion."),
    ('وفرح كتير.', "And was very pleased.")),
  P(('ومشى بالغابة.', "And walked through the forest."),
    ('والحيوانات شافوه.', "And the animals saw him."),
    ('وهربوا.', "And fled."),
    ('الغزلان هربت.', "The deer fled."),
    ('والأرانب هربت.', "And the rabbits fled."),
    ('وحتى الذيب هرب.', "And even the wolf fled."),
    ('والحمار قال: أنا ملك!', "And the donkey said: I am king!")),
  P(('ومر الثعلب.', "And the fox passed."),
    ('وشاف الأسد.', "And saw the lion."),
    ('وخاف.', "And was afraid."),
    ('ووقف.', "And stopped."),
    ('والحمار فرح أكتر.', "And the donkey was even more pleased."),
    ('وقال: بخوفه!', "And said: I will frighten him!"),
    ('وفتح تمه.', "And opened his mouth.")),
  P(('وقال: هيــهاااو!', "And said: hee-haaw!"),
    ('والثعلب ضحك.', "And the fox laughed."),
    ('قال: أسد؟', "He said: a lion?"),
    ('الأسد بيزعق.', "A lion roars."),
    ('وإنت بتنهق.', "And you bray."),
    ('إنت حمار.', "You are a donkey."),
    ('بجلد أسد.', "In a lion's skin."),
    ('والحيوانات رجعت، وضحكت عليه.', "And the animals came back, and laughed at him."),
    ('الجلد بيخبي، والصوت بيفضح.', "The skin hides, and the voice betrays."))]),

 ("The Wolf in Sheep's Clothing", 'الذيب بجلد الخروف', [
  P(('ذيب كان جعان.', "A wolf was hungry."),
    ('وقريب منه قطيع غنم.', "And near him a flock of sheep."),
    ('بس الراعي دايماً موجود.', "But the shepherd was always there."),
    ('ومعه كلاب.', "And with him dogs."),
    ('والذيب ما بيقدر يقرب.', "And the wolf could not come near."),
    ('وقعد يفكر.', "And he sat thinking."),
    ('ولقى جلد خروف عالأرض.', "And found a sheepskin on the ground.")),
  P(('لبس الذيب الجلد.', "The wolf put on the skin."),
    ('وصار شكله خروف.', "And looked like a sheep."),
    ('ومشى على مهل.', "And walked slowly."),
    ('ودخل بين الغنم.', "And went in among the sheep."),
    ('والراعي ما انتبه.', "And the shepherd did not notice."),
    ('والكلاب ما انتبهت.', "And the dogs did not notice."),
    ('والذيب قال: الليلة بآكل.', "And the wolf said: tonight I eat.")),
  P(('وإجا المسا.', "And evening came."),
    ('والراعي دخل الغنم للحظيرة.', "And the shepherd put the sheep in the fold."),
    ('والذيب معهم.', "And the wolf with them."),
    ('وسكر الباب.', "And shut the gate."),
    ('والذيب قال: هلق.', "And the wolf said: now."),
    ('واستنى العتمة.', "And waited for the dark.")),
  P(('بس الراعي رجع.', "But the shepherd came back."),
    ('كان بده لحمة للعشا.', "He wanted meat for supper."),
    ('ودخل الحظيرة بالعتمة.', "And went into the fold in the dark."),
    ('ومد إيده.', "And reached out his hand."),
    ('وأخد أول خروف لقاه.', "And took the first sheep he found."),
    ('كان الذيب.', "It was the wolf."),
    ('ودبحه.', "And killed him."),
    ('اللي بيتنكر، بيوقع بتنكره.', "Whoever disguises himself falls by his disguise."))]),

 ('The Boy Who Cried Wolf', 'الولد والذيب', [
  P(('ولد كان راعي.', "A boy was a shepherd."),
    ('كل يوم بياخد الغنم عالجبل.', "Every day he took the sheep up the hill."),
    ('وبيقعد لحاله.', "And sat alone."),
    ('من الصبح للمسا.', "From morning to evening."),
    ('وكان زهقان.', "And he was bored."),
    ('كتير.', "Very."),
    ('وبيوم، إجت له فكرة.', "And one day, an idea came to him.")),
  P(('صرخ: ذيب! ذيب!', "He shouted: wolf! Wolf!"),
    ('الناس بالقرية سمعوا.', "The people in the village heard."),
    ('وركضوا عالجبل.', "And ran up the hill."),
    ('بالعصي والفؤوس.', "With sticks and axes."),
    ('ووصلوا.', "And arrived."),
    ('وما في ذيب.', "And there was no wolf."),
    ('والولد بيضحك.', "And the boy was laughing."),
    ('والناس زعلوا، ورجعوا.', "And the people were angry, and went back.")),
  P(('بعد أسبوع، زهق كمان.', "A week later, he was bored again."),
    ('وصرخ: ذيب! ذيب!', "And shouted: wolf! Wolf!"),
    ('والناس ركضوا.', "And the people ran."),
    ('وما في ذيب.', "And there was no wolf."),
    ('والولد بيضحك.', "And the boy was laughing."),
    ('وقالوا: هالولد كذاب.', "And they said: this boy is a liar."),
    ('ما منسمع له بعد اليوم.', "We will not listen to him again.")),
  P(('وبعد أسبوع، إجا ذيب.', "And a week later, a wolf came."),
    ('ذيب حقيقي.', "A real wolf."),
    ('ودخل بين الغنم.', "And went in among the sheep."),
    ('والولد صرخ: ذيب! ذيب!', "And the boy shouted: wolf! Wolf!"),
    ('صرخ بكل صوته.', "He shouted with all his voice."),
    ('والناس سمعوا.', "And the people heard."),
    ('وقالوا: بيكذب كمان.', "And said: he is lying again."),
    ('وما حدا طلع.', "And no one went up."),
    ('والذيب أكل الغنم.', "And the wolf ate the sheep."),
    ('الكذاب ما حدا بيصدقه، حتى لما يصدق.', "No one believes a liar, even when he tells the truth."))]),

 ('The Milkmaid and Her Pail', 'البنت وسطل الحليب', [
  P(('بنت فلاحة حلبت البقرة.', "A farmer's daughter milked the cow."),
    ('وعبت سطل حليب.', "And filled a pail with milk."),
    ('سطل كبير.', "A big pail."),
    ('وحطته على راسها.', "And put it on her head."),
    ('ومشيت عالسوق.', "And walked to the market."),
    ('عشان تبيعه.', "To sell it."),
    ('وبالطريق، صارت تفكر.', "And on the way, she began to think.")),
  P(('قالت: ببيع الحليب.', "She said: I sell the milk."),
    ('وبالمصاري، بشتري بيض.', "And with the money, I buy eggs."),
    ('ومن البيض، بيطلع صيصان.', "And from the eggs, chicks hatch."),
    ('والصيصان بتكبر.', "And the chicks grow."),
    ('وبتصير دجاج.', "And become hens."),
    ('وببيع الدجاج.', "And I sell the hens."),
    ('وبشتري فستان.', "And buy a dress.")),
  P(('فستان أحمر.', "A red dress."),
    ('وبلبسه للعرس.', "And wear it to the wedding."),
    ('وكل الشباب بيتطلعوا فيّ.', "And all the young men look at me."),
    ('وواحد بيجي يحكي معي.', "And one comes to talk to me."),
    ('وأنا ما برد عليه.', "And I do not answer him."),
    ('بهز راسي هيك.', "I toss my head like this."),
    ('وهزت راسها.', "And she tossed her head.")),
  P(('والسطل وقع.', "And the pail fell."),
    ('والحليب انكب عالأرض.', "And the milk spilled on the ground."),
    ('كله.', "All of it."),
    ('والبنت وقفت.', "And the girl stood."),
    ('وتطلعت بالحليب.', "And looked at the milk."),
    ('ولا بيض، ولا دجاج.', "No eggs, no hens."),
    ('ولا فستان، ولا عرس.', "No dress, no wedding."),
    ('ما تعد الصيصان قبل ما تفقس.', "Do not count the chicks before they hatch."))]),

 ('The Ant and the Grasshopper', 'النملة والصرصور', [
  P(('بالصيف، النملة كانت تشتغل.', "In summer, the ant was working."),
    ('كل يوم.', "Every day."),
    ('تحمل حبة قمح.', "Carrying a grain of wheat."),
    ('وتحطها ببيتها.', "And putting it in her house."),
    ('وترجع تجيب وحدة تانية.', "And going back for another."),
    ('من الصبح للمسا.', "From morning to evening."),
    ('والشمس حامية.', "And the sun hot.")),
  P(('والصرصور كان يغني.', "And the grasshopper was singing."),
    ('على ورقة، بالظل.', "On a leaf, in the shade."),
    ('وشاف النملة.', "And he saw the ant."),
    ('وقال: يا نملة!', "And said: ant!"),
    ('ليش بتشتغلي؟', "Why are you working?"),
    ('الصيف حلو.', "Summer is lovely."),
    ('تعالي غني معي.', "Come and sing with me.")),
  P(('قالت النملة: الشتا جاي.', "The ant said: winter is coming."),
    ('وبالشتا، ما في أكل.', "And in winter, there is no food."),
    ('أنا بجمع للشتا.', "I am gathering for winter."),
    ('قال الصرصور: الشتا بعيد.', "The grasshopper said: winter is far off."),
    ('وضحك.', "And laughed."),
    ('وغنى.', "And sang."),
    ('وكمل الصيف كله يغني.', "And spent the whole summer singing.")),
  P(('وإجا الشتا.', "And winter came."),
    ('والتلج غطى الأرض.', "And snow covered the ground."),
    ('وما في ورق، ولا حب.', "And no leaves, no grain."),
    ('والصرصور جعان.', "And the grasshopper was hungry."),
    ('وبردان.', "And cold."),
    ('وراح لبيت النملة.', "And went to the ant's house."),
    ('ودق الباب.', "And knocked."),
    ('وقال: أعطيني أكل.', "And said: give me food."),
    ('قالت النملة: بالصيف، شو كنت تعمل؟', "The ant said: in summer, what were you doing?"),
    ('قال: كنت أغني.', "He said: I was singing."),
    ('قالت: طيب. هلق ارقص.', "She said: fine. Now dance."),
    ('اللي بيشتغل بالصيف، بياكل بالشتا.', "Whoever works in summer eats in winter."))]),

 ('The Wind and the Sun', 'الريح والشمس', [
  P(('الريح والشمس تخانقوا.', "The wind and the sun quarrelled."),
    ('قالت الريح: أنا أقوى.', "The wind said: I am stronger."),
    ('قالت الشمس: لا، أنا أقوى.', "The sun said: no, I am stronger."),
    ('وتحتهم، عالطريق، رجل ماشي.', "And below them, on the road, a man walking."),
    ('لابس معطف.', "Wearing a coat."),
    ('قالت الشمس: خلينا نجرب.', "The sun said: let us try."),
    ('اللي بيشلح المعطف عن الرجل، هو الأقوى.', "Whoever gets the coat off the man is the stronger.")),
  P(('قالت الريح: سهلة.', "The wind said: easy."),
    ('ونفخت.', "And blew."),
    ('نفخت بقوة.', "Blew hard."),
    ('والرجل مسك معطفه.', "And the man held his coat."),
    ('ونفخت أقوى.', "And blew harder."),
    ('والرجل زرر معطفه.', "And the man buttoned his coat."),
    ('ونفخت بكل قوتها.', "And blew with all her strength."),
    ('والرجل لف المعطف حوله.', "And the man wrapped the coat around him."),
    ('ومسكه بإيديه الاتنين.', "And held it with both hands.")),
  P(('الريح تعبت.', "The wind grew tired."),
    ('وقالت: دورك.', "And said: your turn."),
    ('والشمس طلعت من ورا الغيم.', "And the sun came out from behind the clouds."),
    ('ودفت.', "And warmed."),
    ('شوي شوي.', "Little by little."),
    ('والرجل فك الأزرار.', "And the man undid the buttons.")),
  P(('والشمس دفت أكتر.', "And the sun warmed more."),
    ('والرجل عرق.', "And the man sweated."),
    ('ومسح جبينه.', "And wiped his brow."),
    ('وشلح المعطف.', "And took off the coat."),
    ('وحطه على كتفه.', "And put it over his shoulder."),
    ('وكمل طريقه.', "And went on his way."),
    ('وقالت الشمس: شفتي؟', "And the sun said: you see?"),
    ('اللطف بيعمل أكتر من القوة.', "Gentleness does more than force."))]),

 ('The Miser and His Gold', 'البخيل ودهبه', [
  P(('كان في رجل بخيل.', "There was a miser."),
    ('عنده دهب كتير.', "He had a lot of gold."),
    ('بس ما بيصرف قرش.', "But he never spent a penny."),
    ('بياكل خبز ومي.', "He ate bread and water."),
    ('ولابس تياب قديمة.', "And wore old clothes."),
    ('والدهب مخبى.', "And the gold was hidden."),
    ('بحفرة، تحت شجرة، بالحديقة.', "In a hole, under a tree, in the garden.")),
  P(('كل ليلة، بيطلع.', "Every night, he went out."),
    ('وبيحفر.', "And dug."),
    ('وبيطلع الدهب.', "And took out the gold."),
    ('وبيعده.', "And counted it."),
    ('وبيتطلع فيه.', "And looked at it."),
    ('وبيرجعه للحفرة.', "And put it back in the hole."),
    ('وبينام مبسوط.', "And slept content.")),
  P(('وبيوم، شافه حرامي.', "And one day, a thief saw him."),
    ('شافه بيحفر بالليل.', "Saw him digging at night."),
    ('واستنى لحد ما نام.', "And waited until he slept."),
    ('وحفر.', "And dug."),
    ('وأخد الدهب كله.', "And took all the gold."),
    ('وراح.', "And left.")),
  P(('تاني ليلة، البخيل طلع.', "The next night, the miser went out."),
    ('وحفر.', "And dug."),
    ('والحفرة فاضية.', "And the hole was empty."),
    ('وصرخ.', "And he screamed."),
    ('وبكى.', "And wept."),
    ('وإجا جاره.', "And his neighbour came."),
    ('وقال: شو صار؟', "And said: what happened?"),
    ('قال البخيل: دهبي! سرقوه!', "The miser said: my gold! Stolen!"),
    ('قال الجار: وكنت بتصرف منه؟', "The neighbour said: and were you spending it?"),
    ('قال البخيل: لا. أبداً.', "The miser said: no. Never."),
    ('قال الجار: طيب.', "The neighbour said: fine."),
    ('حط حجر بالحفرة.', "Put a stone in the hole."),
    ('وتطلع فيه كل ليلة.', "And look at it every night."),
    ('نفس الشي.', "The same thing."),
    ('الدهب اللي ما بتستعمله، زي الحجر.', "Gold you do not use is like a stone."))]),
]

if __name__ == '__main__':
    emit_book(BOOK_ID, BOOK_TITLE, 'beginner', CHAPTERS, unit='Fable', unit_ar='خرافة', shelf=2,
              meta={'work': "Aesop's Fables", 'author': 'Aesop (traditional)',
                    'year': 'c. 600 BCE', 'status': 'public domain — ancient, anonymous'})
