#!/usr/bin/env python3
"""السندباد البحري — the seven voyages, retold in spoken Palestinian, graded to intermediate.

Sindbad belongs to the ألف ليلة وليلة tradition: medieval, anonymous, public domain by age. These
are retellings from the traditional plots, not a translation of Burton, Lane or any other edition.

WHY THIS BOOK, HERE. It is structurally the same thing that works about Around the World in 80
Days — a journey, one self-contained episode per chapter, a reason to open the next one — except
it is Arab heritage rather than Victorian Europe, and a Palestinian reader meets it as something
already half known.

LEVEL. The existing intermediate book runs 49.5 characters a sentence against a 32.5 baseline for
the intermediate short stories, so the middle of the shelf currently has no gentle way in. This
one is deliberately written near the baseline: past-tense narrative with real connectors
(لما، بعد ما، لأنه، بس، وقتها) and relative clauses with اللي, but one clause at a time.

Every voyage runs four chapters — out, the trouble, the escape, the return — so a reader can stop
after any of them and has finished something.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_sindbad.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, emit_book

BOOK_ID = 'sindbad'
BOOK_TITLE = {'en': "Sindbad's Seven Voyages", 'ar': 'رحلات السندباد السبع'}

# (english title, arabic title, [paragraph, ...])
#
# SECOND EDITION (2026-09-03). The first edition was seven sentences a chapter. Same twenty-eight
# chapters, four to a voyage, now told at length in Sindbad's own voice to the porter, with the
# frame — the porter at the gate, the gold at the end of each evening — kept in view.
CHAPTERS = [
 # ---------------- Voyage One ----------------
 ('The Porter and the Sailor', 'الحمّال والبحري', [
  P(('ببغداد، أيام الخليفة هارون الرشيد، كان في حمّال فقير.', "In Baghdad, in the days of the Caliph Harun al-Rashid, there was a poor porter."),
    ('اسمه السندباد.', "His name was Sindbad."),
    ('كان يحمل أغراض الناس على راسه من الصبح للمسا.', "He carried people's goods on his head from morning to evening."),
    ('وبيوم حر كتير، كان شايل حمل تقيل، وتعب.', "And on a very hot day, he was carrying a heavy load, and grew tired."),
    ('وقف قدام بيت كبير، فيه باب واسع وحديقة.', "He stopped in front of a big house, with a wide door and a garden."),
    ('ومن جوا، سمع موسيقى، وضحك، وريحة أكل طيب.', "And from inside, he heard music, and laughter, and the smell of good food.")),
  P(('قعد على مصطبة قدام الباب، وحط الحمل جنبه.', "He sat on a bench in front of the door, and put the load beside him."),
    ('وقال بصوت عالي، لحاله:', "And he said out loud, to himself:"),
    ('يا رب، شو الفرق بيني وبين صاحب هالبيت؟', "Lord, what is the difference between me and the owner of this house?"),
    ('هو بيقعد بالظل وبياكل، وأنا بحمل بالشمس وبجوع.', "He sits in the shade and eats, and I carry in the sun and go hungry."),
    ('إحنا الاتنين بني آدم، فليش هو فوق وأنا تحت؟', "We are both human beings, so why is he above and I below?"),
    ('وما كان يعرف إن صاحب البيت واقف عالشباك، وسامعه.', "And he did not know that the owner of the house was standing at the window, hearing him.")),
  P(('بعد شوي، طلع خادم وقال له: سيدي بده يشوفك.', "A little later, a servant came out and said to him: my master wants to see you."),
    ('خاف الحمّال، وقال: أنا ما قلت إشي غلط.', "The porter was afraid, and said: I said nothing wrong."),
    ('قال الخادم: تعال، ما حدا رح يأذيك.', "The servant said: come, no one will harm you."),
    ('ودخل الحمّال على قاعة كبيرة.', "And the porter went into a big hall."),
    ('فيها ناس قاعدين، وأكل، وفواكه، ومغنيين.', "In it people seated, food, fruit, and singers."),
    ('وبالصدر، قاعد رجل كبير بالعمر، وجهه هادي، ولحيته بيضا.', "And at the head sat an old man, with a calm face and a white beard.")),
  P(('قال الرجل: اسمك شو؟', "The man said: what is your name?"),
    ('قال: السندباد الحمّال.', "He said: Sindbad the porter."),
    ('ضحك الرجل، وقال: وأنا اسمي السندباد كمان. السندباد البحري.', "The man laughed, and said: and my name is Sindbad too. Sindbad the sailor."),
    ('وسمعت اللي قلته عالباب.', "And I heard what you said at the door."),
    ('وإنت معك حق تسأل. بس أنا ما جبت هالمصاري بالسهل.', "And you are right to ask. But I did not get this money easily."),
    ('كل درهم عندي، دفعت ثمنه خوف وجوع وموت.', "Every dirham I have, I paid for with fear and hunger and death."),
    ('اقعد، وكول معنا، وأنا بحكي لك عن سبع رحلات.', "Sit, eat with us, and I will tell you about seven voyages."),
    ('وكل ليلة، لما أخلص، بعطيك مية دينار.', "And every night, when I finish, I give you a hundred dinars."),
    ('وقعد الحمّال، وبلش السندباد البحري يحكي.', "And the porter sat, and Sindbad the sailor began to tell."))]),

 ('The First Ship', 'أول سفينة', [
  P(('قال السندباد: أبوي كان تاجر كبير، ومات وأنا شاب.', "Sindbad said: my father was a great merchant, and died when I was young."),
    ('ورثت منه مصاري كتير، وبيت، وأراضي.', "I inherited from him a lot of money, a house, and lands."),
    ('وأنا كنت زغير وغبي، وفكرت إن المصاري ما بتخلص.', "And I was young and foolish, and thought money never runs out."),
    ('صرفت على الأصحاب، وعالأكل، وعالحفلات.', "I spent on friends, on food, on parties."),
    ('وكل يوم كان بيتي مليان ناس، وكل ليلة موسيقى.', "And every day my house was full of people, and every night music.")),
  P(('وبيوم، فقت، وشفت إن الصندوق فاضي.', "And one day, I woke up, and saw that the chest was empty."),
    ('والأصحاب اللي كانوا ياكلوا عندي، ما عادوا يجوا.', "And the friends who used to eat at my house no longer came."),
    ('قعدت لحالي، وتذكرت كلمة كان أبوي يقولها.', "I sat alone, and remembered a word my father used to say."),
    ('كان يقول: القبر أحسن من الفقر، والشغل أحسن من الاتنين.', "He would say: the grave is better than poverty, and work is better than both."),
    ('فقمت، وبعت اللي ضل عندي: الأثاث، والتياب، والبيت.', "So I got up, and sold what I had left: the furniture, the clothes, the house."),
    ('وجمعت تلاتة آلاف درهم.', "And I collected three thousand dirhams.")),
  P(('اشتريت فيها بضاعة: قماش، وعطر، وأشيا خفيفة وغالية.', "With them I bought goods: cloth, perfume, things light and dear."),
    ('ونزلت عالبصرة، وركبت سفينة مع تجار رايحين على الهند.', "And I went down to Basra, and boarded a ship with merchants bound for India."),
    ('كانت أول مرة بشوف البحر.', "It was the first time I saw the sea."),
    ('كبير، وأزرق، وما إله آخر.', "Big, and blue, and without end."),
    ('وقفت عالسطح ساعات، وأنا بتفرج، وقلبي بيدق.', "I stood on deck for hours, watching, my heart beating.")),
  P(('البحر كان هادي بالأول، والريح معنا.', "The sea was calm at first, and the wind was with us."),
    ('كل ما نوصل على جزيرة، ننزل ونبيع ونشتري.', "Every time we reached an island, we went down and sold and bought."),
    ('وكنت أربح بكل جزيرة أكتر من اللي قبلها.', "And on every island I made more than on the one before."),
    ('قلت: هاد الشغل سهل. ليش الناس بيخافوا من البحر؟', "I said: this work is easy. Why are people afraid of the sea?"),
    ('وضحك السندباد الحمّال، وقال: هيك بيفكر كل واحد بالأول.', "And Sindbad the porter laughed, and said: that is what everyone thinks at first."),
    ('قال السندباد البحري: صح. واسمع شو صار.', "Sindbad the sailor said: right. And listen to what happened."))]),

 ('The Island That Moved', 'الجزيرة اللي تحركت', [
  P(('بعد أسابيع، شفنا جزيرة زغيرة، خضرا، بنص البحر.', "After weeks, we saw a small island, green, in the middle of the sea."),
    ('كانت زي حديقة طالعة من المي.', "It was like a garden rising out of the water."),
    ('القبطان رسّى السفينة جنبها، ونزلنا كلنا.', "The captain anchored the ship beside it, and we all went down."),
    ('واحد شعل نار، وواحد بلش يطبخ، وواحد راح يغسل تيابه.', "One lit a fire, one began to cook, and one went to wash his clothes."),
    ('وأنا مشيت عالحافة، أتفرج عالمي.', "And I walked along the edge, looking at the water.")),
  P(('وفجأة، الأرض تحتنا اهتزت.', "And suddenly, the ground beneath us shook."),
    ('صرخ القبطان من السفينة: اطلعوا! اطلعوا بسرعة!', "The captain shouted from the ship: get up! Get up quickly!"),
    ('هاي مش جزيرة! هاي سمكة!', "This is no island! This is a fish!"),
    ('سمكة كبيرة كتير، نامت من مية سنة، ونبت عليها شجر وعشب.', "A fish so big it had slept for a hundred years, and trees and grass had grown on it."),
    ('ولما حسّت بالنار على ظهرها، فاقت.', "And when it felt the fire on its back, it woke."),
    ('وبلشت تغطس.', "And it began to dive.")),
  P(('الناس ركضوا للسفينة، واللي وصل وصل، واللي ما وصل، غرق.', "The people ran for the ship, and those who reached it reached it, and those who did not, drowned."),
    ('وأنا كنت أبعد واحد.', "And I was the farthest away."),
    ('السمكة غطست، والمي غطتني، وصرت أسبح.', "The fish dived, the water covered me, and I began to swim."),
    ('والسفينة، من الخوف، رفعت الشراع ومشيت بلا ما تستنى.', "And the ship, from fear, raised sail and left without waiting."),
    ('شفتها بتبعد، وأنا بصرخ، وما حدا سمعني.', "I saw her growing distant, as I shouted, and no one heard me.")),
  P(('كان في قطعة خشب من السفينة طافية جنبي، فمسكتها.', "There was a piece of wood from the ship floating beside me, so I grabbed it."),
    ('وضليت عليها يوم وليلة، والموج بيرميني.', "And I stayed on it a day and a night, the waves tossing me."),
    ('وفكرت: خلص، هاي آخرتي. بعد أول رحلة.', "And I thought: this is it, this is my end. After the first voyage."),
    ('وبآخر الليل، الموج رماني على شط جزيرة حقيقية.', "And at the end of the night, the waves threw me onto the shore of a real island."),
    ('زحفت عالرمل، ونمت زي الميت.', "I crawled onto the sand, and slept like the dead."),
    ('ولما فقت، إجريّ كانت وارمة، وما بقدر أوقف.', "And when I woke, my legs were swollen, and I could not stand."))]),

 ('The King of the Sea Horses', 'ملك خيل البحر', [
  P(('زحفت على إيديّ لحد ما وصلت على شجر فيه فواكه، وأكلت.', "I crawled on my hands until I reached trees with fruit, and ate."),
    ('وشربت من نبع، ورجعت إلي قوتي بعد أيام.', "And I drank from a spring, and my strength came back after days."),
    ('ومشيت بالجزيرة، لحد ما شفت إشي غريب.', "And I walked the island, until I saw something strange."),
    ('فرس مربوطة عند البحر، حلوة كتير، ولحالها.', "A mare tied by the sea, very beautiful, and alone."),
    ('قربت منها، وسمعت صوت من تحت الأرض.', "I approached her, and heard a voice from under the ground.")),
  P(('طلع رجل من حفرة، وسحبني معه لتحت.', "A man came out of a hole, and pulled me down with him."),
    ('قال: اسكت، ولا تتحرك.', "He said: be silent, and do not move."),
    ('وشفنا من الحفرة: طلع من البحر حصان، ملك خيل البحر.', "And we saw from the hole: a horse came out of the sea, the king of the sea horses."),
    ('وقرب من الفرس، وبعدين رجع للبحر لحاله.', "And he approached the mare, and then went back to the sea alone."),
    ('قال الرجل: هيك بنعمل كل شهر.', "The man said: this is what we do every month."),
    ('بنربط فرس عالشط، وخيل البحر بتيجي.', "We tie a mare on the shore, and the sea horses come."),
    ('والمهر اللي بيولد ما إله مثيل.', "And the foal that is born has no equal."),
    ('إحنا خدام الملك مهراجان، وهاي خيله.', "We are servants of King Mihrjan, and these are his horses.")),
  P(('أخدوني عند الملك، وحكيت له قصتي.', "They took me to the king, and I told him my story."),
    ('كان ملك كريم، وقال: يا سندباد، الله نجاك لسبب.', "He was a generous king, and said: Sindbad, God saved you for a reason."),
    ('وعينني مسؤول عن ميناء مدينته.', "And he appointed me over the harbour of his city."),
    ('صرت أسجل السفن اللي بتيجي وبتروح، وأسأل كل قبطان: من وين؟ ولوين؟', "I began recording the ships that came and went, asking every captain: from where? And to where?"),
    ('وكنت أسأل كل واحد عن بغداد، وما حدا سمع فيها.', "And I asked every one about Baghdad, and no one had heard of it."),
    ('ومرت شهور.', "And months passed.")),
  P(('وبيوم، دخلت الميناء سفينة، وعرفتها.', "And one day, a ship entered the harbour, and I knew her."),
    ('كانت سفينتي، اللي تركتني بالبحر.', "It was my ship, the one that had left me in the sea."),
    ('نزل القبطان، وشافني، وما صدق عينه.', "The captain came down, saw me, and did not believe his eyes."),
    ('قال: السندباد؟ إنت غرقت!', "He said: Sindbad? You drowned!"),
    ('قلت: الله كتب لي عمر جديد.', "I said: God wrote me a new life."),
    ('وكانت بضاعتي لسا بالسفينة، ما حدا لمسها.', "And my goods were still on the ship, no one had touched them."),
    ('بعتها بأحسن سعر، وأعطيت الملك هدية، وودعته.', "I sold them at the best price, gave the king a gift, and bade him farewell."),
    ('ورجعت على بغداد غني، بعد ما كنت ميت.', "And I returned to Baghdad rich, after having been dead."),
    ('وسكت السندباد، وأعطى الحمّال مية دينار، وقال: تعال بكرا.', "And Sindbad fell silent, gave the porter a hundred dinars, and said: come tomorrow."))]),

 # ---------------- Voyage Two ----------------
 ('Bored at Home', 'زهقان بالبيت', [
  P(('تاني يوم، رجع الحمّال، وقعد بنفس المكان.', "The next day, the porter came back, and sat in the same place."),
    ('قال السندباد البحري: عشت ببغداد سنة، مرتاح وغني.', "Sindbad the sailor said: I lived in Baghdad a year, comfortable and rich."),
    ('اشتريت بيت أكبر من الأول، وحديقة، وخدم.', "I bought a house bigger than the first, and a garden, and servants."),
    ('وكل يوم أقعد وآكل وأسمع موسيقى.', "And every day I sat and ate and listened to music."),
    ('وبعد شهور، صرت أحس بإشي غريب.', "And after months, I began to feel something strange.")),
  P(('كنت زهقان.', "I was bored."),
    ('كل يوم زي اللي قبله، وكل أكلة زي اللي قبلها.', "Every day like the one before, every meal like the one before."),
    ('وكنت أحلم بالبحر، وبالجزر، وبالناس اللي شفتهم.', "And I dreamed of the sea, and the islands, and the people I had seen."),
    ('حتى الخوف، كنت أشتاق له.', "Even the fear, I missed it."),
    ('قال الحمّال: بتشتاق للخوف؟ إنت مجنون!', "The porter said: you miss the fear? You are mad!"),
    ('ضحك السندباد وقال: يمكن. بس اللي شاف البحر مرة، البيت بيصير زغير عليه.', "Sindbad laughed and said: perhaps. But whoever has seen the sea once, the house grows small on him.")),
  P(('فاشتريت بضاعة جديدة، ونزلت عالبصرة، وركبت سفينة.', "So I bought new goods, went down to Basra, and boarded a ship."),
    ('وهالمرة كنت أعرف شو بعمل، أو هيك فكرت.', "And this time I knew what I was doing, or so I thought."),
    ('سافرنا من جزيرة لجزيرة، ونبيع ونشتري.', "We sailed from island to island, selling and buying."),
    ('وبيوم، وصلنا على جزيرة حلوة، فيها شجر وعصافير ونبع.', "And one day, we reached a beautiful island, with trees and birds and a spring."),
    ('نزلت لحالي، وقعدت تحت شجرة، وأكلت، ونمت.', "I went down alone, sat under a tree, ate, and slept."),
    ('نمت كتير.', "I slept a long time.")),
  P(('ولما فقت، كانت الشمس واطية، والشط فاضي.', "And when I woke, the sun was low, and the shore was empty."),
    ('ركضت عالشط، وشفت السفينة نقطة بعيدة بالأفق.', "I ran to the shore, and saw the ship a distant dot on the horizon."),
    ('نسيوني.', "They had forgotten me."),
    ('صرخت، ولوحت بتيابي، ولا حدا شافني.', "I shouted, waved my clothes, and no one saw me."),
    ('وقعدت عالرمل، وضربت راسي بإيدي.', "And I sat on the sand, and struck my head with my hands."),
    ('وقلت: مرة نجوت من الغرق، وهلق بموت من الجوع لحالي.', "And I said: once I escaped drowning, and now I die of hunger alone."),
    ('وليش؟ لأني زهقت من بيتي.', "And why? Because I was bored of my house."))]),

 ('The Great White Dome', 'القبة البيضا', [
  P(('تاني يوم، طلعت على أعلى شجرة، وتطلعت حوالي الجزيرة.', "The next day, I climbed the tallest tree, and looked around the island."),
    ('ما في بيوت، ولا دخان، ولا ناس.', "No houses, no smoke, no people."),
    ('بس بعيد، بنص الجزيرة، شفت إشي أبيض وكبير، يلمع بالشمس.', "But far off, in the middle of the island, I saw something white and big, shining in the sun."),
    ('قلت: هاي قبة. يعني في مسجد، يعني في ناس.', "I said: that is a dome. So there is a mosque, so there are people."),
    ('ونزلت ومشيت باتجاهها نص يوم.', "And I came down and walked toward it half a day.")),
  P(('لما وصلت، لفيت حواليها، ودورت على باب.', "When I reached it, I walked around it, looking for a door."),
    ('ما في باب. ولا شباك. ولا حجر.', "No door. No window. No stones."),
    ('كانت ملسا، وبيضا، ودافية.', "It was smooth, and white, and warm."),
    ('لفيت حواليها خمسين خطوة، وما فهمت شو هي.', "I walked fifty paces around it, and did not understand what it was."),
    ('وفجأة، صارت الدنيا عتمة.', "And suddenly, the world went dark."),
    ('تطلعت لفوق، وشفت غيمة كبيرة سودا بتغطي الشمس.', "I looked up, and saw a huge black cloud covering the sun."),
    ('بس الغيمة كانت بتتحرك، وإلها جناحين.', "But the cloud was moving, and it had two wings.")),
  P(('كان طير.', "It was a bird."),
    ('طير أكبر من سفينة، وجناحه يغطي الأرض.', "A bird bigger than a ship, its wing covering the ground."),
    ('وتذكرت قصة سمعتها من البحارة، عن طير اسمه الرخ.', "And I remembered a story I had heard from sailors, about a bird called the Rukh."),
    ('بيصيد فيلة، وبياكلها بالهوا.', "It hunts elephants, and eats them in the air."),
    ('وفهمت: القبة البيضا مش قبة.', "And I understood: the white dome was no dome."),
    ('هاي بيضة الرخ.', "This was the Rukh's egg."),
    ('والرخ نزل عليها، وغطاها بجناحيه، ونام.', "And the Rukh came down on it, covered it with its wings, and slept.")),
  P(('وإجت لي فكرة، من الخوف أو من الجنون، ما بعرف.', "And an idea came to me, from fear or from madness, I do not know."),
    ('فكيت عمامتي، وربطت حالي بإجر الطير.', "I undid my turban, and tied myself to the bird's leg."),
    ('إجره كانت أكبر من جذع شجرة.', "Its leg was bigger than a tree trunk."),
    ('وقلت: بكرا الصبح، لما يطير، بياخدني معه.', "And I said: tomorrow morning, when it flies, it takes me with it."),
    ('لوين؟ ما بعرف. بس أي مكان أحسن من جزيرة فاضية.', "Where to? I do not know. But anywhere is better than an empty island."),
    ('وضليت مربوط طول الليل، وما نمت.', "And I stayed tied all night, and did not sleep."),
    ('ومع أول ضو، الطير فتح جناحيه، وطار.', "And with the first light, the bird opened its wings, and flew."))]),

 ('The Valley of Diamonds', 'وادي الألماس', [
  P(('طار لفوق، لفوق، لحد ما صارت الجزيرة نقطة.', "It flew up, and up, until the island was a dot."),
    ('وأنا معلق بإجره، والريح بتضربني، والغيم حوالي.', "And I hung from its leg, the wind striking me, the clouds around me."),
    ('سكرت عيني، وقلت الشهادة.', "I closed my eyes, and said the prayer of the dying."),
    ('وبعد ساعات، حسيت إنه بينزل.', "And after hours, I felt it descending."),
    ('نزل على أرض صخرية، ووقف.', "It came down on rocky ground, and stood."),
    ('فكيت العمامة بسرعة، وركضت بعيد عنه.', "I untied the turban quickly, and ran far from it."),
    ('وهو ما شافني. مسك بمخالبه حية كبيرة، وطار.', "And it did not see me. It seized a huge snake in its claws, and flew.")),
  P(('وقعدت أتطلع حوالي.', "And I sat looking around me."),
    ('كنت بوادي عميق، وحواليه جبال عالية من كل جهة.', "I was in a deep valley, with high mountains around it on every side."),
    ('ما في طريق يطلع، ولا شجر، ولا مي.', "No path going up, no trees, no water."),
    ('والأرض كلها حجار بتلمع.', "And the ground was all shining stones."),
    ('رفعت واحدة، وشفتها: ألماس.', "I picked one up, and saw it: a diamond."),
    ('الوادي كله ألماس. أكتر من كل خزائن الخلفاء.', "The whole valley was diamonds. More than all the treasuries of the caliphs."),
    ('وقلت: يا ما أغنى إنسان بالدنيا، وأنا رح أموت هون.', "And I said: what a rich man I am, and I am going to die here.")),
  P(('وبعدين شفت شو بيعيش بالوادي.', "And then I saw what lived in the valley."),
    ('حيات. حيات كبيرة، طولها زي النخلة، بتنام بالنهار وبتطلع بالليل.', "Snakes. Huge snakes, long as palm trees, sleeping by day and coming out at night."),
    ('وهاي اللي كان الرخ بيصيدها.', "And these were what the Rukh hunted."),
    ('لما إجا الليل، فتشت على مغارة، ولقيت وحدة زغيرة.', "When night came, I looked for a cave, and found a small one."),
    ('فت فيها، وسكرت بابها بحجر.', "I went in, and blocked its mouth with a stone."),
    ('وطول الليل، سمعت الحيات بتزحف برا، وبتفح.', "And all night, I heard the snakes crawling outside, and hissing."),
    ('وما نمت.', "And I did not sleep.")),
  P(('بالصبح، طلعت، وأنا نص ميت من التعب والخوف.', "In the morning, I came out, half dead from exhaustion and fear."),
    ('ومشيت بالوادي، وفجأة وقع جنبي إشي من فوق.', "And I walked through the valley, and suddenly something fell beside me from above."),
    ('قطعة لحمة. كبيرة، وطازة، ومدبوحة.', "A piece of meat. Big, fresh, and slaughtered."),
    ('تطلعت لفوق، وما شفت حدا. الجبل عالي كتير.', "I looked up, and saw no one. The mountain was very high."),
    ('وبعدين وقعت قطعة تانية، وتالتة.', "And then a second piece fell, and a third."),
    ('وتذكرت قصة تانية من البحارة.', "And I remembered another story from the sailors."),
    ('قصة عن تجار الألماس.', "A story about the diamond merchants."),
    ('وكيف بيطلعوا الألماس من وادي ما حدا بيقدر ينزله.', "And how they get diamonds out of a valley no one can descend into."))]),

 ('The Meat and the Eagles', 'اللحمة والنسور', [
  P(('التجار بيوقفوا فوق الجبل، وبيرموا لحمة عالوادي.', "The merchants stand on top of the mountain, and throw meat into the valley."),
    ('اللحمة بتوقع عالألماس، والألماس بيلزق فيها.', "The meat falls on the diamonds, and the diamonds stick to it."),
    ('وبعدين بتيجي النسور، وبتاخد اللحمة لأعشاشها فوق الجبل.', "And then the eagles come, and carry the meat to their nests on top of the mountain."),
    ('والتجار بيصرخوا ويخوفوا النسور.', "And the merchants shout and scare the eagles away."),
    ('وبياخدوا الألماس من اللحمة.', "And they take the diamonds from the meat."),
    ('هيك بيطلعوا الألماس، وما حدا بينزل عالوادي.', "That is how they get the diamonds out, and no one goes down into the valley."),
    ('لأنه اللي بينزل، ما بيطلع.', "Because whoever goes down does not come up.")),
  P(('قلت: إذا اللحمة بتطلع، أنا بطلع مع اللحمة.', "I said: if the meat goes up, I go up with the meat."),
    ('عبيت جيوبي وحزامي ألماس، أكبر حبات لقيتها.', "I filled my pockets and my belt with diamonds, the biggest I found."),
    ('وربطت حالي بعمامتي تحت أكبر قطعة لحمة.', "And I tied myself with my turban under the biggest piece of meat."),
    ('وتمددت على ظهري، ووجهي لفوق، واستنيت.', "And I lay on my back, face up, and waited."),
    ('والشمس فوقي، والحيات نايمة حوالي.', "The sun above me, and the snakes sleeping around me.")),
  P(('وبعدين سمعت الأجنحة.', "And then I heard the wings."),
    ('نسر كبير نزل، ومسك اللحمة بمخالبه، وطار.', "A big eagle came down, gripped the meat in its claws, and flew."),
    ('وأنا معه، معلق تحت اللحمة زي الميت.', "And I with it, hanging under the meat like a dead man."),
    ('طلع بي فوق الوادي، وفوق الجبل، وحط على عشه.', "It carried me up above the valley, above the mountain, and landed at its nest."),
    ('وبنفس اللحظة، صار صياح وضرب حجار.', "And in that same moment, there was shouting and the throwing of stones."),
    ('التجار.', "The merchants."),
    ('النسر طار خايف، وأنا فكيت حالي ووقفت.', "The eagle flew off in fright, and I untied myself and stood up.")),
  P(('التاجر اللي إجا ياخد اللحمة، شافني، ورجع لورا.', "The merchant who came to take the meat saw me, and stepped back."),
    ('قال: مين إنت؟ بني آدم ولا جني؟', "He said: who are you? A human or a jinn?"),
    ('قلت: بني آدم، وتاجر زيك، وقصتي طويلة.', "I said: a human, and a merchant like you, and my story is long."),
    ('وتطلع عاللحمة، وما لقى فيها ولا حبة ألماس، وحزن.', "And he looked at the meat, and found not one diamond in it, and was sad."),
    ('ففتحت حزامي، وأعطيته حبات أكبر من اللي بيشوفها بسنة.', "So I opened my belt, and gave him stones bigger than he sees in a year."),
    ('وفرح، وأخدني معه، وحكيت للتجار كلهم قصتي.', "And he rejoiced, and took me with him, and I told all the merchants my story."),
    ('وما حدا صدق، لحد ما شافوا الألماس.', "And no one believed, until they saw the diamonds."),
    ('ورجعت على بغداد بمركبهم، غني أكتر من أول مرة.', "And I returned to Baghdad on their ship, richer than the first time."),
    ('وأعطى السندباد الحمّال مية دينار.', "And Sindbad gave the porter a hundred dinars."),
    ('وقال: بكرا، الرحلة التالتة.', "And he said: tomorrow, the third voyage."))]),

 # ---------------- Voyage Three ----------------
 ('The Hairy People', 'الناس الشعرانية', [
  P(('قال الحمّال بتالت يوم: وبعد كل هاد، رجعت عالبحر؟', "The porter said on the third day: and after all that, you went back to sea?"),
    ('قال السندباد: رجعت. لأنه الإنسان بينسى الألم وبيتذكر الفرح.', "Sindbad said: I went back. Because a person forgets the pain and remembers the joy."),
    ('ركبت سفينة كبيرة، مع تجار كتار، وسافرنا شهور.', "I boarded a big ship, with many merchants, and we sailed for months."),
    ('وبيوم، الريح لفت علينا، وجرتنا لجهة ما بدنا ياها.', "And one day, the wind turned on us, and carried us in a direction we did not want."),
    ('والقبطان صار وجهه أصفر، وقال: هاي جزيرة القرود.', "And the captain's face went yellow, and he said: this is the island of the apes."),
    ('اللي بيوصلها، ما بيرجع.', "Whoever reaches it does not return.")),
  P(('ما قدرنا نهرب. السفينة رست، رغماً عنا.', "We could not flee. The ship came to anchor, despite us."),
    ('ومن الشجر، نزلوا علينا.', "And out of the trees, they came down on us."),
    ('ناس زغار، طولهم متر، وكلهم شعر، وعيونهم صفرا.', "Small people, a metre tall, all covered in hair, with yellow eyes."),
    ('مش قرود، ومش بني آدم، ومئات منهم.', "Not apes, and not humans, and hundreds of them."),
    ('طلعوا عالسفينة زي النمل، وما قدرنا نضربهم، لأنهم كتار.', "They climbed onto the ship like ants, and we could not fight them, because there were so many."),
    ('قطعوا حبال المرساة، وسحبوا السفينة عالشط، ورمونا برا.', "They cut the anchor ropes, dragged the ship onto the shore, and threw us off."),
    ('وأخدوا السفينة، وراحوا فيها بالبحر.', "And they took the ship, and went off with her to sea.")),
  P(('وقفنا عالشط، بلا سفينة، وبلا أكل، بجزيرة ما بنعرفها.', "We stood on the shore, without a ship, without food, on an island we did not know."),
    ('مشينا لجوا، ولقينا قصر كبير، بابه مفتوح.', "We walked inland, and found a big palace, its door open."),
    ('فتنا، ولقينا ساحة، وفيها عظام كتيرة، وعظام بني آدم.', "We went in, and found a courtyard, with many bones in it, human bones."),
    ('وحفرة نار كبيرة، وأسياخ حديد طويلة.', "And a big fire pit, and long iron spits."),
    ('قال واحد: خلينا نطلع من هون.', "One said: let us get out of here."),
    ('بس كنا تعبانين، والشمس غابت، ونمنا بالساحة.', "But we were exhausted, the sun had set, and we slept in the courtyard.")),
  P(('وفقنا على صوت.', "And we woke to a sound."),
    ('الأرض بتهتز، وباب القصر بيفتح.', "The ground shaking, and the palace door opening."),
    ('ودخل.', "And it came in."),
    ('طوله زي النخلة، وأسود زي الفحم، وإله عين وحدة بنص جبينه.', "Tall as a palm tree, black as coal, with a single eye in the middle of its forehead."),
    ('وأسنانه زي أسنان الخنزير، وإيديه زي المخالب.', "And its teeth like the teeth of a boar, and its hands like claws."),
    ('وقف بالباب، وتطلع فينا.', "It stood in the doorway, and looked at us."),
    ('وضحك.', "And it laughed."))]),

 ('The Giant', 'العملاق', [
  P(('العملاق قعد عالأرض، ومد إيده، وبلش يلمسنا واحد واحد.', "The giant sat on the ground, reached out its hand, and began feeling us one by one."),
    ('كان يمسك الواحد، ويقلبه، ويعصر ذراعه، ويرميه.', "It would pick one up, turn him over, squeeze his arm, and throw him down."),
    ('وفهمت إنه بيدور على الأسمن.', "And I understood it was looking for the fattest."),
    ('ولما وصل عليّ، عصرني، ولقاني نحيف من الجوع، ورماني.', "And when it came to me, it squeezed me, found me thin from hunger, and threw me down."),
    ('وبالآخر مسك القبطان، وكان سمين.', "And at last it seized the captain, and he was fat."),
    ('ما بدي أحكي لك شو عمل فيه.', "I do not want to tell you what it did to him."),
    ('بس بعد ساعة، العملاق كان شبعان، ونام جنب النار.', "But an hour later, the giant was full, and slept by the fire."),
    ('وشخيره زي الرعد.', "Its snoring like thunder.")),
  P(('كل يوم نفس الإشي.', "Every day the same thing."),
    ('بالصبح بيطلع، وبيسكر الباب علينا.', "In the morning it goes out, and locks the door on us."),
    ('وبالمسا بيرجع، وبياخد واحد.', "And in the evening it comes back, and takes one."),
    ('وصرنا نقعد ونستنى الدور، زي الخراف.', "And we sat waiting our turn, like sheep."),
    ('وبليلة، قلت للباقي: بدنا نموت هون، واحد واحد؟', "And one night, I said to the rest: are we going to die here, one by one?"),
    ('قال واحد: وشو نعمل؟ هو أقوى من كلنا.', "One said: and what can we do? It is stronger than all of us."),
    ('قلت: أقوى، بس بينام. والنايم ما إله قوة.', "I said: stronger, but it sleeps. And a sleeper has no strength.")),
  P(('عملنا خطة.', "We made a plan."),
    ('بالنهار، لما طلع، جمعنا خشب من الساحة.', "By day, when it went out, we gathered wood from the courtyard."),
    ('وعملنا طوف عالشط، وخبيناه.', "And we built a raft on the shore, and hid it."),
    ('وبالليل، لما أكل ونام، أخدنا سيخين من الحديد.', "And at night, when it had eaten and slept, we took two iron spits."),
    ('وحطيناهم بالنار.', "And we put them in the fire."),
    ('لحد ما صاروا حمر.', "Until they were red."),
    ('وحملناهم عشرة، ومشينا على مهل، لحد ما وقفنا فوق وجهه.', "And ten of us carried them, and walked slowly, until we stood over its face."),
    ('وكانت عينه الوحدة مسكرة.', "And its one eye was closed.")),
  P(('قلت: هلق.', "I said: now."),
    ('ودفشنا الحديد بعينه، بكل قوتنا، كلنا مع بعض.', "And we drove the iron into its eye, with all our strength, all together."),
    ('وصرخ العملاق صرخة هزت القصر.', "And the giant gave a scream that shook the palace."),
    ('وقام، وصار يدور بإيديه، ويكسر كل إشي.', "And it got up, and began groping with its hands, breaking everything."),
    ('وإحنا ركضنا بين إجريه، وطلعنا من الباب، وركضنا عالشط.', "And we ran between its legs, out the door, and ran for the shore."),
    ('والعملاق وراءنا، أعمى، وبيصرخ، وبيتعثر.', "And the giant behind us, blind, screaming, stumbling."),
    ('ورمينا الطوف بالمي، وقفزنا عليه.', "And we threw the raft into the water, and jumped on it."))]),

 ('The Iron in the Fire', 'الحديد بالنار', [
  P(('كنا نجدف بإيدينا، والطوف بيبعد عالشط شوي شوي.', "We paddled with our hands, and the raft moved away from the shore little by little."),
    ('وفكرنا إنا نجينا.', "And we thought we were saved."),
    ('وبعدين شفنا عالشط اتنين تانيين.', "And then we saw on the shore two more."),
    ('عملاقين، جايين مع الأعمى، وماسكينه من إيده.', "Two giants, coming with the blind one, holding it by the hand."),
    ('ووقفوا عالشط، ورفعوا صخور كبيرة زي البيوت، ورموها علينا.', "And they stood on the shore, lifted rocks big as houses, and hurled them at us.")),
  P(('الصخرة الأولى وقعت جنبنا، والموج قلب نص الطوف.', "The first rock fell beside us, and the wave overturned half the raft."),
    ('والتانية ضربت بالنص، وكسرته.', "And the second struck the middle, and broke it."),
    ('والتالتة قتلت أكتر اللي كانوا معي.', "And the third killed most of those who were with me."),
    ('وصرنا تلاتة، على قطعة خشب، وبنجدف بكل روحنا.', "And we were three, on a piece of wood, paddling with all our souls."),
    ('لحد ما صاروا العمالقة زغار عالشط، وبعدين اختفوا.', "Until the giants were small on the shore, and then vanished."),
    ('ونحنا نبكي على اللي ماتوا، ونشكر الله إنا حيين.', "And we wept for those who had died, and thanked God that we were alive.")),
  P(('الموج رمانا بعد يومين على جزيرة تانية.', "The waves threw us after two days onto another island."),
    ('فيها فواكه ومي، فأكلنا وشربنا ونمنا.', "It had fruit and water, so we ate and drank and slept."),
    ('وبالليل، سمعت صوت زحف.', "And at night, I heard a slithering sound."),
    ('حية، طولها زي السفينة، وسمكها زي البرميل.', "A snake, long as a ship, thick as a barrel."),
    ('وقبل ما نتحرك، بلعت واحد من صاحبيّ، وهو نايم.', "And before we could move, it swallowed one of my two companions, in his sleep."),
    ('وسمعت عظامه بتنكسر جوا بطنها.', "And I heard his bones breaking inside its belly."),
    ('وزحفت الحية للغابة، شبعانة.', "And the snake slithered off into the forest, full.")),
  P(('تاني يوم، طلعنا أنا وصاحبي على شجرة عالية، ونمنا على غصن.', "The next day, my companion and I climbed a tall tree, and slept on a branch."),
    ('وبالليل، رجعت الحية.', "And at night, the snake came back."),
    ('لفت حول الشجرة، وطلعت، وطلعت، ووصلت لصاحبي، وبلعته.', "It wound around the tree, and climbed, and climbed, and reached my companion, and swallowed him."),
    ('وأنا فوقه بغصن، بتفرج، وما بقدر أعمل إشي.', "And I above him on a branch, watching, unable to do anything."),
    ('ونزلت الحية، وراحت.', "And the snake came down, and went."),
    ('وضليت أنا لحالي، آخر واحد.', "And I was left alone, the last one."),
    ('وعرفت إنه بكرا بالليل، دوري.', "And I knew that tomorrow night, it was my turn."))]),

 ('The Serpent and the Board', 'الحية واللوح', [
  P(('طول النهار، فكرت.', "All day, I thought."),
    ('الحية بتيجي بالليل، وبتبلع اللي بتوصله.', "The snake comes at night, and swallows whoever it reaches."),
    ('ما بقدر أهرب منها، وما بقدر أقاتلها.', "I cannot flee it, and I cannot fight it."),
    ('بس بقدر أمنعها توصلني.', "But I can prevent it from reaching me."),
    ('جمعت ألواح خشب من الطوف اللي رماه الموج عالشط.', "I gathered planks from the raft the waves had thrown on the shore."),
    ('وحبال من الشجر.', "And ropes from the trees.")),
  P(('وعملت لحالي صندوق.', "And I made myself a box."),
    ('لوح تحتي، ولوح فوقي، ولوح على كل جهة.', "A plank beneath me, a plank above, a plank on each side."),
    ('مربوطين بالحبال، وأنا بالنص.', "Tied with the ropes, and I in the middle."),
    ('وربطت الصندوق بجذع الشجرة، عشان الحية ما تدحرجه.', "And I tied the box to the trunk of the tree, so the snake could not roll it."),
    ('ودخلت فيه قبل الغروب، وسكرت آخر لوح، واستنيت.', "And I got inside before sunset, closed the last plank, and waited."),
    ('وإجا الليل، وإجت الحية.', "And night came, and the snake came.")),
  P(('سمعتها بتزحف حوالي الصندوق.', "I heard it slithering around the box."),
    ('وبعدين حسيت فيها بتلف حواليه، وبتعصر.', "And then I felt it winding around it, and squeezing."),
    ('الخشب صرّ، والحبال شدت، وأنا جوا، مكوم زي الجنين.', "The wood creaked, the ropes strained, and I inside, curled like an unborn child."),
    ('وحاولت تفوت راسها من كل جهة، وما لقت مكان.', "And it tried to push its head in from every side, and found no opening."),
    ('وضلت طول الليل تلف وتعصر وتفح.', "And all night it kept winding and squeezing and hissing."),
    ('وأنا بقول: يا رب، الخشب. خلي الخشب يصمد.', "And I kept saying: Lord, the wood. Let the wood hold."),
    ('ومع أول ضو، فكت حالها، وراحت.', "And with the first light, it uncoiled, and went.")),
  P(('طلعت من الصندوق، وأنا أرجف، وركضت عالشط.', "I came out of the box, shaking, and ran to the shore."),
    ('وشفت سفينة بعيدة.', "And I saw a distant ship."),
    ('صرخت، وشعلت نار، ولوحت بغصن.', "I shouted, lit a fire, waved a branch."),
    ('وشافوني، وبعتوا مركب، وأخدوني.', "And they saw me, sent a boat, and took me."),
    ('ولما حكيت لهم قصة الحية، ما صدقوا.', "And when I told them the story of the snake, they did not believe."),
    ('بس القبطان قال: صدقوه. أنا شفت العجايب بهالبحر.', "But the captain said: believe him. I have seen wonders in this sea."),
    ('وقال لي: عندي بضاعة لتاجر مات من سنين. بعتها وخد أجرك.', "And he said to me: I have goods of a merchant who died years ago. Sell them and take your wage."),
    ('وسألته: شو اسمه؟', "And I asked him: what was his name?"),
    ('قال: السندباد. تركناه على جزيرة، بالغلط، ونام.', "He said: Sindbad. We left him on an island, by mistake, asleep."),
    ('كانت سفينتي من الرحلة التانية.', "It was my ship from the second voyage."),
    ('وبكى القبطان لما عرفني، ورجعت على بغداد ببضاعتي وأرباحي.', "And the captain wept when he knew me, and I returned to Baghdad with my goods and my profits."))]),

 # ---------------- Voyage Four ----------------
 ('The Storm', 'العاصفة', [
  P(('قال السندباد برابع ليلة: يا حمّال، اسمع.', "Sindbad said on the fourth night: porter, listen."),
    ('هاي الرحلة أصعب من كل اللي قبلها.', "This voyage was harder than all before it."),
    ('لأنه فيها ما شفت وحوش، شفت بني آدم.', "Because in it I saw no monsters; I saw human beings."),
    ('سافرت من البصرة بسفينة جديدة، وبأصحاب جداد.', "I sailed from Basra on a new ship, with new companions."),
    ('وبعد أسابيع، إجت علينا عاصفة ما شفت زيها.', "And after weeks, a storm came upon us like none I had seen."),
    ('الموج زي الجبال، والريح بتصرخ، والسما سودا بالنهار.', "Waves like mountains, the wind screaming, the sky black by day.")),
  P(('الشراع انقطع، والسارية انكسرت.', "The sail tore, and the mast broke."),
    ('والسفينة انقلبت، وكلنا وقعنا بالبحر.', "And the ship overturned, and we all fell into the sea."),
    ('مسكت لوح، ومسك اللوح معي خمسة تانيين.', "I grabbed a plank, and five others grabbed the plank with me."),
    ('والموج حملنا يوم وليلة، لحد ما رمانا على شط.', "And the waves carried us a day and a night, until they threw us onto a shore."),
    ('وقعنا عالرمل، نص ميتين، وما قدرنا نتحرك.', "We fell on the sand, half dead, and could not move.")),
  P(('تاني يوم، مشينا لجوا، ولقينا ناس.', "The next day, we walked inland, and found people."),
    ('ناس عاريين، وجلدهم أسود، وعيونهم بتلمع بشكل غريب.', "Naked people, with black skin, and eyes that shone strangely."),
    ('ما حكوا معنا. أخدونا لملكهم.', "They did not speak to us. They took us to their king."),
    ('والملك ما حكى كمان. أشر، فجابوا لنا أكل.', "And the king did not speak either. He gestured, so they brought us food."),
    ('أكل غريب، أخضر، وريحته قوية.', "Strange food, green, with a strong smell."),
    ('أصحابي كانوا جوعانين، فأكلوا كتير.', "My companions were starving, so they ate a lot."),
    ('وأنا، ما بعرف ليش، ما حبيته، وأكلت شوي كتير.', "And I, I do not know why, did not like it, and ate very little.")),
  P(('وبعد أيام، لاحظت إشي.', "And after days, I noticed something."),
    ('أصحابي صاروا ياكلوا وياكلوا، وما يشبعوا.', "My companions ate and ate, and were never full."),
    ('وعيونهم صارت زي عيون أهل البلد: بتلمع، وفاضية.', "And their eyes became like the eyes of the people of the land: shining, and empty."),
    ('وما عادوا يحكوا معي، ولا يعرفوني.', "And they no longer spoke to me, or knew me."),
    ('وصاروا يسمنوا، يوم ورا يوم.', "And they grew fat, day after day."),
    ('وفهمت: الأكل كان دوا، بيقتل العقل وبيسمن الجسم.', "And I understood: the food was a drug, that kills the mind and fattens the body."),
    ('وهدول الناس، بياكلوا الناس.', "And these people ate people."),
    ('وكانوا بيربوا أصحابي، زي ما بيربوا الخراف.', "And they were fattening my companions, as one fattens sheep."))]),

 ('The King and the Saddle', 'الملك والسرج', [
  P(('كنت نحيف، فما حدا اهتم فيّ.', "I was thin, so no one paid me attention."),
    ('وبليلة، لما ناموا، طلعت من القرية، ومشيت.', "And one night, while they slept, I left the village, and walked."),
    ('مشيت سبع أيام، آكل عشب، وأشرب من المطر.', "I walked seven days, eating grass, drinking from the rain."),
    ('وبثامن يوم، شفت ناس بيجمعوا فلفل بحقل.', "And on the eighth day, I saw people picking pepper in a field."),
    ('ناس عاديين، لابسين، وعيونهم صاحية.', "Ordinary people, clothed, with clear eyes."),
    ('ركضت عليهم، وحكيت لهم قصتي.', "I ran to them, and told them my story."),
    ('وصدقوني، لأنهم بيعرفوا أكلة الناس.', "And they believed me, because they knew the man-eaters.")),
  P(('أخدوني لمدينتهم، وعند ملكهم.', "They took me to their city, and to their king."),
    ('كان ملك طيب، وسمع قصتي، وأعطاني بيت.', "He was a good king, who heard my story, and gave me a house."),
    ('وصرت أمشي بالمدينة، وأتفرج، وأتعلم.', "And I began walking around the city, watching, learning."),
    ('وبيوم، شفت الملك راكب حصان، وقاعد على ظهره بلا إشي.', "And one day, I saw the king riding a horse, sitting on its back with nothing."),
    ('لا سرج، ولا ركاب. زي ما بيركب الولد.', "No saddle, no stirrups. As a boy rides."),
    ('وسألت: ليش الملك بيركب هيك؟', "And I asked: why does the king ride like this?"),
    ('قالوا: وكيف غير هيك؟', "They said: and how else?"),
    ('ما كانوا يعرفوا السرج.', "They did not know the saddle.")),
  P(('رحت عند نجار، ورسمت له سرج على الأرض.', "I went to a carpenter, and drew him a saddle on the ground."),
    ('وعند حداد، ورسمت له ركاب.', "And to a blacksmith, and drew him stirrups."),
    ('وعند خياط، وعلمته يغطي الخشب بالجلد والصوف.', "And to a tailor, and taught him to cover the wood with leather and wool."),
    ('وبعد أسبوع، حطيت السرج على حصان الملك.', "And after a week, I put the saddle on the king's horse."),
    ('وركب الملك، وما نزل لحد المسا.', "And the king mounted, and did not get down until evening."),
    ('قال: يا سندباد، هاد أحسن إشي صار بمملكتي.', "He said: Sindbad, this is the best thing that has happened in my kingdom.")),
  P(('وطلب كل وزير سرج، وكل تاجر، وكل ضابط.', "And every minister asked for a saddle, and every merchant, and every officer."),
    ('وصرت غني، بلا بحر وبلا بضاعة، بسرج بس.', "And I became rich, without sea and without goods, with only a saddle."),
    ('وبيوم، قال لي الملك: يا سندباد، إنت صرت واحد منا.', "And one day, the king said to me: Sindbad, you have become one of us."),
    ('بدي أزوجك، عشان ما تفكر ترجع لبلدك.', "I want to marry you off, so you stop thinking of returning to your country."),
    ('وزوجني بنت من أحسن بيوت المدينة، حلوة وغنية وطيبة.', "And he married me to a girl from the best houses of the city, beautiful, rich and kind."),
    ('وعشت معها، وحبيتها.', "And I lived with her, and loved her."),
    ('وقلت: يمكن أنسى بغداد.', "And I said: perhaps I will forget Baghdad."),
    ('بس كان في قانون بهالمدينة، ما حدا حكى لي عنه.', "But there was a law in this city, that no one had told me about."))]),

 ('The Law of the City', 'قانون المدينة', [
  P(('كان جاري تاجر، وصاحبي، وماتت مرته.', "My neighbour was a merchant, and my friend, and his wife died."),
    ('رحت أعزيه، ولقيته بيبكي زي الولد.', "I went to console him, and found him weeping like a child."),
    ('قلت: الله يصبرك. إنت شاب، وبتتزوج مرة تانية.', "I said: God give you patience. You are young, and you will marry again."),
    ('تطلع فيّ، وقال: إنت ما بتعرف؟', "He looked at me, and said: do you not know?"),
    ('قلت: شو؟', "I said: what?"),
    ('قال: القانون. اللي بتموت مرته، بيندفن معها. واللي بيموت زوجها، بتندفن معه.', "He said: the law. A man whose wife dies is buried with her. And a woman whose husband dies is buried with him."),
    ('حي.', "Alive.")),
  P(('ما صدقت، لحد ما شفت بعيني.', "I did not believe, until I saw with my own eyes."),
    ('غسلوا مرته، ولبسوها أحسن تيابها، وحطوها بصندوق.', "They washed his wife, dressed her in her best clothes, and put her in a coffin."),
    ('ومشوا فيها لجبل برا المدينة، وفوقه حجر كبير.', "And they carried her to a mountain outside the city, with a big stone on top."),
    ('شالوا الحجر، وكان تحته بير عميق، أسود.', "They lifted the stone, and beneath it was a deep well, black."),
    ('نزلوا الصندوق فيه بالحبال.', "They lowered the coffin into it with ropes."),
    ('وبعدين ربطوا جاري بالحبال، وأعطوه سبع خبزات وجرة مي.', "And then they tied my neighbour with ropes, and gave him seven loaves and a jar of water."),
    ('ونزلوه وراها، وهو بيصرخ.', "And they lowered him after her, as he screamed."),
    ('ورجعوا الحجر مكانه.', "And they put the stone back in its place.")),
  P(('رجعت عالبيت، ورحت للملك.', "I went home, and went to the king."),
    ('قلت: يا ملك، أنا غريب. هالقانون ما بينطبق عليّ.', "I said: my king, I am a foreigner. This law does not apply to me."),
    ('قال الملك: إنت واحد منا. قلتها بنفسي.', "The king said: you are one of us. I said so myself."),
    ('القانون على الكل. عليّ أنا كمان.', "The law is for all. For me too."),
    ('ورجعت عالبيت، وتطلعت بمرتي.', "And I went home, and looked at my wife."),
    ('وصرت أدعي كل ليلة: يا رب، خليني أموت قبلها.', "And I began praying every night: Lord, let me die before her."),
    ('وهي كمان، كانت تدعي نفس الدعا.', "And she too prayed the same prayer.")),
  P(('وبعد سنة، مرضت مرتي.', "And after a year, my wife fell ill."),
    ('ومرضت، ومرضت، وماتت.', "And she grew sicker, and sicker, and died."),
    ('وإجوا، وغسلوها، ولبسوها، وحطوها بالصندوق.', "And they came, washed her, dressed her, put her in the coffin."),
    ('وربطوني، وأعطوني سبع خبزات وجرة مي.', "And they tied me, and gave me seven loaves and a jar of water."),
    ('وصرخت، وقلت: أنا غريب! أنا من بغداد!', "And I screamed, and said: I am a foreigner! I am from Baghdad!"),
    ('وما حدا سمع.', "And no one listened."),
    ('ونزلوني بالبير، والحجر رجع مكانه، والدنيا صارت سودا.', "And they lowered me into the well, the stone went back in place, and the world went black."))]),

 ('The Way Out', 'طريق الخروج', [
  P(('فكيت الحبال، ووقفت، وما شفت إشي.', "I undid the ropes, stood up, and saw nothing."),
    ('عتمة كاملة، وريحة موت، وصوت مي بتنقط من بعيد.', "Complete darkness, the smell of death, and the sound of water dripping far off."),
    ('مشيت وإيدي قدامي، ودعست على عظام.', "I walked with my hands before me, and stepped on bones."),
    ('كانت المغارة كبيرة، وفيها كل الموتى من مية سنة.', "The cave was big, with all the dead of a hundred years in it."),
    ('قعدت بزاوية، وأكلت خبزة وحدة، وشربت شوي.', "I sat in a corner, ate one loaf, and drank a little."),
    ('وقلت: سبع خبزات، سبع أيام. وبعدين بموت.', "And I said: seven loaves, seven days. And then I die.")),
  P(('وبعد أيام، سمعت الحجر بينشال.', "And after days, I heard the stone being lifted."),
    ('ونزل ضو، وصندوق، ووراه واحد بيبكي.', "And light came down, and a coffin, and after it someone weeping."),
    ('رجل نزلوه مع مرته الميتة، ومعه خبزه وميته.', "A man they had lowered with his dead wife, with his bread and water."),
    ('ورجع الحجر، ورجعت العتمة.', "And the stone went back, and the darkness returned."),
    ('ومشيت عليه بالعتمة، وأخدت خبزه وميته.', "And I went to him in the darkness, and took his bread and water."),
    ('ما بدي أحكي لك كيف.', "I do not want to tell you how."),
    ('قال الحمّال: ما بدي أعرف.', "The porter said: I do not want to know."),
    ('قال السندباد: الجوع بيخلي الإنسان إشي تاني. وأنا عشت، وهو ما عاش.', "Sindbad said: hunger makes a person into something else. And I lived, and he did not.")),
  P(('وضليت هيك شهور. كل ما ينزلوا واحد، آخد أكله.', "And I stayed like that for months. Every time they lowered one, I took his food."),
    ('وبيوم، سمعت صوت مش من فوق.', "And one day, I heard a sound not from above."),
    ('صوت تنفس، وأقدام زغيرة، من جوا المغارة.', "The sound of breathing, and small feet, from inside the cave."),
    ('حيوان. إجا ياكل من الموتى، وشافني، وهرب.', "An animal. It had come to eat from the dead, saw me, and fled."),
    ('وفكرت: من وين فات؟', "And I thought: where did it come in from?"),
    ('ومشيت وراه بالعتمة، بين العظام، ساعات.', "And I followed it in the dark, among the bones, for hours."),
    ('لحد ما شفت نقطة ضو.', "Until I saw a point of light.")),
  P(('كان شق بالصخر، بيطلع عالبحر.', "It was a crack in the rock, opening onto the sea."),
    ('زحفت فيه، وطلعت، وشفت الشمس، وبكيت.', "I crawled through it, came out, saw the sun, and wept."),
    ('وبعدين رجعت عالمغارة.', "And then I went back into the cave."),
    ('قال الحمّال: رجعت؟!', "The porter said: you went back?!"),
    ('قال السندباد: رجعت. لأنه كل ميت نزلوه، نزلوا معه ذهبه ومجوهراته.', "Sindbad said: I went back. Because every dead person they lowered, they lowered his gold and jewels with him."),
    ('وجمعت من المغارة أكتر مما جمعت من كل رحلاتي.', "And I gathered from the cave more than I had gathered from all my voyages."),
    ('وقعدت عالشط، عند الشق، أيام، لحد ما مرت سفينة.', "And I sat on the shore, by the crack, for days, until a ship passed."),
    ('وقلت لهم: أنا تاجر غرقت سفينتي. وما حكيت عن المغارة.', "And I told them: I am a merchant whose ship sank. And I said nothing of the cave."),
    ('ورجعت على بغداد، ومعي ذهب الموتى.', "And I returned to Baghdad, with the gold of the dead."),
    ('وأعطى السندباد الحمّال مية دينار، وما ضحك تلك الليلة.', "And Sindbad gave the porter a hundred dinars, and did not laugh that night."))]),

 # ---------------- Voyage Five ----------------
 ('The Broken Egg', 'البيضة المكسورة', [
  P(('بخامس ليلة، قال السندباد: هالمرة، اشتريت سفينة لحالي.', "On the fifth night, Sindbad said: this time, I bought a ship of my own."),
    ('قلت: القبطان بيهرب، والقبطان بينسى. أنا بكون القبطان.', "I said: the captain flees, and the captain forgets. I will be the captain."),
    ('وأخدت معي تجار، وسافرنا.', "And I took merchants with me, and we sailed."),
    ('وبيوم، وصلنا على جزيرة، وشفت عليها من بعيد قبة بيضا.', "And one day, we reached an island, and I saw on it from afar a white dome."),
    ('وقلبي وقف.', "And my heart stopped."),
    ('قلت للتجار: لا تنزلوا. هاي بيضة رخ.', "I said to the merchants: do not go down. This is a Rukh's egg.")),
  P(('بس التجار ما سمعوا.', "But the merchants did not listen."),
    ('نزلوا، ولفوا حوالي البيضة.', "They went down, and went around the egg."),
    ('وضربوها بالحجار، لحد ما كسروها.', "And they struck it with stones, until they broke it."),
    ('وطلع منها فرخ رخ، كبير زي البيت، وقتلوه، وأخدوا لحمه.', "And a Rukh chick came out, big as a house, and they killed it, and took its meat."),
    ('ورجعوا عالسفينة، وهم بيضحكوا، ومعهم اللحمة.', "And they came back to the ship, laughing, with the meat."),
    ('قلت: يا مجانين! ارفعوا الشراع! بسرعة!', "I said: madmen! Raise the sail! Quickly!"),
    ('وقبل ما نبعد، صارت الدنيا عتمة.', "And before we got away, the world went dark.")),
  P(('الرخ، الأم والأب.', "The Rukh, the mother and the father."),
    ('اتنين، جناحاتهم غطت السما.', "Two of them, their wings covering the sky."),
    ('وشافوا البيضة المكسورة، وصرخوا صرخة كسرت قلوبنا.', "And they saw the broken egg, and gave a scream that broke our hearts."),
    ('وطاروا بعيد، وفكرنا إنهم راحوا.', "And they flew far off, and we thought they had gone."),
    ('بس رجعوا.', "But they came back."),
    ('وبمخالب كل واحد، صخرة زي الجبل.', "And in the claws of each, a rock like a mountain.")),
  P(('الأول رمى صخرته، ووقعت جنب السفينة، والموج رفعنا للسما.', "The first dropped its rock, and it fell beside the ship, and the wave lifted us to the sky."),
    ('والتاني رمى صخرته علينا دغري.', "And the second dropped its rock straight onto us."),
    ('انكسرت السفينة نصين، وطارت الألواح، ووقعنا كلنا بالبحر.', "The ship broke in two, planks flew, and we all fell into the sea."),
    ('ومسكت لوح، مرة تانية، زي كل مرة.', "And I grabbed a plank, once again, as every time."),
    ('وقال الحمّال: كل مرة لوح؟', "And the porter said: every time a plank?"),
    ('قال السندباد: كل مرة. الله بيبعت اللوح، والباقي عليّ.', "Sindbad said: every time. God sends the plank, and the rest is up to me."))]),

 ('The Old Man of the Sea', 'شيخ البحر', [
  P(('الموج رماني على جزيرة فيها شجر وفواكه ونهر.', "The waves threw me onto an island with trees and fruit and a river."),
    ('وقلت: الحمد لله، هاي أحسن من كل اللي قبلها.', "And I said: praise God, this is better than all before it."),
    ('وبعد يوم، لقيت عند النهر رجل كبير بالعمر، قاعد.', "And after a day, I found by the river an old man, sitting."),
    ('نحيف، وضعيف، ولابس ورق شجر.', "Thin, and weak, dressed in leaves."),
    ('وأشر لي بإيده على الجهة التانية من النهر.', "And he gestured to me toward the other side of the river."),
    ('زي إنه بده يعبر.', "As if he wanted to cross."),
    ('قلت: مسكين. رح أحمله.', "I said: poor man. I will carry him.")),
  P(('حطيته على كتافي، وعبرت النهر.', "I put him on my shoulders, and crossed the river."),
    ('وبالجهة التانية، انحنيت عشان ينزل.', "And on the other side, I bent so he could get down."),
    ('ما نزل.', "He did not get down."),
    ('لف إجريه حول رقبتي، وشد.', "He wound his legs around my neck, and squeezed."),
    ('إجرين زي الجلد الأسود، قاسية، وقوية زي الحديد.', "Legs like black leather, hard, and strong as iron."),
    ('ما قدرت أتنفس، ووقعت عالأرض.', "I could not breathe, and fell to the ground."),
    ('وهو ضرب على راسي بإيده، وأشر: قوم. امشي.', "And he struck my head with his hand, and gestured: get up. Walk.")),
  P(('ومشيت.', "And I walked."),
    ('من الصبح للمسا، وهو على كتافي، وإجريه حول رقبتي.', "From morning to evening, him on my shoulders, his legs around my neck."),
    ('كل ما أوقف، يعصر. كل ما أبطئ، يضرب.', "Every time I stopped, he squeezed. Every time I slowed, he struck."),
    ('وكان ياكل من الشجر وهو فوقي، ويبول عليّ، وينام على كتافي.', "And he ate from the trees while on me, and relieved himself on me, and slept on my shoulders."),
    ('وحتى بالنوم، إجريه ما بتفك.', "And even asleep, his legs did not loosen."),
    ('أيام. وبعدين أسابيع.', "Days. And then weeks."),
    ('وصرت زي حمار، وهو صاحب الحمار.', "And I became like a donkey, and he the donkey's owner."),
    ('وفكرت: من كل الموت اللي شفته، هاد الأسوأ.', "And I thought: of all the deaths I have seen, this is the worst.")),
  P(('قال الحمّال: وليش؟ ما كان بيقتلك.', "The porter said: and why? He was not killing you."),
    ('قال السندباد: لأنه ما كان بيقتلني.', "Sindbad said: because he was not killing me."),
    ('العملاق بياكلك وبتخلص. والحية بتبلعك وبتخلص.', "The giant eats you and it is over. The snake swallows you and it is over."),
    ('بس هاد، كان بده إياني أعيش، عشانه.', "But this one wanted me to live, for his sake."),
    ('كل يوم، لحد ما أموت من التعب.', "Every day, until I died of exhaustion."),
    ('وشفت تحت الشجر عظام ناس، وفهمت إنهم كانوا قبلي.', "And I saw under the trees the bones of men, and understood they had been before me."),
    ('حمير قديمة لشيخ البحر.', "Old donkeys of the Old Man of the Sea."))]),

 ('The Wine', 'النبيذ', [
  P(('بيوم، وأنا ماشي، شفت قرع كبير مرمي تحت شجرة.', "One day, as I walked, I saw a big gourd lying under a tree."),
    ('يابس، وفاضي من جوا.', "Dry, and hollow inside."),
    ('وحواليه عنب، كتير، وناضج، ووقع عالأرض.', "And around it grapes, many, ripe, fallen to the ground."),
    ('وإجت لي فكرة، من أيام بغداد.', "And an idea came to me, from the days of Baghdad."),
    ('جمعت العنب، وعصرته بالقرع، وسكرته، وحطيته بالشمس.', "I gathered the grapes, pressed them into the gourd, sealed it, and put it in the sun."),
    ('والشيخ فوقي، بيتفرج، وما بيفهم.', "And the old man on top of me, watching, not understanding.")),
  P(('بعد أيام، رجعت للقرع.', "After days, I went back to the gourd."),
    ('كان العنب صار نبيذ.', "The grapes had become wine."),
    ('شربت منه، وحسيت بالدفا، وقوة، ونسيت شوي من تعبي.', "I drank of it, and felt warmth, and strength, and forgot a little of my exhaustion."),
    ('وصرت أغني، وأرقص، والشيخ على كتافي.', "And I began singing, and dancing, the old man on my shoulders."),
    ('والشيخ شاف، وضرب على راسي، وأشر: أعطيني.', "And the old man saw, struck my head, and gestured: give me."),
    ('أعطيته القرع.', "I gave him the gourd.")),
  P(('شرب. وشرب. وشرب لحد ما فضي القرع.', "He drank. And drank. And drank until the gourd was empty."),
    ('وبلش يضحك، ويهز راسه، ويغني بصوت مش صوت.', "And he began laughing, wagging his head, singing in a voice that was no voice."),
    ('وشوي شوي، حسيت إجريه بتفك.', "And little by little, I felt his legs loosening."),
    ('قدرت أتنفس. قدرت أحرك راسي.', "I could breathe. I could move my head."),
    ('ووقفت ساكت، لا أتحرك، لحد ما نام.', "And I stood still, not moving, until he slept."),
    ('نام، وإجريه رخوة، وراسه على كتفي.', "He slept, his legs slack, his head on my shoulder.")),
  P(('مسكت إجريه، ورفعتهم عن رقبتي، ورميته عالأرض.', "I gripped his legs, lifted them from my neck, and threw him to the ground."),
    ('ووقفت فوقه، وهو نايم.', "And I stood over him, as he slept."),
    ('ورفعت حجر.', "And I lifted a stone."),
    ('قال الحمّال: وقتلته؟', "The porter said: and you killed him?"),
    ('قال السندباد: قتلته.', "Sindbad said: I killed him."),
    ('وما بندم، ولا يوم. لأنه لو فاق، كان رجع على كتافي.', "And I do not regret it, not one day. Because had he woken, he would have gone back on my shoulders."),
    ('وركضت للشط، وبعد يومين مرت سفينة، وأخدوني.', "And I ran to the shore, and after two days a ship passed, and took me."),
    ('ولما حكيت لهم، قال القبطان: هاد شيخ البحر. ما حدا نجا منه قبلك.', "And when I told them, the captain said: that is the Old Man of the Sea. No one escaped him before you."))]),

 ('The City of Apes', 'مدينة القرود', [
  P(('السفينة وصلتنا على مدينة كبيرة، عالبحر، بيوتها عالية.', "The ship brought us to a big city, on the sea, with tall houses."),
    ('وشفت إشي غريب: مع الغروب، كل الناس بيطلعوا من المدينة.', "And I saw something strange: at sunset, all the people leave the city."),
    ('بيركبوا مراكب، وبيناموا بالبحر، وبيرجعوا الصبح.', "They board boats, sleep on the sea, and return in the morning."),
    ('وسألت: ليش؟', "And I asked: why?"),
    ('قالوا: القرود.', "They said: the apes."),
    ('كل ليلة، بينزل من الجبل آلاف القرود.', "Every night, thousands of apes come down from the mountain."),
    ('بيدخلوا المدينة، وبيقتلوا اللي بيلاقوه.', "They enter the city, and kill whoever they find.")),
  P(('وأنا ما كان معي مصاري، وما حدا أخدني بمركبه.', "And I had no money, and no one took me in his boat."),
    ('وإجا الليل، وأنا بالمدينة لحالي.', "And night came, and I was in the city alone."),
    ('وسمعتهم بينزلوا من الجبل، زي المطر.', "And I heard them coming down from the mountain, like rain."),
    ('ركضت وتخبيت ببيت، وسكرت الباب، وطلعت عالسطح.', "I ran and hid in a house, locked the door, and went up to the roof."),
    ('وطول الليل، سمعتهم بيكسروا الأبواب تحتي، وبيصرخوا.', "And all night, I heard them breaking doors beneath me, and screeching."),
    ('وبالصبح، طلعوا للجبل، ورجع الناس.', "And in the morning, they went up to the mountain, and the people returned.")),
  P(('وواحد من الناس شافني نازل من السطح، واستغرب إني حي.', "And one of the people saw me coming down from the roof, and was amazed I was alive."),
    ('قال: تعال معي بكرا. بعلمك كيف بنعيش هون.', "He said: come with me tomorrow. I will teach you how we live here."),
    ('وبالصبح، أعطاني كيس، وحجار، ومشينا للجبل.', "And in the morning, he gave me a sack, and stones, and we walked to the mountain."),
    ('كان الجبل مليان شجر جوز هند.', "The mountain was full of coconut trees."),
    ('عالي كتير، ما حدا بيقدر يطلعه.', "Very tall, that no one could climb."),
    ('والقرود عالشجر، نايمين، بعد ليلتهم بالمدينة.', "And the apes were in the trees, sleeping, after their night in the city.")),
  P(('قال: ارمي عليهم حجار.', "He said: throw stones at them."),
    ('رميت، والقرود فاقوا، وزعلوا.', "I threw, and the apes woke, and were angry."),
    ('وردوا علينا. بس ما كان عندهم حجار.', "And they answered us. But they had no stones."),
    ('كان عندهم جوز هند.', "They had coconuts."),
    ('وصاروا يقطفوا جوز الهند ويرموه علينا، بغضب، مئات.', "And they began picking coconuts and hurling them at us, in fury, hundreds."),
    ('وإحنا نجمعه بالأكياس، ونضحك.', "And we gathered them into the sacks, laughing."),
    ('قال: هيك بنعيش. هم بيقطفوا، وإحنا بنبيع.', "He said: this is how we live. They pick, and we sell."),
    ('وشتغلت هيك شهور، وجمعت مصاري، ورجعت على بغداد.', "And I worked like that for months, gathered money, and returned to Baghdad."),
    ('وضحك الحمّال، وقال: هاي أحسن رحلة.', "And the porter laughed, and said: this is the best voyage."),
    ('قال السندباد: لأنه ما مات فيها حدا. غير الشيخ.', "Sindbad said: because no one died in it. Except the old man."))]),

 # ---------------- Voyage Six ----------------
 ('The Mountain of Wrecks', 'جبل السفن المكسورة', [
  P(('بسادس ليلة، قال السندباد: هالرحلة، ما كان فيها وحش.', "On the sixth night, Sindbad said: this voyage had no monster."),
    ('ولا عملاق، ولا شيخ.', "No giant, no old man."),
    ('كان فيها جبل.', "It had a mountain."),
    ('سافرنا بسفينة كبيرة، والقبطان كان أحسن قبطان بالبصرة.', "We sailed on a big ship, and the captain was the best captain in Basra."),
    ('وبيوم، القبطان طلع عالسطح، وصار يبكي، ويشد لحيته.', "And one day, the captain came up on deck, and began to weep, and pull his beard."),
    ('قلنا: شو صار؟', "We said: what has happened?"),
    ('قال: ضعنا. التيار أخدنا لمكان ما بيرجع منه حدا.', "He said: we are lost. The current has taken us to a place from which no one returns.")),
  P(('وشفنا الجبل قدامنا.', "And we saw the mountain before us."),
    ('جبل عالي، أسود، طالع من البحر دغري.', "A high mountain, black, rising straight out of the sea."),
    ('وعند قاعدته، سفن. مئات السفن.', "And at its foot, ships. Hundreds of ships."),
    ('مكسورة، وقديمة، ومرمية على الصخر، بعضها فوق بعض.', "Broken, and old, thrown on the rocks, some on top of others."),
    ('قال القبطان: كل سفينة وصلت لهون، انكسرت هون.', "The captain said: every ship that reached here broke here."),
    ('التيار بيجيبها، والجبل بيكسرها، وما في طريق رجعة.', "The current brings her, the mountain breaks her, and there is no way back."),
    ('والموج حملنا على الصخر، وانكسرت سفينتنا زي الباقي.', "And the waves carried us onto the rocks, and our ship broke like the rest.")),
  P(('نجينا كلنا، وطلعنا على شط ضيق تحت الجبل.', "We all survived, and came up onto a narrow shore beneath the mountain."),
    ('وشفنا حواليه، بين السفن المكسورة، الكنوز.', "And we saw around us, among the broken ships, the treasures."),
    ('ذهب، وفضة، وحرير، ولؤلؤ، وعنبر، وكل بضاعة سفينة انكسرت.', "Gold, silver, silk, pearls, ambergris, and every cargo of every ship that had broken."),
    ('وبينها عظام اللي ماتوا.', "And among them the bones of those who had died."),
    ('كنا أغنى ناس بالدنيا، ومش قادرين نطلع.', "We were the richest people in the world, and unable to leave."),
    ('لأنه الجبل ما بينطلع، والبحر ما بينعبر.', "Because the mountain could not be climbed, and the sea could not be crossed.")),
  P(('وبلش الأكل يخلص.', "And the food began to run out."),
    ('وبلش الناس يموتوا، واحد ورا واحد.', "And the people began to die, one after another."),
    ('وكنا ندفن كل واحد بمكانه، لحد ما ما ضل حدا يدفن.', "And we buried each one where he lay, until no one was left to bury."),
    ('وضليت أنا، آخر واحد، زي كل مرة.', "And I remained, the last one, as every time."),
    ('وحفرت لحالي قبر، جنب الباقي.', "And I dug myself a grave, beside the rest."),
    ('وقلت: لما أحس إني رح أموت، بنام فيه.', "And I said: when I feel I am about to die, I will lie in it."),
    ('عشان الريح تغطيني بالرمل.', "So the wind covers me with sand."))]),

 ('The River Under the Mountain', 'النهر تحت الجبل', [
  P(('وأنا قاعد جنب قبري، لاحظت إشي ما لاحظته قبل.', "And as I sat beside my grave, I noticed something I had not noticed before."),
    ('نهر زغير، حلو، بينزل من الجبل، وبيفوت بمغارة تحته.', "A small river, sweet, coming down from the mountain, and going into a cave beneath it."),
    ('بيفوت، وما بيطلع.', "It goes in, and does not come out."),
    ('وقلت: النهر رايح لمكان. والمكان مش هون.', "And I said: the river is going somewhere. And somewhere is not here."),
    ('يمكن يطلع بالجهة التانية من الجبل.', "Perhaps it comes out on the other side of the mountain."),
    ('يمكن يوصل لبلد فيه ناس.', "Perhaps it reaches a country with people."),
    ('ويمكن يوصل للعتمة بس، وأموت جواته.', "And perhaps it reaches only darkness, and I die inside it."),
    ('بس هون، أنا ميت أكيد.', "But here, I was certainly dead.")),
  P(('عملت طوف زغير من خشب السفن.', "I made a small raft from the wood of the ships."),
    ('ضيق، قد النهر، وطويل قدي.', "Narrow, the width of the river, and as long as myself."),
    ('وحملته باللي ضل من الأكل، وبأحسن اللي لقيته.', "And I loaded it with what remained of the food, and the best of what I had found."),
    ('لؤلؤ، وعنبر، وأحجار.', "Pearls, ambergris, stones."),
    ('وربطت حالي فيه، ودفعته بالنهر.', "And I tied myself to it, and pushed it into the river."),
    ('ودخلت المغارة.', "And I entered the cave.")),
  P(('عتمة.', "Darkness."),
    ('الصخر فوقي، قريب لدرجة إنه بيحك راسي.', "The rock above me, so close it scraped my head."),
    ('وصوت المي بس.', "And only the sound of the water."),
    ('تمددت على ظهري، والطوف بيمشي مع التيار.', "I lay on my back, the raft moving with the current."),
    ('ساعات، وأيام، ما بعرف.', "Hours, days, I do not know."),
    ('وأكلت آخر خبزة، وشربت من النهر.', "And I ate the last loaf, and drank from the river."),
    ('ونمت.', "And I slept."),
    ('نوم عميق، زي الموت، بس مش موت.', "A deep sleep, like death, but not death.")),
  P(('وفقت على ضو، وأصوات.', "And I woke to light, and voices."),
    ('كنت على شط نهر، تحت الشمس.', "I was on a riverbank, under the sun."),
    ('وحوالي ناس، بيحكوا لغة ما بعرفها.', "And around me people, speaking a language I did not know."),
    ('واحد منهم حكى عربي. قال: مين إنت؟ ومن وين جيت؟', "One of them spoke Arabic. He said: who are you? And where did you come from?"),
    ('قلت: من تحت الجبل.', "I said: from under the mountain."),
    ('صاروا يتطلعوا ببعض، وما صدقوا.', "They looked at each other, and did not believe."),
    ('وحكيت لهم القصة، من السفينة للطوف.', "And I told them the story, from the ship to the raft."),
    ('وقالوا: هاي عجيبة. لازم الملك يسمعها.', "And they said: this is a marvel. The king must hear it."),
    ('وسألت: أي ملك؟ وأي بلد؟', "And I asked: which king? And which country?"),
    ('قالوا: سرنديب.', "They said: Serendib."))]),

 ('Serendib', 'سرنديب', [
  P(('سرنديب جزيرة كبيرة، خضرا، وفيها جبل عالي بنص السما.', "Serendib is a big island, green, with a high mountain in the middle of the sky."),
    ('بيقولوا إن آدم نزل عليه لما طلع من الجنة.', "They say Adam came down onto it when he left Paradise."),
    ('وفيها كل إشي: ياقوت، ولؤلؤ، وفيلة، وقرفة.', "And it has everything: rubies, pearls, elephants, cinnamon."),
    ('وملكها كان أعظم ملك شفته.', "And its king was the greatest king I had seen."),
    ('بيركب فيل، وحواليه ألف رجل.', "He rides an elephant, with a thousand men around him."),
    ('وقدامه واحد بينادي: هاد الملك!', "And before him one calling: this is the king!"),
    ('وورا الملك، واحد تاني بينادي: وهاد بيموت زي أي واحد.', "And behind the king, another calling: and he dies like anyone."),
    ('عشان الملك ما ينسى.', "So the king does not forget.")),
  P(('أخدوني للملك، وحكيت له قصتي، وقصة الجبل والنهر.', "They took me to the king, and I told him my story, and the story of the mountain and the river."),
    ('وفرجيته اللي جبته عالطوف.', "And I showed him what I had brought on the raft."),
    ('وأعطيته أحسن اللؤلؤ والعنبر، هدية.', "And I gave him the best of the pearls and the ambergris, as a gift."),
    ('قال: من وين إنت؟', "He said: where are you from?"),
    ('قلت: من بغداد، من بلاد الخليفة هارون الرشيد.', "I said: from Baghdad, from the lands of the Caliph Harun al-Rashid."),
    ('قال: سمعت عنه. بيقولوا إنه ملك عادل.', "He said: I have heard of him. They say he is a just king."),
    ('قلت: هو أعدل ملك بالدنيا.', "I said: he is the justest king in the world."),
    ('وضحك الملك، وقال: كل واحد بيقول هيك عن ملكه.', "And the king laughed, and said: everyone says that of his king.")),
  P(('عشت بسرنديب شهور، ضيف الملك.', "I lived in Serendib for months, the king's guest."),
    ('ورحت أشوف الجبل اللي نزل عليه آدم.', "And I went to see the mountain Adam came down onto."),
    ('وشفت بالسوق ياقوت زي البيض، وفيلة بتشتغل زي الخدم.', "And I saw in the market rubies like eggs, and elephants working like servants."),
    ('وكل يوم كنت أتعلم إشي جديد.', "And every day I learned something new."),
    ('بس كل ليلة، كنت أحلم ببغداد.', "But every night, I dreamed of Baghdad."),
    ('بدجلة، وبالمساجد، وبريحة الخبز الصبح.', "Of the Tigris, the mosques, the smell of bread in the morning."),
    ('وفهمت إشي: الغريب بيحب البلد اللي بيشوفها.', "And I understood something: the stranger loves the country he sees."),
    ('وبيشتاق للبلد اللي تركها.', "And he longs for the country he left.")),
  P(('ورحت عند الملك، وقلت: يا ملك، بدي أرجع.', "And I went to the king, and said: my king, I want to go home."),
    ('قال: ليش؟ عندك هون كل إشي.', "He said: why? You have everything here."),
    ('قلت: ما عندي بغداد.', "I said: I do not have Baghdad."),
    ('وسكت الملك، وبعدين قال: طيب. بس بدي منك خدمة.', "And the king was silent, and then said: fine. But I want a service from you."),
    ('وأنا قلت: أمرك.', "And I said: at your command."),
    ('وما كنت أعرف إن هالخدمة رح تخليني أرجع للبحر مرة تانية.', "And I did not know that this service would send me back to sea one more time."))]),

 ('The King’s Letter', 'مكتوب الملك', [
  P(('قال الملك: بدي أبعت مكتوب للخليفة هارون الرشيد. وإنت بتحمله.', "The king said: I want to send a letter to the Caliph Harun al-Rashid. And you carry it."),
    ('وكتب المكتوب على جلد غزال، بماء الذهب.', "And he wrote the letter on gazelle skin, in gold ink."),
    ('وكتب فيه: من ملك سرنديب، لملك العرب.', "And in it he wrote: from the king of Serendib, to the king of the Arabs."),
    ('السلام عليك. بنبعت لك هدية، وبنطلب صداقتك.', "Peace be upon you. We send you a gift, and ask your friendship."),
    ('وبنطلب منك تكرم اللي حمل المكتوب.', "And we ask you to honour the one who carried the letter.")),
  P(('والهدية كانت: كاسة من ياقوت واحد، مليانة لؤلؤ.', "And the gift was: a cup of a single ruby, full of pearls."),
    ('وجلد حية، اللي بينام عليه ما بيمرض.', "And a snakeskin, on which whoever sleeps does not fall ill."),
    ('وجارية حلوة، وفيل أبيض.', "And a beautiful slave girl, and a white elephant."),
    ('وحطوا كل هاد بسفينة، وودعني الملك بنفسه عالميناء.', "And they put all this on a ship, and the king himself saw me off at the harbour."),
    ('وقال: يا سندباد، إذا رجعت، بابي مفتوح.', "And he said: Sindbad, if you return, my door is open."),
    ('وأبحرنا، وكان البحر هادي، ووصلنا البصرة، وبعدها بغداد.', "And we sailed, and the sea was calm, and we reached Basra, and then Baghdad.")),
  P(('ودخلت على الخليفة، وقبلت الأرض، وأعطيته المكتوب والهدية.', "And I went in to the Caliph, kissed the ground, and gave him the letter and the gift."),
    ('قرا المكتوب، وشاف الكاسة، وقال: هالملك غني ولا فقير؟', "He read the letter, saw the cup, and said: is this king rich or poor?"),
    ('قلت: أغنى من كل ملوك الأرض، إلاك.', "I said: richer than all the kings of the earth, except you."),
    ('وحكيت له عن سرنديب، والفيل، والجبل.', "And I told him of Serendib, the elephant, the mountain."),
    ('وعن المنادي اللي بيقول: بيموت زي أي واحد.', "And of the crier who says: he dies like anyone."),
    ('وضحك الخليفة كتير، وأعجبه المنادي.', "And the Caliph laughed a great deal, and liked the crier."),
    ('وقال: يا سندباد، إنت خدمتني. بدي أكافيك.', "And he said: Sindbad, you have served me. I want to reward you.")),
  P(('وأعطاني خلعة، وذهب، وقال: هالمرة، خلص. اقعد ببغداد.', "And he gave me a robe of honour, and gold, and said: this time, that is enough. Stay in Baghdad."),
    ('وقلت: يا أمير المؤمنين، هاد اللي بدي ياه.', "And I said: Commander of the Faithful, that is what I want."),
    ('ورجعت لبيتي، وقعدت، وحلفت.', "And I went home, and sat down, and swore."),
    ('حلفت إني ما برجع عالبحر أبداً.', "I swore I would never go back to sea."),
    ('قال الحمّال: بس في رحلة سابعة.', "The porter said: but there is a seventh voyage."),
    ('قال السندباد: في. لأنه الخليفة هو اللي بعتني.', "Sindbad said: there is. Because the Caliph is the one who sent me."))]),

 # ---------------- Voyage Seven ----------------
 ('One Last Time', 'آخر مرة', [
  P(('بسابع ليلة، قال السندباد: بعد سنة، ناداني الخليفة.', "On the seventh night, Sindbad said: after a year, the Caliph called me."),
    ('قال: يا سندباد، بدي أرد على ملك سرنديب. وإنت الوحيد اللي بيعرف الطريق.', "He said: Sindbad, I want to answer the king of Serendib. And you are the only one who knows the way."),
    ('قلت: يا أمير المؤمنين، أنا حلفت.', "I said: Commander of the Faithful, I swore."),
    ('قال: وأنا بطلب.', "He said: and I am asking."),
    ('وما حدا بيرد على الخليفة.', "And no one refuses the Caliph."),
    ('فأخدت مكتوبه وهديته، ونزلت عالبصرة.', "So I took his letter and his gift, and went down to Basra."),
    ('وركبت البحر، للمرة السابعة.', "And I took to the sea, for the seventh time.")),
  P(('وصلنا سرنديب بسلام، وسلمت المكتوب، وفرح الملك.', "We reached Serendib in peace, I delivered the letter, and the king rejoiced."),
    ('وقعدت عنده شهر، وودعته، وركبت السفينة راجع.', "And I stayed with him a month, bade him farewell, and boarded the ship home."),
    ('وقلت: خلص. آخر مرة. الطريق معروف، والبحر هادي.', "And I said: it is done. The last time. The way is known, the sea is calm."),
    ('وبعد أسبوع، طلع علينا القراصنة.', "And after a week, the pirates came upon us."),
    ('تلات سفن، ورجال بالسيوف، وما قدرنا نعمل إشي.', "Three ships, and men with swords, and we could do nothing."),
    ('أخدوا السفينة، وأخدونا كلنا عبيد.', "They took the ship, and took us all as slaves.")),
  P(('باعوني بسوق بمدينة ما بعرف اسمها.', "They sold me in a market in a city whose name I do not know."),
    ('واشتراني تاجر غني، وأخدني لبيته، وسألني: شو بتعرف تعمل؟', "And a rich merchant bought me, took me to his house, and asked me: what can you do?"),
    ('قلت: أنا تاجر. بعرف أبيع وأشتري.', "I said: I am a merchant. I know how to sell and buy."),
    ('قال: وبتعرف ترمي بالقوس؟', "He said: and can you shoot a bow?"),
    ('قلت: لما كنت زغير.', "I said: when I was young."),
    ('قال: منيح. بكرا بتطلع معي.', "He said: good. Tomorrow you come out with me.")),
  P(('وأخدني بالصبح على غابة، على ظهر فيل.', "And in the morning he took me to a forest, on the back of an elephant."),
    ('ووقفني على شجرة عالية، وأعطاني قوس وسهام، وأكل لأيام.', "And he stood me in a tall tree, gave me a bow and arrows, and food for days."),
    ('وقال: الفيلة بتمر من هون. لما تشوف واحد، ارميه.', "And he said: the elephants pass here. When you see one, shoot it."),
    ('ولما يموت، تعال قول لي، وأنا بجي بآخد عاجه.', "And when it dies, come and tell me, and I come and take its ivory."),
    ('وراح، وتركني عالشجرة.', "And he left, and left me in the tree."),
    ('وقلت: من قبطان لعبد، ومن عبد لصياد فيلة.', "And I said: from captain to slave, and from slave to elephant hunter."),
    ('هيك الدنيا.', "Such is the world."))]),

 ('The Elephants', 'الفيلة', [
  P(('كل يوم، كانت تمر الفيلة تحت الشجرة.', "Every day, the elephants passed beneath the tree."),
    ('قطعان كبيرة، بطيئة، وما بتشوفني.', "Big herds, slow, and they did not see me."),
    ('وكنت أرمي، وأصيب واحد، وأنزل، وأروح لسيدي.', "And I shot, and hit one, and came down, and went to my master."),
    ('وبيجي وبياخد العاج، وبيدفن الفيل.', "And he would come and take the ivory, and bury the elephant."),
    ('شهرين هيك.', "Two months like that."),
    ('وكنت أحس إني بعمل إشي غلط، بس ما كان عندي خيار.', "And I felt I was doing something wrong, but I had no choice.")),
  P(('وبيوم، الفيلة ما مرت.', "And one day, the elephants did not pass."),
    ('ولا بعده.', "Nor the next."),
    ('وبتالت يوم، سمعت الأرض بتهتز.', "And on the third day, I heard the ground shaking."),
    ('وشفتهم جايين، مش زي كل مرة.', "And I saw them coming, not as every time."),
    ('جايين على الشجرة دغري، كلهم.', "Coming straight for the tree, all of them."),
    ('وقدامهم فيل كبير، أكبر من الكل.', "And at their head a huge elephant, bigger than all."),
    ('وقفوا حوالي الشجرة، ورفعوا خراطيمهم، وتطلعوا فيّ.', "They stood around the tree, raised their trunks, and looked at me."),
    ('وفهمت: عرفوا مين اللي بيقتلهم.', "And I understood: they knew who was killing them.")),
  P(('الفيل الكبير لف خرطومه حول الشجرة.', "The big elephant wound its trunk around the tree."),
    ('وشد.', "And pulled."),
    ('الشجرة صرت، وانحنت، وطلعت من الأرض بجذورها.', "The tree creaked, bent, and came out of the ground by its roots."),
    ('ووقعت أنا معها، على ظهري، والفيلة حوالي.', "And I fell with it, on my back, the elephants around me."),
    ('وقلت: خلص. سابع رحلة، وسابع موت، وهالمرة حقيقي.', "And I said: it is over. The seventh voyage, and the seventh death, and this time real."),
    ('وسكرت عيني.', "And I closed my eyes.")),
  P(('وما داسني.', "And it did not trample me."),
    ('حسيت الخرطوم بيلف حولي، على مهل، وبيرفعني.', "I felt the trunk winding around me, slowly, lifting me."),
    ('وحطني على ظهره.', "And it set me on its back."),
    ('ومشى.', "And it walked."),
    ('والفيلة كلها وراه، ساكتة، بالغابة.', "And all the elephants behind it, silent, through the forest."),
    ('وأنا على ظهره، مش عارف لوين، ومش عارف ليش.', "And I on its back, not knowing where, not knowing why."),
    ('وقال الحمّال: لوين أخدك؟', "And the porter said: where did it take you?"),
    ('قال السندباد: هاد بكرا. الليلة خلصت.', "Sindbad said: that is tomorrow. Tonight is finished."))]),

 ('The Elephant Who Carried Me', 'الفيل اللي شالني', [
  P(('مشى الفيل نص يوم، وأنا على ظهره.', "The elephant walked half a day, with me on its back."),
    ('لحد ما وصلنا على تلة، ووقف، ونزلني بخرطومه على مهل.', "Until we reached a hill, and it stopped, and set me down gently with its trunk."),
    ('وراح، هو والفيلة كلها، وتركوني.', "And it went, it and all the elephants, and left me."),
    ('وقفت، وتطلعت حوالي، وما فهمت.', "I stood, looked around, and did not understand."),
    ('وبعدين فهمت.', "And then I understood.")),
  P(('التلة كلها عاج.', "The hill was all ivory."),
    ('أنياب فيلة، مئات، آلاف، أبيض وأصفر، قديم وجديد.', "Elephant tusks, hundreds, thousands, white and yellow, old and new."),
    ('كانت مقبرة الفيلة.', "It was the elephants' graveyard."),
    ('المكان اللي بيجوا يموتوا فيه من ألف سنة.', "The place they had come to die for a thousand years."),
    ('وفهمت شو قال لي الفيل، بلا كلام.', "And I understood what the elephant had told me, without words."),
    ('قال: بدك عاج؟ هون العاج. خد، وخلينا نعيش.', "It said: you want ivory? Here is ivory. Take it, and let us live."),
    ('وقعدت على التلة، وبكيت.', "And I sat on the hill, and wept.")),
  P(('رجعت لسيدي مشي، يومين.', "I went back to my master on foot, two days."),
    ('ولما شافني، قال: فكرتك مت! الفيلة قلعت الشجرة!', "And when he saw me, he said: I thought you dead! The elephants pulled up the tree!"),
    ('قلت: تعال معي.', "I said: come with me."),
    ('وأخدته للتلة.', "And I took him to the hill."),
    ('ووقف قدام العاج، وما حكى نص ساعة.', "And he stood before the ivory, and did not speak for half an hour."),
    ('وبعدين قال: يا سندباد، هاد كتير.', "And then he said: Sindbad, this is a lot."),
    ('أكتر مما بيجمعه بلدنا بمية سنة.', "More than our country gathers in a hundred years."),
    ('وإنت ما عاد عبد. إنت حر، وإنت شريكي.', "And you are a slave no more. You are free, and you are my partner."),
    ('وما حدا بيقتل فيل بعد اليوم.', "And no one kills an elephant from this day.")),
  P(('وحملنا العاج على فيلة، مش زي قبل، بس اللي تحتاجه القافلة.', "And we carried the ivory on elephants, not as before, only what the caravan needed."),
    ('وباعه، وأعطاني نصه، وسفينة، وودعني.', "And he sold it, gave me half, and a ship, and bade me farewell."),
    ('وأبحرت، وما صار إشي.', "And I sailed, and nothing happened."),
    ('ولا عاصفة، ولا قراصنة، ولا جزيرة.', "No storm, no pirates, no island."),
    ('لأول مرة بحياتي، البحر رجعني عالبيت بسلام.', "For the first time in my life, the sea brought me home in peace."),
    ('وقال الحمّال: ليش؟', "And the porter said: why?"),
    ('قال السندباد: يمكن لأني ما أخدت إلا اللي بحتاجه.', "Sindbad said: perhaps because I took only what I needed."))]),

 ('The Last Return', 'الرجعة الأخيرة', [
  P(('وصلت بغداد بعد سبع وعشرين سنة من أول رحلة.', "I reached Baghdad twenty-seven years after the first voyage."),
    ('ودخلت على الخليفة، وحكيت له عن الفيلة.', "And I went in to the Caliph, and told him about the elephants."),
    ('وقال: يا سندباد، خلص. ما ببعتك لمكان بعد اليوم.', "And he said: Sindbad, enough. I send you nowhere from this day."),
    ('وأمر يكتبوا رحلاتي السبع بماء الذهب، وتنحفظ بخزانته.', "And he ordered my seven voyages written in gold ink, and kept in his treasury."),
    ('عشان اللي بعدنا يعرفوا شو في بالبحر.', "So that those after us know what is in the sea.")),
  P(('ورجعت لبيتي، هالبيت.', "And I came home to my house, this house."),
    ('واشتريت الحديقة، والخدم، والمغنيين.', "And I bought the garden, the servants, the singers."),
    ('وكل يوم بقعد هون، وبسمع الموسيقى، وبآكل.', "And every day I sit here, listen to the music, and eat."),
    ('وكل ليلة بحلم بالبحر.', "And every night I dream of the sea."),
    ('بس ما برجع له.', "But I do not go back to it."),
    ('لأني كبرت، ولأني تعلمت.', "Because I have grown old, and because I have learned."),
    ('والحمّال سأل: تعلمت شو؟', "And the porter asked: learned what?")),
  P(('قال السندباد: تعلمت إشي.', "Sindbad said: I learned something."),
    ('اللي بيطلع بالسفينة، بيرجع إشي تاني.', "Whoever goes out on a ship comes back as something else."),
    ('وإن اللوح بيجي، بس لازم تمسكه.', "And that the plank comes, but you must grab it."),
    ('وإن الجوع بيغير الإنسان، والخوف كمان، والذهب أكتر.', "And that hunger changes a person, and fear too, and gold most of all."),
    ('وإن الغريب بيحب كل بلد، وبيشتاق لبلد واحدة.', "And that the stranger loves every country, and longs for one."),
    ('وإن اللي بياخد أكتر من حاجته، البحر بياخد منه.', "And that whoever takes more than he needs, the sea takes from him."),
    ('هاد اللي تعلمته، بسبع وعشرين سنة.', "That is what I learned, in twenty-seven years."),
    ('وسبع رحلات، وسبع مرات موت.', "And seven voyages, and seven deaths.")),
  P(('وبعدين تطلع بالحمّال.', "And then he looked at the porter."),
    ('وقال: وإنت، يا سندباد الحمّال، شو تعلمت؟', "And he said: and you, Sindbad the porter, what have you learned?"),
    ('قال الحمّال: تعلمت إني ما بدي أكون إنت.', "The porter said: I learned that I do not want to be you."),
    ('بس بدي أكون صاحبك.', "But I want to be your friend."),
    ('وضحك السندباد البحري، وقام، وعانقه.', "And Sindbad the sailor laughed, and rose, and embraced him."),
    ('وقال: من اليوم، إنت بتاكل على سفرتي، وما بتحمل حمل لحدا.', "And he said: from today, you eat at my table, and carry no load for anyone."),
    ('وأعطاه مية دينار، آخر مرة.', "And he gave him a hundred dinars, for the last time."),
    ('وعاشوا الاتنين ببغداد، صاحبين.', "And the two lived in Baghdad, friends."),
    ('لحد ما إجا اللي ما بيرحم حدا.', "Until there came what spares no one."),
    ('وهاي آخر حكاية السندباد.', "And that is the end of the tale of Sindbad."))]),
]

if __name__ == '__main__':
    emit_book(BOOK_ID, BOOK_TITLE, 'intermediate', CHAPTERS, shelf=11,
              meta={'work': 'The Seven Voyages of Sindbad, from ألف ليلة وليلة',
                    'author': 'traditional', 'year': 'medieval',
                    'status': 'public domain — medieval, anonymous'})
