#!/usr/bin/env python3
"""مغامرات توم سوير — Tom Sawyer, retold in spoken Palestinian, graded to intermediate.

Mark Twain died in 1910; the novel (1876) is public domain. This is a retelling from the plot, not
a translation of any edition.

WHY IT FINISHES THE INTERMEDIATE SHELF. Everything else at this level is a journey or a fable —
someone travelling, or animals arguing a moral. This is the only book here about ordinary life:
school, a fence, a funeral, being in trouble, liking someone and handling it badly. That vocabulary
is the vocabulary a learner actually needs, and it comes with a plot strong enough to pull thirty
chapters (the graveyard, the trial, the cave).

ON THE VILLAIN'S NAME. Twain calls him by a slur for Native Americans, used forty times in the
original. This retelling calls him جو — nothing else about the character changes. Reproducing a
racial epithet into a language and an audience it was never part of would be carrying an injury
forward for no reason. Tom's friend Joe Harper is called هاربر throughout so the two never collide.

LEVEL. Near the intermediate story baseline (32.5 characters a sentence), like Sindbad, Kalila and
Treasure Island. Third person, past tense, dialogue doing the heavy lifting.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_tomsawyer.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, emit_book

BOOK_ID = 'tomsawyer'
BOOK_TITLE = {'en': 'The Adventures of Tom Sawyer', 'ar': 'مغامرات توم سوير'}

# (english title, arabic title, [paragraph, ...])
CHAPTERS = [
 ('Tom and Aunt Polly', 'توم والخالة بولي', [
  P(('الخالة بولي صرخت: توم! وين إنت؟', 'Aunt Polly shouted: Tom! Where are you?'),
    ('ما إجا صوت من حدا.', 'No sound came from anyone.')),
  P(('لقيته بالخزانة وتمه مليان مربى.',
     'She found him in the cupboard with his mouth full of jam.'),
    ('مسكته من قميصه وقالت: هلق شفتك.',
     'She grabbed him by his shirt and said: now I have caught you.')),
  P(('توم صرخ: خالتي، شوفي ورايكي!',
     'Tom shouted: Auntie, look behind you!'),
    ('لفت، وهو نط عالسور وهرب.',
     'She turned, and he jumped the fence and fled.'),
    ('وقفت لحالها وضحكت رغم عنها.',
     'She stood alone and laughed in spite of herself.'))]),

 ('The Fence', 'السور', [
  P(('يوم السبت، عاقبته يدهن السور.',
     'On Saturday, she punished him by making him paint the fence.'),
    ('السور كان طويل والشمس حارقة.',
     'The fence was long and the sun burning.')),
  P(('مرق صاحبه بن وصار يضحك عليه.',
     'His friend Ben passed and began laughing at him.'),
    ('توم ما رد، وضل يدهن بهدوء وتركيز.',
     'Tom did not answer, and kept painting calmly and carefully.')),
  P(('قال بن: خليني أجرب شوي.', 'Ben said: let me try a little.'),
    ('قال توم: لأ، هاي شغلة بدها مهارة.',
     'Tom said: no, this is work that needs skill.')),
  P(('بن أعطاه تفاحة عشان يتركه يدهن.',
     'Ben gave him an apple so he would let him paint.'),
    ('وبعده إجوا ولاد تانيين ودفعوا كمان.',
     'And after him other boys came and paid as well.'),
    ('السور خلص، وتوم صار عنده كنز صغير.',
     'The fence was finished, and Tom had a small treasure.'))]),

 ('The New Girl', 'البنت الجديدة', [
  P(('وهو راجع، شاف بنت بشعر أصفر.',
     'On his way back, he saw a girl with yellow hair.'),
    ('كانت واقفة بحديقة بيت جديد.',
     'She was standing in the garden of a new house.')),
  P(('وقف قدامها وصار يعمل حركات غبية.',
     'He stood in front of her and started doing silly tricks.'),
    ('كان يمشي على إيديه ويقلب.',
     'He walked on his hands and turned over.')),
  P(('هي ما حكت ولا كلمة.', 'She did not say a single word.'),
    ('قبل ما تدخل، رمت له وردة.',
     'Before she went in, she threw him a flower.'),
    ('توم أخذ الوردة وحطها بقميصه.',
     'Tom took the flower and put it in his shirt.'))]),

 ('Sunday School', 'مدرسة الأحد', [
  P(('بمدرسة الأحد، كانوا يعطوا تذاكر للحفظ.',
     'At Sunday school, they gave tickets for memorising.'),
    ('اللي بيجمع تذاكر كتيرة بياخد كتاب هدية.',
     'Whoever collects many tickets gets a book as a gift.')),
  P(('توم ما حفظ ولا آية بحياته.',
     'Tom had never memorised a single verse in his life.'),
    ('بس كان عنده أشياء بيبادل فيها.',
     'But he had things he could trade with.')),
  P(('بادل ولاد بتذاكرهم وجمع العدد كله.',
     'He traded with boys for their tickets and collected the whole number.'),
    ('طلع قدام الناس وأخذ الكتاب.',
     'He went up before the people and took the book.')),
  P(('القاضي سأله سؤال بسيط عن الكتاب.',
     'The judge asked him a simple question about the book.'),
    ('توم ما عرف الجواب وسكت.',
     'Tom did not know the answer and was silent.'),
    ('الحفلة خلصت بسرعة بعدها.', 'The ceremony ended quickly after that.'))]),

 ('The Beetle and the Dog', 'الخنفسة والكلب', [
  P(('بالكنيسة، الخطبة كانت طويلة ومملة.',
     'At church, the sermon was long and dull.'),
    ('توم فتح علبة صغيرة معه.',
     'Tom opened a small box he had with him.')),
  P(('طلعت منها خنفسة ووقعت عالأرض.',
     'A beetle came out of it and fell on the floor.'),
    ('كلب صغير دخل وشافها.', 'A small dog came in and saw it.')),
  P(('الكلب لعب فيها لحد ما قرصته.',
     'The dog played with it until it bit him.'),
    ('طلع يركض ويصرخ بين الكراسي.',
     'He ran and yelped between the chairs.'),
    ('الناس ما قدروا يوقفوا الضحك.',
     'The people could not stop laughing.'))]),

 ('Huck Finn', 'هَك فِن', [
  P(('يوم الاتنين، توم ما بده يروح عالمدرسة.',
     'On Monday, Tom did not want to go to school.'),
    ('حاول يقنع خالته إنه مريض وما نفع.',
     'He tried to convince his aunt he was ill and it did not work.')),
  P(('بالطريق، لقي هَك فِن.', 'On the way, he met Huck Finn.'),
    ('هَك كان بلا بيت وبلا مدرسة.',
     'Huck had no home and no school.'),
    ('كل ولاد البلد كانوا يحسدوه.',
     'All the boys of the town envied him.')),
  P(('هَك كان شايل قطة ميتة.', 'Huck was carrying a dead cat.'),
    ('قال: هاي بتشفي الثآليل بالمقبرة.',
     'He said: this cures warts, in the graveyard.'),
    ('اتفقوا يلتقوا بالليل هناك.',
     'They agreed to meet there at night.'))]),

 ('Tom and Becky', 'توم وبيكي', [
  P(('بالمدرسة، توم تأخر وقال السبب: كنت مع هَك.',
     'At school, Tom was late and said why: I was with Huck.'),
    ('الأستاذ ضربه وقعّده مع البنات.',
     'The teacher hit him and seated him with the girls.')),
  P(('قعد جنب بيكي وهو مبسوط بالعقاب.',
     'He sat beside Becky, pleased with the punishment.'),
    ('رسم لها بيت صغير على لوح.',
     'He drew her a small house on a slate.')),
  P(('كتب لها: بحبك.', 'He wrote to her: I love you.'),
    ('هي قرت وخبت وجهها وقالت: يا شقي.',
     'She read it and hid her face and said: you rascal.'))]),

 ('At Midnight in the Graveyard', 'بنص الليل بالمقبرة', [
  P(('بالليل، توم وهَك راحوا عالمقبرة.',
     'At night, Tom and Huck went to the graveyard.'),
    ('خبوا حالهم ورا شجرة وهم خايفين.',
     'They hid behind a tree, afraid.')),
  P(('إجوا تلات رجال ومعهم فوانيس.',
     'Three men came carrying lanterns.'),
    ('كانوا الدكتور روبنسون، وماف بوتر، وجو.',
     'They were Doctor Robinson, Muff Potter, and Joe.')),
  P(('صار خلاف بينهم على مصاري.',
     'A quarrel broke out between them over money.'),
    ('جو طعن الدكتور وحط السكينة بإيد ماف.',
     'Joe stabbed the doctor and put the knife in Muff’s hand.'),
    ('ماف كان سكران وما فهم إشي.',
     'Muff was drunk and understood nothing.'))]),

 ('The Oath', 'القسم', [
  P(('الولدين ركضوا وما وقفوا لحد البلد.',
     'The two boys ran and did not stop until the town.'),
    ('كانوا يرجفوا من الخوف.', 'They were shaking with fear.')),
  P(('توم قال: إذا حكينا، جو بيقتلنا.',
     'Tom said: if we speak, Joe will kill us.'),
    ('كتبوا ورقة وحلفوا يسكتوا.',
     'They wrote a paper and swore to keep silent.')),
  P(('دفنوا الورقة تحت شجرة.', 'They buried the paper under a tree.'),
    ('من هديك الليلة، ما عاد توم ينام منيح.',
     'From that night, Tom no longer slept well.'))]),

 ('Muff Potter in Prison', 'ماف بوتر بالسجن', [
  P(('الصبح، البلد كلها عرفت بالجريمة.',
     'In the morning, the whole town knew about the crime.'),
    ('جو حكى قدام الناس إن ماف هو القاتل.',
     'Joe told the people that Muff was the killer.')),
  P(('ماف نفسه ما كان متأكد.', 'Muff himself was not sure.'),
    ('قال: بلكي عملتها وأنا سكران.',
     'He said: maybe I did it while I was drunk.')),
  P(('توم وهَك صاروا يجيبوا له أكل عالشباك.',
     'Tom and Huck began bringing him food at the window.'),
    ('ماف كان يشكرهم وهو ما بيعرف ليش.',
     'Muff would thank them without knowing why.'),
    ('وهاي كانت أصعب من السكوت.',
     'And that was harder than the silence.'))]),

 ('Becky Turns Away', 'بيكي بتزعل', [
  P(('توم حكى لبيكي عن بنت كان يحبها قبلها.',
     'Tom told Becky about a girl he had liked before her.'),
    ('بيكي زعلت وما عادت تحكي معه.',
     'Becky was upset and stopped speaking to him.')),
  P(('حاول يصالحها بكل طريقة.',
     'He tried to make up with her in every way.'),
    ('جاب لها هدية ورمتها عالأرض.',
     'He brought her a gift and she threw it on the ground.')),
  P(('توم قعد لحاله ورا المدرسة.',
     'Tom sat alone behind the school.'),
    ('قال: بدي أروح بعيد وما أرجع.',
     'He said: I want to go far away and not come back.'))]),

 ('The Pirates Set Out', 'القراصنة بيطلعوا', [
  P(('توم لقى هاربر كمان زعلان من بيته.',
     'Tom found Harper also unhappy at home.'),
    ('وهَك دايماً جاهز لأي إشي.',
     'And Huck was always ready for anything.')),
  P(('اتفقوا يصيروا قراصنة عالنهر.',
     'They agreed to become pirates on the river.'),
    ('التقوا بالليل وأخذوا طوافة صغيرة.',
     'They met at night and took a small raft.')),
  P(('راحوا على جزيرة بنص النهر.',
     'They went to an island in the middle of the river.'),
    ('ولا واحد فيهم قال لأهله.',
     'Not one of them told his family.'))]),

 ('Life on the Island', 'الحياة عالجزيرة', [
  P(('أشعلوا نار وشووا سمك عالحطب.',
     'They lit a fire and grilled fish on the wood.'),
    ('الأكل كان أطيب إشي أكلوه بحياتهم.',
     'The food was the best thing they had eaten in their lives.')),
  P(('سبحوا ولعبوا وناموا تحت الشجر.',
     'They swam and played and slept under the trees.'),
    ('ما في حدا يقول لهم روحوا ناموا.',
     'Nobody told them to go to bed.')),
  P(('بس بالليلة التانية، صار في سكوت.',
     'But on the second night, a silence fell.'),
    ('كل واحد فيهم كان يفكر ببيته.',
     'Each of them was thinking about his home.'))]),

 ('The Sound on the River', 'الصوت عالنهر', [
  P(('الصبح، سمعوا صوت مدفع من النهر.',
     'In the morning, they heard a cannon from the river.'),
    ('في مركب بتلف وبترمي بالمي.',
     'A boat was going round and firing into the water.')),
  P(('هَك قال: هيك بيعملوا لما حدا يغرق.',
     'Huck said: that is what they do when someone drowns.'),
    ('وقتها فهموا: البلد حاسبتهم موتى.',
     'Then they understood: the town thought them dead.')),
  P(('الولاد فرحوا بالأول.', 'The boys were pleased at first.'),
    ('وبعدين توم تذكر وجه خالته.',
     'And then Tom remembered his aunt’s face.'))]),

 ('Tom Goes Home in the Dark', 'توم بيرجع بالعتمة', [
  P(('بالليل، توم عبر النهر لحاله.',
     'At night, Tom crossed the river alone.'),
    ('مشي عالبلد وهو مبلول وساكت.',
     'He walked to the town, wet and silent.')),
  P(('فات البيت من الشباك وخبى حاله.',
     'He entered the house by the window and hid himself.'),
    ('خالته كانت قاعدة مع أم هاربر.',
     'His aunt was sitting with Harper’s mother.')),
  P(('كانوا يبكوا ويحكوا عن الولاد.',
     'They were weeping and talking about the boys.'),
    ('قالت خالته: كان شقي، بس ما كان ابن حرام.',
     'His aunt said: he was a rascal, but he was not a bad boy.'),
    ('توم كاد يطلع، بس ضل ساكت.',
     'Tom almost came out, but he stayed silent.'))]),

 ('The Storm', 'العاصفة', [
  P(('رجع عالجزيرة قبل الفجر.', 'He returned to the island before dawn.'),
    ('ما حكى لهم وين كان.', 'He did not tell them where he had been.')),
  P(('بالليل، إجت عاصفة قوية كتير.',
     'At night, a very strong storm came.'),
    ('الريح قلعت شجرة كبيرة جنبهم.',
     'The wind tore up a big tree beside them.')),
  P(('قعدوا تحت قماش وهم يرجفوا.',
     'They sat under a cloth, shivering.'),
    ('الصبح، كل إشي كان مبلول والشمس طالعة.',
     'In the morning, everything was wet and the sun was up.'))]),

 ('Their Own Funeral', 'جنازتهم', [
  P(('يوم الأحد، البلد كلها كانت بالكنيسة.',
     'On Sunday, the whole town was at church.'),
    ('كانوا عاملين جنازة للولاد التلاتة.',
     'They were holding a funeral for the three boys.')),
  P(('الناس صاروا يتذكروا أشياء حلوة عنهم.',
     'People began remembering good things about them.'),
    ('اللي كانوا يشتكوا منهم صاروا يبكوا.',
     'Those who used to complain about them were weeping.')),
  P(('فجأة، انفتح الباب.', 'Suddenly, the door opened.'),
    ('التلاتة دخلوا وهم عايشين.',
     'The three came in alive.'),
    ('صار صراخ وضحك وبكا بنفس الوقت.',
     'There was shouting and laughing and crying at once.'))]),

 ('The Torn Book', 'الكتاب المقطوع', [
  P(('بيوم، بيكي فتحت كتاب الأستاذ بالسر.',
     'One day, Becky secretly opened the teacher’s book.'),
    ('توم فاجأها، وهي خافت وقطعت صفحة.',
     'Tom startled her, and she was frightened and tore a page.')),
  P(('بعد شوي، الأستاذ سأل: مين قطع الكتاب؟',
     'A little later, the teacher asked: who tore the book?'),
    ('صار يسأل واحد واحد.', 'He began asking one by one.')),
  P(('لما وصل لبيكي، وقف توم.',
     'When he reached Becky, Tom stood up.'),
    ('قال: أنا اللي عملتها.', 'He said: I am the one who did it.'),
    ('أخذ الضرب وهو بيتطلع فيها.',
     'He took the beating while looking at her.'))]),

 ('Examination Day', 'يوم الامتحان', [
  P(('آخر يوم بالسنة، إجا كل الأهالي.',
     'On the last day of the year, all the parents came.'),
    ('الولاد وقفوا يقروا وهم متوترين.',
     'The children stood reading, nervous.')),
  P(('الأستاذ كان قاسي معهم طول السنة.',
     'The teacher had been harsh with them all year.'),
    ('كان عنده شعر مستعار على راسه.',
     'He had a wig on his head.')),
  P(('من فوق، نزلت قطة معلقة بحبل.',
     'From above, a cat came down hanging on a rope.'),
    ('شالت الشعر المستعار وطلعت فيه.',
     'It lifted off the wig and rose with it.'),
    ('القاعة انفجرت ضحك والصيف بلش.',
     'The hall burst out laughing and the summer began.'))]),

 ('The Trial', 'المحاكمة', [
  P(('بعد شهور، إجت محاكمة ماف بوتر.',
     'After months, Muff Potter’s trial came.'),
    ('الكل كان متأكد إنه القاتل.',
     'Everyone was certain he was the killer.')),
  P(('توم ما نام تلات ليالي.', 'Tom did not sleep for three nights.'),
    ('بالآخر، راح عالمحامي وحكى له كل إشي.',
     'In the end, he went to the lawyer and told him everything.')),
  P(('بالمحكمة، ناداه المحامي وسأله.',
     'At the court, the lawyer called him and questioned him.'),
    ('توم حكى شو شاف بالمقبرة.',
     'Tom told what he had seen in the graveyard.'),
    ('جو نط من الشباك وهرب.',
     'Joe jumped from the window and fled.'))]),

 ('After the Trial', 'بعد المحاكمة', [
  P(('ماف طلع من السجن وصار الكل يحبه.',
     'Muff came out of prison and everyone loved him.'),
    ('توم صار بطل البلد بالنهار.',
     'Tom became the town’s hero by day.')),
  P(('بس بالليل كان يحلم بجو.',
     'But at night he dreamed of Joe.'),
    ('كل صوت بالبيت كان يخوفه.',
     'Every sound in the house frightened him.')),
  P(('هَك كمان صار ينام وعينه مفتوحة.',
     'Huck too began sleeping with one eye open.'),
    ('جو كان لسا برا وما حدا لقاه.',
     'Joe was still out there and nobody had found him.'))]),

 ('The Haunted House', 'البيت المسكون', [
  P(('بالصيف، توم وهَك قرروا يدوروا على كنز.',
     'In the summer, Tom and Huck decided to hunt for treasure.'),
    ('راحوا على بيت قديم مهجور برا البلد.',
     'They went to an old abandoned house outside the town.')),
  P(('طلعوا عالطابق الفوقاني وقعدوا.',
     'They climbed to the upper floor and sat.'),
    ('سمعوا صوت باب بيتفتح تحتهم.',
     'They heard a door opening below them.')),
  P(('اتنين رجال دخلوا وقعدوا يحكوا.',
     'Two men came in and sat talking.'),
    ('واحد منهم كان جو، بلبس تاني.',
     'One of them was Joe, in different clothes.'),
    ('الولدين ما قدروا يتحركوا ولا يتنفسوا.',
     'The two boys could not move or breathe.'))]),

 ('The Box of Gold', 'صندوق الذهب', [
  P(('جو ورفيقه صاروا يحفروا بالأرض.',
     'Joe and his companion began digging in the ground.'),
    ('طلعوا صندوق قديم مليان ذهب.',
     'They brought up an old box full of gold.')),
  P(('جو قال: هاد كتير، لازم نخبيه منيح.',
     'Joe said: this is a lot, we must hide it well.'),
    ('قال رفيقه: نخبيه هون.', 'His companion said: let us hide it here.')),
  P(('جو قال: لأ، بنخبيه بمحل رقم اتنين.',
     'Joe said: no, we hide it at place number two.'),
    ('أخذوا الصندوق وطلعوا.', 'They took the box and left.'),
    ('توم وهَك سمعوا الرقم وحفظوه.',
     'Tom and Huck heard the number and memorised it.'))]),

 ('Number Two', 'رقم اتنين', [
  P(('صاروا يدوروا شو يعني رقم اتنين.',
     'They began working out what number two meant.'),
    ('طلع إنها أوضة بنزل بالبلد.',
     'It turned out to be a room in an inn in the town.')),
  P(('هَك قرر يراقب النزل كل ليلة.',
     'Huck decided to watch the inn every night.'),
    ('كان ينام بين البراميل ويستنى.',
     'He would sleep among the barrels and wait.')),
  P(('بعد أيام، شاف جو طالع بالليل.',
     'After days, he saw Joe going out at night.'),
    ('مشي وراه بهدوء بين البيوت.',
     'He followed him quietly between the houses.'))]),

 ('Huck Saves the Widow', 'هَك بينقذ الأرملة', [
  P(('جو ورفيقه وقفوا عند بيت الأرملة دوغلاس.',
     'Joe and his companion stopped at the Widow Douglas’s house.'),
    ('جو حكى عن إشي عمله زوجها معه زمان.',
     'Joe spoke of something her husband had done to him long ago.')),
  P(('هَك سمع ما يكفي وركض.', 'Huck heard enough and ran.'),
    ('دق باب أقرب بيت وصرخ.',
     'He knocked at the nearest door and shouted.')),
  P(('الرجال طلعوا بسلاحهم عالتلة.',
     'The men went up the hill with their weapons.'),
    ('جو هرب بالعتمة كمان مرة.',
     'Joe fled in the dark once again.'),
    ('هَك ما بده حدا يعرف إنه هو.',
     'Huck did not want anyone to know it was him.'))]),

 ('The Picnic', 'الرحلة', [
  P(('بنفس اليوم، كان في رحلة للولاد.',
     'On the same day, there was an outing for the children.'),
    ('راحوا بمركب عالضفة التانية.',
     'They went by boat to the other bank.')),
  P(('في مغارة كبيرة هناك بجوف الجبل.',
     'There was a big cave there inside the hill.'),
    ('دخلوا كلهم وهم يحملوا شمع.',
     'They all went in carrying candles.')),
  P(('توم وبيكي ابتعدوا عن الباقيين.',
     'Tom and Becky wandered from the others.'),
    ('كانوا يتفرجوا عالحجار الغريبة.',
     'They were looking at the strange rocks.'),
    ('وبعد شوي، ما عادوا يعرفوا الطريق.',
     'And a little later, they no longer knew the way.'))]),

 ('Lost in the Cave', 'ضايعين بالمغارة', [
  P(('صرخوا كتير وما حدا رد عليهم.',
     'They shouted a lot and nobody answered them.'),
    ('الشمع كان يخلص شوي شوي.',
     'The candles were running out little by little.')),
  P(('بيكي بكت وقعدت عالأرض.',
     'Becky wept and sat on the ground.'),
    ('توم قال لها: أنا معك، ما تخافي.',
     'Tom said to her: I am with you, do not be afraid.')),
  P(('نامت على كتفه وهو ضل صاحي.',
     'She slept on his shoulder and he stayed awake.'),
    ('كان يعد الساعات بالعتمة.',
     'He was counting the hours in the dark.'))]),

 ('A Face in the Dark', 'وجه بالعتمة', [
  P(('توم ترك بيكي ومشي بممر ضيق.',
     'Tom left Becky and walked along a narrow passage.'),
    ('كان يربط خيط ورا ليعرف يرجع.',
     'He tied a thread behind him so he could find his way back.')),
  P(('شاف ضوء شمعة من بعيد وفرح.',
     'He saw candlelight far off and was glad.'),
    ('نادى، وطلع وجه من ورا الحجر.',
     'He called out, and a face came from behind the rock.')),
  P(('كان جو، مخبى بالمغارة من يوم الهروب.',
     'It was Joe, hidden in the cave since the day he fled.'),
    ('توم ما تحرك، وجو ركض بالاتجاه التاني.',
     'Tom did not move, and Joe ran the other way.'),
    ('التنين كانوا خايفين من بعض.',
     'The two of them were afraid of each other.'))]),

 ('Out of the Hill', 'من جوف الجبل', [
  P(('توم كمّل يجرب ممرات تانية.',
     'Tom kept trying other passages.'),
    ('باليوم التالت، شاف نقطة ضوء زغيرة.',
     'On the third day, he saw a small point of light.')),
  P(('كان فتحة عالنهر من جهة بعيدة.',
     'It was an opening onto the river on a far side.'),
    ('رجع لبيكي وسحبها معه.',
     'He went back to Becky and pulled her with him.')),
  P(('طلعوا، ومرق مركب وأخذهم.',
     'They came out, and a boat passed and took them.'),
    ('البلد كلها طلعت تستقبلهم.',
     'The whole town came out to receive them.'))]),

 ('The Treasure', 'الكنز', [
  P(('بعد كم يوم، سكروا باب المغارة بحديد.',
     'A few days later, they closed the cave door with iron.'),
    ('توم سمع وقال: بس جو جوا!',
     'Tom heard and said: but Joe is inside!')),
  P(('فتحوا الباب ولقوه ميت جنبه.',
     'They opened the door and found him dead beside it.'),
    ('دفنوه عند باب المغارة.',
     'They buried him at the mouth of the cave.')),
  P(('توم وهَك رجعوا للمغارة من الفتحة التانية.',
     'Tom and Huck went back to the cave by the other opening.'),
    ('لقوا الصندوق تحت صليب على حجر.',
     'They found the box under a cross on a rock.'),
    ('طلعوه وحملوه وهم ما بيصدقوا.',
     'They brought it up and carried it, hardly believing.')),
  P(('الأرملة دوغلاس أخذت هَك عندها.',
     'The Widow Douglas took Huck in with her.'),
    ('لبسته تياب نظيفة وعلمته يقعد عالطاولة.',
     'She dressed him in clean clothes and taught him to sit at the table.'),
    ('هَك تحمل ثلاث أسابيع وبعدين هرب.',
     'Huck endured three weeks and then ran away.')),
  P(('توم لقاه براميل قديمة وهو مبسوط.',
     'Tom found him among old barrels, content.'),
    ('قال له: ارجع، وبخليك بعصابتي.',
     'He said to him: come back, and I will let you into my gang.'),
    ('هَك فكر شوي وقال: طيب، بجرب كمان مرة.',
     'Huck thought a little and said: all right, I will try once more.'))]),
]

if __name__ == '__main__':
    emit_book(BOOK_ID, BOOK_TITLE, 'intermediate', CHAPTERS, shelf=14,
              meta={'work': 'The Adventures of Tom Sawyer', 'author': 'Mark Twain',
                    'year': '1876', 'status': 'public domain'})
