#!/usr/bin/env python3
"""مغامرات توم سوير — Tom Sawyer, retold in spoken Palestinian, graded to intermediate.

Mark Twain died in 1910; the novel (1876) is public domain. This is a retelling from the plot, not
a translation of any edition.

WHY IT FINISHES THE INTERMEDIATE SHELF. Everything else at this level is a journey or a fable —
someone travelling, or animals arguing a moral. This is the only book here about ordinary life:
school, a fence, a funeral, being in trouble, liking someone and handling it badly. That vocabulary
is the vocabulary a learner actually needs, and it comes with a plot strong enough to pull thirty
chapters (the graveyard, the trial, the cave).

ON THE VILLAIN'S NAME. Twain calls him by a slur for Native Americans, used forty times in the
original. This retelling calls him جو — nothing else about the character changes. Reproducing a
racial epithet into a language and an audience it was never part of would be carrying an injury
forward for no reason. Tom's friend Joe Harper is called هاربر throughout so the two never collide.

LEVEL. Near the intermediate story baseline (32.5 characters a sentence), like Sindbad, Kalila and
Treasure Island. Third person, past tense, dialogue doing the heavy lifting.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_tomsawyer.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, book

BOOK_ID = 'tomsawyer'
BOOK_TITLE = {'en': 'The Adventures of Tom Sawyer', 'ar': 'مغامرات توم سوير'}

# (english title, arabic title, [paragraph, ...])
#
# SECOND EDITION (2026-09-03). Same thirty chapters and titles, written out from seven sentences
# each to real chapters: the fence, the graveyard, the island, the trial, the cave. Injun Joe is
# جو الهندي and Joe Harper is جو هاربر, so the two are never one جو.
CHAPTERS = [
 ('Tom and Aunt Polly', 'توم والخالة بولي', [
  P(('توم! يا توم!', "Tom! Tom!"),
    ('ما حدا رد.', "No one answered."),
    ('الخالة بولي نزلت نظاراتها على أنفها وتطلعت حوالي الأوضة.', "Aunt Polly lowered her glasses down her nose and looked around the room."),
    ('وبعدين رفعتها على راسها وتطلعت من فوقها.', "And then she pushed them up onto her head and looked out from under them."),
    ('ما كانت بتشوف ولد زغير من خلال النظارات. النظارات للزينة.', "She never looked at a small boy through the glasses. The glasses were for show."),
    ('قالت: إذا مسكتك، أنا رح...', "She said: if I catch you, I will..."),
    ('وما خلصت الجملة، لأنها كانت منحنية تحت السرير بالمكنسة.', "And she did not finish the sentence, because she was bent under the bed with the broom.")),
  P(('طلعت من تحت السرير قطة بس.', "Only a cat came out from under the bed."),
    ('راحت الخالة بولي عالباب، ووقفت بالحديقة، وصرخت: يا توم!', "Aunt Polly went to the door, stood in the garden, and shouted: Tom!"),
    ('وسمعت صوت وراها، ولفت، ومسكت ولد من ياقته.', "And she heard a sound behind her, turned, and caught a boy by his collar."),
    ('قالت: هون كنت! بالمخزن! وشو هاد على تمك؟', "She said: here you were! In the pantry! And what is that on your mouth?"),
    ('قال توم: ما بعرف يا خالتي.', "Tom said: I do not know, auntie."),
    ('قالت: أنا بعرف. مربى. قلت لك مية مرة.', "She said: I know. Jam. I told you a hundred times."),
    ('ورفعت العصا.', "And she raised the stick.")),
  P(('قال توم: يا خالتي! شوفي ورايك!', "Tom said: auntie! Look behind you!"),
    ('لفت الخالة بولي، وبنفس اللحظة، توم نط من فوق السور واختفى.', "Aunt Polly turned, and in that same moment, Tom leapt over the fence and vanished."),
    ('وقفت الخالة لحظة، وبعدين ضحكت ضحكة زغيرة.', "The aunt stood a moment, and then gave a small laugh."),
    ('قالت لحالها: هالولد. كل مرة بنفس الحيلة، وكل مرة بتنطلي عليّ.', "She said to herself: this boy. Every time the same trick, and every time it works on me."),
    ('هو ابن أختي الميتة، وما بقدر أضربه. وما بقدر ما أضربه.', "He is my dead sister's son, and I cannot beat him. And I cannot not beat him."),
    ('بكرا السبت، وبخليه يشتغل، وهو بيكره الشغل أكتر من أي إشي.', "Tomorrow is Saturday, and I will make him work, and he hates work more than anything.")),
  P(('توم رجع عالبيت بالمسا متأخر.', "Tom came home in the evening, late."),
    ('كان تعبان من اللعب، وتيابه وسخة، ووجهه فيه خدش.', "He was tired from playing, his clothes dirty, and a scratch on his face."),
    ('أخوه سيد، اللي أصغر منه وأهدى منه، كان قاعد عالطاولة بهدوء.', "His brother Sid, who was younger and quieter, was sitting at the table calmly."),
    ('الخالة بولي سألته: توم، الجو كان حار اليوم، صح؟ ما رحت تسبح؟', "Aunt Polly asked him: Tom, it was hot today, right? You did not go swimming?"),
    ('قال توم: لا يا خالتي.', "Tom said: no, auntie."),
    ('لمست قميصه. كان ناشف.', "She touched his shirt. It was dry."),
    ('بس سيد قال: بس الخيط اللي خيطتي فيه ياقته كان أبيض.', "But Sid said: but the thread you sewed his collar with was white."),
    ('وهلق أسود.', "And now it is black."),
    ('توم قام، وقال لسيد وهو طالع: بتدفع ثمنها يا سيد.', "Tom got up, and said to Sid as he went out: you will pay for this, Sid."))]),

 ('The Fence', 'السور', [
  P(('إجا السبت، والدنيا مشمسة، وكل الأولاد برا بيلعبوا.', "Saturday came, the world was sunny, and all the boys were outside playing."),
    ('وتوم واقف قدام سور طويل، بإيده فرشاية ودلو دهان أبيض.', "And Tom stood in front of a long fence, with a brush and a bucket of white paint in his hand."),
    ('السور طوله تلاتين متر، وعالي، وكله لازم يندهن.', "The fence was thirty metres long, and high, and all of it had to be painted."),
    ('دهن خط، وتطلع عاللي ضل، وقعد على الأرض.', "He painted one stroke, looked at what remained, and sat down on the ground."),
    ('الحياة صارت بلا معنى.', "Life had become meaningless.")),
  P(('فكر يدفع لولد يدهن بداله، بس ما معه غير حجر وخيط وحبة زجاج.', "He thought of paying a boy to paint instead of him, but he had nothing but a stone, a string and a marble."),
    ('وبهاللحظة، إجت له فكرة. فكرة عظيمة.', "And in that moment, an idea came to him. A great idea."),
    ('أخد الفرشاية، ورجع يدهن، وهو هادي وسعيد.', "He took the brush, and went back to painting, calm and happy."),
    ('وبعد شوي، مر بن روجرز، وبإيده تفاحة، وبيقلد سفينة.', "And a little later, Ben Rogers passed by, an apple in his hand, imitating a steamboat."),
    ('قال بن: يا توم، شو، مسكوك؟ لازم تشتغل؟', "Ben said: hey Tom, what, they caught you? You have to work?"),
    ('توم ما رد. ضل يدهن، ويبعد شوي، ويتطلع عالسور زي الفنان.', "Tom did not answer. He kept painting, stepping back a little, looking at the fence like an artist.")),
  P(('قال توم: شغل؟ هاد مش شغل. هاد دهان سور.', "Tom said: work? This is not work. This is painting a fence."),
    ('وقال: كم ولد بتفكر بيقدر يدهن سور؟ واحد بالألف؟', "And he said: how many boys do you think can paint a fence? One in a thousand?"),
    ('بن وقف، وتطلع عالسور، وبطل ياكل التفاحة.', "Ben stopped, looked at the fence, and stopped eating the apple."),
    ('قال: يا توم، خليني أدهن شوي.', "He said: Tom, let me paint a little."),
    ('قال توم: لا. الخالة بولي بتهتم كتير بهالسور. ما بيقدر أي حدا يدهنه.', "Tom said: no. Aunt Polly cares a lot about this fence. Not just anyone can paint it."),
    ('قال بن: بعطيك التفاحة.', "Ben said: I give you the apple."),
    ('فكر توم، وقال: طيب. بس انتبه.', "Tom thought, and said: fine. But be careful.")),
  P(('وقعد توم بالظل، ياكل التفاحة، وبن بيدهن بالشمس، وهو مبسوط.', "And Tom sat in the shade, eating the apple, while Ben painted in the sun, happy."),
    ('وبعد بن إجا بيلي، ودفع طيارة ورق.', "And after Ben came Billy, and paid a kite."),
    ('وبعد بيلي إجا جوني، ودفع فار ميت بخيط.', "And after Billy came Johnny, and paid a dead rat on a string."),
    ('ومع المسا، السور كان مدهون تلات مرات، وتوم غني.', "And by evening, the fence had been painted three times, and Tom was rich."),
    ('اتناعشر حبة زجاج، ومفتاح، وقطعة طبشور، وقطة بعين وحدة.', "Twelve marbles, a key, a piece of chalk, and a cat with one eye."),
    ('وتعلم توم قانون كبير عن الناس.', "And Tom learned a big law about people."),
    ('عشان تخلي الواحد يشتهي إشي، خليه صعب.', "To make someone want a thing, make it hard to get."))]),

 ('The New Girl', 'البنت الجديدة', [
  P(('راح توم للخالة بولي وقال: خلصت السور.', "Tom went to Aunt Polly and said: I finished the fence."),
    ('ما صدقت، وطلعت تشوف، وشافت السور أبيض زي التلج.', "She did not believe him, went out to see, and saw the fence white as snow."),
    ('قالت: توم، إنت بتقدر تشتغل لما بدك. بس نادراً ما بدك.', "She said: Tom, you can work when you want to. But you rarely want to."),
    ('وأعطته تفاحة، ودرس عن قيمة الشغل.', "And she gave him an apple, and a lesson on the value of work."),
    ('توم أخد التفاحة، وسرق كعكة وهي بتحكي، وطلع.', "Tom took the apple, stole a cake while she talked, and went out.")),
  P(('مشى بالشارع، ومر قدام بيت القاضي تاتشر.', "He walked down the street, and passed by Judge Thatcher's house."),
    ('وبالحديقة، شاف بنت.', "And in the garden, he saw a girl."),
    ('بنت جديدة، ما شافها قبل، شعرها أصفر ومجدول، وفستانها أبيض.', "A new girl, whom he had not seen before, her hair yellow and braided, her dress white."),
    ('وتوم، اللي كان بيحب بنت اسمها آمي من شهور، نسي آمي بلحظة.', "And Tom, who had loved a girl named Amy for months, forgot Amy in a moment."),
    ('وقف عالسور، وبلش يعمل حركات.', "He stood by the fence, and began doing tricks."),
    ('وقف على إيديه، ومشى عالسور، ورمى حاله عالأرض.', "He stood on his hands, walked along the fence, threw himself on the ground."),
    ('والبنت ما تطلعت فيه.', "And the girl did not look at him.")),
  P(('وبعدين، وهي داخلة عالبيت، وقفت لحظة.', "And then, as she went into the house, she stopped a moment."),
    ('ورمت وردة من فوق السور، وفاتت.', "And she threw a flower over the fence, and went in."),
    ('توم ركض للوردة، ووقف جنبها، وعمل حاله بيدور على إشي.', "Tom ran to the flower, stood beside it, and pretended to be looking for something."),
    ('وبعدين رفعها بأصابع إجره، وحطها بجيبه، وراح.', "And then he picked it up with his toes, put it in his pocket, and left."),
    ('ورجع بالمسا، ووقف قدام البيت لحد ما إجا الليل.', "And he came back in the evening, and stood in front of the house until night came."),
    ('وبعدين تمدد تحت الشباك، وتخيل إنه مات، وهي بتبكي عليه.', "And then he lay down under the window, and imagined he had died, and she was crying over him.")),
  P(('وفجأة انفتح الشباك، وطلع منه دلو مي.', "And suddenly the window opened, and a bucket of water came out of it."),
    ('وقع على توم كله.', "It fell on all of Tom."),
    ('قام، ونفض حاله، وركض عالبيت وهو مبلول.', "He got up, shook himself, and ran home soaked."),
    ('وبالبيت، سيد قال: توم، ليش مبلول؟', "And at home, Sid said: Tom, why are you wet?"),
    ('توم ما رد. بس بالليل، رمى على سيد حجارة زغيرة وهو نايم.', "Tom did not answer. But at night, he threw small stones at Sid while he slept."),
    ('وحس إنه رد له الخيط الأسود.', "And he felt he had paid him back for the black thread."))]),

 ('Sunday School', 'مدرسة الأحد', [
  P(('يوم الأحد، الخالة بولي لبست توم أحسن تيابه.', "On Sunday, Aunt Polly dressed Tom in his best clothes."),
    ('بدلة ضيقة، وجزمة بتوجع، وياقة بتخنق.', "A tight suit, shoes that hurt, and a collar that choked."),
    ('وقالت: روح على مدرسة الأحد، واتعلم آيات.', "And she said: go to Sunday school, and learn verses."),
    ('بمدرسة الأحد، كل ولد بيحفظ آيتين من الكتاب المقدس.', "At Sunday school, every child memorised two verses from the Bible."),
    ('وبياخد تذكرة زرقا.', "And got a blue ticket."),
    ('وعشر تذاكر زرقا بتساوي وحدة حمرا.', "And ten blue tickets equalled a red one."),
    ('وعشر حمرا بتساوي وحدة صفرا.', "And ten red equalled a yellow."),
    ('وعشر صفرا، بيعطوك كتاب مقدس، قدام الكل.', "And for ten yellow, they gave you a Bible, in front of everyone.")),
  P(('توم ما كان حافظ ولا آية.', "Tom had not memorised a single verse."),
    ('بس كان معه اتناعشر حبة زجاج، ومفتاح، وقطة بعين وحدة.', "But he had twelve marbles, a key, and a cat with one eye."),
    ('وقف عالباب، وبلش يشتري تذاكر من الأولاد.', "He stood at the door, and began buying tickets from the boys."),
    ('تذكرة زرقا بحبة زجاج. حمرا بالمفتاح. وصفرا بالقطة.', "A blue ticket for a marble. A red for the key. And a yellow for the cat."),
    ('ولما فات، كان معه عشر تذاكر صفرا.', "And when he went in, he had ten yellow tickets."),
    ('ما حدا بالمدرسة كلها كان معه هالقد.', "No one in the whole school had that many.")),
  P(('وهاليوم بالذات، كان في زائر مهم: القاضي تاتشر.', "And on that very day, there was an important visitor: Judge Thatcher."),
    ('ومعه مرته، وبنته. البنت بالشعر الأصفر.', "And with him his wife, and his daughter. The girl with the yellow hair."),
    ('المعلم قال: مين عنده عشر تذاكر صفرا؟', "The teacher said: who has ten yellow tickets?"),
    ('توم وقف، ومشى لقدام، وأعطى التذاكر.', "Tom stood up, walked forward, and handed over the tickets."),
    ('المعلم ما صدق.', "The teacher could not believe it."),
    ('وكل الأولاد اللي باعوه تذاكرهم فهموا، وعضوا شفافهم.', "And all the boys who had sold him their tickets understood, and bit their lips."),
    ('والقاضي حط إيده على راس توم، وقال: ولد ممتاز.', "And the judge put his hand on Tom's head, and said: an excellent boy."),
    ('وبيكي، بنت القاضي، تطلعت فيه.', "And Becky, the judge's daughter, looked at him.")),
  P(('قال القاضي: يا ولد، أكيد بتعرف أسماء التلاميذ الاتناعشر.', "The judge said: boy, surely you know the names of the twelve disciples."),
    ('قول لنا اسمين منهم.', "Tell us two of them."),
    ('توم احمر. وصار يفكر. وما إجا على باله ولا اسم.', "Tom went red. And began to think. And not one name came to his mind."),
    ('قال المعلم: يلا يا توم. أول اتنين.', "The teacher said: come on, Tom. The first two."),
    ('قال توم: داود... وجالوت!', "Tom said: David... and Goliath!"),
    ('وهون بنسكر الستارة على هالمشهد، رحمة بتوم.', "And here we draw the curtain on this scene, out of mercy for Tom."))]),

 ('The Beetle and the Dog', 'الخنفسة والكلب', [
  P(('بعد مدرسة الأحد، في الكنيسة، والكنيسة أطول من المدرسة.', "After Sunday school, there is church, and church is longer than school."),
    ('القس وقف، وبلش يخطب، وصوته بيطلع وبينزل زي الموج.', "The preacher stood, and began his sermon, his voice rising and falling like waves."),
    ('توم عد الصفحات، وعد الناس، وعد الذباب عالشباك.', "Tom counted the pages, counted the people, counted the flies on the window."),
    ('وبعدين تذكر إشي بجيبه.', "And then he remembered something in his pocket."),
    ('خنفسة كبيرة، سودا، بفكين زي الكماشة، حاطها بعلبة.', "A big beetle, black, with jaws like pincers, that he kept in a box.")),
  P(('فتح العلبة، والخنفسة عضت إصبعه أول إشي.', "He opened the box, and the first thing the beetle did was bite his finger."),
    ('توم رماها، ووقعت بالممر، على ظهرها، وإجريها بالهوا.', "Tom flung it, and it fell in the aisle, on its back, legs in the air."),
    ('والناس اللي حوالي صاروا يتطلعوا عليها بدل القس.', "And the people around began watching it instead of the preacher."),
    ('وبعدين إجا كلب.', "And then came a dog."),
    ('كلب زغير، دخل الكنيسة من الباب المفتوح، وشاف الخنفسة.', "A small dog, that came into the church through the open door, and saw the beetle."),
    ('قرب منها، وشمها، ولف حواليها، وقعد يتفرج عليها.', "It approached it, sniffed it, circled it, and sat down to watch it.")),
  P(('وبعدين قرر ياكلها.', "And then it decided to eat it."),
    ('فتح تمه، والخنفسة عضته بفكها.', "It opened its mouth, and the beetle bit it with its jaws."),
    ('الكلب صرخ، وقفز، وصار يركض بالممر وهو بيعوي.', "The dog yelped, leapt, and began running down the aisle howling."),
    ('والخنفسة معلقة بأنفه.', "With the beetle hanging from its nose."),
    ('ركض يمين، وركض شمال، وقفز على الكراسي، وعلى حضن سيدة.', "It ran right, ran left, jumped on the pews, and into a lady's lap."),
    ('والكنيسة كلها بتضحك، وما حدا بيقدر يوقف.', "And the whole church was laughing, and no one could stop."),
    ('والقس واقف، ووجهه أحمر، وبيكمل الخطبة، وما حدا بيسمعه.', "And the preacher stood, his face red, going on with the sermon, and no one listening.")),
  P(('وبالآخر، صاحب الكلب حمله، ورماه من الشباك.', "And at last, the dog's owner picked it up, and threw it out the window."),
    ('وسمعوه بيعوي وهو بيبعد بالشارع.', "And they heard it howling as it went off down the street."),
    ('توم رجع عالبيت مبسوط.', "Tom went home happy."),
    ('قال بقلبه: الكنيسة مش بطالة، إذا فيها شوي تنويع.', "He said to himself: church is not bad, if there is a little variety in it."),
    ('بس كان زعلان على إشي واحد.', "But he was sad about one thing."),
    ('الكلب أخد الخنفسة معه.', "The dog had taken the beetle with it."))]),

 ('Huck Finn', 'هَك فِن', [
  P(('يوم الاتنين، توم فاق تعبان.', "On Monday, Tom woke up miserable."),
    ('يوم الاتنين يعني مدرسة، والمدرسة يعني أسبوع كامل من السجن.', "Monday meant school, and school meant a whole week of prison."),
    ('فكر يعمل حاله مريض. تفحص حاله: ولا إشي.', "He thought of pretending to be ill. He examined himself: nothing."),
    ('وبعدين لقى سن مخلخل، وقرر يستعمله.', "And then he found a loose tooth, and decided to use it."),
    ('بس تذكر إنه إذا حكى عن السن، الخالة بتقلعه.', "But he remembered that if he mentioned the tooth, his aunt would pull it."),
    ('فبلش يئن، ويقول إن إصبع إجره بيوجعه، وبده يموت.', "So he began groaning, saying his toe hurt, and that he was going to die.")),
  P(('الخالة بولي إجت راكضة، وشافت الإصبع، وقالت: إصبعك؟ وشو فيه؟', "Aunt Polly came running, looked at the toe, and said: your toe? What is wrong with it?"),
    ('وضحكت، وبعدين شافت السن، وقلعته بخيط بلحظة.', "And she laughed, and then saw the tooth, and pulled it with a thread in a moment."),
    ('وبعتته عالمدرسة.', "And sent him to school."),
    ('بس بالطريق، توم اكتشف إن السن المقلوع إله فوايد.', "But on the way, Tom discovered that a pulled tooth had its uses."),
    ('بيقدر يبصق من الفراغ بطريقة جديدة، وكل الأولاد بدهم يجربوا.', "He could spit through the gap in a new way, and all the boys wanted to try.")),
  P(('وقدام المدرسة، شاف هَك فِن.', "And in front of the school, he saw Huck Finn."),
    ('هَك كان ابن سكير القرية، وما إله أم، وما إله بيت.', "Huck was the son of the village drunk, and had no mother, and no house."),
    ('بينام بالبراميل لما الدنيا شتا، وعالدرج لما الدنيا صيف.', "He slept in barrels when it was winter, and on doorsteps when it was summer."),
    ('وتيابه تياب رجال كبار، مقطعة، وبنطلونه ماسكه بحبل.', "And his clothes were grown men's clothes, torn, his trousers held up by a rope."),
    ('كل الأمهات بالقرية كانوا يكرهوه.', "All the mothers in the village hated him."),
    ('لأنه ما بيروح عالمدرسة ولا الكنيسة.', "Because he went neither to school nor to church."),
    ('وكل الأولاد بالقرية كانوا يحسدوه، لنفس السبب.', "And all the boys in the village envied him, for the same reason."),
    ('وممنوع عالكل يلعبوا معه. فتوم كان يلعب معه كل ما قدر.', "And everyone was forbidden to play with him. So Tom played with him whenever he could.")),
  P(('قال توم: شو معك يا هَك؟', "Tom said: what have you got, Huck?"),
    ('قال هَك: قطة ميتة.', "Huck said: a dead cat."),
    ('قال توم: وشو بتعمل بقطة ميتة؟', "Tom said: and what do you do with a dead cat?"),
    ('قال هَك: بتشفي التآليل. بتاخدها عالمقبرة بنص الليل، لما بيدفنوا واحد شرير.', "Huck said: it cures warts. You take it to the graveyard at midnight, when they bury a wicked man."),
    ('وبتيجي الشياطين تاخد الميت.', "And the devils come to take the dead man."),
    ('وبترمي القطة وراهم، والتآليل بتروح معهم.', "And you throw the cat after them, and the warts go with them."),
    ('قال توم: هاي بتشتغل؟', "Tom said: does that work?"),
    ('قال هَك: أكيد. والليلة بيدفنوا واحد. بتيجي؟', "Huck said: certainly. And tonight they bury one. Are you coming?"),
    ('قال توم: بجي.', "Tom said: I am coming."),
    ('واتفقوا: هَك بيموء زي القطة تحت شباك توم بنص الليل.', "And they agreed: Huck would meow like a cat under Tom's window at midnight."))]),

 ('Tom and Becky', 'توم وبيكي', [
  P(('بالمدرسة، توم وصل متأخر، لأنه وقف يحكي مع هَك.', "At school, Tom arrived late, because he had stopped to talk with Huck."),
    ('المعلم قال: توم سوير! ليش متأخر؟', "The teacher said: Tom Sawyer! Why are you late?"),
    ('توم كان رح يكذب، بس شاف إشي.', "Tom was about to lie, but he saw something."),
    ('البنت بالشعر الأصفر، قاعدة.', "The girl with the yellow hair, sitting."),
    ('وجنبها المكان الوحيد الفاضي بصف البنات.', "And beside her the only empty seat on the girls' side."),
    ('فقال: وقفت أحكي مع هَك فِن.', "So he said: I stopped to talk with Huck Finn."),
    ('المعلم ما صدق أذنيه. ضربه بالعصا، وقال: روح اقعد مع البنات!', "The teacher could not believe his ears. He beat him with the stick, and said: go and sit with the girls!"),
    ('وهاد بالضبط اللي كان توم بده ياه.', "And that was exactly what Tom wanted.")),
  P(('قعد جنبها، وهي بعدت عنه، وحطت راسها بالكتاب.', "He sat beside her, and she moved away from him, and put her head in her book."),
    ('توم حط قدامها دراقة.', "Tom put a peach in front of her."),
    ('دفشتها. رجعها. دفشتها، بس أبطأ. رجعها. أخدتها.', "She pushed it away. He put it back. She pushed it away, but slower. He put it back. She took it."),
    ('وبعدين رسم على اللوح بيت، وهي تطلعت.', "And then he drew a house on his slate, and she looked."),
    ('همست: ارسم زلمة.', "She whispered: draw a man."),
    ('رسم زلمة أطول من البيت.', "He drew a man taller than the house."),
    ('همست: حلو. وارسمني أنا.', "She whispered: pretty. And draw me."),
    ('رسم دايرة، وفيها عصيتين، واسمها بيكي، وكانت مبسوطة.', "He drew a circle, with two sticks, and her name Becky, and she was pleased.")),
  P(('وبعدين كتب توم على اللوح إشي، وغطاه بإيده.', "And then Tom wrote something on the slate, and covered it with his hand."),
    ('قالت: فرجيني.', "She said: show me."),
    ('قال: لا.', "He said: no."),
    ('قالت: فرجيني، ما بقول لحدا.', "She said: show me, I will not tell anyone."),
    ('رفع إيده، وكان مكتوب: بحبك.', "He lifted his hand, and it said: I love you."),
    ('ضربته على إيده، واحمر وجهها، بس كانت مبسوطة.', "She slapped his hand, and her face went red, but she was pleased."),
    ('وبهاللحظة، إيد كبيرة مسكت توم من أذنه.', "And in that moment, a big hand took Tom by the ear."),
    ('ورفعته، وأخدته لمكانه.', "And lifted him, and took him back to his place."),
    ('المعلم.', "The teacher.")),
  P(('عالغدا، توم وبيكي التقوا ورا المدرسة.', "At lunch, Tom and Becky met behind the school."),
    ('قال توم: بيكي، بتحبي الفيران؟', "Tom said: Becky, do you like rats?"),
    ('قالت: لا! بكرههم!', "She said: no! I hate them!"),
    ('قال: الحية، قصدي. الميتة، اللي بتلفيها على خيط.', "He said: live ones, I mean. Dead ones, that you swing on a string."),
    ('قالت: بحب العلكة أكتر.', "She said: I like chewing gum better."),
    ('وطلع علكة، وقسموها، ولاكوها بالدور.', "And he took out gum, and they shared it, chewing it in turns."),
    ('وقال توم: بيكي، بدك نتخطب؟', "And Tom said: Becky, do you want us to be engaged?"),
    ('قالت: شو يعني؟', "She said: what does that mean?"),
    ('قال: يعني بتقولي لي إنك بتحبيني، وبنبوس بعض، وخلص. ما بتتزوجي غيري.', "He said: it means you tell me you love me, and we kiss, and that is it. You marry no one but me."),
    ('وهمست بحبك، وباسها، وصاروا مخطوبين.', "And she whispered I love you, and he kissed her, and they were engaged."))]),

 ('At Midnight in the Graveyard', 'بنص الليل بالمقبرة', [
  P(('بس الخطوبة ما عاشت نص ساعة.', "But the engagement did not last half an hour."),
    ('توم قال: هاي أحلى من أول مرة، لما كنت مخطوب لآمي.', "Tom said: this is nicer than the first time, when I was engaged to Amy."),
    ('بيكي وقفت. قالت: آمي؟ يعني أنا مش الأولى؟', "Becky stood up. She said: Amy? So I am not the first?"),
    ('وبكت، وما رضيت تحكي معه، وطلعت.', "And she cried, and would not speak to him, and left."),
    ('وتوم قعد لحاله، وحس إن الدنيا ظلمته.', "And Tom sat alone, and felt the world had wronged him."),
    ('قال: بموت. وبعدين بتندم.', "He said: I will die. And then she will be sorry."),
    ('وراح عالبيت، ونام بدري، واستنى نص الليل.', "And he went home, went to bed early, and waited for midnight.")),
  P(('بنص الليل، سمع مواء من تحت الشباك.', "At midnight, he heard a meow from under the window."),
    ('نزل من الشباك عالسقف، ومن السقف عالأرض.', "He climbed out the window onto the roof, from the roof to the ground."),
    ('وهَك بيستناه بالقطة الميتة.', "And Huck was waiting with the dead cat."),
    ('مشوا للمقبرة، فوق التلة، على مهل.', "They walked to the graveyard, on the hill, slowly."),
    ('المقبرة كانت قديمة، والقبور مايلة، والسور مكسور.', "The graveyard was old, the graves leaning, the fence broken."),
    ('والريح بتحرك الشجر، والقمر مرة بيطلع ومرة بيختفي.', "And the wind moved the trees, and the moon came out and vanished by turns."),
    ('اختبوا ورا تلات شجرات، جنب القبر الجديد، واستنوا.', "They hid behind three trees, beside the new grave, and waited.")),
  P(('همس توم: هَك، بتفكر الميتين بيحبوا نيجي هون؟', "Tom whispered: Huck, do you think the dead like us coming here?"),
    ('همس هَك: ما بعرف. اسكت.', "Huck whispered: I do not know. Be quiet."),
    ('وبعدين سمعوا صوت.', "And then they heard a sound."),
    ('أقدام، وحكي، وضو فانوس جاي من بعيد.', "Feet, and talk, and the light of a lantern coming from afar."),
    ('همس هَك: الشياطين! تلاتة!', "Huck whispered: the devils! Three of them!"),
    ('وقرب الضو، وشافوا الوجوه.', "And the light came near, and they saw the faces."),
    ('مش شياطين. تلات رجال.', "Not devils. Three men."),
    ('ماف بوتر، سكير القرية، والدكتور روبنسون الشاب، وجو الهندي.', "Muff Potter, the village drunk, young Doctor Robinson, and Injun Joe.")),
  P(('جو الهندي كان أخطر واحد بالقرية.', "Injun Joe was the most dangerous man in the village."),
    ('نص هندي، ووجهه ما بيتغير، وعينه بتخوف.', "Half Indian, with a face that never changed, and eyes that frightened."),
    ('وكانوا جايين يحفروا القبر الجديد، ويطلعوا الميت.', "And they had come to dig up the new grave, and take out the body."),
    ('الدكتور بده الجثة عشان يدرس عليها، ودافع للاتنين مصاري.', "The doctor wanted the body to study, and had paid the two of them."),
    ('حفروا، وطلعوا الصندوق، وفتحوه.', "They dug, brought up the coffin, and opened it."),
    ('وحطوا الجثة بعربية.', "And they put the body in a cart."),
    ('وبعدين قال جو الهندي: يا دكتور، بدك تدفع كمان.', "And then Injun Joe said: doctor, you have to pay more."),
    ('وتوم وهَك، ورا الشجر، ما بيتنفسوا.', "And Tom and Huck, behind the trees, did not breathe."))]),

 ('The Oath', 'القسم', [
  P(('قال الدكتور: دفعت لكم. ما في كمان.', "The doctor said: I paid you. There is no more."),
    ('قال جو الهندي: من خمس سنين، طردتني من مطبخ أبوك.', "Injun Joe said: five years ago, you drove me from your father's kitchen."),
    ('لأني طلبت أكل.', "Because I asked for food."),
    ('وحلفت وقتها إني ما بنسى. وهلق دورك.', "And I swore then that I would not forget. And now it is your turn."),
    ('ورفع إيده على الدكتور.', "And he raised his hand against the doctor."),
    ('الدكتور ضربه، ووقع جو عالأرض.', "The doctor struck him, and Joe fell to the ground."),
    ('وماف بوتر رمى سكينته، ونط على الدكتور.', "And Muff Potter dropped his knife, and jumped on the doctor."),
    ('والدكتور مسك لوح من القبر، وضرب ماف على راسه.', "And the doctor grabbed a board from the grave, and struck Muff on the head."),
    ('ووقع ماف بلا حركة.', "And Muff fell without moving.")),
  P(('وبهاللحظة، جو الهندي قام.', "And in that moment, Injun Joe got up."),
    ('لقى سكينة ماف عالأرض، وأخدها، وطعن الدكتور بصدره.', "He found Muff's knife on the ground, took it, and stabbed the doctor in the chest."),
    ('الدكتور وقع فوق ماف، والدم غطى الاتنين.', "The doctor fell on top of Muff, and the blood covered them both."),
    ('والقمر اختفى ورا غيمة.', "And the moon vanished behind a cloud."),
    ('وتوم وهَك، ركضوا.', "And Tom and Huck ran."),
    ('ركضوا بالعتمة، بين القبور، بلا ما يتطلعوا ورا.', "They ran in the dark, among the graves, without looking back.")),
  P(('وبالمقبرة، جو الهندي حط السكينة بإيد ماف.', "And in the graveyard, Injun Joe put the knife in Muff's hand."),
    ('وقعد جنبه، واستنى.', "And sat beside him, and waited."),
    ('ولما فاق ماف، وشاف الدم والسكينة، ارتجف.', "And when Muff came to, and saw the blood and the knife, he shook."),
    ('قال: يا جو... شو صار؟ أنا عملت هاد؟', "He said: Joe... what happened? Did I do this?"),
    ('قال جو الهندي: إنت. ضربته بالسكينة. وأنا شفت.', "Injun Joe said: you. You stabbed him with the knife. And I saw."),
    ('وماف، السكران، صدق.', "And Muff, the drunk, believed him."),
    ('وبكى، وقال: يا جو، ما تحكي لحدا. أنا ما بتذكر إشي.', "And he wept, and said: Joe, tell no one. I remember nothing."),
    ('وقال جو: ما بحكي. أنا صاحبك.', "And Joe said: I will not tell. I am your friend.")),
  P(('توم وهَك وصلوا للمصنع المهجور، وقعدوا عالأرض، وهم بيلهثوا.', "Tom and Huck reached the abandoned tannery, and sat on the floor, panting."),
    ('همس توم: هَك، شو رح يصير؟', "Tom whispered: Huck, what is going to happen?"),
    ('قال هَك: إذا الدكتور مات، بيشنقوا حدا.', "Huck said: if the doctor died, they hang someone."),
    ('قال توم: ونحكي؟', "Tom said: and do we tell?"),
    ('قال هَك: إذا حكينا، وجو الهندي ما انشنق، بيقتلنا. زي ما قتل الدكتور.', "Huck said: if we tell, and Injun Joe is not hanged, he kills us. As he killed the doctor."),
    ('وسكتوا، وبعدين قال توم: بنحلف. بنكتب قسم بالدم، وما بنحكي.', "And they were silent, and then Tom said: we swear. We write an oath in blood, and we do not tell."),
    ('وكتب توم على لوح خشب:', "And Tom wrote on a board:"),
    ('توم وهَك بيحلفوا إنهم ما بيحكوا أبداً.', "Tom and Huck swear they will never tell."),
    ('وإذا حكوا، بيموتوا.', "And if they tell, they die."),
    ('وشك كل واحد إصبعه بإبرة، وبصم بدمه.', "And each one pricked his finger with a needle, and signed with his blood."),
    ('ودفنوا اللوح تحت الحيط.', "And they buried the board under the wall."))]),

 ('Muff Potter in Prison', 'ماف بوتر بالسجن', [
  P(('تاني يوم، القرية كلها كانت بالمقبرة.', "The next day, the whole village was in the graveyard."),
    ('الدكتور ميت، والسكينة سكينة ماف بوتر، والكل عارف.', "The doctor was dead, the knife was Muff Potter's, and everyone knew."),
    ('وإجا ماف بنفسه، وهو بيرجف، ووقف قدام الجثة.', "And Muff himself came, shaking, and stood before the body."),
    ('قال: أنا ما عملتها. أنا ما بتذكر إشي.', "He said: I did not do it. I remember nothing."),
    ('وقال جو الهندي، قدام الكل، بصوت هادي: أنا شفته. هو اللي طعنه.', "And Injun Joe said, before everyone, in a calm voice: I saw him. He is the one who stabbed him."),
    ('وحكى القصة، بالمقلوب.', "And he told the story, backwards."),
    ('وتوم وهَك، واقفين بين الناس، وسامعين، وساكتين.', "And Tom and Huck, standing among the people, hearing, and silent.")),
  P(('أخدوا ماف عالسجن، وصار ينتظر المحاكمة.', "They took Muff to the jail, and he sat waiting for the trial."),
    ('والقرية بتقول: الشنق قليل عليه.', "And the village said: hanging is too little for him."),
    ('وتوم ما نام أسبوع.', "And Tom did not sleep for a week."),
    ('كل ليلة يحلم بالمقبرة، ويصحى، ويحكي بالنوم.', "Every night he dreamed of the graveyard, woke, and talked in his sleep."),
    ('وسيد سمعه بيقول: دم! وسكينة! وسأله بالصبح: توم، شو بتحلم؟', "And Sid heard him say: blood! And a knife! And asked him in the morning: Tom, what are you dreaming about?"),
    ('وتوم قال: أسناني بتوجعني. وربط فكه بمنديل، وما حكى.', "And Tom said: my teeth hurt. And he tied his jaw with a handkerchief, and said nothing.")),
  P(('وكل يوم، كان توم يروح عالسجن.', "And every day, Tom went to the jail."),
    ('السجن كان أوضة زغيرة من طوب، وشباك بقضبان.', "The jail was a small brick room, with a barred window."),
    ('وكان يحط للماف من الشباك تبغ وكبريت، وأحياناً أكل.', "And he would pass Muff tobacco and matches through the window, and sometimes food."),
    ('وماف كان يبكي، ويقول: يا توم، إنت الوحيد اللي بيجي.', "And Muff would weep, and say: Tom, you are the only one who comes."),
    ('كنت أساعدك تصيد، وأصلح لك طيارتك، وهلق الكل نسي.', "I used to help you fish, and fix your kites, and now everyone has forgotten."),
    ('بس إنت ما نسيت. ولا هَك.', "But you did not forget. Nor Huck."),
    ('وكل كلمة كانت زي سكينة بقلب توم.', "And every word was like a knife in Tom's heart.")),
  P(('وجو الهندي كان يمشي بالقرية حر، وبيسلم عالناس.', "And Injun Joe walked the village free, greeting people."),
    ('وكل ما شافه توم، كان يختبي.', "And every time Tom saw him, he hid."),
    ('قال هَك: إذا حكينا، جو بيقتلنا. وإذا ما حكينا، ماف بينشنق.', "Huck said: if we tell, Joe kills us. And if we do not tell, Muff hangs."),
    ('قال توم: بعرف.', "Tom said: I know."),
    ('قال هَك: وشو بنعمل؟', "Huck said: and what do we do?"),
    ('قال توم: ما بعرف.', "Tom said: I do not know."),
    ('وهاي أول مرة بحياته ما بيعرف.', "And it was the first time in his life he did not know."))]),

 ('Becky Turns Away', 'بيكي بتزعل', [
  P(('وفوق كل هاد، بيكي ما عادت تحكي معه.', "And on top of all that, Becky no longer spoke to him."),
    ('كانت تمرق جنبه بالمدرسة، وتتطلع لجهة تانية.', "She would pass him at school, and look the other way."),
    ('وتوم حاول كل إشي.', "And Tom tried everything."),
    ('وقف على راسه قدامها. ما تطلعت.', "He stood on his head in front of her. She did not look."),
    ('تخانق مع ولد قدامها، وربح. ما تطلعت.', "He fought a boy in front of her, and won. She did not look."),
    ('وبعدين مرضت، وغابت أسبوع، وتوم فكر إنها رح تموت.', "And then she fell ill, and was away a week, and Tom thought she would die."),
    ('وما عاد يهتم بالحرب ولا بالقراصنة ولا بأي إشي.', "And he no longer cared about war or pirates or anything.")),
  P(('الخالة بولي خافت عليه، لأنه صار أصفر وساكت.', "Aunt Polly worried about him, because he had gone pale and quiet."),
    ('وكانت بتحب الأدوية الجديدة، وبتجرب كل دوا بتسمع عنه.', "And she loved new medicines, and tried every remedy she heard of."),
    ('حممته بمي بارد، ولفته بشراشف مبلولة.', "She bathed him in cold water, and wrapped him in wet sheets."),
    ('وأعطته أدوية بطعم النار.', "And gave him medicines that tasted of fire."),
    ('وتوم ما كان يهتم.', "And Tom did not care."),
    ('وبعدين إجت بدوا جديد: مسكن الألم. وتوم أخد الزجاجة.', "And then she came with a new remedy: the pain-killer. And Tom took the bottle."),
    ('وصار يعطي منه للقطة، بيتر، بالمعلقة.', "And began giving it to the cat, Peter, by the spoonful."),
    ('وبيتر طار، وصار يركض بالبيت، ويقلب الكراسي، ويطلع عالحيطان.', "And Peter flew, and began racing around the house, overturning chairs, climbing the walls."),
    ('وقالت الخالة بولي: توم! شو عملت بالقطة؟', "And Aunt Polly said: Tom! What did you do to the cat?"),
    ('قال توم: أعطيتها الدوا. حبيتها زي ما بتحبيني.', "Tom said: I gave her the medicine. I loved her the way you love me."),
    ('وضحكت، وبكت، وبطلت تعطيه أدوية.', "And she laughed, and cried, and stopped giving him medicines.")),
  P(('وبيوم، رجعت بيكي عالمدرسة.', "And one day, Becky came back to school."),
    ('توم شافها من بعيد، وقلبه نط.', "Tom saw her from afar, and his heart leapt."),
    ('وبلش يلعب، ويصرخ، ويقفز، ويضحك، كله عشانها.', "And he began playing, shouting, jumping, laughing, all for her."),
    ('وهي وقفت مع بنت تانية، وتطلعت فيه، وقالت بصوت عالي:', "And she stood with another girl, looked at him, and said out loud:"),
    ('في ناس بيفكروا حالهم مهمين. بيعملوا أي إشي عشان الناس تتطلع فيهم.', "Some people think they are important. They do anything so people will look at them."),
    ('وتوم وقف مكانه، وصار وجهه أحمر.', "And Tom stood where he was, and his face went red."),
    ('ومشى، وهو بيقول لحاله: خلص. ما حدا بيحبني. رح أصير قرصان.', "And he walked off, saying to himself: that is it. No one loves me. I will become a pirate.")),
  P(('قرصان.', "A pirate."),
    ('يعني سفينة سودا، وعلم أسود، وسيف، وناس بتخاف لما تسمع اسمه.', "That meant a black ship, a black flag, a sword, and people afraid when they heard his name."),
    ('وبعدين بيرجع للقرية، بعد سنين، بتياب سودا.', "And then he would come back to the village, after years, in black clothes."),
    ('وبيكي بتشوفه وبتندم.', "And Becky would see him and be sorry."),
    ('راح وحكى مع جو هاربر، صاحبه.', "He went and talked to Joe Harper, his friend."),
    ('أمه كانت ضربته على إشي ما عمله.', "His mother had beaten him for something he had not done."),
    ('وجو قال: أنا معك.', "And Joe said: I am with you."),
    ('وراحوا عند هَك، وهَك قال: ليش لا؟', "And they went to Huck, and Huck said: why not?"),
    ('وقرروا يهربوا بنص الليل، على جزيرة جاكسون بالنهر.', "And they decided to run away at midnight, to Jackson's Island in the river."),
    ('ويصيروا قراصنة.', "And become pirates."))]),

 ('The Pirates Set Out', 'القراصنة بيطلعوا', [
  P(('بنص الليل، التقوا التلاتة عند النهر، تحت التلة.', "At midnight, the three met by the river, below the hill."),
    ('توم جاب لحمة مسلوقة، وجو هاربر جاب خبز.', "Tom brought boiled meat, and Joe Harper brought bread."),
    ('وهَك جاب مقلاية وتبغ.', "And Huck brought a frying pan and tobacco."),
    ('وكل واحد سرق اللي جابه، لأنه القراصنة ما بيشتروا.', "And each had stolen what he brought, because pirates do not buy."),
    ('توم قال: أنا الأسود، رعب البحار. وجو، إنت رعب المحيط. وهَك، إنت الإيد الحمرا.', "Tom said: I am the Black One, terror of the seas. And Joe, you are terror of the ocean. And Huck, you are Red Hand."),
    ('وكان في طوف زغير مربوط عالشط، لحدا من القرية.', "And there was a small raft tied at the shore, belonging to someone from the village."),
    ('وأخدوه.', "And they took it.")),
  P(('دفعوا الطوف بالنهر، والتيار حملهم.', "They pushed the raft into the river, and the current carried them."),
    ('والقرية نايمة، وضو أو ضوين بس بالشبابيك.', "And the village asleep, with only a light or two in the windows."),
    ('توم وقف بالنص، وإيديه على صدره.', "Tom stood in the middle, arms folded on his chest."),
    ('وقال بصوت واطي: انزلوا الشراع!', "And he said in a low voice: lower the sail!"),
    ('وما كان في شراع، بس جو قال: أمرك يا كابتن.', "And there was no sail, but Joe said: aye, captain."),
    ('ومر الطوف قدام القرية، وتوم تطلع على البيت اللي فيه بيكي.', "And the raft passed in front of the village, and Tom looked at the house where Becky was."),
    ('وقال بقلبه: لو بتعرف.', "And he said to himself: if only she knew.")),
  P(('وصلوا الجزيرة بعد ساعتين، وسحبوا الطوف عالشط.', "They reached the island after two hours, and pulled the raft up on the shore."),
    ('جزيرة جاكسون: طولها ميل، وفيها غابة، وما فيها حدا.', "Jackson's Island: a mile long, with a forest, and no one on it."),
    ('شعلوا نار كبيرة، وشووا اللحمة، وأكلوا زي الذياب.', "They lit a big fire, roasted the meat, and ate like wolves."),
    ('وقال جو: هاي الحياة!', "And Joe said: this is the life!"),
    ('وقال هَك: ما في مدرسة، ولا كنيسة.', "And Huck said: no school, no church."),
    ('ولا حدا بيقول لك اغسل وجهك.', "And no one telling you to wash your face."),
    ('وقال توم: والقراصنة ما بيقوموا بدري.', "And Tom said: and pirates do not get up early."),
    ('وناموا حول النار، والنجوم فوقهم.', "And they slept around the fire, with the stars above them.")),
  P(('بس توم ما نام بسرعة.', "But Tom did not fall asleep quickly."),
    ('كان يفكر بالطوف المسروق، وباللحمة المسروقة.', "He was thinking of the stolen raft, and the stolen meat."),
    ('القراصنة بيسرقوا، صحيح. بس بيسرقوا من الأعداء، مش من الجيران.', "Pirates steal, true. But they steal from enemies, not from neighbours."),
    ('وقرر: من بكرا، القراصنة ما بيسرقوا.', "And he decided: from tomorrow, the pirates would not steal."),
    ('وارتاح، ونام.', "And he was at peace, and slept."),
    ('وجو نام وهو بيفكر بأمه.', "And Joe slept thinking of his mother."),
    ('وهَك نام، لأنه هَك بينام بأي مكان.', "And Huck slept, because Huck slept anywhere."))]),

 ('Life on the Island', 'الحياة عالجزيرة', [
  P(('بالصبح، فاق توم على صوت الطيور، والشمس بين الشجر.', "In the morning, Tom woke to the sound of birds, the sun between the trees."),
    ('كان في ندى على العشب، وسنجاب بيتفرج عليه من غصن.', "There was dew on the grass, and a squirrel watching him from a branch."),
    ('ونملة بتجر ميتة أكبر منها.', "And an ant dragging a dead thing bigger than itself."),
    ('وقعد يتفرج، وحس إنه أول واحد بالدنيا.', "And he sat watching, and felt he was the first person in the world."),
    ('وبعدين صحى الباقي، وركضوا التلاتة للنهر، وسبحوا.', "And then the others woke, and the three ran to the river, and swam.")),
  P(('ولما رجعوا، الطوف ما كان موجود.', "And when they came back, the raft was gone."),
    ('التيار أخده بالليل.', "The current had taken it in the night."),
    ('قال جو: وكيف بنرجع؟', "Joe said: and how do we get back?"),
    ('قال توم: القراصنة ما بيرجعوا.', "Tom said: pirates do not go back."),
    ('وصادوا سمك، وشووه، وأكلوه، وكان أطيب سمك بحياتهم.', "And they caught fish, roasted it, ate it, and it was the best fish of their lives."),
    ('لأنه الجوع أحسن طباخ.', "Because hunger is the best cook."),
    ('وبعد الأكل، مشوا بالجزيرة، ولقوا فيها كل إشي.', "And after eating, they walked the island, and found everything on it."),
    ('شجر، ونبع، ومغارة زغيرة، وشط رملي.', "Trees, a spring, a small cave, a sandy beach.")),
  P(('وبعد الظهر، صار الوقت يمشي بطيء.', "And in the afternoon, time began to move slowly."),
    ('قعدوا عالشط، وما حدا حكى.', "They sat on the shore, and no one spoke."),
    ('توم رسم بالرمل، وجو تطلع عالنهر، وهَك دخن غليونه.', "Tom drew in the sand, Joe looked at the river, and Huck smoked his pipe."),
    ('وجو قال: بتفكروا... شو بيعملوا هلق بالقرية؟', "And Joe said: do you think... what are they doing now in the village?"),
    ('قال توم: أكيد بيدوروا علينا.', "Tom said: surely they are looking for us."),
    ('وقال جو: يمكن أمي...', "And Joe said: maybe my mother..."),
    ('وسكت، لأنه إذا كمل، كان رح يبكي.', "And he stopped, because if he went on, he would cry."),
    ('وتوم كمان كان يفكر بالخالة بولي، بس ما حكى.', "And Tom too was thinking of Aunt Polly, but said nothing.")),
  P(('وهَك، اللي ما إله أم، كان أهدى واحد.', "And Huck, who had no mother, was the calmest one."),
    ('قال: أنا مبسوط. هون في أكل، وما حدا بيضربني.', "He said: I am happy. Here there is food, and no one beats me."),
    ('وبالقرية، لا أكل ولا حدا بيهتم.', "And in the village, no food and no one cares."),
    ('وتوم سمع، وفهم لأول مرة إن هَك مش حر، بل وحيد.', "And Tom heard, and understood for the first time that Huck was not free, but alone."),
    ('وإجا الليل التاني، وشعلوا النار، وناموا.', "And the second night came, and they lit the fire, and slept."),
    ('وما حدا قال إنه بده يرجع.', "And no one said he wanted to go back."),
    ('بس كل واحد فكر فيها.', "But every one of them thought it."))]),

 ('The Sound on the River', 'الصوت عالنهر', [
  P(('بعد الظهر التاني، سمعوا صوت من بعيد.', "The second afternoon, they heard a sound from afar."),
    ('بوم. صوت عميق، من النهر.', "Boom. A deep sound, from the river."),
    ('قال جو: شو هاد؟', "Joe said: what was that?"),
    ('قال هَك: رعد؟', "Huck said: thunder?"),
    ('قال توم: لا. اسمعوا.', "Tom said: no. Listen."),
    ('وبعد دقيقة، بوم كمان مرة.', "And a minute later, boom again."),
    ('ركضوا للشط، وتطلعوا عالنهر.', "They ran to the shore, and looked at the river.")),
  P(('كانت الباخرة الزغيرة تبع القرية، ماشية بنص النهر.', "It was the village's little steamboat, moving down the middle of the river."),
    ('وعليها ناس كتار.', "With many people on it."),
    ('وكل شوي، بيطلع دخان من جنبها، وبعدين بوم.', "And every so often, smoke came from her side, and then boom."),
    ('قال هَك: بيضربوا مدفع عالمي!', "Huck said: they are firing a cannon at the water!"),
    ('قال توم: أنا بعرف ليش! هيك بيعملوا لما حدا يغرق.', "Tom said: I know why! That is what they do when someone drowns."),
    ('صوت المدفع بيخلي الجثة تطلع عالسطح.', "The sound of the cannon makes the body rise to the surface."),
    ('وسكتوا التلاتة، وفهموا مرة وحدة.', "And the three were silent, and understood all at once."),
    ('قال جو: بيدوروا علينا. بيفكروا إنا غرقنا.', "Joe said: they are looking for us. They think we drowned.")),
  P(('وتوم صار وجهه يلمع.', "And Tom's face began to shine."),
    ('قال: يعني القرية كلها بتحكي عنا!', "He said: that means the whole village is talking about us!"),
    ('والناس بتبكي، والأولاد بيحسدونا، وإحنا أبطال!', "The people are crying, the boys envy us, and we are heroes!"),
    ('وحس إنه هاي أحلى لحظة بحياته.', "And he felt it was the finest moment of his life."),
    ('بس جو ما كان مبسوط.', "But Joe was not happy."),
    ('كان بيتخيل أمه، وهي واقفة عالشط، وبتبكي.', "He was imagining his mother, standing on the shore, crying."),
    ('وهَك كان يفكر: مين رح يبكي عليّ؟', "And Huck was thinking: who is going to cry over me?")),
  P(('وإجا الليل، والباخرة رجعت، والنهر رجع هادي.', "And night came, and the steamboat went back, and the river went quiet again."),
    ('وناموا اتنين. وتوم ما نام.', "And two slept. And Tom did not."),
    ('قعد يفكر بالخالة بولي.', "He sat thinking of Aunt Polly."),
    ('وكل ما يفكر، يشوفها تبكي، وهو ما بيتحمل هالصورة.', "And every time he thought, he saw her crying, and he could not bear that picture."),
    ('وبعد نص الليل، قام على مهل، وكتب إشي على قطعة لحا بالطبشور.', "And after midnight, he got up slowly, and wrote something on a piece of bark with chalk."),
    ('وحطها بجيبه، وحط قطعة تانية جنب جو.', "And put it in his pocket, and put another piece beside Joe."),
    ('ومشى للشط، ونزل بالمي.', "And walked to the shore, and went into the water."))]),

 ('Tom Goes Home in the Dark', 'توم بيرجع بالعتمة', [
  P(('النهر بين الجزيرة والقرية مش عريض، بس التيار قوي.', "The river between the island and the village is not wide, but the current is strong."),
    ('مشى توم بالمي لحد الخصر، وبعدين سبح.', "Tom walked in the water up to his waist, and then swam."),
    ('والتيار أخده لتحت، بس هو كان سباح منيح.', "And the current took him downstream, but he was a good swimmer."),
    ('وصل عالشط التاني بعيد عن القرية، ومشى عالطريق، بالعتمة.', "He reached the far bank away from the village, and walked along the road, in the dark."),
    ('وكان في باخرة مربوطة، فركب فيها، ونام بالقاع لحد ما تحركت.', "And there was a ferry tied up, so he got on it, and lay in the bottom until it moved."),
    ('ولما وصلت للقرية، نزل، وركض بين البيوت.', "And when it reached the village, he got off, and ran between the houses.")),
  P(('وصل لبيت الخالة بولي، وشاف ضو بالشباك.', "He reached Aunt Polly's house, and saw a light in the window."),
    ('طل من الشباك: الخالة بولي قاعدة، وسيد، وماري، وأم جو هاربر.', "He looked through the window: Aunt Polly sitting, and Sid, and Mary, and Joe Harper's mother."),
    ('وكلهم بيبكوا.', "And all of them crying."),
    ('دخل من الباب الخلفي، وزحف تحت السرير، وسمع.', "He went in the back door, crawled under the bed, and listened."),
    ('كانت الخالة بولي بتقول: توم ما كان ولد سيء. كان شقي بس.', "Aunt Polly was saying: Tom was not a bad boy. He was only mischievous."),
    ('وقلبه أطيب من قلب أي ولد.', "And his heart was kinder than any boy's."),
    ('وأم جو قالت: وجو كمان. ضربته على إشي ما عمله، والله يسامحني.', "And Joe's mother said: and Joe too. I beat him for something he did not do, God forgive me.")),
  P(('وقالوا إنه الأحد رح يعملوا جنازة للتلاتة.', "And they said that on Sunday they would hold a funeral for the three."),
    ('لأنه بعد أربع أيام، ما حدا بيطلع من النهر.', "Because after four days, no one comes out of the river."),
    ('وتوم تحت السرير، وبده يطلع، وبده يعانق الخالة بولي.', "And Tom under the bed, wanting to come out, wanting to hug Aunt Polly."),
    ('بس ما طلع.', "But he did not come out."),
    ('لأنه إجت له فكرة أكبر.', "Because a bigger idea had come to him."),
    ('وراحوا الضيوف، ونامت الخالة، وهي بتصلي على توم.', "And the guests left, and the aunt slept, praying over Tom.")),
  P(('طلع توم من تحت السرير، ووقف جنبها.', "Tom came out from under the bed, and stood beside her."),
    ('كانت نايمة، ووجهها تعبان، وعلى خدها دمعة.', "She was asleep, her face tired, a tear on her cheek."),
    ('طلع قطعة اللحا من جيبه، وقرا اللي كتبه.', "He took the piece of bark from his pocket, and read what he had written."),
    ('إحنا مش ميتين، إحنا قراصنة.', "We are not dead, we are pirates."),
    ('وكان رح يحطها جنبها.', "And he was about to put it beside her."),
    ('بس فكر بالجنازة، وبالفكرة الكبيرة، ورجع اللحا لجيبه.', "But he thought of the funeral, and the big idea, and put the bark back in his pocket."),
    ('وباسها على خدها، وهي نايمة.', "And he kissed her on the cheek, as she slept."),
    ('وطلع، ورجع للنهر، وسبح للجزيرة قبل الفجر.', "And he went out, went back to the river, and swam to the island before dawn."))]),

 ('The Storm', 'العاصفة', [
  P(('لما وصل، لقى جو وهَك قاعدين عالشط، وزعلانين.', "When he arrived, he found Joe and Huck sitting on the shore, upset."),
    ('قال جو: قريت اللحا. فكرناك هربت وتركتنا.', "Joe said: I read the bark. We thought you had run off and left us."),
    ('قال توم: أنا القرصان الأسود. ما بترك رجالي.', "Tom said: I am the Black Pirate. I do not leave my men."),
    ('وحكى لهم عن الليل، والبكا، والجنازة.', "And he told them about the night, the crying, the funeral."),
    ('وقال: عندي فكرة. بس لسا ما بحكيها.', "And he said: I have an idea. But I am not telling it yet."),
    ('وجو قال: بدي أرجع.', "And Joe said: I want to go home."),
    ('وتوم قال: بس لحد الأحد. صدقني.', "And Tom said: only until Sunday. Trust me.")),
  P(('وبنفس الليلة، إجت العاصفة.', "And that same night, the storm came."),
    ('بالأول ريح، وبعدين برق، وبعدين رعد زي المدافع.', "First wind, then lightning, then thunder like cannons."),
    ('والمطر نزل زي إنه النهر انقلب عليهم من فوق.', "And the rain came down as if the river had been turned over on them from above."),
    ('ركضوا للخيمة اللي عملوها من الشرشف، والريح أخدت الشرشف.', "They ran to the tent they had made from the sheet, and the wind took the sheet."),
    ('ركضوا للشجرة الكبيرة، والبرق ضرب الشجرة.', "They ran to the big tree, and the lightning struck the tree."),
    ('ركضوا للمغارة، وقعدوا فيها.', "They ran to the cave, and sat in it."),
    ('وهم بيرجفوا، ومبلولين لحد العظم.', "Shaking, and soaked to the bone."),
    ('وطول الليل، البرق بيضوي الجزيرة زي النهار، وبعدين عتمة.', "And all night, the lightning lit the island like day, and then darkness.")),
  P(('وبالصبح، هدي كل إشي.', "And in the morning, everything was calm."),
    ('طلعوا من المغارة، والجزيرة صارت إشي تاني.', "They came out of the cave, and the island had become something else."),
    ('شجر مكسور، وأغصان بكل مكان، والنار راحت.', "Broken trees, branches everywhere, and the fire gone."),
    ('والشجرة الكبيرة اللي ناموا تحتها أول ليلة، مشقوقة نصين.', "And the big tree they had slept under the first night, split in two."),
    ('قال هَك: لو كنا تحتها.', "Huck said: if we had been under it."),
    ('وما حدا كمل الجملة.', "And no one finished the sentence."),
    ('ولقوا جمرة تحت الرماد، وشعلوا النار، ونشفوا، وأكلوا.', "And they found an ember under the ashes, lit the fire, dried off, and ate.")),
  P(('وبعد الأكل، توم قال: هلق بحكي لكم الفكرة.', "And after eating, Tom said: now I tell you the idea."),
    ('وحكاها، بصوت واطي، زي إنها سر حرب.', "And he told it, in a low voice, as if it were a secret of war."),
    ('وجو صار يضحك، وهَك صار يضحك، وقالوا: هاي أحسن فكرة بالدنيا.', "And Joe began laughing, and Huck began laughing, and they said: this is the best idea in the world."),
    ('وقال جو: يعني بنرجع الأحد؟', "And Joe said: so we go back on Sunday?"),
    ('قال توم: الأحد. بس مش زي ما بيتوقعوا.', "Tom said: Sunday. But not the way they expect."))]),

 ('Their Own Funeral', 'جنازتهم', [
  P(('يوم الأحد، الكنيسة كانت مليانة زي ما ما كانت أبداً.', "On Sunday, the church was fuller than it had ever been."),
    ('القرية كلها إجت. الناس اللي بيروحوا، واللي ما بيروحوا.', "The whole village came. The people who go, and the ones who do not."),
    ('الخالة بولي، وسيد، وماري، بتياب سودا، بأول صف.', "Aunt Polly, Sid and Mary, in black clothes, in the first row."),
    ('وأم جو هاربر وأبوه جنبهم.', "And Joe Harper's mother and father beside them."),
    ('وما حدا لهَك، بس الأرملة دوغلاس بكت عليه.', "And no one for Huck, but the Widow Douglas cried for him."),
    ('لأنه كان بيجيب لها حطب أحياناً.', "Because he sometimes brought her firewood."),
    ('والناس كلها ساكتة، والجرس بيدق على مهل.', "And all the people silent, and the bell tolling slowly.")),
  P(('القس وقف، وبلش يحكي عن التلاتة.', "The preacher stood, and began speaking about the three."),
    ('حكى عن طيبتهم، وعن ذكائهم، وعن قلوبهم النضيفة.', "He spoke of their goodness, their cleverness, their clean hearts."),
    ('وحكى قصص عنهم، قصص كان الناس يسموها شقاوة، وهلق صارت لطف.', "And he told stories about them, stories people had called mischief, and now called kindness."),
    ('وكل الكنيسة بتبكي.', "And the whole church was weeping."),
    ('والقس نفسه بكى.', "And the preacher himself wept."),
    ('وبآخر الخطبة، انفتح باب الكنيسة.', "And at the end of the sermon, the church door opened."),
    ('وما حدا انتبه، بالأول.', "And no one noticed, at first.")),
  P(('وبعدين القس رفع عينه من الورقة، ووقف.', "And then the preacher raised his eyes from the paper, and froze."),
    ('وبعدين لفت الناس، صف ورا صف.', "And then the people turned, row after row."),
    ('وشافوا.', "And they saw."),
    ('التلاتة، ماشيين بالممر. توم قدام، وجو وراه، وهَك بالآخر، وهو مستحي.', "The three, walking down the aisle. Tom in front, Joe behind him, and Huck last, embarrassed."),
    ('كانوا وسخين، وتيابهم مقطعة، ووجوههم محروقة من الشمس.', "They were dirty, their clothes torn, their faces burned by the sun."),
    ('كانوا مختبيين بالغرفة الخلفية، وسامعين جنازتهم كلها.', "They had been hiding in the back room, hearing their whole funeral."),
    ('والخالة بولي صرخت، وركضت، ومسكت توم، وباسته مية مرة.', "And Aunt Polly screamed, ran, seized Tom, and kissed him a hundred times."),
    ('وأم جو مسكت جو.', "And Joe's mother seized Joe.")),
  P(('وهَك وقف لحاله، وما حدا مسكه.', "And Huck stood alone, and no one seized him."),
    ('وتوم قال: يا خالتي، حدا لازم يفرح بهَك كمان.', "And Tom said: auntie, someone has to be glad about Huck too."),
    ('وقالت الخالة بولي: أنا بفرح فيه. وعانقته.', "And Aunt Polly said: I am glad about him. And she hugged him."),
    ('وهَك ما عرف شو يعمل بإيديه.', "And Huck did not know what to do with his hands."),
    ('وبعدين القس صرخ: غنوا! غنوا بكل قلوبكم!', "And then the preacher shouted: sing! Sing with all your hearts!"),
    ('وغنت الكنيسة كلها، لدرجة إن السقف اهتز.', "And the whole church sang, so the roof shook."),
    ('وتوم وقف بالنص، والناس حواليه.', "And Tom stood in the middle, the people around him."),
    ('وقال بقلبه: هاي أحسن لحظة بحياتي.', "And he said to himself: this is the finest moment of my life."),
    ('وهالمرة، كان معه حق.', "And this time, he was right."))]),

 ('The Torn Book', 'الكتاب المقطوع', [
  P(('بعد الجنازة، توم صار بطل القرية.', "After the funeral, Tom became the hero of the village."),
    ('الأولاد بيمشوا وراه، وبيسألوه عن الجزيرة، وهو بيحكي ويزيد.', "The boys followed him around, asking about the island, and he told it and added to it."),
    ('وبيكي؟ بيكي ما حكت معه.', "And Becky? Becky did not speak to him."),
    ('بس هالمرة، توم قرر إنه ما بده ياها.', "But this time, Tom decided he did not want her."),
    ('وصار يحكي مع آمي قدامها، ويضحك بصوت عالي.', "And he began talking to Amy in front of her, laughing loudly."),
    ('وبيكي صارت تحكي مع ألفرد، ولد غني ومهذب، قدام توم.', "And Becky began talking to Alfred, a rich, polite boy, in front of Tom."),
    ('وكل واحد كان بيتعذب، ويعمل حاله مبسوط.', "And each was suffering, and pretending to be happy.")),
  P(('وبهاليوم، صار إشي بالمدرسة.', "And that day, something happened at school."),
    ('المعلم، السيد دوبنز، كان عنده كتاب بيخبيه بدرج مقفول.', "The teacher, Mr. Dobbins, had a book he kept in a locked drawer."),
    ('كتاب تشريح، فيه صور جسم الإنسان، وكل الأولاد بدهم يشوفوه.', "An anatomy book, with pictures of the human body, and all the children wanted to see it."),
    ('وبيكي مرقت جنب الدرج، ولقيته مفتوح، وما قدرت تقاوم.', "And Becky passed by the drawer, found it open, and could not resist."),
    ('فتحت الكتاب، وشافت صورة، واحمر وجهها.', "She opened the book, saw a picture, and her face went red."),
    ('وبهاللحظة، دخل توم من الباب.', "And in that moment, Tom came in the door."),
    ('خافت، وسكرت الكتاب بسرعة، وانقطعت الصفحة نصين.', "She panicked, shut the book quickly, and the page tore in two.")),
  P(('قالت بيكي: توم سوير، إنت جاسوس! إنت رح تحكي!', "Becky said: Tom Sawyer, you are a spy! You are going to tell!"),
    ('وبكت، وركضت.', "And she cried, and ran."),
    ('وتوم وقف مكانه، وقال: أنا ما حكيت إشي.', "And Tom stood where he was, and said: I did not say anything."),
    ('وفكر: هلق بينضرب حدا. المعلم بيسأل الكل، وبيعرف من وجهها.', "And he thought: now someone gets beaten. The teacher will ask everyone, and know from her face."),
    ('وفكر كمان: وأنا شو بهمني؟ هي ما بتحبني.', "And he thought too: and what do I care? She does not love me."),
    ('بس كان بيهمه.', "But he cared.")),
  P(('وبعد الظهر، المعلم فتح الدرج، وشاف الكتاب، ووقف.', "And in the afternoon, the teacher opened the drawer, saw the book, and froze."),
    ('وسأل: مين قطع هالكتاب؟', "And he asked: who tore this book?"),
    ('وصمت.', "And silence."),
    ('وبلش يسأل واحد واحد. بن؟ لا. جو؟ لا. آمي؟ لا.', "And he began asking one by one. Ben? No. Joe? No. Amy? No."),
    ('ووصل لبيكي، وبيكي صار وجهها أبيض، وإيديها بترجف.', "And he reached Becky, and Becky's face went white, her hands shaking."),
    ('وقبل ما يسألها، توم وقف، وقال: أنا.', "And before he asked her, Tom stood up, and said: me."),
    ('والمدرسة كلها لفت عليه.', "And the whole school turned to him."),
    ('وضربه المعلم أقسى ضرب ضربه بحياته، وتوم ما حس.', "And the teacher gave him the hardest beating he had ever given, and Tom felt nothing."),
    ('لأنه شاف وجه بيكي.', "Because he had seen Becky's face."),
    ('وبآخر النهار، همست له: توم، كيف بتقدر تكون نبيل هيك؟', "And at the end of the day, she whispered to him: Tom, how can you be so noble?"))]),

 ('Examination Day', 'يوم الامتحان', [
  P(('إجا آخر يوم بالسنة، يوم الامتحان.', "The last day of the year came, examination day."),
    ('كل الأهل بيجوا، والأولاد بيقروا شعر.', "All the parents come, and the children recite poems."),
    ('والمعلم بيلبس أحسن تيابه.', "And the teacher wears his best clothes."),
    ('وكان المعلم دوبنز رجل قاسي، وبيضرب كتير، والأولاد بيكرهوه.', "And Mr. Dobbins was a harsh man, who beat a lot, and the children hated him."),
    ('وكان عنده سر: شعره باروكة، وتحتها راسه أصلع ولامع.', "And he had a secret: his hair was a wig, and under it his head was bald and shining."),
    ('والأولاد الكبار عملوا خطة لهاليوم.', "And the older boys made a plan for that day.")),
  P(('كان المعلم بيشرب شوي قبل الامتحان، عشان الشجاعة.', "The teacher would drink a little before the examination, for courage."),
    ('وهاليوم، شرب أكتر، والأولاد كانوا بيعرفوا.', "And that day, he drank more, and the boys knew it."),
    ('الامتحان بلش. ولد قرا شعر. وبنت قرأت مقالة.', "The examination began. A boy recited a poem. A girl read an essay."),
    ('وتوم وقف يقرا خطبة، ونسي بالنص، ووقف يتطلع بالناس، وقعد.', "And Tom stood to give a speech, forgot in the middle, stood staring at the people, and sat down."),
    ('وبعدين قام المعلم يرسم خريطة عاللوح، للجغرافيا.', "And then the teacher got up to draw a map on the board, for geography."),
    ('وظهره للناس، وفوقه، بالسقف، في باب زغير للعلية.', "With his back to the people, and above him, in the ceiling, a small door to the attic.")),
  P(('وانفتح الباب.', "And the door opened."),
    ('ونزل منه حبل، على مهل، وبآخره قطة.', "And a rope came down from it, slowly, with a cat at its end."),
    ('قطة مربوطة من بطنها، وتمها مربوط عشان ما تموء.', "A cat tied around its belly, its mouth tied so it could not meow."),
    ('ونزلت، ونزلت، وهي بتحرك إجريها بالهوا.', "And it came down, and down, paddling its legs in the air."),
    ('والناس بتشوف، والمعلم لا، لأنه مشغول بالخريطة.', "And the people saw, and the teacher did not, because he was busy with the map."),
    ('ولما وصلت القطة فوق راسه، مسكت الباروكة بأظافيرها.', "And when the cat reached above his head, it grabbed the wig with its claws.")),
  P(('وسحبوها لفوق.', "And they pulled it up."),
    ('والباروكة معها.', "And the wig with it."),
    ('ووقف المعلم قدام القرية كلها، وراسه أصلع.', "And the teacher stood before the whole village, his head bald."),
    ('ولامع، ومدهون بالذهب.', "And shining, and painted gold."),
    ('لأنه ولد الرسام دهن راسه وهو نايم من الشرب.', "Because the painter's boy had painted his head while he slept off the drink."),
    ('والقاعة انفجرت.', "And the hall exploded."),
    ('وهيك خلصت السنة الدراسية، وبلشت العطلة.', "And so the school year ended, and the holidays began."))]),

 ('The Trial', 'المحاكمة', [
  P(('بالعطلة، إجت محاكمة ماف بوتر.', "In the holidays, came Muff Potter's trial."),
    ('والقرية كلها بتحكي عنها، وتوم ما بيقدر يهرب من الحكي.', "And the whole village was talking about it, and Tom could not escape the talk."),
    ('كل ليلة، بيروح لهَك، ويحكوا بالسر.', "Every night, he went to Huck, and they talked in secret."),
    ('قال هَك: توم، حكيت لحدا؟', "Huck said: Tom, did you tell anyone?"),
    ('قال توم: لا. ما بقدر. القسم.', "Tom said: no. I cannot. The oath."),
    ('قال هَك: ولا كلمة. لأنه جو الهندي بيغرقنا زي القطط.', "Huck said: not a word. Because Injun Joe would drown us like cats."),
    ('وحلفوا مرة تانية.', "And they swore once more.")),
  P(('وراحوا للسجن، زي كل يوم.', "And they went to the jail, as every day."),
    ('وماف قال من الشباك: يا أولاد، إنتو أحسن ناس بالدنيا.', "And Muff said from the window: boys, you are the best people in the world."),
    ('بكرا بيشنقوني، وأنا مستحق. كنت سكران، وقتلت.', "Tomorrow they hang me, and I deserve it. I was drunk, and I killed."),
    ('بس تذكروني منيح. وما تشربوا أبداً.', "But remember me well. And never drink."),
    ('ومد إيده من القضبان، ومسك إيديهم.', "And he put his hand through the bars, and held their hands."),
    ('وتوم رجع عالبيت، وما نام.', "And Tom went home, and did not sleep."),
    ('وبنص الليل، طلع من الشباك، وراح لمكان.', "And at midnight, he went out the window, and went somewhere.")),
  P(('يوم المحاكمة، المحكمة كانت مليانة.', "On the day of the trial, the courtroom was full."),
    ('ماف قاعد، أصفر، ومكسور، والسلاسل بإيديه.', "Muff sat, pale, broken, chains on his hands."),
    ('وجو الهندي قاعد بين الشهود، ووجهه زي الحجر.', "And Injun Joe sat among the witnesses, his face like stone."),
    ('الشهود حكوا: السكينة سكينة ماف. وماف كان بالمقبرة. وماف غسل الدم بالنهر بالصبح.', "The witnesses told: the knife was Muff's. And Muff was in the graveyard. And Muff washed off blood in the river in the morning."),
    ('ومحامي ماف ما سأل ولا سؤال، والناس استغربوا.', "And Muff's lawyer asked not one question, and the people were puzzled."),
    ('وبعدين وقف المحامي، وقال: بنادي توم سوير.', "And then the lawyer stood, and said: I call Tom Sawyer.")),
  P(('كل الوجوه لفت، وجو الهندي لف كمان.', "Every face turned, and Injun Joe turned too."),
    ('توم مشى للمنصة، وهو بيرجف.', "Tom walked to the stand, shaking."),
    ('قال المحامي: توم، وين كنت ليلة القتل، بنص الليل؟', "The lawyer said: Tom, where were you on the night of the murder, at midnight?"),
    ('توم تطلع بجو الهندي، وضاع صوته.', "Tom looked at Injun Joe, and his voice vanished."),
    ('وبعدين تطلع بماف، وقال: بالمقبرة.', "And then he looked at Muff, and said: in the graveyard."),
    ('وحكى. حكى كل إشي، من القطة الميتة للسكينة.', "And he told. He told everything, from the dead cat to the knife."),
    ('وكل ما يحكي، صوته يقوى، والمحكمة تسكت أكتر.', "And the more he told, the stronger his voice grew, and the quieter the court became."),
    ('ولما وصل للطعنة، وقال: وجو الهندي أخد السكينة و...', "And when he reached the stabbing, and said: and Injun Joe took the knife and..."),
    ('صار صوت زجاج.', "There was the sound of glass."),
    ('جو الهندي نط من الشباك، زي النمر، واختفى.', "Injun Joe leapt through the window, like a tiger, and vanished."))]),

 ('After the Trial', 'بعد المحاكمة', [
  P(('توم صار بطل مرة تانية، وهالمرة بطل حقيقي.', "Tom became a hero once more, and this time a real hero."),
    ('الجريدة كتبت عنه، والقاضي قال إنه رح يصير رجل عظيم.', "The newspaper wrote about him, and the judge said he would become a great man."),
    ('وماف بوتر طلع من السجن، والناس عانقوه، وهو بيبكي.', "And Muff Potter came out of the jail, the people embraced him, and he wept."),
    ('بالنهار، توم كان أسعد ولد بالدنيا.', "By day, Tom was the happiest boy in the world."),
    ('وبالليل، كان أخوف ولد بالدنيا.', "And by night, the most frightened boy in the world."),
    ('لأنه جو الهندي برا، حر، وبيعرف مين حكى.', "Because Injun Joe was out there, free, and knew who had talked.")),
  P(('كل صوت بالليل، جو الهندي.', "Every sound at night, Injun Joe."),
    ('كل وجه بالشارع، جو الهندي.', "Every face in the street, Injun Joe."),
    ('والشرطة دورت عليه بكل مكان، وجابوا محقق من المدينة الكبيرة.', "And the police searched for him everywhere, and brought a detective from the big city."),
    ('والمحقق دور أسبوع، وقال: لقيت دليل.', "And the detective searched a week, and said: I have found a clue."),
    ('بس الدليل ما بيشنقوه.', "But you cannot hang a clue."),
    ('وراح المحقق، وضل جو الهندي برا.', "And the detective left, and Injun Joe stayed out there.")),
  P(('وهَك كان خايف أكتر من توم.', "And Huck was more afraid than Tom."),
    ('قال: يا توم، إنت كسرت القسم.', "He said: Tom, you broke the oath."),
    ('قال توم: ما قدرت أشوف ماف بينشنق.', "Tom said: I could not watch Muff hang."),
    ('قال هَك: بعرف. وأنا ما بلومك. بس هو بيعرف إني كنت معك.', "Huck said: I know. And I do not blame you. But he knows I was with you."),
    ('قال توم: هو ما شافنا.', "Tom said: he did not see us."),
    ('قال هَك: بس بيفكر.', "Huck said: but he thinks."),
    ('وقعدوا الاتنين، وكل واحد بيتطلع عالعتمة من ورا التاني.', "And the two sat, each looking into the dark over the other's shoulder.")),
  P(('ومرت أسابيع، وما ظهر جو الهندي.', "And weeks passed, and Injun Joe did not appear."),
    ('وشوي شوي، الخوف صار أخف.', "And little by little, the fear grew lighter."),
    ('وتوم بلش يفكر بإشي تاني.', "And Tom began thinking of something else."),
    ('كنز.', "Treasure."),
    ('لأنه كل ولد بيجي عليه وقت، وبده يحفر ويلاقي كنز.', "Because every boy comes to a time when he wants to dig and find treasure."),
    ('وراح لهَك، وقال: هَك، بدك نصير أغنيا؟', "And he went to Huck, and said: Huck, do you want us to be rich?"),
    ('قال هَك: كيف؟', "Huck said: how?"),
    ('قال توم: بنحفر.', "Tom said: we dig."))]),

 ('The Haunted House', 'البيت المسكون', [
  P(('قال توم: الكنوز بيدفنوها القراصنة.', "Tom said: pirates bury treasures."),
    ('تحت شجرة ميتة، أو ببيت مسكون.', "Under a dead tree, or in a haunted house."),
    ('قال هَك: وكيف بنعرف وين؟', "Huck said: and how do we know where?"),
    ('قال توم: بنحفر بكل مكان لحد ما نلاقي.', "Tom said: we dig everywhere until we find it."),
    ('وحفروا تحت شجرة ميتة عالتلة، نهار كامل، وما لقوا إشي.', "And they dug under a dead tree on the hill, a whole day, and found nothing."),
    ('قال توم: الغلط إنه لازم نحفر بنص الليل، لما يوقع ظل الغصن.', "Tom said: the mistake is that we must dig at midnight, where the shadow of the branch falls."),
    ('وحفروا بنص الليل، وما لقوا إشي.', "And they dug at midnight, and found nothing."),
    ('قال توم: طيب. البيت المسكون.', "Tom said: fine. The haunted house.")),
  P(('البيت المسكون كان على طرف القرية، مهجور من سنين.', "The haunted house was at the edge of the village, abandoned for years."),
    ('شبابيكه مكسورة، وبابه مايل، والعشب طالع من الدرج.', "Its windows broken, its door hanging, grass growing up the steps."),
    ('وكل الناس بيقولوا إن فيه أشباح، وما حدا بيقرب منه.', "And everyone said it had ghosts, and no one went near it."),
    ('راحوا بالنهار، لأنه الأشباح بتنام بالنهار.', "They went by day, because ghosts sleep by day."),
    ('وفاتوا على مهل، والباب صرّ، وقلبهم بيدق.', "And they went in slowly, the door creaking, their hearts pounding."),
    ('الأوضة تحت: تراب، وعنكبوت، وموقد مكسور.', "The room below: dust, spiders, a broken hearth."),
    ('والدرج طالع لفوق.', "And the stairs going up.")),
  P(('طلعوا لفوق، وشافوا أوضتين فاضيتين.', "They went up, and saw two empty rooms."),
    ('وحطوا الفأس عالأرض، وكانوا رح ينزلوا يحفروا.', "And they put the pick on the floor, and were about to go down and dig."),
    ('وسمعوا صوت.', "And they heard a sound."),
    ('الباب تحت.', "The door below."),
    ('همس توم: أشباح؟', "Tom whispered: ghosts?"),
    ('همس هَك: بالنهار؟', "Huck whispered: by day?"),
    ('وتمددوا عالأرض، وطلوا من شق بين الألواح.', "And they lay on the floor, and looked through a crack between the boards.")),
  P(('رجلين.', "Two men."),
    ('واحد ما شافوه قبل، وسخ، وعجوز.', "One they had not seen before, dirty, and old."),
    ('والتاني، الأطرش الأخرس اللي بيمشي بالقرية من أسبوع.', "And the other, the deaf-mute who had been walking the village for a week."),
    ('لابس تياب إسباني، وشعره طويل.', "In Spanish clothes, with long hair."),
    ('وقعدوا تحت، وبلشوا يحكوا.', "And they sat below, and began to talk."),
    ('والأطرش الأخرس حكى.', "And the deaf-mute spoke."),
    ('وصوته كان صوت جو الهندي.', "And his voice was Injun Joe's voice."),
    ('وتوم وهَك، فوق، ما تنفسوا.', "And Tom and Huck, above, did not breathe."))]),

 ('The Box of Gold', 'صندوق الذهب', [
  P(('قال جو الهندي: الشغلة الأخيرة، وبعدها بنروح على تكساس.', "Injun Joe said: the last job, and after it we go to Texas."),
    ('قال العجوز: الشغلة خطرة. القرية كلها بتعرف وجهك.', "The old man said: the job is dangerous. The whole village knows your face."),
    ('قال جو الهندي: ما بعرفوني هيك. وأنا ما برجع لتكساس قبل ما آخد حقي.', "Injun Joe said: they do not know me like this. And I do not go to Texas before I take my due."),
    ('وحكوا عن مصاري مخبيينها، ستمية دولار، وبدهم يدفنوها بالبيت.', "And they talked of money they had hidden, six hundred dollars, and wanting to bury it in the house."),
    ('وجو الهندي قام يحفر بالزاوية، بسكينته.', "And Injun Joe got up to dig in the corner, with his knife."),
    ('وفوق، توم وهَك، بيسمعوا، وبيحلموا بالستمية.', "And above, Tom and Huck, listening, dreaming of the six hundred.")),
  P(('وبعدين وقفت السكينة على إشي.', "And then the knife struck something."),
    ('قال جو: خشب.', "Joe said: wood."),
    ('وحفروا بالفأس، وطلعوا صندوق.', "And they dug with the pick, and brought up a box."),
    ('صندوق حديد قديم، تقيل، ومقفول.', "An old iron box, heavy, and locked."),
    ('وكسروا القفل، وفتحوه.', "And they broke the lock, and opened it."),
    ('ذهب.', "Gold."),
    ('صندوق كامل من العملات الذهبية، آلاف، بتلمع بالغبار.', "A whole box of gold coins, thousands, shining in the dust."),
    ('قال العجوز: هاي كنز عصابة موريل! كانوا هون من سنين!', "The old man said: this is the Murrell gang's treasure! They were here years ago!"),
    ('وقال جو الهندي: هلق مش لازم نعمل الشغلة الأخيرة.', "And Injun Joe said: now we do not need to do the last job."),
    ('وبعدين قال: لا. بعملها. الشغلة مش عشان المصاري. الشغلة انتقام.', "And then he said: no. I do it. The job is not for money. The job is revenge.")),
  P(('وبهاللحظة، جو الهندي شاف الفأس.', "And in that moment, Injun Joe saw the pick."),
    ('فأس جديد، وعليه تراب طري.', "A new pick, with fresh earth on it."),
    ('قال: مين جاب هالفأس؟', "He said: who brought this pick?"),
    ('وتطلع بالدرج.', "And he looked at the stairs."),
    ('وتوم وهَك، فوق، سمعوا الخشب بيصر، وهو طالع.', "And Tom and Huck, above, heard the wood creak, as he climbed."),
    ('درجة. درجتين. تلاتة.', "One step. Two. Three."),
    ('وفكروا يقفزوا من الشباك، بس ما قدروا يتحركوا.', "And they thought of jumping from the window, but could not move.")),
  P(('وبالدرجة الرابعة، انكسر الخشب العفن.', "And on the fourth step, the rotten wood broke."),
    ('ووقع جو الهندي لتحت، على العجوز.', "And Injun Joe fell down, onto the old man."),
    ('وقام وهو بيشتم، وقال: خلص. لو في حدا فوق، خليه يضل فوق.', "And he got up cursing, and said: enough. If there is anyone up there, let him stay up there."),
    ('واللي بده ينزل، بينزل.', "And whoever wants to come down, comes down."),
    ('وأخدوا الصندوق، وقال جو: ما بنخبيه هون. بنوديه على رقم اتنين، تحت الصليب.', "And they took the box, and Joe said: we do not hide it here. We take it to Number Two, under the cross."),
    ('وطلعوا مع الغروب، ومعهم الذهب.', "And they went out at sunset, with the gold."),
    ('وتوم وهَك نزلوا بعد ساعة، وإجريهم بترجف.', "And Tom and Huck came down an hour later, their legs shaking."),
    ('وقال توم: رقم اتنين. تحت الصليب. لازم نلاقيه.', "And Tom said: Number Two. Under the cross. We must find it."))]),

 ('Number Two', 'رقم اتنين', [
  P(('رقم اتنين. شو رقم اتنين؟', "Number Two. What is Number Two?"),
    ('بيت؟ ما في بيوت بأرقام بالقرية.', "A house? There are no numbered houses in the village."),
    ('قال هَك: أوضة! بالفندق!', "Huck said: a room! At the inn!"),
    ('بالقرية فندقين، وبكل فندق أوضة رقم اتنين.', "In the village there were two inns, and in each inn a room number two."),
    ('بالفندق الأول، الأوضة لمحامي شاب، وما فيها سر.', "At the first inn, the room belonged to a young lawyer, and held no secret."),
    ('بالفندق التاني، الأوضة مقفولة دايماً.', "At the second inn, the room was always locked."),
    ('وابن صاحب الفندق قال لتوم: ما حدا بيفوت عليها إلا بالليل. وشفت ضو فيها.', "And the innkeeper's son told Tom: no one goes in except at night. And I saw a light in it."),
    ('قال توم: هاي هي.', "Tom said: that is it.")),
  P(('الأوضة إلها باب من الخلف، على زقاق ضيق.', "The room had a back door, onto a narrow alley."),
    ('وعملوا خطة: هَك بيراقب الزقاق كل ليلة، وتوم بيجرب المفاتيح.', "And they made a plan: Huck watches the alley every night, and Tom tries the keys."),
    ('جمع توم كل مفاتيح الخالة بولي، وكل مفتاح لقاه.', "Tom gathered all Aunt Polly's keys, and every key he could find."),
    ('وبليلة عتمة، بلا قمر، راح للباب الخلفي، وجرب.', "And on a dark night, with no moon, he went to the back door, and tried."),
    ('مفتاح، ومفتاح، ومفتاح.', "Key after key after key."),
    ('وبعدين لمس الباب، وكان مفتوح.', "And then he touched the door, and it was open.")),
  P(('دخل، على مهل، وهَك برا بيراقب.', "He went in, slowly, with Huck outside watching."),
    ('وبعد ثانية، طلع توم راكض، وصرخ: اركض!', "And a second later, Tom came out running, and shouted: run!"),
    ('وركضوا لحد المصنع المهجور، ووقفوا يلهثوا.', "And they ran to the abandoned tannery, and stood panting."),
    ('قال هَك: شو شفت؟', "Huck said: what did you see?"),
    ('قال توم: جو الهندي! نايم عالأرض، وجنبه قنينة، وذراعه مفتوحة.', "Tom said: Injun Joe! Asleep on the floor, a bottle beside him, his arm flung out."),
    ('كدت أدعس على إيده.', "I nearly stepped on his hand."),
    ('قال هَك: والصندوق؟', "Huck said: and the box?"),
    ('قال توم: ما شفت صندوق. شفت جو الهندي بس، وهرب كل إشي من راسي.', "Tom said: I saw no box. I saw only Injun Joe, and everything fled from my head.")),
  P(('قال توم: إذا هو سكران، الصندوق بالأوضة. ولازم نرجع.', "Tom said: if he is drunk, the box is in the room. And we must go back."),
    ('قال هَك: أنا ما برجع.', "Huck said: I am not going back."),
    ('قال توم: مش الليلة. بس هَك، إنت راقب الزقاق.', "Tom said: not tonight. But Huck, you watch the alley."),
    ('إذا شفته طالع ومعه الصندوق، تعال موء تحت شباكي.', "If you see him leave with the box, come and meow under my window."),
    ('وإذا ما طلع، أنا برجع.', "And if he does not leave, I go back."),
    ('واتفقوا، وصار هَك ينام بالنهار، ويراقب بالليل.', "And they agreed, and Huck began sleeping by day, and watching by night."),
    ('ليلة، وليلتين، وتلاتة.', "One night, two, three."))]),

 ('Huck Saves the Widow', 'هَك بينقذ الأرملة', [
  P(('بالليلة الرابعة، انفتح الباب الخلفي.', "On the fourth night, the back door opened."),
    ('وطلع منه جو الهندي والعجوز، وبإيدهم إشي.', "And out of it came Injun Joe and the old man, with something in their hands."),
    ('مش صندوق. أزغر.', "Not a box. Smaller."),
    ('ومشوا بالزقاق، وهَك وراهم، حافي، زي القطة.', "And they walked down the alley, and Huck after them, barefoot, like a cat."),
    ('مشوا للتلة، باتجاه بيت الأرملة دوغلاس.', "They walked to the hill, toward the Widow Douglas's house."),
    ('وهَك فكر: بيدفنوا الكنز عند الأرملة؟', "And Huck thought: are they burying the treasure at the widow's?")),
  P(('ووقفوا تحت شجرة، قريب من البيت، وهَك وقف ورا شجيرة، وسمع.', "And they stopped under a tree, near the house, and Huck stood behind a bush, and listened."),
    ('قال العجوز: في ضو بالبيت. في ناس عندها.', "The old man said: there is a light in the house. She has people over."),
    ('قال جو الهندي: بنستنى لحد ما يروحوا.', "Injun Joe said: we wait until they leave."),
    ('قال العجوز: يا جو، خلينا نترك هالشغلة. الأرملة ما عملت لك إشي.', "The old man said: Joe, let us leave this job. The widow did nothing to you."),
    ('قال جو الهندي: زوجها. زوجها كان القاضي، وحكم عليّ بالجلد، قدام القرية.', "Injun Joe said: her husband. Her husband was the judge, and sentenced me to the whip, before the village."),
    ('هو مات. وهي رح تدفع بداله.', "He is dead. And she will pay instead of him."),
    ('وما بدي أقتلها. بدي أشوه وجهها.', "And I do not want to kill her. I want to cut her face.")),
  P(('هَك ما استنى يسمع الباقي.', "Huck did not wait to hear the rest."),
    ('رجع لورا، على مهل، وبعدين ركض.', "He backed away, slowly, and then ran."),
    ('ركض عالتلة لبيت الويلزي، الرجل الكبير اللي عنده ولدين.', "He ran up the hill to the Welshman's house, the old man with two sons."),
    ('ودق الباب بإيديه، وصرخ: افتحوا! افتحوا بسرعة!', "And he pounded the door with his hands, and shouted: open! Open quickly!"),
    ('فتح الويلزي، وقال: مين إنت؟', "The Welshman opened, and said: who are you?"),
    ('قال هَك: هَك فِن. ما تحكي لحدا إني جيت. بس اسمع.', "Huck said: Huck Finn. Do not tell anyone I came. But listen."),
    ('وحكى كل إشي.', "And he told everything.")),
  P(('الويلزي وولاده أخدوا بنادقهم، وطلعوا بالعتمة.', "The Welshman and his sons took their guns, and went out into the dark."),
    ('وهَك ركض وراهم لحد الشجيرة، ووقف، وسمع.', "And Huck ran after them as far as the bush, and stopped, and listened."),
    ('صمت. وبعدين صوت بنادق، وصراخ، وأقدام بتركض.', "Silence. And then the sound of guns, and shouts, and running feet."),
    ('وهَك ما استنى. ركض عالتلة لتحت، وما وقف لحد القرية.', "And Huck did not wait. He ran down the hill, and did not stop until the village."),
    ('وبالصبح، القرية كلها عرفت.', "And in the morning, the whole village knew."),
    ('حدا هجم على الأرملة، والويلزي طردهم.', "Someone had attacked the widow, and the Welshman had driven them off."),
    ('بس ما حدا عرف مين اللي حذر الويلزي.', "But no one knew who had warned the Welshman."),
    ('غير الويلزي، وهو حلف يسكت.', "Except the Welshman, and he had sworn to keep quiet."))]),

 ('The Picnic', 'الرحلة', [
  P(('بنفس اليوم، بيكي عملت رحلة لكل أولاد الصف.', "That same day, Becky held a picnic for all the children of the class."),
    ('باخرة، ونهر، وأكل، ومغارة.', "A steamboat, the river, food, and a cave."),
    ('والأمهات قالوا: الأولاد بيناموا عند أصحابهم بعد الرحلة.', "And the mothers said: the children sleep at friends' houses after the picnic."),
    ('عشان ما يرجعوا بالليل.', "So they do not come back at night."),
    ('وتوم راح، طبعاً، وبيكي جنبه، والخطوبة رجعت زي ما كانت.', "And Tom went, of course, with Becky beside him, and the engagement was back as it had been."),
    ('وركبوا الباخرة، ونزلوا عند المغارة الكبيرة.', "And they boarded the steamboat, and got off at the big cave.")),
  P(('مغارة ماكدوغال: باب زغير بالجبل.', "McDougal's Cave: a small door in the mountain."),
    ('وجواتها ممرات وأوض وطرق بلا نهاية.', "And inside, passages and chambers and paths without end."),
    ('كل ولد بيعرف أول كم ممر.', "Every child knew the first few passages."),
    ('وما حدا بيعرف آخرها، لأنه ما حدا وصل لآخرها.', "And no one knew the end of it, because no one had reached the end."),
    ('دخلوا بالشمع، وصار كل واحد يركض بممر، ويصرخ، ويضحك.', "They went in with candles, and each ran down a passage, shouting, laughing."),
    ('والصوت بيرجع من الحيطان، والظل بيرقص.', "And the sound echoed from the walls, and the shadows danced."),
    ('وتوم وبيكي مشوا سوا، أبعد شوي من الباقي.', "And Tom and Becky walked together, a little farther than the rest.")),
  P(('وبعدين أبعد.', "And then farther."),
    ('لقوا ممر ما فيه أسماء عالحيط، يعني ما حدا وصل له.', "They found a passage with no names on the wall, meaning no one had reached it."),
    ('وتوم كتب اسمه واسمها بالشمع.', "And Tom wrote his name and hers in candle smoke."),
    ('ولقوا نبع، وبحيرة زغيرة، وسقف فيه أحجار بتلمع زي النجوم.', "And they found a spring, a small lake, and a ceiling with stones shining like stars."),
    ('وقالت بيكي: توم، صار لنا كتير. خلينا نرجع.', "And Becky said: Tom, it has been a long time. Let us go back."),
    ('وقال توم: طيب.', "And Tom said: fine."),
    ('ومشوا لورا.', "And they walked back.")),
  P(('ومشوا. ومشوا.', "And they walked. And walked."),
    ('وما شافوا الأسماء عالحيط.', "And did not see the names on the wall."),
    ('قال توم: من هون. لا، من هون.', "Tom said: this way. No, this way."),
    ('وكل ممر بيشبه اللي قبله.', "And every passage looked like the one before."),
    ('وبيكي قالت: توم، إحنا ضايعين؟', "And Becky said: Tom, are we lost?"),
    ('وتوم قال: لا.', "And Tom said: no."),
    ('بس كان.', "But they were."),
    ('وبعيد، عالباخرة، الأولاد ركبوا ورجعوا.', "And far off, at the steamboat, the children boarded and went home."),
    ('وكل واحد فكر إن توم وبيكي عند حدا تاني.', "And everyone thought Tom and Becky were with someone else."))]),

 ('Lost in the Cave', 'ضايعين بالمغارة', [
  P(('بيكي بكت، وتوم قال: بيكي، بنلاقي الطريق. صدقيني.', "Becky cried, and Tom said: Becky, we will find the way. Trust me."),
    ('وصرخ: يا ناس! والصوت رجع من العتمة، زي ضحكة.', "And he shouted: hey, people! And the sound came back from the dark, like a laugh."),
    ('ومشوا، وتوم بيمسك إيدها، وبيتطلع بكل ممر.', "And they walked, Tom holding her hand, looking down every passage."),
    ('وبعدين لاحظ الشمعة.', "And then he noticed the candle."),
    ('كانت نص شمعة، وبعدها بيكي معها شمعة وحدة.', "It was half a candle, and after it Becky had one candle."),
    ('وبعدها، عتمة.', "And after that, darkness.")),
  P(('قعدوا عند نبع، وأكلوا آخر قطعة كعك، وبيكي نامت على كتفه.', "They sat by a spring, ate the last piece of cake, and Becky slept on his shoulder."),
    ('وتوم قعد يتطلع بالشمعة، وهي بتنزل.', "And Tom sat watching the candle, as it went down."),
    ('ولما فاقت بيكي، قالت: توم، أنا كنت بالبيت بالحلم.', "And when Becky woke, she said: Tom, I was at home in the dream."),
    ('وتوم قال: بيكي، ما بعرف كم صار الوقت. يمكن أهلنا صاروا يدوروا علينا.', "And Tom said: Becky, I do not know what time it is. Maybe our people are looking for us by now."),
    ('وقالت بيكي: يمكن. بس أهلنا بيفكرونا عند حدا.', "And Becky said: maybe. But our people think we are with someone."),
    ('وسكتوا، وفهموا إنه لحد بكرا، ما حدا بيدور.', "And they were silent, and understood that until tomorrow, no one would search.")),
  P(('وانطفت الشمعة الأخيرة.', "And the last candle went out."),
    ('عتمة. عتمة ما شافوا زيها بحياتهم.', "Darkness. A darkness they had never seen in their lives."),
    ('لا يد، ولا وجه، ولا فرق بين مفتوح العين ومسكرها.', "No hand, no face, no difference between eyes open and eyes closed."),
    ('بيكي بكت، وتوم قعد جنبها، ومسك إيدها، وما حكى.', "Becky cried, and Tom sat beside her, held her hand, and said nothing."),
    ('وبعد ساعات، أو أيام، ما بيعرفوا، سمعوا صوت.', "And after hours, or days, they could not tell, they heard a sound."),
    ('بعيد. صياح. ناس.', "Far off. Shouting. People."),
    ('توم صرخ، وصرخ، وركضوا بالعتمة باتجاه الصوت.', "Tom shouted, and shouted, and they ran in the dark toward the sound."),
    ('ووقعوا بحفرة، وطلعوا، والصوت راح.', "And they fell into a hole, and climbed out, and the sound was gone.")),
  P(('رجعوا للنبع، لأنه النبع الإشي الوحيد اللي بيعرفوه.', "They went back to the spring, because the spring was the only thing they knew."),
    ('وتوم طلع من جيبه خيط طيارة، طويل.', "And Tom took from his pocket a kite string, long."),
    ('ربط طرفه بصخرة عند النبع، وقال: بيكي، خليكي هون.', "He tied its end to a rock by the spring, and said: Becky, stay here."),
    ('أنا بروح بالممرات، والخيط بيرجعني لك.', "I go through the passages, and the string brings me back to you."),
    ('قالت: لا تروح بعيد.', "She said: do not go far."),
    ('وراح، بالعتمة، وإيده عالحيط، والخيط بيتفك وراه.', "And he went, in the dark, his hand on the wall, the string unwinding behind him."))]),

 ('A Face in the Dark', 'وجه بالعتمة', [
  P(('مشى توم بممر، والخيط بيخلص، ورجع.', "Tom went down a passage, the string ran out, and he came back."),
    ('ومشى بممر تاني، ورجع.', "And down a second passage, and came back."),
    ('وبالممر التالت، شاف ضو.', "And in the third passage, he saw a light."),
    ('ضو زغير، بعيد، بيتحرك.', "A small light, far off, moving."),
    ('وقلبه نط، وصرخ: هون! إحنا هون!', "And his heart leapt, and he shouted: here! We are here!"),
    ('والضو وقف، وقرب، ولف الزاوية.', "And the light stopped, and came near, and turned the corner."),
    ('وشاف توم الوجه ورا الشمعة.', "And Tom saw the face behind the candle.")),
  P(('جو الهندي.', "Injun Joe."),
    ('واقف بالعتمة، والشمعة بإيده، ووجهه يلمع.', "Standing in the dark, the candle in his hand, his face shining."),
    ('وتوم وقف مكانه، ما بيقدر يتحرك، ولا يتنفس.', "And Tom stood where he was, unable to move, or breathe."),
    ('وجو الهندي تطلع بالعتمة، باتجاه الصوت.', "And Injun Joe looked into the dark, toward the sound."),
    ('وبعدين لف، وركض، واختفى.', "And then he turned, and ran, and vanished."),
    ('كان خايف. جو الهندي خايف.', "He was afraid. Injun Joe afraid."),
    ('لأنه ما عرف مين اللي صرخ، وبالمغارة، الصوت بيخوف كل واحد.', "Because he did not know who had shouted, and in the cave, a voice frightens everyone.")),
  P(('رجع توم لبيكي على الخيط، وما حكى لها.', "Tom went back to Becky along the string, and did not tell her."),
    ('قال: ما لقيت إشي. بجرب كمان مرة.', "He said: I found nothing. I will try once more."),
    ('وبيكي كانت صارت ضعيفة، وما بتحكي كتير.', "And Becky had grown weak, and did not talk much."),
    ('قالت: توم، إذا مت، خليك جنبي.', "She said: Tom, if I die, stay beside me."),
    ('وقال توم: ما بتموتي. وراح.', "And Tom said: you will not die. And he went."),
    ('وهالمرة، أخد ممر رابع، ما جربه.', "And this time, he took a fourth passage, one he had not tried."),
    ('ومشى، ومشى، والخيط بيخلص.', "And he walked, and walked, and the string ran out.")),
  P(('وبآخر الخيط، شاف إشي.', "And at the end of the string, he saw something."),
    ('مش ضو شمعة. ضو تاني.', "Not candlelight. Another light."),
    ('رمادي، وبعيد، وثابت.', "Grey, far off, and steady."),
    ('ترك الخيط، وزحف باتجاهه.', "He left the string, and crawled toward it."),
    ('وكان شق بالصخر، زغير، قد ما يمرق ولد.', "And it was a crack in the rock, small, just enough for a boy to pass."),
    ('وطلع منه، ووقع على عشب.', "And he came out of it, and fell onto grass."),
    ('وفوقه السما، والنهر تحته، والشمس عم تغيب.', "And above him the sky, the river below, the sun setting."),
    ('وبكى توم، لأول مرة من يومين.', "And Tom cried, for the first time in two days."))]),

 ('Out of the Hill', 'من جوف الجبل', [
  P(('رجع توم بالشق، وزحف على الخيط، لحد بيكي.', "Tom went back through the crack, crawled along the string, to Becky."),
    ('قال: بيكي، لقيت الطريق. في شمس. في نهر.', "He said: Becky, I found the way. There is sun. There is a river."),
    ('وبيكي ما صدقت، وبعدين صدقت، وبكت.', "And Becky did not believe, and then believed, and cried."),
    ('ومشوا سوا، على الخيط، وبعدين بالشق، وطلعوا.', "And they walked together, along the string, then through the crack, and came out."),
    ('كان الليل.', "It was night."),
    ('وشافوا مركب عالنهر، وصرخوا، والمركب إجا.', "And they saw a boat on the river, and shouted, and the boat came."),
    ('والرجال اللي فيه ما صدقوا.', "And the men in it could not believe it."),
    ('لأنه الشق كان خمسة ميل بعيد عن باب المغارة.', "Because the crack was five miles from the cave's door.")),
  P(('وبالقرية، صار لها تلات أيام عم تدور.', "And in the village, they had been searching for three days."),
    ('كل الرجال بالمغارة، بالشمع والحبال، بيصرخوا بالممرات.', "All the men in the cave, with candles and ropes, shouting down the passages."),
    ('والخالة بولي ما تركت السرير، وشعرها صار أبيض بتلات أيام.', "And Aunt Polly had not left her bed, and her hair had gone white in three days."),
    ('وأم بيكي كمان.', "And Becky's mother too."),
    ('وبنص الليل، دق الجرس، وصرخ الناس بالشوارع: لقوهم! لقوهم!', "And at midnight, the bell rang, and people shouted in the streets: they found them! They found them!"),
    ('والقرية كلها طلعت بتيابها، وبتصرخ، وبتضحك، وبتبكي.', "And the whole village came out in their nightclothes, shouting, laughing, crying.")),
  P(('توم ضل بالفراش أسبوع، وبيكي أكتر.', "Tom stayed in bed a week, and Becky longer."),
    ('وحكى القصة مية مرة، وكل مرة أطول.', "And he told the story a hundred times, each time longer."),
    ('وبعد أسبوعين، راح يزور بيكي، وقابل القاضي تاتشر.', "And after two weeks, he went to visit Becky, and met Judge Thatcher."),
    ('وقال القاضي: توم، ما حدا رح يضيع بهالمغارة بعد اليوم.', "And the judge said: Tom, no one will ever be lost in that cave again."),
    ('قال توم: ليش؟', "Tom said: why?"),
    ('قال القاضي: لأني حطيت على بابها باب حديد.', "The judge said: because I had an iron door put on its mouth."),
    ('وقفلته بتلات أقفال.', "And locked it with three locks."),
    ('من أسبوعين.', "Two weeks ago."),
    ('وتوم صار وجهه أبيض زي الورق.', "And Tom's face went white as paper."),
    ('قال: يا قاضي! جو الهندي جوا!', "He said: judge! Injun Joe is inside!")),
  P(('ركضوا للمغارة، اتناعشر مركب، والقاضي وتوم بالأول.', "They raced to the cave, twelve boats, with the judge and Tom in the first."),
    ('وفتحوا الباب الحديد.', "And they opened the iron door."),
    ('وجو الهندي كان مرمي وراه، على وجهه.', "And Injun Joe lay just behind it, on his face."),
    ('ميت.', "Dead."),
    ('ووجهه للشق تحت الباب، حيث كان الضو بيفوت.', "His face to the gap under the door, where the light came in."),
    ('وسكينته مكسورة، من محاولة يحفر تحت الباب.', "And his knife broken, from trying to dig under the door."),
    ('وحواليه بقايا شمع مأكول، وخفافيش مأكولة.', "And around him the remains of eaten candles, and eaten bats."),
    ('وتوم وقف، وحس بإشي غريب: مش فرح، ومش حزن.', "And Tom stood, and felt something strange: not joy, and not grief."),
    ('حس بالراحة.', "He felt relief."),
    ('ولأول مرة من ليلة المقبرة، نام توم بلا حلم.', "And for the first time since the night of the graveyard, Tom slept without a dream."))]),

 ('The Treasure', 'الكنز', [
  P(('بعد الجنازة، توم راح لهَك.', "After the funeral, Tom went to Huck."),
    ('قال: هَك، الذهب بالمغارة.', "He said: Huck, the gold is in the cave."),
    ('قال هَك: كيف عرفت؟', "Huck said: how do you know?"),
    ('قال توم: رقم اتنين، تحت الصليب. بالمغارة، بالممر اللي شفت فيه جو الهندي، في صليب مرسوم بالدخان عالصخر.', "Tom said: Number Two, under the cross. In the cave, in the passage where I saw Injun Joe, there is a cross drawn in smoke on the rock."),
    ('شفته، وما فهمته وقتها.', "I saw it, and did not understand it then."),
    ('قال هَك: بس الباب مقفول.', "Huck said: but the door is locked."),
    ('قال توم: مش الشق. الشق ما حدا بيعرفه غيري.', "Tom said: not the crack. No one knows the crack but me.")),
  P(('أخدوا شمع وأكياس وطعام، ومركب زغير، ونزلوا عالنهر.', "They took candles and sacks and food, and a small boat, and went down the river."),
    ('وطلعوا من الشق، وزحفوا لجوا، ووصلوا للممر، وللصليب.', "And they went in through the crack, crawled inside, reached the passage, and the cross."),
    ('وتحته صخرة كبيرة. حفروا حواليها، ولقوا فجوة.', "And under it a big rock. They dug around it, and found a hollow."),
    ('وبالفجوة، الصندوق.', "And in the hollow, the box."),
    ('وفتحوه، وعدوا الذهب على ضو الشمع.', "And they opened it, and counted the gold by candlelight."),
    ('اتناعشر ألف دولار.', "Twelve thousand dollars."),
    ('أكتر مما شافته القرية كلها بحياتها.', "More than the whole village had seen in its life.")),
  P(('طلعوا الذهب بالأكياس، وحملوه للمركب، ورجعوا القرية بالليل.', "They carried the gold out in the sacks, took it to the boat, and returned to the village at night."),
    ('وبالطريق، مسكهم الويلزي، وقال: تعالوا، الأرملة عاملة حفلة.', "And on the way, the Welshman caught them, and said: come, the widow is giving a party."),
    ('وبالحفلة، الأرملة قالت قدام الكل: هَك فِن أنقذ حياتي.', "And at the party, the widow said before everyone: Huck Finn saved my life."),
    ('لأنه الويلزي حكى بالآخر.', "Because the Welshman had told in the end."),
    ('وقالت: وأنا رح آخده يعيش عندي، وأعلمه، وأدخله الكنيسة.', "And she said: and I will take him to live with me, and educate him, and bring him to church."),
    ('وهَك صار وجهه أحمر، وحس إن الحياة انتهت.', "And Huck's face went red, and he felt life had ended."),
    ('وتوم قال: هَك مش فقير! هَك غني!', "And Tom said: Huck is not poor! Huck is rich!"),
    ('وضحك الكل، وتوم طلع، ورجع بالأكياس، وكبها عالطاولة.', "And everyone laughed, and Tom went out, came back with the sacks, and poured them on the table.")),
  P(('وصار الذهب بالبنك، نص لتوم ونص لهَك.', "And the gold went into the bank, half for Tom and half for Huck."),
    ('والقاضي تاتشر قال إنه توم رح يصير محامي أو جنرال.', "And Judge Thatcher said Tom would become a lawyer or a general."),
    ('وهَك عاش عند الأرملة تلات أسابيع.', "And Huck lived at the widow's for three weeks."),
    ('تياب نضيفة، وشوكة وسكينة، وسرير، وكنيسة.', "Clean clothes, a knife and fork, a bed, and church."),
    ('وبعدين اختفى.', "And then he vanished."),
    ('وتوم لقاه بعد تلات أيام، ببرميله القديم.', "And Tom found him three days later, in his old barrel."),
    ('بتيابه القديمة، وغليونه.', "In his old clothes, with his pipe."),
    ('قال هَك: يا توم، الغنى مش لي. أنا ما بقدر أتنفس بالبيوت.', "Huck said: Tom, riches are not for me. I cannot breathe in houses."),
    ('قال توم: هَك، إذا ما رجعت للأرملة، في مشكلة.', "Tom said: Huck, if you do not go back to the widow, there is a problem."),
    ('ما بقدر آخدك بعصابتي الجديدة.', "I cannot take you into my new gang."),
    ('العصابة كلها ناس محترمين.', "The gang is all respectable people."),
    ('وفكر هَك طويل، وقال: طيب. برجع. بس شهر.', "And Huck thought a long time, and said: fine. I go back. But for a month."),
    ('وهيك بتخلص قصة توم سوير.', "And so ends the story of Tom Sawyer."),
    ('لأنه قصة ولد، ولما بيكبر الولد، بتصير قصة تانية.', "Because it is a boy's story, and when the boy grows up, it becomes another story."))]),
]

if __name__ == '__main__':
    raise SystemExit(book(BOOK_ID, BOOK_TITLE, 'intermediate', CHAPTERS, shelf=14,
              meta={'work': 'The Adventures of Tom Sawyer', 'author': 'Mark Twain',
                    'year': '1876', 'status': 'public domain'}))
