#!/usr/bin/env python3
"""عشرون قصة — ten Maupassant and ten Chekhov stories, retold in spoken Palestinian, advanced.

Guy de Maupassant died in 1893 and Anton Chekhov in 1904; both are long out of copyright, and the
originals are French and Russian. These are retellings from the plots, so no English translation
is involved either — worth stating, because many modern translations of Chekhov are still in
copyright even though Chekhov is not.

WHY THESE CLOSE THE SHELF. Phase 6's milestone is being warm, funny and diplomatic — recognizably
yourself. Holmes trains following an argument; these train the other half: what people do about
pride, money, embarrassment and loneliness, and what they say instead of what they mean. A woman
ruins her life over a necklace she was too proud to ask about. A man is believed to be a thief and
dies still explaining. A cabman whose son has died cannot find one person who will listen, and
tells the horse.

Nothing here has a detective or a moral. That is the point at this level: the reader has to decide
what happened, and Arabic gives them no more help than French or Russian did.

One story per chapter, each complete in a sitting. Maupassant first, then Chekhov, and each half
runs from the lighter stories to the heavier ones.

LEVEL. Written near the advanced short-story baseline (34 characters a sentence), and deliberately
watching the 90th percentile — the Holmes book needed twelve long sentences split after the fact,
so these were written in shorter beats from the start.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_shortstories.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, emit_book

BOOK_ID = 'shortstories'
BOOK_TITLE = {'en': 'Twenty Stories: Maupassant & Chekhov', 'ar': 'عشرون قصة: موباسان وتشيخوف'}

# (english title, arabic title, [paragraph, ...])
CHAPTERS = [
 # ---------------- Maupassant ----------------
 ('Fat and Thin at the Station', 'صاحبين بالمحطة', [
  P(('اتنين أصحاب من أيام المدرسة التقوا بالمحطة.',
     'Two friends from their school days met at the station.'),
    ('تعانقوا وصاروا يضحكوا ويتذكروا.',
     'They embraced and began laughing and remembering.')),
  P(('سأل الأول: وإنت شو صار معك بالحياة؟',
     'The first asked: and what has become of you in life?'),
    ('قال التاني: موظف بسيط، وعندي ولد.',
     'The second said: a small clerk, and I have a son.'),
    ('وإنت؟', 'And you?')),
  P(('قال الأول باستحياء: صرت مدير عام.',
     'The first said shyly: I have become a director.'),
    ('وجه صاحبه تغير بلحظة.', 'His friend’s face changed in an instant.')),
  P(('صار يقول: يا سيدي، وتشرفنا، وإحنا تحت أمرك.',
     'He began saying: my lord, and honoured, and we are at your service.'),
    ('المدير حاول يوقفه وما قدر.',
     'The director tried to stop him and could not.')),
  P(('سلموا على بعض بأطراف أصابعهم.',
     'They shook hands with the tips of their fingers.'),
    ('وكل واحد راح لجهة.', 'And each went his own way.'),
    ('الصداقة اللي عاشت عشرين سنة ماتت بجملة وحدة.',
     'A friendship of twenty years died in one sentence.'))]),

 ('The Umbrella', 'الشمسية', [
  P(('كان في مرا بتحسب كل قرش.', 'There was a woman who counted every penny.'),
    ('زوجها موظف وراتبه محدود.', 'Her husband was a clerk with a limited salary.')),
  P(('اشترت له شمسية غالية بعد نقاش طويل.',
     'She bought him an expensive umbrella after a long argument.'),
    ('بعد شهر، رجع والشمسية فيها حروق زغيرة.',
     'A month later, he came back with small burns in it.')),
  P(('صارت تصرخ وهو بيحلف إنه ما بيعرف.',
     'She started shouting and he swore he did not know how.'),
    ('قالت: زملاءك عاملينها بالقصد.',
     'She said: your colleagues did it on purpose.')),
  P(('راحت عالشركة اللي مأمنة عالبيت.',
     'She went to the company that insured the house.'),
    ('قعدت قدام الموظف وحكت القصة كلها.',
     'She sat before the clerk and told the whole story.')),
  P(('الموظف حاول يفهم شو علاقة الشمسية بالحريق.',
     'The clerk tried to understand what the umbrella had to do with a fire.'),
    ('بالآخر دفعوا لها عشان تسكت وتطلع.',
     'In the end they paid her so she would be quiet and leave.'),
    ('طلعت وهي مبسوطة، ورجعت عالبيت تحسب.',
     'She left pleased, and went home to count.'))]),

 ('The Piece of String', 'قطعة الخيط', [
  P(('بيوم سوق، رجل عجوز شاف خيط عالأرض.',
     'On a market day, an old man saw a piece of string on the ground.'),
    ('انحنى وأخذه ودسه بجيبه.',
     'He bent down, took it and tucked it in his pocket.')),
  P(('واحد بيكرهه شافه وهو ينحني.',
     'A man who disliked him saw him bending.'),
    ('بنفس اليوم، ضاعت محفظة بالسوق.',
     'That same day, a wallet was lost in the market.')),
  P(('الرجل اللي بيكرهه راح عالشرطة وحكى.',
     'The man who disliked him went to the police and spoke.'),
    ('استدعوا العجوز، وهو طلّع الخيط من جيبه.',
     'They summoned the old man, and he took the string from his pocket.'),
    ('محدا صدقه.', 'Nobody believed him.')),
  P(('بعد أيام، رجعت المحفظة ولقوها.',
     'After days, the wallet came back and was found.'),
    ('بس الناس ضلوا يحكوا: هو دبرها.',
     'But people went on saying: he arranged it.')),
  P(('العجوز صار يشرح لكل واحد بيقابله.',
     'The old man began explaining to everyone he met.'),
    ('كل ما يشرح أكتر، كل ما صدقوه أقل.',
     'The more he explained, the less they believed him.'),
    ('مرض ومات وهو لسا بيقول: كان خيط.',
     'He fell ill and died still saying: it was a piece of string.'))]),

 ('The Necklace', 'العقد', [
  P(('مرا حلوة كانت متجوزة موظف بسيط.',
     'A beautiful woman was married to a modest clerk.'),
    ('كانت تحلم بحياة تانية طول الوقت.',
     'She dreamed of another life all the time.')),
  P(('زوجها جاب دعوة لحفلة كبيرة.',
     'Her husband brought an invitation to a great party.'),
    ('قالت: ما عندي إشي ألبسه.', 'She said: I have nothing to wear.'),
    ('صرف عليها كل اللي كان مجمعه.',
     'He spent on her everything he had saved.')),
  P(('واستعارت عقد ألماس من صاحبتها الغنية.',
     'And she borrowed a diamond necklace from her wealthy friend.'),
    ('بالحفلة، كانت أحلى وحدة، ورقصت لآخر الليل.',
     'At the party, she was the loveliest there, and danced till the night’s end.')),
  P(('وهي راجعة، اكتشفت إن العقد ضاع.',
     'On the way back, she discovered the necklace was gone.'),
    ('استلفوا مصاري كتيرة واشتروا عقد مثله.',
     'They borrowed a great deal of money and bought one like it.')),
  P(('عشر سنين اشتغلت خدامة تسدد الدين.',
     'For ten years she worked as a maid to pay the debt.'),
    ('يدينها خشنت ووجهها كبر قبل وقته.',
     'Her hands grew rough and her face aged before its time.')),
  P(('بيوم، قابلت صاحبتها بالشارع.',
     'One day, she met her friend in the street.'),
    ('حكت لها كل إشي وهي فخورة إنها سددت.',
     'She told her everything, proud that she had paid it off.'),
    ('صاحبتها قالت لها: بس عقدي كان مقلد.',
     'Her friend said to her: but my necklace was false.'))]),

 ('My Uncle Jules', 'عمي جول', [
  P(('عيلتنا كانت فقيرة، وكل الأمل بعمي جول.',
     'Our family was poor, and all our hope was in my uncle Jules.'),
    ('كان سافر لأمريكا وبعت مكتوب إنه صار غني.',
     'He had gone to America and written that he had become rich.')),
  P(('أبوي كان يقرا المكتوب لكل ضيف بيجي.',
     'My father used to read the letter to every guest who came.'),
    ('وكل مرة نشوف مركب بنقول: بلكي هو.',
     'And every time we saw a boat we said: perhaps that is him.')),
  P(('بيوم، طلعنا برحلة بحرية زغيرة.',
     'One day, we went on a small sea trip.'),
    ('كان في رجل عجوز بيفتح المحار للركاب.',
     'There was an old man opening oysters for the passengers.')),
  P(('أبوي تطلع فيه طويل وشحب وجهه.',
     'My father looked at him a long time and went pale.'),
    ('راح على الكابتن وسأله عنه بهدوء.',
     'He went to the captain and asked about him quietly.'),
    ('الكابتن قال: هاد مسكين، اسمه جول.',
     'The captain said: that is a poor wretch, his name is Jules.')),
  P(('أمي قالت: لا تقربوا منه، ولا تحكوا.',
     'My mother said: do not go near him, and do not speak.'),
    ('أنا رحت أدفع له تمن المحار.',
     'I went to pay him for the oysters.'),
    ('حطيت المصاري بإيده وتطلعت بوجهه.',
     'I put the money in his hand and looked at his face.')),
  P(('رجعنا بمركب تاني عشان ما نشوفه.',
     'We came back by a different boat so as not to see him.'),
    ('من يومها، ما حدا ذكر اسم عمي جول.',
     'From that day, nobody mentioned my uncle Jules’s name.'))]),

 ('The Jewels', 'المجوهرات', [
  P(('رجل تجوز مرا بسيطة وطيبة وكل الناس حبتها.',
     'A man married a simple, kind woman whom everyone loved.'),
    ('كان عندها عيب واحد بس بنظره.',
     'She had only one fault in his eyes.')),
  P(('كانت تحب المجوهرات المقلدة.',
     'She loved false jewellery.'),
    ('كل ليلة تقعد تفرجه إياها وتفرح فيها.',
     'Every evening she would sit showing it to him, delighted.')),
  P(('كان يقول لها: هاي مش حقيقية.',
     'He used to say to her: these are not real.'),
    ('وهي تضحك وتقول: بس بتعجبني.',
     'And she would laugh and say: but I like them.')),
  P(('ماتت فجأة بمرض بالصدر.', 'She died suddenly of a chest illness.'),
    ('بعد شهور، ضاق حاله وقرر يبيع المقلد.',
     'After months, he was in straits and decided to sell the false pieces.')),
  P(('التاجر تطلع بالعقد وسأله: من وين هاد؟',
     'The jeweller looked at the necklace and asked: where is this from?'),
    ('قال له: من مرتي.', 'He said to him: from my wife.')),
  P(('التاجر قال: هاد حقيقي، وتمنه كبير كتير.',
     'The jeweller said: this is real, and its price is very great.'),
    ('الرجل قعد عالكرسي وما قدر يحكي.',
     'The man sat on the chair and could not speak.'),
    ('صار غني بيوم، وما عاد يعرف مين كانت مرته.',
     'He became rich in a day, and no longer knew who his wife had been.'))]),

 ('Two Friends', 'صاحبين عالنهر', [
  P(('بأيام الحصار، الأكل كان قليل بباريس.',
     'In the days of the siege, food was scarce in Paris.'),
    ('اتنين أصحاب كانوا يصطادوا سمك قبل الحرب.',
     'Two friends used to fish before the war.')),
  P(('التقوا بالشارع وتذكروا أيام النهر.',
     'They met in the street and remembered the days at the river.'),
    ('قرروا يطلعوا يصطادوا زي زمان.',
     'They decided to go out and fish as they used to.')),
  P(('أخذوا ورقة إذن وطلعوا برا المدينة.',
     'They took a pass and went outside the city.'),
    ('قعدوا عالمي وصاروا يصطادوا ويحكوا.',
     'They sat by the water and began fishing and talking.')),
  P(('السمك كان بيجي، والشمس كانت دافية.',
     'The fish were coming, and the sun was warm.'),
    ('نسيوا الحرب لساعتين.', 'They forgot the war for two hours.')),
  P(('إجوا جنود وأخذوهم.', 'Soldiers came and took them.'),
    ('الضابط قال: أعطوني كلمة السر وبتروحوا.',
     'The officer said: give me the password and you may go.')),
  P(('التنين سكتوا وما حكوا.', 'The two were silent and did not speak.'),
    ('بعدها، الضابط أخذ السمك وقال للطباخ: اقليه.',
     'Afterwards, the officer took the fish and said to the cook: fry it.'))]),

 ('In the Fields', 'بالحقول', [
  P(('بيتين فقيرين جنب بعض، وبكل بيت أربع ولاد.',
     'Two poor houses side by side, four children in each.'),
    ('الولاد كانوا يلعبوا بالتراب سوا.',
     'The children played in the dirt together.')),
  P(('بيوم، وقفت عربة حلوة قدامهم.',
     'One day, a fine carriage stopped in front of them.'),
    ('نزلت منها سيدة وصارت تتطلع بالولاد.',
     'A lady got out and began looking at the children.')),
  P(('قالت لأهل البيت الأول: أعطوني ولد.',
     'She said to the first family: give me a child.'),
    ('بنربيه ويصير غني ويرجع يزوركم.',
     'We will raise him and he will be rich and visit you.'),
    ('أهل البيت الأول طردوها بغضب.',
     'The first family drove her off in anger.')),
  P(('أهل البيت التاني وافقوا وأخذوا مصاري.',
     'The second family agreed and took money.'),
    ('الجيران بطلوا يحكوا معهم سنين.',
     'The neighbours stopped speaking to them for years.')),
  P(('بعد عشرين سنة، رجع الولد برجل وسيم وغني.',
     'After twenty years, the boy came back a fine, wealthy man.'),
    ('البيت التاني احتفل فيه.', 'The second house celebrated him.')),
  P(('ابن البيت الأول تطلع من الشباك وشافه.',
     'The son of the first house looked from the window and saw him.'),
    ('هديك الليلة، ترك البيت وما رجع.',
     'That night, he left the house and did not return.'))]),

 ('The Beggar', 'الشحاد', [
  P(('كان في شحاد أعرج بالضيعة من صغره.',
     'There was a lame beggar in the village from his childhood.'),
    ('الناس اعتادوا عليه وصاروا يمرقوا عنه.',
     'People got used to him and began passing him by.')),
  P(('بيوم شتوي، ما لقى ولا لقمة.',
     'On a winter day, he found not one mouthful.'),
    ('مشي على أربع ضياع وكلهم سكروا الأبواب.',
     'He walked to four villages and all of them shut their doors.')),
  P(('بالآخر، لقى دجاجة بحقل وأخذها.',
     'In the end, he found a hen in a field and took her.'),
    ('أكلها ونام تحت شجرة وهو شبعان لأول مرة.',
     'He ate her and slept under a tree, full for the first time.')),
  P(('الصبح، إجوا الشرطة وأخذوه.',
     'In the morning, the police came and took him.'),
    ('حبسوه بأوضة صغيرة وسكروا الباب.',
     'They locked him in a small room and shut the door.')),
  P(('تاني يوم، فتحوا الباب ولقوه ميت.',
     'The next day, they opened the door and found him dead.'),
    ('واحد منهم قال: عجيب، كان لسا عايش امبارح.',
     'One of them said: strange, he was alive only yesterday.'))]),

 ('Mother Sauvage', 'الأم سوفاج', [
  P(('امرأة عجوز عايشة لحالها ببيت بالغابة.',
     'An old woman lived alone in a house in the forest.'),
    ('ابنها الوحيد كان بالجيش بعيد عنها.',
     'Her only son was in the army far from her.')),
  P(('الجنود الأعداء سكنوا عندها أربعة.',
     'Four enemy soldiers were quartered with her.'),
    ('كانوا شباب، وصاروا يساعدوها بالشغل.',
     'They were young, and began helping her with the work.')),
  P(('كانت تطبخ لهم وهم يجيبوا لها حطب.',
     'She cooked for them and they brought her firewood.'),
    ('واحد فيهم فرجاها صورة أمه.',
     'One of them showed her a picture of his mother.')),
  P(('بيوم، وصلها مكتوب إن ابنها انقتل.',
     'One day, a letter reached her that her son had been killed.'),
    ('قرته مرتين وقعدت ساكتة طول النهار.',
     'She read it twice and sat silent all day.')),
  P(('بالليل، طلبت أسماء الجنود الأربعة وأسماء أمهاتهم.',
     'At night, she asked for the four soldiers’ names and their mothers’ names.'),
    ('كتبتهم على ورقة وحطتها بجيبها.',
     'She wrote them on a paper and put it in her pocket.')),
  P(('وبعدها أشعلت البيت وهم نايمين.',
     'And then she set the house alight while they slept.'),
    ('وقفت برا واستنت الجنود يجوا.',
     'She stood outside and waited for the soldiers to come.'),
    ('أعطتهم الورقة وقالت: قولوا لأمهاتهم مين عملها.',
     'She gave them the paper and said: tell their mothers who did it.'))]),

 # ---------------- Chekhov ----------------
 ('The Death of a Clerk', 'موت موظف', [
  P(('موظف صغير راح عالمسرح وهو مبسوط.',
     'A small clerk went to the theatre in good spirits.'),
    ('بنص العرض، عطس فجأة.', 'In the middle of the performance, he sneezed suddenly.')),
  P(('قدامه كان قاعد جنرال كبير.',
     'In front of him sat an important general.'),
    ('الموظف انحنى وقال: بعتذر منك.',
     'The clerk leaned forward and said: I beg your pardon.'),
    ('الجنرال قال: عادي، ما في إشي.',
     'The general said: it is nothing.')),
  P(('بس الموظف حس إنه ما اقتنع.',
     'But the clerk felt he had not been convinced.'),
    ('بالاستراحة، اعتذر كمان مرة.',
     'At the interval, he apologised again.')),
  P(('تاني يوم، راح عالمكتب واعتذر.',
     'The next day, he went to the office and apologised.'),
    ('واليوم اللي بعده، رجع كمان.',
     'And the day after, he came back again.')),
  P(('بالآخر، الجنرال صرخ فيه: اطلع برا!',
     'In the end, the general shouted at him: get out!'),
    ('الموظف رجع عالبيت ونام عالكنباية.',
     'The clerk went home and lay down on the sofa.'),
    ('وما قام.', 'And he did not get up.'))]),

 ('The Chameleon', 'الحرباء', [
  P(('كلب زغير عض إصبع صايغ بالسوق.',
     'A small dog bit a goldsmith’s finger in the market.'),
    ('إجا شرطي وسأل: كلب مين هاد؟',
     'A policeman came and asked: whose dog is this?')),
  P(('واحد قال: بيشبه كلب الجنرال.',
     'Someone said: it looks like the general’s dog.'),
    ('الشرطي قال على طول: والصايغ أكيد استفزه.',
     'The policeman said at once: and the goldsmith surely provoked it.')),
  P(('واحد تاني قال: لأ، مش كلبه.',
     'Another said: no, it is not his dog.'),
    ('الشرطي قال: يا حرام الصايغ، الكلب سايب ولازم يتقتل.',
     'The policeman said: poor goldsmith, the dog is a stray and must be put down.')),
  P(('وبعدين مرق طباخ الجنرال وقال: هاد كلب أخو الجنرال.',
     'And then the general’s cook passed and said: this is the general’s brother’s dog.'),
    ('الشرطي ضحك وقال: يا حلوه، خدوه بحرص.',
     'The policeman laughed and said: how sweet, take her carefully.')),
  P(('لف على الصايغ وقال: وإنت، بشوفك بعدين.',
     'He turned to the goldsmith and said: and you, I will see you later.'),
    ('وكمل طريقه بالسوق.', 'And he went on his way through the market.'))]),

 ('Fat and Thin', 'التخين والنحيف', [
  P(('عامل بمصنع كان بيربي حصان عجوز.',
     'A factory worker kept an old horse.'),
    ('الحصان صار ما بيشتغل، بس ما باعه.',
     'The horse had stopped working, but he did not sell it.')),
  P(('مرته قالت: بنطعمي حيوان ما بينفع.',
     'His wife said: we are feeding an animal that is no use.'),
    ('هو قال: هاد شغل معي عشرين سنة.',
     'He said: this one worked with me twenty years.')),
  P(('الجيران صاروا يضحكوا عليه.',
     'The neighbours began laughing at him.'),
    ('قالوا: بيصرف على حصان زي ما بيصرف على ولد.',
     'They said: he spends on a horse as he would on a child.')),
  P(('بشتوية قاسية، الحصان مرض ومات.',
     'In a harsh winter, the horse fell ill and died.'),
    ('الرجل قعد بالإسطبل طول الليل.',
     'The man sat in the stable all night.')),
  P(('الصبح، مرته سألته: شو بتعمل هون؟',
     'In the morning, his wife asked him: what are you doing here?'),
    ('قال: ولا إشي. بس المحل صار واسع.',
     'He said: nothing. Only, the place has become large.'))]),

 ('The Lottery Ticket', 'ورقة اليانصيب', [
  P(('رجل قاعد بيقرا الجريدة بعد العشا.',
     'A man sat reading the newspaper after supper.'),
    ('مرته قالت: شوف أرقام اليانصيب.',
     'His wife said: look at the lottery numbers.')),
  P(('قرا الرقم الأول ولقاه بيطابق ورقتها.',
     'He read the first number and found it matched her ticket.'),
    ('ما قرا الرقم التاني على طول.',
     'He did not read the second number at once.')),
  P(('قعد يفكر شو رح يعملوا بالمصاري.',
     'He sat thinking what they would do with the money.'),
    ('فكر ببيت بالريف، وسفر، وراحة.',
     'He thought of a house in the country, and travel, and rest.')),
  P(('وبعدين تذكر إن الورقة باسمها هي.',
     'And then he remembered the ticket was in her name.'),
    ('صار يفكر إنها رح تصرف عليهم كلهم.',
     'He began thinking she would spend it on all of them.'),
    ('وتطلع فيها وهي قاعدة قدامه.',
     'And he looked at her sitting in front of him.')),
  P(('قرا الرقم التاني، وما كان مطابق.',
     'He read the second number, and it did not match.'),
    ('التنين سكتوا، والأوضة صارت ضيقة.',
     'The two were silent, and the room became small.'))]),

 ('Vanka', 'فانكا', [
  P(('ولد عمره تسع سنين اشتغل عند إسكافي بالمدينة.',
     'A boy of nine worked for a shoemaker in the city.'),
    ('بليلة عيد، قعد لحاله وأخذ ورقة وقلم.',
     'On a feast night, he sat alone and took paper and pen.')),
  P(('كتب: يا جدي، تعال خدني من هون.',
     'He wrote: grandfather, come and take me from here.'),
    ('بيضربوني وبيناموني بالممر.',
     'They beat me and make me sleep in the passage.')),
  P(('كتب عن الضيعة وعن الكلب وعن التلج.',
     'He wrote about the village and the dog and the snow.'),
    ('وقال: أنا رح أدعي لك طول عمري.',
     'And he said: I will pray for you all my life.')),
  P(('طوى الورقة وحطها بمغلف.',
     'He folded the paper and put it in an envelope.'),
    ('كتب عالمغلف: لجدي بالضيعة.',
     'He wrote on the envelope: to my grandfather in the village.')),
  P(('ركض عالصندوق ورماها فيه وهو فرحان.',
     'He ran to the postbox and dropped it in, happy.'),
    ('رجع ونام ينتظر جواب.', 'He came back and slept waiting for a reply.'))]),

 ('Oysters', 'المحار', [
  P(('ولد وأبوه واقفين بالشارع من الصبح.',
     'A boy and his father stood in the street since morning.'),
    ('أبوه كان بده يمد إيده ويشحد وما بيقدر.',
     'His father wanted to put out his hand and beg and could not.')),
  P(('الولد كان جعان لدرجة إنه شاف الدنيا بتلف.',
     'The boy was so hungry the world seemed to spin.'),
    ('قرا كلمة على لافتة مطعم: محار.',
     'He read a word on a restaurant sign: oysters.')),
  P(('سأل أبوه: شو يعني محار؟', 'He asked his father: what does oysters mean?'),
    ('قال أبوه: حيوان بحري، بياكلوه وهو حي.',
     'His father said: a sea creature, they eat it alive.')),
  P(('الولد صار يتخيله ويشعر بالغثيان.',
     'The boy began imagining it and felt sick.'),
    ('وبنفس الوقت، صار يصرخ: بدي محار!',
     'And at the same time, he began shouting: I want oysters!')),
  P(('اتنين ضحكوا عليه وأطعموه.',
     'Two men laughed at him and fed him.'),
    ('وأبوه ضل واقف جنبه وما مد إيده.',
     'And his father stood beside him and did not put out his hand.'))]),

 ('The Complaints Book', 'دفتر الشكاوى', [
  P(('بمحطة قطار صغيرة، في دفتر معلق للشكاوى.',
     'At a small railway station, a complaints book hung on the wall.'),
    ('المفتاح ضايع من زمان.', 'The key had been lost long ago.')),
  P(('واحد كتب: قبعتي ضاعت وأنا نايم.',
     'One person wrote: my hat was lost while I slept.'),
    ('واحد تاني كتب تحتها: مين قال إنك نمت؟',
     'Another wrote beneath it: who said you slept?')),
  P(('واحد كتب قصيدة حب لبنت اسمها كاتيا.',
     'Someone wrote a love poem to a girl named Katya.'),
    ('واحد كتب: الموظف هون وقح وما بيرد.',
     'Someone wrote: the clerk here is rude and does not answer.')),
  P(('وواحد كتب: أنا مش راكب، أنا بس بمرق.',
     'And someone wrote: I am not a passenger, I am only passing.'),
    ('وواحد رسم وجه بعيون كبيرة.',
     'And someone drew a face with big eyes.')),
  P(('ولا شكوى وحدة كانت عن القطار.',
     'Not one complaint was about the train.'),
    ('الدفتر ضل معلق سنين، وما حدا قراه.',
     'The book hung there for years, and nobody read it.'))]),

 ('The Bet', 'الرهان', [
  P(('بحفلة، صار نقاش عن الإعدام والسجن المؤبد.',
     'At a party, an argument arose about execution and life imprisonment.'),
    ('محامي شاب قال: السجن أرحم.',
     'A young lawyer said: prison is more merciful.')),
  P(('مصرفي غني قال: بتراهن؟',
     'A wealthy banker said: will you bet?'),
    ('قال المحامي: بقعد خمستعش سنة لحالي.',
     'The lawyer said: I will sit fifteen years alone.')),
  P(('حبس حاله ببيت بالحديقة، وما شاف حدا.',
     'He shut himself in a house in the garden, and saw nobody.'),
    ('بالسنين الأولى، طلب كتب موسيقى وروايات.',
     'In the first years, he asked for music books and novels.'),
    ('وبعدين طلب فلسفة ولغات وتاريخ.',
     'And then he asked for philosophy and languages and history.')),
  P(('بآخر ليلة، المصرفي كان صار فقير.',
     'On the last night, the banker had become poor.'),
    ('فكر يقتله عشان ما يدفع.',
     'He thought of killing him so as not to pay.')),
  P(('دخل بهدوء ولقى ورقة عالطاولة.',
     'He went in quietly and found a paper on the table.'),
    ('مكتوب فيها: قريت كل إشي، وما عاد بدي مصاريك.',
     'It read: I have read everything, and I no longer want your money.'),
    ('الصبح، لقوا البيت فاضي.', 'In the morning, they found the house empty.'))]),

 ('A Trifle', 'إشي بسيط', [
  P(('رجل بيزور بيت مطلقة وبيحب يتجوزها.',
     'A man used to visit a divorced woman’s house, hoping to marry her.'),
    ('ابنها الزغير كان يحبه ويلعب معه.',
     'Her small son loved him and played with him.')),
  P(('بيوم، الولد قال له: بدي أحكي لك سر.',
     'One day, the boy said to him: I want to tell you a secret.'),
    ('قال الرجل: احكي، وبحلف ما بقول لحدا.',
     'The man said: speak, and I swear I will tell nobody.')),
  P(('الولد قال: بنشوف بابا كل أسبوع بالسر.',
     'The boy said: we see father every week in secret.'),
    ('وبيبكي وبيسألنا عن ماما.',
     'And he cries and asks us about mother.')),
  P(('بالمسا، الرجل حكى كل إشي لأمه.',
     'In the evening, the man told his mother everything.'),
    ('صار في صراخ بالبيت والولد انضرب.',
     'There was shouting in the house and the boy was beaten.')),
  P(('الولد وقف بالزاوية وهو ما بيفهم.',
     'The boy stood in the corner not understanding.'),
    ('كانت أول مرة يعرف إن الكبار بيكذبوا.',
     'It was the first time he knew that grown-ups lie.'))]),

 ('Grief', 'الهَم', [
  P(('سائق عربة عجوز واقف بالتلج من المسا.',
     'An old cab driver stood in the snow from the evening.'),
    ('التلج غطى كتافه وكتاف حصانه.',
     'The snow covered his shoulders and his horse’s.')),
  P(('ابنه مات هالأسبوع، وهو بده يحكي.',
     'His son had died that week, and he wanted to speak.'),
    ('ركب معه ضابط، وقال له: ابني مات.',
     'An officer rode with him, and he said: my son died.'),
    ('الضابط قال: يا حرام، وسكت.',
     'The officer said: how sad, and fell silent.')),
  P(('بعدها ركبوا تلات شباب وهم يضحكوا.',
     'After that three young men rode with him, laughing.'),
    ('حاول يحكي، وواحد قال: كلنا رح نموت.',
     'He tried to speak, and one said: we will all die.'),
    ('نزلوا وهم ما سمعوه.', 'They got out without having heard him.')),
  P(('رجع عالإسطبل بآخر الليل.',
     'He went back to the stable at the end of the night.'),
    ('واحد نايم هناك، حاول يصحيه ويحكي.',
     'Someone was sleeping there; he tried to wake him and talk.'),
    ('الرجل لف على التاني وكمل نوم.',
     'The man turned over and went back to sleep.')),
  P(('راح عند حصانه وحط إيده على راسه.',
     'He went to his horse and put his hand on its head.'),
    ('قال: لو كان عندك ولد ومات، شو كنتي تعملي؟',
     'He said: if you had a son and he died, what would you do?'),
    ('وقعد يحكي له كل إشي من الأول.',
     'And he sat telling it everything from the beginning.'))]),
]

if __name__ == '__main__':
    emit_book(BOOK_ID, BOOK_TITLE, 'advanced', CHAPTERS, unit='Story', unit_ar='قصة', shelf=21,
              meta={'work': 'short stories by Guy de Maupassant and Anton Chekhov',
                    'author': 'Maupassant (d. 1893) and Chekhov (d. 1904)',
                    'year': '1880s–1900s',
                    'status': 'public domain — retold from the plots, not from any translation'})
