#!/usr/bin/env python3
"""كليلة ودمنة — twenty tales, retold in spoken Palestinian, graded to intermediate.

Ibn al-Muqaffaʿ's 8th-century Arabic version of the Panchatantra, by way of Persian. Public domain
by age; these are retellings from the traditional plots, not a translation of any edition.

WHY IT BELONGS ON THIS SHELF. It is the Arabic narrative classic — an educated Arab meets Kalila
and Dimna at school, and the two jackals are as familiar as Aesop's fox is in English. It also
teaches something no other book here does: the FRAME. A character stops the action to tell a story
that argues a point, and the outer plot resumes changed. That is a real feature of how Arabic
narrative and, for that matter, Arabic conversation works.

TALES CHOSEN TO NOT DUPLICATE THE AESOP BOOK. No tortoise-and-hare, no lion-and-mouse, no crane.
What's here is the Lion and the Ox cycle that gives the book its two jackals, plus the nested
fables that are distinctive to this tradition.

LEVEL. Written near the intermediate story baseline (32.5 characters a sentence), like Sindbad and
unlike the existing Around the World at 49.5. Past-tense narrative with connectors and reported
speech, one clause at a time. The nested tales let dialogue carry a lot of the work, which keeps
sentences short without making the prose childish.

As everywhere in this project the PROSE is written by Claude (flagged NOT native-validated), but
every WORD's root, meaning and pronunciation is looked up in Maknuune by the ingest pipeline.

Run:  python3 pipeline/book_kalila.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, book
BOOK_ID = 'kalila'
BOOK_TITLE = {'en': 'Kalila and Dimna', 'ar': 'كليلة ودمنة'}

# (english title, arabic title, [paragraph, ...])
#
# SECOND EDITION (2026-09-03). The first edition was seven sentences a tale — a summary, not a
# chapter. These are the same twenty tales, same titles, same names, written out: the frame
# stories are told in full, the dialogue is let run, and every tale still ends on its line.
CHAPTERS = [
 ('The Philosopher and the King', 'الفيلسوف والملك', [
  P(('زمان، كان في ملك بالهند اسمه دبشليم.', "Long ago, there was a king in India named Dabshalim."),
    ('بالأول كان ملك منيح، وبعدين تغير.', "At first he was a good king, and then he changed."),
    ('صار ظالم، وبيسمع بس الكلام اللي بيعجبه.', "He became unjust, and listened only to words that pleased him."),
    ('اللي كان يعارضه، كان يحبسه أو يقتله.', "Whoever opposed him, he imprisoned or killed."),
    ('فالناس سكتوا، والبلد صارت زي بيت ساكت من الخوف.', "So the people fell silent, and the country became like a house silent from fear.")),
  P(('بنفس البلد كان في فيلسوف اسمه بيدبا.', "In the same country there was a philosopher named Bidpai."),
    ('كان عنده تلاميذ كتار، وكلهم بيحبوه.', "He had many students, and they all loved him."),
    ('بيوم جمعهم وقال: أنا قررت أروح عند الملك.', "One day he gathered them and said: I have decided to go to the king."),
    ('التلاميذ خافوا وقالوا له: يا معلم، رح يقتلك.', "The students were afraid and said: teacher, he will kill you."),
    ('قال لهم: إذا شفت الخطر وسكت، شو فايدة علمي؟', "He said to them: if I see the danger and stay silent, what is the use of my learning?"),
    ('بس أنا مش رايح أعارضه، أنا رايح أحكي له قصة.', "But I am not going to oppose him; I am going to tell him a story.")),
  P(('راح بيدبا عالقصر ووقف عند الباب أيام.', "Bidpai went to the palace and stood at the gate for days."),
    ('بالآخر سمحوا له يفوت.', "At last they let him in."),
    ('الملك كان قاعد على كرسيه، وحواليه الوزرا ساكتين.', "The king was seated on his throne, and around him the ministers were silent."),
    ('قال له الملك: شو بدك يا شيخ؟', "The king said to him: what do you want, old man?"),
    ('قال بيدبا: بدي أحكي عن أسد وثور وابنين آوى.', "Bidpai said: I want to tell you about a lion, an ox and two jackals."),
    ('ضحك الملك وقال: حيوانات؟ طيب، احكي.', "The king laughed and said: animals? Fine, speak.")),
  P(('وبلش بيدبا يحكي، والملك بيسمع.', "And Bidpai began to speak, and the king listened."),
    ('كل يوم كان يحكي له حكاية، وكل حكاية جواتها حكاية.', "Every day he told him a tale, and inside every tale there was another tale."),
    ('الملك ما زعل، لأن القصة عن حيوانات مش عنه.', "The king was not angry, because the story was about animals, not about him."),
    ('بس بالليل كان يفكر: الأسد اللي بالقصة، ليش بيشبهني؟', "But at night he would think: the lion in the story, why does he resemble me?"),
    ('وشوي شوي فهم إن القصة عنه.', "And little by little he understood that the story was about him."),
    ('قال لبيدبا: إنت ما حكيت لي عن الحيوانات.', "He said to Bidpai: you did not tell me about animals."),
    ('إنت حكيت لي عن حالي.', "You told me about myself."),
    ('قال بيدبا: الحكاية مرآة، وكل واحد بيشوف فيها وجهه.', "Bidpai said: a tale is a mirror, and everyone sees his own face in it."),
    ('وهاي الحكايات اللي حكاها، هي اللي رح تقراها هون.', "And the tales he told are the ones you will read here."))]),

 ('Two Jackals at the Lion’s Gate', 'ابنا آوى عند باب الأسد', [
  P(('بغابة بعيدة، كان في أسد، وكان ملك على كل الحيوانات.', "In a far forest there was a lion, and he was king over all the animals."),
    ('كان قوي، بس كمان كان بيحب اللي بيمدحوه.', "He was strong, but he also loved those who praised him."),
    ('عنده خدم كتار: ذياب وثعالب وغربان وابن آوى.', "He had many servants: wolves, foxes, crows and jackals."),
    ('كل واحد فيهم بده يقرب من الملك أكتر من التاني.', "Each of them wanted to be closer to the king than the other.")),
  P(('عند باب الأسد كان في اتنين من ابن آوى، إخوة.', "At the lion's gate there were two jackals, brothers."),
    ('الأول اسمه كليلة والتاني اسمه دمنة.', "The first was called Kalila and the second Dimna."),
    ('كليلة كان قنوع، بيقول: اللي عندي بيكفيني.', "Kalila was content; he would say: what I have is enough for me."),
    ('أما دمنة، فكان ذكي وطموح، وما بينام من التفكير.', "Dimna, however, was clever and ambitious, and could not sleep for thinking."),
    ('كان يتفرج على الوزرا وهم بيفوتوا عند الملك، ويحسدهم.', "He would watch the ministers going in to the king, and envy them.")),
  P(('بيوم قال دمنة لأخوه: يا كليلة، ليش إحنا واقفين عند الباب؟', "One day Dimna said to his brother: Kalila, why are we standing at the gate?"),
    ('إحنا أذكى من كل الوزرا، وهم جوا وإحنا برا.', "We are smarter than all the ministers, and they are inside and we are outside."),
    ('قال كليلة: وشو بدك بالجوا؟', "Kalila said: and what do you want with the inside?"),
    ('اللي بيقرب من الملك بيقرب من النار.', "Whoever comes near the king comes near the fire."),
    ('واللي بيقرب من النار بينحرق.', "And whoever comes near the fire gets burned."),
    ('قال دمنة: بس النار كمان بتدفي.', "Dimna said: but fire also warms."),
    ('اللي بيخاف من كل إشي، بيضل طول عمره عند الباب.', "Whoever fears everything stays at the gate all his life.")),
  P(('قال كليلة: وكيف بدك توصل للملك؟ هو ما بيعرفك.', "Kalila said: and how will you reach the king? He does not know you."),
    ('قال دمنة: رح أستنى الفرصة.', "Dimna said: I will wait for the chance."),
    ('الملك زي أي واحد، بيجي عليه يوم وبيحتاج حدا.', "The king is like anyone; a day comes when he needs someone."),
    ('وبهاليوم أنا رح أكون موجود.', "And on that day I will be there."),
    ('هز كليلة راسه وسكت.', "Kalila shook his head and fell silent."),
    ('كان عارف إن أخوه ما بيسمع، بس كان بيحبه.', "He knew his brother would not listen, but he loved him."),
    ('وبنفس الليلة، إجت الفرصة اللي دمنة كان يستناها.', "And that same night, the chance Dimna was waiting for came."))]),

 ('The Ox Called Shatraba', 'الثور شتربة', [
  P(('بالليل، سمع الأسد صوت غريب من بعيد.', "At night, the lion heard a strange sound from far away."),
    ('صوت عالي وقوي، ما سمع زيه بحياته.', "A loud, powerful sound, the like of which he had never heard in his life."),
    ('الأسد خاف، بس ما بده حدا يعرف إنه خايف.', "The lion was afraid, but did not want anyone to know he was afraid."),
    ('قعد مكانه وما طلع للصيد، لا هاليوم ولا اللي بعده.', "He stayed where he was and did not go out to hunt, not that day and not the next."),
    ('الحيوانات لاحظت، وبلشت تتهامس.', "The animals noticed, and began to whisper.")),
  P(('دمنة كان واقف عند الباب وشاف الخوف بعين الملك.', "Dimna was standing at the gate and saw the fear in the king's eyes."),
    ('قال لكليلة: هاي هي الفرصة.', "He said to Kalila: this is the chance."),
    ('فات عند الأسد وانحنى وقال: يا ملك، شكلك مهموم.', "He went in to the lion, bowed and said: my king, you look troubled."),
    ('قال الأسد: ومين إنت؟', "The lion said: and who are you?"),
    ('قال: أنا دمنة، خادمك اللي عند الباب.', "He said: I am Dimna, your servant at the gate."),
    ('الصوت اللي سمعته، أنا بقدر أروح وأشوف شو هو.', "The sound you heard, I can go and see what it is."),
    ('استغرب الأسد، لأن ما حدا حكى عن الصوت قدامه.', "The lion was surprised, because no one had spoken about the sound in front of him."),
    ('بس قال: روح، وارجع بخبر.', "But he said: go, and come back with news.")),
  P(('مشى دمنة باتجاه الصوت لحد ما وصل على مرج أخضر.', "Dimna walked toward the sound until he reached a green meadow."),
    ('وهناك شاف ثور كبير، أكبر ثور شافه بحياته.', "And there he saw a big ox, the biggest ox he had ever seen."),
    ('اسمه شتربة، وكان تاجر تركه بالطريق لأنه انكسر إجره.', "His name was Shatraba, and a merchant had left him on the road because his leg had broken."),
    ('لما طاب، لقى حاله لحاله بمرج فيه عشب ومي.', "When he healed, he found himself alone in a meadow with grass and water."),
    ('ومن الفرح، كان يخور بصوت عالي، وهاد الصوت اللي خوف الأسد.', "And from joy, he would bellow loudly, and this was the sound that had frightened the lion.")),
  P(('ضحك دمنة بقلبه وقال: الملك خايف من ثور بياكل عشب.', "Dimna laughed inside and said: the king is afraid of an ox that eats grass."),
    ('قرب من شتربة وقال: أنا رسول الأسد، ملك الغابة.', "He approached Shatraba and said: I am the messenger of the lion, king of the forest."),
    ('هو بده يشوفك، وإذا جيت معي رح تكون بأمان.', "He wants to see you, and if you come with me you will be safe."),
    ('خاف شتربة بالأول، بس دمنة حلف له إنه ما رح يصير له إشي.', "Shatraba was afraid at first, but Dimna swore to him that nothing would happen to him."),
    ('ومشوا سوا، الثور الكبير وابن آوى الزغير.', "And they walked together, the big ox and the small jackal.")),
  P(('لما شاف الأسد الثور، فهم إن الصوت ما كان خطر.', "When the lion saw the ox, he understood that the sound had been no danger."),
    ('استحى من خوفه، وبنفس الوقت فرح.', "He was ashamed of his fear, and at the same time glad."),
    ('قال لدمنة: إنت عملت اللي ما عمله حدا. من اليوم إنت قريب مني.', "He said to Dimna: you did what no one did. From today you are close to me."),
    ('ودمنة انحنى، وقلبه بيرقص.', "And Dimna bowed, his heart dancing."),
    ('بس هو ما كان بيعرف إنه جاب معه المشكلة اللي رح تدمره.', "But he did not know that he had brought with him the trouble that would destroy him."))]),

 ('The Friendship That Grew', 'الصداقة اللي كبرت', [
  P(('بالأول، كان الأسد يسأل دمنة عن كل إشي.', "At first, the lion asked Dimna about everything."),
    ('وكان دمنة سعيد، لأنه صار جوا بعد ما كان برا.', "And Dimna was happy, because he was inside after having been outside."),
    ('بس الأسد كان بيحب يحكي مع شتربة كمان.', "But the lion liked to talk with Shatraba too."),
    ('الثور كان عاقل، وشاف بلاد كتيرة مع التاجر.', "The ox was wise, and had seen many countries with the merchant."),
    ('كان بيحكي عن المدن والأسواق والناس، والأسد بيسمع ومبسوط.', "He would talk about cities and markets and people, and the lion listened, pleased.")),
  P(('مرت الأيام، وصار الأسد وشتربة يقعدوا مع بعض كل يوم.', "The days passed, and the lion and Shatraba began sitting together every day."),
    ('من الصبح للمسا، ما حدا بيقدر يفوت عليهم.', "From morning to evening, no one could go in to them."),
    ('الوزرا القدام زعلوا، ودمنة زعل أكتر من الكل.', "The old ministers were upset, and Dimna was more upset than any of them."),
    ('كان يوقف عند الباب ويسمع ضحكهم من جوا.', "He would stand at the gate and hear their laughter from inside."),
    ('نفس الباب اللي كان واقف عنده من الأول.', "The same gate he had stood at from the beginning.")),
  P(('راح دمنة عند أخوه وقال: شفت شو صار؟', "Dimna went to his brother and said: did you see what happened?"),
    ('أنا جبت الثور بإيدي، وهلق الثور أقرب للملك مني.', "I brought the ox with my own hands, and now the ox is closer to the king than I am."),
    ('كان الملك يسألني، وهلق بيسأله.', "The king used to ask me, and now he asks him."),
    ('قال كليلة: ومين قال إنك تجيبه؟', "Kalila said: and who told you to bring him?"),
    ('إنت عملتها بإيدك، فليش زعلان من غيرك؟', "You did it with your own hand, so why are you angry at someone else?")),
  P(('قال دمنة: صح، أنا عملتها. واللي عملته بقدر أفكه.', "Dimna said: true, I did it. And what I made, I can undo."),
    ('قال كليلة: شو قصدك؟', "Kalila said: what do you mean?"),
    ('قال دمنة: بدي أفرق بين الأسد والثور.', "Dimna said: I want to separate the lion and the ox."),
    ('مش بالقوة، أنا أضعف منهم. بالكلام.', "Not by force; I am weaker than both. By words."),
    ('خاف كليلة وقال: يا أخي، هاد الطريق ما بيرجع منه حدا.', "Kalila was afraid and said: brother, no one comes back from this road."),
    ('ضحك دمنة وقال: الطريق للي ما بيعرف يمشي. أنا بعرف.', "Dimna laughed and said: the road is for those who do not know how to walk. I know."),
    ('فسكت كليلة، وبعدين قال: طيب، خليني أحكي قصة.', "So Kalila was silent, and then he said: fine, let me tell you a story."))]),

 ('The Monkey and the Carpenter', 'القرد والنجار', [
  P(('قال كليلة: اسمع.', "Kalila said: listen."),
    ('اللي بيتدخل بشغل مش شغله، بيصير له زي القرد.', "Whoever meddles in work that is not his ends up like the monkey."),
    ('قال دمنة: أي قرد؟', "Dimna said: which monkey?"),
    ('قال كليلة: كان في نجار بيشتغل بحديقة، جنب شجرة كبيرة.', "Kalila said: there was a carpenter working in a garden, beside a big tree."),
    ('وعالشجرة كان في قرد بيتفرج عليه كل يوم.', "And in the tree there was a monkey who watched him every day.")),
  P(('النجار كان بيشق خشبة طويلة بمنشار.', "The carpenter was splitting a long plank with a saw."),
    ('وكل ما يوصل شوي، يحط إسفين بالشق عشان الخشبة تضل مفتوحة.', "And every time he got a little way, he would put a wedge in the split so the plank stayed open."),
    ('وبعدين يشق شوي كمان، ويحط إسفين تاني، ويشيل الأول.', "Then he would cut a little more, put in a second wedge, and take out the first."),
    ('القرد كان يتفرج ويقول بقلبه: شغلة سهلة. أنا بقدر أعملها أحسن منه.', "The monkey watched and said to himself: an easy job. I can do it better than him.")),
  P(('عالظهر، راح النجار ياكل وترك الخشبة والإسفين مكانهم.', "At noon, the carpenter went to eat and left the plank and the wedge where they were."),
    ('نزل القرد بسرعة وقعد على الخشبة، زي ما كان النجار قاعد.', "The monkey came down quickly and sat on the plank, just as the carpenter had sat."),
    ('وإجريه دلوا بالشق.', "And his legs hung down into the split."),
    ('مسك الإسفين وصار يشد فيه.', "He grabbed the wedge and started pulling on it."),
    ('كان الإسفين قوي، بس القرد قوي كمان.', "The wedge was firm, but the monkey was strong too."),
    ('وبالآخر طلع الإسفين.', "And in the end the wedge came out.")),
  P(('لحظة وحدة، والخشبة سكرت.', "One moment, and the plank closed."),
    ('سكرت على إجرين القرد ومسكته.', "It closed on the monkey's legs and held him."),
    ('صرخ وصرخ، وما حدا سمعه، لأن النجار بعيد بياكل.', "He screamed and screamed, and no one heard him, because the carpenter was far away eating."),
    ('لما رجع النجار ولقاه، ما ساعده. ضربه.', "When the carpenter came back and found him, he did not help him. He beat him."),
    ('قال: أنا ما قلت إنك تشتغل بشغلي.', "He said: I did not tell you to work at my job.")),
  P(('سكت كليلة، وقال: هاد اللي بيصير للي بيتدخل بشغل مش شغله.', "Kalila fell silent, and said: this is what happens to whoever meddles in work that is not his."),
    ('إنت ابن آوى. الأسد والثور شغلهم مش شغلك.', "You are a jackal. The lion and the ox are not your business."),
    ('قال دمنة: بس أنا مش قرد. أنا بفهم شو بعمل.', "Dimna said: but I am not a monkey. I understand what I am doing."),
    ('قال كليلة: والقرد كمان كان بيفكر هيك.', "Kalila said: and the monkey thought so too."),
    ('بس دمنة كان قرر، والقصة ما غيرت إشي.', "But Dimna had decided, and the story changed nothing."))]),

 ('Dimna Speaks to the Lion', 'دمنة بيحكي للأسد', [
  P(('تاني يوم، راح دمنة عند الأسد وقعد قدامه ساكت.', "The next day, Dimna went to the lion and sat before him in silence."),
    ('ما حكى ولا كلمة، وشكله حزين.', "He said not a word, and looked sad."),
    ('الأسد كان متعود يسمع صوته، فاستغرب.', "The lion was used to hearing his voice, so he was surprised."),
    ('قال له: مالك يا دمنة؟ من زمان ما شفتك.', "He said to him: what is wrong, Dimna? I have not seen you for a long time."),
    ('قال دمنة: ولا إشي يا ملك.', "Dimna said: nothing, my king."),
    ('قال الأسد: وجهك بيقول غير هيك. احكي.', "The lion said: your face says otherwise. Speak.")),
  P(('قال دمنة: في إشي، بس بخاف أحكيه.', "Dimna said: there is something, but I am afraid to say it."),
    ('لأنه إذا حكيته، رح تزعل مني، وإذا سكت، رح أكون خاين.', "Because if I say it, you will be angry at me, and if I stay silent, I will be a traitor."),
    ('قال الأسد: أنا الملك، وأنا بقرر مين الخاين. احكي.', "The lion said: I am the king, and I decide who is a traitor. Speak."),
    ('تنهد دمنة، وقال: شتربة.', "Dimna sighed, and said: Shatraba."),
    ('قال الأسد: شو فيه شتربة؟', "The lion said: what about Shatraba?")),
  P(('قال دمنة: شتربة بيحكي مع الحيوانات عنك، وأنا سمعته بإذني.', "Dimna said: Shatraba talks to the animals about you, and I heard him with my own ears."),
    ('بيقول إنه أقوى منك، وإنه شاف ملوك أعظم منك بأسفاره.', "He says he is stronger than you, and that he saw kings greater than you on his travels."),
    ('وبيقول إن الغابة ما بتحتاج أسد، بتحتاج واحد عاقل.', "And he says the forest does not need a lion; it needs someone wise."),
    ('والحيوانات بتسمعه، لأنه قريب منك.', "And the animals listen to him, because he is close to you."),
    ('الأسد صار وجهه أصفر. قال: شتربة صاحبي.', "The lion's face went pale. He said: Shatraba is my friend."),
    ('قال دمنة: وأنا كمان كنت أفكر هيك. عشان هيك تأخرت وأنا بحكي معك.', "Dimna said: and I too thought so. That is why I was slow to tell you.")),
  P(('قال الأسد: بس هو ما عمل إشي.', "The lion said: but he has done nothing."),
    ('قال دمنة: لسا. اللي بيحكي اليوم، بكرا بيعمل.', "Dimna said: not yet. Whoever talks today, acts tomorrow."),
    ('وبعدين، لاحظ لما تشوفه المرة الجاية.', "And then, watch when you see him the next time."),
    ('إذا كان بريء، رح يجي زي كل يوم.', "If he is innocent, he will come as he does every day."),
    ('بس إذا إجا وعينه بتلمع وقرونه لقدام؟', "But if he comes with his eyes shining and his horns forward?"),
    ('وقتها اعرف إنه ناوي على إشي.', "Then know he intends something."),
    ('الأسد سكت طويل، وصار يفكر.', "The lion was silent a long time, and began to think."),
    ('والفكرة، لما بتفوت، صعب تطلع.', "And a thought, once it enters, is hard to get out."))]),

 ('Dimna Speaks to the Ox', 'دمنة بيحكي للثور', [
  P(('طلع دمنة من عند الأسد، وراح على طول عند شتربة.', "Dimna left the lion, and went straight to Shatraba."),
    ('الثور كان قاعد بالمرج بياكل، ولما شافه فرح.', "The ox was in the meadow eating, and when he saw him he was glad."),
    ('قال: يا دمنة، صاحبي الأول بالغابة! وين كنت؟', "He said: Dimna, my first friend in the forest! Where have you been?"),
    ('دمنة قعد جنبه، وعمل حاله حزين، ونفس الشغلة.', "Dimna sat beside him, made himself look sad, and did the same thing.")),
  P(('قال شتربة: مالك؟', "Shatraba said: what is wrong?"),
    ('قال دمنة: أنا صاحبك، وعشان هيك جيت أحذرك.', "Dimna said: I am your friend, and that is why I came to warn you."),
    ('الأسد بده يتخلص منك.', "The lion wants to be rid of you."),
    ('سمعته بيقول للوزرا: الثور صار سمين.', "I heard him say to the ministers: the ox has grown fat."),
    ('وبكرا بعزمكم على لحمه.', "And tomorrow I invite you to his meat."),
    ('شتربة وقف مكانه، وقال: مستحيل. هو صاحبي.', "Shatraba stood where he was, and said: impossible. He is my friend."),
    ('قال دمنة: الأسد أسد. بياكل لحم، وإنت لحم.', "Dimna said: a lion is a lion. He eats meat, and you are meat."),
    ('الصداقة بينكم كانت لعبة، ولما تخلص اللعبة، بيرجع لطبعه.', "The friendship between you was a game, and when the game ends, he goes back to his nature.")),
  P(('شتربة ما صدق بالأول.', "Shatraba did not believe it at first."),
    ('قال: أنا ما عملت له إشي. ليش يقتلني؟', "He said: I have done nothing to him. Why would he kill me?"),
    ('قال دمنة: الملوك ما بيحتاجوا سبب.', "Dimna said: kings do not need a reason."),
    ('وبعدين، لاحظ لما تشوفه المرة الجاية.', "And then, watch when you see him the next time."),
    ('إذا إجا وعينه حمرا وديله بيضرب الأرض؟', "If he comes with his eyes red and his tail beating the ground?"),
    ('وقتها اعرف إنه ناوي عليك.', "Then know he means you harm."),
    ('قال شتربة: وإذا كان هيك، شو أعمل؟', "Shatraba said: and if it is so, what do I do?"),
    ('قال دمنة: دافع عن حالك. إنت كبير وقرونك حادة.', "Dimna said: defend yourself. You are big and your horns are sharp.")),
  P(('طلع دمنة، وترك الثور لحاله بالمرج.', "Dimna left, and left the ox alone in the meadow."),
    ('شتربة ما نام تلك الليلة. كل ما سمع صوت، وقف.', "Shatraba did not sleep that night. Every time he heard a sound, he stood up."),
    ('وبالطرف التاني من الغابة، الأسد كمان ما نام.', "And on the other side of the forest, the lion did not sleep either."),
    ('كل واحد فيهم صار خايف من التاني.', "Each of them had become afraid of the other."),
    ('ورجع دمنة عند كليلة وقال: خلص، زرعت.', "And Dimna went back to Kalila and said: it is done, I have sown."),
    ('قال كليلة: وشو رح تحصد؟', "Kalila said: and what will you reap?"),
    ('دمنة ما جاوب.', "Dimna did not answer."))]),

 ('The Fight', 'الخناقة', [
  P(('تاني يوم الصبح، إجا شتربة عند الأسد زي كل يوم.', "The next morning, Shatraba came to the lion as he did every day."),
    ('بس هالمرة كان ماشي على مهل، وراسه واطي، وقرونه لقدام.', "But this time he was walking slowly, his head low, his horns forward."),
    ('كان خايف، والخايف بيمشي هيك.', "He was afraid, and the fearful walk this way."),
    ('الأسد شافه من بعيد، وتذكر كلام دمنة.', "The lion saw him from afar, and remembered Dimna's words."),
    ('قال بقلبه: قرونه لقدام. إذن صحيح.', "He said to himself: his horns forward. So it is true.")),
  P(('وقف الأسد، وعينه صارت حمرا، وديله بيضرب الأرض.', "The lion stood up, his eyes went red, and his tail beat the ground."),
    ('كان غضبان، والغضبان بيوقف هيك.', "He was angry, and the angry stand this way."),
    ('شتربة شاف عينه الحمرا وديله، وتذكر كلام دمنة.', "Shatraba saw his red eyes and his tail, and remembered Dimna's words."),
    ('قال بقلبه: عينه حمرا. إذن صحيح.', "He said to himself: his eyes are red. So it is true."),
    ('كل واحد شاف بالتاني اللي دمنة قال له يشوفه.', "Each saw in the other what Dimna had told him to see."),
    ('والخوف بيشبه العداوة كتير، لدرجة إن ما حدا بيفرق بينهم.', "And fear looks a great deal like enmity, so much that no one tells them apart.")),
  P(('ما حدا حكى كلمة. ما حدا سأل.', "No one said a word. No one asked."),
    ('لو سأل الأسد: يا شتربة، ليش قرونك لقدام؟', "Had the lion asked: Shatraba, why are your horns forward?"),
    ('كان الثور جاوب: لأني خايف منك.', "The ox would have answered: because I fear you."),
    ('ولو سأل الثور: يا ملك، ليش عينك حمرا؟', "And had the ox asked: my king, why are your eyes red?"),
    ('كان الأسد جاوب: لأني خايف منك.', "The lion would have answered: because I fear you."),
    ('وكان كل إشي انحل بسؤال.', "And everything would have been settled by a question."),
    ('بس ما حدا سأل.', "But no one asked.")),
  P(('نط الأسد، وشتربة ضرب بقرونه.', "The lion leapt, and Shatraba struck with his horns."),
    ('انخانقوا بلا ما حدا منهم بده الخناقة.', "They fought without either of them wanting the fight."),
    ('الغبار طلع، والحيوانات هربت من الصوت.', "The dust rose, and the animals fled from the noise."),
    ('وبالآخر وقع الثور عالأرض ومات.', "And at last the ox fell to the ground and died."),
    ('والأسد وقف فوقه، وهو بينزف من كتفه وصدره.', "And the lion stood over him, bleeding from his shoulder and chest.")),
  P(('لما هدي الغبار، قعد الأسد جنب شتربة.', "When the dust settled, the lion sat beside Shatraba."),
    ('كان الغضب راح، وما ضل غير الحزن.', "The anger had gone, and nothing was left but grief."),
    ('قال: شو عملت؟ خسرت أحسن صاحب عندي.', "He said: what have I done? I have lost the best friend I had."),
    ('ومن بعيد، بين الشجر، كان دمنة بيتفرج.', "And from afar, among the trees, Dimna was watching."),
    ('وجنبه كليلة، وهو بيبكي.', "And beside him Kalila, weeping."))]),

 ('The Trial of Dimna', 'محاكمة دمنة', [
  P(('بعد اللي صار، الأسد ما طلع من مكانه أيام.', "After what happened, the lion did not leave his place for days."),
    ('كان يسأل حاله: شتربة كان بده يقتلني، ولا أنا اللي تخيلت؟', "He asked himself: did Shatraba want to kill me, or did I imagine it?"),
    ('والحيوانات حكت مع بعضها بالسر.', "And the animals talked among themselves in secret."),
    ('كلهم شافوا دمنة رايح جاي بين الأسد والثور، وكلهم فهموا.', "They had all seen Dimna going back and forth between the lion and the ox, and they all understood.")),
  P(('بس ما حدا تجرأ يحكي، غير وحدة: أم الأسد.', "But no one dared to speak, except one: the lion's mother."),
    ('كانت كبيرة وعاقلة، وما بتخاف من ابنها.', "She was old and wise, and did not fear her son."),
    ('راحت عنده وقالت: إنت قتلت صاحبك بكلمة.', "She went to him and said: you killed your friend on a word."),
    ('كلمة سمعتها من واحد ما بتعرفه.', "A word you heard from someone you do not know."),
    ('مين حكى معك إن شتربة بده يقتلك؟', "Who told you that Shatraba wanted to kill you?"),
    ('قال الأسد: دمنة.', "The lion said: Dimna."),
    ('قالت: ومين حكى لشتربة إنك بدك تقتله؟', "She said: and who told Shatraba that you wanted to kill him?"),
    ('الأسد سكت. وبعدين فهم.', "The lion was silent. And then he understood.")),
  P(('أمر الأسد يحبسوا دمنة، وجابوه قدام كل الحيوانات.', "The lion ordered Dimna imprisoned, and they brought him before all the animals."),
    ('صار القاضي يسأله، ودمنة يجاوب بذكاء.', "The judge began to question him, and Dimna answered cleverly."),
    ('قال: أنا ما قتلت حدا. الأسد قتل الثور، مش أنا.', "He said: I killed no one. The lion killed the ox, not I."),
    ('أنا حكيت كلام بس، والكلام مش سيف.', "I only spoke words, and words are not a sword."),
    ('قال القاضي: الكلام بيقتل زي السيف، وأحياناً أكتر.', "The judge said: words kill like a sword, and sometimes more."),
    ('السيف بيقتل واحد. الكلمة قتلت الثور، وجرحت الأسد، وخربت الغابة.', "A sword kills one. The word killed the ox, wounded the lion, and ruined the forest.")),
  P(('طلعوا شهود كتار، وكل واحد حكى شو شاف.', "Many witnesses came forward, and each told what he had seen."),
    ('وبالآخر حكموا على دمنة بالموت، ونفذوا الحكم.', "And in the end they sentenced Dimna to death, and carried out the sentence."),
    ('أما كليلة، فما قدر يعيش بعد أخوه.', "As for Kalila, he could not live after his brother."),
    ('ما كان مذنب، بس كان عارف وساكت.', "He was not guilty, but he had known and stayed silent."),
    ('ومات من الحزن بعد أيام.', "And he died of grief within days.")),
  P(('وهون وقف بيدبا، وسكت.', "And here Bidpai stopped, and was silent."),
    ('قال الملك دبشليم: ودمنة، ليش عمل هيك؟', "King Dabshalim said: and Dimna, why did he do this?"),
    ('قال بيدبا: لأنه كان يسمع بس اللي بيعجبه.', "Bidpai said: because he listened only to what pleased him."),
    ('وما كان حدا يقدر يوقفه.', "And no one could stop him."),
    ('الملك فهم، وما حكى. وقال: احكي لي كمان.', "The king understood, and said nothing. And he said: tell me more."))]),

 ('The Fox and the Drum', 'الثعلب والطبل', [
  P(('قال بيدبا: يا ملك، خليني أحكي عن الثعلب.', "Bidpai said: my king, let me tell you about the fox."),
    ('الثعلب اللي سمع الصوت وصدقه.', "The fox that heard a sound and believed it."),
    ('كان في ثعلب جعان، ما أكل من تلات أيام.', "There was a hungry fox, who had not eaten for three days."),
    ('كان يمشي بالغابة ويدور على أي إشي.', "He was walking through the forest looking for anything at all."),
    ('وفجأة سمع صوت عالي ومخيف بيتكرر ورا بعضه.', "And suddenly he heard a loud, frightening sound repeating one after another."),
    ('وقف الثعلب مكانه، وشعره وقف من الخوف.', "The fox stopped where he was, and his fur stood up in fear.")),
  P(('قال بقلبه: صوت زي هيك، أكيد صاحبه حيوان كبير كتير.', "He said to himself: a sound like this, surely its owner is a very big animal."),
    ('وحيوان كبير، فيه لحم كتير.', "And a big animal has a lot of meat."),
    ('صار يقرب شوي شوي، وكل ما قرب، الصوت بيعلى.', "He began to approach little by little, and the closer he came, the louder the sound grew."),
    ('وصل على شجرة كبيرة، وشاف اللي بيعمل الصوت.', "He reached a big tree, and saw what was making the sound."),
    ('كان طبل. طبل قديم معلق على غصن.', "It was a drum. An old drum hanging from a branch."),
    ('وكل ما تيجي الريح، الغصن بيضرب على الطبل، والطبل بيصوت.', "And every time the wind came, the branch struck the drum, and the drum sounded.")),
  P(('الثعلب ما كان يعرف شو الطبل.', "The fox did not know what a drum was."),
    ('قال: هاد إشي كبير ومدور وصوته عالي. أكيد جواته لحم كتير.', "He said: this thing is big and round and loud. Surely there is a lot of meat inside."),
    ('نط على الطبل، وصار يعض فيه بأسنانه.', "He jumped at the drum, and started biting it with his teeth."),
    ('الجلد كان ناشف ومشدود، وأسنانه وجعته.', "The skin was dry and taut, and his teeth hurt."),
    ('بس هو ضل يعض، لأنه جعان.', "But he kept biting, because he was hungry.")),
  P(('وبالآخر انشق الجلد، وفتح الطبل.', "And at last the skin split, and the drum opened."),
    ('فات الثعلب راسه جوا، ودور.', "The fox put his head inside, and looked."),
    ('ما في إشي. فاضي. ولا لحم، ولا عظم، ولا حتى ريحة.', "There was nothing. Empty. No meat, no bone, not even a smell."),
    ('قعد الثعلب عالأرض، جعان أكتر من قبل، وأسنانه بتوجعه.', "The fox sat on the ground, hungrier than before, his teeth aching."),
    ('وقال: يا ما تعبت عشان صوت.', "And he said: how much I have toiled for a sound.")),
  P(('قال بيدبا: أكبر صوت بيطلع من أفرغ إشي.', "Bidpai said: the biggest noise comes out of the emptiest thing."),
    ('ودمنة كان هيك، صوت عالي وجواته فاضي.', "And Dimna was like that, a loud voice and empty inside."),
    ('والأسد كان الثعلب، سمع الصوت وصدقه قبل ما يفتح ويشوف.', "And the lion was the fox, who heard the sound and believed it before he opened it and looked."),
    ('قال الملك: وأنا؟', "The king said: and I?"),
    ('قال بيدبا: إنت لسا بتسمع، وهاد أحسن من الاتنين.', "Bidpai said: you are still listening, and that is better than both of them."))]),

 ('The Three Fish', 'السمكات التلات', [
  P(('قال بيدبا: بغدير بعيد، بين جبلين، كان في تلات سمكات.', "Bidpai said: in a far pond, between two mountains, there were three fish."),
    ('عاشوا سوا سنين، وكانوا أصحاب.', "They had lived together for years, and were friends."),
    ('بس كانوا مختلفين بالعقل.', "But they differed in mind."),
    ('الأولى عاقلة، بتفكر بالإشي قبل ما يصير.', "The first was wise; she thought about a thing before it happened."),
    ('التانية نص نص، بتفكر لما يصير.', "The second was middling; she thought when it happened."),
    ('والتالتة غافلة، ما بتفكر أبداً.', "And the third was heedless; she never thought at all.")),
  P(('بيوم، مر صيادين جنب الغدير.', "One day, fishermen passed by the pond."),
    ('شافوا المي صافية والسمك كبير، وفرحوا.', "They saw the clear water and the big fish, and were glad."),
    ('قال واحد للتاني: اليوم ما معنا شبك. بكرا منرجع لهون ومنصيد كل اللي فيه.', "One said to the other: today we have no nets. Tomorrow we come back here and catch everything in it."),
    ('والسمكات التلات سمعوا كل كلمة.', "And the three fish heard every word.")),
  P(('السمكة العاقلة ما استنت.', "The wise fish did not wait."),
    ('قالت: الخطر جاي، والطريق لسا مفتوح.', "She said: the danger is coming, and the road is still open."),
    ('كان في مجرى زغير بيوصل الغدير بالنهر.', "There was a small channel joining the pond to the river."),
    ('سبحت فيه بنفس الليلة، وطلعت للنهر، ونجت.', "She swam through it that same night, came out into the river, and was saved."),
    ('السمكة النص نص قالت: خلينا نشوف بكرا. يمكن ما يرجعوا.', "The middling fish said: let us see tomorrow. Perhaps they will not come back."),
    ('والغافلة قالت: صيادين؟ أنا عايشة هون من سنين وما صار إشي.', "And the heedless one said: fishermen? I have lived here for years and nothing has happened.")),
  P(('تاني يوم الصبح رجعوا الصيادين، ومعهم شبك.', "The next morning the fishermen returned, and with them nets."),
    ('وأول إشي عملوه، سكروا المجرى بحجر.', "And the first thing they did was block the channel with a stone."),
    ('السمكة النص نص شافت الحجر، وفهمت إن الطريق سكر.', "The middling fish saw the stone, and understood the road was closed."),
    ('فكرت بسرعة. وقالت: ما بقدر أهرب، بس بقدر أعمل حالي ميتة.', "She thought fast. And she said: I cannot flee, but I can play dead."),
    ('قلبت على ظهرها وطفت عالمي، وما تحركت.', "She turned on her back, floated on the water, and did not move."),
    ('الصياد مسكها وشمها وقال: هاي ميتة من زمان.', "The fisherman grabbed her, smelled her and said: this one has been dead a long time."),
    ('ورماها عالشط، وهي انزحفت للنهر ونجت.', "And he threw her onto the bank, and she wriggled to the river and was saved.")),
  P(('أما الغافلة، فضلت تسبح يمين وشمال.', "As for the heedless one, she kept swimming left and right."),
    ('كل ما تيجي الشبكة، تهرب لجهة، وتلاقي شبكة تانية.', "Every time the net came, she fled to one side, and found another net."),
    ('وبالآخر انمسكت.', "And in the end she was caught."),
    ('قال بيدبا: التفكير قبل الخطر أحسن من التفكير بعده.', "Bidpai said: thinking before danger is better than thinking after it."),
    ('والتفكير بعده أحسن من ولا تفكير.', "And thinking after it is better than no thinking at all."),
    ('قال الملك: وأنا أي سمكة؟', "The king said: and which fish am I?"),
    ('ضحك بيدبا وقال: اللي بيسأل هالسؤال، ما بيكون التالتة.', "Bidpai laughed and said: whoever asks that question is not the third."))]),

 ('The Hare and the Lion', 'الأرنب والأسد', [
  P(('قال بيدبا: بغابة تانية، كان في أسد.', "Bidpai said: in another forest, there was a lion."),
    ('كان بياكل من الحيوانات كل يوم.', "He ate from the animals every day."),
    ('ما كان يصيد واحد وبس. كان يقتل كتار، وياكل واحد.', "He did not hunt just one. He killed many, and ate one."),
    ('الحيوانات خافت إنها تخلص كلها.', "The animals feared they would all be finished."),
    ('فاجتمعوا وراحوا عنده وقالوا: يا ملك، عنا اقتراح.', "So they gathered, went to him and said: my king, we have a proposal."),
    ('كل يوم منبعت واحد من عنا لحاله، تاكله بلا تعب.', "Every day we send you one of us by himself, for you to eat without effort."),
    ('وإنت ما بتطلع للصيد ولا بتقتل غيره.', "And you do not go out hunting or kill anyone else."),
    ('الأسد فكر، ووافق. الأكل بيجي لحاله، ليش يتعب؟', "The lion thought, and agreed. The food comes by itself; why should he tire himself?")),
  P(('ومرت الأيام، وكل يوم بيروح واحد وما بيرجع.', "And the days passed, and every day one went and did not come back."),
    ('وبيوم، إجا الدور على أرنب زغير.', "And one day, the turn came to a small hare."),
    ('كان زغير، بس كان أذكى واحد بالغابة.', "He was small, but he was the cleverest one in the forest."),
    ('قال للحيوانات: أنا رايح، بس خلوني أروح على مهلي.', "He said to the animals: I am going, but let me go in my own time."),
    ('وإذا رجعت، بترجع الغابة كلها معي.', "And if I come back, the whole forest comes back with me."),
    ('ما فهموا شو قصده، بس تركوه.', "They did not understand what he meant, but they let him go.")),
  P(('الأرنب راح عالقصد متأخر. تأخر لحد بعد الظهر.', "The hare went late on purpose. He delayed until after noon."),
    ('لما وصل، كان الأسد جعان وغضبان.', "When he arrived, the lion was hungry and angry."),
    ('زعق: وين كنت؟ وليش إجيت لحالك زغير هيك؟', "He roared: where were you? And why have you come alone, small like this?"),
    ('قال الأرنب وهو بيرجف: يا ملك، ما جيت لحالي.', "The hare said, trembling: my king, I did not come alone."),
    ('بعتوني مع أرنب تاني، أكبر مني وأسمن.', "They sent me with another hare, bigger and fatter than me."),
    ('بس بالطريق طلع علينا أسد، وأخده.', "But on the road a lion came out at us, and took him."),
    ('قال الأسد: أسد؟ بغابتي؟', "The lion said: a lion? In my forest?"),
    ('قال الأرنب: وقال إنه هو الملك، مش إنت.', "The hare said: and he said that he is the king, not you.")),
  P(('قام الأسد، وشعره وقف. قال: وديني عليه.', "The lion rose, his mane bristling. He said: take me to him."),
    ('مشى الأرنب قدامه لحد ما وصل على بير قديم وعميق.', "The hare walked ahead of him until he reached an old, deep well."),
    ('قال: هو هون، تحت، مستخبي.', "He said: he is here, below, hiding."),
    ('الأسد طل بالبير، وشاف أسد تحت.', "The lion looked into the well, and saw a lion below."),
    ('كان خياله بالمي، بس هو ما عرف.', "It was his reflection in the water, but he did not know."),
    ('زعق عليه، والأسد اللي تحت زعق كمان.', "He roared at it, and the lion below roared too."),
    ('ورجع الصوت من البير أقوى من صوته.', "And the sound came back from the well stronger than his own voice.")),
  P(('قال الأسد: بتزعق عليّ؟ أنا الملك!', "The lion said: you roar at me? I am the king!"),
    ('ونط على خياله.', "And he leapt at his reflection."),
    ('ووقع بالبير، وما طلع.', "And he fell into the well, and never came out."),
    ('رجع الأرنب على الغابة لحاله، وقال: خلص.', "The hare went back to the forest alone, and said: it is done."),
    ('وما حدا صدق، لحد ما راحوا وشافوا البير.', "And no one believed him, until they went and saw the well."),
    ('قال بيدبا: القوي اللي ما بيفكر، بيقتله الضعيف اللي بيفكر.', "Bidpai said: the strong one who does not think is killed by the weak one who does."),
    ('وأكتر إشي بيقتل الملك، إنه يشوف عدو بكل مكان.', "And the thing that kills a king most is seeing an enemy everywhere."))]),

 ('The Ringdove and the Net', 'الحمامة المطوقة والشبكة', [
  P(('قال بيدبا: هلق بدي أحكي عن الأصحاب.', "Bidpai said: now I want to tell you about friends."),
    ('لأنه الأصحاب أهم من الملك.', "Because friends matter more than the king."),
    ('كان في شجرة كبيرة جنب مدينة، وعليها عش غراب.', "There was a big tree beside a city, and in it a crow's nest."),
    ('بيوم، شاف الغراب صياد ماشي تحت الشجرة.', "One day, the crow saw a hunter walking under the tree."),
    ('ومعه شبكة وحبة قمح.', "And with him a net and grains of wheat."),
    ('الصياد فرش الشبكة على الأرض، ورش الحبة فوقها، واستخبى.', "The hunter spread the net on the ground, scattered the grain over it, and hid."),
    ('قال الغراب: هاد جاي عشان حدا، وأنا بدي أشوف مين.', "The crow said: this one has come for someone, and I want to see who.")),
  P(('بعد شوي، مر سرب حمام بالسما.', "A little later, a flock of doves passed in the sky."),
    ('قدامهم حمامة كبيرة، على رقبتها طوق، واسمها المطوقة.', "At their head was a big dove, with a ring around her neck, and her name was the Ringdove."),
    ('الحمام شاف الحبة من فوق، وقال: أكل!', "The doves saw the grain from above, and said: food!"),
    ('قالت المطوقة: استنوا. حبة بنص الأرض بلا سبب؟', "The Ringdove said: wait. Grain in the middle of the ground for no reason?"),
    ('بس كانوا جوعانين، وما سمعوا.', "But they were hungry, and did not listen."),
    ('نزلوا كلهم عالأرض، ونزلت معهم، ووقعوا كلهم بالشبكة.', "They all came down to the ground, and she came down with them, and they all fell into the net.")),
  P(('صار كل حمامة تشد لجهتها.', "Each dove began pulling its own way."),
    ('وحدة لليمين ووحدة للشمال ووحدة لفوق.', "One to the right, one to the left, one upward."),
    ('والشبكة ما تحركت أبداً، لأنه كل شدة بتلغي التانية.', "And the net did not move at all, because each pull cancelled the other."),
    ('والصياد طلع من مخبأه وبلش يمشي باتجاههم، وهو بيضحك.', "And the hunter came out of his hiding place and started walking toward them, laughing."),
    ('قالت المطوقة: اسمعوا! إذا ضلينا هيك، منموت كلنا.', "The Ringdove said: listen! If we go on like this, we all die."),
    ('لا حدا يشد لحاله. كلكم اشحدوا مع بعض، لفوق، بنفس اللحظة.', "Let no one pull alone. All of you pull together, upward, at the same moment."),
    ('لما بعد: واحد، اتنين، تلاتة!', "When I count: one, two, three!")),
  P(('عدت، وشدوا كلهم سوا.', "She counted, and they all pulled together."),
    ('والشبكة طلعت من الأرض، وطارت معهم.', "And the net came up from the ground, and flew off with them."),
    ('الصياد ركض وراهم، ورجع الشبك بسمى وهو بيتطلع لفوق.', "The hunter ran after them, watching the net in the sky as he looked up."),
    ('قال: رح يوقعوا. شبكة تقيلة، وحمام.', "He said: they will fall. A heavy net, and doves."),
    ('بس المطوقة قادتهم فوق الجبل، وبعد الجبل، لمكان ما بيوصله.', "But the Ringdove led them over the mountain, and beyond the mountain, to a place he could not reach."),
    ('والغراب طار وراهم، لأنه بده يشوف كيف بتخلص القصة.', "And the crow flew after them, because he wanted to see how the story ended."))]),

 ('The Mouse Who Cut the Net', 'الفار اللي قص الشبكة', [
  P(('طار الحمام لحد ما وصلوا على تلة، وفيها جحر فار.', "The doves flew until they reached a hill, and in it was a mouse's hole."),
    ('الفار اسمه زيرك، وكان صاحب المطوقة من زمان.', "The mouse was named Zirak, and he had long been the Ringdove's friend."),
    ('كان عنده مية باب لجحره، عشان يهرب من مية خطر.', "He had a hundred doors to his hole, to escape a hundred dangers."),
    ('نادت المطوقة: يا زيرك! يا صاحبي!', "The Ringdove called: Zirak! My friend!"),
    ('طلع الفار من باب، وشاف الشبكة والحمام جواها، وفهم.', "The mouse came out of one door, saw the net and the doves inside it, and understood.")),
  P(('ركض زيرك على الشبكة، وبلش يقص الحبال بأسنانه.', "Zirak ran to the net, and began cutting the ropes with his teeth."),
    ('بس بلش من حمامة تانية، مش من المطوقة.', "But he began with another dove, not with the Ringdove."),
    ('قالت المطوقة: يا زيرك، أنا صاحبتك. ليش مش مني أنا الأول؟', "The Ringdove said: Zirak, I am your friend. Why not from me first?"),
    ('قال الفار وهو بيقص: عشان هيك بالضبط.', "The mouse said as he cut: for exactly that reason."),
    ('أسناني رح تتعب، ويمكن أوقف قبل ما أخلص.', "My teeth will tire, and perhaps I will stop before I finish."),
    ('إذا بلشت منك، رح تكوني حرة والباقيين محبوسين.', "If I begin with you, you will be free and the rest still caught."),
    ('وبيقولوا: القائدة نجت ونستنا.', "And they will say: the leader saved herself and forgot us.")),
  P(('بس إذا بلشت منهم، رح أضل أقص لحد ما أوصلك.', "But if I begin with them, I will keep cutting until I reach you."),
    ('لأني بعرف إنك آخر وحدة، وما بقدر أتركك.', "Because I know you are the last, and I cannot leave you."),
    ('قالت المطوقة: عشان هيك إنت صاحبي.', "The Ringdove said: this is why you are my friend."),
    ('وقص الفار حمامة ورا حمامة، وهم يطيروا وحدة وحدة.', "And the mouse cut dove after dove, and they flew off one by one."),
    ('وبالآخر قص حبل المطوقة، وطارت.', "And last he cut the Ringdove's rope, and she flew.")),
  P(('قال بيدبا: القائد بيتحرر آخر واحد.', "Bidpai said: a leader is freed last."),
    ('واللي بيطلع أول، ما بيكون قائد، بيكون هارب.', "And whoever gets out first is not a leader, he is a runaway."),
    ('قال الملك: وهاد الفار، من وين تعلم هالحكمة؟', "The king said: and this mouse, where did he learn this wisdom?"),
    ('قال بيدبا: من مية باب. اللي بيفكر بمية خطر، بيفكر بمية صاحب.', "Bidpai said: from a hundred doors. Whoever thinks of a hundred dangers thinks of a hundred friends."),
    ('والغراب اللي كان بيتفرج، قرر إشي.', "And the crow who had been watching decided something."))]),

 ('The Four Friends', 'الأصحاب الأربعة', [
  P(('نزل الغراب على التلة، ووقف قدام جحر الفار.', "The crow came down onto the hill, and stood before the mouse's hole."),
    ('نادى: يا زيرك، اطلع. بدي أصير صاحبك.', "He called: Zirak, come out. I want to be your friend."),
    ('طلع الفار راسه من باب بعيد، وقال: إنت؟ إنت غراب!', "The mouse put his head out of a far door, and said: you? You are a crow!"),
    ('الغربان بتاكل الفيران. كيف بدك تصير صاحبي؟', "Crows eat mice. How can you be my friend?"),
    ('قال الغراب: شفت شو عملت للحمام.', "The crow said: I saw what you did for the doves."),
    ('وقلت: واحد هيك، بدي أكون صاحبه، مش آكله.', "And I said: one like this, I want to be his friend, not eat him.")),
  P(('قال الفار: الطبع أقوى من الكلام.', "The mouse said: nature is stronger than words."),
    ('اليوم بتقول صاحبي، وبكرا لما تجوع، بتتذكر إني فار.', "Today you say friend, and tomorrow when you get hungry, you remember that I am a mouse."),
    ('قال الغراب: أنا بغير طبعي عشانك.', "The crow said: I will change my nature for you."),
    ('وإذا ما بتصدق، أنا بضل هون عند بابك لحد ما تصدق.', "And if you do not believe me, I will stay here at your door until you do."),
    ('وقعد الغراب عند الباب يوم، ويومين، وتلاتة.', "And the crow sat at the door a day, two days, three."),
    ('كان يجيب أكل ويحطه عند الباب ويرجع لمكانه.', "He would bring food, put it at the door, and go back to his place."),
    ('وباليوم الرابع، طلع الفار وقعد جنبه.', "And on the fourth day, the mouse came out and sat beside him.")),
  P(('صاروا أصحاب، ومع الأيام، صار الفار يركب على ظهر الغراب.', "They became friends, and with the days, the mouse began riding on the crow's back."),
    ('وطاروا سوا لغدير كبير، فيه سلحفاة كانت صاحبة الغراب.', "And they flew together to a big pond, where there was a tortoise who was the crow's friend."),
    ('السلحفاة كانت هادية وبطيئة، بس كلامها بيسوى.', "The tortoise was calm and slow, but her words were worth something."),
    ('قالت: أهلاً بالفار. صاحب صاحبي صاحبي.', "She said: welcome to the mouse. My friend's friend is my friend."),
    ('وعاشوا التلاتة جنب المي.', "And the three lived beside the water."),
    ('وكل يوم بيحكوا لحد ما تغيب الشمس.', "And every day they talked until the sun went down.")),
  P(('وبيوم، إجت غزالة راكضة عالغدير، وخايفة.', "And one day, a gazelle came running to the pond, afraid."),
    ('شربت بسرعة، وصارت تتطلع ورا.', "She drank quickly, and kept looking behind her."),
    ('قالت السلحفاة: مالك؟ ما في صيادين هون.', "The tortoise said: what is wrong? There are no hunters here."),
    ('قالت الغزالة: كان في. هربت منهم من الصبح.', "The gazelle said: there were. I have been fleeing them since morning."),
    ('قال الغراب: خلص، اقعدي معنا. هون بأمان.', "The crow said: enough, stay with us. Here you are safe."),
    ('وصارت الغزالة رابعتهم.', "And the gazelle became their fourth."),
    ('قال بيدبا: غراب وفار وسلحفاة وغزالة. ما حدا فيهم بيشبه التاني.', "Bidpai said: a crow, a mouse, a tortoise and a gazelle. None of them resembled the other."),
    ('وهاد اللي خلاهم ينجوا.', "And that is what saved them."))]),

 ('The Gazelle in the Trap', 'الغزالة بالفخ', [
  P(('بيوم، راحت الغزالة ترعى زي كل يوم، وما رجعت.', "One day, the gazelle went to graze as she did every day, and did not return."),
    ('غابت الشمس، وهي لسا مش هون.', "The sun set, and she still was not there."),
    ('قالت السلحفاة: الغزالة ما بتتأخر. صار لها إشي.', "The tortoise said: the gazelle is never late. Something has happened to her."),
    ('قال الغراب: أنا بطير وبدور عليها من فوق.', "The crow said: I will fly and look for her from above."),
    ('وطار فوق الغابة، يدور ويدور.', "And he flew over the forest, searching and searching.")),
  P(('لقاها بالآخر، جنب الطريق، واقعة بفخ صياد.', "He found her at last, beside the road, caught in a hunter's trap."),
    ('الحبل ملفوف على إجرها، وهي ما بتقدر تتحرك.', "The rope was wound around her leg, and she could not move."),
    ('قالت: يا غراب، روح، الصياد رح يرجع الصبح.', "She said: crow, go, the hunter will return in the morning."),
    ('قال الغراب: بروح، بس برجع.', "The crow said: I will go, but I will come back."),
    ('طار للغدير، وحمل الفار على ظهره، ورجع.', "He flew to the pond, carried the mouse on his back, and returned."),
    ('والفار بلش يقص الحبل بأسنانه، حبل ورا حبل.', "And the mouse began cutting the rope with his teeth, strand after strand.")),
  P(('بس السلحفاة ما قدرت تقعد لحالها.', "But the tortoise could not stay by herself."),
    ('قالت: صاحبتي بخطر وأنا قاعدة؟', "She said: my friend is in danger and I sit?"),
    ('وإجت مشي، على مهلها، لأنها بطيئة.', "And she came on foot, slowly, because she is slow."),
    ('لما وصلت، كان الفار خلص الحبل، والغزالة صارت حرة.', "When she arrived, the mouse had finished the rope, and the gazelle was free."),
    ('قال الغراب: يا سلحفاة، ليش جيتي؟ إنتي ما بتقدري تهربي!', "The crow said: tortoise, why did you come? You cannot run!"),
    ('وبنفس اللحظة، بان الصياد من بعيد.', "And in that same moment, the hunter appeared from afar.")),
  P(('الغزالة ركضت، والفار فات بجحر، والغراب طار.', "The gazelle ran, the mouse went into a hole, and the crow flew up."),
    ('بس السلحفاة ضلت مكانها.', "But the tortoise stayed where she was."),
    ('الصياد لقى الفخ فاضي، وزعل، وبعدين شاف السلحفاة.', "The hunter found the trap empty, was angry, and then saw the tortoise."),
    ('قال: ولا إشي أحسن من ولا إشي.', "He said: nothing is better than nothing."),
    ('ربطها بحبل وحطها بكيس، ومشى.', "He tied her with a rope, put her in a sack, and walked on."),
    ('الأصحاب التلاتة شافوا اللي صار من بعيد.', "The three friends saw what happened from afar."),
    ('قال الغراب: إحنا التلاتة نجونا، والرابعة انمسكت. لازم نرجعها.', "The crow said: the three of us are saved, and the fourth is caught. We must get her back.")),
  P(('عملوا خطة.', "They made a plan."),
    ('الغزالة راحت ووقفت قدام الصياد بالطريق، وعملت حالها عرجا.', "The gazelle went and stood in front of the hunter on the road, and pretended to be lame."),
    ('والغراب وقف على ظهرها، زي إنه بينقرها، زي إنها ميتة.', "And the crow perched on her back, as if pecking at her, as if she were dead."),
    ('قال الصياد: غزالة عرجا! هاي أحسن من سلحفاة.', "The hunter said: a lame gazelle! This is better than a tortoise."),
    ('حط الكيس عالأرض وركض وراها.', "He put the sack on the ground and ran after her."),
    ('وكل ما يقرب، تبعد الغزالة شوي، وكل ما يقرب، تبعد شوي.', "And each time he came near, the gazelle moved a little away, and each time he came near, a little away."),
    ('وبهالوقت، الفار قص حبل الكيس، وطلعت السلحفاة.', "And in that time, the mouse cut the rope of the sack, and the tortoise came out."),
    ('لما رجع الصياد بلا غزالة، لقى الكيس فاضي كمان.', "When the hunter came back without the gazelle, he found the sack empty too."),
    ('قال بيدبا: اللي عندهم أصحاب ما بيضيعوا.', "Bidpai said: those who have friends are not lost."))]),

 ('The Owls and the Crows', 'البوم والغربان', [
  P(('قال بيدبا: وهلق بدي أحكي عن العدو.', "Bidpai said: and now I want to tell you about the enemy."),
    ('لأنه اللي ما بيعرف عدوه بيموت.', "Because whoever does not know his enemy dies."),
    ('كان في جبل، وعلى الجبل شجرة كبيرة فيها ألف عش غراب.', "There was a mountain, and on the mountain a big tree with a thousand crows' nests."),
    ('وقريب منها مغارة، فيها ألف بومة.', "And near it a cave, with a thousand owls."),
    ('وبين البوم والغربان عداوة قديمة.', "And between the owls and the crows there was an old enmity."),
    ('ما حدا بيتذكر من وين إجت.', "No one remembered where it came from."),
    ('البوم بيشوفوا بالليل والغربان بالنهار.', "Owls see at night and crows by day."),
    ('فكل واحد كان بيهجم لما التاني أعمى.', "So each attacked when the other was blind.")),
  P(('بليلة، هجم البوم على الشجرة.', "One night, the owls attacked the tree."),
    ('الغربان كانوا نايمين وما بيشوفوا، والبوم قتلوا منهم كتار.', "The crows were asleep and could not see, and the owls killed many of them."),
    ('لما طلعت الشمس، البوم رجعوا لمغارتهم.', "When the sun rose, the owls returned to their cave."),
    ('والغربان قعدوا على الأرض يبكوا.', "And the crows sat on the ground weeping."),
    ('ملك الغربان جمع الوزرا وقال: شو نعمل؟', "The king of the crows gathered the ministers and said: what do we do?"),
    ('قال واحد: نهرب لجبل تاني.', "One said: we flee to another mountain."),
    ('قال تاني: نهجم عليهم بالنهار.', "Another said: we attack them by day."),
    ('قال تالت: نعطيهم الشجرة ونطلب الصلح.', "A third said: we give them the tree and ask for peace."),
    ('وكل رأي كان فيه غلط.', "And every opinion had a flaw.")),
  P(('كان في غراب كبير بالعمر، وعاقل، وكان ساكت.', "There was a crow old in years, and wise, and he was silent."),
    ('قال الملك: وإنت، شو رأيك؟', "The king said: and you, what do you think?"),
    ('قال الغراب الكبير: نهرب، بيلحقونا. نهجم، بيقتلونا. نطلب صلح، بيذلونا.', "The old crow said: if we flee, they follow us. If we attack, they kill us. If we ask peace, they humiliate us."),
    ('في طريق رابع، بس محدا رح يحبه.', "There is a fourth way, but no one will like it."),
    ('قال الملك: احكي.', "The king said: speak."),
    ('قال: لازم أفوت بينهم.', "He said: I must go in among them."),
    ('وعشان يصدقوني، لازم تنتفوا ريشي وتضربوني.', "And for them to believe me, you must pluck my feathers and beat me."),
    ('وبعدين ترموني تحت الشجرة.', "And then throw me under the tree.")),
  P(('الغربان صرخوا: مستحيل! إنت أكبر واحد فينا!', "The crows cried: impossible! You are the eldest of us!"),
    ('قال الغراب الكبير: عشان هيك أنا. الزغير ما بيصدقوه.', "The old crow said: that is why it is me. A young one they would not believe."),
    ('وبعدين، لما تشوفوني مرمي، لا تبكوا. ارجعوا لأعشاشكم واستنوا.', "And then, when you see me thrown down, do not weep. Go back to your nests and wait."),
    ('وهيك صار. نتفوا ريشه، وضربوه، ورموه.', "And so it was. They plucked his feathers, beat him, and threw him down."),
    ('وطاروا وتركوه على الأرض، وهم يبكوا بصمت.', "And they flew away and left him on the ground, weeping in silence."),
    ('وإجا الليل.', "And night came."))]),

 ('The Crow Among the Owls', 'الغراب بين البوم', [
  P(('بالليل، إجا البوم يهجموا مرة تانية.', "At night, the owls came to attack again."),
    ('ولقوا الغراب مرمي تحت الشجرة.', "And they found the crow thrown down under the tree."),
    ('كان مجروح وبلا ريش، وبالكاد بيحكي.', "He was wounded and featherless, and could barely speak."),
    ('قال ملك البوم: مين إنت؟ ومين عمل فيك هيك؟', "The king of the owls said: who are you? And who did this to you?"),
    ('قال الغراب: أنا وزير ملك الغربان.', "The crow said: I am the minister of the king of the crows."),
    ('قلت له: البوم أقوى من عنا، لازم نطلب الصلح ونعطيهم الشجرة.', "I told him: the owls are stronger than us; we must ask for peace and give them the tree."),
    ('فقال إني خاين، ونتف ريشي، ورماني.', "So he said I was a traitor, plucked my feathers, and threw me out.")),
  P(('وزرا البوم اختلفوا.', "The owls' ministers disagreed."),
    ('قال واحد: اقتلوه. الغراب غراب، وإن حكى حلو.', "One said: kill him. A crow is a crow, even if he speaks sweetly."),
    ('العدو اللي بتاخده لبيتك أخطر من اللي برا.', "The enemy you take into your house is more dangerous than the one outside."),
    ('بس ملك البوم شاف الجروح وقال: هاد مسكين، وبيعرف أسرارهم.', "But the king of the owls saw the wounds and said: this poor thing knows their secrets."),
    ('خدوه على المغارة، وأطعموه، وعالجوه.', "They took him to the cave, fed him, and healed him."),
    ('والوزير اللي قال اقتلوه، زعل وترك المغارة.', "And the minister who had said to kill him was angry and left the cave."),
    ('وراح يعيش لحاله.', "And he went to live alone."),
    ('قال: أنا ما ببيت مع الموت.', "He said: I do not sleep with death.")),
  P(('ضل الغراب بين البوم شهور.', "The crow stayed among the owls for months."),
    ('كان ساكت، ويخدم، ويتفرج.', "He was silent, and served, and watched."),
    ('عد كل باب بالمغارة، وكل بومة، وعرف وين بيناموا بالنهار.', "He counted every door in the cave, and every owl, and learned where they slept by day."),
    ('وريشه رجع طلع، شوي شوي.', "And his feathers grew back, little by little."),
    ('وبيوم، لما صار يقدر يطير، راح عند ملك البوم.', "And one day, when he could fly again, he went to the king of the owls."),
    ('قال له: بدي أطلع أجيب حطب، عشان تدفوا بالشتا.', "He said to him: I want to go out and bring firewood, so you can keep warm in the winter."),
    ('وطلع، وصار يجيب حطب ويحطه عند باب المغارة.', "And he went out, and began bringing wood and piling it at the cave door."),
    ('كل يوم شوي، لحد ما صار الباب كله حطب.', "A little every day, until the whole doorway was wood.")),
  P(('وبيوم، بالنهار، والبوم نايمين جوا، طار الغراب على الشجرة.', "And one day, by daylight, with the owls asleep inside, the crow flew to the tree."),
    ('قال للغربان: جيبوا نار.', "He said to the crows: bring fire."),
    ('كل غراب حمل جمرة من نار الرعيان، وطاروا على المغارة.', "Every crow carried an ember from the shepherds' fires, and they flew to the cave."),
    ('رموا الجمر عالحطب، والحطب ولع.', "They threw the embers on the wood, and the wood caught."),
    ('والبوم اللي جوا ما قدروا يطلعوا.', "And the owls inside could not get out."),
    ('لأنه الباب كان نار، والنهار أعمى.', "Because the doorway was fire, and the day was blind."),
    ('وهيك خلصت العداوة القديمة.', "And so the old enmity ended."),
    ('قال بيدبا: العدو اللي بتاخده لبيتك أخطر من اللي برا.', "Bidpai said: the enemy you take into your house is more dangerous than the one outside."),
    ('والوزير اللي قالها، كان الوحيد اللي عاش.', "And the minister who said it was the only one who lived."))]),

 ('The Monkey and the Tortoise', 'القرد والسلحفاة', [
  P(('قال بيدبا: بشط بحر، كان في شجرة تين كبيرة.', "Bidpai said: on a seashore, there was a big fig tree."),
    ('وعلى الشجرة عاش قرد، كان ملك القرود زمان، وكبر وطردوه.', "And in the tree lived a monkey, who had once been king of the monkeys, and grew old and was driven out."),
    ('كان لحاله، وكل يوم بياكل تين ويرمي البقايا بالمي.', "He was alone, and every day he ate figs and threw the leftovers into the water."),
    ('وبيوم، سمع صوت من تحت الشجرة بيقول: شكراً!', "And one day, he heard a voice from under the tree saying: thank you!"),
    ('كانت سلحفاة، طلعت من البحر تاكل التين اللي بيوقع.', "It was a tortoise, come out of the sea to eat the figs that fell."),
    ('ومن هاليوم، صاروا أصحاب.', "And from that day, they were friends.")),
  P(('كل يوم، كان القرد يرمي تين للسلحفاة، ويحكوا لحد المسا.', "Every day, the monkey threw figs to the tortoise, and they talked until evening."),
    ('والسلحفاة صارت ترجع لبيتها متأخرة.', "And the tortoise began returning home late."),
    ('مرت السلحفاة زعلت. قالت لجارتها: زوجي صار له صاحب، ونسيني.', "The tortoise's wife grew jealous. She said to her neighbour: my husband has found a friend, and forgotten me."),
    ('قالت الجارة: اعملي حالك مريضة. وقولي إنه ما في دوا إلا قلب قرد.', "The neighbour said: pretend to be ill. And say there is no cure but a monkey's heart."),
    ('وهيك عملت. نامت بالفراش، وما أكلت، وقالت: بدي قلب قرد.', "And so she did. She lay in bed, did not eat, and said: I need a monkey's heart.")),
  P(('السلحفاة وقعت بين صاحبها ومرتها.', "The tortoise was caught between his friend and his wife."),
    ('قال: صاحبي رح يموت، ولا مرتي رح تموت.', "He said: either my friend dies, or my wife dies."),
    ('وبالآخر راح عند القرد وقال: تعال زورني ببيتي، بدي أعزمك.', "And in the end he went to the monkey and said: come and visit me at my home; I want to have you as a guest."),
    ('قال القرد: بس بيتك بالبحر، وأنا ما بعرف أسبح.', "The monkey said: but your home is in the sea, and I cannot swim."),
    ('قالت السلحفاة: اركب على ظهري.', "The tortoise said: ride on my back."),
    ('وركب القرد، وسبحت السلحفاة، وهي حزينة وساكتة.', "And the monkey mounted, and the tortoise swam, sad and silent.")),
  P(('بنص البحر، وقفت السلحفاة، وما قدرت تكمل.', "In the middle of the sea, the tortoise stopped, and could not go on."),
    ('قال القرد: مالك؟', "The monkey said: what is wrong?"),
    ('قالت: مرتي مريضة، والدكتور قال ما بيشفيها إلا قلب قرد.', "She said: my wife is ill, and the doctor said nothing will cure her but a monkey's heart."),
    ('وأنا جايبك عشان هيك. سامحني.', "And I am bringing you for that. Forgive me."),
    ('القرد فهم، وخاف، بس ما بين عليه.', "The monkey understood, and was afraid, but did not show it."),
    ('قال بهدوء: يا صاحبي، ليش ما قلت لي من الأول؟', "He said calmly: my friend, why did you not tell me at the start?"),
    ('إحنا القرود ما بنحمل قلوبنا معنا. بنتركها عالشجرة.', "We monkeys do not carry our hearts with us. We leave them in the tree."),
    ('لو قلت لي، كنت جبته معي.', "Had you told me, I would have brought it with me.")),
  P(('قالت السلحفاة: بجد؟', "The tortoise said: really?"),
    ('قال القرد: بجد. ارجع، وبطلع بجيبه، وبنزل.', "The monkey said: really. Go back, and I will climb up, fetch it, and come down."),
    ('ورجعت السلحفاة عالشط، وهي فرحانة.', "And the tortoise went back to the shore, glad."),
    ('نط القرد على الشجرة، وطلع لأعلى غصن، وقعد.', "The monkey leapt onto the tree, climbed to the highest branch, and sat."),
    ('نادت السلحفاة: يلا، جبته؟', "The tortoise called: come on, did you get it?"),
    ('قال القرد من فوق: قلبي هون، وأنا هون، وبنضل هون.', "The monkey said from above: my heart is here, and I am here, and we are staying here."),
    ('روحي، وسلمي لي على مرتك.', "Go, and give my regards to your wife."),
    ('قال بيدبا: اللي بيفلت من الغدر، ما بيرجع له.', "Bidpai said: whoever escapes treachery does not return to it."))]),

 ('The Ascetic and the Mongoose', 'الناسك وابن عرس', [
  P(('قال بيدبا: وآخر حكاية، يا ملك، عن الاستعجال.', "Bidpai said: and the last tale, my king, is about haste."),
    ('كان في ناسك بيعيش بقرية زغيرة مع مرته.', "There was an ascetic living in a small village with his wife."),
    ('صار لهم سنين بلا أولاد، وبعدين إجا لهم ولد.', "They had been years without children, and then a boy came to them."),
    ('وقبل الولد، كان عندهم ابن عرس زغير، رباه الناسك من صغره.', "And before the boy, they had a small mongoose, which the ascetic had raised from infancy."),
    ('كان يمشي وراه بالبيت زي الكلب، وينام جنب الولد.', "It followed him about the house like a dog, and slept beside the boy."),
    ('وكان الناسك بيحبه ويصدقه زي ولده.', "And the ascetic loved it and believed it like his own son.")),
  P(('بيوم، راحت المرة تجيب مي من البير.', "One day, the wife went to fetch water from the well."),
    ('قالت للناسك: خليك مع الولد، لا تتركه.', "She said to the ascetic: stay with the boy, do not leave him."),
    ('وبعد شوي، إجا حدا من القرية ونادى الناسك.', "And a little later, someone from the village came and called the ascetic."),
    ('قال: تعال بسرعة، في واحد بده يسمع كلامك.', "He said: come quickly, there is someone who wants to hear your words."),
    ('تطلع الناسك على الولد، كان نايم، وابن عرس جنبه.', "The ascetic looked at the boy, who was sleeping, with the mongoose beside him."),
    ('قال: دقيقتين وبرجع. وطلع.', "He said: two minutes and I will be back. And he went out.")),
  P(('لما كان الناسك برا، طلعت من شق بالحيط حية كبيرة سودا.', "While the ascetic was out, a big black snake came out of a crack in the wall."),
    ('زحفت باتجاه الولد النايم.', "It slithered toward the sleeping boy."),
    ('ابن عرس شافها، ونط عليها.', "The mongoose saw it, and leapt at it."),
    ('تخانقوا على الأرض، والولد نايم ما حس.', "They fought on the floor, and the boy slept on without stirring."),
    ('وبالآخر ابن عرس قتل الحية، وقطعها.', "And in the end the mongoose killed the snake, and tore it apart."),
    ('وراح يقعد عند الباب، وتمه كله دم.', "And it went to sit at the door, its mouth all blood."),
    ('كان يستنى الناسك عشان يفرجيه.', "It was waiting for the ascetic, to show him.")),
  P(('رجع الناسك، وأول إشي شافه: ابن عرس عند الباب، وتمه دم.', "The ascetic returned, and the first thing he saw: the mongoose at the door, blood on its mouth."),
    ('ما فكر. ما سأل. ما فات يشوف.', "He did not think. He did not ask. He did not go in to look."),
    ('قال: أكل الولد!', "He said: it has eaten the boy!"),
    ('ورفع العصا اللي بإيده، وضربه على راسه، وقتله بضربة وحدة.', "And he raised the stick in his hand, struck it on the head, and killed it with one blow."),
    ('وبعدين فات.', "And then he went in."),
    ('الولد نايم، بالسلامة، وبيتنفس.', "The boy was asleep, safe, and breathing."),
    ('وجنبه حية سودا كبيرة، مقتولة ومقطعة.', "And beside him a big black snake, killed and torn apart.")),
  P(('قعد الناسك عالأرض، ونظر لابن عرس، ونظر للحية، وفهم.', "The ascetic sat on the floor, looked at the mongoose, looked at the snake, and understood."),
    ('وبكى. بكى لحد ما رجعت مرته.', "And he wept. He wept until his wife returned."),
    ('قالت: شو صار؟', "She said: what happened?"),
    ('قال: قتلت اللي أنقذ ابني، لأني ما استنيت دقيقة.', "He said: I killed the one who saved my son, because I did not wait one minute."),
    ('وما نفع البكا. اللي بيحكم بسرعة، بيندم على مهل.', "And weeping was no use. Whoever judges quickly repents slowly."),
    ('وسكت بيدبا، وخلصت الحكايات.', "And Bidpai fell silent, and the tales were finished."),
    ('والملك دبشليم ما قال إشي تلك الليلة.', "And King Dabshalim said nothing that night."),
    ('بس من تاني يوم، صار يسأل قبل ما يحكم، ويسمع قبل ما يحكي.', "But from the next day, he asked before he judged, and listened before he spoke."))]),
]

if __name__ == '__main__':
    raise SystemExit(book(BOOK_ID, BOOK_TITLE, 'intermediate', CHAPTERS, unit='Tale', unit_ar='حكاية', shelf=12,
              meta={'work': 'كليلة ودمنة', 'author': 'Ibn al-Muqaffaʿ, from the Panchatantra',
                    'year': '8th century', 'status': 'public domain — medieval'}))
