#!/usr/bin/env python3
"""Around the World in 80 Days — a full-length, chapter-by-chapter retelling in spoken Palestinian.

Jules Verne's novel is public domain. This follows the novel's full 37-chapter structure and tells
the whole story with its scenes and dialogue, graded to roughly "intermediate" level. It is a
retelling written by Claude (NOT native-validated, flagged as such) — but, as everywhere in this
project, every WORD's metadata is looked up in Maknuune by the ingest pipeline; nothing about the
words is invented.

Emits texts/book-atw80-chNN.json. Paragraph/sentence mechanics live in bookshelf.py.
Run:  python3 pipeline/book_atw80.py    then ingest each chapter + build_app.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bookshelf import P, emit_book

BOOK_ID = 'atw80'
BOOK_TITLE = {'en': 'Around the World in 80 Days', 'ar': 'حول العالم في ثمانين يوم'}

# (english title, arabic title, [paragraph, ...])
CHAPTERS = [
 ('Passepartout Finds a New Master', 'باسبارتو بيلاقي سيد جديد', [
  P(('بلندن، بحي هادي وراقي، كان في بيت كبير يعيش فيه رجل اسمه فيلياس فوغ.', 'In London, in a quiet, elegant neighborhood, there was a big house where a man named Phileas Fogg lived.'),
    ('كان رجل غني، بس محدا كان يعرف من وين جابها المصاري، ولا شو تاريخه.', "He was a rich man, but nobody knew where he got his money, nor his history."),
    ('ما كان له مرا ولا ولاد ولا أصحاب كتار.', 'He had no wife, no children, and not many friends.'),
    ('كان عضو بنادي محترم اسمه نادي الإصلاح، وهناك كان يقضي معظم وقته.', 'He was a member of a respectable club called the Reform Club, and there he spent most of his time.')),
  P(('أهم إشي بحياة فوغ كان الدقة والنظام.', 'The most important thing in Fogg\'s life was precision and order.'),
    ('كل إشي عنده كان لازم يصير بوقته بالزبط، لا دقيقة أكتر ولا دقيقة أقل.', 'Everything of his had to happen at exactly the right time, not a minute more nor a minute less.'),
    ('بهاليوم بالذات، طرد خادمه القديم لأنه جاب له مي حلاقة حرارتها غلط بشوية.', "On this very day, he had dismissed his old servant for bringing him shaving water that was a few degrees off."),
    ('فصار لازم يلاقي خادم جديد.', 'So he had to find a new servant.')),
  P(('إجا رجل فرنسي اسمه باسبارتو ليقدم على الشغل.', 'A Frenchman named Passepartout came to apply for the job.'),
    ('كان رجل قوي ومرح، وعمل بحياته شغلات كتيرة: كان مغني، ولاعب سيرك، وأستاذ رياضة.', 'He was a strong, cheerful man who had done many jobs in his life: he had been a singer, a circus performer, and a gym teacher.'),
    ('قال باسبارتو: أنا تعبت من الحياة المتحركة، وبدّي شغل هادي عند سيد مرتب.', "Passepartout said: I'm tired of the restless life, and I want a quiet job with an orderly master."),
    ('فوغ سأله كم سؤال قصير، وبعدين قال: مقبول. من هلق إنت خادمي.', 'Fogg asked him a few short questions, then said: accepted. From now on you are my servant.'))]),
 ('A Servant to His Liking', 'خادم على قد ذوقه', [
  P(('فوغ طلع من البيت وترك باسبارتو لحاله.', 'Fogg left the house and left Passepartout on his own.'),
    ('راح باسبارتو يتفرج على بيته الجديد، ولقاه نظيف ومرتب زي الساعة.', 'Passepartout went to look around his new house, and found it clean and orderly, like a clock.'),
    ('على الحيط، كان في ورقة مكتوب فيها كل شغلة ووقتها بالثانية.', 'On the wall was a paper listing every task and its exact time, to the second.'),
    ('باسبارتو انبسط كتير وقال: هاد الرجل زي الآلة، وهاي الحياة الي بحلم فيها.', "Passepartout was very pleased and said: this man is like a machine, and this is the life I've been dreaming of.")),
  P(('بس بنفس الليلة، رجع فوغ عالبيت بغير وقته، وهاد إشي ما بيصير أبدًا.', 'But that very night, Fogg came home at the wrong hour, something that never happened.'),
    ('قال لباسبارتو بهدوء: بعد عشر دقايق، أنا وإنت رح نسافر حول العالم.', 'He said to Passepartout calmly: in ten minutes, you and I are going to travel around the world.'),
    ('باسبارتو ما صدّق أذنيه، وفكر إنه سيده عم يمزح.', "Passepartout couldn't believe his ears, and thought his master was joking."),
    ('بس فوغ ما كان يمزح ولا مرة بحياته.', 'But Fogg had never joked a single time in his life.'))]),
 ('The Bet at the Club', 'الرهان بالنادي', [
  P(('لنرجع شوية للورا، لنشوف كيف صار الرهان.', 'Let us go back a little, to see how the bet came about.'),
    ('بنفس النهار، كان فوغ قاعد بالنادي مع كم واحد من أصحابه.', 'That same day, Fogg was sitting at the club with a few of his friends.'),
    ('كانوا يقروا بالجريدة عن سرقة كبيرة صارت من البنك المركزي.', 'They were reading in the paper about a big robbery at the central bank.'),
    ('حدا سرق خمسة وخمسين ألف جنيه، والشرطة عم تدوّر عليه بكل مكان.', 'Someone had stolen fifty-five thousand pounds, and the police were hunting him everywhere.')),
  P(('بعدين صار الحكي عن الدنيا، وقديش صار السفر أسرع وأسهل من زمان.', 'Then the talk turned to the world, and how much faster and easier travel had become than before.'),
    ('قال واحد منهم: صحيح، بس لسا ما بتقدر تلف الأرض كلها بوقت قصير.', "One of them said: true, but you still can't circle the whole earth in a short time."),
    ('قال فوغ بهدوء: بالعكس، الواحد بقدر يلف الدنيا بثمانين يوم بس.', 'Fogg said calmly: on the contrary, a person can go around the world in just eighty days.'),
    ('ضحكوا كلهم وقالوا: هاد إشي على الورق بس، مش بالحقيقة.', "They all laughed and said: that's only on paper, not in reality.")),
  P(('قال فوغ: أنا مستعد أراهن على عشرين ألف جنيه إني بعملها بنفسي.', "Fogg said: I'm ready to bet twenty thousand pounds that I'll do it myself."),
    ('صار في صمت، وبعدين وافقوا كلهم على الرهان.', 'There was a silence, and then they all agreed to the bet.'),
    ('قال فوغ: القطار لباريس بيطلع الليلة الساعة تمانية وخمسة وأربعين دقيقة.', 'Fogg said: the train to Paris leaves tonight at eight forty-five.'),
    ('لازم أرجع لهالنادي بعد ثمانين يوم بالزبط، يوم السبت المسا، وإلا بخسر كل إشي.', 'I must return to this club after exactly eighty days, on Saturday evening, or I lose everything.'))]),
 ('The Departure', 'الانطلاق', [
  P(('رجع فوغ عالبيت وحكى لباسبارتو، والمسكين انصدم وخاف.', "Fogg went home and told Passepartout, and the poor man was shocked and afraid."),
    ('قال له فوغ: خود شنطة صغيرة، وحط فيها بس شوية أواعي.', 'Fogg told him: take a small bag, and put in it only a few clothes.'),
    ('وحط بالشنطة مبلغ كبير من المصاري، عشرين ألف جنيه، للطريق.', 'And he put in the bag a large sum of money, twenty thousand pounds, for the journey.'),
    ('طلعوا عالمحطة وركبوا القطار الساعة تمانية وخمسة وأربعين بالزبط.', 'They went to the station and boarded the train at exactly eight forty-five.')),
  P(('فوغ كان هادي، قاعد بمكانه، ما عليه ولا هم بالدنيا.', "Fogg was calm, sitting in his seat, without a worry in the world."),
    ('أما باسبارتو، فتذكر فجأة إنه نسي يطفي ضو الغاز بغرفته!', "But Passepartout suddenly remembered he had forgotten to turn off the gas lamp in his room!"),
    ('قال لسيده، وفوغ رد ببرود: طيب، بتظل شغالة على حسابك لحد ما نرجع.', "He told his master, and Fogg replied coldly: fine, it'll keep burning at your expense until we return."),
    ('باسبارتو تنهد، وفهم إنه هالرحلة رح تكون طويلة وغريبة.', 'Passepartout sighed, understanding that this journey would be long and strange.'))]),
 ('A Stir in London', 'ضجة بلندن', [
  P(('لما صار خبر الرهان معروف، صارت لندن كلها تحكي عنه.', 'When the news of the bet became known, all of London was talking about it.'),
    ('في ناس راهنوا إنه فوغ رح ينجح، وناس تانيين راهنوا إنه رح يفشل.', 'Some people bet that Fogg would succeed, and others bet that he would fail.'),
    ('بس فجأة، طلع إشي غيّر كل إشي.', 'But suddenly, something came out that changed everything.'),
    ('الشرطة قالت إنه وصف حرامي البنك يشبه فيلياس فوغ كتير.', 'The police said that the description of the bank thief resembled Phileas Fogg closely.')),
  P(('صار في ناس تشك إنه فوغ سرق البنك، وإنه هالرحلة بس حجة ليهرب.', "Some began to suspect Fogg had robbed the bank, and that this journey was just an excuse to flee."),
    ('مخبر شاطر اسمه فيكس كان بدّه يمسك الحرامي ليصير مشهور وياخد مكافأة.', 'A clever detective named Fix wanted to catch the thief to become famous and get a reward.'),
    ('سمع إنه فوغ مسافر عالشرق، فحزم حاله وراح يلحقه.', 'He heard that Fogg was traveling east, so he packed up and went to follow him.'),
    ('قال فيكس بينه وبين حاله: أنا رح أمسك هالحرامي، ولو لفّيت الأرض كلها وراه.', 'Fix said to himself: I will catch this thief, even if I circle the whole earth after him.'))]),
 ('Fix Waits at Suez', 'فيكس بيستنى بالسويس', [
  P(('وصل فوغ لمدينة السويس بمصر، وكان فيكس مستنيه بالميناء.', 'Fogg reached the city of Suez in Egypt, and Fix was waiting for him at the port.'),
    ('فيكس كان قلقان، لأنه الورقة الرسمية الي بتخليه يمسك فوغ لسا ما وصلت من لندن.', "Fix was anxious, because the official warrant that would let him arrest Fogg still hadn't arrived from London."),
    ('بدون الورقة، ما بيقدر يعمل إشي بره إنجلترا.', 'Without the warrant, he could do nothing outside England.'),
    ('فقرر يستنى ويراقب، ويمشي وراهم لحد ما توصل الورقة.', 'So he decided to wait and watch, and follow them until the warrant arrived.')),
  P(('نزل فوغ من المركب بس ليختم جواز سفره عند القنصل.', 'Fogg got off the ship only to stamp his passport at the consul.'),
    ('فيكس شافه من بعيد، ودقّق فيه، وصار أكتر متأكد إنه هو الحرامي.', 'Fix saw him from afar, studied him, and became more sure he was the thief.'),
    ('بس محتاج يعرف وين رايح ليقدر يلحقه صح.', 'But he needed to know where he was headed in order to follow him properly.'),
    ('فراح لعند خادمه باسبارتو ليحاول يطلّع منه المعلومات.', 'So he went to his servant Passepartout to try to draw the information out of him.'))]),
 ('Passports and Police', 'الجوازات والشرطة', [
  P(('فيكس راح لعند باسبارتو وصار يحكي معه بلطف، وكإنه بس مسافر عادي.', 'Fix went to Passepartout and started talking to him kindly, as if he were just an ordinary traveler.'),
    ('باسبارتو كان تعبان، وفرحان إنه لقى حدا يحكي معه بلغته.', 'Passepartout was tired, and glad to find someone who spoke his language.'),
    ('سأله فيكس عن سيده وعن رحلته، وباسبارتو رد بكل بساطة وبراءة.', 'Fix asked him about his master and his journey, and Passepartout answered with total simplicity and innocence.'),
    ('حكى له عن الرهان، وقال: سيدي بدّه يلف الأرض بثمانين يوم!', "He told him about the bet, and said: my master wants to circle the earth in eighty days!")),
  P(('فيكس ما صدّق حظه، وقال بينه وبين حاله: هاد الرهان بس حجة ليهرب بالمصاري.', 'Fix couldn\'t believe his luck, and said to himself: this bet is just a cover to flee with the money.'),
    ('قال لباسبارتو: كل هالمصاري الي معكم، لازم تكون كتيرة.', 'He said to Passepartout: all this money you have, it must be a lot.'),
    ('باسبارتو رد: أه، ومعنا شنطة مليانة، وسيدي بيدفع كاش بكل مكان.', "Passepartout replied: yes, and we have a full bag, and my master pays cash everywhere."),
    ('فيكس ابتسم، وصار أكيد إنه على الطريق الصح.', 'Fix smiled, now certain he was on the right track.'))]),
 ('Passepartout Talks Too Much', 'باسبارتو بيحكي كتير', [
  P(('ركبوا المركب من جديد باتجاه بومباي بالهند، وفيكس معهم من بعيد.', 'They boarded the ship again toward Bombay in India, with Fix along, keeping his distance.'),
    ('باسبارتو صار يشوف فيكس بكل مكان، بكل مركب وبكل محطة.', 'Passepartout began to see Fix everywhere, on every ship and at every stop.'),
    ('بس ما شكّ فيه، وفكر إنه صار صاحبه.', "But he didn't suspect him, and thought he had become his friend."),
    ('كل مرة كان يحكي معه أكتر، ويطلّع له كل أسرار الرحلة بدون ما ينتبه.', 'Each time he talked with him more, unwittingly revealing all the journey\'s secrets.')),
  P(('فوغ ظلّ بغرفته، هادي، بيلعب الورق، وما بيهتم لا بالبحر ولا بالناس.', 'Fogg stayed in his room, calm, playing cards, caring neither for the sea nor for the people.'),
    ('كان بس يكتب بدفتره: وصلنا هون بهاليوم، متقدمين ولا متأخرين.', 'He only wrote in his notebook: we reached here on this day, ahead or behind.'),
    ('لهلق كل إشي كان ماشي حسب الخطة بالزبط.', 'So far everything was going exactly according to plan.'),
    ('بس فيكس كان مستني الفرصة، وعينه على فوغ طول الوقت.', 'But Fix was waiting for his chance, his eye on Fogg the whole time.'))]),
 ('The Red Sea and Beyond', 'البحر الأحمر وما بعده', [
  P(('المركب عبر البحر الأحمر، والجو كان حامي كتير كتير.', 'The ship crossed the Red Sea, and the weather was very, very hot.'),
    ('الركاب كانوا يتعبوا من الحر، بس فوغ ما تأثر ولا شوي.', "The passengers grew weary from the heat, but Fogg wasn't affected in the least."),
    ('بالمسا، كان يلعب الورق مع كم راكب، ويربح دايمًا بهدوء.', 'In the evening, he played cards with a few passengers, and always won, calmly.'),
    ('باسبارتو كان مبسوط، بيتفرج على المدن والموانئ الغريبة.', 'Passepartout was happy, watching the strange cities and ports.')),
  P(('بعد أيام، وصلوا مدينة عدن، وبعدها كمّلوا على المحيط الهندي.', 'After some days, they reached the city of Aden, and after it continued onto the Indian Ocean.'),
    ('البحر كان هادي، والريح كانت مناسبة، فمشيوا بسرعة منيحة.', 'The sea was calm, the wind favorable, so they went at a good speed.'),
    ('وصلوا بومباي قبل الوقت المتوقع بيومين.', 'They reached Bombay two days ahead of the expected time.'),
    ('فوغ ما فرح ولا زعل؛ بس كتب الأرقام بدفتره زي عادته.', 'Fogg neither rejoiced nor fretted; he simply wrote the figures in his notebook as usual.'))]),
 ('Trouble at the Pagoda', 'مشكلة بالمعبد', [
  P(('بومباي كانت مدينة كبيرة، مليانة ناس وألوان وروايح غريبة.', 'Bombay was a big city, full of people, colors, and strange smells.'),
    ('فوغ ظلّ بالمحطة يستنى القطار، بس باسبارتو راح يتمشى ويتفرج.', 'Fogg stayed at the station waiting for the train, but Passepartout went to walk around and look.'),
    ('كل إشي كان جديد بعينه، وحس حاله زي بحلم.', 'Everything was new to his eyes, and he felt as if in a dream.'),
    ('وبدون ما ينتبه، فوت على معبد كبير وهو لابس جزمته.', 'And without noticing, he entered a big temple while wearing his shoes.')),
  P(('هالإشي كان ممنوع وعيب كبير عند الناس هناك.', 'This was forbidden and a great offense to the people there.'),
    ('هجموا عليه بغضب، وشلحوه جزمته، وضربوه.', 'They attacked him angrily, tore off his shoes, and beat him.'),
    ('باسبارتو هرب بأسرع ما يقدر، وطلع من المعبد بلا جزمة.', 'Passepartout fled as fast as he could, and got out of the temple without shoes.'),
    ('رجع لعند فوغ خايف، بس ما حكى له عن المشكلة، خوفًا يزعل منه.', "He returned to Fogg frightened, but didn't tell him about the trouble, afraid he would be angry.")),
  P(('ركبوا القطار الي بيعبر الهند من بومباي لكلكتا.', 'They boarded the train that crosses India, from Bombay to Calcutta.'),
    ('فيكس شاف كل إشي صار بالمعبد، وفرح كتير.', 'Fix saw everything that happened at the temple, and was delighted.'),
    ('قال بينه وبين حاله: هلق معي حجة أوقّف فيها فوغ بالهند، لأنها أرض إنجليزية.', "He said to himself: now I have a pretext to stop Fogg in India, since it's British land."),
    ('بس قرر يستنى الوقت المناسب.', 'But he decided to wait for the right moment.'))]),
 ('The Elephant', 'الفيل', [
  P(('وهم بالقطار، وقف فجأة بنص الطريق، بمكان بعيد عن أي مدينة.', 'While on the train, it suddenly stopped in the middle of the way, far from any city.'),
    ('طلع إنه السكة لسا ما خلصوها، والجرايد بلندن كانت غلطانة.', "It turned out the track wasn't finished, and the newspapers in London had been wrong."),
    ('كل الركاب زعلوا ونزلوا، وصاروا يدوّروا على طريقة يكملوا فيها.', 'All the passengers, upset, got off and began looking for a way to continue.'),
    ('فوغ ظلّ هادي، وقال: لازم نلاقي حل، مش نوقف.', "Fogg stayed calm and said: we must find a solution, not stop.")),
  P(('لقى باسبارتو رجل هندي معه فيل كبير وقوي.', 'Passepartout found an Indian man with a big, strong elephant.'),
    ('فوغ عرض عليه مصاري كتيرة ليشتري الفيل، والرجل رفض بالأول.', 'Fogg offered him a lot of money to buy the elephant, and the man refused at first.'),
    ('كل ما زاد فوغ بالسعر، زاد الرجل بالرفض، لحد ما وصلوا لسعر خيالي.', 'Each time Fogg raised the price, the man refused more, until they reached a fabulous sum.'),
    ('بالآخر وافق الرجل، وأخدوا كمان دليل شاب يعرف الطريق بالغابة.', 'Finally the man agreed, and they also took a young guide who knew the way through the forest.')),
  P(('ركبوا على ظهر الفيل: فوغ وباسبارتو والدليل.', 'They rode on the elephant\'s back: Fogg, Passepartout, and the guide.'),
    ('مشيوا بغابة كثيفة وطريق وعرة لساعات.', 'They traveled through a dense forest and rough road for hours.'),
    ('باسبارتو كان مكشوش، لأنه ما ركب فيل بحياته من قبل.', "Passepartout was thrilled, because he had never ridden an elephant in his life."),
    ('الفيل كان يمشي بثبات، والدليل بيوجهه بمهارة.', 'The elephant walked steadily, and the guide directed it skillfully.'))]),
 ('The Suttee', 'المحرقة', [
  P(('وهم ماشيين بالليل، سمعوا أصوات موسيقى حزينة وشافوا ضو نار.', 'As they traveled at night, they heard sounds of sad music and saw firelight.'),
    ('الدليل قال لهم: خبّوا حالكم، هدول ناس بيعملوا طقس قديم وخطير.', 'The guide told them: hide yourselves, these people are performing an old and dangerous rite.'),
    ('قرّبوا بهدوء، وشافوا موكب كبير حوالين امرأة شابة وحلوة.', 'They approached quietly and saw a great procession around a young, beautiful woman.'),
    ('الدليل حكى: هاي أميرة اسمها عودا، مات جوزها العجوز.', 'The guide said: this is a princess named Aouda; her old husband has died.')),
  P(('حسب عادة قاسية، بدهم يحرقوها حية مع جثة جوزها بكرة الصبح.', 'According to a cruel custom, they intend to burn her alive with her husband\'s body the next morning.'),
    ('كانوا مخدّرينها بالقوة عشان ما تقاوم.', 'They had drugged her by force so she would not resist.'),
    ('فوغ سكت شوية، وبعدين قال: عنا وقت لنص الليل. لازم ننقذها.', "Fogg was silent a while, then said: we have time until midnight. We must save her."),
    ('الدليل خاف وقال: هاد إشي خطير كتير. بس فوغ كان مصمّم.', 'The guide was scared and said: this is very dangerous. But Fogg was determined.'))]),
 ('The Bold Rescue', 'الإنقاذ الجريء', [
  P(('استنوا لنص الليل، لما تعب الحراس وصاروا يناموا شوي شوي.', 'They waited until midnight, when the guards grew tired and started to doze off.'),
    ('حاولوا يوصلوا للأميرة، بس كان في حراس كتار حواليها.', 'They tried to reach the princess, but there were many guards around her.'),
    ('كل خطة جربوها فشلت، وقرب وقت الصبح، وصار فوغ حزين إنه ما قدر يعمل إشي.', "Every plan they tried failed, morning drew near, and Fogg grew sad that he couldn't do anything."),
    ('بس باسبارتو كان اختفى، ومحدا عرف وين راح.', 'But Passepartout had disappeared, and no one knew where he had gone.')),
  P(('بوقت الصبح، حطوا جثة الجوز عالنار، وحطوا الأميرة جنبها.', "At dawn, they placed the husband's body on the fire, and laid the princess beside it."),
    ('وفجأة، الجثة قامت وقفت، وحملت الأميرة، وكل الناس خافوا وهربوا!', 'And suddenly, the body rose up, lifted the princess, and all the people, terrified, fled!'),
    ('طلع إنه باسبارتو تسلل ولبس مكان الجوز الميت، وعمل هالحيلة الذكية.', "It turned out Passepartout had sneaked in and taken the dead husband's place, playing this clever trick."),
    ('ركض بالأميرة عالفيل، وهربوا كلهم بأسرع ما يقدروا.', 'He ran with the princess to the elephant, and they all escaped as fast as they could.')),
  P(('عودا كانت لسا مخدّرة شوي، وما فهمت شو صار.', 'Aouda was still a little drugged, and did not understand what had happened.'),
    ('لما صحيت، عرفت إنهم أنقذوها من موت أكيد.', 'When she came to, she realized they had saved her from certain death.'),
    ('صارت شاكرة كتير، وفوغ عاملها باحترام وأدب.', 'She became very grateful, and Fogg treated her with respect and courtesy.'),
    ('قرر ياخدها معه لمكان أمان، وصارت رابع واحد بالرحلة.', 'He decided to take her along to a safe place, and she became the fourth in the journey.'))]),
 ('Down to Calcutta', 'النزول لكلكتا', [
  P(('وصلوا لمحطة قطار، وودّعوا الدليل الشاب وشكروه.', 'They reached a train station, said goodbye to the young guide, and thanked him.'),
    ('فوغ عطاه الفيل هدية، لأنه ما عاد محتاجه.', 'Fogg gave him the elephant as a gift, since he no longer needed it.'),
    ('ركبوا القطار، ونزلوا مع النهر باتجاه كلكتا.', 'They boarded the train, and went down along the river toward Calcutta.'),
    ('عودا صارت تحكي معهم، وتشكر فوغ على شهامته.', 'Aouda began to talk with them, and to thank Fogg for his nobility.')),
  P(('سألت عودا: ليش عملت كل هالإشي عشان وحدة ما بتعرفها؟', "Aouda asked: why did you do all this for a woman you don't know?"),
    ('فوغ رد بهدوء: هاد الإشي الصح، وعنا وقت، وبس.', "Fogg replied calmly: it's the right thing, and we had time, that's all."),
    ('باسبارتو حس بفخر لسيده، لأنه رجل شجاع وطيب.', 'Passepartout felt proud of his master, because he was a brave and good man.'),
    ('لهلق، كانوا لسا بالوقت، والرحلة ماشية منيح.', 'So far, they were still on time, and the journey was going well.'))]),
 ('The Court and the Bail', 'المحكمة والكفالة', [
  P(('وصلوا كلكتا، وكانوا فرحانين إنهم لحقوا المركب لهونغ كونغ.', 'They reached Calcutta, glad to have made the ship to Hong Kong.'),
    ('بس أول ما نزلوا، جت الشرطة وأمسكت فوغ وباسبارتو.', 'But as soon as they got off, the police came and arrested Fogg and Passepartout.'),
    ('السبب كان مشكلة المعبد الي صارت ببومباي.', 'The reason was the temple trouble that had happened in Bombay.'),
    ('فيكس كان هو الي رتّب هالإشي، ليأخّرهم لحد ما توصل الورقة.', 'Fix was the one who had arranged this, to delay them until the warrant arrived.')),
  P(('راحوا عالمحكمة، والقاضي حكم عليهم بحبس وغرامة كبيرة.', 'They went to court, and the judge sentenced them to jail and a big fine.'),
    ('باسبارتو زعل كتير، لأنه هو السبب بالغلط الي صار.', 'Passepartout was very upset, because he was the cause of the mistake that had happened.'),
    ('بس فوغ ظلّ هادي، ودفع الغرامة فورًا بدون ما يتردد.', 'But Fogg stayed calm, and paid the fine at once, without hesitation.'),
    ('طلعوا من المحكمة بسرعة، وركبوا مركب اسمه رانغون باتجاه هونغ كونغ.', 'They quickly left the court, and boarded a ship called the Rangoon toward Hong Kong.'))]),
 ("Fix Doesn't Understand", 'فيكس ما بيفهم', [
  P(('فيكس كان مجنون من الغضب، لأنه فوغ طلع من إيده مرة تانية.', 'Fix was furious, because Fogg had slipped from his hands again.'),
    ('ركب نفس المركب، رانغون، وظلّ يراقبهم من بعيد.', 'He boarded the same ship, the Rangoon, and kept watching them from a distance.'),
    ('بس هالمرة، باسبارتو صار يشك فيه شوي.', 'But this time, Passepartout began to suspect him a little.'),
    ('قال بينه وبين حاله: ليش هالرجل معنا بكل مكان؟ في إشي مش مظبوط.', "He said to himself: why is this man with us everywhere? Something is not right."),),
  P(('عودا صارت جزء من المجموعة، وكانت تعامل فوغ بلطف وحنان.', 'Aouda had become part of the group, and treated Fogg with kindness and warmth.'),
    ('بس فوغ ظلّ هادي، ما بيّن مشاعره، بس كان يهتم فيها بصمت.', "But Fogg stayed calm, showing no feelings, yet caring for her in silence."),
    ('باسبارتو لاحظ هالإشي، وابتسم بينه وبين حاله.', 'Passepartout noticed this, and smiled to himself.'),
    ('المركب كمّل طريقه، وفيكس كان لسا بلا ورقة، وقلقان.', 'The ship continued on its way, and Fix was still without a warrant, and anxious.'))]),
 ('Toward Hong Kong', 'باتجاه هونغ كونغ', [
  P(('بالطريق، وقف المركب بمدينة سنغافورة لكم ساعة.', 'On the way, the ship stopped in the city of Singapore for a few hours.'),
    ('نزل فوغ وعودا يتمشوا شوي، وكانت المدينة خضرا وحلوة.', 'Fogg and Aouda went out for a short walk, and the city was green and lovely.'),
    ('فوغ قطف لعودا وردة، وهاد كان أول إشي رومانسي يعمله.', 'Fogg picked a flower for Aouda, and this was the first romantic thing he did.'),
    ('رجعوا عالمركب، وكمّلوا الطريق لهونغ كونغ.', 'They returned to the ship, and continued the way to Hong Kong.')),
  P(('بس بالطريق، إجت عاصفة قوية أخّرت المركب.', 'But on the way, a strong storm came and delayed the ship.'),
    ('باسبارتو صار يخاف على الوقت، بس فوغ ظلّ هادي زي عادته.', 'Passepartout began to worry about the time, but Fogg stayed calm as usual.'),
    ('فيكس، من ناحية تانية، كان مبسوط بالتأخير.', 'Fix, on the other hand, was pleased with the delay.'),
    ('لأنه هونغ كونغ آخر أرض إنجليزية، وهناك آخر فرصة يمسك فوغ.', 'Because Hong Kong was the last British land, and there was his last chance to catch Fogg.'))]),
 ('Each About His Business', 'كل واحد بشغلته', [
  P(('وصلوا هونغ كونغ، وكان فوغ بدّه يوصّل عودا لعند قريب إلها هناك.', 'They reached Hong Kong, and Fogg wanted to deliver Aouda to a relative of hers there.'),
    ('راح باسبارتو يسأل عن هالقريب، بس رجع بخبر مش منيح.', 'Passepartout went to ask about this relative, but came back with bad news.'),
    ('القريب سافر من زمان، وراح يعيش بأوروبا.', 'The relative had moved long ago, and gone to live in Europe.'),
    ('فقال فوغ لعودا: إذا بدّك، تعي معنا لحد لندن، وهناك بتكوني بأمان.', 'So Fogg said to Aouda: if you wish, come with us to London, and there you will be safe.')),
  P(('عودا وافقت وهي مبسوطة، لأنها ما بدها تفارقهم.', "Aouda agreed gladly, because she didn't want to leave them."),
    ('بنفس الوقت، فيكس كان محتار كتير.', 'At the same time, Fix was very torn.'),
    ('الورقة لسا ما وصلت، وفوغ رح يطلع من هونغ كونغ بكرة.', "The warrant still hadn't come, and Fogg would leave Hong Kong tomorrow."),
    ('قرر يعمل أي إشي ليوقف فوغ، ولو بطريقة مش شريفة.', 'He decided to do anything to stop Fogg, even by an unfair means.'))]),
 ('The Opium Den', 'مغارة الأفيون', [
  P(('راح فيكس لعند باسبارتو، وقرر يحكي له الحقيقة.', 'Fix went to Passepartout, and decided to tell him the truth.'),
    ('قال له: أنا مخبر، وسيدك متهم بسرقة بنك بلندن.', 'He said: I am a detective, and your master is accused of robbing a bank in London.'),
    ('باسبارتو انصدم وزعل كتير، وما صدّق ولا كلمة.', "Passepartout was shocked and very angry, and didn't believe a word."),
    ('قال: سيدي رجل شريف، وإنت كذاب! ما بسمح لك تأذيه.', "He said: my master is an honorable man, and you are a liar! I won't let you harm him."),),
  P(('فيكس خاف إنه باسبارتو رح يخبّر فوغ ويطلعوا بكير.', 'Fix was afraid Passepartout would warn Fogg and they would leave early.'),
    ('فأخده على مكان بيبيعوا فيه الأفيون، وطلب له مشروب.', 'So he took him to a place where they sold opium, and ordered him a drink.'),
    ('باسبارتو، وهو زعلان، شرب بدون ما ينتبه، وكان في دوا بينوّم.', 'Passepartout, in his anger, drank without noticing, and there was a sleeping drug in it.'),
    ('صار دايخ، ونام على الأرض، ونسي كل إشي.', 'He grew dizzy, fell asleep on the ground, and forgot everything.')),
  P(('بس قبل ما ينام، كان باسبارتو سمع خبر مهم.', 'But before falling asleep, Passepartout had heard important news.'),
    ('الباخرة لليابان، اسمها كارناتيك، رح تطلع الليلة، مش بكرة.', 'The steamer to Japan, called the Carnatic, would leave tonight, not tomorrow.'),
    ('بدّه يخبّر فوغ، بس الدوا كان أقوى منه.', 'He wanted to tell Fogg, but the drug was stronger than him.'),
    ('ظلّ نايم، وفوغ ما عرف إنه الباخرة رح تطلع بكير.', "He stayed asleep, and Fogg did not learn that the ship would leave early."))]),
 ('Fix Confronts Fogg', 'فيكس بيواجه فوغ', [
  P(('الصبح، فوغ صحي وما لقى باسبارتو بأي مكان.', "In the morning, Fogg woke and didn't find Passepartout anywhere."),
    ('راح مع عودا عالميناء، بس الباخرة كارناتيك كانت طلعت من الليل.', 'He went with Aouda to the port, but the steamer Carnatic had left in the night.'),
    ('ما فقد أعصابه، وقال بهدوء: لازم نلاقي طريقة تانية.', "He didn't lose his temper, and said calmly: we must find another way."),
    ('دوّر عالميناء لحد ما لقى مركب صغير وسريع اسمه تانكاديرا.', 'He searched the port until he found a small, fast boat called the Tankadere.')),
  P(('اتفق مع صاحب المركب إنه ياخده هو وعودا لليابان.', 'He agreed with the boat\'s owner to take him and Aouda to Japan.'),
    ('بالآخر لحظة، إجا فيكس وطلب يركب معهم.', 'At the last moment, Fix came and asked to board with them.'),
    ('فوغ وافق بلا ما يعرف مين هو بالحقيقة.', 'Fogg agreed, without knowing who he really was.'),
    ('فيكس صار محتار: بدّه فوغ يوصل إنجلترا ليمسكه، بس مش بسرعة كتير.', 'Fix grew torn: he wanted Fogg to reach England so he could arrest him, but not too fast.'))]),
 ('The Storm', 'العاصفة', [
  P(('المركب الصغير أبحر بالبحر الواسع، وكان الجو منيح بالأول.', 'The small boat set out on the wide sea, and the weather was fine at first.'),
    ('بس بنص الطريق، إجت عاصفة كبيرة وقوية.', 'But midway, a big, strong storm came.'),
    ('الموج صار زي الجبال، والمركب صار يرتفع وينزل بعنف.', 'The waves became like mountains, and the boat rose and fell violently.'),
    ('الكل خاف، بس فوغ ظلّ واقف هادي، بلا خوف.', 'Everyone was afraid, but Fogg stayed standing, calm, without fear.')),
  P(('صاحب المركب قال: لازم نوقف، وإلا رح نغرق كلنا.', 'The boat\'s owner said: we must stop, or we will all drown.'),
    ('بس فوغ عرض عليه مصاري زيادة ليكمّل بأي طريقة.', 'But Fogg offered him extra money to continue by any means.'),
    ('طمع صاحب المركب بالمكافأة، فقرر يكمّل رغم الخطر.', 'The owner, tempted by the reward, decided to continue despite the danger.'),
    ('بعد أيام صعبة، هدّت العاصفة، ووصلوا قريب من اليابان.', 'After hard days, the storm calmed, and they reached near Japan.')),
  P(('بس هلق، لازم يلاقوا باسبارتو الي ضاع منهم بهونغ كونغ.', 'But now, they had to find Passepartout, who had been lost from them in Hong Kong.'),
    ('عودا كانت قلقانة عليه، لأنها صارت تحبه زي أخ.', 'Aouda was worried about him, because she had come to love him like a brother.'),
    ('فوغ قال: رح نلاقيه، لا تخافي.', "Fogg said: we will find him, don't be afraid."),
    ('وصلوا مدينة يوكوهاما، ورايحين يدوّروا عليه.', 'They reached the city of Yokohama, off to search for him.'))]),
 ('Passepartout in Japan', 'باسبارتو باليابان', [
  P(('نرجع لباسبارتو، الي صحي من النوم وهو عالباخرة كارناتيك.', 'Back to Passepartout, who woke from sleep aboard the steamer Carnatic.'),
    ('طلع إنه لما كان دايخ، حدا ساعده وركّبه المركب بالغلط.', "It turned out that while he was dizzy, someone helped him and put him on the ship by mistake."),
    ('الباخرة أخدته لليابان وهو نايم، بلا سيده.', 'The steamer took him to Japan while he slept, without his master.'),
    ('وصل يوكوهاما، وما كان معه ولا قرش بجيبه.', "He reached Yokohama without a single coin in his pocket."),),
  P(('صار جوعان وتعبان، وما بيعرف شو يعمل بأرض غريبة.', 'He grew hungry and tired, not knowing what to do in a strange land.'),
    ('باع شوية من أواعيه عشان ياكل ويعيش.', 'He sold some of his clothes so he could eat and survive.'),
    ('لبس أواعي يابانية غريبة، وصار يتمشى بالشوارع.', 'He put on strange Japanese clothes, and went wandering the streets.'),
    ('كان حزين، بس ظلّ عنده أمل إنه يلاقي سيده.', 'He was sad, but he still had hope of finding his master.'))]),
 ("Passepartout's Long Nose", 'أنف باسبارتو الطويل', [
  P(('لقى باسبارتو فرقة سيرك بتعمل عروض للناس.', 'Passepartout found a circus troupe that performed shows for people.'),
    ('اشتغل معهم عشان ياكل، وصار جزء من عرض كبير ومشهور.', 'He worked with them to eat, and became part of a big, famous show.'),
    ('العرض اسمه "الأنوف الطويلة"، وكانوا يلبسوا أنوف طويلة مضحكة.', 'The show was called "the Long Noses," and they wore long, funny noses.'),
    ('كانوا يعملوا برج كبير من ناس واقفين فوق بعض.', 'They would build a big tower of people standing on top of each other.')),
  P(('باسبارتو كان تحت البرج، لأنه قوي، وبيتحمّل الوزن.', 'Passepartout was at the bottom of the tower, because he was strong and could bear the weight.'),
    ('صار يعمل حركات مضحكة، والناس تضحك وتصفّق له.', 'He performed funny moves, and the people laughed and clapped for him.'),
    ('بس من جوّاته، كان بس يفكر بسيده ووينه.', 'But inside, he was thinking only of his master and where he was.'),
    ('ما كان يعرف إنه فوغ وصل يوكوهاما، وعم يدوّر عليه.', "He didn't know that Fogg had reached Yokohama, and was searching for him."))]),
 ('The Reunion', 'اللقاء', [
  P(('بنفس اليوم، فوغ وعودا كانوا عم يدوّروا على باسبارتو بكل مكان.', 'That same day, Fogg and Aouda were searching for Passepartout everywhere.'),
    ('بالصدفة، راحوا يتفرجوا على عرض السيرك عشان يرتاحوا شوي.', 'By chance, they went to watch the circus show to rest a little.'),
    ('كانوا قاعدين بين الناس، ما بيعرفوا إنه باسبارتو هناك.', 'They were sitting among the people, not knowing Passepartout was there.'),
    ('وفجأة، باسبارتو شاف سيده فوغ بين المتفرجين!', 'And suddenly, Passepartout saw his master Fogg among the spectators!')),
  P(('من الفرحة، نسي حاله وطلع من مكانه بالبرج.', 'Out of joy, he forgot himself and left his spot in the tower.'),
    ('والبرج كله وقع فوق بعض، وصار في فوضى ومنظر مضحك.', 'And the whole tower collapsed, and there was chaos and a funny scene.'),
    ('ركض باسبارتو على سيده، وحضنه وهو مبسوط كتير.', 'Passepartout ran to his master, and hugged him, overjoyed.'),
    ('عودا كمان فرحت كتير، لأنها كانت خايفة عليه.', 'Aouda too was very happy, because she had been afraid for him.')),
  P(('فوغ ارتاح إنه لقى خادمه سالم، بس ما بيّن مشاعره كتير.', "Fogg was relieved to have found his servant safe, but didn't show his feelings much."),
    ('باسبارتو دفع للسيرك تعويض عن البرج الي وقع.', 'Passepartout paid the circus compensation for the tower that fell.'),
    ('طلعوا كلهم سوا، ومعهم فيكس، وركبوا باخرة كبيرة لأمريكا.', 'They all set off together, with Fix, and boarded a big steamer for America.'),
    ('كانت الباخرة اسمها "جنرال غرانت".', 'The steamer was called the "General Grant."'))]),
 ('Crossing the Pacific', 'عبور المحيط الهادي', [
  P(('الباخرة عبرت المحيط الهادي، وكان واسع وطويل بلا نهاية.', 'The steamer crossed the Pacific Ocean, which was vast and endlessly long.'),
    ('فوغ ظلّ يحسب الأيام بدقة، وكان لسا بالوقت.', 'Fogg kept counting the days precisely, and he was still on time.'),
    ('عودا صارت مشاعرها لفوغ أقوى، بس ما حكت.', "Aouda's feelings for Fogg grew stronger, but she said nothing."),
    ('كانت تراقبه بهدوء، وتعجب من قلبه الطيب تحت وشه البارد.', 'She watched him quietly, marveling at his kind heart beneath his cold face.')),
  P(('باسبارتو صار يشك بفيكس أكتر، وقرر يراقبه.', 'Passepartout grew more suspicious of Fix, and decided to watch him.'),
    ('قال بينه وبين حاله: هالرجل بيتبعنا لسبب، بس شو السبب؟', 'He said to himself: this man follows us for a reason, but what reason?'),
    ('لسا ما ربط الأمور مع بعض.', "He hadn't yet put the pieces together."),
    ('وبدون ما يعرفوا، وهم عم يعبروا المحيط، ربحوا يوم كامل بالحساب.', 'And without their knowing, as they crossed the ocean, they gained a whole day in the reckoning.'))]),
 ('A Glimpse of San Francisco', 'لمحة عن سان فرانسيسكو', [
  P(('وصلوا مدينة سان فرانسيسكو بأمريكا، وكانت مدينة كبيرة وحيوية.', 'They reached the city of San Francisco in America, a big and lively city.'),
    ('راحوا يختموا الجوازات، وبعدين يتمشوا بالشارع.', 'They went to stamp their passports, and then to walk in the street.'),
    ('بس صار في مظاهرة سياسية كبيرة، وصار في عراك بين الناس.', 'But there was a big political demonstration, and a brawl broke out among the people.'),
    ('فوغ وفيكس انحشروا بالنص، وصار في دفع وضرب.', 'Fogg and Fix got caught in the middle, and there was pushing and hitting.')),
  P(('واحد كبير حاول يضرب فوغ، بس فيكس وقف قدامه وأخد الضربة.', 'A big man tried to hit Fogg, but Fix stood in front of him and took the blow.'),
    ('فوغ شكره، وقال: رح أرد لك الجميل يوم من الأيام.', 'Fogg thanked him and said: I will repay you the favor one day.'),
    ('طلعوا من العراك بالسلامة، وأواعيهم مخربطة شوي.', 'They got out of the brawl safely, their clothes a bit disheveled.'),
    ('بعدها راحوا عالمحطة، وركبوا القطار الكبير الي بيعبر أمريكا.', 'Then they went to the station and boarded the great train that crosses America.'))]),
 ('Aboard the Pacific Railroad', 'بقطار المحيط الهادي', [
  P(('القطار طلع من سان فرانسيسكو باتجاه نيويورك بالشرق.', 'The train left San Francisco toward New York in the east.'),
    ('الطريق كان طويل كتير، بيعبر جبال وسهول وصحاري وأنهار.', 'The route was very long, crossing mountains, plains, deserts, and rivers.'),
    ('باسبارتو كان يتفرج من الشباك على بلد كبيرة وغريبة.', 'Passepartout watched from the window a big, strange land.'),
    ('كل إشي كان واسع: الأرض، والسما، والمسافات الي بلا نهاية.', 'Everything was vast: the land, the sky, the endless distances.')),
  P(('فوغ ظلّ قاعد بمكانه، بيلعب الورق زي عادته.', 'Fogg stayed in his seat, playing cards as usual.'),
    ('عودا كانت جنبه، وصاروا يحكوا شوي شوي.', 'Aouda was beside him, and they began to talk, little by little.'),
    ('باسبارتو كان مبسوط، بس عينه على فيكس دايمًا.', 'Passepartout was happy, but his eye was always on Fix.'),
    ('كان لسا بالوقت، بس الطريق قدامهم كان فيه مفاجآت كتيرة.', 'He was still on time, but the road ahead held many surprises.'))]),
 ('A Story Along the Way', 'قصة بالطريق', [
  P(('بالطريق، صعد رجل عالقطار وصار يحكي للناس قصص عن تاريخ البلد.', 'Along the way, a man got on the train and began telling people stories about the country\'s history.'),
    ('باسبارتو قعد يسمع، وكان كل إشي جديد وغريب عليه.', 'Passepartout sat listening, and everything was new and strange to him.'),
    ('تعلّم شوي عن الناس الي بيعيشوا بهالأرض الواسعة.', 'He learned a little about the people who lived in this vast land.'),
    ('بس ما طوّل، لأنه القطار كان دايمًا مستعجل.', "But it didn't last, because the train was always in a hurry."),),
  P(('فوغ ما اهتم بالقصص؛ اهتمامه كان بس بالوقت والمسافة.', "Fogg didn't care for the stories; his concern was only time and distance."),
    ('كل ساعة كان يشوف الخريطة، ويحسب وين صاروا.', 'Every hour he checked the map, and calculated where they were.'),
    ('كانوا متقدمين شوي، وهاد فرّح باسبارتو.', 'They were a little ahead, and this pleased Passepartout.'),
    ('بس القطار قرّب من مكان فيه مشاكل كتيرة.', 'But the train drew near a place with much trouble.'))]),
 ('Buffalo on the Track', 'الجاموس عالسكة', [
  P(('فجأة، وقف القطار، وطلعوا يشوفوا شو صار.', 'Suddenly, the train stopped, and they got out to see what had happened.'),
    ('كان في قطيع جاموس ضخم عم يعبر السكة، آلاف مؤلفة.', 'A huge herd of buffalo was crossing the tracks, thousands upon thousands.'),
    ('ما كان في إشي يعملوه غير إنهم يستنوا لحد ما يخلصوا.', 'There was nothing to do but wait until they finished crossing.'),
    ('ظلّوا يعبروا لساعات طويلة، والقطار واقف.', 'They kept crossing for long hours, the train standing still.')),
  P(('باسبارتو انجنّ من الغضب على هالتأخير.', 'Passepartout went mad with anger at this delay.'),
    ('صار يصرخ ويلوّح بإيديه، بس الجاموس ما اهتم فيه.', "He shouted and waved his arms, but the buffalo paid him no mind."),
    ('فوغ ظلّ هادي، قاعد بمكانه، ما عليه ولا هم.', 'Fogg stayed calm, sitting in his seat, without a worry.'),
    ('بالآخر خلص القطيع، وكمّل القطار طريقه.', 'At last the herd finished, and the train continued on its way.'))]),
 ('The Broken Bridge', 'الجسر المكسور', [
  P(('بعد شوي، وصل القطار لجسر قديم وضعيف فوق نهر عميق.', 'A while later, the train reached an old, weak bridge over a deep river.'),
    ('السائق خاف، وقال: الجسر مش قوي، ممكن يوقع تحت وزن القطار.', "The driver was afraid, and said: the bridge is not strong; it might collapse under the train's weight."),
    ('صار في نقاش بين الركاب: نستنى، ولا نجرب نعبر؟', 'A debate broke out among the passengers: do we wait, or try to cross?'),
    ('واحد اقترح فكرة جريئة: نعبر بأسرع سرعة، عشان القطار ما يثقّل على الجسر.', 'One suggested a bold idea: cross at the fastest speed, so the train doesn\'t weigh on the bridge.')),
  P(('رجّع القطار لورا، وبعدين اندفع قدام بسرعة جنونية.', 'The train backed up, then rushed forward at a mad speed.'),
    ('الكل حبس نفسه من الخوف وهو عم يعبر.', 'Everyone held their breath in fear as it crossed.'),
    ('عبر القطار الجسر بسلامة، وبعد ما عبر بلحظات، وقع الجسر بالنهر!', 'The train crossed the bridge safely, and moments after it passed, the bridge collapsed into the river!'),
    ('الكل ارتاح، وباسبارتو مسح العرق عن جبينه.', 'Everyone was relieved, and Passepartout wiped the sweat from his brow.'))]),
 ('Fogg Does His Duty', 'فوغ بيعمل واجبه', [
  P(('وهم ماشيين، هجمت مجموعة من السكان الأصليين على القطار.', 'As they went, a group of natives attacked the train.'),
    ('صار في قتال وخوف كبير بين الركاب.', 'A fight broke out and great fear spread among the passengers.'),
    ('فوغ وفيكس وباسبارتو حاربوا مع الناس ليدافعوا عن حالهم.', 'Fogg, Fix, and Passepartout fought alongside the people to defend themselves.'),
    ('فوغ كان شجاع، وحارب بهدوء وثبات، بلا خوف.', 'Fogg was brave, and fought calmly and steadily, without fear.')),
  P(('باسبارتو كان بطل؛ زحف تحت العربات ليوقف القطار عند الحصن.', 'Passepartout was a hero; he crawled under the cars to stop the train at the fort.'),
    ('نجح إنه يوقفه، وهيك خلّص الركاب من الخطر.', 'He managed to stop it, and thus saved the passengers from danger.'),
    ('بس بالهجمة، انخطف هو وكم راكب تانيين.', 'But in the attack, he and a few other passengers were seized.'),
    ('لما وقف القطار عند الحصن، اكتشفوا إنه باسبارتو مخطوف.', 'When the train stopped at the fort, they discovered Passepartout had been taken.'))]),
 ('Fix Takes Charge', 'فيكس بياخد زمام الأمور', [
  P(('فوغ قال: ما بروح وأترك خادمي بإيد الخطر.', "Fogg said: I won't go and leave my servant in danger's hands."),
    ('طلب من ضباط الحصن يعطوه جنود ليدوّر على باسبارتو.', 'He asked the fort officers to give him soldiers to search for Passepartout.'),
    ('راح فوغ بنفسه مع الجنود بالتلج والبرد.', 'Fogg went himself with the soldiers through the snow and cold.'),
    ('عودا ظلّت بالحصن، قلقانة كتير عليهم.', 'Aouda stayed at the fort, very worried about them.')),
  P(('فيكس كان بدّه يمسك فوغ، بس هلق حس إنه لازم يساعده.', 'Fix wanted to arrest Fogg, but now he felt he had to help him.'),
    ('قال لعودا: أنا رح أستنى فوغ هون، لا تخافي.', "He said to Aouda: I will wait for Fogg here, don't be afraid."),
    ('بعد ساعات، رجع فوغ وقد أنقذ باسبارتو والباقيين.', 'After hours, Fogg came back, having rescued Passepartout and the others.'),
    ('عودا فرحت كتير، بس القطار كان مشي وتركهم.', 'Aouda rejoiced, but the train had left them behind.'))]),
 ('Fogg Fights Ill Fortune', 'فوغ بيصارع الحظ', [
  P(('صاروا متأخرين، والوقت عم يضيع، والرهان صار بخطر.', 'They were now behind, time was slipping away, and the bet was in danger.'),
    ('لقوا رجل معه زحّافة بتمشي عالتلج بقوة الهوا والشراع.', 'They found a man with a sledge that moves on the snow by the power of the wind and a sail.'),
    ('ركبوا فيها، ومشيت بسرعة كبيرة فوق التلج الأبيض.', 'They boarded it, and it sped fast over the white snow.'),
    ('الجو كان بارد جدًا، بس ما كان في وقت للراحة.', 'The weather was bitterly cold, but there was no time to rest.')),
  P(('الزحّافة طارت فوق التلج زي الطير.', 'The sledge flew over the snow like a bird.'),
    ('وصلوا لمحطة قطار تانية بأسرع ما توقعوا.', 'They reached another train station faster than they expected.'),
    ('ركبوا القطار من جديد، ورايحين لمدينة نيويورك.', 'They boarded the train again, headed for the city of New York.'),
    ('فوغ حسب الوقت، وكان لسا في أمل صغير.', 'Fogg calculated the time, and there was still a small hope.'))]),
 ('Fogg Equal to the Occasion', 'فوغ على قد الموقف', [
  P(('وصلوا نيويورك، وركضوا عالميناء بأسرع ما يقدروا.', 'They reached New York, and rushed to the port as fast as they could.'),
    ('بس الباخرة الي لأوروبا كانت طلعت قبلهم بشوية بس.', 'But the ship to Europe had left just a little before them.'),
    ('مرة تانية، ضيّعوا الباخرة بفرق دقايق.', 'Once again, they missed the ship by a few minutes.'),
    ('باسبارتو حس بالذنب، لأنه بسببه صار كل هالتأخير.', 'Passepartout felt guilty, because all this delay was on his account.')),
  P(('بس فوغ ما استسلم، وراح يدوّر على أي مركب تاني.', "But Fogg didn't give up, and went to look for any other ship."),
    ('لقى مركب صغير اسمه هنريتّا، بس صاحبه ما بدّه يروح لإنجلترا.', "He found a small ship called the Henrietta, but its owner didn't want to go to England."),
    ('فوغ عرض عليه مصاري كتيرة، بس الكابتن رفض.', 'Fogg offered him a lot of money, but the captain refused.'),
    ('فوغ اتفق معه إنه بس ياخدهم لفرنسا، وركبوا المركب.', 'Fogg agreed with him only to take them to France, and they boarded the ship.'))]),
 ('Burning the Ship', 'حرق الباخرة', [
  P(('بنص الطريق، فوغ دفع للبحّارة مصاري ليطيعوه هو مش الكابتن.', 'Midway, Fogg paid the sailors money to obey him rather than the captain.'),
    ('حبسوا الكابتن بغرفته، وصار فوغ هو المسؤول عن المركب.', 'They locked the captain in his cabin, and Fogg became in charge of the ship.'),
    ('وجّه المركب باتجاه إنجلترا، والوقت عم يركض.', 'He steered the ship toward England, with time running out.'),
    ('كان لازم يوصل بأسرع ما يمكن، مهما كلّف الأمر.', 'He had to arrive as fast as possible, whatever it cost.')),
  P(('بس بالطريق، الفحم الي بيشغّل المركب خلص.', 'But on the way, the coal that runs the ship ran out.'),
    ('فأمر فوغ إنهم يحرقوا خشب المركب نفسه عشان يكمّلوا.', "So Fogg ordered them to burn the ship's own wood to keep going."),
    ('حرقوا كل إشي من خشب: الكراسي، والأبواب، والسطح.', 'They burned everything wooden: the chairs, the doors, the deck.'),
    ('لحد ما ضلّ بس هيكل الحديد، ووصلوا بر إنجلترا.', 'Until only the iron frame was left, and they reached the shore of England.'))]),
 ('The Arrest', 'الاعتقال', [
  P(('وصلوا ميناء إنجليزي، وفوغ كان فرحان إنه لسا في وقت.', 'They reached an English port, and Fogg was glad there was still time.'),
    ('بس أول ما نزل، إجا فيكس وحط إيده على كتفه.', 'But as soon as he got off, Fix came and put his hand on his shoulder.'),
    ('قال: باسم القانون، إنت معتقل!', "He said: in the name of the law, you are under arrest!"),
    ('هالمرة كانت الورقة الرسمية وصلت، فحطّوا فوغ بالحبس.', 'This time the official warrant had arrived, so they put Fogg in jail.')),
  P(('باسبارتو انجنّ من الغضب، لأنه عرف إنه فيكس كان السبب بكل التأخير.', 'Passepartout went mad with anger, realizing Fix had been the cause of all the delays.'),
    ('عودا كانت حزينة كتير، وحست إنه كل إشي ضاع.', 'Aouda was very sad, and felt that everything was lost.'),
    ('فوغ ظلّ هادي بالحبس، بس من جوّاته كان يعرف إنه الوقت عم يروح.', 'Fogg stayed calm in jail, but inside he knew the time was going.'),
    ('كل دقيقة بالحبس كانت تقرّبه أكتر من خسارة الرهان.', 'Every minute in jail brought him closer to losing the bet.'))]),
 ("Fogg's Name Again in Demand", 'اسم فوغ من جديد', [
  P(('بعد ساعات بالحبس، فتحوا الباب فجأة.', 'After hours in jail, the door suddenly opened.'),
    ('فيكس إجا وهو مكسوف، وقال: سامحني يا سيد فوغ.', 'Fix came in ashamed, and said: forgive me, Mr. Fogg.'),
    ('طلع إنه الحرامي الحقيقي انمسك من كم يوم بلندن.', 'It turned out the real thief had been caught days ago in London.'),
    ('فوغ كان بريء، وما كان له علاقة بالسرقة أبدًا.', 'Fogg was innocent, and had nothing to do with the robbery at all.')),
  P(('فوغ، لأول مرة بحياته، فقد أعصابه، وضرب فيكس ضربة وحدة.', 'Fogg, for the first time in his life, lost his temper, and struck Fix a single blow.'),
    ('وبعدين رجع هادي، وطلع من الحبس بسرعة مع عودا وباسبارتو.', 'And then he grew calm again, and left the jail quickly with Aouda and Passepartout.'),
    ('ركبوا قطار خاص لأسرع ما يقدروا للندن.', 'They took a special train as fast as they could to London.'),
    ('بس لما وصلوا، كان الوقت راح، وفوغ حس إنه خسر الرهان.', 'But when they arrived, the time was gone, and Fogg felt he had lost the bet.'))]),
 ('Fogg Wins Happiness', 'فوغ بيربح السعادة', [
  P(('رجع فوغ عالبيت هادي، بس من جوّاته كان زعلان كتير.', 'Fogg returned home calm, but inside he was very sad.'),
    ('حس إنه خسر كل إشي: المصاري، والرهان، والتعب كله على الفاضي.', 'He felt he had lost everything: the money, the bet, all the effort for nothing.'),
    ('قعد لحاله بغرفته المظلمة، ما بدّه يشوف حدا.', "He sat alone in his dark room, not wanting to see anyone."),
    ('بس عودا دقّت الباب، وقعدت جنبه.', 'But Aouda knocked on the door, and sat beside him.')),
  P(('قالت عودا: يا سيد فوغ، أنا خسرت كل إشي زيّك، بس صار عندي إنت.', 'Aouda said: Mr. Fogg, I lost everything like you, but now I have you.'),
    ('قالت بحياء: بتقبل تتجوزني؟ أنا بحبك.', 'She said shyly: will you marry me? I love you.'),
    ('فوغ، لأول مرة، بان الفرح على وشه.', "Fogg, for the first time, joy showed on his face."),
    ('قال: أنا كمان بحبك، وهاد أغلى إشي ربحته بهالرحلة.', 'He said: I love you too, and this is the most precious thing I won on this journey.'),
    ('بعت باسبارتو فورًا ليجهّز الزواج عند القسّيس.', 'He sent Passepartout at once to arrange the marriage with the priest.')),
  P(('ركض باسبارتو عالكنيسة، وبعد شوي رجع يركض ويصرخ.', 'Passepartout ran to the church, and a little later came running back, shouting.'),
    ('قال: يا سيدي! في غلط بالحساب! اليوم مش الأحد، اليوم السبت!', "He said: master! There's a mistake in the count! Today isn't Sunday, today is Saturday!"),
    ('لأنهم لفّوا الأرض باتجاه الشرق، ربحوا يوم كامل بلا ما ينتبهوا.', 'Because they had gone around the earth toward the east, they had gained a whole day without noticing.'),
    ('لسا في وقت! الرهان لسا ممكن يربحوه!', 'There was still time! The bet could still be won!')),
  P(('ركض فوغ عالنادي بأسرع ما يقدر، والكل مستنيه.', 'Fogg raced to the club as fast as he could, and everyone was waiting for him.'),
    ('دخل الباب بآخر ثانية، قبل ما يخلص الوقت بالزبط.', 'He entered the door at the last second, exactly before the time ran out.'),
    ('ربح الرهان، وربح العشرين ألف جنيه.', 'He won the bet, and won the twenty thousand pounds.'),
    ('بس أهم من الرهان، إنه ربح عودا، وصار مبسوط بحياته لأول مرة.', 'But more important than the bet, he won Aouda, and became happy in his life for the first time.'),
    ('وهيك، الرجل الدقيق الي ما كان يعرف الحب، لف الأرض ولقى قلبه.', 'And so, the precise man who had never known love circled the earth and found his heart.'))]),
]

if __name__ == '__main__':
    emit_book(BOOK_ID, BOOK_TITLE, 'intermediate', CHAPTERS, shelf=10,
              meta={'work': 'Le Tour du monde en quatre-vingts jours', 'author': 'Jules Verne',
                    'year': '1873', 'status': 'public domain'})
