#!/usr/bin/env python3
"""Collect pipeline output into one file the app can read.

Emits a .js file (not .json) that assigns to a global. This is deliberate: a browser
opening a page from file:// REFUSES to fetch() a .json next to it (CORS), so a plain
JSON data file would work when hosted and silently fail when you double-click the app.
A <script> tag has no such restriction. So the app works both ways, with no server —
which is the whole point of a static site.

    python3 pipeline/build_app.py
"""
import json, os, glob, shutil, hashlib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT  = os.path.join(ROOT, 'app', 'data', 'library.js')

def main():
    audio_root = os.path.join(ROOT, 'app', 'audio')
    copied = 0
    texts, drills = [], []
    for p in sorted(glob.glob(os.path.join(ROOT, 'build', '*', 'text.json'))):
        d = json.load(open(p, encoding='utf-8'))
        d['_dir'] = os.path.basename(os.path.dirname(p))
        d['_words'] = sum(len(s['words']) for s in d['sentences'])
        # Rewrite audio paths to live inside app/ — a hosted folder can't reach ../build.
        for i, s_ in enumerate(d['sentences']):
            if s_.get('audio'):
                src = os.path.join(ROOT, 'build', d['_dir'], s_['audio'])
                dst_rel = os.path.join('audio', d['_dir'], os.path.basename(s_['audio']))
                dst = os.path.join(ROOT, 'app', dst_rel)
                if os.path.exists(src):
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    shutil.copy2(src, dst); copied += 1
                    s_['audio'] = dst_rel.replace(os.sep, '/')
                else:
                    s_['audio'] = None
        d['_audio'] = any(s_.get('audio') for s_ in d['sentences'])
        texts.append(d)
    for p in sorted(glob.glob(os.path.join(ROOT, 'build', '*', 'session.json'))):
        d = json.load(open(p, encoding='utf-8'))
        d['_dir'] = os.path.basename(os.path.dirname(p))
        for it in d['items']:
            for k in ('cue_audio', 'answer_audio'):
                if it.get(k):
                    src = os.path.join(ROOT, 'build', d['_dir'], it[k])
                    dst_rel = os.path.join('audio', d['_dir'], os.path.basename(it[k]))
                    dst = os.path.join(ROOT, 'app', dst_rel)
                    if os.path.exists(src):
                        os.makedirs(os.path.dirname(dst), exist_ok=True)
                        shutil.copy2(src, dst); copied += 1
                        it[k] = dst_rel.replace(os.sep, '/')
                    else:
                        it[k] = None
        d['_audio'] = any(i.get('answer_audio') for i in d['items'])
        drills.append(d)

    # AUDIO CACHE BUSTING. Clips are named by position (audio/<text>/s0.mp3), so re-voicing
    # replaces a file WITHOUT changing its URL — and every browser that already played it keeps
    # serving the old voice from cache, indefinitely. That's exactly what made a completed
    # re-voice look like "the voice didn't change". So stamp a version derived from the actual
    # audio bytes; the app appends it to every audio URL, and any change forces a refetch.
    sig = hashlib.md5()
    for p in sorted(glob.glob(os.path.join(ROOT, 'app', 'audio', '**', '*.mp3'), recursive=True)):
        st = os.stat(p)
        sig.update(os.path.relpath(p, ROOT).encode('utf-8'))
        sig.update(str(st.st_size).encode('ascii'))
    audio_version = sig.hexdigest()[:10]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write("// GENERATED by pipeline/build_app.py — do not edit by hand.\n")
        f.write("// AUDIO_VERSION changes whenever any clip changes; the app appends it to audio\n")
        f.write("// URLs so a re-voice is never masked by a cached copy of the old voice.\n")
        f.write('window.AUDIO_VERSION = "%s";\n' % audio_version)
        f.write("window.LIBRARY = ")
        json.dump({"texts": texts, "drills": drills}, f, ensure_ascii=False, indent=1)
        f.write(";\n")

    # Stamp the service worker's cache name with a hash of the app shell + all data, so every
    # deploy gets a fresh cache and the SW's activate step drops the stale one — no learner stuck
    # on old JS/data behind the cache. (The HTML is fetched network-first regardless; this covers
    # the cache-first data/JS assets.)
    sw_path = os.path.join(ROOT, 'app', 'service-worker.js')
    if os.path.exists(sw_path):
        import re as _re
        ash = hashlib.md5()
        shell = [os.path.join(ROOT, 'app', 'index.html')] + \
            sorted(glob.glob(os.path.join(ROOT, 'app', 'data', '*.js')))
        for p in shell:
            try:
                ash.update(open(p, 'rb').read())
            except OSError:
                pass
        appver = ash.hexdigest()[:10]
        sw = open(sw_path, encoding='utf-8').read()
        sw2 = _re.sub(r"const CACHE_VERSION = '[^']*';",
                      "const CACHE_VERSION = 'alp-%s';" % appver, sw, count=1)
        if sw2 != sw:
            open(sw_path, 'w', encoding='utf-8').write(sw2)
        print(f"sw cache version: alp-{appver}")

    print(f"audio version: {audio_version}")
    print(f"texts : {len(texts)}")
    for t in texts:
        print(f"    {t['id']:22} {t['_words']:3} words  audio={'yes' if t['_audio'] else 'no'}")
    print(f"drills: {len(drills)}")
    for d in drills:
        print(f"    {d['id']:22} {len(d['items']):3} chunks audio={'yes' if d['_audio'] else 'no'}")
    print(f"audio files copied into app/: {copied}")
    print(f"\n-> {os.path.relpath(OUT, ROOT)}  ({os.path.getsize(OUT)//1024} KB)")
    print("\napp/ is self-contained — that whole folder is the website.")

if __name__ == '__main__':
    main()
