#!/usr/bin/env python3
"""Collect pipeline output into one file the app can read.

Emits a .js file (not .json) that assigns to a global. This is deliberate: a browser
opening a page from file:// REFUSES to fetch() a .json next to it (CORS), so a plain
JSON data file would work when hosted and silently fail when you double-click the app.
A <script> tag has no such restriction. So the app works both ways, with no server —
which is the whole point of a static site.

    python3 pipeline/build_app.py
"""
import json, os, glob, shutil

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT  = os.path.join(ROOT, 'app', 'data', 'library.js')

def main():
    audio_root = os.path.join(ROOT, 'app', 'audio')
    copied = 0
    texts, drills = [], []
    for p in sorted(glob.glob(os.path.join(ROOT, 'build', '*', 'text.json'))):
        d = json.load(open(p, encoding='utf-8'))
        d['_dir'] = os.path.basename(os.path.dirname(p))
        d['_words'] = sum(len(s['words']) for s in d['sentences'])
        # Rewrite audio paths to live inside app/ — a hosted folder can't reach ../build.
        for i, s_ in enumerate(d['sentences']):
            if s_.get('audio'):
                src = os.path.join(ROOT, 'build', d['_dir'], s_['audio'])
                dst_rel = os.path.join('audio', d['_dir'], os.path.basename(s_['audio']))
                dst = os.path.join(ROOT, 'app', dst_rel)
                if os.path.exists(src):
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    shutil.copy2(src, dst); copied += 1
                    s_['audio'] = dst_rel.replace(os.sep, '/')
                else:
                    s_['audio'] = None
        d['_audio'] = any(s_.get('audio') for s_ in d['sentences'])
        texts.append(d)
    for p in sorted(glob.glob(os.path.join(ROOT, 'build', '*', 'session.json'))):
        d = json.load(open(p, encoding='utf-8'))
        d['_dir'] = os.path.basename(os.path.dirname(p))
        for it in d['items']:
            for k in ('cue_audio', 'answer_audio'):
                if it.get(k):
                    src = os.path.join(ROOT, 'build', d['_dir'], it[k])
                    dst_rel = os.path.join('audio', d['_dir'], os.path.basename(it[k]))
                    dst = os.path.join(ROOT, 'app', dst_rel)
                    if os.path.exists(src):
                        os.makedirs(os.path.dirname(dst), exist_ok=True)
                        shutil.copy2(src, dst); copied += 1
                        it[k] = dst_rel.replace(os.sep, '/')
                    else:
                        it[k] = None
        d['_audio'] = any(i.get('answer_audio') for i in d['items'])
        drills.append(d)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write("// GENERATED by pipeline/build_app.py — do not edit by hand.\n")
        f.write("window.LIBRARY = ")
        json.dump({"texts": texts, "drills": drills}, f, ensure_ascii=False, indent=1)
        f.write(";\n")

    print(f"texts : {len(texts)}")
    for t in texts:
        print(f"    {t['id']:22} {t['_words']:3} words  audio={'yes' if t['_audio'] else 'no'}")
    print(f"drills: {len(drills)}")
    for d in drills:
        print(f"    {d['id']:22} {len(d['items']):3} chunks audio={'yes' if d['_audio'] else 'no'}")
    print(f"audio files copied into app/: {copied}")
    print(f"\n-> {os.path.relpath(OUT, ROOT)}  ({os.path.getsize(OUT)//1024} KB)")
    print("\napp/ is self-contained — that whole folder is the website.")

if __name__ == '__main__':
    main()
