#!/usr/bin/env python3
"""ג'וחא — forty folk tales retold in modern Hebrew, graded to beginner.

The Hebrew twin of pipeline/book_juha.py, tale for tale. Juha — Nasreddin, ג'וחא — is the wise
fool of the whole eastern Mediterranean, and he crossed into Hebrew a long time before this
app: the tales are told in Israel too, and the joke lands in either language because it is
never in the words.

WHY HE OPENS THIS SHELF AS WELL. A Juha tale is three sentences of setup and one that turns,
which is exactly the shape a beginner can hold. And it is entirely dialogue and everyday
objects — a donkey, a pot, a door, a neighbour who borrows — so the vocabulary is the
vocabulary of the street rather than of literature.

Deliberately unpointed. The vowels are looked up at ingest, never typed here. ג'וחא himself has
no lexical entry in any language and is declared in pipeline/he_curated.py, where the pointing
and the gloss are written down once.

Run:  python3 pipeline/he_book_juha.py --lang he            # check
      python3 pipeline/he_book_juha.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'the Juha / Nasreddin folk tales', 'author': 'traditional', 'year': 'medieval',
        'status': 'public domain — folk material, no known author'}

CHAPTERS = [
 ('The Donkey and the Neighbour', 'החמור והשכן', [
  P(('לג\'וחא היה חמור אחד בחצר.', 'Juha had one donkey in the yard.'),
    ('החמור היה זקן אבל עוד עבד.', 'The donkey was old but still worked.'),
    ('בוקר אחד השכן דפק בדלת.', 'One morning the neighbour knocked at the door.'),
    ('ג\'וחא פתח ואמר: בוקר טוב.', 'Juha opened and said: good morning.')),
  P(('השכן אמר: אני צריך את החמור.', 'The neighbour said: I need the donkey.'),
    ('הוא אמר: רק ליום אחד, לשוק.', 'He said: only for one day, to the market.'),
    ('ג\'וחא לא רצה לתת לו אותו.', 'Juha did not want to give it to him.'),
    ('הוא אמר: אני מצטער מאוד.', 'He said: I am very sorry.'),
    ('הוא אמר: החמור לא בבית היום.', 'He said: the donkey is not at home today.')),
  P(('באותו רגע נשמע קול מהחצר.', 'At that moment a sound was heard from the yard.'),
    ('החמור צעק חזק מאוד.', 'The donkey cried out very loudly.'),
    ('השכן הסתכל על ג\'וחא בשקט.', 'The neighbour looked at Juha quietly.'),
    ('הוא אמר: אני שומע אותו עכשיו.', 'He said: I hear it now.')),
  P(('ג\'וחא עמד רגע ולא זז.', 'Juha stood a moment and did not move.'),
    ('ואז הוא אמר: אני לא מבין אותך.', 'And then he said: I do not understand you.'),
    ('הוא אמר: אני איש מבוגר.', 'He said: I am a grown man.'),
    ('הוא אמר: ואתה מאמין לחמור.', 'He said: and you believe a donkey.'),
    ('הוא סגר את הדלת ואז נכנס.', 'He closed the door and went in.'))]),
 ('The Coat at the Feast', 'המעיל בסעודה', [
  P(('קראו לג\'וחא לסעודה גדולה.', 'They called Juha to a big feast.'),
    ('הוא בא בבגדי העבודה שלו.', 'He came in his work clothes.'),
    ('הבגדים היו ישנים ולא נקיים.', 'The clothes were old and not clean.'),
    ('הוא נכנס ואמר שלום לכולם.', 'He came in and said hello to everyone.')),
  P(('איש לא ענה לו כלום.', 'No one answered him anything.'),
    ('הוא ישב בפינה ליד הדלת.', 'He sat in the corner beside the door.'),
    ('האוכל עבר ולא הגיע אליו.', 'The food passed and did not reach him.'),
    ('הוא חיכה שעה ואז יצא.', 'He waited an hour and then went out.')),
  P(('הוא הלך הביתה והחליף בגדים.', 'He went home and changed clothes.'),
    ('הוא לבש מעיל חדש ויקר.', 'He put on a new, expensive coat.'),
    ('הוא חזר לבית של הסעודה.', 'He came back to the house of the feast.'),
    ('בעל הבית קם וקיבל אותו יפה.', 'The master of the house rose and received him nicely.'),
    ('הוא הושיב אותו ליד השולחן.', 'He sat him beside the table.')),
  P(('הביאו לו צלחת מלאה אוכל.', 'They brought him a plate full of food.'),
    ('ג\'וחא לקח את שרוול המעיל.', 'Juha took the sleeve of the coat.'),
    ('הוא הכניס אותו לתוך הצלחת.', 'He put it into the plate.'),
    ('הוא אמר: תאכל, מעיל, בבקשה.', 'He said: eat, coat, please.'),
    ('כולם שאלו: מה אתה עושה?', 'Everyone asked: what are you doing?'),
    ('הוא אמר: הזמנתם את המעיל, לא אותי.', 'He said: you invited the coat, not me.'))]),
 ('The Pot That Gave Birth', 'הסיר שילד', [
  P(('ג\'וחא ביקש סיר גדול מהשכן.', 'Juha asked for a big pot from the neighbour.'),
    ('השכן נתן לו אותו בשמחה.', 'The neighbour gave it to him gladly.'),
    ('אחרי יומיים ג\'וחא החזיר אותו.', 'After two days Juha returned it.'),
    ('בתוך הסיר היה סיר קטן.', 'Inside the pot was a small pot.')),
  P(('השכן שאל: מה זה הדבר הזה?', 'The neighbour asked: what is this thing?'),
    ('ג\'וחא אמר: הסיר שלך ילד בלילה.', 'Juha said: your pot gave birth at night.'),
    ('השכן צחק אבל לקח את שניהם.', 'The neighbour laughed but took both of them.'),
    ('הוא אמר לעצמו: זה איש טיפש.', 'He said to himself: this is a foolish man.')),
  P(('אחרי שבוע ג\'וחא בא שוב.', 'After a week Juha came again.'),
    ('הוא ביקש את הסיר הגדול.', 'He asked for the big pot.'),
    ('השכן נתן לו אותו מיד.', 'The neighbour gave it to him at once.'),
    ('הוא חשב על הסיר הקטן.', 'He thought about the small pot.')),
  P(('עברו שבועיים, ואז חודש.', 'Two weeks passed, and then a month.'),
    ('ג\'וחא לא בא ולא החזיר.', 'Juha did not come and did not return it.'),
    ('השכן הלך אליו ודפק בדלת.', 'The neighbour went to him and knocked at the door.'),
    ('הוא שאל: איפה הסיר שלי?', 'He asked: where is my pot?')),
  P(('ג\'וחא אמר: יש לי חדשות רעות.', 'Juha said: I have bad news.'),
    ('הוא אמר: הסיר שלך מת אתמול.', 'He said: your pot died yesterday.'),
    ('השכן צעק: סיר לא יכול למות!', 'The neighbour shouted: a pot cannot die!'),
    ('ג\'וחא אמר: אבל הוא ילד, נכון?', 'Juha said: but it gave birth, right?'),
    ('הוא אמר: מי שיולד גם מת.', 'He said: whoever gives birth also dies.'))]),
 ('The Smell of the Food', 'הריח של האוכל', [
  P(('איש עני עבר ליד מסעדה.', 'A poor man passed beside a restaurant.'),
    ('היה לו רק לחם יבש ביד.', 'He had only dry bread in his hand.'),
    ('הוא עמד ליד הדלת ואכל.', 'He stood beside the door and ate.'),
    ('הריח של הבשר הגיע אליו.', 'The smell of the meat reached him.')),
  P(('בעל המסעדה יצא וצעק עליו.', 'The owner of the restaurant came out and shouted at him.'),
    ('הוא אמר: אתה אוכל עם הריח שלי.', 'He said: you are eating with my smell.'),
    ('הוא אמר: תשלם לי על זה.', 'He said: pay me for it.'),
    ('האיש אמר: אין לי כסף בכלל.', 'The man said: I have no money at all.')),
  P(('הם הלכו לשופט בעיר.', 'They went to the judge in the city.'),
    ('השופט באותו יום היה ג\'וחא.', 'The judge that day was Juha.'),
    ('הוא שמע את שניהם בשקט.', 'He heard both of them quietly.'),
    ('הוא אמר: זה עניין חשוב מאוד.', 'He said: this is a very important matter.')),
  P(('הוא ביקש מהעני את הכיס שלו.', 'He asked the poor man for his pocket.'),
    ('היו בו שני מטבעות קטנים.', 'In it were two small coins.'),
    ('ג\'וחא לקח אותם ביד אחת.', 'Juha took them in one hand.'),
    ('הוא הזיז את היד ליד האוזן.', 'He moved his hand beside the ear.'),
    ('נשמע קול של כסף שזז.', 'A sound of money moving was heard.')),
  P(('הוא החזיר את המטבעות לעני.', 'He returned the coins to the poor man.'),
    ('הוא אמר לבעל המסעדה: שמעת?', 'He said to the restaurant owner: did you hear?'),
    ('הוא אמר: זה התשלום שלך.', 'He said: that is your payment.'),
    ('הוא אמר: ריח בשביל קול הכסף.', 'He said: a smell for the sound of the money.'))]),
 ('Riding to Market', 'בדרך לשוק', [
  P(('ג\'וחא והבן שלו הלכו לשוק.', 'Juha and his son went to the market.'),
    ('היה להם חמור אחד בדרך.', 'They had one donkey on the road.'),
    ('בהתחלה שניהם הלכו ברגל.', 'At first both of them walked on foot.'),
    ('אנשים בדרך הסתכלו עליהם.', 'People on the road looked at them.'),
    ('הם אמרו: יש להם חמור והם הולכים.', 'They said: they have a donkey and they walk.')),
  P(('ג\'וחא הרים את הבן על החמור.', 'Juha lifted the son onto the donkey.'),
    ('הם המשיכו בדרך עוד קצת.', 'They continued on the road a little more.'),
    ('אנשים אחרים ראו אותם.', 'Other people saw them.'),
    ('הם אמרו: תראו את הילד הזה.', 'They said: look at this child.'),
    ('הם אמרו: האבא הזקן הולך ברגל.', 'They said: the old father walks on foot.')),
  P(('ג\'וחא עלה, והבן ירד.', 'Juha got up, and the son got down.'),
    ('הם הלכו ככה חצי שעה.', 'They went like that for half an hour.'),
    ('נשים בדרך ראו אותם.', 'Women on the road saw them.'),
    ('הן אמרו: איזה אבא הוא.', 'They said: what a father he is.'),
    ('הן אמרו: הילד הקטן מתעייף.', 'They said: the small child gets tired.')),
  P(('שניהם עלו על החמור יחד.', 'Both of them got on the donkey together.'),
    ('החמור הלך לאט מאוד.', 'The donkey walked very slowly.'),
    ('איש זקן עצר אותם בדרך.', 'An old man stopped them on the road.'),
    ('הוא אמר: החמור הזה קטן.', 'He said: this donkey is small.'),
    ('הוא אמר: ואתם שניים עליו.', 'He said: and you are two on it.')),
  P(('ג\'וחא ירד והבן ירד אחריו.', 'Juha got down and the son got down after him.'),
    ('הם הרימו את החמור על הכתפיים.', 'They lifted the donkey onto their shoulders.'),
    ('כל השוק צחק כשהם נכנסו.', 'The whole market laughed when they came in.'),
    ('ג\'וחא אמר לבן: ראית?', 'Juha said to the son: did you see?'),
    ('הוא אמר: אי אפשר לרצות את כולם.', 'He said: it is impossible to please everyone.'))]),
 ('The Key in the Light', 'המפתח באור', [
  P(('בערב אחד ג\'וחא איבד מפתח.', 'One evening Juha lost a key.'),
    ('הוא איבד אותו בתוך הבית.', 'He lost it inside the house.'),
    ('הוא חיפש אותו זמן קצר.', 'He looked for it a short time.'),
    ('ואז הוא יצא לרחוב.', 'And then he went out to the street.')),
  P(('ברחוב עמד פנס גדול.', 'In the street stood a big lamp.'),
    ('ג\'וחא כרע מתחת לפנס.', 'Juha knelt under the lamp.'),
    ('הוא חיפש על האבנים בידיים.', 'He searched on the stones with his hands.'),
    ('שכן עבר וראה אותו.', 'A neighbour passed and saw him.')),
  P(('השכן שאל: מה אתה מחפש?', 'The neighbour asked: what are you looking for?'),
    ('ג\'וחא אמר: איבדתי מפתח.', 'Juha said: I lost a key.'),
    ('השכן כרע גם הוא ועזר לו.', 'The neighbour knelt too and helped him.'),
    ('הם חיפשו יחד חצי שעה.', 'They searched together for half an hour.')),
  P(('השכן שאל: איפה הוא נפל?', 'The neighbour asked: where did it fall?'),
    ('ג\'וחא אמר: בתוך הבית שלי.', 'Juha said: inside my house.'),
    ('השכן קם וצעק: אז למה כאן?', 'The neighbour got up and shouted: then why here?'),
    ('ג\'וחא אמר: בבית אין אור.', 'Juha said: in the house there is no light.'),
    ('הוא אמר: ופה יש אור טוב.', 'He said: and here there is good light.'))]),
 ('Three Days of Bread', 'לחם לשלושה ימים', [
  P(('בכפר היה רעב באותה שנה.', 'In the village there was hunger that year.'),
    ('לא היה מספיק אוכל לכולם.', 'There was not enough food for everyone.'),
    ('ג\'וחא קנה לחם לשלושה ימים.', 'Juha bought bread for three days.'),
    ('הוא שם אותו בארון בבית.', 'He put it in the cupboard in the house.')),
  P(('בערב בא אליו אורח.', 'In the evening a guest came to him.'),
    ('האורח היה רעב מאוד.', 'The guest was very hungry.'),
    ('ג\'וחא נתן לו את לחם היום.', 'Juha gave him the day’s bread.'),
    ('האורח אכל הכול ואמר תודה.', 'The guest ate everything and said thank you.')),
  P(('בבוקר בא אורח שני.', 'In the morning a second guest came.'),
    ('ג\'וחא נתן לו את לחם המחר.', 'Juha gave him tomorrow’s bread.'),
    ('בערב בא אורח שלישי.', 'In the evening a third guest came.'),
    ('ג\'וחא נתן לו את הלחם האחרון.', 'Juha gave him the last bread.')),
  P(('אשתו אמרה: מה נאכל עכשיו?', 'His wife said: what shall we eat now?'),
    ('ג\'וחא ישב ולא ענה לה.', 'Juha sat and did not answer her.'),
    ('בבוקר דפקו שוב בדלת.', 'In the morning they knocked at the door again.'),
    ('ג\'וחא פתח, ועמד שם אדם.', 'Juha opened, and a man stood there.'),
    ('לאיש היה שק גדול על הגב.', 'The man had a big sack on his back.')),
  P(('האיש אמר: אתה ג\'וחא, נכון?', 'The man said: you are Juha, right?'),
    ('הוא אמר: אכלתי אצלך פעם.', 'He said: I ate at your house once.'),
    ('הוא אמר: היום יש לי הרבה.', 'He said: today I have a lot.'),
    ('הוא שם את השק על הרצפה והלך.', 'He put the sack on the floor and went.'),
    ('ג\'וחא אמר לאשתו: את רואה?', 'Juha said to his wife: do you see?'))]),
 ('The Sermon', 'הדרשה', [
  P(('ביום שישי ג\'וחא עלה לדבר.', 'On Friday Juha went up to speak.'),
    ('כל אנשי הכפר ישבו למטה.', 'All the village people sat below.'),
    ('הוא הסתכל עליהם בשקט.', 'He looked at them quietly.'),
    ('הוא שאל: אתם יודעים מה אני אומר?', 'He asked: do you know what I am going to say?')),
  P(('כולם ענו יחד: לא, אנחנו לא יודעים.', 'They all answered together: no, we do not know.'),
    ('ג\'וחא אמר: אז אין טעם לדבר.', 'Juha said: then there is no point in speaking.'),
    ('הוא ירד והלך הביתה.', 'He came down and went home.'),
    ('האנשים ישבו והסתכלו זה על זה.', 'The people sat and looked at each other.')),
  P(('בשבוע הבא הוא עלה שוב.', 'The next week he went up again.'),
    ('הוא שאל את אותה שאלה בדיוק.', 'He asked exactly the same question.'),
    ('הפעם כולם ענו: כן, אנחנו יודעים.', 'This time they all answered: yes, we know.'),
    ('ג\'וחא אמר: אז אני לא צריך לדבר.', 'Juha said: then I do not need to speak.'),
    ('הוא ירד והלך הביתה שוב.', 'He came down and went home again.')),
  P(('בשבוע השלישי הם דיברו לפני זה.', 'In the third week they talked beforehand.'),
    ('הם החליטו: חצי יגידו כן.', 'They decided: half will say yes.'),
    ('הם החליטו: וחצי יגידו לא.', 'They decided: and half will say no.'),
    ('ג\'וחא עלה ושאל את השאלה.', 'Juha went up and asked the question.'),
    ('חצי ענו כן וחצי ענו לא.', 'Half answered yes and half answered no.')),
  P(('ג\'וחא עמד רגע וחשב.', 'Juha stood a moment and thought.'),
    ('ואז הוא אמר: זה פשוט מאוד.', 'And then he said: it is very simple.'),
    ('הוא אמר: מי שיודע יספר לשני.', 'He said: whoever knows will tell the other.'),
    ('הוא ירד והלך הביתה בשלישית.', 'He came down and went home for the third time.'))]),
 ('Carrying the Door', 'הדלת על הגב', [
  P(('ג\'וחא נסע לעיר ליום אחד.', 'Juha travelled to the city for one day.'),
    ('אשתו אמרה לו לפני שיצא.', 'His wife said to him before he went out.'),
    ('היא אמרה: תשמור על הדלת.', 'She said: guard the door.'),
    ('היא אמרה: אל תעזוב אותה לרגע.', 'She said: do not leave it for a moment.')),
  P(('ג\'וחא אמר: טוב, אני אשמור.', 'Juha said: good, I shall guard it.'),
    ('הוא הוציא את הדלת מהמקום.', 'He took the door out of its place.'),
    ('הוא שם אותה על הגב שלו.', 'He put it on his back.'),
    ('הוא הלך איתה כל הדרך לעיר.', 'He walked with it all the way to the city.')),
  P(('בעיר כולם הסתכלו עליו.', 'In the city everyone looked at him.'),
    ('ילדים הלכו אחריו וצחקו.', 'Children walked after him and laughed.'),
    ('הוא קנה מה שהוא צריך בשוק.', 'He bought what he needed at the market.'),
    ('הוא חזר הביתה בערב עם הדלת.', 'He came back home in the evening with the door.')),
  P(('בבית הכול היה פתוח וריק.', 'At home everything was open and empty.'),
    ('גנבים לקחו את כל הדברים.', 'Thieves had taken all the things.'),
    ('אשתו ישבה ובכתה בחצר.', 'His wife sat and wept in the yard.'),
    ('ג\'וחא אמר: אני לא אשם.', 'Juha said: I am not guilty.'),
    ('הוא אמר: הדלת אצלי, ראי.', 'He said: the door is with me, look.'))]),
 ('The Ring in the Well', 'הטבעת בבאר', [
  P(('אשתו של ג\'וחא איבדה טבעת.', 'Juha’s wife lost a ring.'),
    ('הטבעת נפלה לתוך הבאר.', 'The ring fell into the well.'),
    ('היא קראה לו מהר מאוד.', 'She called him very fast.'),
    ('ג\'וחא בא והסתכל למטה.', 'Juha came and looked down.')),
  P(('הבאר הייתה עמוקה וחשוכה.', 'The well was deep and dark.'),
    ('הוא לא ראה שם כלום.', 'He did not see anything there.'),
    ('הוא הביא חבל ודלי מהחצר.', 'He brought a rope and a bucket from the yard.'),
    ('הוא הוריד אותם לתוך המים.', 'He lowered them into the water.')),
  P(('הוא הוציא מים כל הבוקר.', 'He took out water all morning.'),
    ('הוא לא מצא את הטבעת.', 'He did not find the ring.'),
    ('אחר כך הוא הלך לחצר.', 'Afterwards he went to the yard.'),
    ('הוא הביא בשר מהמטבח.', 'He brought meat from the kitchen.'),
    ('הוא זרק אותו לתוך הבאר.', 'He threw it into the well.')),
  P(('אשתו שאלה: למה עשית את זה?', 'His wife asked: why did you do that?'),
    ('ג\'וחא אמר: אני מכיר את הבאר.', 'Juha said: I know the well.'),
    ('הוא אמר: היא לא נותנת כלום.', 'He said: it does not give anything.'),
    ('הוא אמר: אולי בשביל בשר כן.', 'He said: maybe for meat it will.'))]),
 ('Counting the Donkeys', 'סופרים את החמורים', [
  P(('ג\'וחא לקח עשרה חמורים לשוק.', 'Juha took ten donkeys to the market.'),
    ('הוא עלה על אחד מהם בבוקר.', 'He got on one of them in the morning.'),
    ('הדרך הייתה ארוכה ושקטה.', 'The road was long and quiet.'),
    ('באמצע הדרך הוא ספר אותם.', 'In the middle of the road he counted them.')),
  P(('הוא ספר ומצא רק תשעה.', 'He counted and found only nine.'),
    ('הוא ירד מהר מאוד לאדמה.', 'He got down to the ground very fast.'),
    ('הוא ספר שוב, ועכשיו עשרה.', 'He counted again, and now ten.'),
    ('הוא עלה בחזרה והמשיך בדרך.', 'He got back up and continued on the road.')),
  P(('אחרי קצת הוא ספר שוב.', 'After a little he counted again.'),
    ('שוב היו רק תשעה חמורים.', 'Again there were only nine donkeys.'),
    ('הוא ירד ובדק, והיו עשרה.', 'He got down and checked, and there were ten.'),
    ('הוא לא הבין מה קורה כאן.', 'He did not understand what is happening here.')),
  P(('הוא החליט ללכת ברגל עד הסוף.', 'He decided to walk on foot until the end.'),
    ('בשוק פגש אותו חבר ותיק.', 'At the market an old friend met him.'),
    ('החבר שאל: למה אתה הולך?', 'The friend asked: why are you walking?'),
    ('ג\'וחא אמר: ככה יש לי עשרה.', 'Juha said: this way I have ten.'),
    ('הוא אמר: וכשאני רוכב יש תשעה.', 'He said: and when I ride there are nine.'))]),
 ('The Cold Night', 'הלילה הקר', [
  P(('בכפר דיברו על ג\'וחא בערב.', 'In the village they spoke about Juha in the evening.'),
    ('אחד אמר: הוא לא יעמוד בקור.', 'One said: he will not stand the cold.'),
    ('ג\'וחא אמר: אני כן אעמוד.', 'Juha said: I will indeed stand it.'),
    ('הם אמרו: אז נעשה התערבות.', 'They said: then we shall make a bet.')),
  P(('הם אמרו: תעמוד לילה שלם בחוץ.', 'They said: stand a whole night outside.'),
    ('הם אמרו: בלי אש ובלי מעיל.', 'They said: without fire and without a coat.'),
    ('הם אמרו: ואם תצליח, נבשל לך.', 'They said: and if you succeed, we shall cook for you.'),
    ('ג\'וחא אמר: אני מסכים לזה.', 'Juha said: I agree to that.')),
  P(('הוא עמד כל הלילה בשדה.', 'He stood all night in the field.'),
    ('היה קר מאוד, והוא רעד.', 'It was very cold, and he trembled.'),
    ('בבוקר הוא בא אליהם.', 'In the morning he came to them.'),
    ('הוא אמר: עמדתי, ואני כאן.', 'He said: I stood, and I am here.')),
  P(('הם שאלו: ראית משהו בלילה?', 'They asked: did you see anything at night?'),
    ('הוא אמר: ראיתי אור מרחוק.', 'He said: I saw a light far away.'),
    ('הוא אמר: היה שם נר בחלון.', 'He said: there was a candle in a window there.'),
    ('הם צעקו: אז היה לך חום!', 'They shouted: then you had warmth!'),
    ('הם אמרו: אתה הפסדת בהתערבות.', 'They said: you lost the bet.')),
  P(('ג\'וחא הזמין אותם לארוחה.', 'Juha invited them to a meal.'),
    ('הם באו רעבים בערב.', 'They came hungry in the evening.'),
    ('הם ישבו וחיכו הרבה זמן.', 'They sat and waited a long time.'),
    ('בסוף הם נכנסו למטבח.', 'In the end they went into the kitchen.'),
    ('הסיר היה תלוי גבוה מאוד.', 'The pot hung very high.'),
    ('נר קטן עמד על הרצפה מתחתיו.', 'A small candle stood on the floor beneath it.'),
    ('ג\'וחא אמר: הנר מבשל, כמו אתמול.', 'Juha said: the candle is cooking, like yesterday.'))]),
 ('Which Half', 'איזה חצי', [
  P(('לג\'וחא היה חמור אחד יפה.', 'Juha had one fine donkey.'),
    ('שכן ביקש לקנות ממנו חצי.', 'A neighbour asked to buy half of it from him.'),
    ('ג\'וחא חשב ואז אמר: טוב.', 'Juha thought and then said: good.'),
    ('הם חילקו את החמור בדיבור.', 'They divided the donkey in words.')),
  P(('השכן אמר: החצי הקדמי שלי.', 'The neighbour said: the front half is mine.'),
    ('ג\'וחא אמר: והחצי האחורי שלי.', 'Juha said: and the back half is mine.'),
    ('הם לחצו ידיים על זה.', 'They shook hands on it.'),
    ('החמור נשאר בחצר של ג\'וחא.', 'The donkey stayed in Juha’s yard.')),
  P(('אחרי כמה ימים היה עומס.', 'After a few days there was a load.'),
    ('ג\'וחא רצה לשים אותו על החמור.', 'Juha wanted to put it on the donkey.'),
    ('השכן אמר: לא על החלק שלי.', 'The neighbour said: not on my part.'),
    ('ג\'וחא שם הכול על החלק שלו.', 'Juha put everything on his part.')),
  P(('אחר כך הוא הפסיק לתת אוכל.', 'Afterwards he stopped giving food.'),
    ('השכן שאל: למה הוא רעב?', 'The neighbour asked: why is it hungry?'),
    ('ג\'וחא אמר: הפה שלך, לא שלי.', 'Juha said: the mouth is yours, not mine.'),
    ('הוא אמר: אני מאכיל את הזנב.', 'He said: I feed the tail.'),
    ('השכן ביקש לבטל את הקנייה.', 'The neighbour asked to cancel the purchase.'))]),
 ('The Long Way Home', 'הדרך הארוכה הביתה', [
  P(('ג\'וחא היה בעיר רחוקה.', 'Juha was in a far city.'),
    ('הוא סיים את העבודה בערב.', 'He finished the work in the evening.'),
    ('הוא רצה לחזור הביתה מהר.', 'He wanted to return home fast.'),
    ('הוא שאל איש בדרך על הזמן.', 'He asked a man on the road about the time.')),
  P(('הוא שאל: כמה זמן עד הכפר?', 'He asked: how long until the village?'),
    ('האיש הסתכל עליו ולא ענה.', 'The man looked at him and did not answer.'),
    ('ג\'וחא שאל שוב בקול גדול.', 'Juha asked again in a loud voice.'),
    ('האיש עוד לא אמר כלום.', 'The man still did not say anything.')),
  P(('ג\'וחא כעס והתחיל ללכת.', 'Juha grew angry and began to walk.'),
    ('אחרי קצת האיש קרא לו.', 'After a little the man called to him.'),
    ('הוא אמר: שעתיים, אם תלך ככה.', 'He said: two hours, if you walk like that.'),
    ('ג\'וחא חזר ושאל: למה עכשיו?', 'Juha came back and asked: why now?')),
  P(('האיש אמר: לא ידעתי קודם.', 'The man said: I did not know before.'),
    ('הוא אמר: לא ראיתי איך אתה הולך.', 'He said: I did not see how you walk.'),
    ('הוא אמר: עכשיו ראיתי, ואני יודע.', 'He said: now I saw, and I know.'),
    ('ג\'וחא צחק והמשיך בדרך.', 'Juha laughed and continued on the road.'))]),
 ('Salt and Wool', 'מלח וצמר', [
  P(('ג\'וחא קנה מלח בשוק בבוקר.', 'Juha bought salt at the market in the morning.'),
    ('הוא שם אותו על החמור בשקים.', 'He put it on the donkey in sacks.'),
    ('הדרך הביתה עברה ליד נהר.', 'The road home passed beside a river.'),
    ('החמור נכנס למים לאט.', 'The donkey went into the water slowly.')),
  P(('הוא נפל ושכב בתוך הנהר.', 'It fell and lay in the river.'),
    ('המלח נמס ונעלם במים.', 'The salt melted and disappeared in the water.'),
    ('החמור קם קל מאוד.', 'The donkey got up very light.'),
    ('הוא המשיך בדרך בשמחה.', 'It continued on the road happily.'),
    ('ג\'וחא ראה הכול ולא אמר כלום.', 'Juha saw everything and did not say anything.')),
  P(('בשבוע הבא הוא קנה צמר.', 'The next week he bought wool.'),
    ('הוא שם אותו על אותו חמור.', 'He put it on the same donkey.'),
    ('הם הגיעו שוב אל הנהר.', 'They came again to the river.'),
    ('החמור נכנס ושכב מיד.', 'The donkey went in and lay down at once.')),
  P(('הצמר לקח את כל המים.', 'The wool took in all the water.'),
    ('הוא נעשה כבד מאוד.', 'It became very heavy.'),
    ('החמור ניסה לקום ולא הצליח.', 'The donkey tried to get up and did not succeed.'),
    ('ג\'וחא עמד על החוף וחייך.', 'Juha stood on the bank and smiled.'),
    ('הוא אמר: אתה חכם, אבל אני יותר.', 'He said: you are clever, but I am more so.'))]),
 ('The Borrowed Cooking', 'הבישול המושאל', [
  P(('שכן בישל בשר בחצר שלו.', 'A neighbour cooked meat in his yard.'),
    ('הריח עלה בכל הרחוב.', 'The smell rose in the whole street.'),
    ('ג\'וחא עמד ליד הגדר והריח.', 'Juha stood beside the fence and smelled.'),
    ('השכן ראה אותו ולא הזמין.', 'The neighbour saw him and did not invite him.')),
  P(('בערב ג\'וחא ביקש ממנו סיר.', 'In the evening Juha asked him for a pot.'),
    ('הוא אמר: אני מבשל מחר.', 'He said: I am cooking tomorrow.'),
    ('השכן שאל: מה אתה מבשל?', 'The neighbour asked: what are you cooking?'),
    ('ג\'וחא אמר: בשר, הרבה בשר.', 'Juha said: meat, a lot of meat.')),
  P(('השכן נתן לו את הסיר מהר.', 'The neighbour gave him the pot fast.'),
    ('בבוקר הוא בא לבית של ג\'וחא.', 'In the morning he came to Juha’s house.'),
    ('הוא אמר: באתי לראות מה שלומך.', 'He said: I came to see how you are.'),
    ('ג\'וחא אמר: תיכנס, בבקשה.', 'Juha said: come in, please.')),
  P(('על האש עמד הסיר, וריח עלה.', 'On the fire stood the pot, and a smell rose.'),
    ('השכן ישב וחיכה זמן רב.', 'The neighbour sat and waited a long time.'),
    ('בסוף ג\'וחא פתח את הסיר.', 'In the end Juha opened the pot.'),
    ('היו בתוכו רק מים ואבן.', 'Inside it were only water and a stone.'),
    ('ג\'וחא אמר: אתמול היה לך בשר.', 'Juha said: yesterday you had meat.'),
    ('הוא אמר: והיום יש לי ריח.', 'He said: and today I have a smell.'))]),
 ('The Fur Coat in Summer', 'מעיל הפרווה בקיץ', [
  P(('בקיץ החם ג\'וחא לבש מעיל.', 'In the hot summer Juha wore a coat.'),
    ('המעיל היה כבד וחם מאוד.', 'The coat was heavy and very warm.'),
    ('אנשים בשוק שאלו אותו.', 'People at the market asked him.'),
    ('הם אמרו: לא חם לך ככה?', 'They said: are you not hot like that?')),
  P(('ג\'וחא אמר: אני יודע מה אני עושה.', 'Juha said: I know what I am doing.'),
    ('הוא הלך בשמש עם המעיל.', 'He walked in the sun with the coat.'),
    ('הזיעה ירדה על הפנים שלו.', 'The sweat ran down his face.'),
    ('הוא לא הוריד אותו בכלל.', 'He did not take it off at all.')),
  P(('בערב הוא ישב עם החברים.', 'In the evening he sat with his friends.'),
    ('אחד שאל שוב על המעיל.', 'One asked again about the coat.'),
    ('ג\'וחא אמר: תקשיבו רגע.', 'Juha said: listen a moment.'),
    ('הוא אמר: בחורף אני קונה לחם.', 'He said: in the winter I buy bread.')),
  P(('הוא אמר: ובקיץ אין לי כסף.', 'He said: and in the summer I have no money.'),
    ('הוא אמר: המעיל הזה הוא הבית שלי.', 'He said: this coat is my house.'),
    ('הוא אמר: הוא שומר עליי מהשמש.', 'He said: it protects me from the sun.'),
    ('הוא אמר: ובחורף מהגשם ומהקור.', 'He said: and in the winter from the rain and the cold.'),
    ('הוא אמר: לעני אין שני בגדים.', 'He said: a poor man does not have two garments.'))]),
 ('The Debt', 'החוב', [
  P(('ג\'וחא לווה כסף משכן.', 'Juha borrowed money from a neighbour.'),
    ('הוא הבטיח להחזיר בעוד חודש.', 'He promised to return it in a month.'),
    ('החודש עבר, ולא היה לו כסף.', 'The month passed, and he had no money.'),
    ('השכן בא ודפק בדלת.', 'The neighbour came and knocked at the door.')),
  P(('ג\'וחא פתח והזמין אותו פנימה.', 'Juha opened and invited him inside.'),
    ('הוא הביא לו קפה ותמרים.', 'He brought him coffee and dates.'),
    ('השכן שתה ואז אמר: והכסף?', 'The neighbour drank and then said: and the money?'),
    ('ג\'וחא אמר: אני חושב על זה כל יום.', 'Juha said: I think about it every day.')),
  P(('השכן שאל: אז מתי תחזיר?', 'The neighbour asked: so when will you return it?'),
    ('ג\'וחא אמר: יש לי תוכנית טובה.', 'Juha said: I have a good plan.'),
    ('הוא אמר: אני אמכור את הצמר.', 'He said: I shall sell the wool.'),
    ('השכן שאל: איזה צמר יש לך?', 'The neighbour asked: what wool do you have?')),
  P(('ג\'וחא אמר: אין לי צמר עדיין.', 'Juha said: I do not have wool yet.'),
    ('הוא אמר: אני אקנה כבשים.', 'He said: I shall buy sheep.'),
    ('השכן שאל: ובאיזה כסף?', 'The neighbour asked: and with what money?'),
    ('ג\'וחא אמר: בכסף מהצמר.', 'Juha said: with the money from the wool.'),
    ('השכן קם והלך בלי לומר מילה.', 'The neighbour got up and went without saying a word.'))]),
 ('The Old Tree', 'העץ של הזקן', [
  P(('ג\'וחא ראה זקן שותל עץ.', 'Juha saw an old man planting a tree.'),
    ('הזקן היה בן תשעים שנה.', 'The old man was ninety years old.'),
    ('הוא חפר לאט מאוד באדמה.', 'He dug very slowly in the earth.'),
    ('ג\'וחא עמד והסתכל עליו.', 'Juha stood and looked at him.')),
  P(('הוא שאל: איזה עץ זה?', 'He asked: what tree is this?'),
    ('הזקן אמר: עץ של אגוזים.', 'The old man said: a nut tree.'),
    ('ג\'וחא שאל: ומתי הוא נותן פרי?', 'Juha asked: and when does it give fruit?'),
    ('הזקן אמר: אחרי עשרים שנה.', 'The old man said: after twenty years.')),
  P(('ג\'וחא צחק ואמר בשקט: סליחה.', 'Juha laughed and said quietly: forgive me.'),
    ('הוא אמר: אתה לא תאכל ממנו.', 'He said: you will not eat from it.'),
    ('הזקן המשיך לחפור ולא הרים ראש.', 'The old man went on digging and did not raise his head.'),
    ('הוא אמר: גם אני לא שתלתי.', 'He said: I did not plant either.')),
  P(('הוא אמר: ואכלתי כל החיים.', 'He said: and I ate all my life.'),
    ('הוא אמר: מישהו שתל בשבילי.', 'He said: someone planted for me.'),
    ('ג\'וחא לקח מקל והתחיל לחפור.', 'Juha took a stick and began to dig.'),
    ('הם שתלו יחד עד הערב.', 'They planted together until the evening.'))]),
 ('The Broken Jar', 'הכד השבור', [
  P(('ג\'וחא שלח את הבן שלו למים.', 'Juha sent his son for water.'),
    ('הוא נתן לו כד גדול ויפה.', 'He gave him a big, fine jar.'),
    ('לפני שהבן יצא מהבית.', 'Before the son went out of the house.'),
    ('ג\'וחא נתן לו מכה קלה.', 'Juha gave him a light blow.')),
  P(('הבן צעק: למה הכית אותי?', 'The son shouted: why did you strike me?'),
    ('הוא אמר: לא עשיתי שום דבר.', 'He said: I did not do anything.'),
    ('ג\'וחא אמר: זה בשביל הכד.', 'Juha said: that is for the jar.'),
    ('הוא אמר: אם תשבור אותו, זה כואב.', 'He said: if you break it, it hurts.')),
  P(('שכן עמד בחוץ וראה הכול.', 'A neighbour stood outside and saw everything.'),
    ('הוא נכנס ואמר: זה לא נכון.', 'He came in and said: that is not right.'),
    ('הוא אמר: הוא עוד לא שבר.', 'He said: he has not broken it yet.'),
    ('ג\'וחא אמר: וכשישבור אותו?', 'Juha said: and when he breaks it?')),
  P(('הוא אמר: אז יהיה מאוחר מדי.', 'He said: then it will be too late.'),
    ('הוא אמר: הכד כבר לא יחזור.', 'He said: the jar will not come back.'),
    ('השכן שתק ולא ידע מה לומר.', 'The neighbour was silent and did not know what to say.'),
    ('הבן הלך והביא מים בשקט.', 'The son went and brought water quietly.'))]),
 ('Both Are Right', 'שניהם צודקים', [
  P(('ג\'וחא ישב פעם בבית משפט.', 'Juha once sat in a court.'),
    ('הוא היה השופט של אותו יום.', 'He was the judge of that day.'),
    ('שני אנשים נכנסו וצעקו.', 'Two men came in and shouted.'),
    ('הראשון סיפר את כל הסיפור.', 'The first told the whole story.')),
  P(('הוא סיפר על עז ועל שדה.', 'He told about a goat and about a field.'),
    ('הוא אמר: העז אכלה את הכול.', 'He said: the goat ate everything.'),
    ('ג\'וחא הקשיב וחשב רגע.', 'Juha listened and thought a moment.'),
    ('הוא אמר: אתה צודק לגמרי.', 'He said: you are completely right.')),
  P(('השני קם ואמר: תשמע גם אותי.', 'The second got up and said: hear me too.'),
    ('הוא סיפר על גדר שבורה.', 'He told about a broken fence.'),
    ('הוא אמר: הוא לא תיקן אותה.', 'He said: he did not repair it.'),
    ('ג\'וחא אמר: גם אתה צודק.', 'Juha said: you are right too.')),
  P(('אשתו ישבה בפינה ושמעה.', 'His wife sat in the corner and heard.'),
    ('היא אמרה: זה לא יכול להיות.', 'She said: that cannot be.'),
    ('היא אמרה: שניים לא צודקים יחד.', 'She said: two are not right together.'),
    ('ג\'וחא הסתכל בה ואמר: נכון.', 'Juha looked at her and said: true.'),
    ('הוא אמר: וגם את צודקת.', 'He said: and you are right too.'))]),
 ('The Heavy Basket', 'הסל הכבד', [
  P(('ג\'וחא נסע לעיר על החמור.', 'Juha travelled to the city on the donkey.'),
    ('היה לו סל כבד מלא ירקות.', 'He had a heavy basket full of vegetables.'),
    ('הוא ישב על החמור בדרך.', 'He sat on the donkey on the road.'),
    ('את הסל הוא החזיק על הראש.', 'The basket he held on his head.')),
  P(('הצוואר שלו כאב מאוד.', 'His neck hurt a great deal.'),
    ('הידיים שלו נעשו עייפות.', 'His hands became tired.'),
    ('הוא לא הוריד את הסל בכלל.', 'He did not put the basket down at all.'),
    ('איש עבר בדרך וראה אותו.', 'A man passed on the road and saw him.')),
  P(('הוא שאל: למה זה על הראש?', 'He asked: why is it on your head?'),
    ('הוא אמר: תשים אותו על החמור.', 'He said: put it on the donkey.'),
    ('ג\'וחא אמר: אני איש טוב.', 'Juha said: I am a good man.'),
    ('הוא אמר: החמור נושא אותי כבר.', 'He said: the donkey carries me already.')),
  P(('הוא אמר: זה מספיק בשבילו.', 'He said: that is enough for it.'),
    ('הוא אמר: את הסל אני נושא.', 'He said: the basket I carry.'),
    ('האיש צחק והמשיך בדרך.', 'The man laughed and continued on the road.'),
    ('ג\'וחא הגיע לעיר עם כאב ראש.', 'Juha reached the city with a headache.'))]),
 ('Nine Months', 'תשעה חודשים', [
  P(('לג\'וחא נולד בן אחרי שנה.', 'A son was born to Juha after a year.'),
    ('כל הכפר בא לברך אותו.', 'The whole village came to bless him.'),
    ('הם ישבו בחצר ושתו קפה.', 'They sat in the yard and drank coffee.'),
    ('אחד שאל: מתי בדיוק נולד?', 'One asked: when exactly was he born?')),
  P(('ג\'וחא אמר: לפני שישה חודשים.', 'Juha said: six months ago.'),
    ('האיש אמר: אבל התחתנת לפני שנה.', 'The man said: but you married a year ago.'),
    ('ג\'וחא אמר: נכון מאוד.', 'Juha said: quite right.'),
    ('האיש אמר: אז זה לא מסתדר.', 'The man said: then it does not fit.')),
  P(('ג\'וחא לקח נייר ועיפרון.', 'Juha took paper and a pencil.'),
    ('הוא אמר: בוא נחשב יחד.', 'He said: let us calculate together.'),
    ('הוא אמר: אני נשוי שנה שלמה.', 'He said: I am married a whole year.'),
    ('הוא אמר: וגם אשתי, שנה שלמה.', 'He said: and my wife also, a whole year.')),
  P(('הוא אמר: וגם הבן, שישה חודשים.', 'He said: and the son also, six months.'),
    ('הוא אמר: שנה ושנה זה שנתיים.', 'He said: a year and a year is two years.'),
    ('הוא אמר: ועוד חצי, זה יותר.', 'He said: and another half, that is more.'),
    ('הוא אמר: אז מה הבעיה בדיוק?', 'He said: so what exactly is the problem?'),
    ('כולם שתקו ושתו את הקפה.', 'Everyone was silent and drank the coffee.'))]),
 ('The Guest Who Stayed', 'האורח שנשאר', [
  P(('אורח בא לבית של ג\'וחא.', 'A guest came to Juha’s house.'),
    ('הוא היה בן דוד רחוק מאוד.', 'He was a very distant cousin.'),
    ('ג\'וחא קיבל אותו יפה מאוד.', 'Juha received him very nicely.'),
    ('הוא הביא לו אוכל ומיטה.', 'He brought him food and a bed.')),
  P(('אחרי יומיים האורח נשאר.', 'After two days the guest stayed.'),
    ('אחרי שבוע הוא עוד היה שם.', 'After a week he was still there.'),
    ('אשתו של ג\'וחא כעסה מאוד.', 'Juha’s wife was very angry.'),
    ('היא אמרה: תגיד לו משהו.', 'She said: say something to him.')),
  P(('ג\'וחא לא רצה לפגוע בו.', 'Juha did not want to hurt him.'),
    ('בבוקר הוא ישב איתו לאכול.', 'In the morning he sat with him to eat.'),
    ('הוא אמר: יש לי שאלה קטנה.', 'He said: I have a small question.'),
    ('הוא שאל: דג טרי כמה ימים טוב?', 'He asked: a fresh fish is good for how many days?')),
  P(('האורח אמר: יומיים, אולי שלושה.', 'The guest said: two days, maybe three.'),
    ('ג\'וחא אמר: ואחרי זה?', 'Juha said: and after that?'),
    ('האורח אמר: אחרי זה יש ריח.', 'The guest said: after that there is a smell.'),
    ('ג\'וחא אמר: וגם אורח ככה.', 'Juha said: and a guest is the same.'),
    ('האורח לקח את התיק והלך.', 'The guest took his bag and went.'))]),
 ('Which Is Older', 'מה יותר חשוב', [
  P(('בבית הקפה ישבו אנשים בערב.', 'In the coffee house people sat in the evening.'),
    ('הם דיברו על השמש ועל הירח.', 'They talked about the sun and about the moon.'),
    ('אחד שאל: מה יותר חשוב?', 'One asked: which is more important?'),
    ('כולם ענו: השמש, כמובן.', 'Everyone answered: the sun, of course.')),
  P(('ג\'וחא ישב בפינה ושתה.', 'Juha sat in the corner and drank.'),
    ('הוא אמר: אתם טועים לגמרי.', 'He said: you are completely wrong.'),
    ('כולם הסתובבו והסתכלו עליו.', 'Everyone turned and looked at him.'),
    ('הם שאלו: אז מה יותר חשוב?', 'They asked: so which is more important?')),
  P(('ג\'וחא אמר: הירח, בלי ספק.', 'Juha said: the moon, without doubt.'),
    ('הם צחקו ושאלו למה.', 'They laughed and asked why.'),
    ('הוא אמר: תחשבו על זה רגע.', 'He said: think about it a moment.'),
    ('הוא אמר: הירח בא בלילה.', 'He said: the moon comes at night.')),
  P(('הוא אמר: בלילה חשוך מאוד.', 'He said: at night it is very dark.'),
    ('הוא אמר: ואנחנו צריכים אור.', 'He said: and we need light.'),
    ('הוא אמר: השמש באה ביום.', 'He said: the sun comes in the day.'),
    ('הוא אמר: וביום ממילא יש אור.', 'He said: and in the day there is light anyway.'),
    ('כולם שתקו וחשבו על זה.', 'Everyone was silent and thought about it.'))]),
 ('The Mirror', 'המראה', [
  P(('ג\'וחא מצא מראה בדרך.', 'Juha found a mirror on the road.'),
    ('הוא מעולם לא ראה מראה.', 'He had never seen a mirror.'),
    ('הוא הרים אותה והסתכל בה.', 'He picked it up and looked in it.'),
    ('הוא ראה שם פנים של איש.', 'He saw there a man’s face.')),
  P(('הוא אמר: איזה איש מכוער.', 'He said: what an ugly man.'),
    ('הוא זרק אותה חזרה לאדמה.', 'He threw it back on the ground.'),
    ('הוא הלך קצת והפסיק.', 'He walked a little and stopped.'),
    ('הוא חשב: אולי לא יפה לזרוק.', 'He thought: perhaps it is not nice to throw.')),
  P(('הוא חזר והרים אותה שוב.', 'He came back and picked it up again.'),
    ('הוא הסתכל בה עוד פעם.', 'He looked in it one more time.'),
    ('הוא אמר: אני מבין עכשיו.', 'He said: I understand now.'),
    ('הוא אמר: הוא זרק אותה בעצמו.', 'He said: he threw it away himself.')),
  P(('הוא אמר: הוא ידע איך הוא נראה.', 'He said: he knew how he looks.'),
    ('הוא שם אותה בצד הדרך.', 'He put it at the side of the road.'),
    ('הוא כיסה אותה בעלים.', 'He covered it with leaves.'),
    ('הוא אמר: שלא יראה אותה שוב.', 'He said: so that he will not see it again.'))]),
 ('The Wrong Grave', 'הקבר הלא נכון', [
  P(('ג\'וחא הלך בלילה בדרך.', 'Juha walked at night on the road.'),
    ('הוא עבר ליד בית קברות.', 'He passed beside a cemetery.'),
    ('הוא שמע קול מאחוריו.', 'He heard a sound behind him.'),
    ('הוא פחד מאוד והתחיל לרוץ.', 'He was very afraid and began to run.')),
  P(('הוא קפץ מעל הגדר פנימה.', 'He jumped over the fence inside.'),
    ('הוא ראה חור פתוח באדמה.', 'He saw an open hole in the ground.'),
    ('הוא נכנס לתוכו ושכב בשקט.', 'He went into it and lay quietly.'),
    ('הוא חיכה שם זמן רב.', 'He waited there a long time.')),
  P(('שני אנשים עברו ליד החור.', 'Two men passed beside the hole.'),
    ('הם ראו איש שוכב בפנים.', 'They saw a man lying inside.'),
    ('הם שאלו: מי אתה, אדוני?', 'They asked: who are you, sir?'),
    ('הם שאלו: ומה אתה עושה כאן?', 'They asked: and what are you doing here?')),
  P(('ג\'וחא הרים את הראש לאט.', 'Juha raised his head slowly.'),
    ('הוא אמר: אני מת, כמובן.', 'He said: I am dead, of course.'),
    ('הם שאלו: ולמה אתה מדבר?', 'They asked: and why do you speak?'),
    ('הוא אמר: כי אתם שאלתם אותי.', 'He said: because you asked me.'),
    ('הוא אמר: מת גם עונה לפעמים.', 'He said: a dead man also answers sometimes.'))]),
 ('The Egg', 'הביצה', [
  P(('ג\'וחא ישב עם חברים בערב.', 'Juha sat with friends in the evening.'),
    ('הם רצו לצחוק ממנו קצת.', 'They wanted to laugh at him a little.'),
    ('אחד אמר: יש לנו משחק.', 'One said: we have a game.'),
    ('הוא אמר: כל אחד ישים ביצה.', 'He said: each one will put an egg.')),
  P(('הוא אמר: נשים אותן במים.', 'He said: we shall put them in water.'),
    ('הוא אמר: מי שאין לו, משלם.', 'He said: whoever does not have one, pays.'),
    ('כולם הביאו ביצה מהכיס.', 'Everyone brought an egg from his pocket.'),
    ('לג\'וחא לא הייתה ביצה.', 'Juha did not have an egg.')),
  P(('הם צחקו והסתכלו עליו.', 'They laughed and looked at him.'),
    ('ג\'וחא קם ועמד רגע.', 'Juha got up and stood a moment.'),
    ('ואז הוא צעק כמו תרנגול.', 'And then he crowed like a cock.'),
    ('הוא צעק חזק מאוד בחדר.', 'He crowed very loudly in the room.')),
  P(('כולם שאלו: מה זה היה?', 'Everyone asked: what was that?'),
    ('ג\'וחא אמר: זה פשוט מאוד.', 'Juha said: it is very simple.'),
    ('הוא אמר: כולם כאן תרנגולות.', 'He said: everyone here is a hen.'),
    ('הוא אמר: והן מביאות ביצים.', 'He said: and they bring eggs.'),
    ('הוא אמר: ואני התרנגול שלכן.', 'He said: and I am your cock.'))]),
 ('Teaching the Donkey', 'מלמדים את החמור', [
  P(('המלך שמע על ג\'וחא בעיר.', 'The king heard about Juha in the city.'),
    ('הוא קרא לו לבוא לארמון.', 'He called him to come to the palace.'),
    ('ג\'וחא בא עם החמור שלו.', 'Juha came with his donkey.'),
    ('המלך שאל: אתה איש חכם?', 'The king asked: are you a wise man?')),
  P(('ג\'וחא אמר: אני מלמד דברים.', 'Juha said: I teach things.'),
    ('המלך צחק ואמר: באמת?', 'The king laughed and said: really?'),
    ('הוא אמר: אז תלמד את החמור.', 'He said: then teach the donkey.'),
    ('הוא אמר: תלמד אותו לקרוא.', 'He said: teach it to read.')),
  P(('ג\'וחא אמר: אין שום בעיה.', 'Juha said: there is no problem at all.'),
    ('הוא אמר: אני צריך עשר שנים.', 'He said: I need ten years.'),
    ('הוא אמר: ואני צריך גם כסף.', 'He said: and I also need money.'),
    ('המלך נתן לו שק של זהב.', 'The king gave him a sack of gold.')),
  P(('חבר שאל אותו בדרך הביתה.', 'A friend asked him on the way home.'),
    ('הוא אמר: אתה משוגע לגמרי.', 'He said: you are completely mad.'),
    ('הוא אמר: החמור לא יקרא לעולם.', 'He said: the donkey will never read.'),
    ('ג\'וחא אמר: עשר שנים זה הרבה.', 'Juha said: ten years is a lot.'),
    ('הוא אמר: או שהמלך ימות.', 'He said: either the king will die.'),
    ('הוא אמר: או שאני אמות.', 'He said: or I shall die.'),
    ('הוא אמר: או שהחמור ימות.', 'He said: or the donkey will die.'))]),
 ('The Fastest Way', 'הדרך הכי מהירה', [
  P(('ג\'וחא רצה להגיע לכפר.', 'Juha wanted to reach a village.'),
    ('היו שתי דרכים מהבית שלו.', 'There were two roads from his house.'),
    ('אחת הייתה קצרה אבל קשה.', 'One was short but hard.'),
    ('השנייה הייתה ארוכה וקלה.', 'The second was long and easy.')),
  P(('הוא בחר בדרך הקצרה.', 'He chose the short road.'),
    ('הדרך עלתה על הר גבוה.', 'The road went up a high mountain.'),
    ('היו שם אבנים גדולות.', 'There were big stones there.'),
    ('החמור הלך לאט מאוד.', 'The donkey walked very slowly.')),
  P(('אחרי שעה החמור עצר.', 'After an hour the donkey stopped.'),
    ('הוא לא רצה ללכת יותר.', 'It did not want to walk any more.'),
    ('ג\'וחא ירד ומשך אותו.', 'Juha got down and pulled it.'),
    ('החמור ישב על האדמה.', 'The donkey sat on the ground.')),
  P(('ג\'וחא חזר בדרך הארוכה.', 'Juha went back by the long road.'),
    ('הוא הגיע לכפר בערב.', 'He reached the village in the evening.'),
    ('חבר שאל: איך הייתה הדרך?', 'A friend asked: how was the road?'),
    ('הוא אמר: הקצרה היא הארוכה.', 'He said: the short one is the long one.'),
    ('הוא אמר: והארוכה היא הקצרה.', 'He said: and the long one is the short one.'))]),
 ('The Two Ends', 'שני הצדדים', [
  P(('ג\'וחא ישב על ענף בעץ.', 'Juha sat on a branch in a tree.'),
    ('הוא חתך את הענף במסור.', 'He cut the branch with a saw.'),
    ('הוא ישב על הצד הרחוק.', 'He sat on the far side.'),
    ('הוא חתך בין העץ ובינו.', 'He cut between the tree and himself.')),
  P(('איש עבר בדרך וראה אותו.', 'A man passed on the road and saw him.'),
    ('הוא צעק: אתה תיפול!', 'He shouted: you will fall!'),
    ('ג\'וחא לא הקשיב לו בכלל.', 'Juha did not listen to him at all.'),
    ('הוא המשיך לחתוך בשקט.', 'He went on cutting quietly.')),
  P(('אחרי דקה הענף נשבר.', 'After a minute the branch broke.'),
    ('ג\'וחא נפל על האדמה.', 'Juha fell on the ground.'),
    ('הוא קם ורץ אחרי האיש.', 'He got up and ran after the man.'),
    ('הוא צעק: תעצור, בבקשה!', 'He shouted: stop, please!')),
  P(('הוא אמר: ידעת שאני אפול.', 'He said: you knew that I would fall.'),
    ('הוא אמר: אז אתה יודע דברים.', 'He said: so you know things.'),
    ('הוא שאל: מתי אני אמות?', 'He asked: when shall I die?'),
    ('האיש ברח ולא ענה לו.', 'The man ran away and did not answer him.'))]),
 ('The Bag of Onions', 'שק הבצל', [
  P(('ג\'וחא הלך בשוק בבוקר.', 'Juha walked in the market in the morning.'),
    ('הוא ראה שק גדול של בצל.', 'He saw a big sack of onions.'),
    ('המחיר היה נמוך מאוד.', 'The price was very low.'),
    ('הוא קנה את כל השק.', 'He bought the whole sack.')),
  P(('הוא הביא אותו הביתה בשמחה.', 'He brought it home happily.'),
    ('אשתו שאלה: מה נעשה עם זה?', 'His wife asked: what shall we do with this?'),
    ('הוא אמר: נמכור בכפר ביוקר.', 'He said: we shall sell in the village at a high price.'),
    ('היא אמרה: בכפר יש בצל.', 'She said: in the village there are onions.')),
  P(('הוא לקח את השק לכפר.', 'He took the sack to the village.'),
    ('הוא עמד שם כל היום.', 'He stood there all day.'),
    ('איש אחד לא קנה ממנו.', 'Not one man bought from him.'),
    ('בערב הוא חזר עם השק.', 'In the evening he came back with the sack.')),
  P(('אשתו שאלה: אז מה עכשיו?', 'His wife asked: so what now?'),
    ('ג\'וחא אמר: אני חושב על זה.', 'Juha said: I am thinking about it.'),
    ('הוא אמר: אנחנו נאכל בצל.', 'He said: we shall eat onions.'),
    ('הוא אמר: כל יום, עד הסוף.', 'He said: every day, until the end.'),
    ('היא אמרה: זאת התוכנית שלך?', 'She said: is that your plan?'))]),
 ('Two Dinners', 'שתי ארוחות', [
  P(('שני אנשים הזמינו את ג\'וחא.', 'Two men invited Juha.'),
    ('שניהם הזמינו לאותו ערב.', 'Both invited for the same evening.'),
    ('הוא אמר לשניהם: אני אבוא.', 'He said to both: I shall come.'),
    ('אשתו אמרה: זה לא אפשרי.', 'His wife said: that is not possible.')),
  P(('הוא הלך קודם לבית הראשון.', 'He went first to the first house.'),
    ('הם ישבו ואכלו לאט מאוד.', 'They sat and ate very slowly.'),
    ('ג\'וחא הסתכל על החלון.', 'Juha looked at the window.'),
    ('הוא חשב על הבית השני.', 'He thought about the second house.')),
  P(('הוא אמר: סליחה, שכחתי דבר.', 'He said: forgive me, I forgot a thing.'),
    ('הוא יצא ורץ לבית השני.', 'He went out and ran to the second house.'),
    ('שם כבר אכלו את הבשר.', 'There they had already eaten the meat.'),
    ('נשאר רק לחם על השולחן.', 'Only bread remained on the table.')),
  P(('הוא חזר מהר לבית הראשון.', 'He went back fast to the first house.'),
    ('שם כבר לקחו את הצלחות.', 'There they had already taken the plates.'),
    ('ג\'וחא ישב ולא אמר כלום.', 'Juha sat and did not say anything.'),
    ('הוא הלך הביתה רעב מאוד.', 'He went home very hungry.'),
    ('אשתו נתנה לו לחם ומים.', 'His wife gave him bread and water.'))]),
 ('The Neighbour Who Never Returns', 'השכן שלא מחזיר', [
  P(('לשכן היה מנהג לא נעים.', 'The neighbour had an unpleasant habit.'),
    ('הוא לקח דברים ולא החזיר.', 'He took things and did not return them.'),
    ('הוא לקח מקל, ואז סכין.', 'He took a stick, and then a knife.'),
    ('ג\'וחא נתן ולא אמר כלום.', 'Juha gave and did not say anything.')),
  P(('יום אחד הוא בא שוב.', 'One day he came again.'),
    ('הוא ביקש את החבל הארוך.', 'He asked for the long rope.'),
    ('ג\'וחא אמר: אני מצטער.', 'Juha said: I am sorry.'),
    ('הוא אמר: החבל תפוס עכשיו.', 'He said: the rope is busy now.')),
  P(('השכן שאל: תפוס במה?', 'The neighbour asked: busy with what?'),
    ('ג\'וחא אמר: אנחנו שמים עליו קמח.', 'Juha said: we are putting flour on it.'),
    ('השכן צעק: קמח על חבל?', 'The neighbour shouted: flour on a rope?'),
    ('הוא אמר: זה לא הגיוני בכלל.', 'He said: that is not sensible at all.')),
  P(('ג\'וחא אמר: אתה צודק.', 'Juha said: you are right.'),
    ('הוא אמר: זה באמת מוזר.', 'He said: it is really strange.'),
    ('הוא אמר: אבל אם לא רוצים לתת.', 'He said: but if one does not want to give.'),
    ('הוא אמר: אז הכול הגיוני מספיק.', 'He said: then everything is sensible enough.'))]),
 ('The Sweetest Thing', 'הדבר הכי מתוק', [
  P(('בבית הקפה שאלו שאלה.', 'In the coffee house they asked a question.'),
    ('הם שאלו: מה הדבר הכי מתוק?', 'They asked: what is the sweetest thing?'),
    ('אחד אמר: דבש מהכפר.', 'One said: honey from the village.'),
    ('אחר אמר: תמרים מהעץ.', 'Another said: dates from the tree.')),
  P(('אחד אמר: סוכר מהעיר.', 'One said: sugar from the city.'),
    ('כולם הסכימו שזה נכון.', 'Everyone agreed that it is true.'),
    ('ג\'וחא ישב ולא אמר כלום.', 'Juha sat and did not say anything.'),
    ('הם שאלו אותו: ומה אתה אומר?', 'They asked him: and what do you say?')),
  P(('ג\'וחא אמר: כולם כאן טועים.', 'Juha said: everyone here is wrong.'),
    ('הוא אמר: הדבר הכי מתוק הוא שינה.', 'He said: the sweetest thing is sleep.'),
    ('הם צחקו ואמרו: שינה?', 'They laughed and said: sleep?'),
    ('הם אמרו: אין לה טעם בכלל.', 'They said: it has no taste at all.')),
  P(('הוא אמר: תחשבו על הבוקר.', 'He said: think about the morning.'),
    ('הוא אמר: אתם עייפים מאוד.', 'He said: you are very tired.'),
    ('הוא אמר: אני אשים דבש לידכם.', 'He said: I shall put honey beside you.'),
    ('הוא אמר: ואשים גם עוד חצי שעה.', 'He said: and I shall also put another half hour.'),
    ('הוא שאל: מה תבחרו מהשניים?', 'He asked: which of the two will you choose?'))]),
 ('The Empty Purse', 'הארנק הריק', [
  P(('ג\'וחא איבד את הארנק שלו.', 'Juha lost his purse.'),
    ('הוא חיפש אותו בכל הבית.', 'He looked for it in the whole house.'),
    ('הוא לא מצא אותו בשום מקום.', 'He did not find it anywhere.'),
    ('הוא יצא לרחוב ושאל אנשים.', 'He went out to the street and asked people.')),
  P(('הוא הכריז בשוק בקול גדול.', 'He announced in the market in a loud voice.'),
    ('הוא אמר: מי שמצא ארנק.', 'He said: whoever found a purse.'),
    ('הוא אמר: יקבל ממני חצי.', 'He said: will receive half from me.'),
    ('איש אחד בא מיד אליו.', 'A man came to him at once.')),
  P(('הוא אמר: מצאתי אותו בדרך.', 'He said: I found it on the road.'),
    ('הוא נתן לג\'וחא את הארנק.', 'He gave Juha the purse.'),
    ('ג\'וחא פתח אותו והסתכל.', 'Juha opened it and looked.'),
    ('היו בפנים עשרה מטבעות.', 'Inside were ten coins.')),
  P(('ג\'וחא אמר: היו שם עשרים.', 'Juha said: there were twenty there.'),
    ('הוא אמר: אז לקחת את החצי.', 'He said: so you took the half.'),
    ('הוא אמר: וזה בדיוק הפרס שלך.', 'He said: and that is exactly your prize.'),
    ('הוא אמר: תודה רבה לך, אדוני.', 'He said: thank you very much, sir.'),
    ('האיש עמד ולא ידע מה לומר.', 'The man stood and did not know what to say.'))]),
 ('The Wise Fool', 'החכם שנראה טיפש', [
  P(('בעיר ידעו שג\'וחא מוזר.', 'In the city they knew that Juha is strange.'),
    ('ילדים היו עושים ממנו צחוק.', 'Children used to make fun of him.'),
    ('הם הראו לו שני מטבעות.', 'They showed him two coins.'),
    ('אחד היה גדול ואחד קטן.', 'One was big and one was small.')),
  P(('הם אמרו: תבחר אחד מהם.', 'They said: choose one of them.'),
    ('ג\'וחא לקח תמיד את הגדול.', 'Juha always took the big one.'),
    ('הגדול היה שווה פחות.', 'The big one was worth less.'),
    ('הילדים צחקו כל פעם מחדש.', 'The children laughed every time anew.')),
  P(('איש מבוגר ראה את זה.', 'A grown man saw that.'),
    ('הוא לקח את ג\'וחא הצידה.', 'He took Juha aside.'),
    ('הוא אמר: הקטן שווה יותר.', 'He said: the small one is worth more.'),
    ('הוא אמר: אתה מפסיד כל יום.', 'He said: you lose every day.')),
  P(('ג\'וחא אמר: אני יודע את זה.', 'Juha said: I know that.'),
    ('הוא אמר: אני יודע כבר שנים.', 'He said: I have known for years.'),
    ('הוא אמר: אבל אם אקח את הקטן.', 'He said: but if I take the small one.'),
    ('הוא אמר: הם יפסיקו לשחק איתי.', 'He said: they will stop playing with me.'),
    ('הוא אמר: ואז לא אקבל כלום.', 'He said: and then I shall receive nothing.'))]),
 ('The Letter', 'המכתב', [
  P(('איש בא לג\'וחא עם נייר.', 'A man came to Juha with a paper.'),
    ('הוא אמר: תכתוב לי מכתב.', 'He said: write me a letter.'),
    ('הוא אמר: זה בשביל אחי בעיר.', 'He said: it is for my brother in the city.'),
    ('ג\'וחא ישב ולא לקח את העט.', 'Juha sat and did not take the pen.')),
  P(('הוא אמר: אני לא יכול היום.', 'He said: I cannot today.'),
    ('הוא אמר: הרגל שלי כואבת.', 'He said: my leg hurts.'),
    ('האיש שאל: מה הקשר לרגל?', 'The man asked: what does the leg have to do with it?'),
    ('הוא אמר: אתה כותב ביד.', 'He said: you write with your hand.')),
  P(('ג\'וחא אמר: זה נכון מאוד.', 'Juha said: that is quite right.'),
    ('הוא אמר: אבל אף אחד לא קורא.', 'He said: but no one can read it.'),
    ('הוא אמר: הכתב שלי קשה מאוד.', 'He said: my handwriting is very hard.'),
    ('הוא אמר: רק אני קורא אותו.', 'He said: only I read it.')),
  P(('הוא אמר: אז אני אצטרך לנסוע.', 'He said: so I shall have to travel.'),
    ('הוא אמר: אני אלך עד העיר.', 'He said: I shall go all the way to the city.'),
    ('הוא אמר: ואני אקרא לאחיך בקול.', 'He said: and I shall read it aloud to your brother.'),
    ('הוא אמר: וזה רחוק בשביל הרגל.', 'He said: and that is far for the leg.'))]),
 ('The Full Moon', 'הירח המלא', [
  P(('בלילה ג\'וחא הלך לבאר.', 'At night Juha went to the well.'),
    ('הוא הסתכל לתוך המים.', 'He looked into the water.'),
    ('הוא ראה שם את הירח.', 'He saw the moon there.'),
    ('הוא אמר: הירח נפל פנימה.', 'He said: the moon has fallen inside.')),
  P(('הוא רץ הביתה והביא חבל.', 'He ran home and brought a rope.'),
    ('הוא קשר לחבל אבן כבדה.', 'He tied a heavy stone to the rope.'),
    ('הוא זרק אותו לתוך הבאר.', 'He threw it into the well.'),
    ('הוא משך בכל הכוח שלו.', 'He pulled with all his strength.')),
  P(('האבן נתפסה בין אבנים.', 'The stone was caught among stones.'),
    ('הוא משך שוב, חזק מאוד.', 'He pulled again, very hard.'),
    ('החבל נקרע פתאום.', 'The rope tore suddenly.'),
    ('ג\'וחא נפל אחורה על הגב.', 'Juha fell backwards on his back.')),
  P(('הוא שכב על האדמה והסתכל.', 'He lay on the ground and looked.'),
    ('הירח היה למעלה בשמיים.', 'The moon was up in the sky.'),
    ('הוא אמר: תודה לאל.', 'He said: thanks be to God.'),
    ('הוא אמר: הוצאתי אותו בזמן.', 'He said: I got it out in time.'),
    ('הוא אמר: והגב שלי שילם על זה.', 'He said: and my back paid for it.'))]),
 ('Everyone Is a Little Right', 'לכל אחד יש קצת צדק', [
  P(('בסוף החיים ג\'וחא היה זקן.', 'At the end of his life Juha was old.'),
    ('הוא ישב בחצר עם הנכדים.', 'He sat in the yard with the grandchildren.'),
    ('הם ביקשו ממנו סיפור אחרון.', 'They asked him for a last story.'),
    ('הוא אמר: אני אספר על עצמי.', 'He said: I shall tell about myself.')),
  P(('הוא אמר: כל החיים צחקו ממני.', 'He said: all my life they laughed at me.'),
    ('הוא אמר: אמרו שאני טיפש.', 'He said: they said that I am foolish.'),
    ('הוא אמר: ואולי זה נכון.', 'He said: and perhaps it is true.'),
    ('הוא אמר: אבל תשימו לב לדבר.', 'He said: but notice one thing.')),
  P(('הוא אמר: הם זוכרים כל סיפור.', 'He said: they remember every story.'),
    ('הוא אמר: הם מספרים אותם לילדים.', 'He said: they tell them to their children.'),
    ('הוא אמר: ומי שמספר, לומד.', 'He said: and whoever tells, learns.'),
    ('הוא אמר: אז מי הטיפש כאן?', 'He said: so who is the fool here?')),
  P(('הנכד הקטן אמר: אתה, סבא.', 'The small grandson said: you, grandfather.'),
    ('כולם צחקו חזק בחצר.', 'Everyone laughed loudly in the yard.'),
    ('ג\'וחא צחק יותר מכולם.', 'Juha laughed more than everyone.'),
    ('הוא אמר: אתה צודק, ילד.', 'He said: you are right, child.'),
    ('הוא אמר: ולכל אחד יש קצת צדק.', 'He said: and everyone is a little right.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('juha', {'en': 'Juha', 'he': "ג'וחא"}, 'beginner', CHAPTERS,
                          unit='Tale', unit_he='מעשה', shelf=1, meta=META))
