#!/usr/bin/env python3
"""עשרים סיפורים: מופסאן וצ'כוב — twenty stories retold in modern Hebrew, graded to advanced.

The Hebrew twin of pipeline/book_shortstories.py: ten by Maupassant, ten by Chekhov, the same
twenty the Arabic shelf carries. Maupassant died in 1893 and Chekhov in 1904; both are public
domain, and these are retellings from the plots rather than translations of anyone's version.

WHY THIS IS THE LAST BOOK ON THE SHELF. Every other reader here rewards a reader who follows the
plot. These do not: the plot of "The Necklace" fits in one sentence and means nothing, and the
whole story is in what the last line does to the first. A reader who gets that in Hebrew is no
longer decoding Hebrew — which is the only honest definition of finishing a graded shelf.

The sentences are the longest in this project, and they carry the load in the tier's own way:
two clauses at a time, a past tense that does not restart at every sentence, and irony, which
needs the reader to hold what was said against what was meant.

Deliberately unpointed; the vowels are looked up at ingest.

Run:  python3 pipeline/he_book_shortstories.py --lang he            # check
      python3 pipeline/he_book_shortstories.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'short stories by Guy de Maupassant and Anton Chekhov',
        'author': 'Maupassant (d. 1893) and Chekhov (d. 1904)', 'year': '1880s–1900s',
        'status': 'public domain — retold from the plots, not from any translation'}

CHAPTERS = [
 ('Moonlight', 'אור הירח', [
  P(('הכומר היה איש גבוה, רזה, קשה, שהאמין בכל ליבו ולא הבין למה יש בעולם נשים.', 'The priest was a tall, thin, hard man, who believed with all his heart and did not understand why there are women in the world.'),
    ('הוא חשב שאלוהים ברא כל דבר לתכלית ברורה, ושהוא יודע את התכלית של כל דבר.', 'He thought that God created every thing for a clear purpose, and that he knows the purpose of every thing.'),
    ('הוא היה אומר: השמש בשביל היום, הגשם בשביל השדות, הלילה בשביל השינה, וזה הכול.', 'He used to say: the sun is for the day, the rain for the fields, the night for sleep, and that is all.'),
    ('רק את הנשים הוא לא הצליח להכניס לסדר הזה, והן הפריעו לו כמו טעות בחשבון.', 'Only women he did not manage to fit into that order, and they disturbed him like a mistake in a sum.'),
    ('הוא היה אומר עליהן שהן חלשות ומסוכנות, ושהן קיימות רק כדי להפיל גברים.', 'He used to say about them that they are weak and dangerous, and that they exist only in order to make men fall.')),
  P(('בבית שלו גרה אחיינית צעירה, יתומה, שהוא גידל מגיל קטן ושמר עליה מכל דבר.', 'In his house lived a young niece, an orphan, whom he raised from a small age and guarded from everything.'),
    ('היא הייתה שקטה, וצחקה מעט, ובחודשים האחרונים היא נעשתה שקטה עוד יותר.', 'She was quiet, and laughed little, and in the last months she became even quieter.'),
    ('היא הייתה יוצאת לגינה בערב ונשארת שם זמן רב, ומסתכלת על הדרך שיורדת לנהר.', 'She would go out to the garden in the evening and stay there a long time, and look at the road that goes down to the river.'),
    ('הוא ראה את זה, ולא אמר כלום, ובלב שלו התחיל לגדול חשד כבד.', 'He saw that, and said nothing, and in his heart a heavy suspicion began to grow.')),
  P(('יום אחד המשרתת אמרה לו בשקט: אדוני, יש לה מישהו, והם נפגשים ליד הנהר.', 'One day the maid said to him quietly: sir, she has someone, and they meet beside the river.'),
    ('הוא עמד רגע בלי לזוז, ואז הפנים שלו נעשו אדומות, והוא לא הצליח לדבר.', 'He stood a moment without moving, and then his face became red, and he could not speak.'),
    ('הוא חשב על כל מה שהוא לימד אותה, ועל התפילות, ועל הבית הנקי, ועל השקר.', 'He thought about everything that he taught her, and about the prayers, and about the clean house, and about the lie.'),
    ('הוא לקח מקל גדול מאחורי הדלת, ובדק אותו בידיים, ואז יצא החוצה בלי כובע.', 'He took a big stick from behind the door, and tested it in his hands, and went outside without a hat.'),
    ('הוא הלך מהר בשביל שיורד אל המים, ואמר לעצמו שהוא יגמור את זה הלילה.', 'He walked fast on the path that goes down to the water, and said to himself that he would finish this tonight.')),
  P(('ואז הוא יצא מבין העצים אל השדה הפתוח, ועצר, כי כל העולם היה לבן.', 'And then he came out from among the trees into the open field, and stopped, because the whole world was white.'),
    ('הירח היה מלא ונמוך, והאור שלו שכב על הדשא ועל המים ועל הגגות של הכפר.', 'The moon was full and low, and its light lay on the grass and on the water and on the roofs of the village.'),
    ('העצים עמדו שחורים מול האור, ובכל ענף היה משהו רך שהוא לא ראה שם קודם.', 'The trees stood black against the light, and in every branch there was something soft that he had not seen there before.'),
    ('ציפורים קטנות שרו בין העלים, בקול שמתאים ללילה ולא ליום, וכל השדה נשם.', 'Small birds sang among the leaves, in a voice that suits the night and not the day, and the whole field breathed.'),
    ('הוא עמד עם המקל ביד וחשב: בשביל מה אלוהים עשה לילה יפה כזה?', 'He stood with the stick in his hand and thought: for what did God make such a beautiful night?')),
  P(('הוא אמר לעצמו: ביום אני רואה את העבודה, את השדה, את הלחם, את הסדר.', 'He said to himself: in the day I see the work, the field, the bread, the order.'),
    ('אבל הלילה הזה לא נעשה בשביל שינה, כי מי שישן לא רואה ממנו כלום.', 'But this night was not made for sleep, because whoever sleeps sees nothing of it.'),
    ('ואז הוא ראה אותם, שני צללים הולכים לאט על שפת המים, קרובים מאוד.', 'And then he saw them, two shadows walking slowly on the edge of the water, very close.'),
    ('היא הניחה את הראש על הכתף שלו, והם לא דיברו, והלכו לתוך האור.', 'She rested her head on his shoulder, and they did not speak, and walked into the light.')),
  P(('הכומר הרים את המקל, ואז הוריד אותו, וידיו רעדו, והוא לא זז ממקומו.', 'The priest raised the stick, and then lowered it, and his hands trembled, and he did not move from his place.'),
    ('הוא חשב: אולי אלוהים עשה את הלילה הזה בשביל דבר אחד שאני מעולם לא הבנתי.', 'He thought: maybe God made this night for one thing that I have never understood.'),
    ('ואם הוא עשה אותו כל כך יפה, אולי הוא עשה אותו בשבילם ולא בשבילי.', 'And if he made it so beautiful, perhaps he made it for them and not for me.'),
    ('הוא הסתובב לאט, וחזר הביתה בדרך אחרת, כדי שהם לא ישמעו את הקולות שלו.', 'He turned around slowly, and went home by another road, so that they would not hear his steps.'),
    ('בבית הוא שם את המקל בחזרה מאחורי הדלת, ואז ישב בחושך, ולא הדליק נר.', 'At home he put the stick back behind the door, and sat in the dark, and did not light a candle.'))]),
 ('The Umbrella', 'המטרייה', [
  P(('הגברת אוריי הייתה אישה זהירה מאוד בכסף, וזאת מילה יפה מדי בשביל מה שהיא הייתה.', 'Madame Oreille was a woman very careful with money, and that is too nice a word for what she was.'),
    ('בבית שלה כל מטבע היה עובר דרך היד שלה פעמיים לפני שהוא יצא לעולם.', 'In her house every coin would pass through her hand twice before it went out into the world.'),
    ('הבעל שלה היה פקיד במשרד, ושכרו לא היה גדול, אבל גם לא היה קטן.', 'Her husband was a clerk in an office, and his wage was not big, but also was not small.'),
    ('ובכל זאת הוא היה מסתובב עם מעיל ישן, כי לבקש מעיל חדש היה עניין של שבועות.', 'And nevertheless he would go about in an old coat, because to ask for a new coat was a matter of weeks.')),
  P(('יום אחד הוא אמר לה: אני מוכרח מטרייה, כי זאת שיש לי כבר שנים.', 'One day he said to her: I must have an umbrella, because the one that I have is already years old.'),
    ('היא נתנה לו מטרייה זולה מאוד, שחורה, והוא לקח אותה למשרד באותו בוקר.', 'She gave him a very cheap umbrella, black, and he took it to the office that morning.'),
    ('החברים שלו צחקו, ואמרו לו שהמטרייה הזאת לא מתאימה אפילו לגשם, והוא שתק.', 'His friends laughed, and told him that this umbrella shames even the rain, and he was silent.'),
    ('הוא בא הביתה ואמר לה שהוא צריך מטרייה של איש, ושהוא לא ילד קטן.', 'He came home and said to her that he needs a man’s umbrella, and that he is not a small child.'),
    ('אחרי מלחמה של שבוע היא קנתה לו מטרייה טובה, ואמרה שהיא צריכה להחזיק חמש שנים.', 'After a week of war she bought him a good umbrella, and said that it must last five years.')),
  P(('אחרי חודש הוא חזר הביתה, והמטרייה הייתה בידו, ובבד היו כמה חורים קטנים ושרופים.', 'After a month he came home, and the umbrella was in his hand, and in the cloth were several small burned holes.'),
    ('היא הסתכלה, ולא אמרה מילה, ואז התחילה לצעוק כאילו נשרף כל הבית.', 'She looked, and did not say a word, and then began to shout as if the whole house had burned.'),
    ('הוא אמר: זה מהסיגר של מישהו במשרד, ואני לא עשיתי כלום, וזה קרה ליד הדלת.', 'He said: it is from someone’s cigar at the office, and I did nothing, and it happened beside the coat rack.'),
    ('היא אמרה: זאת מטרייה של שמונה עשרה, ואתה שורף אותה בחודש, ואני אשלם שוב?', 'She said: it is an umbrella of eighteen, and you burn it in a month, and I shall pay again?'),
    ('היא תפרה טלאים על החורים, ונתנה לו אותה בחזרה, והמטרייה נראתה כמו בגד של עני.', 'She sewed patches over the holes, and gave it back to him, and the umbrella looked like a poor man’s garment.')),
  P(('אחרי שבועיים הוא חזר עם המטרייה שרופה כמעט לגמרי, ורק המוטות נשארו שלמים.', 'After two weeks he came back with the umbrella burned almost entirely, and only the ribs remained whole.'),
    ('הפעם היא לא צעקה, והיא ישבה על הכיסא ובכתה, וזה היה נורא יותר מהצעקות.', 'This time she did not shout, and she sat on the chair and wept, and that was more terrible than the shouting.'),
    ('בלילה היא לא ישנה, וחשבה על הכסף, ובבוקר עלה בראש שלה רעיון.', 'At night she did not sleep, and thought about the money, and in the morning an idea came into her head.'),
    ('היא אמרה לעצמה: אנחנו משלמים כל שנה לחברת הביטוח, ומעולם לא ביקשנו מהם דבר.', 'She said to herself: we pay every year to the insurance company, and we have never asked them for anything.'),
    ('ואם הבית נשרף הם משלמים, ואם המטרייה נשרפת, למה שהם לא ישלמו גם עליה?', 'And if the house burns they pay, and if the umbrella burns, why should they not pay for it too?')),
  P(('היא לבשה את הבגד הטוב שלה, לקחה את המטרייה בנייר, ואז נסעה למשרדי החברה.', 'She put on her good dress, took the umbrella in paper, and travelled to the company’s offices.'),
    ('המנהל היה איש מנומס עם זקן, והוא הקשיב לה, ולא הבין מיד על מה מדובר.', 'The manager was a polite man with a beard, and he listened to her, and did not immediately understand what it was about.'),
    ('היא פרשה את המטרייה על השולחן שלו ואמרה: זאת שרפה, ואני מבוטחת נגד שרפות.', 'She spread the umbrella on his table and said: this is a fire, and I am insured against fires.'),
    ('הוא אמר: גברתי, אנחנו מדברים על בתים, והיא אמרה: אתם מדברים על שרפה, וזאת שרפה.', 'He said: madam, we speak about houses, and she said: you speak about fire, and this is fire.'),
    ('הם דיברו חצי שעה, והיא לא זזה, והוא הבין שהיא לא תצא מהחדר בלי כסף.', 'They spoke half an hour, and she did not move, and he understood that she would not leave the room without money.')),
  P(('בסוף הוא כתב פתק, ואמר לה: לכי לחנות, תקני בד חדש, ואת תביאי לי את החשבון.', 'In the end he wrote a note, and said to her: go to a shop, buy new cloth, and bring me the bill.'),
    ('היא ירדה במדרגות והלכה לחנות היקרה ביותר שהיא מכירה בכל הרובע.', 'She went down the stairs and walked to the most expensive shop that she knows in the whole quarter.'),
    ('היא בחרה משי, ושאלה כמה, ואמרה: זה בסדר, ולא הסתכלה במחיר פעם שנייה.', 'She chose silk, and asked how much, and said: that is fine, and did not look at the price a second time.'),
    ('בפעם הראשונה בחיים שלה היא קנתה את הדבר היקר, וזה היה יפה בעיניה.', 'For the first time in her life she bought the expensive thing, and it was beautiful in her eyes.'),
    ('כשהיא יצאה לרחוב עם המטרייה החדשה, ירד גשם קל, והיא לא פתחה אותה.', 'When she went out into the street with the new umbrella, a light rain fell, and she did not open it.'))]),
 ('The Piece of String', 'חתיכת החוט', [
  P(('ביום השוק כל הכפרים באים לעיירה, והכיכר מתמלאת אנשים ובהמות ועגלות וקולות.', 'On market day all the villages come to the town, and the square fills with people and animals and carts and voices.'),
    ('איכר זקן ממשי, קטן וכפוף, הלך בין הדוכנים לאט, כי הרגליים שלו כאבו.', 'An old peasant from the countryside, small and bent, walked among the stalls slowly, because his legs hurt.'),
    ('ואז הוא ראה על האדמה חתיכת חוט קטנה, והתכופף בקושי, והרים אותה.', 'And then he saw on the ground a small piece of string, and bent with difficulty, and picked it up.'),
    ('הוא היה איש זהיר בכסף, מהסוג שאוסף כל דבר שאפשר יהיה להשתמש בו יום אחד.', 'He was a man careful with money, of the sort that gathers everything that it will be possible to use one day.'),
    ('וכשהוא התיישר, הוא ראה שאיש עומד בפתח החנות ומסתכל עליו, ואת האיש הזה הוא שנא.', 'And when he straightened up, he saw that a man was standing in the shop doorway and looking at him, and this man he hated.')),
  P(('הם רבו פעם על עניין של סוס, וזה היה לפני שנים, והריב לא נגמר עד היום.', 'They once quarrelled over a matter of a horse, and that was years ago, and the quarrel has not ended to this day.'),
    ('האיכר נבוך שראו אותו מרים חוט מהרצפה, והחביא אותו מהר בתוך הבגד.', 'The peasant was embarrassed that he was seen picking up string from the ground, and quickly hid it inside his clothing.'),
    ('ואז הוא עשה כאילו הוא מחפש עוד משהו באדמה, ולא מצא, והמשיך ללכת.', 'And then he pretended that he was looking for something else on the ground, and did not find it, and went on walking.'),
    ('הוא הלך לאכול צהריים בפונדק, והמקום היה מלא, והכול דיברו על המחירים.', 'He went to eat lunch at the inn, and the place was full, and everyone spoke about the prices.')),
  P(('באמצע הארוחה נכנס איש מהעירייה ושאל אם מישהו מצא ארנק עור עם כסף בפנים.', 'In the middle of the meal a man from the town hall entered and asked whether anyone had found a leather wallet with money inside.'),
    ('הוא אמר: אבד ארנק בדרך, ובתוכו חמש מאות, וגם ניירות חשובים של בעליו.', 'He said: a wallet was lost on the road, and inside it five hundred, and also important papers of its owner.'),
    ('אחרי שעה בא שוטר וקרא לאיכר הזקן ואמר לו: ראש העיר רוצה לדבר איתך.', 'After an hour a policeman came and called the old peasant and said to him: the mayor wants to speak with you.'),
    ('הוא הלך בלי לדאוג, כי הוא לא עשה כלום, והוא לא הבין למה קוראים לו.', 'He went without worrying, because he had done nothing, and he did not understand why he was being called.')),
  P(('ראש העיר אמר לו: ראו אותך מרים את הארנק בכיכר, ואיש נאמן מעיד על זה.', 'The mayor said to him: you were seen picking up the wallet in the square, and a trustworthy man testifies to it.'),
    ('האיכר אמר: אני? ארנק? הרמתי חתיכת חוט, וזה הכול, והנה היא אצלי בכיס.', 'The peasant said: I? A wallet? I picked up a piece of string, and that is all, and here it is with me in my pocket.'),
    ('הוא הוציא את החוט והראה אותו, וראש העיר הסתכל בו ולא האמין לו.', 'He took out the string and showed it, and the mayor looked at it and did not believe him.'),
    ('הוא אמר: אתה מספר לי שאיש מרים חוט מהרצפה ומחביא אותו כמו גנב?', 'He said: you tell me that a man picks up string from the ground and hides it like a thief?'),
    ('הם חיפשו בכיסים שלו ולא מצאו כלום, ושלחו אותו הביתה, ואמרו שיבדקו.', 'They searched his pockets and found nothing, and sent him home, and said that they would check.')),
  P(('למחרת פועל אחד החזיר את הארנק, ואמר שהוא מצא אותו על הדרך והוא לא יודע לקרוא.', 'The next day a labourer returned the wallet, and said that he found it on the road and does not know how to read.'),
    ('האיכר שמע את זה ואז יצא לכיכר בשמחה, וסיפר את הסיפור לכל מי שעמד שם.', 'The peasant heard that and went out to the square in joy, and told the story to everyone who stood there.'),
    ('אבל האנשים הקשיבו וחייכו חיוך קטן, ואמרו: כן, כן, מצא אותו, ואתה סידרת את זה.', 'But the people listened and smiled a small smile, and said: yes, yes, he found it, and you arranged it.'),
    ('הוא חזר וסיפר שוב, ובכל פעם הסיפור נעשה ארוך יותר, וזה הזיק לו עוד יותר.', 'He told it again and again, and each time the story became longer, and that harmed him even more.')),
  P(('הוא הלך מבית לבית בכפר, ותפס אנשים ברחוב, והוציא את החוט מהכיס והראה.', 'He went from house to house in the village, and caught people in the street, and took the string out of his pocket and showed it.'),
    ('ככל שהוא הסביר יותר, כך האמינו לו פחות, כי איש ישר לא מסביר כל כך הרבה.', 'The more he explained, the less they believed him, because an honest man does not explain so much.'),
    ('הוא הפסיק לאכול, והוא כחש, והוא דיבר לעצמו בלילה על החוט ועל הארנק.', 'He stopped eating, and he grew thin, and he spoke to himself at night about the string and about the wallet.'),
    ('בחורף הוא נפל למיטה, ובימים האחרונים הוא חזר על אותה מילה שוב ושוב.', 'In the winter he fell into bed, and in the last days he repeated the same word again and again.'),
    ('הוא אמר: חתיכת חוט קטנה, אדוני, חתיכת חוט קטנה, ואז הוא מת.', 'He said: a small piece of string, sir, a small piece of string, and then he died.'))]),
 ('The Necklace', 'השרשרת', [
  P(('מאטילדה נולדה במשפחה של פקידים, והייתה יפה, וחשבה שזאת טעות של הגורל.', 'Mathilde was born into a family of clerks, and was beautiful, and thought that this was a mistake of fate.'),
    ('היא התחתנה עם פקיד קטן במשרד החינוך, איש טוב, שקט, שלא ביקש מהחיים הרבה.', 'She married a small clerk in the ministry of education, a good, quiet man, who did not ask much of life.'),
    ('היא הייתה יושבת בדירה הקטנה שלהם ומדמיינת חדרים גדולים עם וילונות כבדים.', 'She would sit in their small flat and imagine big rooms with heavy curtains.'),
    ('כשהמשרתת הביאה מרק לשולחן, בעלה אמר: אין דבר טוב מזה, והיא חשבה על ארמונות.', 'When the maid brought soup to the table, her husband said: there is nothing better than this, and she thought about palaces.')),
  P(('ערב אחד הוא בא הביתה שמח והביא מעטפה, ואמר: תפתחי, עבדתי על זה חודשיים.', 'One evening he came home happy and brought an envelope, and said: open it, I worked on this for two months.'),
    ('הייתה שם הזמנה לנשף במשרד, ושמות של אנשים גדולים, ותאריך בסוף החודש.', 'There was there an invitation to a ball at the ministry, and names of great people, and a date at the end of the month.'),
    ('היא זרקה את הנייר על השולחן ואמרה: ומה אני אלבש? אין לי שום דבר.', 'She threw the paper on the table and said: and what shall I wear? I have nothing at all.'),
    ('הוא חשב על הרובה שהוא רצה לקנות לקיץ, ואמר: ארבע מאות יספיקו לשמלה?', 'He thought about the gun that he wanted to buy for the summer, and said: will four hundred be enough for a dress?')),
  P(('השמלה נקנתה, ושלושה ימים לפני הנשף היא הייתה עצובה שוב, ולא רצתה לומר למה.', 'The dress was bought, and three days before the ball she was sad again, and did not want to say why.'),
    ('בסוף היא אמרה: אין לי תכשיט אחד, ואישה בלי תכשיט נראית כמו עניה.', 'In the end she said: I do not have one piece of jewellery, and a woman without jewellery looks like a poor woman.'),
    ('הוא אמר: לכי לחברה שלך פורסטייה, היא עשירה, ואת תבקשי ממנה משהו לערב אחד.', 'He said: go to your friend Forestier, she is rich, and ask her for something for one evening.'),
    ('היא הלכה, ופורסטייה פתחה לפניה קופסה גדולה, ואמרה: תבחרי מה שאת רוצה.', 'She went, and Forestier opened a big box before her, and said: choose what you want.'),
    ('היא בחרה שרשרת יהלומים, וסגרה אותה על הצוואר, והסתכלה במראה זמן רב.', 'She chose a diamond necklace, and closed it on her neck, and looked in the mirror a long time.')),
  P(('בנשף היא הייתה היפה בכל הנשים, וכל הגברים שאלו מי היא, וכולם רצו לרקוד איתה.', 'At the ball she was the most beautiful of all, and all the men asked who she is, and everyone wanted to dance with her.'),
    ('היא רקדה עד ארבע לפנות בוקר, ובעלה ישן בחדר צדדי על שלושה כיסאות.', 'She danced until four in the morning, and her husband slept in a side room on three chairs.'),
    ('בחוץ לא הייתה כרכרה, והם הלכו ברגל, והיא כיסתה את הכתפיים במעיל הישן.', 'Outside there was no carriage, and they walked on foot, and she covered her shoulders with the old coat.'),
    ('בבית היא עמדה מול המראה כדי לראות את עצמה עוד פעם אחת, וצעקה.', 'At home she stood in front of the mirror in order to see herself one more time, and screamed.'),
    ('השרשרת לא הייתה על הצוואר שלה, והם חיפשו בכל מקום, ולא מצאו אותה.', 'The necklace was not on her neck, and they searched everywhere, and did not find it.')),
  P(('הוא הלך ברחובות עד הבוקר, וחזר למשטרה, ולעיתונים, ולחברת העגלות.', 'He walked in the streets until morning, and went back to the police, and to the newspapers, and to the carriage company.'),
    ('אחרי שבוע הם מצאו בחנות שרשרת דומה בדיוק, במחיר של שלושים ושש אלף.', 'After a week they found in a shop a necklace exactly similar, at the price of thirty-six thousand.'),
    ('היה לו מהאב שלו שמונה עשר אלף, ואת השאר הוא לווה מכל מי שהסכים.', 'He had from his father eighteen thousand, and the rest he borrowed from everyone who agreed.'),
    ('הוא חתם על ניירות שהוא לא הבין, והבטיח דברים שאיש לא היה מבטיח.', 'He signed papers that he did not understand, and promised things that no one would promise.'),
    ('היא החזירה את הקופסה, ופורסטייה לקחה אותה ולא פתחה, ואמרה תודה בקור.', 'She returned the box, and Forestier took it and did not open it, and said thank you coldly.')),
  P(('ואז התחילו עשר שנים, והם עזבו את הדירה, ולקחו חדר קטן מתחת לגג.', 'And then ten years began, and they left the flat, and took a small room under the roof.'),
    ('היא שלחה את המשרתת, וכיבסה בעצמה, ואז ירדה כל בוקר עם דלי לחצר.', 'She sent the maid away, and did the washing herself, and went down every morning with a bucket to the yard.'),
    ('הוא עבד בערבים אצל סוחר, והעתיק דפים בלילה בחמישה לדף, עד מאוחר.', 'He worked in the evenings for a merchant, and copied pages at night at five a page, until late.'),
    ('אחרי עשר שנים הם שילמו הכול, וידיה היו אדומות, וקולה נעשה קול של אישה מהשוק.', 'After ten years they paid everything, and her hands were red, and her voice became the voice of a woman from the market.')),
  P(('יום ראשון אחד היא הלכה בשדרה, וראתה את פורסטייה עם ילד, עדיין צעירה ויפה.', 'One Sunday she walked on the avenue, and saw Forestier with a child, still young and beautiful.'),
    ('היא ניגשה ואמרה שלום, ופורסטייה לא הכירה אותה, והסתכלה בה בפליאה.', 'She approached and said hello, and Forestier did not know her, and looked at her in astonishment.'),
    ('היא אמרה: זאת אני, מאטילדה, ופורסטייה אמרה: אלוהים, מה קרה לך?', 'She said: it is I, Mathilde, and Forestier said: God, what happened to you?'),
    ('היא סיפרה הכול, את השרשרת, ואת החוב, ואת עשר השנים, וצחקה בסוף.', 'She told everything, the necklace, and the debt, and the ten years, and laughed at the end.'),
    ('פורסטייה אחזה בשתי ידיה ואמרה: אבל השרשרת שלי לא הייתה אמיתית, היא הייתה זכוכית.', 'Forestier held both her hands and said: but my necklace was not real, it was glass.'))]),
 ('My Uncle Jules', "הדוד ז'ול", [
  P(('גדלתי במשפחה שלא הייתה ענייה ולא הייתה עשירה, וזה המצב הקשה ביותר.', 'I grew up in a family that was not poor and was not rich, and that is the hardest condition.'),
    ('אבא עבד עד הערב, ואמא ספרה כל מטבע, ובבית לא היה אף פעם מספיק.', 'Father worked until evening, and mother counted every coin, and in the house there was never enough.'),
    ('הבגדים שלנו היו נקיים, ותוקנו שוב ושוב, כי לצאת לא מסודר היה אסון.', 'Our clothes were clean and sewn again and again, because to go out untidy was a disaster.'),
    ('ואם הזמינו אותנו לארוחה, אמא הייתה אומרת לנו לא לאכול הרבה ולא לבקש עוד.', 'And if we were invited to a meal, mother would tell us not to eat much and not to ask for more.')),
  P(("לאבא היה אח בשם ז'ול, שנסע לאמריקה כשהיה צעיר, אחרי שגמר את כל הכסף שלו.", 'Father had a brother named Jules, who travelled to America when he was young, after he finished all his money.'),
    ('במשפחה דיברו עליו כמו על אסון, ואמרו: הוא לקח את החלק שלנו ואכל אותו.', 'In the family they spoke about him as about a disaster, and said: he took our share and ate it.'),
    ('ואז הגיע ממנו מכתב, והוא כתב שהוא עובד, ושהוא בריא, ושהוא מבקש סליחה.', 'And then a letter came from him, and he wrote that he is working, and that he is healthy, and that he asks forgiveness.'),
    ('ואחרי שנתיים הגיע מכתב שני, והוא כתב שיש לו חנות, ושהעסק שלו הולך טוב.', 'And after two years a second letter came, and he wrote that he has a shop, and that his business is going well.'),
    ('הוא כתב שהוא יחזור עשיר, ושהוא ישלם הכול, ומאותו יום הוא נעשה תקוות הבית.', 'He wrote that he will return rich, and that he will pay everything, and from that day he became the hope of the house.')),
  P(('המכתב הזה נקרא בקול בכל פעם שבא אורח, ואבא היה מוציא אותו מהמגירה.', 'That letter was read aloud every time a guest came, and father would take it out of the drawer.'),
    ("כשדיברנו על העתיד, אמרו תמיד: כשז'ול יחזור, נקנה בית קטן ליד הים.", 'When we spoke about the future, they always said: when Jules returns, we shall buy a small house by the sea.'),
    ('לאחות הגדולה שלי לא היה חתן, כי לא היה כסף, וזה היה הכאב של אמא.', 'My older sister had no bridegroom, because there was no money, and that was mother’s pain.'),
    ('ואז בא בחור אחד, וראה את המכתב על השולחן, וקרא אותו, ובאותו שבוע ביקש את ידה.', 'And then a young man came, and saw the letter on the table, and read it, and that same week asked for her hand.')),
  P(('אחרי החתונה החליטו לנסוע לאי לטיול קטן, וזאת הייתה הנסיעה הראשונה שלנו בחיים.', 'After the wedding they decided to travel to the island for a small trip, and that was our first journey in our lives.'),
    ('על האונייה אבא הלך זקוף, ואמא לבשה את השמלה הטובה, וכולנו הרגשנו עשירים.', 'On the ship father walked upright, and mother wore the good dress, and all of us felt rich.'),
    ('שני אדונים על הסיפון קנו צדפים מאיש זקן, ואכלו אותן בעמידה, בנימוס גדול.', 'Two gentlemen on the deck bought oysters from an old man, and ate them standing, with great manners.'),
    ('אבא הסתכל בהם, ואמר: זה דבר מכובד, ושאל את אמא אם לקנות גם לנו.', 'Father looked at them, and said: that is a respectable thing, and asked mother whether to buy for us too.'),
    ('אמא אמרה בקול חמוץ: תקנה לבנות, אבל לא לילד, כי ילדים לא צריכים דברים כאלה.', 'Mother said in a sour voice: buy for the girls, but not for the boy, because children do not need such things.')),
  P(('אבא ניגש אל האיש הזקן שפתח את הצדפים, והסתכל בו, ועמד רגע בלי לדבר.', 'Father went up to the old man who was opening the oysters, and looked at him, and stood a moment without speaking.'),
    ('הוא חזר אלינו לבן כמו סדין, ואז ישב, ולחש לאמא: זה הוא, זה האח שלי.', 'He came back to us white as a sheet, and sat, and whispered to mother: it is he, it is my brother.'),
    ('אמא אמרה: אתה משוגע, ואז היא הלכה בעצמה להסתכל, וחזרה, וידיה רעדו.', 'Mother said: you are mad, and then she went herself to look, and came back, and her hands trembled.'),
    ('היא אמרה: אסור שהחתן יראה, ואסור שמישהו ידע, ואנחנו הולכים לצד השני.', 'She said: the bridegroom must not see, and no one must know, and we are going to the other side.')),
  P(('אבא שאל את הקברן של האונייה מי האיש, והתשובה הייתה: איש עני מצרפת, ירד מנכסיו.', 'Father asked the ship’s officer who the man is, and the answer was: a poor man from France, who came down in the world.'),
    ('אמא נתנה לי מטבע ואמרה: לך שלם על הצדפים, ואתה תחזור מיד, ואל תדבר איתו.', 'Mother gave me a coin and said: go pay for the oysters, and come back at once, and do not speak with him.'),
    ('הלכתי אליו וראיתי ידיים זקנות ולא נקיות, ופנים של איש זקן, ועיניים עייפות.', 'I went up to him and saw old, dirty hands, and a face with wrinkles, and tired eyes.'),
    ('אמרתי לו: כמה זה, אדוני? והוא אמר את המחיר, ואמר תודה, ולא הרים את הראש.', 'I said to him: how much is it, sir? And he said the price, and said thank you, and did not lift his head.'),
    ('נתתי לו את המטבע והוספתי משהו קטן משלי, והוא אמר: אלוהים יברך אותך, ילד.', 'I gave him the coin and added something small of my own, and he said: God bless you, boy.')),
  P(('חזרתי ואמא שאלה כמה שילמת, ואמרתי, והיא הסתכלה בי בחשד ולא אמרה כלום.', 'I came back and mother asked how much you paid, and I said, and she looked at me with suspicion and said nothing.'),
    ('בדרך חזרה קנינו כרטיסים לאונייה אחרת, כדי לא לעבור שוב באותו סיפון.', 'On the way back we bought tickets for another ship, in order not to pass again on that same deck.'),
    ('ומאותו יום לא דיברו בבית שלנו על הדוד, ולא הוציאו יותר את המכתב מהמגירה.', 'And from that day they did not speak in our house about the uncle, and did not take the letter out of the drawer any more.'),
    ('ואני, כשאני רואה איש עני מבקש מטבע ברחוב, אני נותן לו יותר ממה שצריך.', 'And I, when I see a poor man asking for a coin in the street, give him more than is needed.'))]),
 ('The Jewels', 'התכשיטים', [
  P(('הפקיד פגש אותה בערב אצל מכרים, והתחתן איתה אחרי חודשיים, והיה מאושר.', 'The clerk met her one evening at acquaintances’, and married her after two months, and was happy.'),
    ('היא ניהלה את הבית כמו שאיש לא ידע לנהל, וכל מטבע עשה אצלה עבודה כפולה.', 'She ran the house as no one knew how to run it, and every coin did double work with her.'),
    ('החברים שלו אמרו לו: אתה איש בר מזל, וזאת האישה הכי טובה בעיר הזאת.', 'His friends said to him: you are a lucky man, and this is the best wife in this city.'),
    ('היו לה רק שני דברים שהוא לא אהב: היא אהבה ללכת לתיאטרון, ואהבה תכשיטים.', 'She had only two things that he did not like: she loved to go to the theatre, and loved jewellery.')),
  P(('התכשיטים שלה היו זכוכית, כמובן, כי מאיפה יהיה להם כסף לדברים אמיתיים.', 'Her jewellery was glass, of course, because from where would they have money for real things.'),
    ('אבל היא הייתה יושבת בערב ופותחת את הקופסה ומסתכלת בהם באור המנורה.', 'But she would sit in the evening and open the box and look at them in the lamplight.'),
    ('היא הייתה שמה שרשרת על הצוואר וצוחקת ואומרת לו: תראה איך זה נראה אמיתי.', 'She would put a necklace on her neck and laugh and say to him: see how real it looks.'),
    ('הוא היה אומר: אישה שאין לה תכשיטים צריכה להיות יפה, ואת יפה, וזה מספיק.', 'He would say: a woman who has no jewellery needs beauty, and you have it, and that is enough.'),
    ('היא הייתה עונה: אני לא יכולה לשנות את עצמי, ואני אוהבת דברים שמבריקים.', 'She would answer: I cannot change myself, and I love things that shine.')),
  P(('ערב אחד היא חזרה מהתיאטרון בקור, ורעדה כל הלילה, ובבוקר עלה לה חום.', 'One evening she came back from the theatre in the cold, and trembled all night, and in the morning a fever rose in her.'),
    ('אחרי שבוע היא מתה, והוא לא הבין את זה, ולא בכה, ולא דיבר עם איש.', 'After a week she died, and he did not understand it, and did not weep, and did not speak with anyone.'),
    ('אחרי חודש התברר שהמשכורת שלו לבד לא מספיקה אפילו לשליש מהחודש.', 'After a month it became clear that his salary alone is not enough even for a third of the month.'),
    ('הוא ישב ערב אחד ולא היה לו כסף לארוחה, ואז נזכר בקופסת התכשיטים.', 'He sat one evening and had no money for a meal, and then remembered the box of jewellery.')),
  P(('הוא לקח את השרשרת הגדולה ואמר לעצמו: אולי ייתנו לי עליה כמה מטבעות.', 'He took the big necklace and said to himself: perhaps they will give me a few coins for it.'),
    ('הוא נכנס לחנות של צורף, והניח אותה על השולחן, ואמר: כמה זה שווה?', 'He entered a jeweller’s shop, and placed it on the table, and said: how much is this worth?'),
    ('הצורף הרים אותה, והסתכל בה, ואז הסתכל בפקיד, ואז יצא לחדר האחורי.', 'The jeweller lifted it, and looked at it, and then looked at the clerk, and then went out to the back room.'),
    ('הוא חזר ואמר: אני יכול לתת שתים עשרה אלף, ואם אתה מביא נייר, אפילו יותר.', 'He came back and said: I can give twelve thousand, and if you bring a paper, even more.'),
    ('הפקיד עמד עם הפה פתוח ואמר: אתה בטוח שזאת אותה שרשרת שהבאתי לכאן?', 'The clerk stood with his mouth open and said: are you sure that this is the same necklace that I brought here?')),
  P(('הוא יצא לרחוב והלך בלי לדעת לאן, וניסה לחשוב, ולא הצליח לחשוב.', 'He went out into the street and walked without knowing where, and tried to think, and did not manage to think.'),
    ('אם השרשרת אמיתית, מישהו קנה אותה, ואם מישהו קנה אותה, מי הוא היה.', 'If the necklace is real, someone bought it, and if someone bought it, who was he.'),
    ('הוא עמד ליד קיר ואמר לעצמו: לא, זאת מתנה מהמשפחה שלה, וזה בטח מה שהיה.', 'He leaned on a wall and said to himself: no, it is a gift from her family, and that is surely what it was.'),
    ('אבל למשפחה שלה לא היה כלום, וגם הוא ידע את זה, וההסבר לא החזיק.', 'But her family had nothing, and he too knew that, and the explanation did not hold.')),
  P(('בבוקר הוא חזר לחנות ומכר את השרשרת, ואז חזר הביתה והוציא את שאר הקופסה.', 'In the morning he came back to the shop and sold the necklace, and then went home and took out the rest of the box.'),
    ('בסוף השבוע התברר שהתכשיטים של אשתו שווים מאה תשעים ושישה אלף.', 'At the end of the week it became clear that his wife’s jewellery is worth a hundred and ninety-six thousand.'),
    ('הוא עזב את המשרד, וסיפר לכולם ברחוב שהוא קיבל ירושה מדוד רחוק.', 'He left the office, and told everyone in the street that he had received an inheritance from a distant uncle.'),
    ('הוא אכל במסעדות טובות, ולבש בגדים חדשים, ואז ישב בתיאטרון במקומות הקדמיים.', 'He ate in good restaurants, and wore new clothes, and sat in the theatre in the front places.'),
    ('אחרי חצי שנה הוא התחתן עם אישה ישרה מאוד, והיא עשתה לו חיים קשים מאוד.', 'After half a year he married a very honest woman, and she made his life very hard.'))]),
 ('Two Friends', 'שני חברים', [
  P(('בימי המצור בעיר לא היה אוכל, ולא היה עץ להסקה, והאנשים הלכו ברחובות לאט.', 'In the days of the siege in the city there was no food, and no wood for heating, and people walked in the streets slowly.'),
    ('מוריסו היה שען, ובימי שלום היה יוצא כל יום ראשון עם חכה אל הנהר.', 'Morissot was a watchmaker, and in days of peace he would go out every Sunday with a rod to the river.'),
    ('שם הוא היה פוגש איש קטן ושמן בשם סובאז, שמכר חוטים וכפתורים, ושאהב דגים בדיוק כמוהו.', 'There he would meet a small, fat man named Sauvage, who sold small wares, and loved fish exactly like him.'),
    ('הם היו יושבים על שפת המים שעות בלי לדבר, ובסוף היום היו נפרדים ולוחצים ידיים.', 'They would sit on the edge of the water for hours without speaking, and at the end of the day would part with a handshake.')),
  P(('בבוקר אחד של אביב הם נפגשו ברחוב ריק, והכירו זה את זה, ועמדו לדבר.', 'On one spring morning they met in an empty street, and recognised each other, and stood to talk.'),
    ('סובאז אמר: אתה זוכר את הנהר? ומוריסו אמר: אני חושב עליו כל יום.', 'Sauvage said: do you remember the river? And Morissot said: I think about it every day.'),
    ('הם נכנסו לשתות כוס יחד, ואחרי הכוס השנייה הרעיון כבר לא נשמע מטורף.', 'They went in to drink a glass together, and after the second glass the idea no longer sounded mad.'),
    ('סובאז אמר: הקווים בחוץ, אבל אנחנו מכירים את הדרך, ואף אחד לא ישים לב לשנינו.', 'Sauvage said: the lines are outside, but we know the way, and no one will notice the two of us.'),
    ('הם הלכו לקצין שהכיר את מוריסו, וביקשו נייר מעבר, והוא נתן להם וצחק.', 'They went to an officer who knew Morissot, and asked for a pass, and he gave it to them and laughed.')),
  P(('הם עברו את השדות הריקים, ובבתים בדרך לא היה איש, והדלתות היו פתוחות.', 'They passed the empty fields, and in the houses on the way there was no one, and the doors were open.'),
    ('הם ירדו אל המים, ואז ישבו בין השיחים, ופתחו את המקלות, וזרקו אותן פנימה.', 'They went down to the water, and sat among the bushes, and opened the rods, and threw them in.'),
    ('הדגים באו מהר, ותוך שעה הייתה להם סל קטן מלא, והשמש עלתה מעל הגבעה.', 'The fish came fast, and within an hour they had a small basket full, and the sun rose above the hill.'),
    ('הם דיברו על המלחמה בשקט, ואמרו זה לזה שהמנהיגים משחקים והאנשים משלמים.', 'They spoke about the war quietly, and said to each other that the leaders play and the people pay.'),
    ('ופתאום הרגישו רגליים מאחוריהם, והסתובבו, ועמדו שם חיילים עם רובים.', 'And suddenly they felt feet behind them, and turned around, and there stood soldiers with guns.')),
  P(('הקצין היה איש גדול, ודיבר צרפתית טובה, ואז ישב על כיסא שהביאו לו לשפת המים.', 'The officer was a big man, and spoke good French, and sat on a chair that they brought him to the water’s edge.'),
    ('הוא אמר: דייגים נחמדים, ובכיסים שלכם יש נייר מעבר, ולנייר הזה יש סיסמה.', 'He said: nice fishermen, and in your pockets there is a pass, and to that paper there is a password.'),
    ('הוא אמר: תגידו לי את הסיסמה של הקווים שלכם, ואתם הולכים הביתה עם הדגים.', 'He said: tell me the password of your lines, and you go home with the fish.'),
    ('שניהם לא ענו, ולא הסתכלו זה בזה, והביטו על המים שזרמו כמו תמיד.', 'Both of them did not answer, and did not look at each other, and gazed at the water that flowed as always.')),
  P(('הקצין אמר לסובאז: אתה נראה איש חכם, ואיש חכם חושב על המשפחה שלו.', 'The officer said to Sauvage: you look like a wise man, and a wise man thinks about his family.'),
    ('סובאז הסתכל בו והפנים שלו לא זזו, והוא לא פתח את הפה בכלל.', 'Sauvage looked at him and his face did not move, and he did not open his mouth at all.'),
    ('הוא אמר למוריסו: אתה מבוגר, ויש לך זמן להסתכל אחורה, ואני נותן לך דקה.', 'He said to Morissot: you are older, and you have time to look back, and I give you a minute.'),
    ('מוריסו לחש: שלום, סובאז, וסובאז לחש: שלום, מוריסו, ואז נגמרה הדקה.', 'Morissot whispered: goodbye, Sauvage, and Sauvage whispered: goodbye, Morissot, and then the minute ended.')),
  P(('אחרי הירי הקצין קם, ואמר לחיילים לקשור לכל אחד אבן ולהוריד אותם למים.', 'After the shooting the officer got up, and told the soldiers to tie a stone to each of them and lower them into the water.'),
    ('המים נסגרו מעליהם, ואחרי רגע הנהר נראה בדיוק כמו שהוא נראה בבוקר.', 'The water closed over them, and after a moment the river looked exactly as it looked in the morning.'),
    ('הקצין ראה את הסל, והרים אותו, והסתכל בדגים הקטנים שעוד זזו בפנים.', 'The officer saw the basket, and lifted it, and looked at the small fish that still moved inside.'),
    ('הוא קרא לחייל ואמר לו: תביא את זה למטבח, ושיטגנו לי אותם עכשיו, חמים.', 'He called a soldier and said to him: take this to the kitchen, and let them fry them for me now, hot.'),
    ('ואז הוא הדליק את המקטרת שלו, והסתכל על הנהר, ואז ישב בשמש עוד קצת.', 'And then he lit his pipe, and looked at the river, and sat in the sun a little longer.'))]),
 ('In the Fields', 'בשדות', [
  P(('שני בתים קטנים עמדו זה ליד זה על גבעה, ובשניהם היו ארבעה ילדים.', 'Two small houses stood one beside the other on a hill, and in both of them were four children.'),
    ('ההורים כמעט לא הבדילו בין הילדים, ובשעת האוכל כולם ישבו על אותו סף.', 'The parents almost did not distinguish between the children, and at mealtime all of them sat on the same threshold.'),
    ('הקטנים התגלגלו באדמה מהבוקר עד הערב, ולא היה להם צעצוע אחד בעולם.', 'The little ones rolled in the earth from morning until evening, and they did not have one toy in the world.'),
    ('הגדולים אכלו מהר, כי מי שגומר ראשון יכול לבקש עוד לפני שהסיר מתרוקן.', 'The big ones ate fast, because whoever finishes first can ask for more before the pot empties.')),
  P(('קיץ אחד התחילה לעבור בדרך כרכרה יפה, לאט, ובתוכה גברת עם כובע לבן.', 'One summer a fine carriage began to pass on the road, slowly, and inside it a lady with a white hat.'),
    ('היא הייתה עוצרת ליד הבתים ומסתכלת על הילדים, ולפעמים נותנת להם ממתק.', 'She would stop beside the houses and look at the children, and sometimes give them a sweet.'),
    ('פעם היא ירדה מהכרכרה, והרימה את הקטן ביותר, ונשקה לו על הפנים שאינן נקיות.', 'Once she got down from the carriage, and lifted the smallest, and kissed him on his dirty face.'),
    ('אנשי הכפר צחקו ואמרו: לעשירים אין מה לעשות, אז הם אוהבים ילדים של אחרים.', 'The village people laughed and said: the rich have nothing to do, so they love other people’s children.')),
  P(('יום אחד הכרכרה עצרה, והגברת ובעלה ירדו, ואז נכנסו לבית הראשון, ודיברו.', 'One day the carriage stopped, and the lady and her husband got down, and entered the first house, and spoke.'),
    ('הגברת אמרה: אין לנו ילדים, ואנחנו רוצים לגדל את הקטן שלכם כמו בן.', 'The lady said: we have no children, and we want to raise your little one like a son.'),
    ('היא אמרה: הוא ילמד, והוא יירש הכול, ואנחנו נשלם לכם כל חודש עד הסוף.', 'She said: he will study, and he will inherit everything, and we shall pay you every month until the end.'),
    ('האם עמדה, והפנים שלה נעשו אדומות, והיא הרימה מטאטא וצעקה שיצאו מהבית.', 'The mother stood, and her face became red, and she raised a broom and shouted that they should get out of the house.'),
    ('היא צעקה: למכור ילד? תשאלו את השכנים, אולי שם מוכרים, אצלנו לא מוכרים.', 'She shouted: to sell a child? Ask the neighbours, maybe there they sell, with us they do not sell.')),
  P(('הזוג יצא, והלך אל הבית השני, ושם ישבו וסיפרו את אותו דבר בדיוק.', 'The couple went out, and walked to the second house, and there they sat and told exactly the same thing.'),
    ('האב והאם הסתכלו זה בזה, ולא ענו מיד, ושאלו כמה בדיוק כל חודש.', 'The father and mother looked at each other, and did not answer at once, and asked how much exactly every month.'),
    ('הגברת אמרה מספר, והם ביקשו יותר, והיא הוסיפה, והם ביקשו עוד קצת.', 'The lady said a number, and they asked for more, and she added, and they asked for a little more.'),
    ('בסוף האם אמרה: אם זה בשבילו, ואם הוא יהיה אדון, אנחנו מסכימים.', 'In the end the mother said: if it is for him, and if he will be a gentleman, we agree.'),
    ('הילד יצא בזרועות של הגברת, ובכה, כי הוא לא הכיר אותה ורצה הביתה.', 'The child went out in the lady’s arms, and wept, because he did not know her and wanted to go home.')),
  P(('השכנים דיברו על זה שנים, והאם הראשונה הייתה אומרת בכל הזדמנות: אני לא מכרתי.', 'The neighbours spoke about it for years, and the first mother would say at every opportunity: I did not sell.'),
    ('היא הייתה עומדת בפתח וקוראת בקול: יש אמהות שמוכרות, ויש אמהות שלא.', 'She would stand in the doorway and call out loudly: there are mothers who sell, and there are mothers who do not.'),
    ('והבן שלה, שנשאר, גדל ועבד בשדה, ולא למד לקרוא, וידיו נעשו קשות.', 'And her son, who stayed, grew up and worked in the field, and did not learn to read, and his hands became hard.'),
    ('הוא היה שומע את זה כל חייו, ובכל פעם הוא היה שותק והולך הצידה.', 'He would hear that all his life, and every time he would be silent and go aside.')),
  P(('אחרי עשרים ואחת שנים עצרה מול הבתים כרכרה, וירד ממנה אדון צעיר ויפה.', 'After twenty-one years a carriage stopped in front of the houses, and a young, handsome gentleman got down from it.'),
    ('הוא נכנס לבית השני, וחיבק את ההורים שלו, וכולם בכו, וכל הכפר בא לראות.', 'He entered the second house, and embraced his parents, and everyone wept, and the whole village came to see.'),
    ('הבן של הבית הראשון עמד בחוץ והסתכל, וידיו היו שחורות מהעבודה בשדה.', 'The son of the first house stood outside and looked, and his hands were black from the work in the field.'),
    ('בערב הוא נכנס הביתה ואמר לאמו: אז זה מה שיכולתי להיות, ואת לא נתת.', 'In the evening he entered the house and said to his mother: so that is what I could have been, and you did not allow it.'),
    ('הוא לקח את הכובע שלו ואז יצא, והם קראו לו בדרך, והוא לא הסתובב.', 'He took his hat and went out, and they called to him on the road, and he did not turn around.'))]),
 ('The Beggar', 'הקבצן', [
  P(('הוא היה בן של איש כפר, ובגיל חמש עשרה עגלה עברה עליו ושברה לו את הרגליים.', 'He was the son of a village man, and at the age of fifteen a cart passed over him and broke his legs.'),
    ('מאז הוא ישב על הדרך, בין שני מקלות, וביקש מטבע מכל מי שעבר.', 'From then he sat on the road, between two sticks, and asked a coin from everyone who passed.'),
    ('בהתחלה נתנו לו, כי זכרו את האבא שלו, וכי הסיפור עוד היה חדש.', 'At first they gave to him, because they remembered his father, and because the story was still new.'),
    ('אבל עברו שנים, והוא נעשה חלק מהנוף, ואיש כבר לא ראה אותו כשעבר.', 'But years passed, and he became part of the scenery, and no one saw him any more when passing.')),
  P(('הוא ידע ללכת ארבעה כפרים, ובכל כפר היה בית אחד שנתן לו לחם.', 'He knew how to walk four villages, and in every village there was one house that gave him bread.'),
    ('הוא היה יוצא בבוקר ומגיע לכפר הרחוק בערב, וישן בגורן או מתחת לעץ.', 'He would go out in the morning and reach the far village in the evening, and sleep in a barn or under a tree.'),
    ('הנשים היו אומרות לו: אתמול נתתי, ואי אפשר כל יום, ולך למקום אחר.', 'The women would say to him: yesterday I gave, and it is not possible every day, and go somewhere else.'),
    ('הילדים היו הולכים אחריו וזורקים עליו אבנים קטנות וקוראים לו שמות רעים.', 'The children would walk after him and throw small stones at him and call him a name of scorn.')),
  P(('בחורף אחד קשה ירד שלג שלושה ימים, והדרכים היו ריקות, והבתים סגורים.', 'In one hard winter snow fell for three days, and the roads were empty, and the houses closed.'),
    ('הוא הלך מבית לבית ולא קיבל כלום, ובערב השלישי הוא לא אכל שני ימים.', 'He went from house to house and received nothing, and on the third evening he had not eaten for two days.'),
    ('הוא ישב על אבן ליד גדר, ולא היה לו כוח לקום, והידיים שלו לא הרגישו.', 'He sat on a stone beside a fence, and he had no strength to get up, and his hands did not feel.'),
    ('ואז הוא ראה תרנגולות שהלכו בחצר של בית, ואיש לא היה בחוץ.', 'And then he saw hens that were walking in the yard of a house, and no one was outside.')),
  P(('הוא זרק אבן ופגע, והתרנגולת נפלה, והוא זחל אליה והכניס אותה תחת הבגד.', 'He threw a stone and hit, and the hen fell, and he crawled to it and put it under his clothing.'),
    ('הוא הגיע לשיחים בקצה הכפר, והתחיל לעשות אש קטנה בין שתי אבנים.', 'He reached the bushes at the edge of the village, and began to make a small fire between two stones.'),
    ('ואז באו שני אנשים, ולקחו אותו, וקראו לשוטר, והשוטר לקח אותו לעיירה.', 'And then two men came, and took him, and called the policeman, and the policeman took him to the town.'),
    ('הם הכניסו אותו לחדר קטן עם דלת ברזל, ואמרו שהשופט יבוא ביום שני.', 'They put him in a small room with an iron door, and said that the judge will come on Monday.')),
  P(('בחדר היה קר, והוא ישב על הרצפה, והרגליים שלו כאבו יותר מתמיד.', 'In the room it was cold, and he sat on the floor, and his legs hurt more than ever.'),
    ('בבוקר בא השומר והביא לחם, והוא לא לקח, כי הוא כבר לא הצליח לבלוע.', 'In the morning the guard came and brought bread, and he did not take it, because he could no longer swallow.'),
    ('בבוקר השני השומר פתח את הדלת, וקרא לו, והוא לא ענה, והוא לא זז.', 'On the second morning the guard opened the door, and called him, and he did not answer, and he did not move.'),
    ('השומר יצא וקרא לאנשים, ואמר: הוא מת, והם עמדו בפתח והסתכלו פנימה.', 'The guard went out and called people, and said: he is dead, and they stood in the doorway and looked inside.'),
    ('אחד מהם אמר: אז בשביל מה הוא גנב תרנגולת? ואיש לא ידע מה לענות.', 'One of them said: so what did he steal a hen for? And no one knew what to answer.'))]),
 ('Mother Sauvage', 'האם מהכפר', [
  P(('בכפר קטן בין היערות גרה אישה זקנה לבד בבית אבן עם גג נמוך.', 'In a small village among the forests an old woman lived alone in a stone house with a low roof.'),
    ('בעלה מת לפני שנים, והבן שלה, בן שלושים ושלוש, יצא לצבא בתחילת המלחמה.', 'Her husband died years ago, and her son, thirty-three years old, went out to the army at the start of the war.'),
    ('היא נשארה עם עז אחת וגן קטן, וכל בוקר היא עבדה בו לפני האור.', 'She remained with one goat and a small garden, and every morning she worked in it before the light.'),
    ('כשהצבא הזר נכנס לכפר, שמו אצלה בבית ארבעה חיילים צעירים, כי היה לה מקום.', 'When the foreign army entered the village, they put in her house four young soldiers, because she had room.')),
  P(('הם היו בחורים גדולים וכבדים, והם קמו מוקדם, וניקו את הבית, ועזרו לה.', 'They were big, heavy lads, and they got up early, and cleaned the house, and helped her.'),
    ('אחד מהם היה קולף תפוחי אדמה, ואחד היה מביא מים, ואחד היה חותך עצים.', 'One of them would peel potatoes, and one would bring water, and one would cut wood.'),
    ('הם לא ידעו את השפה שלה, והיא לא ידעה את שלהם, אבל הם הסתדרו בידיים.', 'They did not know her language, and she did not know theirs, but they managed with their hands.'),
    ('בערב הם היו יושבים סביב האש, והיא הייתה יושבת לידם, ומסתכלת בהם.', 'In the evening they would sit around the fire, and she would sit opposite them, and look at them.'),
    ('היא חשבה לעצמה: גם להם יש אמא איפשהו, וגם היא מחכה למכתב כמוני.', 'She thought to herself: they too have a mother somewhere, and she too waits for a letter like me.')),
  P(('יום אחד בא איש מהעיירה והביא לה נייר, והיא לא ידעה לקרוא, וביקשה עזרה.', 'One day a man came from the town and brought her a paper, and she did not know how to read, and asked for help.'),
    ('בנייר היה כתוב שהבן שלה נהרג בקרב, ושכדור פגע בו, ושהוא לא סבל.', 'In the paper it was written that her son was killed in battle, and that a bullet struck him, and that he did not suffer.'),
    ('הכותב הוסיף שהוא היה חבר טוב, ושכולם אהבו אותו, ושהוא נקבר יפה.', 'The writer added that he was a good friend, and that everyone loved him, and that he was buried well.'),
    ('היא לא צעקה, ולא בכתה, והיא לקחה את הנייר וקיפלה אותו והכניסה לכיס.', 'She did not scream, and did not weep, and she took the paper and folded it and put it in her pocket.'),
    ('היא ישבה כל היום מול החלון, והחיילים חזרו בערב, ואכלו, ולא הבינו כלום.', 'She sat all day in front of the window, and the soldiers came back in the evening, and ate, and understood nothing.')),
  P(('בבוקר היא ביקשה מהם בסימנים להביא הרבה קש, כי היא רוצה למלא את המיטות.', 'In the morning she asked them by signs to bring a lot of straw, because she wants to fill the beds.'),
    ('הם עבדו כל היום בשמחה, והביאו קש עד התקרה, ומילאו את החדר העליון.', 'They worked all day happily, and brought straw up to the ceiling, and filled the upper room.'),
    ('בערב היא הכינה להם אוכל טוב, ואמרה בסימנים שהם צריכים לישון למעלה.', 'In the evening she prepared good food for them, and said by signs that they should sleep upstairs.'),
    ('כשהם עלו וכיבו את הנר, היא חיכתה שעה, ואז יצאה החוצה בשקט.', 'When they went up and put out the candle, she waited an hour, and then went outside quietly.')),
  P(('היא סגרה את הדלת מבחוץ במוט ברזל, והביאה קש יבש, ושמה אותו לאורך הקיר.', 'She closed the door from outside with an iron bar, and brought dry straw, and put it along the wall.'),
    ('היא הדליקה אותו, ועמדה מול הבית שלה, והאש עלתה מהר מאוד בגלל הקש.', 'She lit it, and stood in front of her house, and the fire rose very fast because of the straw.'),
    ('היא שמעה קולות מלמעלה, ואז שמעה ירי בפנים, ואז לא שמעה יותר כלום.', 'She heard voices from above, and then heard shooting inside, and then heard nothing more.'),
    ('היא ישבה על האבן בחוץ עד הבוקר, והסתכלה בבית שלה נשרף עד הסוף.', 'She sat on the stone outside until morning, and looked at her house burning to the end.')),
  P(('בבוקר באו הקצינים, ומצאו אותה יושבת שם, שקטה, עם הידיים על הברכיים.', 'In the morning the officers came, and found her sitting there, quiet, with her hands on her knees.'),
    ('הם שאלו מי עשה את זה, והיא אמרה: אני, ואז הוציאה את הנייר מהכיס.', 'They asked who did this, and she said: I, and then took the paper out of her pocket.'),
    ('היא ביקשה שיכתבו את השמות של הארבעה, כדי שהיא תשלח אותם למשפחות שלהם.', 'She asked that they write down the names of the four, so that she may send them to their families.'),
    ('היא אמרה: תגידו לאמהות שלהם שאני עשיתי את זה, וששמי כתוב כאן על הנייר.', 'She said: tell their mothers that I did it, and that my name is written here on the paper.'),
    ('הם העמידו אותה מול הקיר, והיא לא ביקשה כלום, והחזיקה את הנייר ביד.', 'They stood her against the wall, and she asked for nothing, and held the paper in her hand.'))]),
 ('The Death of a Clerk', 'המוות של הפקיד', [
  P(('בערב יפה אחד ישב פקיד קטן בתיאטרון, במקום טוב, והרגיש את עצמו מאושר.', 'On one fine evening a small clerk sat in the theatre, in a good place, and felt himself happy.'),
    ('הוא הסתכל בבמה דרך משקפת קטנה, וחשב שאין בעולם דבר טוב יותר מזה.', 'He looked at the stage through a small opera glass, and thought that there is nothing better in the world than this.'),
    ('ואז פתאום הפנים שלו התכווצו, והעיניים נסגרו, והוא התעטש בקול גדול.', 'And then suddenly his face contracted, and his eyes closed, and he sneezed loudly.'),
    ('להתעטש זה לא אסור, ואיכרים מתעטשים, ושרים מתעטשים, וכולם מתעטשים לפעמים.', 'To sneeze is not forbidden, and peasants sneeze, and ministers sneeze, and everyone sneezes sometimes.'),
    ('הוא לא נבהל בכלל, וניגב את הפנים במטפחת, והסתכל סביבו לראות אם הפריע.', 'He was not alarmed at all, and wiped his face with a handkerchief, and looked around to see whether he had disturbed anyone.')),
  P(('לפניו ישב איש מבוגר עם ראש קירח, שניגב את הצוואר שלו בכפפה, ומלמל משהו.', 'In front of him sat an older man with a bald head, who wiped his neck with a glove, and muttered something.'),
    ('הפקיד הכיר אותו מיד, וזה היה פקיד בכיר מאוד ממשרד אחר, איש חשוב.', 'The clerk knew him at once, and this was a very senior official from another ministry, an important man.'),
    ('הוא חשב: התעטשתי עליו, והוא לא המנהל שלי, אבל בכל זאת לא יפה.', 'He thought: I sneezed on him, and he is not my chief, but nevertheless it is not nice.'),
    ('הוא התכופף קדימה ואמר בשקט: סלח לי, אדוני, זה יצא לי בלי כוונה בכלל.', 'He leaned forward and said quietly: forgive me, sir, it came out of me without any intention at all.'),
    ('האיש אמר: זה בסדר, זה בסדר, והמשיך להסתכל על הבמה בלי להסתובב.', 'The man said: it is all right, it is all right, and continued to look at the stage without turning around.')),
  P(('הפקיד ישב, אבל הוא כבר לא ראה את הבמה, כי המילים לא נשמעו לו טובות.', 'The clerk sat, but he no longer saw the stage, because the words did not sound good to him.'),
    ('הוא חשב: הוא אמר זה בסדר, אבל הוא לא הסתובב, וזה סימן שהוא כועס.', 'He thought: he said it is all right, but he did not turn around, and that is a sign that he is angry.'),
    ('בהפסקה הוא ניגש אליו שוב ואמר: אדוני, אני מבקש שתבין שזה היה בטעות.', 'In the interval he approached him again and said: sir, I ask that you understand that it was by accident.'),
    ('האיש אמר: כבר שכחתי, ואתה מדבר על זה, והפקיד חשב שהוא ענה בקוצר רוח.', 'The man said: I have already forgotten, and you keep speaking about it, and the clerk thought that he answered impatiently.')),
  P(('בבית הוא סיפר לאשתו הכול, והיא אמרה: לך אליו מחר למשרד ואתה תסביר יפה.', 'At home he told his wife everything, and she said: go to him tomorrow at the office and explain nicely.'),
    ('בבוקר הוא לבש בגד חדש, והסתפר, והלך למשרד של האיש, וחיכה בתור.', 'In the morning he put on a new suit, and had a haircut, and went to the man’s office, and waited in the queue.'),
    ('כשהגיע תורו הוא נכנס ואמר: אתמול בתיאטרון, אם אדוני זוכר, אני התעטשתי.', 'When his turn came he entered and said: yesterday at the theatre, if sir remembers, I sneezed.'),
    ('האיש הרים את היד ואמר: מספיק, אני עסוק, לך, והוא הסתכל בניירות.', 'The man raised his hand and said: enough, I am busy, go, and he looked at the papers.')),
  P(('הפקיד יצא לרחוב ולא הבין איך יצא, ורגליו הלכו לבד, והוא הזיע.', 'The clerk went out into the street and did not understand how he got out, and his legs walked by themselves, and he sweated.'),
    ('הוא חשב: הוא אמר לך, וזאת מילה קשה, ואולי הוא כבר כתב עליי משהו.', 'He thought: he said go, and that is a hard word, and perhaps he has already written something about me.'),
    ('למחרת הוא הלך שוב, ואז נכנס, והאיש הסתכל בו והפנים שלו נעשו אדומות.', 'The next day he went again, and entered, and the man looked at him and his face became red.'),
    ('האיש צעק: אתה צוחק ממני? צא מכאן! והפקיד יצא, ולא הרגיש את הרגליים.', 'The man shouted: are you laughing at me? Get out of here! And the clerk went out, and did not feel his legs.')),
  P(('הוא הלך הביתה ברחובות ולא ראה איש, והמילה האחרונה חזרה לו בראש.', 'He walked home in the streets and did not see anyone, and the last word came back to him in his head.'),
    ('הוא הגיע הביתה, ולא הוריד את הבגד, ושכב על הספה עם הפנים לקיר.', 'He arrived home, and did not take off his coat, and lay on the sofa with his face to the wall.'),
    ('אשתו קראה לו לארוחה, והוא לא ענה, והיא חשבה שהוא נרדם והלכה.', 'His wife called him to the meal, and he did not answer, and she thought that he had fallen asleep and went away.'),
    ('ואז הוא מת, וזה נשמע דבר קטן, ובכל זאת זה בדיוק מה שהיה לו.', 'And then he died, and that sounds like a small thing, and nevertheless that is exactly what befell him.'))]),
 ('The Chameleon', 'איש שמשנה צבע', [
  P(('השוטר עבר בכיכר השוק עם מעיל חדש, ואחריו הלך שוטר צעיר עם סל של דובדבנים.', 'The policeman passed through the market square with a new coat, and behind him walked a young policeman with a basket of cherries.'),
    ('השוק היה ריק באותה שעה, והחנויות עמדו פתוחות ומשעממות מול השמש.', 'The market was empty at that hour, and the shops stood open and dull in front of the sun.'),
    ('ואז נשמעה צעקה מהחצר של מחסן העצים, וקול של כלב שצועק מכאב.', 'And then a shout was heard from the yard of the wood store, and the sound of a dog crying from pain.'),
    ('אנשים רצו לשם מכל הצדדים, כאילו הם עמדו וחיכו לזה כל הבוקר.', 'People ran there from all sides, as if they had been standing and waiting for it all morning.')),
  P(('באמצע החצר עמד צורף עם אצבע באוויר, ודם על היד, וכולם הסתכלו עליה.', 'In the middle of the yard a goldsmith stood with a raised finger, and blood on the hand, and everyone looked at it.'),
    ('לידו עמד כלב לבן וקטן, עם פנים חדות, ורעד, וניסה להיכנס בין הרגליים.', 'Beside him stood a small white dog, with a sharp face, and trembled, and tried to get in between the legs.'),
    ('הצורף צעק: תראו מה עשו לי! אני עובד באצבעות, ועכשיו אני לא יכול לעבוד.', 'The goldsmith shouted: see what they have done to me! I work with my fingers, and now I cannot work.'),
    ('השוטר אמר: מי הבעלים של הכלב? זה לא ייגמר כאן, ואני אכתוב על זה דוח.', 'The policeman said: who is the owner of the dog? This will not end here, and I shall write a report about it.')),
  P(('הוא אמר: כלב משוטט בעיר, וזה אסור, ואני אקח קנס מהאיש שלא שומר עליו.', 'He said: a dog wandering in the city, and that is forbidden, and I shall take a fine from the man who does not guard it.'),
    ('מישהו מהקהל אמר בשקט: אני חושב שזה הכלב של אחי הגנרל, הוא הגיע אתמול.', 'Someone from the crowd said quietly: I think that it is the dog of the general’s brother, he arrived yesterday.'),
    ('השוטר הוריד את הקול ואמר: חם היום, נכון? תוריד לי את המעיל בבקשה.', 'The policeman lowered his voice and said: it is hot today, is it not? Take my coat off me please.'),
    ('הוא אמר לצורף: ואיך כלב קטן כזה מגיע לאצבע שלך, אם אתה לא מתכופף?', 'He said to the goldsmith: and how does such a small dog reach your finger, if you do not bend down?'),
    ('הוא אמר: אולי דקרת את האצבע במסמר, ואז חשבת על תרגיל קטן, אני מכיר אתכם.', 'He said: perhaps you pricked your finger on a nail, and then thought of a little trick, I know your kind.')),
  P(('אדם אחר מהקהל אמר: לא, זה לא הכלב שלו, לגנרל אין כלבים כאלה בכלל.', 'Another man from the crowd said: no, it is not his dog, the general does not have such dogs at all.'),
    ('השוטר אמר: נכון מאוד, וזה כלב רחוב, ולמה אנחנו בכלל עומדים כאן ומדברים.', 'The policeman said: quite right, and it is a street dog, and why are we standing here and talking at all.'),
    ('הוא אמר: הכלב הזה חולה, ואתם תראו את הפנים שלו, ואני אומר להרוג אותו היום.', 'He said: this dog is sick, and look at its face, and I say to kill it today.'),
    ('הצורף אמר: יפה מאוד, אדוני, וזה בדיוק מה שצריך לעשות עם חיה כזאת.', 'The goldsmith said: very fine, sir, and that is exactly what should be done with such an animal.')),
  P(('ואז עבר בחצר הטבח של הגנרל, והשוטר קרא לו ושאל אם הוא מכיר את הכלב.', 'And then the general’s cook passed through the yard, and the policeman called him and asked whether he knows the dog.'),
    ('הטבח הסתכל ואמר: אצלנו אין כלב כזה, ואף פעם לא היה לנו כלב לבן.', 'The cook looked and said: with us there is no such dog, and we never had a white dog.'),
    ('השוטר אמר: אז גמרנו, וזה כלב רחוב, ואל תעמדו כאן, ולכו לעבודה.', 'The policeman said: then we are finished, and it is a street dog, and do not stand here, and go to work.'),
    ('הטבח הוסיף: אבל זה הכלב של האח של הגנרל, שהגיע אלינו אתמול בערב.', 'The cook added: but it is the dog of the general’s brother, who arrived with us yesterday evening.')),
  P(('השוטר צחק ואמר: כלב יפה, איזה כלב חכם, תראו איך הוא מסתכל עלינו.', 'The policeman laughed and said: a fine dog, what a clever dog, see how it looks at us.'),
    ('הוא אמר לטבח: קח אותו, ואתה תשמור עליו, ואתה תגיד שלא יוציאו אותו לבד.', 'He said to the cook: take it, and guard it, and say that they should not let it out alone.'),
    ('הוא הסתובב אל הצורף ואמר: ואתה, אני עוד אגיע אליך, ואתה יודע למה.', 'He turned to the goldsmith and said: and you, I shall still get to you, and you know why.'),
    ('הוא לבש את המעיל, ואז יישר אותו, והמשיך ללכת בכיכר כאילו לא קרה כלום.', 'He put on the coat, and straightened it, and continued to walk in the square as if nothing had happened.'),
    ('הצורף עמד עם האצבע ביד, והקהל התפזר, וכולם צחקו ממנו בדרך.', 'The goldsmith stood with the finger in his hand, and the crowd scattered, and everyone laughed at him on the way.'))]),
 ('Fat and Thin', 'השמן והרזה', [
  P(('בתחנת הרכבת נפגשו שני אנשים שלא ראו זה את זה שלושים שנה ויותר.', 'At the railway station two men met who had not seen each other for thirty years and more.'),
    ('האחד היה שמן ורגוע, ואז יצא מהמסעדה של התחנה, וריח של יין טוב עלה ממנו.', 'The one was fat and calm, and came out of the station restaurant, and a smell of good wine rose from him.'),
    ('השני היה רזה, ועמד עם מזוודות וקופסאות, ואשתו וילדו עמדו לידו.', 'The other was thin, and stood with suitcases and boxes, and his wife and his child stood beside him.'),
    ('הם הסתכלו זה בזה רגע, ואז שניהם צעקו יחד, וחיבקו, ונשקו פעמיים.', 'They looked at each other a moment, and then both of them shouted together, and embraced, and kissed twice.')),
  P(('הרזה אמר: אני לא מאמין! כמה שנים עברו! ואתה בדיוק כמו שהיית.', 'The thin one said: I do not believe it! How many years have passed! And you are exactly as you were.'),
    ('השמן אמר: ואתה? מה איתך? ספר לי הכול, ואל תשכח שום דבר.', 'The fat one said: and you? What about you? Tell me everything, and do not forget anything.'),
    ('הרזה אמר: זאת אשתי, וזה הבן שלי, והוא לומד בבית הספר, והוא תלמיד טוב.', 'The thin one said: this is my wife, and this is my son, and he studies at school, and he is a good pupil.'),
    ('הוא אמר: אני עובד במשרד כבר שנים, והמשכורת קטנה, אבל אשתי נותנת שיעורים.', 'He said: I have been working in an office for years, and the salary is small, but my wife gives lessons.'),
    ('הוא אמר: ואני עושה קופסאות סיגריות בבית ומוכר אותן, וזה מוסיף קצת.', 'He said: and I make cigarette boxes at home and sell them, and that adds a little.')),
  P(('הוא צחק ואמר: ואתה זוכר איך קראנו לך בבית הספר בגלל המצחיה שלך?', 'He laughed and said: and do you remember what we called you at school because of your cap?'),
    ('הוא אמר: ואיך שרפת פעם ספר של המורה, וכולנו עמדנו בחוץ בקור?', 'He said: and how you once burned the teacher’s book, and all of us stood outside in the cold?'),
    ('השמן צחק גם הוא, ואמר: היו ימים טובים, וטוב שנפגשנו כאן בדיוק.', 'The fat one laughed too, and said: those were good days, and it is good that we met here of all places.'),
    ('הרזה אמר: ואתה? איפה אתה עובד עכשיו? הגעת רחוק, אני רואה עליך.', 'The thin one said: and you? Where do you work now? You have got far, I see it on you.')),
  P(('השמן אמר: אני במשרד הכספים, ולפני שנתיים קיבלתי דרגה, ויש לי כוכב.', 'The fat one said: I am at the ministry of finance, and two years ago I received a rank, and I have a star.'),
    ('הוא אמר את זה בפשטות, כמו שאומרים על מזג האוויר, והמשיך לחייך.', 'He said it simply, as one speaks about the weather, and continued to smile.'),
    ('הרזה עמד רגע ולא זז, והפנים שלו השתנו, והוא נעשה קטן יותר בעיניים.', 'The thin one stood a moment and did not move, and his face changed, and he became smaller in the eyes.'),
    ('ואז הוא התכופף קצת, וידיו היו קרובות לגוף, וכל הקופסאות נראו כבדות פתאום.', 'And then he bent a little, and his hands pressed to his body, and all the boxes looked heavy suddenly.')),
  P(('הוא אמר: אדוני הנכבד, אני שמח מאוד, וזה כבוד גדול בשבילי לפגוש אותך.', 'He said: my honoured sir, I am very glad, and it is a great honour for me to meet you.'),
    ('השמן אמר: מה אתה עושה? אנחנו חברים מהילדות, ולמה אתה מדבר ככה?', 'The fat one said: what are you doing? We are friends from childhood, and why do you speak like that?'),
    ('הרזה חייך חיוך קטן ואמר: איך אפשר, אדוני, וזה לא מתאים, ואני יודע את מקומי.', 'The thin one smiled a small smile and said: how is it possible, sir, and it is not fitting, and I know my place.'),
    ('הוא הסתובב אל אשתו ואמר: זה חבר ותיק שלי, ואדם גדול, תגידי שלום יפה.', 'He turned to his wife and said: this is an old friend of mine, and a great man, say hello nicely.'),
    ('הילד הוריד את הכובע, והאישה הורידה את הראש, וכולם עמדו כמו בתמונה של משפחה זרה.', 'The child took off his hat, and the woman bowed, and everyone stood like in a photograph of a strange family.')),
  P(('השמן ניסה עוד פעם, והושיט את היד, ואמר שיבואו לבקר אצלו בבית.', 'The fat one tried once more, and held out his hand, and said that they should come to visit him at home.'),
    ('הרזה לחץ שלוש אצבעות בלבד, והוריד את הראש, וצחק צחוק קטן ולא נעים.', 'The thin one pressed only three fingers, and bowed, and laughed a small, unpleasant laugh.'),
    ('השמן הסתובב והלך, וזה היה ברור ששניהם רוצים שזה כבר ייגמר.', 'The fat one turned and went, and it was clear that both of them want this to be over already.'),
    ('הרזה נשאר עומד עם המזוודות, והרים אותן, ולא הסתכל על אשתו.', 'The thin one remained standing with the suitcases, and lifted them, and did not look at his wife.'))]),
 ('The Lottery Ticket', 'כרטיס ההגרלה', [
  P(('אחרי ארוחת הערב ישב האיש על הספה עם העיתון, מרוצה מהיום ומהאוכל.', 'After the evening meal the man sat on the sofa with the newspaper, satisfied with the day and with the food.'),
    ('אשתו ניקתה את השולחן, ואז אמרה לו: תסתכל בעיתון, פרסמו היום את המספרים.', 'His wife cleaned the table, and then said to him: look in the newspaper, they published the numbers today.'),
    ('הוא אמר: יש לך כרטיס השנה? והיא אמרה: כן, קניתי אחד, והוא במגירה.', 'He said: do you have a ticket this year? And she said: yes, I bought one, and it is in the drawer.'),
    ('היא הביאה אותו ואמרה את המספר בקול, והוא חיפש אותו בטור הראשון.', 'She brought it and said the number aloud, and he searched for it in the first column.')),
  P(('הוא אמר: הסדרה שלנו נמצאת, וזה כתוב כאן, ואני רואה את זה בעיניים שלי.', 'He said: our series is here, and it is written here, and I see it with my own eyes.'),
    ('היא הפסיקה לזוז, והניחה את המגבת, ואז ישבה על הכיסא בלי לומר מילה.', 'She stopped moving, and put down the towel, and sat on the chair without saying a word.'),
    ('הוא לא בדק את המספר עצמו מיד, והוא רצה להישאר עוד רגע בתוך הרגע הזה.', 'He did not check the number itself at once, and he wanted to stay another moment inside that moment.'),
    ('הוא אמר: אם זה אנחנו, זה שבעים וחמישה אלף, וזה משנה את כל החיים.', 'He said: if it is us, it is seventy-five thousand, and that changes the whole life.')),
  P(('הוא עצם את העיניים והתחיל לחשוב איך זה יהיה, והתמונות באו מהר.', 'He closed his eyes and began to think how it will be, and the pictures came fast.'),
    ('הוא ראה אדמה, ובית עם גינה, ועצים, ונהר קטן, ודגים במים.', 'He saw land, and a house with a garden, and trees, and a small river, and fish in the water.'),
    ('הוא ראה את עצמו הולך בבוקר עם דלי, ואוכל ריבה, וישן אחרי הצהריים.', 'He saw himself walking in the morning with a bucket, and eating jam, and sleeping in the afternoon.'),
    ('הוא ראה את הגשמים, והגשם, והאש בתנור, והוא כבר הרגיש את החום.', 'He saw the autumn, and the rain, and the fire in the stove, and he already felt the warmth.')),
  P(('ואז נכנסה לתמונה אשתו, ופתאום היא הפריעה לו, והוא לא ידע להסביר למה.', 'And then his wife entered the picture, and suddenly she disturbed him, and he did not know how to explain why.'),
    ('הוא חשב: הכרטיס שלה, לא שלי, וזה אומר שהכסף שלה ולא שלי.', 'He thought: the ticket is hers, not mine, and that means that the money is hers and not mine.'),
    ('הוא חשב: היא תיסע לחוץ לארץ, והיא תיקח את הכסף, והיא תשאיר אותי בבית.', 'He thought: she will travel abroad, and she will take the money, and leave me at home.'),
    ('הוא חשב: והמשפחה שלה תבוא, כל האחיות, וכל האחיינים, ואני אשלם על הכול.', 'He thought: and her family will come, all the sisters, and all the nephews, and I shall pay for everything.'),
    ('הוא פתח את העיניים והסתכל בה, והיא ישבה מולו ולא זזה, וגם היא חשבה.', 'He opened his eyes and looked at her, and she sat opposite him and did not move, and she too was thinking.')),
  P(('הוא ראה על הפנים שלה שגם היא כבר סידרה משהו בראש בלעדיו.', 'He saw on her face that she too had already arranged something in her head without him.'),
    ('הוא אמר בקול קר: ואל תשכחי שאני קניתי לך את הכרטיס הזה בכספי.', 'He said in a cold voice: and do not forget that I bought you this ticket with my money.'),
    ('היא אמרה: לא נכון, ואני קניתי אותו, ואתה אפילו לא ידעת עליו.', 'She said: not true, and I bought it, and you did not even know about it.'),
    ('הוא הרים את העיתון, ובדק את המספר האמיתי, והמספר לא היה שלהם.', 'He raised the newspaper, and checked the real number, and the number was not theirs.')),
  P(('הוא הניח את העיתון על הברכיים, ולא אמר כלום, והחדר נעשה קטן מאוד.', 'He put the newspaper on his knees, and said nothing, and the room became very small.'),
    ('הוא הסתכל על התקרה, ועל הרצפה, ועל הקירות, וכל דבר הרגיז אותו.', 'He looked at the ceiling, and at the floor, and at the walls, and everything annoyed him.'),
    ('הוא אמר: איזה בית, ואיזה אוכל, ואיזה חיים, ואי אפשר לנשום כאן בכלל.', 'He said: what a house, and what food, and what a life, and it is impossible to breathe here at all.'),
    ('היא אמרה: אז לך, ותלה את עצמך על עץ בחוץ, ואל תעשה לי טובות.', 'She said: then go, and hang yourself on a tree outside, and do not do me any favours.'),
    ('הוא לקח את הכובע ואז יצא, ובחוץ ירד גשם, והוא הלך ברחוב בלי מטרייה.', 'He took his hat and went out, and outside rain fell, and he walked in the street without an umbrella.'))]),
 ('Vanka', 'ואנקה', [
  P(('בערב חג המולד, כשכל הבית הלך לתפילה, נשאר ילד בן תשע לבד בסדנה.', 'On Christmas eve, when the whole house went to prayer, a nine-year-old boy remained alone in the workshop.'),
    ('הוא חיכה עד שהקולות נגמרו בחצר, ואז הוציא בקבוק דיו ועט חלוד.', 'He waited until the steps ended in the yard, and then took out a bottle of ink and a rusty pen.'),
    ('הוא הניח נייר ישן על הספסל, וכרע על הברכיים, והתחיל לכתוב.', 'He put a crumpled paper on the bench, and knelt on his knees, and began to write.'),
    ('הוא כתב: סבא היקר שלי, אני כותב לך מכתב, ואין לי אבא ואין לי אמא.', 'He wrote: my dear grandfather, I am writing you a letter, and I have no father and no mother.')),
  P(('לפני שהוא כתב עוד, הוא הסתכל לחלון וחשב על הכפר ועל הסבא שלו.', 'Before he wrote more, he looked at the window and thought about the village and about his grandfather.'),
    ('הסבא היה שומר לילה אצל אדונים, איש קטן בן שישים וחמש, שתמיד צחק.', 'The grandfather was a night watchman for gentlefolk, a small man of sixty-five, who always laughed.'),
    ('בלילות הוא היה מסתובב סביב הבית עם מקל, ושני כלבים היו הולכים אחריו.', 'At night he would go around the house with a stick, and two dogs would walk after him.'),
    ('אחד היה זקן ושחור, והשני היה צעיר ומהיר, ותמיד מקבל מכות ותמיד חוזר.', 'One was old and black, and the second was young and fast, and always gets beaten and always comes back.')),
  P(('הוא חזר לנייר וכתב: אתמול הבעל הבית לקח אותי בשיער וזרק אותי לחצר.', 'He returned to the paper and wrote: yesterday the master took me by the hair and threw me into the yard.'),
    ('הוא כתב: זה היה כי נרדמתי כששמרתי על התינוק שלהם, וזה קרה בלי כוונה.', 'He wrote: it was because I fell asleep while I rocked their baby, and it happened without intention.'),
    ('הוא כתב: והאישה שלחה אותי לנקות דג, והתחלתי מהזנב, והיא הכתה אותי בו.', 'He wrote: and the wife sent me to clean a fish, and I began from the tail, and she struck me with it.'),
    ('הוא כתב: והעובדים הגדולים שולחים אותי בלילה לקנות להם, וצוחקים עליי.', 'He wrote: and the older workers send me at night to buy for them, and laugh at me.'),
    ('הוא כתב: ואוכל אין, ובבוקר לחם, ובצהריים דייסה, ובערב שוב לחם.', 'He wrote: and food there is none, and in the morning bread, at noon porridge, and in the evening bread again.')),
  P(('הוא כתב: סבא, קח אותי מכאן, ואני לא יכול יותר, ואני מבקש את זה.', 'He wrote: grandfather, take me away from here, and I cannot any more, and I ask you.'),
    ('הוא כתב: אני אשפשף לך את הרגליים, ואני אתפלל בשבילך, ואתה תכה אותי אם אני רע.', 'He wrote: I shall rub your feet for you, and I shall pray for you, and beat me if I am bad.'),
    ('הוא כתב: ואם אין עבודה בשבילי, אני אבקש מהשומר שייתן לי לנקות נעליים.', 'He wrote: and if there is no work for me, I shall ask the watchman to let me clean shoes.'),
    ('הוא כתב: אני בורח ברגל, ואני לא יודע את הדרך, ואני מפחד מהזאבים.', 'He wrote: I will run away on foot, and I do not know the road, and I am afraid of the wolves.')),
  P(('הוא הפסיק לרגע, וזכר איך הם היו הולכים ליער להביא עץ לחג.', 'He stopped for a moment, and remembered how they used to go to the forest to bring a tree for the holiday.'),
    ('הסבא היה מעשן, וצוחק, וקורא לו לרוץ, והכפור היה נשרף על הפנים.', 'The grandfather would smoke, and laugh, and call him to run, and the frost would burn on the face.'),
    ('אחר כך הם היו סוחבים את העץ לבית הגדול, והגברת הייתה נותנת לו ממתק.', 'Afterwards they would drag the tree to the big house, and the lady would give him a sweet.'),
    ('היא לימדה אותו לקרוא ולכתוב, ובגלל זה הוא יושב עכשיו עם עט ביד.', 'She taught him to read and to write, and because of that he sits now with a pen in his hand.')),
  P(('הוא סיים וכתב בסוף: הנכד שלך, ואז חשב וכתב: תבוא מהר, אני מחכה.', 'He finished and wrote at the end: your grandson, and then thought and wrote: come quickly, I am waiting.'),
    ('הוא קיפל את הנייר לארבעה, והכניס אותו למעטפה שקנה אתמול בפרוטה.', 'He folded the paper into four, and put it into an envelope that he bought yesterday for a penny.'),
    ('הוא חשב רגע, ואז כתב על המעטפה: לכפר, לסבא, וזה נראה לו מספיק.', 'He thought a moment, and then wrote on the envelope: to the village, to grandfather, and that seemed enough to him.'),
    ('הוא רץ החוצה בלי מעיל, והגיע לתיבת הדואר בפינה, וזרק את המכתב פנימה.', 'He ran outside without a coat, and reached the postbox on the corner, and threw the letter inside.'),
    ('הוא חזר, ושכב, וחלם על הסבא שיושב על התנור וקורא את המכתב לכולם.', 'He came back, and lay down, and dreamed about the grandfather who sits on the stove and reads the letter to everyone.'))]),
 ('Oysters', 'הצדפים', [
  P(('אני זוכר את הערב ההוא היטב, ואני הייתי בן שמונה, ועמדתי ברחוב עם אבא.', 'I remember that evening well, and I was eight years old, and stood in the street with my father.'),
    ('היינו בעיר כמה חודשים, ואבא חיפש עבודה, ולא מצא, וכל יום היה קשה יותר.', 'We had been in the city several months, and father looked for work, and did not find any, and every day was harder.'),
    ('באותו ערב הוא לבש את המעיל הקיצי שלו, למרות הקור, כי את השני מכר.', 'That evening he wore his summer coat, in spite of the cold, because the other one he had sold.'),
    ('הוא עמד ליד קיר, ולא זז, והשפתיים שלו זזו כאילו הוא מדבר עם עצמו.', 'He stood beside a wall, and did not move, and his lips moved as if he speaks with himself.')),
  P(('אני ידעתי שהוא רוצה לבקש כסף מהאנשים שעוברים, וזה היה יומו הראשון.', 'I knew that he wants to ask money from the people who pass, and it was his first day.'),
    ('הוא הכין משפט וחזר עליו בשקט, ואז בא איש, ואבא לא אמר כלום.', 'He prepared a sentence and repeated it quietly, and then a man came, and father said nothing.'),
    ('אחר כך בא עוד אחד, ואבא עשה צעד קדימה, ואז חזר לקיר ועמד לידו.', 'Afterwards another one came, and father took a step forward, and then went back to the wall and leaned on it.'),
    ('אני לא אכלתי כלום מהבוקר, ובראש שלי היה חם, והרגליים שלי לא החזיקו.', 'I had eaten nothing since the morning, and in my head it was hot, and my legs did not hold me.')),
  P(('הסתכלתי מולי וראיתי שלט גדול על מסעדה, ובשלט הייתה מילה שלא הכרתי.', 'I looked in front of me and saw a big sign on a restaurant, and on the sign was a word that I did not know.'),
    ('שאלתי את אבא: מה זה אומר? והוא הסתכל ואמר: זאת חיה שאוכלים אותה.', 'I asked my father: what does it mean? And he looked and said: it is an animal that people eat.'),
    ('שאלתי אם היא טעימה, והוא אמר: היא חיה בים, בתוך קליפה, ואוכלים אותה חיה.', 'I asked whether it is tasty, and he said: it lives in the sea, inside a shell, and people eat it alive.'),
    ('הוא אמר: פותחים את הקליפה בסכין, ושמים לימון, ובולעים בלי ללעוס בכלל.', 'He said: they open the shell with a knife, and put lemon, and swallow without chewing at all.')),
  P(('בראש שלי התחילה לגדול תמונה של חיה רכה, עם עיניים, וקליפה קשה מסביב.', 'In my head a picture began to grow of a soft animal, with eyes, and a hard shell around it.'),
    ('חשבתי שזה דבר נורא, ושאני לעולם לא אוכל דבר כזה, ובכל זאת רציתי.', 'I thought that it is a terrible thing, and that I will never eat such a thing, and nevertheless I wanted it.'),
    ('הרעב היה חזק מהפחד, והתחלתי להרגיש את הטעם, ואת הלימון, ואת הקור.', 'The hunger was stronger than the fear, and I began to feel the taste, and the lemon, and the cold.'),
    ('פתחתי את הפה וצעקתי בקול: תנו לי צדפים! ואני לא ידעתי שאני צועק.', 'I opened my mouth and shouted aloud: give me oysters! And I did not know that I was shouting.'),
    ('אבא התכופף אלי, ושאל מה קרה, ואני חזרתי על אותה מילה עוד ועוד.', 'Father bent to me, and asked what happened, and I repeated the same word again and again.')),
  P(('שני אנשים עמדו מעלינו וצחקו, ואחד אמר: תראו, הילד רוצה צדפים, בואו.', 'Two men stood over us and laughed, and one said: look, the boy wants oysters, come.'),
    ('הם הכניסו אותי למסעדה, והושיבו אותי ליד שולחן, וכל הצלחות הבריקו.', 'They brought me into the restaurant, and sat me beside a table, and all the plates shone.'),
    ('הביאו צלחת עם קליפות, ואני לקחתי אחת, ואכלתי בלי להסתכל בכלל.', 'They brought a plate with shells, and I took one, and ate without looking at all.'),
    ('לא הרגשתי טעם, ורק הרגשתי משהו קר ורטוב, והמשכתי לאכול מהר.', 'I did not feel taste, and only felt something cold and wet, and I continued to eat fast.'),
    ('ואז התחלתי ללעוס גם את הקליפות, כי לא ידעתי איפה החיה נגמרת.', 'And then I began to chew the shells too, because I did not know where the animal ends.')),
  P(('האנשים צחקו חזק, וקראו לחברים שלהם, ומישהו אמר: תראו איך הוא אוכל.', 'The men laughed loudly, and called their friends, and someone said: see how he eats.'),
    ('אחר כך אני לא זוכר איך יצאתי, ואיך הגעתי הביתה, ואיך שכבתי במיטה.', 'Afterwards I do not remember how I went out, and how I got home, and how I lay in the bed.'),
    ('בלילה קמתי מהצמא, וראיתי את אבא יושב ליד החלון ומזיז את הידיים.', 'At night I got up from thirst, and saw father sitting beside the window and moving his hands.'),
    ('הוא היה חם, ודיבר לעצמו, ולא ידע שאני עומד לידו ומסתכל עליו.', 'He was hot, and spoke to himself, and did not know that I stand beside him and look at him.'),
    ('בבוקר שאלתי אותו אם ביקש כסף מהאנשים, והוא הסתכל בי ולא ענה כלום.', 'In the morning I asked him whether he had asked money from the people, and he looked at me and did not answer anything.'))]),
 ('The Complaints Book', 'ספר התלונות', [
  P(('בתחנת רכבת קטנה יש חדר עם שולחן, ועל השולחן מונח ספר קשור בחוט.', 'At a small railway station there is a room with a table, and on the table lies a book tied with string.'),
    ('הספר נקרא ספר התלונות, והוא נועד לנוסעים שרוצים לכתוב על עובדי התחנה.', 'The book is called the complaints book, and it is meant for passengers who want to write about the station workers.'),
    ('המפתח של הארון שבו הוא מונח אבד לפני שנתיים, והספר פשוט נשאר בחוץ.', 'The key of the cupboard where it lies was lost two years ago, and the book simply stayed outside.'),
    ('לכן כל אחד שנכנס לשם ומשתעמם לוקח את העט וכותב מה שהוא רוצה.', 'Therefore anyone who enters there and is bored takes the pen and writes what he wants.')),
  P(('בעמוד הראשון כתוב: אני מנסה את העט, ואני לא יודע אם יש בו דיו.', 'On the first page it is written: I am trying the pen, and I do not know whether there is ink in it.'),
    ('מתחת לזה כתוב: אני עברתי כאן ביום שני, ואני לא מרוצה, ולא אכתוב למה.', 'Under that it is written: I passed here on Monday, and I am not satisfied, and I will not write why.'),
    ('מתחת לזה כתוב בכתב יפה: כמה יפה הנוף מהחלון, ואיזה בוקר שקט וטוב.', 'Under that it is written in a fine hand: how beautiful the view is from the window, and what a quiet, good morning.'),
    ('ואחר כך מישהו הוסיף בעיפרון: מי שכתב את זה לא חיכה כאן ארבע שעות.', 'And afterwards someone added in pencil: whoever wrote this did not wait here four hours.')),
  P(('אחד כתב: אני מוחה על כך שהמנהל הסתכל על אשתי ולא הוריד את העיניים.', 'One wrote: I protest that the manager looked at my wife and did not lower his eyes.'),
    ('מתחת לזה ענה מישהו אחר: אולי הוא הסתכל כי אשתך עמדה על הפסים.', 'Under that someone else answered: perhaps he looked because your wife stood on the rails.'),
    ('ומתחת לזה כתב שלישי: כולם משעממים, ואני נוסע הרבה ורואה דברים אמיתיים.', 'And under that a third wrote: all of you are boring, and I travel a lot and see real things.'),
    ('אחד כתב שם של אישה שלוש פעמים, ואחר כך מחק אותו, וכתב אותו שוב.', 'One wrote a woman’s name three times, and afterwards crossed it out, and wrote it again.')),
  P(('בעמוד השני כתב מישהו שיר קצר על אהבה, ובשורה האחרונה שכח את החרוז.', 'On the second page someone wrote a short poem about love, and in the last line forgot the rhyme.'),
    ('מתחת לשיר כתוב: זה לא שיר, וזה גם לא תלונה, ואסור לכתוב כאן דברים כאלה.', 'Under the poem it is written: this is not a poem, and it is also not a complaint, and it is forbidden to write such things here.'),
    ('ומתחת לזה: ומי אתה שתגיד לי מה מותר, ואולי תכתוב תלונה עליי בעצמך.', 'And under that: and who are you to tell me what is permitted, and perhaps write a complaint about me yourself.'),
    ('ומתחת לזה מישהו צייר פנים עם אף ארוך, ולא כתב מילה אחת בכלל.', 'And under that someone drew a face with a long nose, and did not write one word at all.')),
  P(('אחד כתב: אני עומד לפטר את השומר, כי הוא ישן בזמן שהרכבת עוברת.', 'One wrote: I am about to dismiss the watchman, because he sleeps at the time when the train passes.'),
    ('מתחת לזה כתוב: הוא לא ישן, והוא רק סוגר את העיניים כדי לשמוע טוב.', 'Under that it is written: he does not sleep, and he only closes his eyes in order to hear better.'),
    ('אחד כתב תלונה ארוכה על הקפה, ואמר שהוא חם מדי ומר מדי וקטן מדי.', 'One wrote a long complaint about the coffee, and said that it is too hot and too bitter and too small.'),
    ('בסוף הוא כתב: ובכל זאת אני אשתה אותו שוב מחר, כי אין לי ברירה.', 'At the end he wrote: and nevertheless I shall drink it again tomorrow, because I have no choice.')),
  P(('בעמוד האחרון כתב פקיד התחנה: אני מבקש לא לכתוב כאן דברים שאינם תלונות.', 'On the last page the station clerk wrote: I ask that people not write here things that are not complaints.'),
    ('מתחת לזה ענה נוסע: ואני מבקש שהרכבת תבוא בזמן, וזאת תלונה אמיתית.', 'Under that a passenger answered: and I ask that the train come on time, and that is a real complaint.'),
    ('מתחת לזה כתוב בכתב גדול: אני אוהב אותה, והיא לא יודעת, וזה הכול.', 'Under that it is written in big handwriting: I love her, and she does not know, and that is all.'),
    ('ובשורה האחרונה של הספר כתוב: מי שקורא את זה, שיכתוב גם הוא משהו.', 'And on the last line of the book it is written: whoever reads this, let him also write something.'))]),
 ('The Bet', 'ההתערבות', [
  P(('בערב אחד ישב איש בנק זקן בחדר שלו וזכר מסיבה שערך לפני חמש עשרה שנה.', 'On one autumn evening an old banker sat in his room and remembered a party that he held fifteen years ago.'),
    ('היו שם אנשים חכמים, והשיחה עברה לעונש מוות, ורוב האורחים היו נגדו.', 'There were clever people there, and the conversation turned to the death penalty, and most of the guests were against it.'),
    ('הם אמרו שהמדינה לא יודעת להחיות, ולכן היא לא צריכה לקחת חיים.', 'They said that the state does not know how to give life, and therefore it should not take life.'),
    ('איש הבנק אמר: אני חושב שמוות טוב יותר ממאסר לכל החיים, וכל אחד יבחר במוות.', 'The banker said: I think that death is better than imprisonment for life, and everyone would choose death.')),
  P(('עורך דין צעיר שישב שם אמר: אני חושב אחרת, ואני הייתי בוחר לחיות.', 'A young lawyer who sat there said: I think otherwise, and I would choose to live.'),
    ('איש הבנק צחק ואמר: אני שם שני מיליון על זה שאתה לא תחזיק חמש שנים.', 'The banker laughed and said: I put two million on it that you will not last five years.'),
    ('הצעיר אמר: לא חמש, אלא חמש עשרה, ואני מוכן להתחיל כבר הלילה.', 'The young man said: not five, but fifteen, and I am ready to begin this very night.'),
    ('הם לחצו ידיים, וכולם צחקו, וכולם ידעו ששניהם שתו יותר מדי יין.', 'They shook hands, and everyone laughed, and everyone knew that both of them had drunk too much wine.')),
  P(('בבוקר הם כתבו הסכם: הצעיר יגור בבית קטן בגן, ולא יראה איש.', 'In the morning they wrote an agreement: the young man will live in a small house in the garden, and will see no one.'),
    ('הוא יוכל לקבל ספרים, ויין, ומכתבים, וכל דבר, על ידי חלון קטן בקיר.', 'He will be able to receive books, and wine, and letters, and everything, through a small window in the wall.'),
    ('אם הוא יצא מהדלת דקה אחת לפני הזמן, איש הבנק לא ישלם לו כלום.', 'If he goes out of the door one minute before the time, the banker will not pay him anything.'),
    ('הם קבעו את השעה בדיוק, ואת היום, ואת החודש, ואת השנה שבה זה נגמר.', 'They fixed the hour exactly, and the day, and the month, and the year in which it ends.')),
  P(('בשנה הראשונה הוא ביקש ספרים קלים, ולא נגע ביין, וניגן בפסנתר הרבה.', 'In the first year he asked for light books, and did not touch wine, and played the piano a lot.'),
    ('בשנה השנייה הפסנתר שתק, והוא ביקש ספרים גדולים של סופרים ידועים.', 'In the second year the piano was silent, and he asked for great books by known writers.'),
    ('בשנה החמישית הוא שתה יין, ושכב, ולפעמים כתב כל הלילה וקרע בבוקר.', 'In the fifth year he drank wine, and lay down, and sometimes wrote all night and tore it up in the morning.'),
    ('אחר כך הוא למד שפות, ואחר כך פילוסופיה, ואחר כך ביקש רק ספר אחד.', 'Afterwards he studied languages, and afterwards philosophy, and afterwards asked for only one book.'),
    ('בשנים האחרונות הוא קרא הכול בערבוביה, וביקש ספר על כימיה ואחריו שירים.', 'In the last years he read everything mixed together, and asked for a book on chemistry and after it poems.')),
  P(('ובאותן שנים עברו על איש הבנק שנים רעות, ובבורסה הוא הפסיד כמעט את הכול.', 'Meanwhile bad years passed over the banker, and on the exchange he lost almost everything.'),
    ('בלילה שלפני הסוף הוא ישב וחשב: אם אשלם שני מיליון, אני גמור לגמרי.', 'On the night before the end he sat and thought: if I pay two million, I am completely finished.'),
    ('הוא לקח מפתח, ואז יצא לגן בגשם, ואז נכנס לבית הקטן בלי להשמיע קול.', 'He took a key, and went out to the garden in the rain, and entered the little house without making a sound.'),
    ('הוא רצה לעשות דבר נורא, ואמר לעצמו שאיש לא יידע ושהכול ייראה טבעי.', 'He wanted to do a terrible thing, and said to himself that no one would know and that everything would look natural.')),
  P(('בחדר ישב איש שנראה כמו שלד, עם שיער ארוך, וישן על השולחן.', 'In the room sat a man who looked like a skeleton, with long hair, and slept on the table.'),
    ('לידו היה נייר כתוב, ואיש הבנק לקח אותו והתקרב לנר וקרא אותו לאט.', 'Beside him was a written paper, and the banker took it and drew near the candle and read it slowly.'),
    ('היה כתוב שם: מחר אני יוצא לחופש, ולפני זה יש לי דבר אחד לומר לך.', 'It was written there: tomorrow I go out to freedom, and before that I have one thing to say to you.'),
    ('היה כתוב: קראתי אלף ספרים, וראיתי ערים, ואהבתי נשים, וטיפסתי על הרים.', 'It was written: I have read a thousand books, and seen cities, and loved women, and climbed mountains.'),
    ('היה כתוב: וכל זה קרה בראש שלי בלבד, ובכל זאת אני יודע שזה שווה מעט.', 'It was written: and all of that happened in my head alone, and nevertheless I know that it is worth little.')),
  P(('היה כתוב בסוף: אתם חיים בשקר, ואתם קוראים ליופי מה שאינו יפה.', 'It was written at the end: you live in a lie, and you call beautiful what is not beautiful.'),
    ('היה כתוב: ואני מראה לכם שאני מואס בזה, ולכן אני יוצא חמש שעות מוקדם.', 'It was written: and I show you that I despise it, and therefore I go out five hours early.'),
    ('היה כתוב: ובזה אני מפסיד את הכסף, ואני עושה את זה בכוונה גמורה.', 'It was written: and by this I lose the money, and I do it with complete intention.'),
    ('איש הבנק הניח את הנייר, ונשק לאיש הישן על הראש, ואז יצא, ובכה בגשם.', 'The banker put down the paper, and kissed the sleeping man on the head, and went out, and wept in the rain.'),
    ('בבוקר השומרים באו וסיפרו שהאיש ברח מהחלון, ואיש הבנק לקח את הנייר ושמר אותו בכספת.', 'In the morning the guards came and told that the man had escaped through the window, and the banker took the paper and kept it in the safe.'))]),
 ('A Trifle', 'דבר קטן', [
  P(('איש צעיר ונעים היה בא כל ערב לבית של אישה שהוא הכיר כבר שנתיים.', 'A young, pleasant man used to come every evening to the house of a woman whom he had known for two years already.'),
    ('היא הייתה נשואה פעם, והבעל עזב, והיא נשארה עם שני ילדים קטנים.', 'She had once been married, and the husband left, and she remained with two small children.'),
    ('האיש היה נוח לעצמו, והוא אהב לשבת שם, כי בבית היה חם ושקט ונקי.', 'The man was comfortable with himself, and liked to sit there, because in the house it was warm and quiet and clean.'),
    ('הוא לא חשב הרבה על הילדים, וכשראה אותם היה אומר להם שלום ולא יותר.', 'He did not think much about the children, and when he saw them he would say hello to them and not more.')),
  P(('ערב אחד הוא בא מוקדם, והאם עוד לא הייתה מוכנה, והוא חיכה בסלון.', 'One evening he came early, and the mother was not yet ready, and he waited in the sitting room.'),
    ('הילד הגדול, בן שמונה, נכנס אליו, והסתכל בו, והתיישב לידו על הספה.', 'The older boy, eight years old, came in to him, and looked at him, and sat down beside him on the sofa.'),
    ('הוא היה ילד חכם, עם עיניים גדולות, ותמיד חשב לפני שהוא פותח את הפה.', 'He was a clever child, with big eyes, and always thought before he opens his mouth.'),
    ('האיש אמר לו: אז מה שלומך, ומה עשית היום, ואיך היה בבית הספר?', 'The man said to him: so how are you, and what did you do today, and how was it at school?')),
  P(('הילד ענה בקצרה, ואז שתק, ואז הרים את הראש ואמר: אתה יודע לשמור סוד?', 'The child answered briefly, and then was silent, and then raised his head and said: do you know how to keep a secret?'),
    ('האיש צחק ואמר: אני איש מבוגר, ואני שומר סודות טוב יותר מכל אחד.', 'The man laughed and said: I am a grown man, and I keep secrets better than anyone.'),
    ('הילד הסתכל אל הדלת, ואז התקרב, ואמר בקול נמוך מאוד: ראינו את אבא.', 'The child looked at the door, and then came closer, and said in a very low voice: we saw father.'),
    ('הוא אמר: אנחנו נפגשים איתו בגן, ואמא לא יודעת, ואסור להגיד לה.', 'He said: we meet him in the park, and mother does not know, and it is forbidden to tell her.')),
  P(('הילד סיפר: הוא בוכה כשהוא רואה אותנו, ומחזיק אותנו, ומספר לנו סיפורים.', 'The child told: he weeps when he sees us, and holds us, and tells us stories.'),
    ('הוא אמר: הוא קונה לנו ממתקים, ואומר שהוא חושב עלינו כל בוקר וכל לילה.', 'He said: he buys us sweets, and says that he thinks about us every morning and every night.'),
    ('הוא אמר: הוא אמר שאם אמא תדע, היא לא תיתן לנו לראות אותו יותר.', 'He said: he said that if mother knows, she will not let us see him any more.'),
    ('האיש אמר: אני מבין, וזה סוד, ואל תדאג, ואני לא אומר מילה אחת.', 'The man said: I understand, and it is a secret, and do not worry, and I shall not say one word.')),
  P(('אחרי רגע נכנסה האם, מוכנה, ושאלה על מה הם מדברים כל כך יפה.', 'After a moment the mother came in, ready, and asked what they are talking about so nicely.'),
    ('האיש רצה לומר משהו נעים, ולא מצא, ואז הוא סיפר לה את מה ששמע.', 'The man wanted to say something pleasant, and did not find anything, and then he told her what he had heard.'),
    ('הוא סיפר את זה בקלות, כמו דבר קטן, וצחק, וחשב שזה יעשה שיחה.', 'He told it lightly, like a small thing, and laughed, and thought that it would make conversation.'),
    ('הפנים של האם השתנו, והיא קמה, ופנתה אל הילד, ואמרה: זה נכון?', 'The mother’s face changed, and she got up, and turned to the child, and said: is that true?')),
  P(('הילד עמד, והסתכל באיש, ולא הבין, וחיכה שהאיש יגיד שזאת טעות.', 'The child stood, and looked at the man, and did not understand, and waited for the man to say that it is a mistake.'),
    ('האיש הסתכל הצידה, ואמר: זה באמת שום דבר, וילדים מספרים כל מיני דברים.', 'The man looked aside, and said: it is really nothing, and children tell all sorts of things.'),
    ('האם לקחה את הילד ביד וסחבה אותו לחדר השני, ואז נשמעו קולות.', 'The mother took the child by the hand and dragged him to the other room, and then voices were heard.'),
    ('האיש ישב על הספה, והרים את העיתון, וקרא שורה אחת שלוש פעמים.', 'The man sat on the sofa, and raised the newspaper, and read one line three times.'),
    ('כשהילד יצא משם, הוא עבר לידו לאט, ולא בכה, ולא הסתכל עליו.', 'When the child came out of there, he passed beside him slowly, and did not weep, and did not look at him.'))]),
 ('Grief', 'הצער', [
  P(('הערב ירד על העיר, והשלג נפל לאט, וכיסה את הגגות ואת האנשים ואת הסוסים.', 'The evening came down on the city, and the snow fell slowly, and covered the roofs and the people and the horses.'),
    ('נהג זקן ישב על העגלה שלו כבר שעות, ולא זז, והשלג עמד על הכתפיים שלו.', 'An old cabman had been sitting on his cab for hours already, and did not move, and the snow stood on his shoulders.'),
    ('הסוס שלו עמד לפניו לבן ושקט, ולא הזיז את הראש, וגם הוא חשב משהו.', 'His horse stood in front of him white and quiet, and did not move its head, and it too was thinking something.'),
    ('שניהם נלקחו מהשדה ומהעבודה השקטה, ונזרקו לתוך הרעש הזה של העיר.', 'Both of them were taken from the field and from the quiet work, and thrown into this noise of the city.')),
  P(('סוף סוף עצר לידו קצין וצעק לו כתובת, והם יצאו לדרך בין העגלות.', 'At last an officer stopped beside him and shouted an address to him, and they set out among the carriages.'),
    ('הנהג הסתובב לאחור באמצע הנסיעה ואמר: אדוני, הבן שלי מת השבוע.', 'The cabman turned back in the middle of the ride and said: sir, my son died this week.'),
    ('הקצין שאל: ממה הוא מת? והנהג הסתובב עוד קצת כדי לספר את הכול.', 'The officer asked: what did he die of? And the cabman turned a little more in order to tell everything.'),
    ('הקצין אמר: תסתכל על הדרך, ואתה כמעט נכנסת בעגלה, ואתה תשמור על הראש שלי.', 'The officer said: look at the road, and you almost went into a carriage, and take care of my head.')),
  P(('אחר כך עלו שלושה צעירים, וצחקו, והתווכחו כל הדרך על מי משלם.', 'Afterwards three young men got on, and laughed, and argued the whole way about who pays.'),
    ('אחד מהם היה גבוה, ושניים היו נמוכים, וכולם דיברו יחד ולא הקשיבו.', 'One of them was tall, and two were short, and all of them spoke together and did not listen.'),
    ('הנהג שמע אותם וחייך, כי לפחות יש בעגלה קול של אנשים חיים.', 'The cabman heard them and smiled, because at least there is in the cab the sound of living people.'),
    ('אחרי כמה דקות הוא אמר להם: והשבוע, אתם יודעים, הבן שלי מת אצלי.', 'After a few minutes he said to them: and this week, you know, my son died on me.'),
    ('הגבוה אמר: כולנו נמות, וקדימה, סע מהר יותר, ולמה אתה נוסע כמו זקן.', 'The tall one said: all of us will die, and go on, drive faster, and why do you drive like an old man.')),
  P(('כשהם ירדו הוא נשאר לבד שוב, ואז נסע לאט, וחיפש עוד מישהו ברחוב.', 'When they got down he remained alone again, and drove slowly, and looked for someone else in the street.'),
    ('הוא ראה שוער עומד בפתח, ועצר לידו, ואמר לו: כבר מאוחר, נכון?', 'He saw a doorkeeper standing in a doorway, and stopped beside him, and said to him: it is late already, is it not?'),
    ('השוער אמר: מאוחר, לך מכאן, ואל תעמוד לי בפתח, ואל תפריע לאנשים.', 'The doorkeeper said: it is late, go away from here, and do not stand in my doorway, and do not disturb people.'),
    ('הנהג הרים את המושכות, וכל גופו כאב, כי הצער היה גדול והוא לא יצא.', 'The cabman raised the reins, and his whole body hurt, because the grief was big and it did not come out.')),
  P(('הוא חזר לחצר של האכסניה, ושם ישנו הנהגים על הרצפה ועל הספסלים.', 'He came back to the yard of the inn, and there the cabmen slept on the floor and on the benches.'),
    ('היה חם וחשוך, וריח של בגדים רטובים, ואיש לא פתח את העיניים.', 'It was warm and dim, and a smell of wet clothes, and no one opened his eyes.'),
    ('הוא ראה בחור צעיר שקם לשתות מים, וניגש אליו מהר, והתחיל לדבר.', 'He saw a young lad who got up to drink water, and went to him fast, and began to speak.'),
    ('הוא אמר: הבן שלי, אתה יודע, הוא היה חולה שלושה ימים, ואז הוא הלך.', 'He said: my son, you know, he was ill three days, and then he went.'),
    ('הבחור שתה, וקינח את הפה, ושכב בחזרה, ואז נרדם לפני שהמשפט נגמר.', 'The lad drank, and wiped his mouth, and lay back down, and fell asleep before the sentence ended.')),
  P(('הנהג ישב על הספסל ולא יכול לישון, ולבש את המעיל, ואז יצא החוצה.', 'The cabman sat on the bench and could not sleep, and put on his coat, and went outside.'),
    ('הוא הלך לאורווה, ועמד ליד הסוס שלו, ושם לו אוכל, והסתכל עליו.', 'He went to the stable, and stood beside his horse, and put food for it, and looked at it.'),
    ('הוא אמר: אתה אוכל, ואני עומד, ואין לנו כסף, וזה מה שיש היום.', 'He said: you are eating, and I am standing, and we have no money, and that is what there is today.'),
    ('הוא אמר: היה לי בן, ועכשיו אין לי בן, ואתה מבין את זה, נכון?', 'He said: I had a son, and now I have no son, and you understand that, do you not?'),
    ('הסוס לעס, ואז נשם על היד שלו, והקשיב, והנהג סיפר לו את הכול מההתחלה.', 'The horse chewed, and breathed on his hand, and listened, and the cabman told it everything from the beginning.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('shortstories', {'en': 'Twenty Stories: Maupassant & Chekhov',
                                           'he': "עשרים סיפורים: מופסאן וצ'כוב"}, 'advanced',
                          CHAPTERS, unit='Story', unit_he='סיפור', shelf=21, meta=META))
