#!/usr/bin/env python3
"""אי המטמון — Stevenson, retold in modern Hebrew, graded to intermediate.

The Hebrew twin of pipeline/book_treasure.py, chapter for chapter. Stevenson died in 1894 and
the book is public domain; this is a retelling from the plot rather than a translation.

WHY IT IS ON THIS SHELF. It is told in the FIRST PERSON by a boy roughly the age of the reader
of any language course's imagined self, which does two useful things at once: it keeps the verbs
in a person a learner uses constantly, and it means every fact arrives as something someone
noticed rather than as narration from above. That is the register spoken Hebrew actually has.

Deliberately unpointed; the vowels are looked up at ingest. The names are declared in
pipeline/he_curated.py.

Run:  python3 pipeline/he_book_treasure.py --lang he            # check
      python3 pipeline/he_book_treasure.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'Treasure Island', 'author': 'Robert Louis Stevenson', 'year': '1883',
        'status': 'public domain'}

CHAPTERS = [
 ('The Old Sea-Dog', 'המלח הזקן', [
  P(("קוראים לי ג'ים הוקינס, וזה הסיפור שלי על המטמון.", 'My name is Jim Hawkins, and this is my story about the treasure.'),
    ('להורים שלי היה פונדק קטן ליד הים.', 'My parents had a small inn by the sea.'),
    ('אבא שלי היה חולה, ואימא שלי עשתה את כל העבודה.', 'My father was ill, and my mother did all the work.'),
    ('ואני הייתי ילד, עזרתי במטבח והסתכלתי על הדרך.', 'And I was a boy, I helped in the kitchen and watched the road.')),
  P(('יום אחד בא איש זקן, ועל הכתף שלו ארגז של מלח.', 'One day an old man came, and on his shoulder a sailor’s chest.'),
    ('הוא היה גבוה וחזק, ועל הפנים שלו הייתה צלקת גדולה.', 'He was tall and strong, and on his face there was a big scar.'),
    ('השיער שלו היה לבן וקשור, והבגדים שלו מלוכלכים.', 'His hair was white and tied back, and his clothes were dirty.'),
    ('הוא עמד לפני הפונדק והסתכל על הים הרבה זמן.', 'He stood in front of the inn and looked at the sea a long time.'),
    ('ואז הוא אמר: כאן טוב, אני רוצה חדר.', 'And then he said: here is good, I want a room.'),
    ('הוא זרק מטבע זהב על השולחן ואמר: כשזה נגמר, תגידו לי.', 'He threw a gold coin on the table and said: when it runs out, tell me.')),
  P(('הוא גר אצלנו חודשים, ואף פעם לא דיבר על עצמו.', 'He lived with us for months, and never spoke about himself.'),
    ('כל יום הוא עלה על הסלעים עם המשקפת שלו, והסתכל על הים.', 'Every day he went up on the rocks with his spyglass, and looked at the sea.'),
    ('ובלילה הוא שתה רום ושר שירים של מלחים.', 'And at night he drank rum and sang sailors’ songs.'),
    ('האנשים פחדו ממנו, ובאותו זמן אהבו לשמוע את הסיפורים שלו.', 'People were afraid of him, and at the same time loved to hear his stories.'),
    ('סיפורים על סופות, על תלייה, ועל אנשים שהולכים על הקרש.', 'Stories about storms, about hanging, and about men who walk the plank.'),
    ('וכולם קראו לו: המפקד.', 'And everyone called him: the Captain.')),
  P(('יום אחד הוא לקח אותי הצידה ונתן לי כסף.', 'One day he took me aside and gave me money.'),
    ('הוא אמר: כל חודש אני נותן לך ככה, ואתה תסתכל על הדרך.', 'He said: every month I give you this, and you watch the road.'),
    ('אם אתה רואה מלח עם רגל אחת, בוא תגיד לי מיד.', 'If you see a sailor with one leg, come and tell me at once.'),
    ('שאלתי אותו: מי הוא? הוא לא ענה.', 'I asked him: who is he? He did not answer.'),
    ('אבל מאותו יום חלמתי על המלח עם הרגל האחת.', 'But from that day I dreamed about the sailor with one leg.'),
    ('הוא בא בלילה, בצורה אחרת כל פעם, ורץ אחריי.', 'He came at night, in a different shape every time, and ran after me.'),
    ('ולא ידעתי שאני אראה אותו באמת, ובקרוב.', 'And I did not know that I would see him for real, and soon.'))]),

 ('Black Dog', 'הכלב השחור', [
  P(('ביום חורף קר אבא שלי היה חולה מאוד, ואני הייתי לבד בפונדק.', 'One cold winter day my father was very ill, and I was alone in the inn.'),
    ('המפקד יצא ללכת על החוף, כמו בכל בוקר.', 'The Captain had gone out to walk on the shore, as on every morning.'),
    ('הדלת נפתחה, והוא נכנס, איש שלא ראיתי לפני כן.', 'The door opened, and a man I had not seen before came in.'),
    ('הוא היה חיוור ושמן, וחסרו לו שתי אצבעות ביד שמאל.', 'He was pale and fat, and two fingers were missing from his left hand.'),
    ('הוא לא נראה כמו מלח, אבל היה בו משהו מהים.', 'He did not look like a sailor, but there was something of the sea in him.')),
  P(('הוא ביקש כוס רום, ושאל אותי: השולחן הזה בשביל החבר שלי בילי?', 'He asked for a glass of rum, and asked me: is this table for my friend Billy?'),
    ('אמרתי לו: אני לא מכיר בילי, יש אצלנו אחד שקוראים לו המפקד.', 'I told him: I do not know any Billy, we have one here they call the Captain.'),
    ('הוא אמר: המפקד? יש לו צלקת על הלחי, נכון?', 'He said: the Captain? He has a scar on his cheek, right?'),
    ('אמרתי: נכון.', 'I said: right.'),
    ('הוא צחק צחוק שלא אהבתי, ואמר: זה בילי, איפה הוא?', 'He laughed a laugh I did not like, and said: that is Billy, where is he?'),
    ('אמרתי: הוא יצא ללכת, והוא יחזור בקרוב.', 'I said: he went out to walk, and he will be back soon.'),
    ('הוא אמר: טוב, אני אחכה לו כאן, הוא ישמח לראות אותי.', 'He said: good, I will wait for him here, he will be glad to see me.'),
    ('והוא ישב מאחורי הדלת, במקום שלא רואים ממנו.', 'And he sat behind the door, in a place one cannot be seen from.')),
  P(('אחרי זמן קצר המפקד נכנס.', 'A little later the Captain came in.'),
    ('הוא הלך לשולחן שלו, ולא ראה את האיש.', 'He went to his table, and did not see the man.'),
    ('האיש אמר מאחוריו: בילי.', 'The man said from behind him: Billy.'),
    ('המפקד הסתובב, והפנים שלו נהיו לבנות כמו הקיר.', 'The Captain turned, and his face went white as the wall.'),
    ('הוא אמר: הכלב השחור!', 'He said: Black Dog!'),
    ('האיש אמר: זה אני, הכלב השחור בא לבקר את החבר הישן שלו בילי.', 'The man said: it is me, Black Dog has come to visit his old friend Billy.'),
    ('המפקד אמר: טוב, מה אתה רוצה?', 'The Captain said: fine, what do you want?'),
    ('הכלב השחור אמר: לדבר, אבל קודם, ילד, צא החוצה.', 'Black Dog said: to talk, but first, boy, get out.')),
  P(('יצאתי, אבל עמדתי מאחורי הדלת ושמעתי.', 'I went out, but I stood behind the door and listened.'),
    ('בהתחלה הם דיברו בשקט, והבנתי רק מילים.', 'At first they talked quietly, and I understood only words.'),
    ('ואז הקולות עלו, ושמעתי את המפקד צועק: לא, לא, לא!', 'And then the voices rose, and I heard the Captain shout: no, no, no!'),
    ('ואז היה רעש של כיסאות, ורעש של חרבות.', 'And then there was a noise of chairs, and a noise of swords.'),
    ('פתחתי את הדלת וראיתי את שניהם עומדים, וביד של כל אחד חרב.', 'I opened the door and saw the two of them standing, a sword in each one’s hand.'),
    ('הכלב השחור דימם מהכתף.', 'Black Dog was bleeding from the shoulder.'),
    ('הוא ברח מהדלת, רץ על הדרך, ונעלם.', 'He fled through the door, ran up the road, and vanished.'),
    ('והמפקד עמד במקום, תפס את הקיר, והוא נפל על הרצפה.', 'And the Captain stood where he was, held the wall, and fell to the floor.'))]),

 ('The Black Spot', 'הכתם השחור', [
  P(('רצתי וקראתי לאימא שלי, והבאנו את הרופא ליבסי.', 'I ran and called my mother, and we fetched Doctor Livesey.'),
    ('הרופא היה איש שקט ונקי, והוא לא פחד מאף אחד.', 'The doctor was a quiet, clean man, and he was afraid of no one.'),
    ('הוא בדק את המפקד ואמר: זה לא פצע, זה מהרום.', 'He examined the Captain and said: this is no wound, this is from the rum.'),
    ('כשהמפקד התעורר, הרופא אמר לו: עוד כוס רום, ואתה מת.', 'When the Captain woke, the doctor told him: one more glass of rum, and you die.'),
    ('המפקד אמר: אני מת בלי רום.', 'The Captain said: I die without rum.'),
    ('הרופא אמר: זאת ההחלטה שלך.', 'The doctor said: that is your decision.')),
  P(('בלילה המפקד קרא לי לחדר שלו.', 'At night the Captain called me to his room.'),
    ("הוא אמר: ג'ים, אתה היחיד שאני סומך עליו.", 'He said: Jim, you are the only one I trust.'),
    ('הכלב השחור לא לבד, יש רבים, וכולם רוצים את הארגז שלי.', 'Black Dog is not alone, there are many, and they all want my chest.'),
    ('שאלתי אותו: ולמה הם רוצים את הארגז שלך?', 'I asked him: and why do they want your chest?'),
    ('הוא אמר: כי הייתי העוזר הראשון של פלינט.', 'He said: because I was Flint’s first mate.'),
    ('פלינט, שודד הים הכי מסוכן, ואני היחיד שיודע איפה המקום שלו.', 'Flint, the most dangerous pirate, and I am the only one who knows his place.'),
    ('אם הם באים ונותנים לי את הכתם השחור, רוץ לרופא.', 'If they come and give me the black spot, run to the doctor.'),
    ('שאלתי: מה זה הכתם השחור?', 'I asked: what is the black spot?'),
    ('הוא אמר: אזהרה, זה אומר שהזמן שלך הגיע.', 'He said: a warning, it means your time has come.')),
  P(('ובאותו שבוע אבא שלי מת.', 'And that same week my father died.'),
    ('הייתי עסוק בצער, ושכחתי את המפקד ואת הארגז שלו.', 'I was taken up with grief, and forgot the Captain and his chest.'),
    ('אבל יום אחד אחרי ההלוויה עמדתי ליד הדלת, וראיתי מישהו בא בדרך.', 'But one day after the funeral I stood by the door, and saw someone coming up the road.'),
    ('הוא היה עיוור, הלך עם מקל, ולבש גלימה גדולה.', 'He was blind, walked with a stick, and wore a big cloak.'),
    ('הוא אמר: יש כאן מישהו שיעזור לעיוור מסכן?', 'He said: is there someone here to help a poor blind man?'),
    ('נתתי לו את היד שלי, והוא תפס אותה בכוח כמו ברזל.', 'I held out my hand, and he grabbed it with a grip like iron.'),
    ('הוא אמר בקול אחר: קח אותי אל המפקד, או שאני שובר לך את היד.', 'He said in another voice: take me to the Captain, or I break your arm.')),
  P(('הכנסתי אותו אל המפקד, והלב שלי דפק.', 'I brought him in to the Captain, and my heart pounded.'),
    ('כשהמפקד ראה אותו, הוא ניסה לקום, ולא הצליח.', 'When the Captain saw him, he tried to get up, and could not.'),
    ('העיוור אמר: תישאר לשבת, בילי, תן את היד.', 'The blind man said: stay seated, Billy, hold out your hand.'),
    ('הוא שם נייר ביד של המפקד, והוא יצא מהר, והמקל שלו דפק על הדרך.', 'He put a paper in the Captain’s hand, and went out fast, and his stick tapped on the road.'),
    ('המפקד פתח את הנייר, וראה כתם שחור.', 'The Captain opened the paper, and saw a black spot.'),
    ('ומתחתיו היה כתוב: יש לך עד השעה עשר הלילה.', 'And beneath it was written: you have until ten o’clock tonight.'),
    ("הוא אמר: עשר! יש לנו שש שעות, ג'ים, אנחנו נצליח.", 'He said: ten! We have six hours, Jim, we will make it.'),
    ('הוא קם, תפס את החזה שלו, והוא נפל.', 'He got up, clutched his chest, and fell.'),
    ('והפעם הוא לא התעורר.', 'And this time he did not wake.'))]),

 ('The Sea Chest', 'ארגז המלח', [
  P(('סיפרתי לאימא שלי הכול, ולא היה לנו זמן לבכות.', 'I told my mother everything, and we had no time to cry.'),
    ('היא אמרה: האיש הזה היה חייב לנו כסף, והכסף בארגז שלו.', 'She said: this man owed us money, and the money is in his chest.'),
    ('ואני לא אתן לחברים שלו לקחת את מה ששלנו.', 'And I will not let his friends take what is ours.'),
    ('רצנו לכפר לבקש עזרה, אבל האנשים פחדו.', 'We ran to the village to ask for help, but the people were afraid.'),
    ('המילה פלינט הספיקה כדי שאף אחד לא יצא איתנו.', 'The word Flint was enough for no one to come with us.'),
    ('אימא שלי אמרה: טוב, אנחנו הולכים לבד.', 'My mother said: fine, we go alone.')),
  P(('חזרנו לפונדק בחושך, וסגרנו את הדלת.', 'We went back to the inn in the dark, and locked the door.'),
    ('המפקד שכב על הרצפה כמו שהשארנו אותו.', 'The Captain lay on the floor as we had left him.'),
    ('לקחתי את המפתח מהצוואר שלו, ועלינו לחדר שלו.', 'I took the key from around his neck, and we went up to his room.'),
    ('הארגז היה ישן, ועליו האות ב שרופה.', 'The chest was old, and on it the letter B burned in.'),
    ('פתחנו אותו: בגדים, מצפן, שני אקדחים, ומטבע כסף.', 'We opened it: clothes, a compass, two pistols, and a silver coin.'),
    ('ומתחת לכל זה, שק כסף, וחבילת ניירות עטופה בבד.', 'And under all that, a bag of money, and a bundle of papers wrapped in cloth.')),
  P(('אימא שלי התחילה לספור את הכסף, מטבע אחרי מטבע.', 'My mother began counting the money, coin after coin.'),
    ('היא אמרה: רק מה ששלנו, ולא אגורה יותר.', 'She said: only what is ours, and not a penny more.'),
    ('המטבעות היו מכל ארצות העולם, והיא הייתה איטית.', 'The coins were from every country in the world, and she was slow.'),
    ('ואני עמדתי ליד החלון, והלב שלי בגרון.', 'And I stood by the window, my heart in my throat.'),
    ('ופתאום שמעתי קול: דפיקה, דפיקה, דפיקה, על הדרך.', 'And suddenly I heard a sound: tap, tap, tap, on the road.'),
    ('המקל של העיוור.', 'The blind man’s stick.')),
  P(('הקול הגיע לדלת, ואז מישהו ניסה את הידית.', 'The sound reached the door, and then someone tried the handle.'),
    ('הדלת הייתה סגורה, והעיוור עמד, ואז הלך.', 'The door was locked, and the blind man stood, and then walked away.'),
    ('אמרתי: אימא, קחי את כל השק ובואי נצא!', 'I said: mother, take the whole bag and let us go!'),
    ('היא אמרה: לא, רק מה ששלנו.', 'She said: no, only what is ours.'),
    ('ואז שמענו שריקה מרחוק, וקול של הרבה אנשים רצים.', 'And then we heard a whistle from afar, and the sound of many men running.'),
    ('אימא שלי אמרה: טוב, קח את הניירות, ואני לוקחת מה שספרתי.', 'My mother said: fine, take the papers, and I take what I have counted.'),
    ('ויצאנו מהדלת שמאחור, לתוך החושך.', 'And we went out the back door, into the dark.'))]),

 ('The Blind Man', 'העיוור', [
  P(('הערפל היה כבד, והירח עוד לא עלה.', 'The fog was heavy, and the moon had not yet risen.'),
    ('רצנו עד הגשר הקטן, ואימא שלי אמרה: אני לא יכולה להמשיך.', 'We ran as far as the little bridge, and my mother said: I cannot go on.'),
    ('היא נפלה ליד הגשר, ואני משכתי אותה מתחתיו.', 'She fell beside the bridge, and I pulled her under it.'),
    ('היינו קרובים לפונדק, ושמענו וראינו הכול.', 'We were close to the inn, and heard and saw everything.'),
    ('ראיתי שבעה או שמונה אנשים באים בריצה, והעיוור באמצע.', 'I saw seven or eight men coming at a run, and the blind man in the middle.')),
  P(('העיוור צעק: תשברו את הדלת!', 'The blind man shouted: break the door!'),
    ('הם שברו את הדלת, נכנסו, ושמענו את הקולות שלהם מבפנים.', 'They broke the door, went in, and we heard their voices from inside.'),
    ('אחד צעק: בילי מת!', 'One shouted: Billy is dead!'),
    ('העיוור צעק: תחפשו עליו! ואז תעלו לארגז!', 'The blind man shouted: search him! And go up to the chest!'),
    ('ואחרי רגע אחד צעק מהחלון: מישהו פתח את הארגז לפנינו!', 'And a moment later one shouted from the window: someone opened the chest before us!'),
    ('העיוור אמר: הכסף שם?', 'The blind man said: is the money there?'),
    ('הוא אמר: הכסף שם, אבל הניירות של פלינט לא.', 'He said: the money is there, but Flint’s papers are not.'),
    ('העיוור צעק: הילד! הילד לקח אותם! תחפשו אותו!', 'The blind man screamed: the boy! The boy took them! Look for him!')),
  P(('הם התחילו לחפש בכל מקום, ולשבור הכול.', 'They began searching everywhere, and breaking everything.'),
    ('ואני מתחת לגשר, לא נושם.', 'And I under the bridge, not breathing.'),
    ('ואז שמענו שריקה מהגבעה, פעם, ופעמיים.', 'And then we heard a whistle from the hill, once, and twice.'),
    ('אחד אמר: זאת האזהרה! חייבים לברוח!', 'One said: that is the alarm! We must run!'),
    ('העיוור אמר: לא בורחים! הילד קרוב! תחפשו!', 'The blind man said: no running! The boy is close! Search!'),
    ('אבל האנשים לא שמעו לו, הם רצו כל אחד לכיוון אחר.', 'But the men did not listen to him, they ran each in another direction.'),
    ('והעיוור נשאר לבד באמצע הדרך, מכה במקל שלו וצועק עליהם.', 'And the blind man was left alone in the middle of the road, striking with his stick and shouting at them.')),
  P(('וברגע הזה שמענו סוסים באים מהגבעה.', 'And in that moment we heard horses coming from the hill.'),
    ('אלה היו אנשי המשטרה, שבאו כי מישהו מהכפר קרא להם.', 'They were the customs men, who came because someone from the village had called them.'),
    ('העיוור שמע את הסוסים, נבהל, ורץ לכיוון שגוי.', 'The blind man heard the horses, panicked, and ran the wrong way.'),
    ('הוא נפל מתחת לסוס הראשון, ולא קם.', 'He fell under the first horse, and did not get up.'),
    ('יצאתי מתחת לגשר, וקראתי לאנשי המשטרה.', 'I came out from under the bridge, and called the customs men.'),
    ('אמרתי: הניירות אצלי, אני חייב להביא אותם לרופא ליבסי.', 'I said: the papers are with me, I must bring them to Doctor Livesey.'),
    ('ועליתי על הסוס מאחורי אחד מהם, ורכבנו בלילה.', 'And I got on the horse behind one of them, and we rode through the night.'))]),

 ('The Captain’s Papers', 'הניירות של המלח', [
  P(('הרופא לא היה בבית שלו, הוא היה אצל האדון טרלוני, בבית הגדול.', 'The doctor was not at his house, he was with Squire Trelawney, at the big house.'),
    ('טרלוני היה איש גבוה ועשיר, עם קול חזק, והוא אהב מסעות.', 'Trelawney was a tall, rich man, with a loud voice, and he loved adventures.'),
    ('כשנכנסתי, הם ישבו ליד האש, ולפניהם אוכל.', 'When I came in, they sat by the fire, and before them food.'),
    ('סיפרתי להם הכול מההתחלה.', 'I told them everything from the beginning.'),
    ('ושמתי את החבילה על השולחן.', 'And I put the bundle on the table.')),
  P(('הרופא אמר: פלינט? שמעת עליו?', 'The doctor said: Flint? Have you heard of him?'),
    ('טרלוני אמר: שמעתי עליו? הוא היה שודד הים הכי מסוכן בעולם!', 'Trelawney said: heard of him? He was the most dangerous pirate in the world!'),
    ('וכולם יודעים שהוא קבר מטמון באיזה מקום.', 'And everyone knows he buried a treasure somewhere.'),
    ('אם הניירות האלה אומרים איפה, רופא, אני מכין ספינה מחר.', 'If these papers say where, doctor, I prepare a ship tomorrow.'),
    ('הרופא אמר: קודם נפתח אותם.', 'The doctor said: first let us open them.'),
    ('והוא פתח את החבילה עם הסכין שלו.', 'And he opened the bundle with his knife.')),
  P(('היו בה מחברת ונייר סגור בחותם.', 'In it were a notebook and a paper closed with a seal.'),
    ('המחברת הייתה חשבונות: תאריכים, סכומים ושמות של ספינות.', 'The notebook was accounts: dates, sums and names of ships.'),
    ('וליד כל סכום, צלב קטן.', 'And beside every sum, a small cross.'),
    ('הרופא אמר: כל צלב הוא ספינה שהם הטביעו, וכל סכום הוא החלק שלו.', 'The doctor said: every cross is a ship they sank, and every sum is his share.'),
    ('ואז הוא פתח את הנייר החתום.', 'And then he opened the sealed paper.'),
    ('זאת הייתה מפה של אי.', 'It was a map of an island.')),
  P(('האי היה באורך תשעה מיל, והיו בו שלוש גבעות.', 'The island was nine miles long, and there were three hills on it.'),
    ('ועליו שלושה צלבים בדיו אדומה, וליד אחד כתוב: המטמון כאן.', 'And on it three crosses in red ink, and beside one written: the treasure here.'),
    ('ומתחת למפה הוראות בכתב היד של פלינט.', 'And under the map instructions in Flint’s handwriting.'),
    ('טרלוני קפץ ואמר: מחר אני נוסע לבריסטול!', 'Trelawney jumped up and said: tomorrow I go to Bristol!'),
    ('בעוד עשרה ימים תהיה לנו ספינה, ואחר כך נצא כולנו.', 'In ten days we will have a ship, and then we all set out.'),
    ("אתה, רופא, ואני, וג'ים בתור נער הספינה.", 'You, doctor, and I, and Jim as the ship’s boy.'),
    ('הרופא אמר: אני בא איתך, אבל בתנאי אחד.', 'The doctor said: I come with you, but on one condition.'),
    ('אל תספר לאף אחד על המפה, אף מילה.', 'Do not tell anyone about the map, not a word.'),
    ('טרלוני אמר: אני? אני קבר!', 'Trelawney said: me? I am a grave!'),
    ('והרופא צחק, כי הוא הכיר אותו.', 'And the doctor laughed, because he knew him.'))]),

 ('To Bristol', 'לבריסטול', [
  P(('עשרת הימים נהיו שבועות, והרופא נסע ללונדון.', 'The ten days became weeks, and the doctor went to London.'),
    ('ואני נשארתי בבית הגדול, וחלמתי על האי.', 'And I stayed at the big house, and dreamed about the island.'),
    ('פתחתי את המפה כל יום, והלכתי עליה עם האצבע.', 'I opened the map every day, and walked over it with my finger.'),
    ('ואז הגיע מכתב מטרלוני מבריסטול.', 'And then a letter came from Trelawney from Bristol.')),
  P(('הוא כתב: הספינה מוכנה! קוראים לה היספניולה, והיא הספינה הכי יפה בנמל.', 'He wrote: the ship is ready! She is called the Hispaniola, and she is the finest ship in the harbour.'),
    ('קניתי אותה במחיר טוב, וכולם מדברים על המסע שלנו.', 'I bought her at a good price, and everyone is talking about our voyage.'),
    ('הוא כתב גם: היה קשה למצוא מלחים, אבל המזל עזר לי.', 'He also wrote: it was hard to find sailors, but luck helped me.'),
    ("פגשתי בנמל איש עם רגל אחת, קוראים לו ג'ון סילבר.", 'I met in the harbour a man with one leg, his name is John Silver.'),
    ('הוא היה טבח בספינות, ואיבד את הרגל בשירות המולדת.', 'He was a ship’s cook, and lost his leg in the service of his country.'),
    ('והוא מצא לי את כל הצוות, אנשים שמכירים את הים.', 'And he found me the whole crew, men who know the sea.'),
    ("בוא, ג'ים, בוא מהר!", 'Come, Jim, come quickly!')),
  P(('קראתי את המכתב פעמיים, רגל אחת.', 'I read the letter twice, one leg.'),
    ('נזכרתי במפקד, בפחד שלו, ובחלומות שלי.', 'I remembered the Captain, his fear, and my dreams.'),
    ('אבל אמרתי לעצמי: יש הרבה מלחים עם רגל אחת.', 'But I said to myself: there are many sailors with one leg.'),
    ('וטרלוני אמר שהוא איש טוב.', 'And Trelawney said he is a good man.'),
    ('למחרת הלכתי להיפרד מאימא שלי בפונדק.', 'The next day I went to say goodbye to my mother at the inn.'),
    ('היא פתחה אותו שוב, והיה שם ילד חדש שעוזר לה.', 'She had opened it again, and there was a new boy helping her.'),
    ('ובכיתי, כי ראיתי ילד אחר במקום שלי.', 'And I cried, because I saw another boy in my place.')),
  P(('נסעתי בכרכרה כל הלילה.', 'I travelled by coach all night.'),
    ('וכשהתעוררתי, היינו בבריסטול, והרחתי את הים ואת הזפת.', 'And when I woke, we were in Bristol, and I smelled the sea and the tar.'),
    ('טרלוני היה לבוש כמו מפקד, ועמד לפני מלון בנמל.', 'Trelawney was dressed like a captain, and stood in front of an inn on the harbour.'),
    ('הוא אמר: הגעת! והרופא הגיע אתמול! מחר אנחנו מפליגים!', 'He said: you have arrived! And the doctor arrived yesterday! Tomorrow we sail!'),
    ("והוא נתן לי פתק, ואמר: לך תמסור אותו לג'ון סילבר, בפונדק המשקפת.", 'And he gave me a note, and said: go and give it to John Silver, at the Spyglass inn.'))]),

 ('The Sign of the Spy-glass', 'הפונדק של סילבר', [
  P(('הפונדק היה בית קפה קטן בנמל, ועל הדלת שלו משקפת גדולה.', 'The inn was a small tavern in the harbour, and over its door a big spyglass.'),
    ('הוא היה מלא מלחים, ורעש וצחוק ועשן.', 'It was full of sailors, and noise and laughter and smoke.'),
    ('עמדתי בדלת, ופחדתי להיכנס.', 'I stood at the door, and was afraid to go in.'),
    ('ואז ראיתי אותו.', 'And then I saw him.'),
    ('הוא היה גבוה וחזק, עם פנים גדולות ומחייכות, ורגל שמאל חתוכה מהירך.', 'He was tall and strong, with a big smiling face, and his left leg cut off at the thigh.'),
    ('והוא זז על המקל שלו בין השולחנות כמו ציפור.', 'And he moved on his crutch between the tables like a bird.')),
  P(('מהמבט הראשון הבנתי שזה לא המפקד.', 'From the first look I understood that this was not the Captain.'),
    ('המפקד היה מלוכלך ועצוב ומפחיד.', 'The Captain had been dirty and sad and frightening.'),
    ('וזה נקי, וצוחק, והקול שלו נעים.', 'And this one is clean, and laughing, and his voice is pleasant.'),
    ('אמרתי: אתה מר סילבר?', 'I said: are you Mr. Silver?'),
    ("הוא אמר: זה אני, ילד, ואתה בטח ג'ים, נער הספינה החדש!", 'He said: that is me, boy, and you must be Jim, the new ship’s boy!'),
    ('והוא הושיט את היד הגדולה שלו ולחץ את ידי.', 'And he held out his big hand and shook mine.')),
  P(('ובאותו רגע אחד האורחים קם ורץ לדלת.', 'And in that moment one of the customers got up and ran for the door.'),
    ('הכרתי אותו מיד: הכלב השחור.', 'I knew him at once: Black Dog.'),
    ('צעקתי: תתפסו אותו! זה הכלב השחור!', 'I shouted: catch him! That is Black Dog!'),
    ('סילבר צעק: מי? איזה כלב? הארי, רוץ אחריו!', 'Silver shouted: who? What dog? Harry, run after him!'),
    ('ואחד קם ורץ אחריו, אבל חזר בלי כלום.', 'And one got up and ran after him, but came back with nothing.'),
    ('סילבר אמר: הוא ברח, בפונדק שלי! אני אספר לטרלוני בעצמי.', 'Silver said: he got away, in my inn! I will tell Trelawney myself.'),
    ('והוא דיבר ודיבר על הכלב השחור ועל העוול שנעשה.', 'And he talked and talked about Black Dog and the wrong that had been done.')),
  P(('יצאנו יחד לנמל, והוא סיפר לי על הספינות.', 'We went out together to the harbour, and he told me about the ships.'),
    ('הוא הכיר כל ספינה, כל דגל, וכל סיפור.', 'He knew every ship, every flag, and every story.'),
    ('והוא צחק, והצחיק אותי.', 'And he laughed, and made me laugh.'),
    ('אמרתי בלב: זה החבר הכי טוב לים בעולם.', 'I said to myself: this is the best shipmate in the world.'),
    ('וכשהגענו לטרלוני, הוא אמר: אני וג\'ים ראינו מה קרה.', 'And when we reached Trelawney, he said: Jim and I saw what happened.'),
    ('והוא סיפר את הסיפור כמו שהיה, בדיוק.', 'And he told the story as it was, exactly.'),
    ('והרופא אמר אחרי שהוא יצא: האיש הזה צודק.', 'And the doctor said after he left: this man is right.'),
    ("טרלוני אמר: אמרתי לך, ג'ון הוא אוצר.", 'Trelawney said: I told you, John is a treasure.'))]),

 ('Powder and Arms', 'נשק וכלים', [
  P(('עלינו על הספינה בלילה, והיא באמת הייתה יפה.', 'We went aboard at night, and she really was beautiful.'),
    ('ועל הסיפון חיכה לנו המפקד של הספינה, ושמו סמולט.', 'And on the deck the ship’s captain waited for us, and his name was Smollett.'),
    ('הוא היה איש רציני, והפנים שלו לא צחקו.', 'He was a serious man, and his face did not laugh.'),
    ('הוא אמר: אדון טרלוני, אני רוצה לדבר איתך בתא, לפני הרופא.', 'He said: Mr. Trelawney, I want to speak with you in the cabin, in front of the doctor.'),
    ('ירדנו, וסמולט אמר: אני לא מרוצה מהמסע הזה.', 'We went down, and Smollett said: I am not happy with this voyage.')),
  P(('טרלוני אמר: ולמה?', 'Trelawney said: and why?'),
    ('המפקד אמר: כי אני לא יודע לאן אנחנו הולכים.', 'The captain said: because I do not know where we are going.'),
    ('וכל מלח בנמל יודע יותר ממני.', 'And every sailor in the harbour knows more than I do.'),
    ('אומרים שיש מפה, ומטמון, ושהמפה אצלך.', 'They say there is a map, and a treasure, and that the map is with you.'),
    ('הפנים של טרלוני נהיו אדומות והוא אמר: לא סיפרתי לאף אחד!', 'Trelawney’s face went red and he said: I told no one!'),
    ('הרופא אמר בשקט: מישהו סיפר.', 'The doctor said quietly: someone told.'),
    ('המפקד אמר: ואחר כך, הצוות, אני לא בחרתי אותם.', 'The captain said: and then, the crew, I did not choose them.'),
    ('והעוזר הראשון שלי שותה, והמלחים לא מכבדים אותו.', 'And my first mate drinks, and the sailors do not respect him.')),
  P(('טרלוני אמר: אז מה אתה רוצה?', 'Trelawney said: so what do you want?'),
    ('המפקד אמר: שלושה דברים.', 'The captain said: three things.'),
    ('אבק השרפה והנשק יהיו מתחת לתא שלנו, לא בקדמת הספינה.', 'The powder and the arms go under our cabin, not in the bow.'),
    ('האנשים שלך, שאתה הבאת בעצמך, יישנו לידנו.', 'Your men, whom you brought yourself, sleep beside us.'),
    ('ואת המפה אף אחד לא רואה, גם לא אני.', 'And the map no one sees, not even I.'),
    ('הרופא אמר: כלומר אתה מפחד ממרד.', 'The doctor said: that is, you fear a mutiny.'),
    ('המפקד אמר: אני לא אומר כלום, אני אומר תהיו מוכנים.', 'The captain said: I say nothing, I say be ready.')),
  P(('טרלוני כעס, אבל הרופא הסכים להכול.', 'Trelawney was angry, but the doctor agreed to everything.'),
    ('ועבדנו כולנו כל הלילה, והעברנו את החביות ואת הרובים.', 'And we all worked all night, and moved the barrels and the guns.'),
    ("וג'ון סילבר בא מהנמל, וכשראה, אמר: מה זה?", 'And John Silver came from the harbour, and when he saw, said: what is this?'),
    ('המפקד אמר: הפקודות שלי, לך למטבח.', 'The captain said: my orders, go to the galley.'),
    ('סילבר אמר: כן, מפקד, והלך.', 'Silver said: yes, captain, and went.'),
    ('ואחר כך טרלוני לחש: אני לא אוהב את המפקד הזה.', 'And afterwards Trelawney whispered: I do not like this captain.'),
    ('והרופא אמר: אני אוהב אותו, כי הוא לא מנסה למצוא חן בעינינו.', 'And the doctor said: I like him, because he is not trying to please us.'))]),

 ('The Voyage', 'המסע', [
  P(('הפלגנו עם השחר, וכל הנמל נפרד מאיתנו.', 'We sailed at dawn, and the whole harbour saw us off.'),
    ('סילבר עמד על הסיפון והתחיל את השיר: חמישה עשר אנשים על הארגז של המת.', 'Silver stood on deck and started the song: fifteen men on the dead man’s chest.'),
    ('וכל המלחים ענו: יו הו הו ובקבוק רום.', 'And all the sailors answered: yo ho ho and a bottle of rum.'),
    ('ואני עמדתי בקדמת הספינה, וראיתי את היבשה נהיית רחוקה.', 'And I stood at the bow, and saw the land growing distant.'),
    ('וחשבתי על הפונדק, על אימא שלי, ועל המפקד המת ששר את אותו השיר.', 'And I thought about the inn, about my mother, and about the dead Captain who sang the same song.')),
  P(('המסע היה ארוך, אבל לא קרה בו הרבה, חוץ מדבר אחד.', 'The voyage was long, but not much happened on it, except one thing.'),
    ('העוזר הראשון של המפקד היה שיכור כל הזמן.', 'The captain’s first mate was drunk all the time.'),
    ('אף אחד לא ידע מאיפה הוא מביא את המשקה, כי המפקד סגר את כל המשקאות.', 'No one knew where he got the drink, because the captain had locked up all the drink.'),
    ('ובלילה אחד של סופה הוא נעלם.', 'And on one stormy night he vanished.'),
    ('המפקד אמר: הוא נפל לים, אף אחד לא יתגעגע אליו.', 'The captain said: he fell into the sea, no one will miss him.'),
    ('והמלח הגדול לקח את המקום שלו.', 'And the big sailor took his place.')),
  P(('וסילבר היה המלך של הספינה.', 'And Silver was the king of the ship.'),
    ('הוא בישל, שר, סיפר, והמלחים אהבו אותו והקשיבו לו.', 'He cooked, sang, told stories, and the sailors loved him and listened to him.'),
    ('והיה לו תוכי, שקראו לו מפקד פלינט, שצעק: מטבעות זהב! מטבעות זהב!', 'And he had a parrot, called Captain Flint, that screeched: pieces of eight! Pieces of eight!'),
    ('הוא אמר לי: הציפור הזאת בת מאתיים שנה, והיא ראתה את כל הרע בעולם.', 'He told me: this bird is two hundred years old, and she has seen all the evil in the world.'),
    ('ואני ישבתי במטבח שעות, והוא סיפר לי על הימים.', 'And I sat in the galley for hours, and he told me about the seas.'),
    ("הוא אמר: אתה חכם, ג'ים, אתה דומה לי כשהייתי צעיר.", 'He said: you are clever, Jim, you are like me when I was young.'),
    ('ושמחתי.', 'And I was glad.')),
  P(('המפקד סמולט היה שקט, ולא אהב בלגן.', 'Captain Smollett was quiet, and did not like disorder.'),
    ('וטרלוני נתן למלחים תפוחים ומשקה בכל הזדמנות.', 'And Trelawney gave the sailors apples and drink at every opportunity.'),
    ('הייתה חבית תפוחים פתוחה על הסיפון, למי שרוצה.', 'There was an open barrel of apples on deck, for whoever wanted.'),
    ('ובלילה אחד, יום לפני שהגענו, הלכתי לקחת תפוח.', 'And one night, a day before we arrived, I went to take an apple.'),
    ('החבית הייתה כמעט ריקה, אז נכנסתי לתוכה כדי להגיע לתפוח האחרון.', 'The barrel was almost empty, so I got inside it to reach the last apple.'),
    ('וישבתי בפנים בחושך, ונרדמתי קצת.', 'And I sat inside in the dark, and dozed a little.'),
    ('והתעוררתי מקול, מישהו ישב ליד החבית והתחיל לדבר.', 'And I woke to a voice, someone had sat down beside the barrel and begun to talk.'))]),

 ('What I Heard in the Apple Barrel', 'מה שמעתי בחבית', [
  P(('זה היה הקול של סילבר.', 'It was Silver’s voice.'),
    ('אבל לא הקול שאני מכיר, קול קר, בלי צחוק.', 'But not the voice I knew, a cold voice, without laughter.'),
    ('הוא דיבר עם מלח צעיר.', 'He was talking with a young sailor.'),
    ('סילבר אמר: אני הייתי עם פלינט, אני הייתי האחראי על אבק השרפה שלו.', 'Silver said: I was with Flint, I was in charge of his powder.'),
    ('והעיוור היה איתנו, ובילי בונס.', 'And the blind man was with us, and Billy Bones.'),
    ('כולם מתו עניים, ולי יש כסף בבנק.', 'They all died poor, and I have money in the bank.'),
    ('כי אני חכם.', 'Because I am clever.')),
  P(('המלח הצעיר אמר: ואני? מה יקרה איתי?', 'The young sailor said: and me? What happens with me?'),
    ('סילבר אמר: אתה איתנו, אדוני המזל, ככה אנחנו קוראים לעצמנו.', 'Silver said: you are with us, gentlemen of fortune, that is what we call ourselves.'),
    ('וכשנגיע לאי, ואז נוציא את המטמון, כל אחד ייקח את החלק שלו.', 'And when we reach the island, and dig up the treasure, each one takes his share.'),
    ('הצעיר אמר: והמפקד? וטרלוני? והרופא?', 'The young one said: and the captain? And Trelawney? And the doctor?'),
    ('סילבר אמר: שהם יביאו אותנו, אנחנו צריכים אותם כדי להוביל את הספינה.', 'Silver said: let them bring us there, we need them to sail the ship.'),
    ('ואחר כך, כשהמטמון יהיה על הספינה, נראה.', 'And then, when the treasure is on the ship, we will see.'),
    ('הצעיר אמר: כלומר נהרוג אותם?', 'The young one said: that is, we kill them?'),
    ('סילבר אמר: מתים לא נושכים.', 'Silver said: dead men do not bite.')),
  P(('הייתי בתוך החבית, לא נשמתי, והלב שלי דפק כמו תוף.', 'I was inside the barrel, not breathing, and my heart beat like a drum.'),
    ('זה האיש שאהבתי.', 'This was the man I had loved.'),
    ('זה שאמר שאני דומה לו.', 'The one who said I was like him.'),
    ('ובא שלישי, ישראל הנדס, ההגאי.', 'And a third came, Israel Hands, the coxswain.'),
    ("הנדס אמר: ג'ון, עד מתי נחכה? נמאס לי מהמפקד.", 'Hands said: John, how long do we wait? I am sick of the captain.'),
    ('סילבר אמר: עד שאני אגיד, הרגע האחרון האפשרי.', 'Silver said: until I say, the last possible moment.'),
    ("הנדס אמר: והילד? ג'ים?", 'Hands said: and the boy? Jim?'),
    ('סילבר אמר: אני אוהב את הילד, אבל כשיגיע הזמן שלו, הוא ייקח את החלק שלו כמו כולם.', 'Silver said: I like the boy, but when his time comes, he takes his share like everyone.')),
  P(('סילבר אמר: יאללה, תביא לי תפוח מהחבית.', 'Silver said: come on, bring me an apple from the barrel.'),
    ('ואני אמרתי: זהו, נגמרתי.', 'And I said: that is it, I am finished.'),
    ('אבל הנדס אמר: תפוחים? בוא נשתה רום.', 'But Hands said: apples? Let us drink rum.'),
    ('והצעיר הלך להביא רום, והם ישבו ושתו.', 'And the young one went to bring rum, and they sat and drank.'),
    ('ובאותו רגע מישהו צעק מלמעלה: יבשה! יבשה!', 'And in that moment someone shouted from above: land! Land!'),
    ('וכולם רצו לקדמת הספינה, ואני יצאתי מהחבית והתערבבתי ביניהם.', 'And everyone ran to the bow, and I got out of the barrel and mixed in among them.'),
    ('וראיתי את האי, בפעם הראשונה, לאור הירח.', 'And I saw the island, for the first time, by moonlight.'),
    ('שלוש גבעות, וערפל, ועצים שחורים.', 'Three hills, and mist, and black trees.'))]),

 ('Council of War', 'ישיבה בלילה', [
  P(('המפקד סמולט פתח את המפה, אבל עותק בלי הצלבים האדומים.', 'Captain Smollett opened the map, but a copy without the red crosses.'),
    ('והוא שאל את סילבר: אתה מכיר את האי הזה?', 'And he asked Silver: do you know this island?'),
    ('סילבר אמר: בטח, מפקד, עברתי לידו פעם, עם ספינת סוחר.', 'Silver said: of course, captain, I passed it once, with a merchant ship.'),
    ('והוא סיפר על המעגן, על המים המתוקים, ועל מזג האוויר.', 'And he told about the anchorage, the fresh water, and the weather.'),
    ('והקול שלו היה חם וצוחק, כמו תמיד.', 'And his voice was warm and laughing, as always.'),
    ('ואני עמדתי לידו, ורציתי לברוח מהריח של השקר.', 'And I stood beside him, and wanted to flee from the smell of the lie.')),
  P(('כשהסיפון התרוקן, הלכתי לרופא ואמרתי לו: אני חייב לדבר איתך בתא.', 'When the deck emptied, I went to the doctor and told him: I must speak with you in the cabin.'),
    ('ירדנו, וטרלוני והמפקד איתנו.', 'We went down, and Trelawney and the captain with us.'),
    ('וסיפרתי כל מילה ששמעתי בחבית.', 'And I told every word I had heard in the barrel.'),
    ('כשסיימתי, אף אחד לא דיבר.', 'When I finished, no one spoke.'),
    ('ואז המפקד אמר לטרלוני: צדקת, אני טעיתי.', 'And then the captain said to Trelawney: you were right, I was wrong.'),
    ('טרלוני אמר: לא, אתה זה שצדק, ואני הטיפש.', 'Trelawney said: no, you are the one who was right, and I the fool.'),
    ('והטבח הזה, אני זה שהביא אותו.', 'And this cook, I am the one who brought him.')),
  P(('המפקד אמר: בואו נספור.', 'The captain said: let us count.'),
    ('אנחנו שבעה: שלושה מכם, אני, ושלושה מהאנשים של טרלוני.', 'We are seven: three of you, myself, and three of Trelawney’s men.'),
    ('והם תשעה עשר.', 'And they are nineteen.'),
    ('אבל בטח לא כולם איתו, יש אנשים שמהססים.', 'But surely not all are with him, there are men who hesitate.'),
    ('הרופא אמר: ומה נעשה?', 'The doctor said: and what do we do?'),
    ('המפקד אמר: נמשיך כמו שאנחנו.', 'The captain said: we go on as we are.'),
    ('אם נחזור עכשיו, הם יתקפו מיד, אם נמשיך, הם יחכו למטמון.', 'If we turn back now, they attack at once, if we go on, they wait for the treasure.'),
    ('והזמן איתנו.', 'And time is on our side.')),
  P(("הרופא אמר: וג'ים?", 'The doctor said: and Jim?'),
    ("המפקד אמר: ג'ים הוא הכי חשוב בינינו.", 'The captain said: Jim is the most important one among us.'),
    ('המלחים לא שמים לב אליו, והוא שומע הכול.', 'The sailors pay him no attention, and he hears everything.'),
    ("ג'ים, תישאר עם סילבר כמו קודם, והעיניים פתוחות.", 'Jim, stay with Silver as before, and keep your eyes open.'),
    ('אמרתי: כן, מפקד.', 'I said: yes, captain.'),
    ('אבל בלב פחדתי מאוד.', 'But in my heart I was very afraid.'),
    ('שבעה נגד תשעה עשר, ואני אחד מהשבעה.', 'Seven against nineteen, and I one of the seven.'))]),

 ('The Island', 'האי', [
  P(('בבוקר עמדנו מול האי, והוא היה אחר מאשר בלילה.', 'In the morning we lay off the island, and it was different from at night.'),
    ('עצים אפורים, סלע צהוב, וגבעות בצורה מוזרה.', 'Grey trees, yellow rock, and hills of a strange shape.'),
    ('הגבעה הכי גבוהה הייתה כמו משקפת, ולכן קראו לה גבעת המשקפת.', 'The highest hill was like a spyglass, and that is why they called it Spyglass Hill.'),
    ('לא הייתה רוח, הספינה עמדה, והשמש חמה.', 'There was no wind, the ship stood still, and the sun was hot.'),
    ('ומהרגע הראשון שנאתי את האי.', 'And from the first moment I hated the island.')),
  P(('המלחים נהיו כועסים.', 'The sailors grew edgy.'),
    ('הם לא שמעו לפקודות, דיברו בקול רם, והסתכלו על החוף.', 'They did not obey orders, talked loudly, and looked at the shore.'),
    ('המפקד ראה את הסכנה, ואמר לטרלוני: אם הם יישארו על הספינה, המרד יהיה היום.', 'The captain saw the danger, and said to Trelawney: if they stay on the ship, the mutiny will be today.'),
    ('והוא החליט לתת להם לרדת לחוף אחרי הצהריים.', 'And he decided to let them go ashore in the afternoon.'),
    ('הוא אמר: שירוצו באי כמו ילדים, וסילבר ילך איתם כדי להרגיע אותם.', 'He said: let them run about the island like children, and Silver goes with them to calm them.'),
    ('כי גם סילבר לא רצה את המרד לפני המטמון.', 'Because Silver too did not want the mutiny before the treasure.')),
  P(('שלושה עשר מלחים ירדו בשתי סירות, וסילבר איתם.', 'Thirteen sailors went down in two boats, and Silver with them.'),
    ('ושישה נשארו על הספינה, כולם מהאנשים שלו.', 'And six stayed on the ship, all of them his men.'),
    ('ואני, אני לא יודע למה, עשיתי את הדבר הכי טיפשי בחיים שלי.', 'And I, I do not know why, did the most foolish thing in my life.'),
    ('קפצתי לסירה האחרונה, בלי שאף אחד ראה אותי.', 'I jumped into the last boat, without anyone seeing me.'),
    ('אמרתי: אני רוצה לראות את האי.', 'I said: I want to see the island.'),
    ("כשהגענו, סילבר צעק: ג'ים! ג'ים!", 'When we landed, Silver shouted: Jim! Jim!'),
    ('אבל אני כבר קפצתי, נכנסתי בין העצים ורצתי.', 'But I had already jumped, gone in among the trees and run.'))]),

 ('Ashore', 'יורדים לחוף', [
  P(('רצתי עד שכבר לא שמעתי את הקול שלהם.', 'I ran until I could no longer hear their voices.'),
    ('ועצרתי ביער, ובפעם הראשונה בחיים שלי הייתי לבד במקום חדש.', 'And I stopped in a wood, and for the first time in my life I was alone in a new place.'),
    ('עצים שאני לא מכיר, ציפורים שאני לא מכיר, ונחש קטן הרים את הראש.', 'Trees I did not know, birds I did not know, and a small snake raised its head.'),
    ('ואז הגעתי לביצה, ומאחורי העצים שמעתי קולות.', 'And then I reached a marsh, and from behind the trees I heard voices.'),
    ('הקול של סילבר, וקול אחר, של מלח שקראו לו טום.', 'Silver’s voice, and another voice, of a sailor they called Tom.'),
    ('זחלתי והתקרבתי, והתחבאתי מאחורי עץ.', 'I crawled and came closer, and hid behind a tree.')),
  P(('סילבר דיבר בקול החם שלו: טום, אתה איש טוב, ואני אוהב אותך.', 'Silver was speaking in his warm voice: Tom, you are a good man, and I like you.'),
    ('בוא איתנו, כל השאר איתנו.', 'Come with us, all the others are with us.'),
    ("טום אמר: ג'ון, גם אני אוהב אותך, אבל אני לא בוגד.", 'Tom said: John, I like you too, but I am no traitor.'),
    ('אני מת לפני שאני בוגד במפקד.', 'I die before I betray the captain.'),
    ('ובאותו רגע, מרחוק, שמענו צעקה.', 'And in that moment, from afar, we heard a scream.'),
    ('צעקה אחת, ארוכה, ואחר כך כלום.', 'One scream, long, and then nothing.'),
    ('טום אמר: מה זה היה?', 'Tom said: what was that?'),
    ('סילבר אמר בשקט: זה? זה אלן, אני חושב.', 'Silver said calmly: that? That is Alan, I think.'),
    ('אלן היה מלח אחר, שסירב להצטרף אליהם.', 'Alan was another sailor, who had refused to join them.')),
  P(('טום הבין.', 'Tom understood.'),
    ("הוא אמר: אלן! שינוח בשלום, ואתה, ג'ון סילבר, אתה שטן.", 'He said: Alan! May he rest in peace, and you, John Silver, you are a devil.'),
    ('תהרוג אותי אם אתה יכול, אני הולך.', 'Kill me if you can, I am going.'),
    ('והוא הפנה את הגב והלך.', 'And he turned his back and walked away.'),
    ('סילבר תפס את המקל שלו, וזרק אותו בכל הכוח.', 'Silver seized his crutch, and threw it with all his strength.'),
    ('הוא פגע בגב של טום, וטום נפל.', 'It hit Tom in the back, and Tom fell.'),
    ('וסילבר קפץ עליו על רגל אחת, כמו קוף, ודקר אותו פעמיים.', 'And Silver leapt on him on one leg, like a monkey, and stabbed him twice.')),
  P(('אני לא יודע איך לא צעקתי.', 'I do not know how I did not scream.'),
    ('העולם הסתובב סביבי, והעצים התחילו להסתובב.', 'The world spun around me, and the trees began to turn.'),
    ('וכשחזרתי לראות, סילבר עמד, וניקה את הסכין שלו על העשב.', 'And when I could see again, Silver was standing, and wiping his knife on the grass.'),
    ('ואז הוא שרק במשרוקית, וידעתי שהוא קורא לאחרים.', 'And then he blew a whistle, and I knew he was calling the others.'),
    ('רצתי, רצתי בלי לדעת לאן.', 'I ran, I ran without knowing where.'),
    ('וכל הזמן חשבתי: אני מת, סילבר יודע ששמעתי.', 'And all the time I thought: I am dead, Silver knows I heard.'),
    ('ופתאום משהו עמד לפניי מאחורי עץ.', 'And suddenly something stood before me from behind a tree.'),
    ('לא איש ולא חיה, משהו שזז מהר, ונעלם.', 'Not a man and not an animal, something that moved fast, and vanished.'))]),

 ('The Man of the Island', 'האיש של האי', [
  P(('עמדתי במקום, ולא ידעתי לאן לרוץ.', 'I stood where I was, and did not know where to run.'),
    ('מאחוריי הרוצחים, ולפניי הדבר הזה.', 'Behind me the murderers, and before me this thing.'),
    ('ואז הוא יצא מאחורי העץ, ירד על הברכיים, והושיט את הידיים.', 'And then it came out from behind the tree, dropped to its knees, and held out its hands.'),
    ('זה היה איש.', 'It was a man.'),
    ('השיער שלו ארוך ושחור, העור שלו שרוף מהשמש, והבגדים שלו חתיכות בד קשורות.', 'His hair long and black, his skin burned by the sun, and his clothes pieces of cloth tied together.'),
    ('והעיניים שלו היו מבריקות, כמו של מישהו שלא ראה בן אדם שנים.', 'And his eyes shone, like someone who had not seen a human being for years.')),
  P(('הוא אמר: מי אתה?', 'He said: who are you?'),
    ("אמרתי: ג'ים.", 'I said: Jim.'),
    ("הוא אמר: ג'ים, ג'ים, אני בן גאן, אני בן גאן המסכן.", 'He said: Jim, Jim, I am Ben Gunn, I am poor Ben Gunn.'),
    ('שלוש שנים לא דיברתי עם אף אחד.', 'For three years I have not spoken with anyone.'),
    ('אמרתי: שלוש שנים? הספינה שלך טבעה?', 'I said: three years? Did your ship sink?'),
    ('הוא אמר: לא, השאירו אותי כאן, ככה עושים לבוגד.', 'He said: no, they left me here, that is what they do to a traitor.'),
    ('והוא דיבר על גבינה, הוא אמר: אתה חולם על גבינה? אני חולם עליה כל לילה.', 'And he talked about cheese, he said: do you dream about cheese? I dream about it every night.')),
  P(('ואז הוא שאל אותי: זאת הספינה של פלינט?', 'And then he asked me: is that Flint’s ship?'),
    ('אמרתי: פלינט מת, אבל האנשים שלו איתנו על הספינה.', 'I said: Flint is dead, but his men are with us on the ship.'),
    ('הוא אמר: יש אחד עם רגל אחת?', 'He said: is there one with one leg?'),
    ('אמרתי: סילבר.', 'I said: Silver.'),
    ('בן גאן רעד כולו, ותפס את היד שלי.', 'Ben Gunn shook all over, and grabbed my hand.'),
    ('הוא אמר: אם סילבר שלח אותך, אני מת, אבל אתה לא מהאנשים שלו, נכון?', 'He said: if Silver sent you, I am dead, but you are not one of his men, right?'),
    ('וסיפרתי לו את כל הסיפור.', 'And I told him the whole story.'),
    ('הוא הקשיב, ואז צחק, ואמר: אני הייתי עם פלינט כשהוא קבר את המטמון.', 'He listened, and then laughed, and said: I was with Flint when he buried the treasure.')),
  P(('הוא אמר: הייתי בספינה אחרת, וחזרתי לחפש את המטמון עם האנשים שלי.', 'He said: I was on another ship, and came back to look for the treasure with my men.'),
    ('שנים עשר יום חיפשנו, ולא מצאנו, אז הם כעסו עליי, ועזבו אותי.', 'Twelve days we searched, and did not find, so they were angry at me, and left me.'),
    ('אבל אני בן גאן, ואני חכם.', 'But I am Ben Gunn, and I am clever.'),
    ('והוא קרץ לי, ואמר: לך תגיד לטרלוני: בן גאן רוצה לחזור הביתה.', 'And he winked at me, and said: go and tell Trelawney: Ben Gunn wants to go home.'),
    ('והוא רוצה חלק, ויש לו סירה קטנה שעשה בידיים שלו, מתחת לסלע הלבן.', 'And he wants a share, and he has a little boat he made with his own hands, under the white rock.'),
    ('וברגע הזה שמענו קול של תותח מהספינה.', 'And in that moment we heard the sound of a cannon from the ship.'),
    ('בן גאן אמר: המלחמה התחילה.', 'Ben Gunn said: the war has begun.'))]),

 ('The Ship Abandoned', 'עוזבים את הספינה', [
  P(('את החלק הזה של הסיפור הרופא סיפר לי אחר כך, כי אני לא הייתי שם.', 'This part of the story the doctor told me afterwards, because I was not there.'),
    ('כשהמלחים ירדו לאי, הרופא, טרלוני והמפקד ישבו וחשבו.', 'When the sailors went ashore, the doctor, Trelawney and the captain sat and thought.'),
    ('שישה מהאנשים של סילבר על הספינה, ואנחנו שישה עם הנשק.', 'Six of Silver’s men on the ship, and we six with the weapons.'),
    ('הרופא אמר: אני רוצה לרדת לחוף ולראות את המפה מול המקום.', 'The doctor said: I want to go ashore and see the map against the place.'),
    ('כי על המפה היה ציור של בית עץ, קרוב למים.', 'Because on the map was drawn a wooden building, close to the water.')),
  P(('הרופא ירד עם אחד מהאנשים של טרלוני.', 'The doctor went down with one of Trelawney’s men.'),
    ('והם מצאו את המבנה: בית עץ חזק, סביבו גדר של גזעים, ולידו מעיין.', 'And they found the building: a strong wooden house, around it a fence of trunks, and beside it a spring.'),
    ('הרופא אמר: כאן אפשר להחזיק מעמד חודשים.', 'The doctor said: here one could hold out for months.'),
    ('ובאותו רגע הם שמעו את הצעקה מרחוק, הצעקה של אלן.', 'And in that moment they heard the scream from afar, Alan’s scream.'),
    ("הרופא אמר: זהו, חוזרים לספינה, ג'ים באי, ושאלוהים יעזור לו.", 'The doctor said: that is it, back to the ship, Jim is on the island, and may God help him.')),
  P(('הם חזרו לספינה, והחליטו: עוזבים את הספינה, והולכים למבנה.', 'They went back to the ship, and decided: we leave the ship, and go to the building.'),
    ('כי על הספינה סילבר יחזור עם שלושה עשר אנשים, ואנחנו נפסיד.', 'Because on the ship Silver would return with thirteen men, and we would lose.'),
    ('הם העמיסו את הסירה באוכל, באבק שרפה וברובים, ונסעו פעם, וחזרו פעם.', 'They loaded the boat with food, powder and guns, and went once, and came back once.'),
    ('והשישה על הספינה הסתכלו, ולא ידעו מה לעשות.', 'And the six on the ship watched, and did not know what to do.'),
    ('ובנסיעה האחרונה המפקד עלה ועמד על הסיפון.', 'And on the last trip the captain came up and stood on the deck.'),
    ('הוא אמר: גריי, אני יודע שאתה איש טוב, אני נותן לך שלושים שניות.', 'He said: Gray, I know you are a good man, I give you thirty seconds.'),
    ('ואחרי רגע של שקט היה קול של קרב, וגריי בא בריצה, ועל הפנים שלו דם.', 'And after a moment of silence there was a sound of a fight, and Gray came running, his face wounded.'),
    ('הוא אמר: אני איתך, מפקד.', 'He said: I am with you, captain.')),
  P(('הם ירדו לסירה, שישה אנשים ואוכל ואבק שרפה.', 'They went down into the boat, six men and food and powder.'),
    ('והסירה הייתה כבדה, והמים הגיעו לקצה שלה.', 'And the boat was heavy, and the water reached its edge.'),
    ('והזרם משך אותם רחוק מהמבנה.', 'And the current pulled them away from the building.'),
    ('ואז המפקד אמר: התותח.', 'And then the captain said: the cannon.'),
    ('על הספינה היה תותח, והאנשים של סילבר סובבו אותו לכיוון שלהם.', 'On the ship was a cannon, and Silver’s men were turning it toward them.'),
    ('טרלוני הרים את הרובה שלו, ירה באיש שטען את התותח, ופגע בו.', 'Trelawney raised his gun, fired at the man loading the cannon, and hit him.'),
    ('אבל התותח ירה.', 'But the cannon fired.'),
    ('הכדור עבר מעל הראשים שלהם, והגל הפך את הסירה.', 'The ball passed over their heads, and the wave overturned the boat.'),
    ('והם עלו לחוף, רטובים, בלי חצי מהאוכל, ובלי חצי מאבק השרפה.', 'And they came up on the shore, wet, without half the food, and without half the powder.'))]),

 ('The Last Boat', 'הסירה האחרונה', [
  P(('הם יצאו מהמים ורצו למבנה, והקול מאחורי העצים התקרב.', 'They came out of the water and ran to the building, and the noise behind the trees drew nearer.'),
    ('האנשים של סילבר שמעו את התותח, והם באו.', 'Silver’s men had heard the cannon, and they were coming.'),
    ('המפקד אמר: טרלוני, אתה היורה הכי טוב, תישאר אחרון.', 'The captain said: Trelawney, you are the best shot, stay last.'),
    ('והם הגיעו לגדר, והרוצחים יצאו מהעצים.', 'And they reached the fence, and the murderers came out of the trees.'),
    ('הם היו שבעה, והמלח הגדול בראשם.', 'They were seven, and the big sailor at their head.')),
  P(('היה ירי משני הצדדים.', 'There was shooting from both sides.'),
    ('אחד מהרוצחים נפל, והאחרים ברחו לעצים.', 'One of the murderers fell, and the others fled into the trees.'),
    ('אבל לפני שברחו, כדור בא מאחור.', 'But before they fled, a bullet came from behind.'),
    ('והוא פגע במשרת הזקן של טרלוני.', 'And it hit Trelawney’s old servant.'),
    ('הם נשאו אותו לתוך המבנה, והוא ידע שהוא הולך למות.', 'They carried him into the building, and he knew he was going to die.'),
    ('הוא אמר לטרלוני: אני הולך, אדוני, תסלח לי אם טעיתי במשהו.', 'He said to Trelawney: I am going, sir, forgive me if I ever did anything wrong.'),
    ('וטרלוני בכה, ונישק את היד שלו.', 'And Trelawney wept, and kissed his hand.'),
    ('והמשרת מת אחרי זמן קצר.', 'And the servant died a little later.')),
  P(('המפקד הוציא מהכיס דגל אנגלי, ותלה אותו מעל המבנה.', 'The captain took an English flag from his pocket, and hung it over the building.'),
    ('הוא אמר: זה המבצר שלנו, וזה הדגל שלנו.', 'He said: this is our fort, and this is our flag.'),
    ('ואז הוא ישב וספר: אוכל לעשרה ימים, מים מהמעיין, ואבק שרפה לקרב או שניים.', 'And then he sat and counted: food for ten days, water from the spring, and powder for a battle or two.'),
    ("והוא אמר: ג'ים אבד, אולי מת, אבל אולי לא.", 'And he said: Jim is lost, maybe dead, but maybe not.'),
    ('ואז התותח מהספינה התחיל לירות על המבנה.', 'And then the cannon from the ship began firing at the building.'),
    ('הכדורים עברו מעל, נפלו בעצים, ולא עשו כלום.', 'The balls passed over, fell in the trees, and did nothing.'),
    ('המפקד אמר: שיבזבזו את אבק השרפה שלהם.', 'The captain said: let them waste their powder.')),
  P(('ובערב, כשהתותח נרגע, הם שמעו קול מחוץ לגדר.', 'And in the evening, when the cannon quietened, they heard a voice outside the fence.'),
    ("קול שאומר: רופא! טרלוני! זה אני! ג'ים!", 'A voice saying: doctor! Trelawney! It is me! Jim!'),
    ('הרופא רץ לדלת, ואני קפצתי מעל הגדר.', 'The doctor ran to the door, and I jumped over the fence.'),
    ('והייתי חי, והייתי רעב, והכי חשוב: היו לי חדשות.', 'And I was alive, and I was hungry, and most important: I had news.'),
    ('אמרתי: יש איש על האי שקוראים לו בן גאן.', 'I said: there is a man on the island called Ben Gunn.'),
    ('המפקד אמר: קודם תגמור לאכול, ואחר כך תספר.', 'The captain said: first finish eating, and then tell.'),
    ('וככה נגמר היום הראשון על האי.', 'And so ended the first day on the island.'))]),

 ('The First Day’s Fighting', 'היום הראשון של הקרב', [
  P(('אכלתי כמו שלא אכלתי בחיים שלי, ואחר כך סיפרתי.', 'I ate as I had never eaten in my life, and then I told.'),
    ('סיפרתי על סילבר ועל טום, ועל בן גאן, והסירה שלו מתחת לסלע הלבן.', 'I told about Silver and Tom, and about Ben Gunn, and his boat under the white rock.'),
    ('הרופא אמר: בן גאן? אני לא יודע אם הוא משוגע או שפוי.', 'The doctor said: Ben Gunn? I do not know if he is mad or sane.'),
    ('המפקד אמר: איש שלוש שנים לבד, הוא שניהם.', 'The captain said: a man three years alone, he is both.'),
    ('וטרלוני אמר: אבל אם יש לו סירה, זה חשוב יותר מהמטמון.', 'And Trelawney said: but if he has a boat, that matters more than the treasure.')),
  P(('הלילה היה ארוך.', 'The night was long.'),
    ('המפקד חילק אותנו למשמרות: שניים שומרים, והשאר ישנים.', 'The captain divided us into watches: two on guard, and the rest asleep.'),
    ('ואני לא יכולתי לישון, כי כל פעם שסגרתי עיניים ראיתי את סילבר מנקה את הסכין.', 'And I could not sleep, because every time I closed my eyes I saw Silver cleaning the knife.'),
    ('מרחוק שמענו את הרוצחים שרים סביב האש.', 'From afar we heard the murderers singing around the fire.'),
    ('הקול שלהם היה שיכור, והשיר אותו שיר: יו הו הו ובקבוק רום.', 'Their voices were drunk, and the song the same song: yo ho ho and a bottle of rum.'),
    ('גריי אמר: זה הרום מהספינה, הם ישתו עד הבוקר.', 'Gray said: that is the rum from the ship, they will drink until morning.'),
    ('המפקד אמר: יותר טוב, שיכור לא פוגע.', 'The captain said: better, a drunk man does not hit.')),
  P(('עם השחר בא הקרב הראשון.', 'With the dawn came the first fight.'),
    ('שלושה מהאנשים של סילבר התקרבו לגדר, אולי לנסות את המזל.', 'Three of Silver’s men came near the fence, maybe to try their luck.'),
    ('טרלוני וגריי ירו פעם אחת.', 'Trelawney and Gray fired once.'),
    ('אחד נפל, והשניים האחרים רצו לעצים וצעקו.', 'One fell, and the other two ran to the trees and shouted.'),
    ('וזה שנפל לא קם.', 'And the one who fell did not get up.'),
    ('המפקד אמר: עכשיו הם חמישה עשר.', 'The captain said: now they are fifteen.'),
    ("והרופא אמר: ואנחנו עדיין שבעה, עם ג'ים.", 'And the doctor said: and we are still seven, with Jim.')),
  P(('ואז חזר השקט, השמש עלתה, והאי נהיה חם.', 'And then the quiet returned, the sun rose, and the island grew hot.'),
    ('ישבנו כולנו בתוך המבנה, הזבובים סביבנו, והריח מהגופה בחוץ.', 'We all sat inside the building, the flies around us, and the smell from the body outside.'),
    ('טרלוני אמר: כמה ימים אנחנו יכולים להישאר ככה?', 'Trelawney said: how many days can we stay like this?'),
    ('המפקד אמר: עשרה, ואחר כך נמות מרעב, או נצא להילחם.', 'The captain said: ten, and then we die of hunger, or go out to fight.'),
    ('הרופא אמר: או שבן גאן יגיע אלינו.', 'The doctor said: or Ben Gunn reaches us.'),
    ('והרופא יצא מהמבנה, עם הרובה שלו, והלך לעצים.', 'And the doctor left the building, with his gun, and went into the trees.'),
    ('הוא אמר: אני הולך לחפש משוגע.', 'He said: I am going to look for a madman.'))]),

 ('The Garrison in the Stockade', 'המבנה על הגבעה', [
  P(('היינו שישה במבנה, והעבודה הייתה רבה.', 'We were six in the building, and the work was much.'),
    ('המפקד נתן לכל אחד עבודה.', 'The captain gave everyone a job.'),
    ('שניים מביאים עצים, גריי שומר, וטרלוני מנקה את הרובים.', 'Two fetch wood, Gray keeps watch, and Trelawney cleans the guns.'),
    ('ואני מבשל, ומביא מים מהמעיין.', 'And I cook, and bring water from the spring.'),
    ('וכל שעה המפקד יוצא ומסתכל על הספינה עם המשקפת.', 'And every hour the captain goes out and looks at the ship with the spyglass.'),
    ('הספינה עמדה במקום שלה, ועליה דגל שחור.', 'The ship stood in her place, and on her a black flag.')),
  P(('המפקד אמר: הלכה הספינה הכי טובה שהפלגתי בה.', 'The captain said: there goes the best ship I ever sailed in.'),
    ('וטרלוני אמר: אנחנו נחזיר אותה.', 'And Trelawney said: we will get her back.'),
    ('המפקד אמר: איך? אנחנו שישה והם חמישה עשר.', 'The captain said: how? We are six and they are fifteen.'),
    ('ואני שמעתי, וחשבתי על הסירה של בן גאן מתחת לסלע הלבן.', 'And I heard, and thought about Ben Gunn’s boat under the white rock.'),
    ('ולא אמרתי כלום.', 'And I said nothing.')),
  P(('אחרי הצהריים הרופא חזר, והפנים שלו שמחות.', 'In the afternoon the doctor came back, and his face was pleased.'),
    ('הוא אמר: מצאתי את בן גאן, ישבנו יחד שעה.', 'He said: I found Ben Gunn, we sat together an hour.'),
    ('הוא משוגע, והוא שפוי, והוא יעזור לנו.', 'He is mad, and he is sane, and he will help us.'),
    ('טרלוני אמר: והוא רוצה חלק?', 'Trelawney said: and he wants a share?'),
    ('הרופא אמר: הוא רוצה אלף לירות, ודרך הביתה.', 'The doctor said: he wants a thousand pounds, and a way home.'),
    ('טרלוני אמר: אפשר.', 'Trelawney said: that can be done.'),
    ('והרופא אמר: אבל הוא לא אמר לי איפה הסירה שלו, הוא אמר: רק לילד.', 'And the doctor said: but he did not tell me where his boat is, he said: only to the boy.')),
  P(('ואחרי זמן קצר היה קול מחוץ לגדר.', 'And a little later there was a voice outside the fence.'),
    ('הקול של סילבר: אתם שבפנים! הפסקת אש! הפסקת אש!', 'Silver’s voice: you inside! A truce! A truce!'),
    ('וראינו אותו, עומד ליד העצים, וביד שלו בד לבן על מקל.', 'And we saw him, standing by the trees, and in his hand a white cloth on a stick.'),
    ('ולידו עוד אחד, עם ידיים למעלה.', 'And beside him another, with hands raised.'),
    ('המפקד אמר: כולם פנימה, אף אחד לא יוצא.', 'The captain said: everyone inside, no one goes out.'),
    ('והוא צעק: מי אתה ומה אתה רוצה?', 'And he shouted: who are you and what do you want?'),
    ('סילבר ענה: מפקד סילבר, אדוני, בא להציע תנאים.', 'Silver answered: Captain Silver, sir, come to offer terms.'),
    ('המפקד סמולט אמר: מפקד סילבר? אני לא מכיר אחד כזה.', 'Captain Smollett said: Captain Silver? I know no such man.'),
    ('וסילבר צחק, ואמר: האנשים בחרו בי, אחרי שאתה עזבת אותנו.', 'And Silver laughed, and said: the men chose me, after you deserted us.'))]),

 ('Silver’s Embassy', 'סילבר בא לדבר', [
  P(('המפקד אמר: אם אתה רוצה לדבר, בוא, אבל לבד.', 'The captain said: if you want to talk, come, but alone.'),
    ('וסילבר בא, על המקל שלו, וטיפס על הגדר בקושי.', 'And Silver came, on his crutch, and climbed the fence with difficulty.'),
    ('אף אחד לא עזר לו.', 'No one helped him.'),
    ('והוא ישב על החול לפני הדלת, והמפקד עמד מולו.', 'And he sat on the sand before the door, and the captain stood facing him.'),
    ('סילבר אמר: מפקד, עשית יפה אתמול, אחד מהאנשים שלי נהרג בלילה, בשינה.', 'Silver said: captain, you did well yesterday, one of my men was killed in the night, in his sleep.'),
    ('המפקד אמר: אני לא שלחתי אף אחד.', 'The captain said: I sent no one.'),
    ('ואני הבנתי: בן גאן.', 'And I understood: Ben Gunn.')),
  P(('סילבר אמר: בואו נדבר לעניין.', 'Silver said: let us talk sense.'),
    ('אנחנו רוצים את המטמון, ואתם רוצים את החיים שלכם.', 'We want the treasure, and you want your lives.'),
    ('תנו לנו את המפה, ואני נשבע: נחלק את האוכל איתכם, ואז נשלח לכם ספינה כשנגיע.', 'Give us the map, and I swear: we share the food with you, and send you a ship when we arrive.'),
    ('או, אם אתם רוצים, אתם באים איתנו ואנחנו מורידים אתכם בנמל הראשון.', 'Or, if you like, you come with us and we put you off at the first port.'),
    ('והקול שלו היה חם, והגיוני, ונעים.', 'And his voice was warm, and reasonable, and pleasant.'),
    ('ואם לא הייתי רואה אותו הורג את טום, הייתי מאמין לו.', 'And had I not seen him kill Tom, I would have believed him.')),
  P(('המפקד סמולט לא ענה מיד.', 'Captain Smollett did not answer at once.'),
    ('הוא שם טבק במקטרת שלו, הדליק, ועישן.', 'He put tobacco in his pipe, lit it, and smoked.'),
    ('ואז אמר: סיימת?', 'And then said: are you finished?'),
    ('סילבר אמר: זאת המילה האחרונה, אחריה, כדורים.', 'Silver said: that is the last word, after it, bullets.'),
    ('המפקד אמר: טוב, תשמע את המילה שלי.', 'The captain said: fine, hear my word.'),
    ('אם תבואו אחד אחד בלי נשק, אני אשים אתכם בכבלים ואז אקח אתכם לאנגליה למשפט הוגן.', 'If you come one by one without weapons, I put you in chains and take you to England for a fair trial.'),
    ('חוץ מזה, אין כלום.', 'Other than that, there is nothing.'),
    ('אין לכם ספינה, כי אתם לא יודעים להוביל אותה, ואין לכם מטמון, כי אתם לא יודעים איפה הוא.', 'You have no ship, because you cannot sail her, and you have no treasure, because you do not know where it is.'),
    ('וזאת המילה האחרונה שלי, ובפעם הבאה אני יורה עליך.', 'And that is my last word, and next time I shoot you.')),
  P(('הפנים של סילבר השתנו.', 'Silver’s face changed.'),
    ('הן נהיו אדומות, העיניים שלו נהיו צרות, והוא נהיה דומה לאיש שראיתי ביער.', 'It went red, his eyes went narrow, and he came to look like the man I had seen in the wood.'),
    ('הוא אמר: תעזרו לי לקום.', 'He said: help me get up.'),
    ('אף אחד לא זז.', 'No one moved.'),
    ('הוא זחל על החול עד שהגיע לגדר, תפס עמוד, וקם.', 'He crawled on the sand until he reached the fence, grabbed a post, and got up.'),
    ('והוא אמר: בעוד שעה אני נכנס למבצר שלכם כמו חבית רום.', 'And he said: in an hour I come into your fort like a barrel of rum.'),
    ('ומי שימות מכם, יהיה בר מזל.', 'And whoever of you dies will be the lucky one.'),
    ('והוא ירק, ועבר את הגדר, ונעלם בעצים.', 'And he spat, and went over the fence, and vanished into the trees.'))]),

 ('The Attack', 'ההתקפה', [
  P(('המפקד הסתובב אלינו ואמר: בתוך שעה הם תוקפים.', 'The captain turned to us and said: within an hour they attack.'),
    ('אנחנו פחות, אבל יש לנו גדר, ובית, ורובים.', 'We are fewer, but we have a fence, and a house, and guns.'),
    ('והוא שם כל אחד במקום שלו: אחד בכל צד, ואני עם עוד אחד ליד הדלת טוענים את הרובים.', 'And he put everyone in his place: one on each side, and I with another by the door loading the guns.'),
    ('והשמש נהייתה חמה, והשקט היה השעה הכי ארוכה בחיים שלי.', 'And the sun grew hot, and the silence was the longest hour of my life.'),
    ('ואז מישהו צעק: הם באים!', 'And then someone shouted: they are coming!')),
  P(('היו כדורים מכל הכיוונים בבת אחת.', 'There were bullets from every direction at once.'),
    ('אף אחד לא נפגע, אבל העץ עף סביבנו.', 'No one was hit, but the wood flew around us.'),
    ('ומהצד הצפוני יצאו מהעצים שבעה אנשים ורצו לגדר.', 'And from the north side seven men came out of the trees and ran to the fence.'),
    ('ירינו, ושניים נפלו, וחמישה טיפסו על הגדר.', 'We fired, and two fell, and five climbed the fence.'),
    ('והמלח הגדול בראשם, צועק: עליהם, חברים!', 'And the big sailor at their head, shouting: at them, lads!'),
    ('אחד נכנס מהחלון, תפס את הרובה של השומר והכה אותו איתו בראש.', 'One came in through the window, grabbed the guard’s gun and struck him on the head with it.'),
    ('ואחר נכנס מהדלת אל הרופא.', 'And another came in the door at the doctor.')),
  P(('המפקד צעק: החוצה! החוצה! תילחמו בהם בחוץ!', 'The captain shouted: out! Out! Fight them outside!'),
    ('ותפסתי חרב ויצאתי מהדלת, ואני לא יודע איך.', 'And I grabbed a sword and went out the door, and I do not know how.'),
    ('לפניי המלח הגדול, עם החרב למעלה, רוצה להוריד אותה על הראש שלי.', 'Before me the big sailor, with his sword raised, wanting to bring it down on my head.'),
    ('לא חשבתי, קפצתי הצידה, נפלתי על החול, והתגלגלתי.', 'I did not think, I jumped aside, fell on the sand, and rolled.'),
    ('וכשקמתי, הרופא הרג אותו במכת חרב.', 'And when I got up, the doctor had killed him with a stroke of his sword.'),
    ('וגריי הרג שני, וטרלוני שלישי מהחלון.', 'And Gray killed a second, and Trelawney a third from the window.'),
    ('ואלה שנשארו, ברחו לעצים.', 'And those who remained, fled into the trees.')),
  P(('הכול נגמר בדקה.', 'It was all over in a minute.'),
    ('חמישה מהרוצחים מתו סביב המבנה, ושניים ברחו.', 'Five of the murderers died around the building, and two fled.'),
    ('אבל השומר היה מעולף מהמכה, ומשרת אחר נהרג מכדור בראש.', 'But the guard was unconscious from the blow, and another servant was killed by a bullet to the head.'),
    ('והמפקד נפגע משני כדורים, בכתף וברגל.', 'And the captain was hit by two bullets, in the shoulder and the leg.'),
    ('הרופא טיפל בו, ואמר: הוא יחיה, אבל הוא לא יילחם.', 'The doctor treated him, and said: he will live, but he will not fight.'),
    ('המפקד אמר: עכשיו הם תשעה, ואנחנו?', 'The captain said: now they are nine, and we?'),
    ("הרופא אמר: ארבעה שיכולים להילחם, וג'ים.", 'The doctor said: four who can fight, and Jim.'),
    ('והשומר מת בלילה, ולא התעורר.', 'And the guard died in the night, and did not wake.'))]),

 ('I Slip Away', 'אני יוצא בשקט', [
  P(('אחרי הצהריים הרופא יצא שוב מהמבנה, עם הרובה שלו ועם המפה.', 'In the afternoon the doctor left the building again, with his gun and with the map.'),
    ('גריי אמר: הרופא השתגע? הולך אל הרוצחים?', 'Gray said: has the doctor gone mad? Going to the murderers?'),
    ('אמרתי: לא, הולך אל בן גאן.', 'I said: no, going to Ben Gunn.'),
    ('וקינאתי בו, כי בחוץ יש אוויר ועצים, וכאן ריח של דם וחום.', 'And I envied him, because outside there is air and trees, and here the smell of blood and heat.'),
    ('והתחלתי לחשוב על רעיון.', 'And I began to think about an idea.'),
    ('רעיון טיפשי, כמו הרעיון שלי עם הסירה.', 'A foolish idea, like my idea with the boat.')),
  P(('הרעיון היה: ללכת לסלע הלבן, ולמצוא את הסירה של בן גאן.', 'The idea was: go to the white rock, and find Ben Gunn’s boat.'),
    ('ידעתי שאף אחד לא ירשה לי, אז לא שאלתי.', 'I knew no one would let me, so I did not ask.'),
    ('שמתי בכיס לחם ועוגיות, ולקחתי שני אקדחים ואבק שרפה.', 'I put bread and biscuits in my pocket, and took two pistols and powder.'),
    ('וכשכולם היו עסוקים, עברתי את הגדר מהצד השני, ורצתי.', 'And when everyone was busy, I went over the fence on the other side, and ran.'),
    ('זאת הפעם השנייה שאני בורח, והפעם ידעתי שזאת טעות.', 'This was the second time I ran away, and this time I knew it was a mistake.'),
    ('אבל הייתי ילד, ורציתי לעשות משהו.', 'But I was a boy, and I wanted to do something.')),
  P(('הלכתי לאורך החוף, מאחורי העצים, עד שראיתי את הספינה.', 'I walked along the shore, behind the trees, until I saw the ship.'),
    ('היא עמדה במפרץ, ולידה סירה קטנה, ובה שניים מהרוצחים.', 'She stood in the bay, and beside her a small boat, and in it two of the murderers.'),
    ('הם צעקו אחד על השני, ושיכורים.', 'They were shouting at each other, and drunk.'),
    ('ועל הספינה ראיתי את הנדס, ההגאי, ועוד אחד.', 'And on the ship I saw Hands, the coxswain, and another.'),
    ('המשכתי לסלע הלבן, והשמש הייתה שוקעת.', 'I went on to the white rock, and the sun was setting.'),
    ('ומתחת לסלע, בבור מכוסה בעור של עז, מצאתי את הסירה.', 'And under the rock, in a hollow covered with goatskin, I found the boat.')),
  P(('זאת הייתה הסירה הכי מוזרה שראיתי בחיים שלי.', 'It was the strangest boat I had seen in my life.'),
    ('עץ ועור, עגולה, וקטנה, ונושאת רק אחד.', 'Wood and skin, round, and small, and carrying only one.'),
    ('בן גאן עשה אותה בידיים שלו, בשלוש שנים.', 'Ben Gunn had made it with his own hands, in three years.'),
    ('וישבתי לידה וחיכיתי לחושך, ואכלתי לחם.', 'And I sat beside it and waited for the dark, and ate bread.'),
    ('וחשבתי: אם אני חותך את חבל העוגן של הספינה, היא נסחפת לחוף, ונשברת.', 'And I thought: if I cut the ship’s anchor rope, she drifts to the shore, and breaks.'),
    ('והרוצחים בלי ספינה נהיים חלשים יותר.', 'And the murderers without a ship become weaker.'),
    ('וכשהלילה נהיה שחור, הרמתי את הסירה וירדתי למים.', 'And when the night went black, I lifted the boat and went down to the water.'))]),

 ('The Ebb-Tide Runs', 'המים מושכים', [
  P(('הסירה הקטנה הסתובבה עם כל גל, ולא הלכה ישר.', 'The little boat spun with every wave, and did not go straight.'),
    ('אבל הזרם הלך לכיוון הספינה, ונשא אותי.', 'But the current went toward the ship, and carried me.'),
    ('הגעתי לחבל העוגן, ותפסתי אותו.', 'I reached the anchor rope, and grabbed it.'),
    ('הוא היה מתוח כמו מיתר, מכוח הזרם.', 'It was taut as a bowstring, from the force of the current.'),
    ('אם הייתי חותך אותו בבת אחת, הוא היה מכה בי והופך את הסירה.', 'Had I cut it all at once, it would have struck me and overturned the boat.'),
    ('אז חיכיתי שהוא יירפה קצת עם הגל, וחתכתי חוט אחרי חוט.', 'So I waited for it to slacken a little with the wave, and cut strand after strand.')),
  P(('ומלמעלה, מהתא, שמעתי שני קולות.', 'And from above, from the cabin, I heard two voices.'),
    ('הנדס והשני, שיכורים, ורבים.', 'Hands and the other, drunk, and quarrelling.'),
    ('קול של כוסות נשברות, וקול של מילים רעות.', 'The sound of glasses breaking, and the sound of curses.'),
    ('ועל החוף, האש הגדולה של הרוצחים, והשיר שלהם מרחוק.', 'And on the shore, the murderers’ big fire, and their song from afar.'),
    ('ואני באמצע, בסירה מעור, וביד שלי סכין.', 'And I in the middle, in a boat of skin, and in my hand a knife.'),
    ('וחתכתי את החוט האחרון.', 'And I cut the last strand.')),
  P(('הספינה השתחררה, והתחילה להסתובב לאט עם הזרם.', 'The ship came free, and began to turn slowly with the current.'),
    ('והסירה הקטנה נמשכה איתה, ונדבקה אליה.', 'And the little boat was pulled with her, and clung to her.'),
    ('ונתתי יד ותפסתי חבל שהיה תלוי מהספינה, אני לא יודע למה.', 'And I reached out and caught a rope hanging from the ship, I do not know why.'),
    ('וטיפסתי קצת, והצצתי מהחלון של התא.', 'And I climbed a little, and peeked through the cabin window.'),
    ('הנדס והשני תפסו אחד את השני בגרון.', 'Hands and the other had each other by the throat.'),
    ('וירדתי מהר לפני שראו אותי.', 'And I dropped fast before they saw me.')),
  P(('ואז קרה הדבר שלא חשבתי עליו.', 'And then came the thing I had not thought of.'),
    ('הזרם התחזק, והספינה והסירה נסחפו יחד לים הפתוח.', 'The current grew stronger, and the ship and the boat were swept together to the open sea.'),
    ('לא לחוף, כמו שתכננתי, אלא החוצה.', 'Not to the shore, as I had planned, but outward.'),
    ('ושמעתי את הרוצחים על החוף צועקים, אבל רחוק.', 'And I heard the murderers on the shore shouting, but far off.'),
    ('והסירה הקטנה התחילה להסתובב, ולהסתובב, והגלים עלו.', 'And the little boat began to spin, and spin, and the waves rose.'),
    ('שכבתי בתחתית הסירה, תפסתי את הצדדים שלה, ועצמתי עיניים.', 'I lay in the bottom of the boat, held its sides, and closed my eyes.'),
    ('ואמרתי: אם אני צריך למות, אני מת כאן.', 'And I said: if I must die, I die here.'),
    ('ונרדמתי, אני לא יודע איך, אבל נרדמתי.', 'And I fell asleep, I do not know how, but I fell asleep.'))]),

 ('The Cruise of the Coracle', 'הסירה הקטנה', [
  P(('התעוררתי והשמש עלתה, והסירה רקדה על גלים גדולים.', 'I woke and the sun was up, and the boat danced on big waves.'),
    ('הייתי רחוק מהאי, בדרום שלו, והזרם משך אותי סביבו.', 'I was far from the island, to its south, and the current was pulling me around it.'),
    ('והייתי צמא יותר מכל דבר.', 'And I was thirstier than anything.'),
    ('כל פעם שניסיתי לחתור, הסירה הסתובבה והתמלאה מים.', 'Every time I tried to paddle, the boat spun and filled with water.'),
    ('אז למדתי: לא להילחם בגלים, לתת להם לשאת אותך.', 'So I learned: do not fight the waves, let them carry you.'),
    ('ולאט לאט, הגלים קירבו אותי לחוף.', 'And little by little, the waves brought me nearer the shore.')),
  P(('ואז ראיתי אותה.', 'And then I saw her.'),
    ('היספניולה, שטה עם המפרשים שלה, בלי אף אחד שמוביל אותה.', 'The Hispaniola, sailing under her canvas, with no one steering her.'),
    ('היא הלכה ימינה, והלכה שמאלה, כמו שיכור.', 'She went right, and went left, like a drunk man.'),
    ('והמפרשים הכו ברוח, וההגה חופשי.', 'And the sails beat in the wind, and the helm free.'),
    ('אמרתי: הנדס והשני ישנים או מתים.', 'I said: Hands and the other are asleep or dead.'),
    ('ואם אני מגיע אליה, הספינה חוזרת אלינו.', 'And if I reach her, the ship comes back to us.')),
  P(('היא באה לכיוון שלי, פעם קרובה ופעם רחוקה.', 'She came my way, now nearer, now farther.'),
    ('ואני חתרתי בכל הכוח, צמא, והשמש שורפת.', 'And I paddled with all my strength, thirsty, the sun burning.'),
    ('ופתאום הרוח הסתובבה, והספינה באה עליי ישר.', 'And suddenly the wind turned, and the ship came straight at me.'),
    ('ראיתי את החרטום שלה מעל הראש שלי, גבוה כמו בית.', 'I saw her bow above my head, high as a house.'),
    ('וקפצתי, תפסתי חבל של המפרש הקדמי, ונשארתי תלוי.', 'And I jumped, caught a rope of the front sail, and hung on.'),
    ('ומתחתיי, הסירה הקטנה נמעכה מתחת לספינה, ונעלמה.', 'And beneath me, the little boat was crushed under the ship, and vanished.'),
    ('ולא הייתה לי עוד דרך חזרה.', 'And I had no way back.')),
  P(('טיפסתי למעלה ונפלתי על הסיפון.', 'I climbed up and fell onto the deck.'),
    ('הסיפון היה ריק, ועליו דם, ובקבוקים ריקים.', 'The deck was empty, and on it blood, and empty bottles.'),
    ('והשניים היו שם.', 'And the two were there.'),
    ('אחד שוכב על הגב, הידיים פתוחות, ומת.', 'One lying on his back, his arms spread, and dead.'),
    ('והשני, הנדס, יושב ליד הקיר, הראש על החזה, והפנים צהובות.', 'And the other, Hands, sitting by the bulwark, his head on his chest, and his face yellow.'),
    ('כל גל הזיז את המת, והנדס לא זז.', 'Every wave moved the dead man, and Hands did not move.'),
    ('ואז הנדס פתח את העיניים, והסתכל עליי.', 'And then Hands opened his eyes, and looked at me.'),
    ('והוא אמר: רום.', 'And he said: rum.'))]),

 ('I Strike the Jolly Roger', 'מוריד את הדגל השחור', [
  P(('ירדתי לתא, והכול היה שבור והפוך.', 'I went down to the cabin, and everything was broken and overturned.'),
    ('מצאתי בקבוק רום, הבאתי אותו להנדס, ואני שתיתי מים.', 'I found a bottle of rum, brought it to Hands, and I drank water.'),
    ('ואכלתי עוגיות, ובפעם הראשונה מזה יומיים הרגשתי שאני חי.', 'And I ate biscuits, and for the first time in two days I felt alive.'),
    ('הנדס שתה חצי בקבוק, ואמר: זה מה שהייתי צריך.', 'Hands drank half the bottle, and said: ah, that is what I needed.'),
    ('ושאלתי אותו: אתה פצוע?', 'And I asked him: are you wounded?'),
    ('הוא אמר: זה שהיה איתי דקר אותי בירך, והוא מת, ואני לא.', 'He said: the one who was with me stabbed me in the thigh, and he died, and I did not.')),
  P(('ואז אמרתי לו: מר הנדס, אני עכשיו המפקד של הספינה הזאת.', 'And then I said to him: Mr. Hands, I am now the captain of this ship.'),
    ('והפקודה הראשונה: אני מוריד את הדגל השחור.', 'And the first order: I take down the black flag.'),
    ('הלכתי לתורן, הורדתי את דגל השודדים, וזרקתי אותו לים.', 'I went to the mast, took down the pirates’ flag, and threw it into the sea.'),
    ('אמרתי: יחי המלך! וזהו מפקד סילבר!', 'I said: long live the king! And so much for Captain Silver!'),
    ('הנדס הסתכל עליי, וצחק צחוק קטן.', 'Hands looked at me, and gave a small laugh.'),
    ('הוא אמר: טוב, מפקד הוקינס, ועכשיו מה אתה רוצה לעשות?', 'He said: fine, Captain Hawkins, and now what do you want to do?')),
  P(('אמרתי: אני רוצה להביא את הספינה למפרץ הצפוני, ולהעלות אותה על החוף.', 'I said: I want to bring the ship to the northern bay, and run her onto the shore.'),
    ('כי אני לא יכול לחזור למעגן הישן, הרוצחים שם.', 'Because I cannot go back to the old anchorage, the murderers are there.'),
    ('הנדס אמר: ואתה יודע להוביל ספינה?', 'Hands said: and do you know how to sail a ship?'),
    ('אמרתי: לא.', 'I said: no.'),
    ('הוא אמר: אני יודע, אבל אני פצוע.', 'He said: I do, but I am wounded.'),
    ('אתה נותן לי אוכל ומשקה ובד לפצע שלי, ואני אומר לך איך להוביל אותה.', 'You give me food and drink and a cloth for my wound, and I tell you how to sail her.'),
    ('והעיניים שלו הסתכלו עליי בצורה שלא אהבתי.', 'And his eyes looked at me in a way I did not like.'),
    ('אבל לא הייתה לי ברירה.', 'But I had no choice.')),
  P(('וככה הובלנו שנינו את הספינה: אני בידיים, והוא בפה.', 'And so the two of us sailed the ship: I with my hands, and he with his mouth.'),
    ('קצת ימינה, קצת שמאלה, תמשוך את החבל, תרפה.', 'A little right, a little left, pull the rope, ease off.'),
    ('והספינה שמעה, והלכה כמו שרצינו.', 'And the ship obeyed, and went as we wished.'),
    ('ולאט לאט הקפנו את האי, והגענו לצפון.', 'And little by little we rounded the island, and reached the north.'),
    ('והנדס יושב, ושותה, ומסתכל עליי.', 'And Hands sitting, and drinking, and looking at me.'),
    ('ואני ידעתי שהוא חושב על משהו.', 'And I knew he was thinking about something.'),
    ('אבל הייתי מאושר מאוד, כי הייתי המפקד של ספינה, ובן ארבע עשרה.', 'But I was very happy, because I was the captain of a ship, and fourteen years old.'))]),

 ('Israel Hands', 'ישראל הנדס', [
  P(("לפני שנכנסנו למפרץ, הנדס אמר: ג'ים, אני רוצה משהו.", 'Before we entered the bay, Hands said: Jim, I want something.'),
    ('יש יין בתא, הרום חזק לי מדי, תביא לי יין.', 'There is wine in the cabin, the rum is too strong for me, bring me wine.'),
    ('לא האמנתי לו.', 'I did not believe him.'),
    ('אחד כמו הנדס לא מבקש יין במקום רום.', 'A man like Hands does not ask for wine instead of rum.'),
    ('אמרתי: טוב, וירדתי לתא, הורדתי את הנעליים, עליתי מהפתח השני, והסתכלתי.', 'I said: fine, and went down to the cabin, took off my shoes, came up through the other hatch, and watched.')),
  P(('הנדס קם, בכאב, וזחל על הסיפון.', 'Hands got up, in pain, and crawled across the deck.'),
    ('הוא הגיע לחבל, הוציא ממנו סכין ארוכה, ושם אותה בכיס.', 'He reached a coiled rope, took out of it a long knife, and put it in his pocket.'),
    ('וזחל חזרה למקום שלו, והוא ישב כמו קודם.', 'And crawled back to his place, and sat as before.'),
    ('הבנתי הכול.', 'I understood everything.'),
    ('הוא רוצה להביא את הספינה לחוף, ואחר כך להרוג אותי.', 'He wants to bring the ship to the shore, and then kill me.'),
    ('והוא רוצה אותי חי עד שנגיע.', 'And he wants me alive until we arrive.'),
    ('כלומר, יש לי זמן עד החוף.', 'That is, I have time until the shore.')),
  P(('חזרתי עם היין, נתתי לו אותו, ועשיתי כאילו לא ראיתי כלום.', 'I came back with the wine, gave it to him, and acted as if I had seen nothing.'),
    ('ונכנסנו למפרץ, הרוח איתנו, והחוף מתקרב.', 'And we entered the bay, the wind with us, and the shore approaching.'),
    ('הנדס אמר: עכשיו, ימינה! כל הימינה!', 'Hands said: now, right! Hard right!'),
    ('סובבתי את ההגה, הספינה נטתה, ונכנסה בחול ברעש גדול.', 'I turned the helm, the ship heeled, and ran into the sand with a great noise.'),
    ('והמכה זרקה אותי על הרצפה.', 'And the shock threw me to the floor.'),
    ('וכשהרמתי את הראש, הנדס עמד מעליי, והסכין בידו.', 'And when I raised my head, Hands stood over me, and the knife in his hand.')),
  P(('קפצתי הצידה, ורצתי, והוא אחריי.', 'I jumped aside, and ran, and he after me.'),
    ('הקפנו את התורן פעם ופעמיים, כמו משחק של ילדים.', 'We went round the mast once and twice, like a children’s game.'),
    ('אבל הוא פצוע ואיטי, ואני מהיר.', 'But he was wounded and slow, and I was fast.'),
    ('והוצאתי אקדח מהכיס, ולחצתי, והוא לא ירה, אבק השרפה רטוב.', 'And I took a pistol from my pocket, and pulled, and it did not fire, the powder was wet.'),
    ('אז טיפסתי על התורן, למעלה, עד שהוא לא יכול היה להגיע אליי.', 'So I climbed the mast, upward, until he could not reach me.'),
    ('ושם, באוויר, טענתי את שני האקדחים באבק שרפה יבש.', 'And there, in the air, I loaded the two pistols with dry powder.'),
    ('והנדס מתחתיי, מסתכל למעלה, וחושב.', 'And Hands below me, looking up, and thinking.')),
  P(("הוא אמר: ג'ים, הפסדתי, אני לא בר מזל.", 'He said: Jim, I have lost, I am not a lucky man.'),
    ('קשה לאחד כמוני להיכנע לילד, אבל אני נכנע.', 'It is hard for one like me to give in to a boy, but I give in.'),
    ('והוא דיבר, והיד שלו זזה מאחורי הגב.', 'And he talked, and his hand moved behind his back.'),
    ('ופתאום הוא זרק את הסכין.', 'And suddenly he threw the knife.'),
    ('הרגשתי מכה בכתף, ושמעתי את שני האקדחים יורים, בלי שהתכוונתי.', 'I felt a blow in the shoulder, and heard the two pistols fire, without meaning to.'),
    ('והנדס נפל מהספינה, למים, ושקע, ולא עלה.', 'And Hands fell from the ship, into the water, and sank, and did not come up.'),
    ('ואני תלוי על התורן, והסכין מחזיקה את הכתף שלי לעץ.', 'And I hung on the mast, and the knife held my shoulder to the wood.'))]),

 ('Pieces of Eight', 'מטבעות זהב', [
  P(('הדם ירד על היד שלי, ופחדתי מאוד.', 'The blood ran down my arm, and I was very afraid.'),
    ('אבל כשמשכתי, הבנתי שהסכין מחזיקה רק את העור.', 'But when I pulled, I understood that the knife held only the skin.'),
    ('משכתי פעם אחת, והשתחררתי, והכאב היה קטן מהפחד.', 'I pulled once, and was free, and the pain was smaller than the fear.'),
    ('ירדתי לתא, וטיפלתי בפצע שלי בעצמי.', 'I went down to the cabin, and treated my wound myself.'),
    ('וזרקתי את המת השני לים, אחרי הנדס.', 'And I threw the other dead man into the sea, after Hands.'),
    ('והספינה הייתה שלי, שלי לבד.', 'And the ship was mine, mine alone.')),
  P(('השמש שקעה, והספינה נטתה על החול, אבל שלמה.', 'The sun set, and the ship leaned on the sand, but whole.'),
    ('ירדתי למים עד המותניים, והגעתי לחוף.', 'I went down into the water up to the waist, and reached the shore.'),
    ('ואמרתי: עכשיו אני חוזר למבנה, ואומר להם: הספינה שלנו.', 'And I said: now I go back to the building, and tell them: the ship is ours.'),
    ('ואולי הם יסלחו לי על הבריחה שלי.', 'And maybe they forgive me for my running away.'),
    ('והלכתי באי בחושך, שעות.', 'And I walked through the island in the dark, for hours.'),
    ('והירח עלה, וראיתי את המבנה, ולא הייתה בו אש.', 'And the moon rose, and I saw the building, and there was no fire in it.'),
    ('אמרתי: ישנים, וזה לא נכון, המפקד לא משאיר בלי שמירה.', 'I said: asleep, and that is wrong, the captain never leaves it without a guard.')),
  P(('טיפסתי על הגדר, זחלתי לבית, ונכנסתי מהדלת על הידיים והברכיים.', 'I climbed the fence, crawled to the house, and went in the door on hands and knees.'),
    ('היו אנשים ישנים, וישנים חזק.', 'There were people asleep, and snoring.'),
    ('ואמרתי: אני אפתיע אותם, והם יצחקו.', 'And I said: I will surprise them, and they will laugh.'),
    ('ובאותו רגע קול חד צעק בחושך:', 'And in that moment a sharp voice screeched in the dark:'),
    ('מטבעות זהב! מטבעות זהב! מטבעות זהב!', 'Pieces of eight! Pieces of eight! Pieces of eight!'),
    ('התוכי של סילבר.', 'Silver’s parrot.')),
  P(('כולם קמו בבת אחת.', 'Everyone got up at once.'),
    ('ושמעתי את הקול של סילבר צועק: מי שם?', 'And I heard Silver’s voice shout: who is there?'),
    ('רצתי לדלת, ונפלתי לידיים של מישהו.', 'I ran for the door, and fell into someone’s arms.'),
    ('הוא תפס אותי, ואחר הדליק אור.', 'He held me, and another lit a light.'),
    ('וראיתי: המבנה מלא שודדים.', 'And I saw: the building was full of pirates.'),
    ('שישה אנשים, וסילבר באמצע, על המקל שלו.', 'Six men, and Silver in the middle, on his crutch.'),
    ('ואף אחד מהחברים שלי.', 'And not one of my friends.'),
    ("סילבר אמר: ג'ים הוקינס! אלוהים! בא לבקר אותנו.", 'Silver said: Jim Hawkins! Good Lord! Come to visit us.'))]),

 ('In the Enemy’s Camp', 'במחנה של האויב', [
  P(('ישבתי על הרצפה, סילבר מולי, והאנשים שלו סביבי.', 'I sat on the floor, Silver facing me, and his men around me.'),
    ("סילבר אמר: ג'ים, תמיד אהבתי אותך, אתה דומה לי.", 'Silver said: Jim, I always liked you, you are like me.'),
    ('החברים שלך עזבו אותך, הרופא אמר: הילד? אנחנו לא רוצים אותו.', 'Your friends left you, the doctor said: the boy? We do not want him.'),
    ('אמרתי: שקר.', 'I said: a lie.'),
    ('סילבר אמר: אתמול הרופא בא עם דגל לבן, ואמר: זהו, הספינה הלכה.', 'Silver said: yesterday the doctor came with a white flag, and said: it is over, the ship is gone.'),
    ('והוא נתן לנו את המבנה, ואת האוכל, ותנאי אחד: לא לרדוף אחרי החברים שלך.', 'And he gave us the building, and the food, and one condition: not to chase them.'),
    ('והם הלכו, ואני לא יודע לאן.', 'And they went, and I do not know where.')),
  P(('לא הבנתי, אבל שתקתי.', 'I did not understand, but kept silent.'),
    ('סילבר אמר: אז אתה איתנו, או נגדנו, תבחר.', 'Silver said: so you are with us, or against us, choose.'),
    ('והרגשתי שאני חייב לדבר, אחרת אמות מפחד.', 'And I felt I must speak, or die of fear.'),
    ('אז אמרתי: אני זה שהייתי בחבית, ושמעתי כל מילה.', 'So I said: I am the one who was in the barrel, and heard every word.'),
    ('ואני זה שחתכתי את החבל של הספינה, והרגתי את הנדס.', 'And I am the one who cut the ship’s rope, and killed Hands.'),
    ('והספינה במקום שאתם לא מכירים, ואתם לא תראו אותה.', 'And the ship is in a place you do not know, and you will not see her.'),
    ('תהרגו אותי אם אתם רוצים, או תשאירו אותי חי, ואני אדבר בשבילכם בבית המשפט.', 'Kill me if you want, or leave me alive, and I testify for you in court.')),
  P(('היה שקט.', 'There was silence.'),
    ('ואז אחד קם ושלף סכין, ואמר: אני הורג אותו.', 'And then one got up and drew a knife, and said: I kill him.'),
    ('סילבר אמר: תישאר במקום שלך.', 'Silver said: stay where you are.'),
    ('אני המפקד כאן, ומי שנוגע בילד, נלחם בי.', 'I am the captain here, and whoever touches the boy fights me.'),
    ('האנשים שלו התחילו ללחוש, ולהסתכל עליו.', 'His men began to whisper, and to look at him.'),
    ('ואחד אמר: אנחנו רוצים לדבר בחוץ.', 'And one said: we want to talk outside.'),
    ('והשישה יצאו, והשאירו אותי לבד עם סילבר.', 'And the six went out, and left me alone with Silver.')),
  P(("סילבר אמר בקול נמוך: ג'ים, אתה קרוב למוות.", 'Silver said in a low voice: Jim, you are close to death.'),
    ('וגם אני, האנשים שלי רוצים לזרוק אותי, כי הגנתי עליך.', 'And so am I, my men want to throw me out, because I protected you.'),
    ("אבל תשמע: אני מגן עליך, ואתה מגן על ג'ון סילבר מהתלייה.", 'But listen: I protect you, and you protect John Silver from the gallows.'),
    ('אמרתי: אני אעשה מה שאני יכול.', 'I said: I will do what I can.'),
    ('הוא אמר: סגור.', 'He said: agreed.'),
    ('ואז אמר, והסתכל באש: הרופא נתן לי עוד משהו, חוץ מהמבנה.', 'And then he said, looking into the fire: the doctor gave me something else, besides the building.'),
    ('הוא נתן לי את המפה.', 'He gave me the map.'),
    ('והוא הוציא אותה מהכיס, ואני לא הבנתי כלום.', 'And he took it out of his pocket, and I understood nothing.'))]),

 ('The Black Spot Again', 'שוב הכתם השחור', [
  P(('השישה חזרו, ואחד מהם לפניהם, ובידו נייר.', 'The six came back, and one of them in front, and in his hand a paper.'),
    ("סילבר אמר: בוא, ג'ורג', אני מכיר את החוק.", 'Silver said: come, George, I know the rule.'),
    ('הוא שם את הנייר ביד של סילבר, ואמר: הכתם השחור.', 'He put the paper in Silver’s hand, and said: the black spot.'),
    ('סילבר פתח אותו, וצחק.', 'Silver opened it, and laughed.'),
    ('הוא אמר: חתכתם אותו מספר קדוש! משוגעים! זה מזל רע.', 'He said: you cut it out of a Bible! Madmen! That is bad luck.'),
    ("והוא קרא: סוף, אתה לא המפקד, ואמר: ולמה, ג'ורג'?", 'And he read: deposed, and said: and why, George?')),
  P(("ג'ורג' אמר: ארבע סיבות.", 'George said: four reasons.'),
    ('הרסת את המסע, ונתת לאויב לצאת מהמבנה, ולא תקפת אותם.', 'You ruined the voyage, and let the enemy leave the building, and did not attack them.'),
    ('והילד, הגנת על הילד.', 'And the boy, you protected the boy.'),
    ('סילבר אמר: טוב, אני עונה.', 'Silver said: fine, I answer.'),
    ('מי הרס את המסע? אתם, כשלא חיכיתם עד שאני אגיד.', 'Who ruined the voyage? You, when you did not wait until I said.'),
    ('ומי איבד את הספינה? אתם, שהשארתם אותה בלי שמירה.', 'And who lost the ship? You, who left her without a guard.'),
    ('והילד? הילד הוא בן ערובה, הוא הקלף האחרון שלנו.', 'And the boy? The boy is a hostage, he is our last card.')),
  P(('והוא אמר: והמבנה? למה עשיתי הסכם עם הרופא?', 'And he said: and the building? Why did I make a deal with the doctor?'),
    ('בשביל זה.', 'For this.'),
    ('והוא זרק את המפה על הרצפה.', 'And he threw the map on the floor.'),
    ('כולם קפצו עליה, כמו חתולים על עכבר.', 'They all jumped on it, like cats on a mouse.'),
    ('הצלבים האדומים, וההוראות בכתב היד של פלינט.', 'The red crosses, and the instructions in Flint’s handwriting.'),
    ('הם צעקו: המפה! המפה של פלינט!', 'They shouted: the map! Flint’s map!'),
    ("וג'ורג' אמר: טוב, אבל איך נצא עם המטמון בלי ספינה?", 'And George said: fine, but how do we get out with the treasure without a ship?'),
    ('סילבר אמר: זה העניין שלי, אני מפקד או לא?', 'Silver said: that is my business, am I captain or not?'),
    ('וכולם צעקו: סילבר! סילבר מפקד!', 'And they all shouted: Silver! Silver for captain!')),
  P(('בבוקר הרופא בא למבנה, כמו בכל יום, לטפל בחולים.', 'In the morning the doctor came to the building, as on every day, to treat the wounded.'),
    ('והוא ראה אותי, והפנים שלו השתנו, אבל הוא לא דיבר.', 'And he saw me, and his face changed, but he did not speak.'),
    ('הוא טיפל בחולים, ואז אמר: אני רוצה לדבר עם הילד.', 'He treated the sick, and then said: I want to speak with the boy.'),
    ("סילבר אמר: ג'ים, אתה נשבע שאתה לא בורח?", 'Silver said: Jim, do you swear you will not run?'),
    ('נשבעתי.', 'I swore.'),
    ('ויצאנו מחוץ לגדר, אני והרופא.', 'And we went outside the fence, the doctor and I.'),
    ("הרופא אמר: ג'ים, למה ברחת?", 'The doctor said: Jim, why did you run away?'),
    ('וסיפרתי לו הכול, והספינה, והנדס.', 'And I told him everything, and the ship, and Hands.'),
    ("הוא אמר: הספינה! ג'ים, כל פעם אתה מציל אותנו.", 'He said: the ship! Jim, every time you save us.'),
    ('והוא אמר: עכשיו תברח איתי.', 'And he said: now run away with me.'),
    ('אמרתי: נשבעתי לסילבר.', 'I said: I swore to Silver.'),
    ('והרופא שתק, ואמר: טוב, אתה גבר.', 'And the doctor was silent, and said: fine, you are a man.'))]),

 ('The Treasure Hunt', 'מחפשים את המטמון', [
  P(('יצאנו לחפש את המטמון, כולנו, ואני קשור בחבל לסילבר.', 'We set out to look for the treasure, all of us, and I tied with a rope to Silver.'),
    ('הם היו שמחים, ושרו, ואיתם מכושים ואוכל.', 'They were happy, and sang, and with them picks and food.'),
    ('והרופא אמר לי לפני שיצאנו: תישאר ליד סילבר, אל תלך רחוק ממנו.', 'And the doctor had said to me before we left: stay beside Silver, do not go far from him.'),
    ('ולא הבנתי למה.', 'And I did not understand why.'),
    ('ההוראות היו: עץ גבוה על הכתף של גבעת המשקפת.', 'The instructions were: a tall tree on the shoulder of Spyglass Hill.'),
    ('ועלינו על הגבעה, השמש חמה, וסילבר מתקשה על המקל שלו.', 'And we climbed the hill, the sun hot, and Silver struggling on his crutch.')),
  P(('ובאמצע הדרך, אחד צעק.', 'And halfway, one shouted.'),
    ('הוא מצא מתחת לעץ שלד של בן אדם.', 'He had found under a tree the skeleton of a man.'),
    ('הוא שכב ישר, והידיים מעל הראש, בקו ישר.', 'It lay straight, and the arms above the head, in a straight line.'),
    ('סילבר אמר: זה לא מקרה, זה חץ.', 'Silver said: this is no accident, this is an arrow.'),
    ('פלינט שם אותו ככה, כדי להראות את הדרך.', 'Flint put him like that, to show the way.'),
    ('ואחד אמר בקול רועד: פלינט, הוא היה לוקח שישה איתו, וחוזר לבד.', 'And one said in a trembling voice: Flint, he would take six with him, and come back alone.'),
    ('וזה אחד מהשישה.', 'And this is one of the six.')),
  P(('הם המשיכו, אבל בלי שירה.', 'They went on, but without singing.'),
    ('ואז, מאחורי העצים, בא קול.', 'And then, from behind the trees, came a voice.'),
    ('קול דק ששר: חמישה עשר אנשים על הארגז של המת.', 'A thin voice singing: fifteen men on the dead man’s chest.'),
    ('כולם עצרו, והפנים שלהם נהיו לבנות.', 'They all stopped, and their faces went white.'),
    ('אחד אמר: זה פלינט!', 'One said: that is Flint!'),
    ('והקול צעק: תביא לי רום!', 'And the voice cried: bring me rum!'),
    ('ואלה היו המילים האחרונות של פלינט לפני שמת.', 'And those had been Flint’s last words before he died.'),
    ('האנשים התחילו לרעוד, ואחד אמר: אנחנו חוזרים.', 'The men began to shake, and one said: we go back.'),
    ('אבל סילבר אמר: זה לא רוח, לרוחות אין הד, ולזה יש הד.', 'But Silver said: this is no ghost, ghosts have no echo, and this one has an echo.'),
    ('ואז אמר: אני מכיר את הקול הזה, זה בן גאן!', 'And then said: I know this voice, that is Ben Gunn!'),
    ('וכולם צחקו, כי מבן גאן אף אחד לא מפחד.', 'And they all laughed, because no one is afraid of Ben Gunn.')),
  P(('הם הגיעו לעץ הגדול, ורצו קדימה.', 'They reached the big tree, and ran ahead.'),
    ('וסילבר מושך אותי אחריו, העיניים שלו מבריקות, והפנים שלו לא פנים של חבר.', 'And Silver dragged me after him, his eyes shining, and his face not a friend’s face.'),
    ('ואז כולם עצרו, ליד בור.', 'And then they all stopped, by a pit.'),
    ('בור גדול, ישן, ובו ידית שבורה של מכוש, וארגזים פתוחים.', 'A big pit, old, and in it a broken pick handle, and open crates.'),
    ('וריק.', 'And empty.'),
    ('המטמון הלך, מישהו לקח אותו מזמן.', 'The treasure was gone, someone had taken it long ago.'),
    ('סילבר הסתכל בו שנייה, ואז שם ביד שלי אקדח, ולחש: תהיה מוכן.', 'Silver looked into it a second, and then put a pistol in my hand, and whispered: be ready.'),
    ('והפנים שלו השתנו שוב, והוא עמד לידי, נגד האנשים שלו.', 'And his face changed again, and he stood beside me, against his men.')),
  P(('השישה יצאו מהבור, והפנים שלהם שחורות מכעס.', 'The six came out of the pit, and their faces black with anger.'),
    ("ג'ורג' אמר: זה סילבר! הוא זה שידע! הוא והילד!", 'George said: it is Silver! He is the one who knew! He and the boy!'),
    ('והוא הרים את האקדח שלו.', 'And he raised his pistol.'),
    ('ובאותו רגע היו שלושה קולות של ירי מהעצים.', 'And in that moment three shots came from the trees.'),
    ("ג'ורג' נפל לבור, ועוד אחד נפל לידו, והאחרים ברחו.", 'George fell into the pit, and another fell beside him, and the others fled.'),
    ('ומהעצים יצאו הרופא, וגריי, ובן גאן, והרובים מעשנים.', 'And out of the trees came the doctor, and Gray, and Ben Gunn, and the guns smoking.'),
    ("סילבר אמר: רופא! באת בזמן, אני וג'ים היינו מתים.", 'Silver said: doctor! You came in time, Jim and I were about to die.'),
    ('ובן גאן אמר, וצחק: אני, אני זה שלקחתי את המטמון, לפני שלוש שנים.', 'And Ben Gunn said, and laughed: me, I am the one who took the treasure, three years ago.'),
    ('והוא במערה שלי, כולו.', 'And it is in my cave, all of it.')),
  P(('וככה הבנתי הכול.', 'And so I understood everything.'),
    ('הרופא ידע מבן גאן שהמטמון לא במקום שלו.', 'The doctor knew from Ben Gunn that the treasure was not in its place.'),
    ('אז הוא נתן לסילבר את המפה, כי היא נהייתה נייר ריק.', 'So he gave Silver the map, because it had become an empty paper.'),
    ('ונתן לו את המבנה, כי המערה טובה יותר, והמטמון בה.', 'And gave him the building, because the cave is better, and the treasure is in it.'),
    ('ונשאנו את הזהב לספינה ימים, שק אחרי שק.', 'And we carried the gold to the ship for days, sack after sack.'),
    ("וסילבר עבד איתנו, וצחק, ואמר: ג'ים, שנינו ניצלנו.", 'And Silver worked with us, and laughed, and said: Jim, the two of us survived.'),
    ('ובלילה האחרון לפני שהגענו לנמל הראשון, סילבר נעלם.', 'And on the last night before we reached the first port, Silver vanished.'),
    ('ואיתו שק זהב, והתוכי שלו.', 'And with him a sack of gold, and his parrot.'),
    ('ואני לא הצטערתי, ולא ידעתי למה.', 'And I was not sorry, and did not know why.'),
    ('ועד היום אני חולם על האי, ושומע את התוכי צועק: מטבעות זהב! מטבעות זהב!', 'And to this day I dream about the island, and hear the parrot screeching: pieces of eight! Pieces of eight!'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('treasure', {'en': 'Treasure Island', 'he': 'אי המטמון'},
                          'intermediate', CHAPTERS, unit='Chapter', unit_he='פרק',
                          shelf=13, meta=META))
