#!/usr/bin/env python3
"""שבעת מסעות סינדבאד — the seven voyages, retold in modern Hebrew, graded to intermediate.

The Hebrew twin of pipeline/book_sindbad.py. Sindbad comes out of the Thousand and One Nights —
medieval, anonymous, public domain by age — and these are retellings from the traditional plots
rather than a translation of any edition.

WHY IT SITS HERE. Seven voyages is seven times the same sentence pattern with different nouns
in it: he sailed, the ship broke, he found, he came home rich. A learner who has read the first
voyage can read the third almost without help, and that experience — reading Hebrew fast enough
to forget you are reading — is what the intermediate tier is for. It is also the one book on
this shelf whose story is native to the region on both sides of the Green Line.

Deliberately unpointed; the vowels are looked up at ingest.

Run:  python3 pipeline/he_book_sindbad.py --lang he            # check
      python3 pipeline/he_book_sindbad.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'The Seven Voyages of Sindbad, from the Thousand and One Nights',
        'author': 'traditional', 'year': 'medieval',
        'status': 'public domain — medieval, anonymous'}

CHAPTERS = [
 ('The Porter and the Sailor', 'הסבל והמלח', [
  P(('בבגדאד, בימים של המלך הגדול, היה סבל עני, ושמו סינדבאד.', 'In Baghdad, in the days of the great king, there was a poor porter, and his name was Sindbad.'),
    ('הוא נשא את הדברים של האנשים על הראש שלו מהבוקר עד הערב.', 'He carried people’s things on his head from morning to evening.'),
    ('ביום חם מאוד הוא נשא משא כבד, והתעייף.', 'On a very hot day he carried a heavy load, and grew tired.'),
    ('הוא עצר לפני בית גדול, עם שער רחב וגן.', 'He stopped in front of a big house, with a wide gate and a garden.'),
    ('ומבפנים הוא שמע מוזיקה, וצחוק, וריח של אוכל טוב.', 'And from inside he heard music, and laughter, and a smell of good food.')),
  P(('הוא ישב על ספסל ליד השער, ושם את המשא לידו.', 'He sat on a bench by the gate, and put the load beside him.'),
    ('ואמר בקול, לעצמו: אלוהים, מה ההבדל ביני ובין בעל הבית הזה?', 'And said aloud, to himself: God, what is the difference between me and the owner of this house?'),
    ('הוא יושב בצל ואוכל, ואני נושא בשמש ורעב.', 'He sits in the shade and eats, and I carry in the sun and go hungry.'),
    ('שנינו בני אדם, אז למה הוא למעלה ואני למטה?', 'We are both human beings, so why is he above and I below?'),
    ('והוא לא ידע שבעל הבית עומד בחלון, ושומע אותו.', 'And he did not know that the owner of the house was standing at the window, and hearing him.')),
  P(('אחרי זמן קצר יצא משרת ואמר לו: האדון שלי רוצה לראות אותך.', 'A little later a servant came out and said to him: my master wants to see you.'),
    ('הסבל פחד, ואמר: לא אמרתי שום דבר רע.', 'The porter was afraid, and said: I said nothing bad.'),
    ('המשרת אמר: בוא, אף אחד לא יעשה לך רע.', 'The servant said: come, no one will hurt you.'),
    ('והסבל נכנס לאולם גדול, ובו אנשים יושבים, ואוכל, ופירות, וזמרים.', 'And the porter went into a big hall, and in it people sitting, and food, and fruit, and singers.'),
    ('ובראש ישב איש זקן, עם פנים שקטות, וזקן לבן.', 'And at the head sat an old man, with a calm face, and a white beard.')),
  P(('האיש אמר: מה השם שלך?', 'The man said: what is your name?'),
    ('הוא אמר: סינדבאד הסבל.', 'He said: Sindbad the porter.'),
    ('האיש צחק ואמר: וגם השם שלי סינדבאד, סינדבאד המלח.', 'The man laughed and said: and my name is Sindbad too, Sindbad the sailor.'),
    ('ושמעתי מה שאמרת ליד השער.', 'And I heard what you said by the gate.'),
    ('ואתה צודק לשאול, אבל את הכסף הזה לא קיבלתי בקלות.', 'And you are right to ask, but this money I did not get easily.'),
    ('על כל מטבע שלי שילמתי בפחד, ברעב ובמוות.', 'For every coin of mine I paid in fear, in hunger and in death.'),
    ('שב, תאכל איתנו, ואני אספר לך על שבעה מסעות.', 'Sit, eat with us, and I will tell you about seven voyages.'),
    ('וכל ערב, כשאני מסיים, אני נותן לך מאה מטבעות זהב.', 'And every evening, when I finish, I give you a hundred gold coins.'),
    ('והסבל ישב, וסינדבאד המלח התחיל לספר.', 'And the porter sat, and Sindbad the sailor began to tell.'))]),

 ('The First Ship', 'הספינה הראשונה', [
  P(('סינדבאד אמר: אבא שלי היה סוחר גדול, והוא מת כשהייתי צעיר.', 'Sindbad said: my father was a great merchant, and he died when I was young.'),
    ('ירשתי ממנו הרבה כסף, ובית, ואדמות.', 'I inherited from him a lot of money, and a house, and lands.'),
    ('ואני הייתי צעיר וטיפש, וחשבתי שכסף לא נגמר.', 'And I was young and foolish, and thought that money never runs out.'),
    ('בזבזתי על חברים, על אוכל, ועל מסיבות.', 'I spent on friends, on food, and on parties.'),
    ('וכל יום הבית שלי היה מלא אנשים, וכל לילה מוזיקה.', 'And every day my house was full of people, and every night music.')),
  P(('ויום אחד התעוררתי, וראיתי שהארגז ריק.', 'And one day I woke up, and saw that the chest was empty.'),
    ('והחברים שאכלו אצלי לא באו יותר.', 'And the friends who used to eat at my house did not come any more.'),
    ('ישבתי לבד, ונזכרתי במילה שאבא שלי היה אומר.', 'I sat alone, and remembered a word my father used to say.'),
    ('הוא היה אומר: הקבר טוב מהעוני, והעבודה טובה משניהם.', 'He used to say: the grave is better than poverty, and work is better than both.'),
    ('אז קמתי, ומכרתי מה שנשאר לי: הרהיטים, הבגדים, והבית.', 'So I got up, and sold what was left to me: the furniture, the clothes, and the house.'),
    ('ואספתי שלושת אלפים מטבעות.', 'And I gathered three thousand coins.')),
  P(('קניתי בהם סחורה: בד, ובושם, ודברים קלים ויקרים.', 'With them I bought goods: cloth, and perfume, and things light and expensive.'),
    ('וירדתי לנמל, ועליתי על ספינה עם סוחרים שנסעו להודו.', 'And I went down to the port, and boarded a ship with merchants going to India.'),
    ('זאת הייתה הפעם הראשונה שראיתי את הים.', 'It was the first time I saw the sea.'),
    ('גדול, וכחול, ובלי סוף.', 'Big, and blue, and without end.'),
    ('עמדתי על הסיפון שעות, והסתכלתי, והלב שלי דפק.', 'I stood on the deck for hours, and looked, and my heart beat.')),
  P(('הים היה שקט בהתחלה, והרוח איתנו.', 'The sea was calm at first, and the wind with us.'),
    ('כל פעם שהגענו לאי, ירדנו ומכרנו וקנינו.', 'Every time we reached an island, we went down and sold and bought.'),
    ('ובכל אי הרווחתי יותר מהאי הקודם.', 'And on every island I earned more than on the island before.'),
    ('אמרתי: העבודה הזאת קלה, למה אנשים מפחדים מהים?', 'I said: this work is easy, why are people afraid of the sea?'),
    ('וסינדבאד הסבל צחק, ואמר: ככה כל אחד חושב בהתחלה.', 'And Sindbad the porter laughed, and said: that is what everyone thinks at first.'),
    ('סינדבאד המלח אמר: נכון, ואז תשמע מה קרה.', 'Sindbad the sailor said: right, and listen to what happened.'))]),

 ('The Island That Moved', 'האי שזז', [
  P(('אחרי שבועות ראינו אי קטן, ירוק, באמצע הים.', 'After weeks we saw a small island, green, in the middle of the sea.'),
    ('הוא היה כמו גן שיוצא מהמים.', 'It was like a garden coming out of the water.'),
    ('המפקד עצר את הספינה לידו, וכולנו ירדנו.', 'The captain stopped the ship beside it, and we all went down.'),
    ('אחד הדליק אש, אחד התחיל לבשל, ואחד הלך לכבס את הבגדים שלו.', 'One lit a fire, one began to cook, and one went to wash his clothes.'),
    ('ואני הלכתי על הקצה, והסתכלתי על המים.', 'And I walked along the edge, and looked at the water.')),
  P(('ופתאום האדמה מתחתינו רעדה.', 'And suddenly the ground beneath us shook.'),
    ('המפקד צעק מהספינה: תעלו! תעלו מהר!', 'The captain shouted from the ship: get up! Get up quickly!'),
    ('זה לא אי! זה דג!', 'This is not an island! This is a fish!'),
    ('דג כל כך גדול, שישן מאה שנה, וצמחו עליו עצים ועשב.', 'A fish so big, that had slept a hundred years, and trees and grass had grown on it.'),
    ('וכשהרגיש את האש על הגב שלו, הוא התעורר.', 'And when it felt the fire on its back, it woke.'),
    ('והוא התחיל לרדת למים.', 'And it began to go down into the water.')),
  P(('האנשים רצו לספינה, ומי שהגיע הגיע, ומי שלא הגיע, טבע.', 'The people ran to the ship, and whoever reached it reached it, and whoever did not, drowned.'),
    ('ואני הייתי הכי רחוק.', 'And I was the farthest.'),
    ('הדג ירד, המים כיסו אותי, והתחלתי לשחות.', 'The fish went down, the water covered me, and I began to swim.'),
    ('והספינה, מפחד, פתחה את המפרש והלכה בלי לחכות.', 'And the ship, from fear, opened its sail and went without waiting.'),
    ('ראיתי אותה הולכת רחוק, ואני צועק, ואף אחד לא שמע אותי.', 'I saw it going away, and I shouting, and no one heard me.')),
  P(('חתיכת עץ מהספינה צפה לידי, ותפסתי אותה.', 'A piece of wood from the ship floated beside me, and I grabbed it.'),
    ('ונשארתי עליה יום ולילה, והגלים זורקים אותי.', 'And I stayed on it a day and a night, and the waves throwing me.'),
    ('וחשבתי: זהו, זה הסוף שלי, אחרי המסע הראשון.', 'And I thought: that is it, this is my end, after the first voyage.'),
    ('ובסוף הלילה, הגלים זרקו אותי על חוף של אי אמיתי.', 'And at the end of the night, the waves threw me onto the shore of a real island.'),
    ('זחלתי על החול, וישנתי כמו מת.', 'I crawled on the sand, and slept like a dead man.'),
    ('וכשהתעוררתי, הרגליים שלי היו נפוחות, ולא יכולתי לעמוד.', 'And when I woke, my legs were swollen, and I could not stand.'))]),

 ('The King of the Sea Horses', 'המלך וסוסי הים', [
  P(('זחלתי על הידיים עד שהגעתי לעצים עם פירות, ואכלתי.', 'I crawled on my hands until I reached trees with fruit, and ate.'),
    ('ושתיתי ממעיין, והכוח שלי חזר אחרי כמה ימים.', 'And I drank from a spring, and my strength came back after some days.'),
    ('והלכתי באי, עד שראיתי דבר מוזר.', 'And I walked on the island, until I saw a strange thing.'),
    ('סוסה קשורה ליד הים, יפה מאוד, ולבד.', 'A mare tied by the sea, very beautiful, and alone.'),
    ('התקרבתי אליה, ושמעתי קול מתחת לאדמה.', 'I approached her, and heard a voice from under the ground.')),
  P(('איש יצא מבור, ומשך אותי איתו למטה.', 'A man came out of a hole, and pulled me down with him.'),
    ('הוא אמר: תשתוק, ואל תזוז.', 'He said: be quiet, and do not move.'),
    ('וראינו מהבור: סוס יצא מהים, המלך של סוסי הים.', 'And we saw from the hole: a horse came out of the sea, the king of the sea horses.'),
    ('והוא התקרב לסוסה, ואחר כך חזר לים לבד.', 'And he approached the mare, and afterwards went back to the sea alone.'),
    ('האיש אמר: ככה אנחנו עושים כל חודש.', 'The man said: this is what we do every month.'),
    ('אנחנו קושרים סוסה על החוף, סוסי הים באים, ולסוס הצעיר שנולד אין דומה.', 'We tie a mare on the shore, the sea horses come, and the foal that is born has no equal.'),
    ('אנחנו המשרתים של המלך, ואלה הסוסים שלו.', 'We are the servants of the king, and these are his horses.')),
  P(('הם לקחו אותי אל המלך, וסיפרתי לו את הסיפור שלי.', 'They took me to the king, and I told him my story.'),
    ('הוא היה מלך נדיב, ואמר: סינדבאד, אלוהים הציל אותך בגלל סיבה.', 'He was a generous king, and said: Sindbad, God saved you for a reason.'),
    ('והוא עשה אותי אחראי על הנמל של העיר שלו.', 'And he made me responsible for the port of his city.'),
    ('התחלתי לרשום את הספינות שבאות והולכות, ולשאול כל מפקד: מאיפה? ולאן?', 'I began to write down the ships that came and went, and to ask every captain: from where? And to where?'),
    ('ושאלתי כל אחד על בגדאד, ואף אחד לא שמע עליה.', 'And I asked everyone about Baghdad, and no one had heard of it.'),
    ('ועברו חודשים.', 'And months passed.')),
  P(('ויום אחד נכנסה לנמל ספינה, והכרתי אותה.', 'And one day a ship came into the port, and I knew it.'),
    ('זאת הייתה הספינה שלי, שעזבה אותי בים.', 'It was my ship, that had left me in the sea.'),
    ('המפקד ירד, ראה אותי, ולא האמין לעיניים שלו.', 'The captain came down, saw me, and did not believe his eyes.'),
    ('הוא אמר: סינדבאד? אתה טבעת!', 'He said: Sindbad? You drowned!'),
    ('אמרתי: אלוהים נתן לי חיים חדשים.', 'I said: God gave me a new life.'),
    ('והסחורה שלי עדיין הייתה על הספינה, אף אחד לא נגע בה.', 'And my goods were still on the ship, no one had touched them.'),
    ('מכרתי אותה במחיר הכי טוב, נתתי למלך מתנה, ונפרדתי ממנו.', 'I sold them at the best price, gave the king a gift, and said goodbye to him.'),
    ('וחזרתי לבגדאד עשיר, אחרי שהייתי מת.', 'And I returned to Baghdad rich, after having been dead.'),
    ('וסינדבאד שתק, נתן לסבל מאה מטבעות, ואמר: בוא מחר.', 'And Sindbad was silent, gave the porter a hundred coins, and said: come tomorrow.'))]),

 ('Bored at Home', 'משעמם בבית', [
  P(('למחרת הסבל חזר, והוא ישב באותו מקום.', 'The next day the porter came back, and sat in the same place.'),
    ('סינדבאד המלח אמר: חייתי בבגדאד שנה, בנוחות ובעושר.', 'Sindbad the sailor said: I lived in Baghdad a year, in comfort and wealth.'),
    ('קניתי בית גדול מהראשון, וגן, ומשרתים.', 'I bought a house bigger than the first, and a garden, and servants.'),
    ('וכל יום ישבתי ואכלתי ושמעתי מוזיקה.', 'And every day I sat and ate and listened to music.'),
    ('ואחרי חודשים התחלתי להרגיש משהו מוזר.', 'And after months I began to feel something strange.')),
  P(('היה לי משעמם.', 'I was bored.'),
    ('כל יום כמו היום שלפניו, וכל ארוחה כמו הארוחה שלפניה.', 'Every day like the day before, and every meal like the meal before.'),
    ('וחלמתי על הים, ועל האיים, ועל האנשים שראיתי.', 'And I dreamed about the sea, and the islands, and the people I had seen.'),
    ('אפילו לפחד התגעגעתי.', 'Even the fear I missed.'),
    ('הסבל אמר: אתה מתגעגע לפחד? אתה משוגע!', 'The porter said: you miss the fear? You are mad!'),
    ('סינדבאד צחק ואמר: אולי, אבל מי שראה את הים פעם, הבית נהיה קטן עליו.', 'Sindbad laughed and said: perhaps, but for one who has seen the sea once, the house becomes small on him.')),
  P(('אז קניתי סחורה חדשה, ירדתי לנמל, ועליתי על ספינה.', 'So I bought new goods, went down to the port, and boarded a ship.'),
    ('והפעם ידעתי מה אני עושה, או ככה חשבתי.', 'And this time I knew what I was doing, or so I thought.'),
    ('נסענו מאי לאי, ומכרנו וקנינו.', 'We sailed from island to island, and sold and bought.'),
    ('ויום אחד הגענו לאי יפה, ובו עצים וציפורים ומעיין.', 'And one day we reached a beautiful island, with trees and birds and a spring.'),
    ('ירדתי לבד, ישבתי מתחת לעץ, אכלתי, ואז ישנתי.', 'I went down alone, sat under a tree, ate, and slept.'),
    ('ישנתי הרבה.', 'I slept a lot.')),
  P(('וכשהתעוררתי, השמש הייתה נמוכה, והחוף ריק.', 'And when I woke, the sun was low, and the shore was empty.'),
    ('רצתי לחוף, וראיתי את הספינה נקודה רחוקה באופק.', 'I ran to the shore, and saw the ship a far dot on the horizon.'),
    ('הם שכחו אותי.', 'They had forgotten me.'),
    ('צעקתי, ונופפתי בבגדים שלי, ואף אחד לא ראה אותי.', 'I shouted, and waved my clothes, and no one saw me.'),
    ('וישבתי על החול, והכיתי את הראש שלי בידיים.', 'And I sat on the sand, and struck my head with my hands.'),
    ('ואמרתי: פעם ניצלתי מטביעה, ועכשיו אני מת מרעב לבד.', 'And I said: once I was saved from drowning, and now I die of hunger alone.'),
    ('ולמה? כי היה לי משעמם בבית.', 'And why? Because I was bored at home.'))]),

 ('The Great White Dome', 'הכיפה הלבנה', [
  P(('למחרת עליתי על העץ הכי גבוה, והסתכלתי סביב האי.', 'The next day I climbed the tallest tree, and looked around the island.'),
    ('אין בתים, ואין עשן, ואין אנשים.', 'No houses, and no smoke, and no people.'),
    ('אבל רחוק, באמצע האי, ראיתי משהו לבן וגדול, שמבריק בשמש.', 'But far away, in the middle of the island, I saw something white and big, that shone in the sun.'),
    ('אמרתי: זאת כיפה, כלומר יש מסגד, כלומר יש אנשים.', 'I said: that is a dome, that is, there is a mosque, that is, there are people.'),
    ('וירדתי והלכתי לכיוון שלה חצי יום.', 'And I came down and walked toward it half a day.')),
  P(('כשהגעתי, הקפתי אותה, וחיפשתי דלת.', 'When I arrived, I went around it, and looked for a door.'),
    ('אין דלת, ואין חלון, ואין אבנים.', 'No door, and no window, and no stones.'),
    ('היא הייתה חלקה, ולבנה, וחמה.', 'It was smooth, and white, and warm.'),
    ('הקפתי אותה חמישים פעמים, ולא הבנתי מה היא.', 'I went around it fifty steps, and did not understand what it was.'),
    ('ופתאום העולם נהיה חשוך.', 'And suddenly the world went dark.'),
    ('הסתכלתי למעלה, וראיתי ענן גדול ושחור שמכסה את השמש.', 'I looked up, and saw a big black cloud covering the sun.'),
    ('אבל הענן זז, והיו לו שתי כנפיים.', 'But the cloud moved, and it had two wings.')),
  P(('זאת הייתה ציפור.', 'It was a bird.'),
    ('ציפור גדולה מספינה, והכנף שלה מכסה את האדמה.', 'A bird bigger than a ship, and its wing covered the ground.'),
    ('ונזכרתי בסיפור ששמעתי מהמלחים, על ציפור ענקית.', 'And I remembered a story I had heard from the sailors, about a giant bird.'),
    ('היא צדה פילים, ואוכלת אותם באוויר.', 'It hunts elephants, and eats them in the air.'),
    ('והבנתי: הכיפה הלבנה היא לא כיפה.', 'And I understood: the white dome was no dome.'),
    ('זאת הביצה של הציפור.', 'This was the bird’s egg.'),
    ('והציפור ירדה עליה, כיסתה אותה בכנפיים, וישנה.', 'And the bird came down on it, covered it with its wings, and slept.')),
  P(('ובא לי רעיון, מפחד או משיגעון, אני לא יודע.', 'And an idea came to me, from fear or from madness, I do not know.'),
    ('פתחתי את הבד שעל הראש שלי, וקשרתי את עצמי לרגל של הציפור.', 'I undid the cloth on my head, and tied myself to the bird’s leg.'),
    ('הרגל שלה הייתה גדולה מגזע של עץ.', 'Its leg was bigger than the trunk of a tree.'),
    ('ואמרתי: מחר בבוקר, כשהיא תעוף, היא תיקח אותי איתה.', 'And I said: tomorrow morning, when it flies, it will take me with it.'),
    ('לאן? אני לא יודע, אבל כל מקום טוב מאי ריק.', 'Where to? I do not know, but any place is better than an empty island.'),
    ('ונשארתי קשור כל הלילה, ולא ישנתי.', 'And I stayed tied all night, and did not sleep.'),
    ('ועם האור הראשון, הציפור פתחה את הכנפיים, ועפה.', 'And with the first light, the bird opened its wings, and flew.'))]),

 ('The Valley of Diamonds', 'עמק היהלומים', [
  P(('היא עפה למעלה, למעלה, עד שהאי נהיה נקודה.', 'It flew up, up, until the island became a dot.'),
    ('ואני תלוי על הרגל שלה, והרוח מכה בי, והעננים סביבי.', 'And I hanging from its leg, and the wind striking me, and the clouds around me.'),
    ('עצמתי את העיניים, ואמרתי תפילה.', 'I closed my eyes, and said a prayer.'),
    ('ואחרי שעות הרגשתי שהיא יורדת.', 'And after hours I felt it going down.'),
    ('היא ירדה על אדמה של סלעים, ועמדה.', 'It came down on rocky ground, and stood.'),
    ('התרתי את הבד מהר, ורצתי רחוק ממנה.', 'I untied the cloth quickly, and ran far from it.'),
    ('והיא לא ראתה אותי, היא תפסה נחש גדול, ועפה.', 'And it did not see me, it seized a big snake, and flew.')),
  P(('וישבתי והסתכלתי סביבי.', 'And I sat and looked around me.'),
    ('הייתי בעמק עמוק, וסביבו הרים גבוהים מכל צד.', 'I was in a deep valley, and around it high mountains on every side.'),
    ('אין דרך למעלה, ואין עצים, ואין מים.', 'No way up, and no trees, and no water.'),
    ('והאדמה כולה אבנים שמבריקות.', 'And the ground all shining stones.'),
    ('הרמתי אחת, וראיתי אותה: יהלום.', 'I picked one up, and saw it: a diamond.'),
    ('כל העמק יהלומים, יותר מכל האוצרות של המלכים.', 'The whole valley diamonds, more than all the treasures of the kings.'),
    ('ואמרתי: איזה איש עשיר אני, ואני הולך למות כאן.', 'And I said: what a rich man I am, and I am going to die here.')),
  P(('ואז ראיתי מה חי בעמק.', 'And then I saw what lived in the valley.'),
    ('נחשים, נחשים גדולים, ארוכים כמו עץ תמר, ישנים ביום ויוצאים בלילה.', 'Snakes, big snakes, long as a palm tree, sleeping by day and coming out at night.'),
    ('ואותם הציפור צדה.', 'And those the bird hunted.'),
    ('כשבא הלילה, חיפשתי מערה, מצאתי אחת קטנה, נכנסתי, וסגרתי את הפתח באבן.', 'When night came, I looked for a cave, found a small one, went in, and closed the opening with a stone.'),
    ('וכל הלילה שמעתי את הנחשים זוחלים בחוץ.', 'And all night I heard the snakes crawling outside.'),
    ('ולא ישנתי.', 'And I did not sleep.')),
  P(('בבוקר יצאתי, חצי מת מעייפות ומפחד.', 'In the morning I came out, half dead from tiredness and fear.'),
    ('והלכתי בעמק, ופתאום נפל לידי משהו מלמעלה.', 'And I walked in the valley, and suddenly something fell beside me from above.'),
    ('חתיכת בשר, גדולה, וטרייה.', 'A piece of meat, big, and fresh.'),
    ('הסתכלתי למעלה, ולא ראיתי אף אחד, ההר גבוה מאוד.', 'I looked up, and saw no one, the mountain was very high.'),
    ('ואז נפלה חתיכה שנייה, ושלישית.', 'And then a second piece fell, and a third.'),
    ('ונזכרתי בסיפור אחר מהמלחים.', 'And I remembered another story from the sailors.'),
    ('סיפור על סוחרי היהלומים, ואיך הם מוציאים יהלומים מעמק שאף אחד לא יכול לרדת אליו.', 'A story about the diamond merchants, and how they get diamonds out of a valley no one can go down into.'))]),

 ('The Meat and the Eagles', 'הבשר והנשרים', [
  P(('הסוחרים עומדים על ההר, וזורקים בשר לעמק.', 'The merchants stand on the mountain, and throw meat into the valley.'),
    ('הבשר נופל על היהלומים, והיהלומים נשארים עליו.', 'The meat falls on the diamonds, and the diamonds stick to it.'),
    ('ואז באים הנשרים, ולוקחים את הבשר לקנים שלהם על ההר.', 'And then the eagles come, and take the meat to their nests on the mountain.'),
    ('והסוחרים צועקים ומפחידים את הנשרים, ולוקחים את היהלומים מהבשר.', 'And the merchants shout and frighten the eagles, and take the diamonds from the meat.'),
    ('ככה הם מוציאים את היהלומים, ואף אחד לא יורד לעמק.', 'That is how they get the diamonds out, and no one goes down into the valley.'),
    ('כי מי שיורד, לא עולה.', 'Because whoever goes down does not come up.')),
  P(('אמרתי: אם הבשר עולה, אני עולה עם הבשר.', 'I said: if the meat goes up, I go up with the meat.'),
    ('מילאתי את הכיסים ואת החגורה ביהלומים, הכי גדולים שמצאתי.', 'I filled my pockets and my belt with diamonds, the biggest I found.'),
    ('וקשרתי את עצמי בבד מתחת לחתיכת הבשר הכי גדולה.', 'And I tied myself with the cloth under the biggest piece of meat.'),
    ('ושכבתי על הגב, הפנים למעלה, וחיכיתי.', 'And I lay on my back, face up, and waited.'),
    ('והשמש מעליי, והנחשים ישנים סביבי.', 'And the sun above me, and the snakes sleeping around me.')),
  P(('ואז שמעתי את הכנפיים.', 'And then I heard the wings.'),
    ('נשר גדול ירד, תפס את הבשר, ועף.', 'A big eagle came down, seized the meat, and flew.'),
    ('ואני איתו, תלוי מתחת לבשר כמו מת.', 'And I with it, hanging under the meat like a dead man.'),
    ('הוא העלה אותי מעל העמק, מעל ההר, והוא ישב על הקן שלו.', 'It carried me up above the valley, above the mountain, and landed on its nest.'),
    ('ובאותו רגע היו קולות ואבנים.', 'And in that moment there were shouts and stones.'),
    ('הסוחרים.', 'The merchants.'),
    ('הנשר עף בפחד, ואני התרתי את עצמי, והוא ישב, ועמדתי.', 'The eagle flew off in fear, and I untied myself and stood up.')),
  P(('הסוחר שבא לקחת את הבשר ראה אותי, וחזר אחורה.', 'The merchant who came to take the meat saw me, and stepped back.'),
    ('הוא אמר: מי אתה? בן אדם או שד?', 'He said: who are you? A human or a demon?'),
    ('אמרתי: בן אדם, וסוחר כמוך, והסיפור שלי ארוך.', 'I said: a human, and a merchant like you, and my story is long.'),
    ('והוא הסתכל על הבשר, ולא מצא בו אף יהלום, והיה עצוב.', 'And he looked at the meat, and found not one diamond in it, and was sad.'),
    ('אז פתחתי את החגורה, ונתתי לו אבנים גדולות ממה שהוא רואה בשנה.', 'So I opened my belt, and gave him stones bigger than he sees in a year.'),
    ('והוא שמח, ולקח אותי איתו, וסיפרתי לכל הסוחרים את הסיפור שלי.', 'And he was glad, and took me with him, and I told all the merchants my story.'),
    ('ואף אחד לא האמין, עד שראו את היהלומים.', 'And no one believed, until they saw the diamonds.'),
    ('וחזרתי לבגדאד בספינה שלהם, עשיר יותר מהפעם הראשונה.', 'And I returned to Baghdad on their ship, richer than the first time.'),
    ('וסינדבאד נתן לסבל מאה מטבעות, ואמר: מחר, המסע השלישי.', 'And Sindbad gave the porter a hundred coins, and said: tomorrow, the third voyage.'))]),

 ('The Hairy People', 'האנשים הקטנים', [
  P(('הסבל אמר ביום השלישי: ואחרי כל זה, חזרת לים?', 'The porter said on the third day: and after all that, you went back to sea?'),
    ('סינדבאד אמר: חזרתי, כי בן אדם שוכח את הכאב וזוכר את השמחה.', 'Sindbad said: I went back, because a person forgets the pain and remembers the joy.'),
    ('עליתי על ספינה גדולה, עם הרבה סוחרים, ונסענו חודשים.', 'I boarded a big ship, with many merchants, and we sailed for months.'),
    ('ויום אחד הרוח הסתובבה עלינו, וסחפה אותנו לכיוון שלא רצינו.', 'And one day the wind turned on us, and swept us in a direction we did not want.'),
    ('והמפקד נהיה חיוור, ואמר: זה האי של הקופים.', 'And the captain went pale, and said: this is the island of the apes.'),
    ('מי שמגיע אליו, לא חוזר.', 'Whoever reaches it does not come back.')),
  P(('לא יכולנו לברוח, הספינה עצרה, נגד הרצון שלנו.', 'We could not flee, the ship stopped, against our will.'),
    ('ומהעצים הם ירדו עלינו.', 'And from the trees they came down on us.'),
    ('אנשים קטנים, בגובה מטר, כולם שיער, והעיניים שלהם צהובות.', 'Small people, a metre tall, all hair, and their eyes yellow.'),
    ('לא קופים, ולא בני אדם, ומאות מהם.', 'Not apes, and not humans, and hundreds of them.'),
    ('הם עלו על הספינה כמו נמלים, ולא יכולנו להכות אותם, כי הם רבים.', 'They climbed onto the ship like ants, and we could not fight them, because they were many.'),
    ('הם חתכו את החבלים של העוגן, משכו את הספינה לחוף, וזרקו אותנו החוצה.', 'They cut the anchor ropes, pulled the ship to the shore, and threw us off.'),
    ('ולקחו את הספינה, והלכו איתה לים.', 'And they took the ship, and went with it to sea.')),
  P(('עמדנו על החוף, בלי ספינה, ובלי אוכל, באי שאנחנו לא מכירים.', 'We stood on the shore, without a ship, and without food, on an island we did not know.'),
    ('הלכנו פנימה, ומצאנו ארמון גדול, והדלת שלו פתוחה.', 'We walked inland, and found a big palace, and its door was open.'),
    ('נכנסנו, ומצאנו חצר, ובה הרבה עצמות, עצמות של בני אדם.', 'We went in, and found a courtyard, and in it many bones, human bones.'),
    ('ובור אש גדול, ומוטות ברזל ארוכים.', 'And a big fire pit, and long iron rods.'),
    ('אחד אמר: בואו נצא מכאן.', 'One said: let us get out of here.'),
    ('אבל היינו עייפים, והשמש שקעה, וישנו בחצר.', 'But we were tired, and the sun set, and we slept in the courtyard.')),
  P(('והתעוררנו מקול.', 'And we woke from a sound.'),
    ('האדמה רועדת, ודלת הארמון נפתחת.', 'The ground shaking, and the palace door opening.'),
    ('והוא נכנס.', 'And he came in.'),
    ('גבוה כמו עץ תמר, שחור כמו פחם, ועין אחת באמצע המצח.', 'Tall as a palm tree, black as coal, and one eye in the middle of the forehead.'),
    ('והשיניים שלו כמו שיניים של חזיר, והידיים שלו כמו ציפורניים.', 'And his teeth like the teeth of a pig, and his hands like claws.'),
    ('הוא עמד בדלת, והסתכל עלינו.', 'He stood in the door, and looked at us.'),
    ('וצחק.', 'And laughed.'))]),

 ('The Giant', 'הענק', [
  P(('הענק ישב על האדמה, הושיט את היד, והתחיל לגעת בנו אחד אחד.', 'The giant sat on the ground, reached out his hand, and began feeling us one by one.'),
    ('הוא תפס אחד, הפך אותו, לחץ על הזרוע שלו, וזרק אותו.', 'He grabbed one, turned him over, pressed his arm, and threw him.'),
    ('והבנתי שהוא מחפש את השמן ביותר.', 'And I understood that he was looking for the fattest.'),
    ('וכשהגיע אליי, לחץ אותי, מצא אותי רזה מרעב, וזרק אותי.', 'And when he came to me, he pressed me, found me thin from hunger, and threw me.'),
    ('ובסוף הוא תפס את המפקד, והוא היה שמן.', 'And at last he grabbed the captain, and he was fat.'),
    ('אני לא רוצה לספר לך מה הוא עשה לו.', 'I do not want to tell you what he did to him.'),
    ('אבל אחרי שעה הענק היה שבע, וישן ליד האש, והקול שלו בשינה כמו רעם.', 'But after an hour the giant was full, and slept by the fire, and his snoring like thunder.')),
  P(('כל יום אותו הדבר.', 'Every day the same thing.'),
    ('בבוקר הוא יוצא, וסוגר עלינו את הדלת, ובערב הוא חוזר, ולוקח אחד.', 'In the morning he goes out, and shuts the door on us, and in the evening he comes back, and takes one.'),
    ('וישבנו וחיכינו לתור, כמו כבשים.', 'And we sat and waited for our turn, like sheep.'),
    ('ולילה אחד אמרתי לאחרים: אנחנו נמות כאן, אחד אחד?', 'And one night I said to the others: are we going to die here, one by one?'),
    ('אחד אמר: ומה נעשה? הוא חזק מכולנו.', 'One said: and what shall we do? He is stronger than all of us.'),
    ('אמרתי: חזק, אבל הוא ישן, ולמי שישן אין כוח.', 'I said: strong, but he sleeps, and one who sleeps has no strength.')),
  P(('עשינו תוכנית.', 'We made a plan.'),
    ('ביום, כשהוא יצא, אספנו עצים מהחצר, בנינו רפסודה על החוף, והחבאנו אותה.', 'By day, when he went out, we gathered wood from the courtyard, built a raft on the shore, and hid it.'),
    ('ובלילה, כשהוא אכל וישן, לקחנו שני מוטות ברזל, ושמנו אותם באש.', 'And at night, when he had eaten and slept, we took two iron rods, and put them in the fire.'),
    ('עד שהם נהיו אדומים.', 'Until they became red.'),
    ('ועשרה מאיתנו נשאו אותם, והלכנו לאט, עד שעמדנו מעל הפנים שלו.', 'And ten of us carried them, and walked slowly, until we stood over his face.'),
    ('והעין האחת שלו הייתה סגורה.', 'And his one eye was closed.')),
  P(('אמרתי: עכשיו.', 'I said: now.'),
    ('ודחפנו את הברזל לעין שלו, בכל הכוח, כולנו יחד.', 'And we pushed the iron into his eye, with all our strength, all together.'),
    ('והענק צעק צעקה שהרעידה את הארמון.', 'And the giant gave a scream that shook the palace.'),
    ('והוא קם, והתחיל לחפש בידיים, ולשבור הכול.', 'And he got up, and began groping with his hands, and breaking everything.'),
    ('ואנחנו רצנו בין הרגליים שלו, יצאנו מהדלת, ורצנו לחוף.', 'And we ran between his legs, went out the door, and ran to the shore.'),
    ('והענק אחרינו, עיוור, צועק, והוא נופל.', 'And the giant after us, blind, screaming, and falling.'),
    ('וזרקנו את הרפסודה למים, וקפצנו עליה.', 'And we threw the raft into the water, and jumped on it.'))]),

 ('The Iron in the Fire', 'הברזל באש', [
  P(('חתרנו בידיים, והרפסודה הלכה רחוק מהחוף לאט לאט.', 'We paddled with our hands, and the raft moved away from the shore little by little.'),
    ('וחשבנו שניצלנו.', 'And we thought we were saved.'),
    ('ואז ראינו על החוף עוד שניים.', 'And then we saw on the shore two more.'),
    ('שני ענקים, באים עם העיוור, ומחזיקים אותו ביד.', 'Two giants, coming with the blind one, and holding him by the hand.'),
    ('והם עמדו על החוף, הרימו סלעים גדולים כמו בתים, וזרקו אותם עלינו.', 'And they stood on the shore, lifted rocks big as houses, and threw them at us.')),
  P(('הסלע הראשון נפל לידנו, והגל הפך חצי מהרפסודה.', 'The first rock fell beside us, and the wave overturned half the raft.'),
    ('והשני פגע באמצע, ושבר אותה.', 'And the second hit the middle, and broke it.'),
    ('והשלישי הרג את רוב מי שהיה איתי.', 'And the third killed most of those who were with me.'),
    ('ונשארנו שלושה, על חתיכת עץ, חותרים בכל הנשמה.', 'And we remained three, on a piece of wood, paddling with all our soul.'),
    ('עד שהענקים נהיו קטנים על החוף, ואז נעלמו.', 'Until the giants became small on the shore, and then vanished.'),
    ('ואנחנו בוכים על מי שמת, ומודים לאלוהים שאנחנו חיים.', 'And we weeping for those who died, and thanking God that we are alive.')),
  P(('הגלים זרקו אותנו אחרי יומיים על אי אחר.', 'The waves threw us after two days onto another island.'),
    ('היו בו פירות ומים, אז אכלנו ושתינו וישנו.', 'There were fruit and water on it, so we ate and drank and slept.'),
    ('ובלילה שמעתי קול של זחילה.', 'And at night I heard a sound of crawling.'),
    ('נחש, ארוך כמו ספינה, ועבה כמו חבית.', 'A snake, long as a ship, and thick as a barrel.'),
    ('ולפני שזזנו, הוא בלע אחד משני החברים שלי, בשינה.', 'And before we moved, it swallowed one of my two friends, in his sleep.'),
    ('ושמעתי את העצמות שלו נשברות בבטן שלו.', 'And I heard his bones breaking in its belly.'),
    ('והנחש זחל ליער, שבע.', 'And the snake crawled to the forest, full.')),
  P(('למחרת, אני והחבר שלי עלינו על עץ גבוה, וישנו על ענף.', 'The next day, my friend and I climbed a tall tree, and slept on a branch.'),
    ('ובלילה הנחש חזר.', 'And at night the snake came back.'),
    ('הוא הסתובב סביב העץ, ועלה, ועלה, והגיע לחבר שלי, ובלע אותו.', 'It wound around the tree, and climbed, and climbed, and reached my friend, and swallowed him.'),
    ('ואני מעליו על ענף, מסתכל, ולא יכול לעשות כלום.', 'And I above him on a branch, looking, and unable to do anything.'),
    ('והנחש ירד, והלך.', 'And the snake came down, and went.'),
    ('ונשארתי אני לבד, האחרון.', 'And I remained alone, the last.'),
    ('וידעתי שמחר בלילה, התור שלי.', 'And I knew that tomorrow night, it was my turn.'))]),

 ('The Serpent and the Board', 'הנחש והלוח', [
  P(('כל היום חשבתי.', 'All day I thought.'),
    ('הנחש בא בלילה, ובולע את מי שהוא מגיע אליו.', 'The snake comes at night, and swallows whoever it reaches.'),
    ('אני לא יכול לברוח ממנו, ואני לא יכול להילחם בו.', 'I cannot flee from it, and I cannot fight it.'),
    ('אבל אני יכול למנוע ממנו להגיע אליי.', 'But I can prevent it from reaching me.'),
    ('אספתי לוחות עץ מהרפסודה שהגלים זרקו על החוף, וחבלים מהעצים.', 'I gathered wooden boards from the raft the waves had thrown on the shore, and ropes from the trees.')),
  P(('ועשיתי לעצמי ארגז.', 'And I made myself a box.'),
    ('לוח מתחתיי, לוח מעליי, ולוח בכל צד, קשורים בחבלים, ואני באמצע.', 'A board beneath me, a board above me, and a board on every side, tied with ropes, and I in the middle.'),
    ('וקשרתי את הארגז לגזע העץ, כדי שהנחש לא יגלגל אותו.', 'And I tied the box to the trunk of the tree, so the snake would not roll it.'),
    ('ונכנסתי לתוכו לפני השקיעה, סגרתי את הלוח האחרון, וחיכיתי.', 'And I went inside before sunset, closed the last board, and waited.'),
    ('ובא הלילה, ובא הנחש.', 'And night came, and the snake came.')),
  P(('שמעתי אותו זוחל סביב הארגז.', 'I heard it crawling around the box.'),
    ('ואז הרגשתי אותו מסתובב סביבו, ולוחץ.', 'And then I felt it winding around it, and squeezing.'),
    ('העץ חרק, החבלים נמתחו, ואני בפנים, מכווץ כמו תינוק.', 'The wood creaked, the ropes stretched, and I inside, curled up like a baby.'),
    ('והוא ניסה להכניס את הראש מכל צד, ולא מצא מקום.', 'And it tried to push its head in from every side, and found no place.'),
    ('וכל הלילה הוא הסתובב ולחץ.', 'And all night it wound and squeezed.'),
    ('ואני אומר: אלוהים, העץ, תן לעץ להחזיק.', 'And I saying: God, the wood, let the wood hold.'),
    ('ועם האור הראשון, הוא הרפה, והלך.', 'And with the first light, it let go, and went.')),
  P(('יצאתי מהארגז, רועד, ורצתי לחוף.', 'I came out of the box, shaking, and ran to the shore.'),
    ('וראיתי ספינה רחוקה.', 'And I saw a far ship.'),
    ('צעקתי, והדלקתי אש, ונופפתי בענף.', 'I shouted, and lit a fire, and waved a branch.'),
    ('והם ראו אותי, ושלחו סירה, ולקחו אותי.', 'And they saw me, and sent a boat, and took me.'),
    ('וכשסיפרתי להם את הסיפור על הנחש, הם לא האמינו.', 'And when I told them the story about the snake, they did not believe.'),
    ('אבל המפקד אמר: תאמינו לו, אני ראיתי פלאים בים הזה.', 'But the captain said: believe him, I have seen wonders in this sea.'),
    ('והוא אמר לי: יש לי סחורה של סוחר שמת לפני שנים, תמכור אותה ואז תיקח את השכר שלך.', 'And he said to me: I have goods of a merchant who died years ago, sell them and take your wage.'),
    ('ושאלתי אותו: מה השם שלו?', 'And I asked him: what was his name?'),
    ('הוא אמר: סינדבאד, השארנו אותו על אי, בטעות, ישן.', 'He said: Sindbad, we left him on an island, by mistake, asleep.'),
    ('זאת הייתה הספינה שלי מהמסע השני.', 'It was my ship from the second voyage.'),
    ('והמפקד בכה כשהכיר אותי, וחזרתי לבגדאד עם הסחורה שלי והרווח שלי.', 'And the captain wept when he knew me, and I returned to Baghdad with my goods and my profit.'))]),

 ('The Storm', 'הסופה', [
  P(('סינדבאד אמר בלילה הרביעי: סבל, המסע הזה היה קשה מכל מה שלפניו.', 'Sindbad said on the fourth night: porter, this voyage was harder than all before it.'),
    ('כי בו לא ראיתי מפלצות, ראיתי בני אדם.', 'Because in it I saw no monsters, I saw human beings.'),
    ('יצאתי מהנמל בספינה חדשה, ועם חברים חדשים.', 'I left the port on a new ship, and with new companions.'),
    ('ואחרי שבועות באה עלינו סופה שלא ראיתי כמוה.', 'And after weeks a storm came upon us like none I had seen.'),
    ('גלים כמו הרים, הרוח צועקת, והשמיים שחורים ביום.', 'Waves like mountains, the wind screaming, and the sky black by day.')),
  P(('המפרש נקרע, והתורן נשבר.', 'The sail tore, and the mast broke.'),
    ('והספינה התהפכה, וכולנו נפלנו לים.', 'And the ship overturned, and we all fell into the sea.'),
    ('תפסתי לוח, ועוד חמישה תפסו את הלוח איתי.', 'I grabbed a board, and five more grabbed the board with me.'),
    ('והגלים נשאו אותנו יום ולילה, עד שזרקו אותנו על חוף.', 'And the waves carried us a day and a night, until they threw us on a shore.'),
    ('נפלנו על החול, חצי מתים, ולא יכולנו לזוז.', 'We fell on the sand, half dead, and could not move.')),
  P(('למחרת הלכנו פנימה, ומצאנו אנשים.', 'The next day we walked inland, and found people.'),
    ('אנשים ערומים, והעור שלהם שחור, והעיניים שלהם מבריקות בצורה מוזרה.', 'Naked people, and their skin black, and their eyes shining strangely.'),
    ('הם לא דיברו איתנו, הם לקחו אותנו למלך שלהם.', 'They did not speak with us, they took us to their king.'),
    ('והמלך לא דיבר גם, הוא סימן, והביאו לנו אוכל.', 'And the king did not speak either, he gestured, and they brought us food.'),
    ('אוכל מוזר, ירוק, והריח שלו חזק.', 'Strange food, green, and its smell strong.'),
    ('החברים שלי היו רעבים, אז הם אכלו הרבה.', 'My companions were hungry, so they ate a lot.'),
    ('ואני, אני לא יודע למה, לא אהבתי אותו, ואכלתי מעט מאוד.', 'And I, I do not know why, did not like it, and ate very little.')),
  P(('ואחרי ימים שמתי לב למשהו.', 'And after days I noticed something.'),
    ('החברים שלי אכלו ואכלו, ולא היו שבעים.', 'My companions ate and ate, and were never full.'),
    ('והעיניים שלהם נהיו כמו העיניים של אנשי המקום: מבריקות, וריקות.', 'And their eyes became like the eyes of the people of the place: shining, and empty.'),
    ('והם לא דיברו איתי יותר, ולא הכירו אותי.', 'And they did not speak with me any more, and did not know me.'),
    ('והם נהיו שמנים, יום אחרי יום.', 'And they became fat, day after day.'),
    ('והבנתי: האוכל היה סם, שהורג את השכל ומשמין את הגוף.', 'And I understood: the food was a drug, that kills the mind and fattens the body.'),
    ('והאנשים האלה אוכלים בני אדם.', 'And these people eat human beings.'),
    ('והם האכילו את החברים שלי הרבה, כמו שמאכילים כבשים.', 'And they were fattening my companions, as one fattens sheep.'))]),

 ('The King and the Saddle', 'המלך והאוכף', [
  P(('הייתי רזה, אז אף אחד לא שם לב אליי.', 'I was thin, so no one paid attention to me.'),
    ('ולילה אחד, כשהם ישנו, יצאתי מהכפר, והלכתי.', 'And one night, when they slept, I left the village, and walked.'),
    ('הלכתי שבעה ימים, אוכל עשב, ושותה מהגשם.', 'I walked seven days, eating grass, and drinking from the rain.'),
    ('וביום השמיני ראיתי אנשים אוספים פלפל בשדה.', 'And on the eighth day I saw people picking pepper in a field.'),
    ('אנשים רגילים, לבושים, והעיניים שלהם ערות.', 'Ordinary people, dressed, and their eyes awake.'),
    ('רצתי אליהם, סיפרתי להם את הסיפור שלי, והם האמינו לי, כי הם הכירו את אוכלי האדם.', 'I ran to them, told them my story, and they believed me, because they knew the man-eaters.')),
  P(('הם לקחו אותי לעיר שלהם, ואל המלך שלהם.', 'They took me to their city, and to their king.'),
    ('הוא היה מלך טוב, ושמע את הסיפור שלי, ונתן לי בית.', 'He was a good king, and heard my story, and gave me a house.'),
    ('והתחלתי ללכת בעיר, ולהסתכל, וללמוד.', 'And I began walking in the city, and looking, and learning.'),
    ('ויום אחד ראיתי את המלך רוכב על סוס, ויושב על הגב שלו בלי כלום.', 'And one day I saw the king riding a horse, and sitting on its back with nothing.'),
    ('לא אוכף, ולא כלום, כמו שילד רוכב.', 'No saddle, and nothing, as a child rides.'),
    ('ושאלתי: למה המלך רוכב ככה?', 'And I asked: why does the king ride like that?'),
    ('הם אמרו: ואיך אחרת?', 'They said: and how else?'),
    ('הם לא הכירו את האוכף.', 'They did not know the saddle.')),
  P(('הלכתי לנגר, וציירתי לו אוכף על האדמה.', 'I went to a carpenter, and drew him a saddle on the ground.'),
    ('ולנפח, וציירתי לו את הברזל לרגליים.', 'And to a blacksmith, and drew him the iron for the feet.'),
    ('ולחייט, ולימדתי אותו לכסות את העץ בעור ובצמר.', 'And to a tailor, and taught him to cover the wood with leather and wool.'),
    ('ואחרי שבוע, שמתי את האוכף על הסוס של המלך.', 'And after a week, I put the saddle on the king’s horse.'),
    ('והמלך רכב, ולא ירד עד הערב.', 'And the king rode, and did not get down until evening.'),
    ('הוא אמר: סינדבאד, זה הדבר הכי טוב שקרה בממלכה שלי.', 'He said: Sindbad, this is the best thing that has happened in my kingdom.')),
  P(('וכל שר ביקש אוכף, וכל סוחר, וכל קצין.', 'And every minister asked for a saddle, and every merchant, and every officer.'),
    ('ונהייתי עשיר, בלי ים ובלי סחורה, רק מאוכף.', 'And I became rich, without sea and without goods, only from a saddle.'),
    ('ויום אחד המלך אמר לי: סינדבאד, נהיית אחד מאיתנו.', 'And one day the king said to me: Sindbad, you have become one of us.'),
    ('אני רוצה לחתן אותך, כדי שלא תחשוב לחזור לארץ שלך.', 'I want to marry you off, so that you will not think of going back to your country.'),
    ('והוא חיתן אותי עם בת מאחד הבתים הטובים בעיר, יפה ועשירה וטובה.', 'And he married me to a daughter of one of the good houses of the city, beautiful and rich and good.'),
    ('וחייתי איתה, ואהבתי אותה.', 'And I lived with her, and loved her.'),
    ('ואמרתי: אולי אשכח את בגדאד.', 'And I said: maybe I will forget Baghdad.'),
    ('אבל היה חוק בעיר הזאת, שאף אחד לא סיפר לי עליו.', 'But there was a law in this city, that no one had told me about.'))]),

 ('The Law of the City', 'החוק של העיר', [
  P(('השכן שלי היה סוחר, וחבר שלי, ואשתו מתה.', 'My neighbour was a merchant, and my friend, and his wife died.'),
    ('הלכתי לנחם אותו, ומצאתי אותו בוכה כמו ילד.', 'I went to comfort him, and found him crying like a child.'),
    ('אמרתי: תהיה חזק, אתה צעיר, ואז תתחתן שוב.', 'I said: be strong, you are young, and you will marry again.'),
    ('הוא הסתכל עליי, ואמר: אתה לא יודע?', 'He looked at me, and said: you do not know?'),
    ('אמרתי: מה?', 'I said: what?'),
    ('הוא אמר: החוק, מי שאשתו מתה, קוברים אותו איתה, ומי שבעלה מת, קוברים אותה איתו.', 'He said: the law, a man whose wife dies is buried with her, and a woman whose husband dies is buried with him.'),
    ('בחיים.', 'Alive.')),
  P(('לא האמנתי, עד שראיתי בעיניים שלי.', 'I did not believe, until I saw with my own eyes.'),
    ('הם רחצו את אשתו, הלבישו אותה בבגדים הכי יפים שלה, ושמו אותה בארון.', 'They washed his wife, dressed her in her most beautiful clothes, and put her in a coffin.'),
    ('והלכו איתה להר מחוץ לעיר, ועליו אבן גדולה.', 'And went with her to a mountain outside the city, and on it a big stone.'),
    ('הם הרימו את האבן, ומתחתיה הייתה באר עמוקה, שחורה.', 'They lifted the stone, and beneath it was a deep well, black.'),
    ('הם הורידו את הארון לתוכה בחבלים.', 'They lowered the coffin into it with ropes.'),
    ('ואז הם קשרו את השכן שלי בחבלים, ונתנו לו שבעה לחמים וכד מים.', 'And then they tied my neighbour with ropes, and gave him seven loaves and a jug of water.'),
    ('והורידו אותו אחריה, והוא צועק.', 'And lowered him after her, and he screaming.'),
    ('והחזירו את האבן למקום.', 'And put the stone back in place.')),
  P(('חזרתי הביתה, והלכתי אל המלך.', 'I went home, and went to the king.'),
    ('אמרתי: המלך, אני זר, החוק הזה לא חל עליי.', 'I said: my king, I am a stranger, this law does not apply to me.'),
    ('המלך אמר: אתה אחד מאיתנו, אמרתי את זה בעצמי.', 'The king said: you are one of us, I said so myself.'),
    ('החוק על כולם, גם עליי.', 'The law is for everyone, also for me.'),
    ('וחזרתי הביתה, והסתכלתי על אשתי.', 'And I went home, and looked at my wife.'),
    ('והתחלתי להתפלל כל לילה: אלוהים, תן לי למות לפניה.', 'And I began to pray every night: God, let me die before her.'),
    ('וגם היא התפללה את אותה תפילה.', 'And she too prayed the same prayer.')),
  P(('ואחרי שנה אשתי חלתה.', 'And after a year my wife fell ill.'),
    ('והיא חלתה, וחלתה, ומתה.', 'And she grew sicker, and sicker, and died.'),
    ('והם באו, רחצו אותה, הלבישו אותה, ושמו אותה בארון.', 'And they came, washed her, dressed her, and put her in the coffin.'),
    ('וקשרו אותי, ונתנו לי שבעה לחמים וכד מים.', 'And tied me, and gave me seven loaves and a jug of water.'),
    ('וצעקתי, ואמרתי: אני זר! אני מבגדאד!', 'And I screamed, and said: I am a stranger! I am from Baghdad!'),
    ('ואף אחד לא שמע.', 'And no one listened.'),
    ('והורידו אותי לבאר, והאבן חזרה למקום, והעולם נהיה שחור.', 'And they lowered me into the well, and the stone went back in place, and the world went black.'))]),

 ('The Way Out', 'הדרך החוצה', [
  P(('התרתי את החבלים, ועמדתי, ולא ראיתי כלום.', 'I untied the ropes, and stood, and saw nothing.'),
    ('חושך מלא, וריח של מוות, וקול של מים שנופלים מרחוק.', 'Complete darkness, and a smell of death, and a sound of water dripping from afar.'),
    ('הלכתי עם הידיים לפניי, ודרכתי על עצמות.', 'I walked with my hands before me, and stepped on bones.'),
    ('המערה הייתה גדולה, ובה כל המתים של מאה שנה.', 'The cave was big, and in it all the dead of a hundred years.'),
    ('ישבתי בפינה, אכלתי לחם אחד, ושתיתי קצת.', 'I sat in a corner, ate one loaf, and drank a little.'),
    ('ואמרתי: שבעה לחמים, שבעה ימים, ואחר כך אני מת.', 'And I said: seven loaves, seven days, and then I die.')),
  P(('ואחרי ימים שמעתי את האבן זזה.', 'And after days I heard the stone moving.'),
    ('וירד אור, וארון, ואחריו מישהו שבוכה.', 'And light came down, and a coffin, and after it someone crying.'),
    ('איש שהורידו עם אשתו המתה, ואיתו הלחם והמים שלו.', 'A man they had lowered with his dead wife, and with him his bread and his water.'),
    ('והאבן חזרה, והחושך חזר.', 'And the stone went back, and the darkness came back.'),
    ('והלכתי אליו בחושך, ולקחתי את הלחם והמים שלו.', 'And I went to him in the dark, and took his bread and his water.'),
    ('אני לא רוצה לספר לך איך.', 'I do not want to tell you how.'),
    ('הסבל אמר: אני לא רוצה לדעת.', 'The porter said: I do not want to know.'),
    ('סינדבאד אמר: הרעב עושה מבן אדם משהו אחר, ואני חייתי, והוא לא.', 'Sindbad said: hunger makes something else out of a person, and I lived, and he did not.')),
  P(('ונשארתי ככה חודשים, כל פעם שהורידו מישהו, לקחתי את האוכל שלו.', 'And I stayed like that for months, every time they lowered someone, I took his food.'),
    ('ויום אחד שמעתי קול שלא מלמעלה.', 'And one day I heard a sound not from above.'),
    ('קול של נשימה, ורגליים קטנות, מתוך המערה.', 'A sound of breathing, and small feet, from inside the cave.'),
    ('חיה, היא באה לאכול מהמתים, ראתה אותי, וברחה.', 'An animal, it came to eat from the dead, saw me, and fled.'),
    ('וחשבתי: מאיפה היא נכנסה?', 'And I thought: where did it come in from?'),
    ('והלכתי אחריה בחושך, בין העצמות, שעות.', 'And I followed it in the dark, among the bones, for hours.'),
    ('עד שראיתי נקודה של אור.', 'Until I saw a point of light.')),
  P(('זה היה סדק בסלע, שיוצא אל הים.', 'It was a crack in the rock, that came out to the sea.'),
    ('זחלתי בו, ויצאתי, וראיתי את השמש, ובכיתי.', 'I crawled through it, and came out, and saw the sun, and wept.'),
    ('ואז חזרתי למערה.', 'And then I went back to the cave.'),
    ('הסבל אמר: חזרת?!', 'The porter said: you went back?!'),
    ('סינדבאד אמר: חזרתי, כי עם כל מת שהורידו, הורידו את הזהב ואת התכשיטים שלו.', 'Sindbad said: I went back, because with every dead person they lowered, they lowered his gold and his jewels.'),
    ('ואספתי מהמערה יותר ממה שאספתי בכל המסעות שלי.', 'And I gathered from the cave more than I had gathered in all my voyages.'),
    ('וישבתי על החוף, ליד הסדק, ימים, עד שעברה ספינה.', 'And I sat on the shore, by the crack, for days, until a ship passed.'),
    ('ואמרתי להם: אני סוחר שהספינה שלו טבעה, ולא סיפרתי על המערה.', 'And I told them: I am a merchant whose ship sank, and I said nothing about the cave.'),
    ('וחזרתי לבגדאד, ואיתי הזהב של המתים.', 'And I returned to Baghdad, and with me the gold of the dead.'),
    ('וסינדבאד נתן לסבל מאה מטבעות, ולא צחק באותו לילה.', 'And Sindbad gave the porter a hundred coins, and did not laugh that night.'))]),

 ('The Broken Egg', 'הביצה השבורה', [
  P(('בלילה החמישי סינדבאד אמר: הפעם קניתי ספינה משלי.', 'On the fifth night Sindbad said: this time I bought a ship of my own.'),
    ('אמרתי: המפקד בורח, והמפקד שוכח, אני אהיה המפקד.', 'I said: the captain runs, and the captain forgets, I will be the captain.'),
    ('ולקחתי איתי סוחרים, ונסענו.', 'And I took merchants with me, and we sailed.'),
    ('ויום אחד הגענו לאי, וראיתי עליו מרחוק כיפה לבנה.', 'And one day we reached an island, and I saw on it from afar a white dome.'),
    ('והלב שלי עצר.', 'And my heart stopped.'),
    ('אמרתי לסוחרים: אל תרדו, זאת ביצה של הציפור הענקית.', 'I said to the merchants: do not go down, this is an egg of the giant bird.')),
  P(('אבל הסוחרים לא שמעו.', 'But the merchants did not listen.'),
    ('הם ירדו, הקיפו את הביצה, והכו אותה באבנים, עד ששברו אותה.', 'They went down, surrounded the egg, and struck it with stones, until they broke it.'),
    ('והוא יצא ממנה, גוזל, גדול כמו בית, והם הרגו אותו, ולקחו את הבשר שלו.', 'And a chick came out of it, big as a house, and they killed it, and took its meat.'),
    ('וחזרו לספינה, צוחקים, ואיתם הבשר.', 'And they came back to the ship, laughing, and with them the meat.'),
    ('אמרתי: משוגעים! תרימו את המפרש! מהר!', 'I said: madmen! Raise the sail! Quickly!'),
    ('ולפני שהלכנו רחוק, העולם נהיה חשוך.', 'And before we got away, the world went dark.')),
  P(('הציפורים, האימא והאבא.', 'The birds, the mother and the father.'),
    ('שתיים, והכנפיים שלהן כיסו את השמיים.', 'Two, and their wings covered the sky.'),
    ('והן ראו את הביצה השבורה, וצעקו צעקה ששברה לנו את הלב.', 'And they saw the broken egg, and gave a scream that broke our hearts.'),
    ('והן עפו רחוק, וחשבנו שהן הלכו.', 'And they flew far, and we thought they had gone.'),
    ('אבל הן חזרו.', 'But they came back.'),
    ('ובציפורניים של כל אחת, סלע כמו הר.', 'And in the claws of each, a rock like a mountain.')),
  P(('הראשונה זרקה את הסלע שלה, והוא נפל ליד הספינה, והגל הרים אותנו לשמיים.', 'The first threw its rock, and it fell beside the ship, and the wave lifted us to the sky.'),
    ('והשנייה זרקה את הסלע שלה עלינו ישר.', 'And the second threw its rock straight onto us.'),
    ('הספינה נשברה לשניים, הלוחות עפו, וכולנו נפלנו לים.', 'The ship broke in two, the boards flew, and we all fell into the sea.'),
    ('ותפסתי לוח, שוב, כמו בכל פעם.', 'And I grabbed a board, again, as every time.'),
    ('והסבל אמר: כל פעם לוח?', 'And the porter said: every time a board?'),
    ('סינדבאד אמר: כל פעם, אלוהים שולח את הלוח, והשאר עליי.', 'Sindbad said: every time, God sends the board, and the rest is up to me.'))]),

 ('The Old Man of the Sea', 'הזקן על הגב', [
  P(('הגלים זרקו אותי על אי עם עצים ופירות ונהר.', 'The waves threw me onto an island with trees and fruit and a river.'),
    ('ואמרתי: תודה לאל, זה טוב מכל מה שלפניו.', 'And I said: thank God, this is better than all before it.'),
    ('ואחרי יום מצאתי ליד הנהר איש זקן, יושב.', 'And after a day I found by the river an old man, sitting.'),
    ('רזה, וחלש, ולבוש עלים.', 'Thin, and weak, and dressed in leaves.'),
    ('והוא סימן לי ביד לצד השני של הנהר, כאילו הוא רוצה לעבור.', 'And he gestured to me with his hand to the other side of the river, as if he wanted to cross.'),
    ('אמרתי: מסכן, אני אשא אותו.', 'I said: poor man, I will carry him.')),
  P(('שמתי אותו על הכתפיים שלי, ועברתי את הנהר.', 'I put him on my shoulders, and crossed the river.'),
    ('ובצד השני התכופפתי כדי שהוא יירד.', 'And on the other side I bent so that he would get down.'),
    ('הוא לא ירד.', 'He did not get down.'),
    ('הוא כרך את הרגליים שלו סביב הצוואר שלי, ולחץ.', 'He wound his legs around my neck, and squeezed.'),
    ('רגליים כמו עור שחור, קשות, וחזקות כמו ברזל.', 'Legs like black leather, hard, and strong as iron.'),
    ('לא יכולתי לנשום, ונפלתי על האדמה.', 'I could not breathe, and fell to the ground.'),
    ('והוא הכה על הראש שלי ביד, וסימן: קום, לך.', 'And he struck my head with his hand, and gestured: get up, walk.')),
  P(('והלכתי.', 'And I walked.'),
    ('מהבוקר עד הערב, והוא על הכתפיים שלי, והרגליים שלו סביב הצוואר.', 'From morning to evening, and he on my shoulders, and his legs around my neck.'),
    ('כל פעם שעצרתי, הוא לחץ, וכל פעם שהאטתי, הוא הכה.', 'Every time I stopped, he squeezed, and every time I slowed, he struck.'),
    ('והוא אכל מהעצים כשהוא עליי, וישן על הכתפיים שלי.', 'And he ate from the trees while on me, and slept on my shoulders.'),
    ('וגם בשינה, הרגליים שלו לא נפתחו.', 'And even in sleep, his legs did not open.'),
    ('ימים, ואז שבועות.', 'Days, and then weeks.'),
    ('ונהייתי כמו חמור, והוא בעל החמור.', 'And I became like a donkey, and he the owner of the donkey.'),
    ('וחשבתי: מכל המוות שראיתי, זה הכי גרוע.', 'And I thought: of all the death I have seen, this is the worst.')),
  P(('הסבל אמר: ולמה? הוא לא הרג אותך.', 'The porter said: and why? He was not killing you.'),
    ('סינדבאד אמר: כי הוא לא הרג אותי.', 'Sindbad said: because he was not killing me.'),
    ('הענק אוכל אותך וזה נגמר, והנחש בולע אותך וזה נגמר.', 'The giant eats you and it is over, and the snake swallows you and it is over.'),
    ('אבל זה רצה שאני אחיה, בשבילו.', 'But this one wanted me to live, for his sake.'),
    ('כל יום, עד שאמות מעייפות.', 'Every day, until I died of exhaustion.'),
    ('וראיתי מתחת לעצים עצמות של אנשים, והבנתי שהם היו לפניי.', 'And I saw under the trees bones of men, and understood that they had been before me.'),
    ('חמורים ישנים של הזקן.', 'Old donkeys of the old man.'))]),

 ('The Wine', 'היין', [
  P(('יום אחד, כשהלכתי, ראיתי דלעת גדולה זרוקה מתחת לעץ.', 'One day, as I walked, I saw a big gourd lying under a tree.'),
    ('יבשה, וריקה מבפנים.', 'Dry, and empty inside.'),
    ('וסביבה ענבים, הרבה, בשלים, שנפלו על האדמה.', 'And around it grapes, many, ripe, that had fallen on the ground.'),
    ('ובא לי רעיון, מהימים של בגדאד.', 'And an idea came to me, from the days of Baghdad.'),
    ('אספתי את הענבים, סחטתי אותם לתוך הדלעת, סגרתי אותה, ושמתי אותה בשמש.', 'I gathered the grapes, squeezed them into the gourd, closed it, and put it in the sun.'),
    ('והזקן עליי, מסתכל, ולא מבין.', 'And the old man on me, looking, and not understanding.')),
  P(('אחרי ימים חזרתי לדלעת.', 'After days I went back to the gourd.'),
    ('הענבים נהיו יין.', 'The grapes had become wine.'),
    ('שתיתי ממנו, והרגשתי חום, וכוח, ושכחתי קצת מהעייפות שלי.', 'I drank from it, and felt warmth, and strength, and forgot a little of my tiredness.'),
    ('והתחלתי לשיר, ולרקוד, והזקן על הכתפיים שלי.', 'And I began to sing, and to dance, and the old man on my shoulders.'),
    ('והזקן ראה, והכה על הראש שלי, וסימן: תן לי.', 'And the old man saw, and struck my head, and gestured: give me.'),
    ('נתתי לו את הדלעת.', 'I gave him the gourd.')),
  P(('הוא שתה, ושתה, ושתה עד שהדלעת התרוקנה.', 'He drank, and drank, and drank until the gourd was empty.'),
    ('והתחיל לצחוק, ולנענע את הראש, ולשיר בקול שהוא לא קול.', 'And began to laugh, and shake his head, and sing in a voice that was no voice.'),
    ('ולאט לאט הרגשתי שהרגליים שלו נפתחות.', 'And little by little I felt his legs opening.'),
    ('יכולתי לנשום, יכולתי להזיז את הראש.', 'I could breathe, I could move my head.'),
    ('ועמדתי בשקט, לא זז, עד שהוא נרדם.', 'And I stood still, not moving, until he fell asleep.'),
    ('הוא נרדם, והרגליים שלו פתוחות, והראש שלו על הכתף שלי.', 'He fell asleep, and his legs loose, and his head on my shoulder.')),
  P(('תפסתי את הרגליים שלו, הרמתי אותן מהצוואר שלי, וזרקתי אותו על האדמה.', 'I grabbed his legs, lifted them from my neck, and threw him on the ground.'),
    ('ועמדתי מעליו, והוא ישן.', 'And I stood over him, and he asleep.'),
    ('והרמתי אבן.', 'And I lifted a stone.'),
    ('הסבל אמר: והרגת אותו?', 'The porter said: and you killed him?'),
    ('סינדבאד אמר: הרגתי אותו.', 'Sindbad said: I killed him.'),
    ('ואני לא מתחרט, אף יום, כי אם הוא היה מתעורר, הוא היה חוזר על הכתפיים שלי.', 'And I do not regret, not one day, because if he had woken, he would have gone back on my shoulders.'),
    ('ורצתי לחוף, ואחרי יומיים עברה ספינה, ולקחו אותי.', 'And I ran to the shore, and after two days a ship passed, and they took me.'),
    ('וכשסיפרתי להם, המפקד אמר: זה הזקן של הים, אף אחד לא ניצל ממנו לפניך.', 'And when I told them, the captain said: that is the old man of the sea, no one escaped him before you.'))]),

 ('The City of Apes', 'עיר הקופים', [
  P(('הספינה הביאה אותנו לעיר גדולה, על הים, והבתים שלה גבוהים.', 'The ship brought us to a big city, on the sea, and its houses tall.'),
    ('וראיתי דבר מוזר: עם השקיעה, כל האנשים יוצאים מהעיר.', 'And I saw a strange thing: at sunset, all the people leave the city.'),
    ('הם עולים על סירות, וישנים על הים, וחוזרים בבוקר.', 'They get into boats, and sleep on the sea, and come back in the morning.'),
    ('ושאלתי: למה?', 'And I asked: why?'),
    ('הם אמרו: הקופים.', 'They said: the apes.'),
    ('כל לילה יורדים מההר אלפי קופים, ונכנסים לעיר, והורגים את מי שהם מוצאים.', 'Every night thousands of apes come down from the mountain, and enter the city, and kill whoever they find.')),
  P(('ולי לא היה כסף, ואף אחד לא לקח אותי בסירה שלו.', 'And I had no money, and no one took me in his boat.'),
    ('ובא הלילה, ואני בעיר לבד.', 'And night came, and I in the city alone.'),
    ('ושמעתי אותם יורדים מההר, כמו גשם.', 'And I heard them coming down from the mountain, like rain.'),
    ('רצתי והתחבאתי בבית, סגרתי את הדלת, ועליתי לגג.', 'I ran and hid in a house, closed the door, and went up to the roof.'),
    ('וכל הלילה שמעתי אותם שוברים דלתות מתחתיי, וצועקים.', 'And all night I heard them breaking doors beneath me, and screaming.'),
    ('ובבוקר הם עלו להר, והאנשים חזרו.', 'And in the morning they went up to the mountain, and the people came back.')),
  P(('ואחד מהאנשים ראה אותי יורד מהגג, והתפלא שאני חי.', 'And one of the people saw me coming down from the roof, and was amazed that I was alive.'),
    ('הוא אמר: בוא איתי מחר, אני אלמד אותך איך אנחנו חיים כאן.', 'He said: come with me tomorrow, I will teach you how we live here.'),
    ('ובבוקר הוא נתן לי שק, ואבנים, והלכנו להר.', 'And in the morning he gave me a sack, and stones, and we went to the mountain.'),
    ('ההר היה מלא עצים של אגוזי קוקוס, גבוהים מאוד, שאף אחד לא יכול לטפס עליהם.', 'The mountain was full of coconut trees, very tall, that no one could climb.'),
    ('והקופים על העצים, ישנים, אחרי הלילה שלהם בעיר.', 'And the apes in the trees, asleep, after their night in the city.')),
  P(('הוא אמר: תזרוק עליהם אבנים.', 'He said: throw stones at them.'),
    ('זרקתי, והקופים התעוררו, וכעסו.', 'I threw, and the apes woke, and were angry.'),
    ('והם ענו לנו, אבל לא היו להם אבנים.', 'And they answered us, but they had no stones.'),
    ('היו להם אגוזי קוקוס.', 'They had coconuts.'),
    ('והם התחילו לקטוף אגוזים ולזרוק אותם עלינו, בכעס, מאות.', 'And they began to pick coconuts and throw them at us, in anger, hundreds.'),
    ('ואנחנו אוספים אותם לשקים, וצוחקים.', 'And we gathering them into the sacks, and laughing.'),
    ('הוא אמר: ככה אנחנו חיים, הם קוטפים, ואנחנו מוכרים.', 'He said: this is how we live, they pick, and we sell.'),
    ('ועבדתי ככה חודשים, ואספתי כסף, וחזרתי לבגדאד.', 'And I worked like that for months, and gathered money, and returned to Baghdad.'),
    ('והסבל צחק, ואמר: זה המסע הכי טוב.', 'And the porter laughed, and said: this is the best voyage.'),
    ('סינדבאד אמר: כי בו אף אחד לא מת, חוץ מהזקן.', 'Sindbad said: because in it no one died, except the old man.'))]),

 ('The Mountain of Wrecks', 'הר הספינות השבורות', [
  P(('בלילה השישי סינדבאד אמר: במסע הזה לא היה ענק, ולא נחש, ולא זקן.', 'On the sixth night Sindbad said: in this voyage there was no giant, and no snake, and no old man.'),
    ('היה בו הר.', 'There was a mountain in it.'),
    ('נסענו בספינה גדולה, והמפקד היה הכי טוב בנמל.', 'We sailed on a big ship, and the captain was the best in the port.'),
    ('ויום אחד המפקד עלה על הסיפון, והתחיל לבכות, ולמשוך בזקן שלו.', 'And one day the captain came up on deck, and began to cry, and pull his beard.'),
    ('אמרנו: מה קרה?', 'We said: what happened?'),
    ('הוא אמר: אבדנו, הזרם לקח אותנו למקום שאף אחד לא חוזר ממנו.', 'He said: we are lost, the current has taken us to a place no one comes back from.')),
  P(('וראינו את ההר לפנינו.', 'And we saw the mountain before us.'),
    ('הר גבוה, שחור, שיוצא מהים ישר.', 'A high mountain, black, coming straight out of the sea.'),
    ('ולמרגלותיו, ספינות, מאות ספינות.', 'And at its foot, ships, hundreds of ships.'),
    ('שבורות, וישנות, ונמצאות על הסלעים, אחת על השנייה.', 'Broken, and old, and thrown on the rocks, one on top of the other.'),
    ('המפקד אמר: כל ספינה שהגיעה לכאן, נשברה כאן.', 'The captain said: every ship that reached here broke here.'),
    ('הזרם מביא אותה, וההר שובר אותה, ואין דרך חזרה.', 'The current brings it, and the mountain breaks it, and there is no way back.'),
    ('והגלים נשאו אותנו על הסלעים, והספינה שלנו נשברה כמו כל השאר.', 'And the waves carried us onto the rocks, and our ship broke like all the rest.')),
  P(('כולנו ניצלנו, ועלינו על חוף צר מתחת להר.', 'We all survived, and came up onto a narrow shore beneath the mountain.'),
    ('וראינו סביבנו, בין הספינות השבורות, את האוצרות.', 'And we saw around us, among the broken ships, the treasures.'),
    ('זהב, וכסף, ומשי, ופנינים, וכל סחורה של כל ספינה שנשברה.', 'Gold, and silver, and silk, and pearls, and every cargo of every ship that had broken.'),
    ('וביניהם העצמות של אלה שמתו.', 'And among them the bones of those who had died.'),
    ('היינו האנשים הכי עשירים בעולם, ולא יכולנו לצאת.', 'We were the richest people in the world, and could not get out.'),
    ('כי על ההר אי אפשר לעלות, ואת הים אי אפשר לעבור.', 'Because the mountain cannot be climbed, and the sea cannot be crossed.')),
  P(('והאוכל התחיל להיגמר.', 'And the food began to run out.'),
    ('והאנשים התחילו למות, אחד אחרי השני.', 'And the people began to die, one after another.'),
    ('וקברנו כל אחד במקום שלו, עד שלא נשאר מי שיקבור.', 'And we buried each one in his place, until no one was left to bury.'),
    ('ונשארתי אני, האחרון, כמו בכל פעם.', 'And I remained, the last, as every time.'),
    ('וחפרתי לעצמי קבר, ליד האחרים.', 'And I dug myself a grave, beside the others.'),
    ('ואמרתי: כשאני ארגיש שאני הולך למות, אני אשכב בו.', 'And I said: when I feel that I am about to die, I will lie in it.'),
    ('כדי שהרוח תכסה אותי בחול.', 'So that the wind covers me with sand.'))]),

 ('The River Under the Mountain', 'הנהר מתחת להר', [
  P(('וכשישבתי ליד הקבר שלי, שמתי לב למשהו שלא ראיתי קודם.', 'And as I sat by my grave, I noticed something I had not seen before.'),
    ('נהר קטן, מתוק, שיורד מההר, והוא נכנס למערה מתחתיו.', 'A small river, sweet, coming down from the mountain, and going into a cave beneath it.'),
    ('הוא נכנס פנימה, ולא יוצא.', 'It goes in, and does not come out.'),
    ('ואמרתי: הנהר הולך למקום, והמקום הוא לא כאן.', 'And I said: the river is going somewhere, and somewhere is not here.'),
    ('אולי הוא יוצא בצד השני של ההר.', 'Maybe it comes out on the other side of the mountain.'),
    ('אולי הוא מגיע לארץ שיש בה אנשים.', 'Maybe it reaches a land where there are people.'),
    ('ואולי הוא מגיע רק לחושך, ואני אמות בתוכו.', 'And maybe it reaches only darkness, and I die inside it.'),
    ('אבל כאן, אני מת בטוח.', 'But here, I am surely dead.')),
  P(('עשיתי רפסודה קטנה מהעץ של הספינות.', 'I made a small raft from the wood of the ships.'),
    ('צרה, ברוחב הנהר, וארוכה כמוני.', 'Narrow, the width of the river, and as long as myself.'),
    ('והעמסתי עליה מה שנשאר מהאוכל, והכי טוב ממה שמצאתי: פנינים, ואבנים.', 'And I loaded on it what remained of the food, and the best of what I had found: pearls, and stones.'),
    ('וקשרתי את עצמי אליה, ודחפתי אותה לנהר.', 'And I tied myself to it, and pushed it into the river.'),
    ('והמערה בלעה אותי.', 'And I entered the cave.')),
  P(('חושך.', 'Darkness.'),
    ('הסלע מעליי, קרוב כל כך שהוא מגרד את הראש שלי.', 'The rock above me, so close that it scraped my head.'),
    ('ורק הקול של המים.', 'And only the sound of the water.'),
    ('שכבתי על הגב, והרפסודה הולכת עם הזרם, שעות, וימים, אני לא יודע.', 'I lay on my back, and the raft going with the current, hours, and days, I do not know.'),
    ('ואכלתי את הלחם האחרון, ושתיתי מהנהר.', 'And I ate the last bread, and drank from the river.'),
    ('ונרדמתי.', 'And I fell asleep.'),
    ('שינה עמוקה, כמו מוות, אבל לא מוות.', 'A deep sleep, like death, but not death.')),
  P(('והתעוררתי לאור, ולקולות.', 'And I woke to light, and to voices.'),
    ('הייתי על חוף של נהר, מתחת לשמש, וסביבי אנשים, מדברים שפה שאני לא מכיר.', 'I was on the bank of a river, under the sun, and around me people, speaking a language I did not know.'),
    ('אחד מהם דיבר ערבית, הוא אמר: מי אתה? ומאיפה באת?', 'One of them spoke Arabic, he said: who are you? And where did you come from?'),
    ('אמרתי: מתחת להר.', 'I said: from under the mountain.'),
    ('הם הסתכלו אחד על השני, ולא האמינו.', 'They looked at each other, and did not believe.'),
    ('וסיפרתי להם את הסיפור, מהספינה עד הרפסודה.', 'And I told them the story, from the ship to the raft.'),
    ('והם אמרו: זה פלא, המלך חייב לשמוע אותו.', 'And they said: this is a wonder, the king must hear it.'),
    ('ושאלתי: איזה מלך? ואיזו ארץ?', 'And I asked: which king? And which land?'),
    ('הם אמרו: סרנדיב.', 'They said: Serendib.'))]),

 ('Serendib', 'סרנדיב', [
  P(('סרנדיב הוא אי גדול, ירוק, ובו הר גבוה באמצע השמיים.', 'Serendib is a big island, green, and in it a high mountain in the middle of the sky.'),
    ('אומרים שאדם ירד עליו כשיצא מגן העדן.', 'They say Adam came down on it when he left the Garden of Eden.'),
    ('ויש בו הכול: אבנים אדומות, ופנינים, ופילים, ובשמים.', 'And it has everything: red stones, and pearls, and elephants, and spices.'),
    ('והמלך שלו היה המלך הכי גדול שראיתי.', 'And its king was the greatest king I had seen.'),
    ('הוא רוכב על פיל, וסביבו אלף איש, ולפניו אחד קורא: זה המלך!', 'He rides an elephant, and around him a thousand men, and before him one calling: this is the king!'),
    ('ומאחורי המלך, אחר קורא: והוא מת כמו כל אחד.', 'And behind the king, another calling: and he dies like anyone.'),
    ('כדי שהמלך לא ישכח.', 'So that the king does not forget.')),
  P(('הם לקחו אותי אל המלך, וסיפרתי לו את הסיפור שלי, ואת הסיפור על ההר והנהר.', 'They took me to the king, and I told him my story, and the story about the mountain and the river.'),
    ('והראיתי לו מה שהבאתי על הרפסודה.', 'And I showed him what I had brought on the raft.'),
    ('ונתתי לו את הפנינים הכי טובות, מתנה.', 'And I gave him the best pearls, as a gift.'),
    ('הוא אמר: מאיפה אתה?', 'He said: where are you from?'),
    ('אמרתי: מבגדאד, מהארץ של המלך הגדול.', 'I said: from Baghdad, from the land of the great king.'),
    ('הוא אמר: שמעתי עליו, אומרים שהוא מלך צודק.', 'He said: I have heard of him, they say he is a just king.'),
    ('אמרתי: הוא המלך הכי צודק בעולם.', 'I said: he is the most just king in the world.'),
    ('והמלך צחק, ואמר: כל אחד אומר ככה על המלך שלו.', 'And the king laughed, and said: everyone says that about his king.')),
  P(('חייתי בסרנדיב חודשים, האורח של המלך.', 'I lived in Serendib for months, the king’s guest.'),
    ('והלכתי לראות את ההר שאדם ירד עליו.', 'And I went to see the mountain Adam came down on.'),
    ('וראיתי בשוק אבנים אדומות כמו ביצים, ופילים שעובדים כמו משרתים.', 'And I saw in the market red stones like eggs, and elephants that work like servants.'),
    ('וכל יום למדתי משהו חדש.', 'And every day I learned something new.'),
    ('אבל כל לילה חלמתי על בגדאד.', 'But every night I dreamed about Baghdad.'),
    ('על הנהר, ועל המסגדים, ועל הריח של הלחם בבוקר.', 'About the river, and the mosques, and the smell of bread in the morning.'),
    ('והבנתי משהו: הזר אוהב את הארץ שהוא רואה, ומתגעגע לארץ שהוא עזב.', 'And I understood something: the stranger loves the land he sees, and longs for the land he left.')),
  P(('והלכתי אל המלך, ואמרתי: המלך, אני רוצה לחזור.', 'And I went to the king, and said: my king, I want to go back.'),
    ('הוא אמר: למה? יש לך כאן הכול.', 'He said: why? You have everything here.'),
    ('אמרתי: אין לי בגדאד.', 'I said: I do not have Baghdad.'),
    ('והמלך שתק, ואז אמר: טוב, אבל אני רוצה שתעשה בשבילי משהו.', 'And the king was silent, and then said: fine, but I want a service from you.'),
    ('ואני אמרתי: כרצונך.', 'And I said: as you wish.'),
    ('ולא ידעתי שהשירות הזה יחזיר אותי לים עוד פעם.', 'And I did not know that this service would return me to the sea once more.'))]),

 ('The King’s Letter', 'המכתב של המלך', [
  P(('המלך אמר: אני רוצה לשלוח מכתב למלך של בגדאד, ואתה תיקח אותו.', 'The king said: I want to send a letter to the king of Baghdad, and you will take it.'),
    ('והוא כתב את המכתב על עור של צבי, בדיו של זהב.', 'And he wrote the letter on gazelle skin, in gold ink.'),
    ('והוא כתב בו: מהמלך של סרנדיב, למלך של הערבים.', 'And he wrote in it: from the king of Serendib, to the king of the Arabs.'),
    ('שלום לך, אנחנו שולחים לך מתנה, ומבקשים את הידידות שלך.', 'Peace to you, we send you a gift, and ask for your friendship.'),
    ('ומבקשים שתכבד את מי שנשא את המכתב.', 'And ask you to honour the one who carried the letter.')),
  P(('והמתנה הייתה: כוס מאבן אדומה אחת, מלאה פנינים.', 'And the gift was: a cup from one red stone, full of pearls.'),
    ('ועור של נחש, שמי שישן עליו לא חולה.', 'And a snake skin, that whoever sleeps on it does not fall ill.'),
    ('ונערה יפה, ופיל לבן.', 'And a beautiful girl, and a white elephant.'),
    ('ושמו את כל זה בספינה, והמלך נפרד ממני בעצמו בנמל.', 'And they put all this on a ship, and the king said goodbye to me himself at the port.'),
    ('והוא אמר: סינדבאד, אם תחזור, הדלת שלי פתוחה.', 'And he said: Sindbad, if you come back, my door is open.'),
    ('והפלגנו, והים היה שקט, והגענו לנמל, ואחר כך לבגדאד.', 'And we sailed, and the sea was calm, and we reached the port, and then Baghdad.')),
  P(('ונכנסתי אל המלך, השתחוויתי, ונתתי לו את המכתב ואת המתנה.', 'And I went in to the king, bowed, and gave him the letter and the gift.'),
    ('הוא קרא את המכתב, ראה את הכוס, ואמר: המלך הזה עשיר או עני?', 'He read the letter, saw the cup, and said: is this king rich or poor?'),
    ('אמרתי: עשיר מכל המלכים בעולם, חוץ מהמלך שלנו.', 'I said: richer than all the kings in the world, except you.'),
    ('וסיפרתי לו על סרנדיב, והפיל, וההר, והקורא שאומר: והוא מת כמו כל אחד.', 'And I told him about Serendib, and the elephant, and the mountain, and the crier who says: and he dies like anyone.'),
    ('והמלך צחק הרבה, והקורא מצא חן בעיניו.', 'And the king laughed a lot, and the crier pleased him.'),
    ('והוא אמר: סינדבאד, עזרת לי, אני רוצה לגמול לך.', 'And he said: Sindbad, you have served me, I want to reward you.')),
  P(('והוא נתן לי בגד של כבוד, וזהב, ואמר: הפעם, די, תישאר בבגדאד.', 'And he gave me a robe of honour, and gold, and said: this time, enough, stay in Baghdad.'),
    ('ואמרתי: המלך, זה מה שאני רוצה.', 'And I said: my king, that is what I want.'),
    ('וחזרתי לבית שלי, וישבתי, ונשבעתי.', 'And I went back to my house, and sat, and swore.'),
    ('נשבעתי שאני לא חוזר לים אף פעם.', 'I swore that I never go back to the sea.'),
    ('הסבל אמר: אבל יש מסע שביעי.', 'The porter said: but there is a seventh voyage.'),
    ('סינדבאד אמר: יש, כי המלך הוא זה ששלח אותי.', 'Sindbad said: there is, because the king is the one who sent me.'))]),

 ('One Last Time', 'עוד פעם אחרונה', [
  P(('בלילה השביעי סינדבאד אמר: אחרי שנה, המלך קרא לי.', 'On the seventh night Sindbad said: after a year, the king called me.'),
    ('הוא אמר: סינדבאד, אני רוצה לענות למלך של סרנדיב, ואתה היחיד שמכיר את הדרך.', 'He said: Sindbad, I want to answer the king of Serendib, and you are the only one who knows the way.'),
    ('אמרתי: המלך, נשבעתי.', 'I said: my king, I swore.'),
    ('הוא אמר: ואני מבקש.', 'He said: and I am asking.'),
    ('ואף אחד לא מסרב למלך.', 'And no one refuses the king.'),
    ('אז לקחתי את המכתב שלו ואת המתנה שלו, ירדתי לנמל, ויצאתי לים, בפעם השביעית.', 'So I took his letter and his gift, went down to the port, and went out to sea, for the seventh time.')),
  P(('הגענו לסרנדיב בשלום, מסרתי את המכתב, והמלך שמח.', 'We reached Serendib in peace, I delivered the letter, and the king was glad.'),
    ('וישבתי אצלו חודש, נפרדתי ממנו, ועליתי על הספינה חזרה.', 'And I stayed with him a month, said goodbye to him, and boarded the ship back.'),
    ('ואמרתי: זהו, הפעם האחרונה, הדרך ידועה, והים שקט.', 'And I said: that is it, the last time, the way is known, and the sea is calm.'),
    ('ואחרי שבוע באו עלינו שודדי ים.', 'And after a week pirates came upon us.'),
    ('שלוש ספינות, ואנשים עם חרבות, ולא יכולנו לעשות כלום.', 'Three ships, and men with swords, and we could do nothing.'),
    ('הם לקחו את הספינה, ולקחו את כולנו לעבדים.', 'They took the ship, and took us all as slaves.')),
  P(('הם מכרו אותי בשוק בעיר שאני לא יודע את השם שלה.', 'They sold me in a market in a city whose name I do not know.'),
    ('וסוחר עשיר קנה אותי, לקח אותי לבית שלו, ושאל: מה אתה יודע לעשות?', 'And a rich merchant bought me, took me to his house, and asked: what do you know how to do?'),
    ('אמרתי: אני סוחר, אני יודע למכור ולקנות.', 'I said: I am a merchant, I know how to sell and buy.'),
    ('הוא אמר: ואתה יודע לירות בקשת?', 'He said: and do you know how to shoot a bow?'),
    ('אמרתי: כשהייתי צעיר.', 'I said: when I was young.'),
    ('הוא אמר: טוב, מחר אתה יוצא איתי.', 'He said: good, tomorrow you come out with me.')),
  P(('והוא לקח אותי בבוקר ליער, על הגב של פיל.', 'And he took me in the morning to a forest, on the back of an elephant.'),
    ('והעמיד אותי על עץ גבוה, ונתן לי קשת וחיצים, ואוכל לימים.', 'And stood me on a tall tree, and gave me a bow and arrows, and food for days.'),
    ('ואמר: הפילים עוברים כאן, כשאתה רואה אחד, תירה בו.', 'And said: the elephants pass here, when you see one, shoot it.'),
    ('וכשהוא מת, בוא תגיד לי, ואני בא ולוקח את השן שלו.', 'And when it dies, come and tell me, and I come and take its tusk.'),
    ('והוא הלך, והשאיר אותי על העץ.', 'And he went, and left me on the tree.'),
    ('ואמרתי: ממפקד לעבד, ומעבד לצייד פילים.', 'And I said: from captain to slave, and from slave to elephant hunter.'),
    ('ככה העולם.', 'Such is the world.'))]),

 ('The Elephants', 'הפילים', [
  P(('כל יום הפילים עברו מתחת לעץ.', 'Every day the elephants passed beneath the tree.'),
    ('קבוצות גדולות, איטיות, והם לא ראו אותי.', 'Big herds, slow, and they did not see me.'),
    ('ויריתי, ופגעתי באחד, וירדתי, והלכתי לאדון שלי.', 'And I shot, and hit one, and came down, and went to my master.'),
    ('והוא בא ולקח את השן, וקבר את הפיל.', 'And he came and took the tusk, and buried the elephant.'),
    ('חודשיים ככה.', 'Two months like that.'),
    ('והרגשתי שאני עושה משהו רע, אבל לא הייתה לי ברירה.', 'And I felt that I was doing something bad, but I had no choice.')),
  P(('ויום אחד הפילים לא עברו.', 'And one day the elephants did not pass.'),
    ('וגם לא למחרת.', 'And not the next day either.'),
    ('וביום השלישי שמעתי את האדמה רועדת.', 'And on the third day I heard the ground shaking.'),
    ('וראיתי אותם באים, לא כמו בכל פעם.', 'And I saw them coming, not as every time.'),
    ('באים אל העץ ישר, כולם, ולפניהם פיל גדול, גדול מכולם.', 'Coming straight to the tree, all of them, and before them a big elephant, bigger than all.'),
    ('הם עמדו סביב העץ, הרימו את האפים הארוכים, והסתכלו עליי.', 'They stood around the tree, raised their trunks, and looked at me.'),
    ('והבנתי: הם ידעו מי הורג אותם.', 'And I understood: they knew who was killing them.')),
  P(('הפיל הגדול כרך את האף הארוך שלו סביב העץ.', 'The big elephant wound its trunk around the tree.'),
    ('ומשך.', 'And pulled.'),
    ('העץ חרק, התכופף, והוא יצא מהאדמה עם השורשים.', 'The tree creaked, bent, and came out of the ground with its roots.'),
    ('ונפלתי איתו, על הגב, והפילים סביבי.', 'And I fell with it, on my back, and the elephants around me.'),
    ('ואמרתי: זהו, מסע שביעי, ומוות שביעי, והפעם אמיתי.', 'And I said: that is it, a seventh voyage, and a seventh death, and this time real.'),
    ('ועצמתי את העיניים.', 'And I closed my eyes.')),
  P(('והוא לא דרך עליי.', 'And it did not tread on me.'),
    ('הרגשתי את האף הארוך מסתובב סביבי, לאט, ומרים אותי.', 'I felt the trunk winding around me, slowly, and lifting me.'),
    ('והוא שם אותי על הגב שלו.', 'And it put me on its back.'),
    ('והלך.', 'And walked.'),
    ('וכל הפילים אחריו, בשקט, ביער.', 'And all the elephants after it, quietly, through the forest.'),
    ('ואני על הגב שלו, לא יודע לאן, ולא יודע למה.', 'And I on its back, not knowing where, and not knowing why.'),
    ('והסבל אמר: לאן הוא לקח אותך?', 'And the porter said: where did it take you?'),
    ('סינדבאד אמר: זה מחר, הלילה נגמר.', 'Sindbad said: that is tomorrow, tonight is over.'))]),

 ('The Elephant Who Carried Me', 'הפיל שנשא אותי', [
  P(('הפיל הלך חצי יום, ואני על הגב שלו.', 'The elephant walked half a day, and I on its back.'),
    ('עד שהגענו לגבעה, והוא עצר, והוריד אותי באף הארוך שלו לאט.', 'Until we reached a hill, and it stopped, and set me down with its trunk slowly.'),
    ('והלך, הוא וכל הפילים, והשאירו אותי.', 'And went, it and all the elephants, and left me.'),
    ('עמדתי, הסתכלתי סביבי, ולא הבנתי.', 'I stood, looked around me, and did not understand.'),
    ('ואז הבנתי.', 'And then I understood.')),
  P(('כל הגבעה שנהב.', 'The whole hill was ivory.'),
    ('שיניים של פילים, מאות, אלפים, לבנות וצהובות, ישנות וחדשות.', 'Tusks of elephants, hundreds, thousands, white and yellow, old and new.'),
    ('זה היה בית הקברות של הפילים.', 'It was the cemetery of the elephants.'),
    ('המקום שהם באים למות בו כבר אלף שנה.', 'The place they have come to die in for a thousand years.'),
    ('והבנתי מה הפיל אמר לי, בלי מילים.', 'And I understood what the elephant had told me, without words.'),
    ('הוא אמר: אתה רוצה שנהב? זה שנהב, קח, ותן לנו לחיות.', 'It said: you want ivory? Here is ivory, take, and let us live.'),
    ('וישבתי על הגבעה, ובכיתי.', 'And I sat on the hill, and wept.')),
  P(('חזרתי לאדון שלי ברגל, יומיים.', 'I went back to my master on foot, two days.'),
    ('וכשראה אותי, אמר: חשבתי שמת! הפילים עקרו את העץ!', 'And when he saw me, he said: I thought you were dead! The elephants pulled out the tree!'),
    ('אמרתי: בוא איתי.', 'I said: come with me.'),
    ('ולקחתי אותו לגבעה.', 'And I took him to the hill.'),
    ('והוא עמד מול השנהב, ולא דיבר חצי שעה.', 'And he stood before the ivory, and did not speak for half an hour.'),
    ('ואז אמר: סינדבאד, זה יותר ממה שהארץ שלנו אוספת במאה שנה.', 'And then he said: Sindbad, this is more than our land gathers in a hundred years.'),
    ('ואתה לא עבד יותר, אתה חופשי, ואתה השותף שלי.', 'And you are a slave no more, you are free, and you are my partner.'),
    ('ואף אחד לא הורג פיל מהיום.', 'And no one kills an elephant from this day.')),
  P(('ונשאנו את השנהב על פילים, לא כמו קודם, רק מה שהשיירה צריכה.', 'And we carried the ivory on elephants, not as before, only what the caravan needed.'),
    ('והוא מכר אותו, ונתן לי חצי, וספינה, ונפרד ממני.', 'And he sold it, and gave me half, and a ship, and said goodbye to me.'),
    ('והפלגתי, ולא קרה כלום.', 'And I sailed, and nothing happened.'),
    ('לא סופה, ולא שודדים, ולא אי.', 'No storm, and no pirates, and no island.'),
    ('בפעם הראשונה בחיים שלי, הים החזיר אותי הביתה בשלום.', 'For the first time in my life, the sea brought me home in peace.'),
    ('והסבל אמר: למה?', 'And the porter said: why?'),
    ('סינדבאד אמר: אולי כי לקחתי רק מה שאני צריך.', 'Sindbad said: maybe because I took only what I needed.'))]),

 ('The Last Return', 'החזרה האחרונה', [
  P(('הגעתי לבגדאד עשרים ושבע שנים אחרי המסע הראשון.', 'I reached Baghdad twenty-seven years after the first voyage.'),
    ('ונכנסתי אל המלך, וסיפרתי לו על הפילים.', 'And I went in to the king, and told him about the elephants.'),
    ('והוא אמר: סינדבאד, די, אני לא שולח אותך לשום מקום מהיום.', 'And he said: Sindbad, enough, I do not send you anywhere from this day.'),
    ('והוא ציווה לכתוב את שבעת המסעות שלי בדיו של זהב, ולשמור אותם באוצר שלו.', 'And he ordered my seven voyages written in gold ink, and kept in his treasury.'),
    ('כדי שמי שאחרינו ידע מה יש בים.', 'So that those after us know what there is in the sea.')),
  P(('וחזרתי לבית שלי, הבית הזה.', 'And I came back to my house, this house.'),
    ('וקניתי את הגן, ואת המשרתים, ואת הזמרים.', 'And I bought the garden, and the servants, and the singers.'),
    ('וכל יום אני יושב כאן, ושומע מוזיקה, ואוכל.', 'And every day I sit here, and listen to music, and eat.'),
    ('וכל לילה אני חולם על הים.', 'And every night I dream about the sea.'),
    ('אבל אני לא חוזר אליו.', 'But I do not go back to it.'),
    ('כי הזדקנתי, וכי למדתי.', 'Because I have grown old, and because I have learned.'),
    ('והסבל שאל: מה למדת?', 'And the porter asked: what did you learn?')),
  P(('סינדבאד אמר: למדתי שמי שיוצא בספינה, חוזר משהו אחר.', 'Sindbad said: I learned that whoever goes out on a ship comes back as something else.'),
    ('ושהלוח בא, אבל צריך לתפוס אותו.', 'And that the board comes, but you have to grab it.'),
    ('ושהרעב משנה בן אדם, וגם הפחד, והזהב יותר מכולם.', 'And that hunger changes a person, and fear too, and gold more than all.'),
    ('ושהזר אוהב כל ארץ, ומתגעגע לארץ אחת.', 'And that the stranger loves every land, and longs for one.'),
    ('ושמי שלוקח יותר ממה שהוא צריך, הים לוקח ממנו.', 'And that whoever takes more than he needs, the sea takes from him.'),
    ('זה מה שלמדתי, בעשרים ושבע שנים, ושבעה מסעות, ושבע פעמים מוות.', 'That is what I learned, in twenty-seven years, and seven voyages, and seven times death.')),
  P(('ואז הוא הסתכל על הסבל, ואמר: ואתה, סינדבאד הסבל, מה למדת?', 'And then he looked at the porter, and said: and you, Sindbad the porter, what did you learn?'),
    ('הסבל אמר: למדתי שאני לא רוצה להיות אתה.', 'The porter said: I learned that I do not want to be you.'),
    ('אבל אני רוצה להיות החבר שלך.', 'But I want to be your friend.'),
    ('וסינדבאד המלח צחק, וקם, וחיבק אותו.', 'And Sindbad the sailor laughed, and got up, and hugged him.'),
    ('והוא אמר: מהיום אתה אוכל בשולחן שלי, ולא נושא משא לאף אחד.', 'And he said: from today you eat at my table, and carry no load for anyone.'),
    ('ונתן לו מאה מטבעות, בפעם האחרונה.', 'And gave him a hundred coins, for the last time.'),
    ('ושניהם חיו בבגדאד, חברים, עד שבא מה שלא מרחם על אף אחד.', 'And the two lived in Baghdad, friends, until there came what has mercy on no one.'),
    ('וזה הסוף של הסיפור של סינדבאד.', 'And that is the end of the story of Sindbad.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('sindbad', {'en': "Sindbad's Seven Voyages",
                                      'he': 'שבעת מסעות סינדבאד'}, 'intermediate',
                          CHAPTERS, unit='Chapter', unit_he='פרק', shelf=11, meta=META))
