#!/usr/bin/env python3
"""משלי איזופוס — thirty fables retold in modern Hebrew, graded to beginner.

The Hebrew twin of pipeline/book_aesop.py, fable for fable, so the two shelves are one shelf in
two languages. Aesop is ancient and anonymous in any practical sense — public domain by age,
with no edition being translated. These are retellings from the traditional plots.

WHY AESOP OPENS THE HEBREW SHELF TOO. The plots are known in English, so nothing is spent
working out what happens and all of the attention goes to the Hebrew. And a fable is the one
narrative shape that fits inside beginner sentences honestly: a setup, a turn, a line at the
end, none of which needs a subordinate clause.

Written to what he_bookshelf.py measures: present-tense narration where Hebrew prefers it,
past where the story turns, one clause a sentence, and a small recurring cast — שועל, אריה,
זאב, עורב, עכבר — so the same words come back fable after fable.

Deliberately unpointed. The vowels are looked up at ingest, never typed here.

Run:  python3 pipeline/he_book_aesop.py --lang he            # check
      python3 pipeline/he_book_aesop.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': "Aesop's Fables", 'author': 'Aesop (traditional)', 'year': 'c. 600 BCE',
        'status': 'public domain — ancient, anonymous'}

# (english title, hebrew title, [paragraph, ...])
CHAPTERS = [
 ('The Oak and the Reed', 'האלון והקנה', [
  P(('על יד הנהר עמד עץ גדול וגבוה.', 'Beside the river stood a big, tall tree.'),
    ('לידו, במים, גדל קנה קטן ורזה.', 'Beside it, in the water, grew a small, thin reed.'),
    ('העץ הסתכל על הקנה כל יום.', 'The tree looked at the reed every day.'),
    ('הוא אמר: אתה קטן מאוד וחלש.', 'It said: you are very small and weak.'),
    ('כל רוח קטנה מזיזה אותך לצדדים.', 'Every little wind moves you to the sides.')),
  P(('הקנה אמר: נכון, אני זז עם הרוח.', 'The reed said: true, I move with the wind.'),
    ('העץ אמר: תסתכל עליי, אני לא זז.', 'The tree said: look at me, I do not move.'),
    ('יש לי שורשים עמוקים באדמה.', 'I have deep roots in the earth.'),
    ('הקנה שתק ולא ענה לו כלום.', 'The reed was silent and did not answer it anything.')),
  P(('בלילה אחד באה רוח חזקה מאוד.', 'On one night a very strong wind came.'),
    ('הקנה ירד עד המים והתכופף.', 'The reed went down to the water and bent.'),
    ('העץ עמד ישר ולא רצה לזוז.', 'The tree stood straight and did not want to move.'),
    ('הרוח דחפה אותו שוב ושוב.', 'The wind pushed it again and again.'),
    ('ואז נשמע קול גדול, והעץ נפל.', 'And then a big sound was heard, and the tree fell.')),
  P(('בבוקר הקנה עמד שוב במים.', 'In the morning the reed stood again in the water.'),
    ('העץ הגדול שכב על האדמה.', 'The big tree lay on the ground.'),
    ('מי שיודע להתכופף לא נשבר.', 'Whoever knows how to bend does not break.'))]),
 ('The Fox and the Grapes', 'השועל והענבים', [
  P(('שועל הלך בדרך ביום חם מאוד.', 'A fox walked on the road on a very hot day.'),
    ('הוא היה רעב, והוא חיפש אוכל.', 'He was hungry, and he looked for food.'),
    ('ואז הוא ראה ענבים על עץ גבוה.', 'And then he saw grapes on a tall tree.'),
    ('הענבים היו גדולים, ואדומים, ויפים.', 'The grapes were big, and red, and beautiful.'),
    ('השועל אמר: זה בדיוק מה שאני רוצה.', 'The fox said: that is exactly what I want.')),
  P(('הוא קפץ פעם אחת, ולא הגיע.', 'He jumped one time, and did not reach.'),
    ('הוא הלך אחורה, ורץ, וקפץ שוב.', 'He went back, and ran, and jumped again.'),
    ('גם בפעם הזאת הוא לא הגיע.', 'This time too he did not reach.'),
    ('הוא ניסה עוד ועוד, עד שהתעייף.', 'He tried again and again, until he grew tired.'),
    ('הרגליים שלו כאבו, והוא נשם חזק.', 'His legs hurt, and he breathed hard.')),
  P(('הוא ישב על האדמה והסתכל למעלה.', 'He sat on the ground and looked up.'),
    ('הענבים היו שם, בדיוק באותו מקום.', 'The grapes were there, in exactly the same place.'),
    ('השועל קם והתחיל ללכת משם.', 'The fox got up and began to walk away from there.'),
    ('הוא אמר בקול: הענבים האלה חמוצים.', 'He said aloud: these grapes are sour.'),
    ('ואיש לא רוצה ענבים חמוצים.', 'And no one wants sour grapes.'),
    ('קל לומר על דבר שהוא לא טוב.', 'It is easy to say about a thing that it is not good.'))]),
 ('The Tortoise and the Hare', 'הצב והארנב', [
  P(('ארנב רץ מהר יותר מכל חיה ביער.', 'A hare ran faster than any animal in the forest.'),
    ('הוא סיפר על זה לכולם כל יום.', 'He told everyone about it every day.'),
    ('יום אחד הוא ראה צב הולך לאט.', 'One day he saw a tortoise walking slowly.'),
    ('הוא צחק ואמר: תראו איך הוא הולך.', 'He laughed and said: look how he walks.'),
    ('הצב אמר: אני מוכן לרוץ נגדך.', 'The tortoise said: I am ready to run against you.')),
  P(('כל החיות באו לראות את המרוץ.', 'All the animals came to see the race.'),
    ('השועל עמד וספר: אחת, שתיים, שלוש.', 'The fox stood and counted: one, two, three.'),
    ('הארנב רץ מהר ונעלם בין העצים.', 'The hare ran fast and disappeared among the trees.'),
    ('הצב התחיל ללכת, צעד אחרי צעד.', 'The tortoise began to walk, step after step.')),
  P(('הארנב עצר באמצע הדרך והסתכל אחורה.', 'The hare stopped in the middle of the road and looked back.'),
    ('הוא לא ראה את הצב בכלל.', 'He did not see the tortoise at all.'),
    ('הוא אמר: יש לי הרבה זמן.', 'He said: I have a lot of time.'),
    ('הוא שכב מתחת לעץ ואז נרדם.', 'He lay under a tree and fell asleep.')),
  P(('הצב המשיך ללכת בלי לעצור.', 'The tortoise continued to walk without stopping.'),
    ('הוא עבר על יד הארנב הישן.', 'He passed beside the sleeping hare.'),
    ('הוא הגיע לסוף, וכולם צעקו.', 'He reached the end, and everyone shouted.'),
    ('הארנב קם מהקול, ורץ מהר.', 'The hare got up from the noise, and ran fast.'),
    ('אבל הצב כבר עמד שם וחייך.', 'But the tortoise already stood there and smiled.'),
    ('לאט ובלי לעצור זה מגיע רחוק.', 'Slowly and without stopping gets far.'))]),
 ('The Lion and the Mouse', 'האריה והעכבר', [
  P(('אריה גדול ישן בשמש אחרי הצהריים.', 'A big lion slept in the sun in the afternoon.'),
    ('עכבר קטן רץ ועלה עליו בטעות.', 'A small mouse ran and climbed on him by mistake.'),
    ('האריה פתח את העיניים ותפס אותו.', 'The lion opened his eyes and caught him.'),
    ('הוא אמר: עכשיו אני אוכל אותך.', 'He said: now I shall eat you.'),
    ('העכבר אמר: בבקשה, תן לי ללכת.', 'The mouse said: please, let me go.')),
  P(('העכבר אמר: יום אחד אני אעזור לך.', 'The mouse said: one day I shall help you.'),
    ('האריה צחק חזק מאוד מזה.', 'The lion laughed very hard at that.'),
    ('הוא אמר: אתה? תעזור לי?', 'He said: you? Will help me?'),
    ('הוא פתח את היד ונתן לו ללכת.', 'He opened his hand and let him go.'),
    ('העכבר רץ ונעלם בין העשב.', 'The mouse ran and disappeared among the grass.')),
  P(('אחרי כמה ימים אנשים באו ליער.', 'After a few days people came to the forest.'),
    ('הם שמו רשת בין שני עצים.', 'They put a net between two trees.'),
    ('האריה נכנס לרשת ולא יכול לצאת.', 'The lion entered the net and could not get out.'),
    ('הוא צעק בקול גדול מאוד.', 'He shouted in a very loud voice.')),
  P(('העכבר שמע את הקול ורץ לשם.', 'The mouse heard the voice and ran there.'),
    ('הוא התחיל לאכול את החוטים.', 'He began to eat the threads.'),
    ('הוא עבד הרבה זמן, בלי לעצור.', 'He worked a long time, without stopping.'),
    ('הרשת נפתחה, והאריה יצא.', 'The net opened, and the lion came out.'),
    ('גם חבר קטן יכול לעזור מאוד.', 'Even a small friend can help a great deal.'))]),
 ('The Fox and the Stork', 'השועל והחסידה', [
  P(('שועל וחסידה היו חברים טובים.', 'A fox and a stork were good friends.'),
    ('יום אחד השועל אמר לה: בואי לאכול.', 'One day the fox said to her: come to eat.'),
    ('החסידה שמחה מאוד ובאה בערב.', 'The stork was very happy and came in the evening.'),
    ('השועל שם מרק בצלחת שטוחה.', 'The fox put soup in a flat plate.')),
  P(('השועל אכל הכול מהר מאוד.', 'The fox ate everything very fast.'),
    ('החסידה ניסתה, אבל היא לא הצליחה.', 'The stork tried, but she did not succeed.'),
    ('הצוואר שלה היה ארוך וצר.', 'Her neck was long and narrow.'),
    ('היא הלכה הביתה רעבה מאוד.', 'She went home very hungry.'),
    ('השועל צחק אחרי שהיא יצאה.', 'The fox laughed after she went out.')),
  P(('אחרי שבוע החסידה אמרה: בוא אליי.', 'After a week the stork said: come to me.'),
    ('השועל בא, והוא היה רעב.', 'The fox came, and he was hungry.'),
    ('היא שמה את האוכל בכד גבוה וצר.', 'She put the food in a tall, narrow jar.'),
    ('היא הכניסה את הראש ואכלה יפה.', 'She put in her head and ate nicely.')),
  P(('השועל הסתכל על הכד ולא הצליח.', 'The fox looked at the jar and did not succeed.'),
    ('האף שלו היה גדול מדי בשבילו.', 'His nose was too big for it.'),
    ('הוא הלך הביתה בלי לאכול כלום.', 'He went home without eating anything.'),
    ('מה שאתה עושה חוזר אליך.', 'What you do comes back to you.'))]),
 ('The Fisherman and the Little Fish', 'הדייג והדג הקטן', [
  P(('דייג עבד על יד הים כל היום.', 'A fisherman worked beside the sea all day.'),
    ('הוא זרק את הרשת פעם אחר פעם.', 'He threw the net time after time.'),
    ('בכל פעם הרשת יצאה ריקה.', 'Every time the net came out empty.'),
    ('בערב הוא היה עייף ועצוב.', 'In the evening he was tired and sad.')),
  P(('בפעם האחרונה הוא הרים את הרשת.', 'The last time he lifted the net.'),
    ('בתוכה היה דג אחד, קטן מאוד.', 'Inside it was one fish, very small.'),
    ('הדג אמר: תן לי לחזור למים.', 'The fish said: let me go back to the water.'),
    ('הוא אמר: אני קטן, ואין בי בשר.', 'He said: I am small, and there is no meat in me.')),
  P(('הדג אמר: תחכה שנה או שנתיים.', 'The fish said: wait a year or two.'),
    ('הוא אמר: אני אגדל, ואני אהיה דג גדול.', 'He said: I shall grow and be a big fish.'),
    ('הוא אמר: ואז תתפוס אותי שוב.', 'He said: and then you will catch me again.'),
    ('הוא אמר: ואתה תקבל הרבה יותר בשוק.', 'He said: and you will get much more at the market.')),
  P(('הדייג הסתכל בדג הקטן וחשב.', 'The fisherman looked at the small fish and thought.'),
    ('הוא אמר: אתה מדבר יפה מאוד.', 'He said: you speak very nicely.'),
    ('אבל אתה בידיים שלי עכשיו.', 'But you are in my hands now.'),
    ('ומחר אולי לא אתפוס כלום.', 'And tomorrow perhaps I shall catch nothing.'),
    ('דבר קטן ביד טוב מדבר גדול רחוק.', 'A small thing in hand is better than a big thing far away.'))]),
 ('The Dove and the Ant', 'היונה והנמלה', [
  P(('נמלה קטנה ירדה לנהר לשתות.', 'A small ant went down to the river to drink.'),
    ('המים היו מהירים והיא נפלה פנימה.', 'The water was fast and she fell in.'),
    ('היא ניסתה לצאת ולא הצליחה.', 'She tried to get out and did not succeed.'),
    ('המים לקחו אותה עוד ועוד.', 'The water took her further and further.')),
  P(('יונה ישבה על ענף מעל הנהר.', 'A dove sat on a branch above the river.'),
    ('היא ראתה את הנמלה במים.', 'She saw the ant in the water.'),
    ('היא לקחה עלה וזרקה אותו למטה.', 'She took a leaf and threw it down.'),
    ('הנמלה עלתה על העלה והחזיקה חזק.', 'The ant climbed on the leaf and held tight.'),
    ('העלה הגיע לחוף, והנמלה יצאה.', 'The leaf reached the shore, and the ant came out.')),
  P(('אחרי כמה ימים בא צייד ליער.', 'After a few days a hunter came to the forest.'),
    ('הוא ראה את היונה על העץ.', 'He saw the dove on the tree.'),
    ('הוא הרים את הרובה שלו לאט.', 'He raised his gun slowly.'),
    ('הנמלה ראתה אותו מהאדמה.', 'The ant saw him from the ground.')),
  P(('היא רצה מהר ועלתה על הרגל שלו.', 'She ran fast and climbed on his foot.'),
    ('היא נשכה אותו חזק מאוד.', 'She bit him very hard.'),
    ('הצייד צעק והזיז את הרגל.', 'The hunter shouted and moved his foot.'),
    ('היונה שמעה ועפה משם מיד.', 'The dove heard and flew away from there at once.'),
    ('טובה קטנה חוזרת ביום קשה.', 'A small kindness returns on a hard day.'))]),
 ('The Stag at the Pool', 'האייל ליד הבריכה', [
  P(('אייל בא לשתות מים בבוקר.', 'A stag came to drink water in the morning.'),
    ('המים היו שקטים כמו מראה.', 'The water was quiet like a mirror.'),
    ('הוא ראה את עצמו בתוך המים.', 'He saw himself in the water.'),
    ('הוא הסתכל על הקרניים שלו.', 'He looked at his horns.')),
  P(('הוא אמר: הקרניים שלי יפות מאוד.', 'He said: my horns are very beautiful.'),
    ('הן גדולות, והן עולות למעלה.', 'They are big, and they rise upwards.'),
    ('ואז הוא ראה את הרגליים שלו.', 'And then he saw his legs.'),
    ('הוא אמר: הרגליים האלה דקות מדי.', 'He said: these legs are too thin.'),
    ('אני נבוך כשאני רואה אותן.', 'I am embarrassed when I see them.')),
  P(('פתאום הוא שמע כלבים מרחוק.', 'Suddenly he heard dogs from far away.'),
    ('הוא התחיל לרוץ מהר מאוד.', 'He began to run very fast.'),
    ('הרגליים הדקות לקחו אותו רחוק.', 'The thin legs took him far.'),
    ('הכלבים נשארו הרבה מאחור.', 'The dogs remained a long way behind.')),
  P(('ואז הוא נכנס לתוך היער.', 'And then he entered into the forest.'),
    ('הקרניים שלו נתפסו בין הענפים.', 'His horns were caught among the branches.'),
    ('הוא משך, ולא הצליח לצאת.', 'He pulled, and did not manage to get out.'),
    ('הכלבים הגיעו, והוא הבין הכול.', 'The dogs arrived, and he understood everything.'),
    ('מה שיפה לא תמיד עוזר.', 'What is beautiful does not always help.'))]),
 ('The Peacock and the Crane', 'הטווס והעגור', [
  P(('טווס עמד בגן ופתח את הזנב.', 'A peacock stood in the garden and opened his tail.'),
    ('הזנב שלו היה מלא צבעים.', 'His tail was full of colours.'),
    ('כל מי שעבר עמד והסתכל.', 'Everyone who passed stopped and looked.'),
    ('הטווס הלך לאט מצד לצד.', 'The peacock walked slowly from side to side.')),
  P(('עגור אפור ירד לגן לאכול.', 'A grey crane came down to the garden to eat.'),
    ('הטווס הסתכל עליו וצחק.', 'The peacock looked at him and laughed.'),
    ('הוא אמר: תראה איזה צבע יש לך.', 'He said: look what a colour you have.'),
    ('הוא אמר: אתה אפור כמו אבן.', 'He said: you are grey like a stone.'),
    ('הוא אמר: ואני יפה כמו מלך.', 'He said: and I am beautiful like a king.')),
  P(('העגור אמר: נכון, אתה יפה מאוד.', 'The crane said: true, you are very beautiful.'),
    ('העגור פתח את הכנפיים לאט.', 'The crane opened his wings slowly.'),
    ('הוא עלה למעלה, אל השמיים.', 'He rose upwards, to the sky.'),
    ('הוא עף מעל הבתים ומעל העצים.', 'He flew above the houses and above the trees.')),
  P(('הטווס נשאר עומד באדמה.', 'The peacock remained standing on the ground.'),
    ('הוא פתח את הכנפיים וניסה.', 'He opened his wings and tried.'),
    ('הוא לא עלה אפילו מטר אחד.', 'He did not rise even one metre.'),
    ('העגור קרא לו מלמעלה: אני הולך.', 'The crane called to him from above: I am going.'),
    ('מי שיפה בלי כוח לא מגיע רחוק.', 'Beauty without strength does not take one far.'))]),
 ('The Wolf and the Crane', 'הזאב והעגור', [
  P(('זאב אכל בשר מהר מאוד בערב.', 'A wolf ate meat very fast in the evening.'),
    ('עצם נתקעה לו בתוך הגרון.', 'A bone got stuck in his throat.'),
    ('הוא לא יכול לאכול ולא לשתות.', 'He could not eat and could not drink.'),
    ('הוא רץ ביער וחיפש עזרה.', 'He ran in the forest and looked for help.')),
  P(('הוא פגש חיות ושאל את כולן.', 'He met animals and asked all of them.'),
    ('כולן ברחו ממנו בלי לענות.', 'All of them ran from him without answering.'),
    ('ואז הוא ראה עגור על יד המים.', 'And then he saw a crane beside the water.'),
    ('הוא אמר: יש לך צוואר ארוך.', 'He said: you have a long neck.'),
    ('הוא אמר: תוציא לי את העצם.', 'He said: take the bone out for me.')),
  P(('העגור אמר: אני מפחד מהשיניים שלך.', 'The crane said: I am afraid of your teeth.'),
    ('הזאב אמר: אני אשלם לך יפה.', 'The wolf said: I shall pay you well.'),
    ('העגור הכניס את הראש לתוך הפה.', 'The crane put his head into the mouth.'),
    ('הוא לקח את העצם ואז יצא מהר.', 'He took the bone and came out fast.')),
  P(('הזאב נשם ושתה מים קרים.', 'The wolf breathed and drank cold water.'),
    ('העגור אמר: ועכשיו התשלום שלי.', 'The crane said: and now my payment.'),
    ('הזאב צחק ואמר: איזה תשלום?', 'The wolf laughed and said: what payment?'),
    ('הוא אמר: הראש שלך היה בפה שלי.', 'He said: your head was in my mouth.'),
    ('הוא אמר: ואז יצאת חי, וזה מספיק.', 'He said: and you came out alive, and that is enough.'),
    ('מרשע אל תבקש תודה.', 'From a wicked one do not ask thanks.'))]),
 ('The Town Mouse and the Country Mouse', 'עכבר העיר ועכבר הכפר', [
  P(('עכבר גר בשדה על יד הכפר.', 'A mouse lived in a field beside the village.'),
    ('הבית שלו היה חור באדמה.', 'His house was a hole in the ground.'),
    ('יום אחד בא אליו חבר מהעיר.', 'One day a friend from the city came to him.'),
    ('הוא הכין לו אוכל: חיטה ומים.', 'He prepared food for him: wheat and water.')),
  P(('עכבר העיר אכל מעט מאוד.', 'The city mouse ate very little.'),
    ('הוא אמר: איך אתה חי ככה?', 'He said: how do you live like this?'),
    ('הוא אמר: אצלנו יש אוכל אחר לגמרי.', 'He said: with us there is entirely different food.'),
    ('הוא אמר: בוא איתי הערב לעיר.', 'He said: come with me this evening to the city.'),
    ('עכבר השדה הסכים והם הלכו.', 'The field mouse agreed and they went.')),
  P(('הם הגיעו לבית גדול בעיר.', 'They arrived at a big house in the city.'),
    ('על השולחן היה אוכל של אנשים.', 'On the table was people’s food.'),
    ('היו שם גבינה, ולחם, ופירות.', 'There were there cheese, and bread, and fruit.'),
    ('עכבר השדה אמר: זה באמת יפה.', 'The field mouse said: this is really fine.')),
  P(('פתאום נפתחה הדלת בקול.', 'Suddenly the door opened with a noise.'),
    ('שני כלבים נכנסו לתוך החדר.', 'Two dogs came into the room.'),
    ('שני העכברים ברחו לתוך חור.', 'The two mice ran into a hole.'),
    ('הם ישבו שם וחיכו בשקט.', 'They sat there and waited quietly.')),
  P(('עכבר השדה אמר: אני הולך הביתה.', 'The field mouse said: I am going home.'),
    ('הוא אמר: אצלי יש רק חיטה.', 'He said: with me there is only wheat.'),
    ('הוא אמר: אבל אני אוכל בשקט.', 'He said: but I eat quietly.'),
    ('לחם יבש בשקט טוב מבשר בפחד.', 'Dry bread in quiet is better than meat in fear.'))]),
 ('The Boastful Traveller', 'המטייל שהתפאר', [
  P(('איש חזר הביתה אחרי נסיעה ארוכה.', 'A man came home after a long journey.'),
    ('כל הערב הוא סיפר על הדרך.', 'All evening he told about the road.'),
    ('הוא אמר: הייתי בהרבה ארצות.', 'He said: I was in many countries.'),
    ('הוא אמר: וראיתי דברים גדולים.', 'He said: and I saw big things.')),
  P(('הוא אמר: באי אחד היה מרוץ.', 'He said: on one island there was a race.'),
    ('הוא אמר: וכולם קפצו רחוק מאוד.', 'He said: and everyone jumped very far.'),
    ('הוא אמר: אבל אני קפצתי הכי רחוק.', 'He said: but I jumped the farthest.'),
    ('הוא אמר: קפצתי עשרה מטרים בבת אחת.', 'He said: I jumped ten metres at once.'),
    ('האנשים סביבו הסתכלו זה על זה.', 'The people around him looked at each other.')),
  P(('הוא אמר: ויש שם אנשים שראו אותי.', 'He said: and there are people there who saw me.'),
    ('הוא אמר: תשאלו אותם, והם יגידו לכם.', 'He said: ask them, and they will tell you.'),
    ('אחד מהאנשים קם ואמר בשקט: יפה מאוד.', 'One of the people got up and said quietly: fine.'),
    ('הוא אמר: אבל אנחנו לא ניסע לשם.', 'He said: but we shall not travel there.')),
  P(('הוא סימן קו על האדמה ברגל.', 'He marked a line on the ground with his foot.'),
    ('הוא אמר: תגיד שזה האי, כאן.', 'He said: say that this is the island, here.'),
    ('הוא אמר: ועכשיו תקפוץ בשבילנו.', 'He said: and now jump for us.'),
    ('האיש עמד ולא אמר עוד מילה.', 'The man stood and did not say another word.'),
    ('מי שעשה משהו לא צריך לספר.', 'Whoever did something does not need to tell about it.'))]),
 ('The Frog and the Ox', 'הצפרדע והשור', [
  P(('צפרדע ישבה על יד המים עם הילדים שלה.', 'A frog sat beside the water with her children.'),
    ('שור גדול בא לשתות מהנהר.', 'A big ox came to drink from the river.'),
    ('הצפרדעים הקטנות ברחו מהר.', 'The little frogs ran away fast.'),
    ('הן חזרו אחר כך וסיפרו לאמא.', 'They came back afterwards and told their mother.')),
  P(('הן אמרו: ראינו חיה גדולה מאוד.', 'They said: we saw a very big animal.'),
    ('האמא אמרה: גדולה כמה?', 'The mother said: big how much?'),
    ('היא נשמה עמוק ונעשתה גדולה.', 'She breathed deep and became big.'),
    ('היא שאלה: היא הייתה גדולה ככה?', 'She asked: was it as big as this?'),
    ('הן אמרו: לא, הרבה יותר גדולה.', 'They said: no, much bigger.')),
  P(('היא נשמה עוד פעם, חזק יותר.', 'She breathed again, harder.'),
    ('היא שאלה: ועכשיו? עכשיו כמוה?', 'She asked: and now? Now like it?'),
    ('הן אמרו: לא, את עוד קטנה.', 'They said: no, you are still small.'),
    ('הן אמרו: אמא, בבקשה, תפסיקי.', 'They said: mother, please, stop.')),
  P(('היא לא הקשיבה להן בכלל.', 'She did not listen to them at all.'),
    ('היא נשמה עוד פעם, הכי חזק.', 'She breathed again, the hardest.'),
    ('ואז נשמע קול קטן, והיא נפלה.', 'And then a small sound was heard, and she fell.'),
    ('הילדים ישבו לידה בשקט.', 'The children sat beside her quietly.'),
    ('מי שרוצה להיות אחר נשבר.', 'Whoever wants to be someone else breaks.'))]),
 ('The Farmer and the Snake', 'האיכר והנחש', [
  P(('בחורף קר איכר הלך בשדה שלו.', 'In a cold winter a farmer walked in his field.'),
    ('הוא ראה נחש שוכב על השלג.', 'He saw a snake lying on the snow.'),
    ('הנחש לא זז, והוא היה קפוא.', 'The snake did not move, and it was frozen.'),
    ('האיכר עמד והסתכל עליו רגע.', 'The farmer stood and looked at it a moment.')),
  P(('הוא אמר: הוא ימות כאן בקור.', 'He said: it will die here in the cold.'),
    ('הוא הרים אותו ושם אותו בבגד.', 'He picked it up and put it in his clothing.'),
    ('הוא הלך הביתה מהר מאוד.', 'He walked home very fast.'),
    ('אשתו אמרה: למה הבאת אותו?', 'His wife said: why did you bring it?'),
    ('הוא אמר: הוא קטן, ואין בו סכנה.', 'He said: it is small, and there is no danger in it.')),
  P(('הוא שם אותו על יד האש.', 'He put it beside the fire.'),
    ('החום נכנס לגוף של הנחש.', 'The heat entered the snake’s body.'),
    ('הוא התחיל לזוז לאט לאט.', 'It began to move slowly slowly.'),
    ('אחרי שעה הוא כבר היה חזק.', 'After an hour it was already strong.')),
  P(('הילדים באו לראות אותו.', 'The children came to see it.'),
    ('הנחש הרים את הראש אליהם.', 'The snake raised its head to them.'),
    ('האיכר קפץ ולקח מקל מהפינה.', 'The farmer jumped and took a stick from the corner.'),
    ('הוא הוציא אותו החוצה מהר.', 'He took it outside fast.'),
    ('טובה לרע חוזרת ברעה.', 'A kindness to a bad one comes back as harm.'))]),
 ("The Ass and His Masters", 'החמור והבעלים שלו', [
  P(('חמור עבד אצל איש שמכר ירקות.', 'A donkey worked for a man who sold vegetables.'),
    ('הוא קם מוקדם והלך לשוק.', 'He got up early and went to the market.'),
    ('הוא נשא סלים כבדים כל היום.', 'He carried heavy baskets all day.'),
    ('בערב הוא קיבל מעט אוכל.', 'In the evening he received little food.')),
  P(('הוא אמר: אני רוצה בעלים אחרים.', 'He said: I want other masters.'),
    ('הוא ביקש את זה בתפילה כל לילה.', 'He asked for it in prayer every night.'),
    ('אחרי חודש האיש מכר אותו.', 'After a month the man sold him.'),
    ('הקונה החדש עשה לבנים מחומר.', 'The new buyer made bricks from clay.')),
  P(('החמור נשא לבנים כל היום.', 'The donkey carried bricks all day.'),
    ('הן היו כבדות מהירקות.', 'They were heavier than the vegetables.'),
    ('בערב הוא קיבל עוד פחות אוכל.', 'In the evening he received even less food.'),
    ('הוא אמר: הראשון היה טוב יותר.', 'He said: the first one was better.'),
    ('הוא ביקש שוב בעלים אחרים.', 'He asked again for other masters.')),
  P(('הפעם קנה אותו איש שעבד בעור.', 'This time a man who worked in leather bought him.'),
    ('החמור עבד אצלו יום אחד.', 'The donkey worked for him one day.'),
    ('בערב הוא ראה את החצר.', 'In the evening he saw the yard.'),
    ('היו שם עורות של חיות על הקיר.', 'There were animal skins on the wall there.'),
    ('הוא אמר: היה לי טוב ולא ידעתי.', 'He said: I had it good and did not know.'))]),
 ('The Goose and the Golden Eggs', 'האווז וביצי הזהב', [
  P(('לאיש ולאשתו היה אווז בחצר.', 'A man and his wife had a goose in the yard.'),
    ('בוקר אחד הם מצאו ביצה מוזרה.', 'One morning they found a strange egg.'),
    ('היא הייתה כבדה וצהובה מאוד.', 'It was heavy and very yellow.'),
    ('האיש לקח אותה לשוק לבדוק.', 'The man took it to the market to check.'),
    ('הסוחר אמר: זאת ביצה של זהב.', 'The merchant said: this is an egg of gold.')),
  P(('הם חזרו הביתה מאושרים מאוד.', 'They came home very happy.'),
    ('בבוקר השני הייתה עוד ביצה.', 'On the second morning there was another egg.'),
    ('וגם ביום השלישי, וגם ברביעי.', 'And also on the third day, and on the fourth.'),
    ('הם קנו בית חדש ובגדים חדשים.', 'They bought a new house and new clothes.')),
  P(('אחרי חודש האיש אמר לאשתו: זה לאט.', 'After a month the man said to his wife: this is slow.'),
    ('הוא אמר: ביצה אחת בכל יום.', 'He said: one egg every day.'),
    ('הוא אמר: בטח יש בפנים הרבה זהב.', 'He said: surely there is a lot of gold inside.'),
    ('היא אמרה: אולי כדאי לחכות.', 'She said: perhaps it is worth waiting.'),
    ('הוא אמר: לא, אני רוצה הכול היום.', 'He said: no, I want everything today.')),
  P(('הוא לקח סכין והלך לחצר.', 'He took a knife and went to the yard.'),
    ('אחרי דקה הוא חזר לבית.', 'After a minute he came back to the house.'),
    ('הוא אמר: אין שם כלום בכלל.', 'He said: there is nothing there at all.'),
    ('ומאותו יום לא הייתה עוד ביצה.', 'And from that day there was no more egg.'),
    ('מי שרוצה הכול מאבד גם את המעט.', 'Whoever wants everything loses even the little.'))]),
 ('The Dog and His Reflection', 'הכלב והבבואה', [
  P(('כלב מצא חתיכת בשר גדולה.', 'A dog found a big piece of meat.'),
    ('הוא לקח אותה בפה והלך הביתה.', 'He took it in his mouth and went home.'),
    ('הוא היה שמח מאוד באותו יום.', 'He was very happy that day.'),
    ('בדרך הוא הגיע לגשר קטן.', 'On the way he came to a small bridge.')),
  P(('הוא עצר והסתכל למטה, למים.', 'He stopped and looked down, at the water.'),
    ('הוא ראה שם כלב אחר.', 'He saw there another dog.'),
    ('גם לכלב הזה היה בשר בפה.', 'That dog too had meat in its mouth.'),
    ('הוא חשב: הבשר שלו גדול יותר.', 'He thought: his meat is bigger.'),
    ('הוא חשב: אני רוצה גם אותו.', 'He thought: I want it too.')),
  P(('הוא פתח את הפה כדי לצעוק.', 'He opened his mouth in order to bark.'),
    ('הבשר שלו נפל לתוך המים.', 'His meat fell into the water.'),
    ('הוא ראה אותו יורד ונעלם.', 'He saw it going down and disappearing.'),
    ('הוא חיפש את הכלב האחר.', 'He looked for the other dog.'),
    ('גם הוא לא היה שם יותר.', 'It too was no longer there.')),
  P(('הכלב עמד על הגשר לבד.', 'The dog stood on the bridge alone.'),
    ('הוא הלך הביתה בלי כלום.', 'He went home with nothing.'),
    ('מי שרודף אחרי צל מאבד את שלו.', 'Whoever chases after a shadow loses his own.'))]),
 ('The Old Man and Death', 'הזקן והמוות', [
  P(('איש זקן עבד ביער כל היום.', 'An old man worked in the forest all day.'),
    ('הוא חתך עצים ושם אותם על הגב.', 'He cut wood and put it on his back.'),
    ('הדרך הביתה הייתה ארוכה מאוד.', 'The road home was very long.'),
    ('העצים היו כבדים והיה חם.', 'The wood was heavy and it was hot.')),
  P(('באמצע הדרך הוא עצר לנוח.', 'In the middle of the road he stopped to rest.'),
    ('הוא הוריד את העצים לאדמה.', 'He put the wood down on the ground.'),
    ('הוא ישב על אבן ואז נשם חזק.', 'He sat on a stone and breathed hard.'),
    ('הרגליים שלו כאבו מאוד.', 'His legs hurt a great deal.')),
  P(('הוא אמר: החיים שלי קשים מדי.', 'He said: my life is too hard.'),
    ('הוא אמר: כל יום אותו דבר.', 'He said: every day the same thing.'),
    ('הוא אמר: המוות, בוא אליי.', 'He said: death, come to me.'),
    ('הוא אמר את זה בקול גדול.', 'He said it in a loud voice.')),
  P(('פתאום מישהו עמד לידו.', 'Suddenly someone stood beside him.'),
    ('הוא היה גבוה, ולבוש שחור.', 'He was tall, and dressed in black.'),
    ('הוא אמר: קראת לי, ובאתי.', 'He said: you called me, and I came.'),
    ('הזקן הסתכל בו ופחד מאוד.', 'The old man looked at him and was very afraid.'),
    ('הוא אמר: כן, קראתי לך.', 'He said: yes, I called you.'),
    ('הוא אמר: תעזור לי להרים את העצים.', 'He said: help me to lift the wood.'))]),
 ('The Two Travellers and the Bear', 'שני המטיילים והדוב', [
  P(('שני חברים הלכו יחד בדרך ביער.', 'Two friends walked together on a road in the forest.'),
    ('הם דיברו כל הזמן ולא פחדו.', 'They talked all the time and were not afraid.'),
    ('אחד אמר: אנחנו חברים אמיתיים.', 'One said: we are real friends.'),
    ('השני אמר: נכון, ולתמיד.', 'The second said: true, and forever.')),
  P(('פתאום יצא דוב גדול מבין העצים.', 'Suddenly a big bear came out from among the trees.'),
    ('הראשון רץ מיד ועלה על עץ.', 'The first ran at once and climbed a tree.'),
    ('הוא לא קרא לחבר שלו בכלל.', 'He did not call his friend at all.'),
    ('השני לא ידע לעלות על עצים.', 'The second did not know how to climb trees.'),
    ('הוא שכב על האדמה ולא זז.', 'He lay on the ground and did not move.')),
  P(('הוא עצר את הנשימה שלו.', 'He held his breath.'),
    ('הדוב בא וריח אותו לאט.', 'The bear came and smelled him slowly.'),
    ('הוא שם את האף ליד האוזן.', 'It put its nose beside his ear.'),
    ('ואז הוא הלך משם בשקט.', 'And then it went away quietly.')),
  P(('הראשון ירד מהעץ וצחק.', 'The first came down from the tree and laughed.'),
    ('הוא שאל: מה הדוב אמר לך?', 'He asked: what did the bear say to you?'),
    ('השני קם וניקה את הבגדים.', 'The second got up and cleaned his clothes.'),
    ('הוא אמר: הוא אמר לי דבר אחד.', 'He said: it said one thing to me.'),
    ('הוא אמר: אל תלך עם מי שבורח.', 'He said: do not walk with one who runs away.'))]),
 ('The Crow and the Pitcher', 'העורב והכד', [
  P(('היה קיץ חם מאוד באותה שנה.', 'It was a very hot summer that year.'),
    ('הנהרות היו יבשים, ולא היו מים.', 'The rivers were dry, and there was no water.'),
    ('עורב עף שעות וחיפש משהו לשתות.', 'A crow flew for hours and looked for something to drink.'),
    ('הוא היה עייף מאוד וצמא.', 'He was very tired and thirsty.')),
  P(('ואז הוא ראה כד ליד בית.', 'And then he saw a jar beside a house.'),
    ('הוא ירד מהר ועמד עליו.', 'He came down fast and stood on it.'),
    ('בתוך הכד היו מעט מים.', 'Inside the jar there was little water.'),
    ('הוא הכניס את הראש ולא הגיע.', 'He put his head in and did not reach.'),
    ('הצוואר של הכד היה צר וארוך.', 'The neck of the jar was narrow and long.')),
  P(('הוא ניסה להפיל את הכד.', 'He tried to knock the jar over.'),
    ('הכד היה כבד ולא זז.', 'The jar was heavy and did not move.'),
    ('הוא ישב לידו וחשב רגע.', 'He sat beside it and thought a moment.'),
    ('ואז הוא ראה אבנים קטנות.', 'And then he saw small stones.')),
  P(('הוא לקח אבן והכניס אותה פנימה.', 'He took a stone and put it inside.'),
    ('המים עלו קצת מאוד.', 'The water rose very little.'),
    ('הוא לקח עוד אבן, ועוד אחת.', 'He took another stone, and one more.'),
    ('הוא עבד ככה זמן רב.', 'He worked like that a long time.'),
    ('בסוף המים הגיעו עד למעלה.', 'In the end the water reached the top.'),
    ('הוא שתה, ואז עף לו בשמחה.', 'He drank, and then flew off happily.'))]),
 ('The Bundle of Sticks', 'צרור המקלות', [
  P(('לאיכר זקן היו ארבעה בנים.', 'An old farmer had four sons.'),
    ('הם רבו כל יום על כל דבר.', 'They quarrelled every day about everything.'),
    ('הם רבו על השדה ועל הכסף.', 'They quarrelled about the field and about the money.'),
    ('האב דיבר איתם, והם לא הקשיבו.', 'The father spoke with them, and they did not listen.')),
  P(('יום אחד הוא קרא להם לחצר.', 'One day he called them to the yard.'),
    ('הוא הביא צרור של מקלות דקים.', 'He brought a bundle of thin sticks.'),
    ('הוא נתן אותו לבן הגדול.', 'He gave it to the big son.'),
    ('הוא אמר: תשבור את זה עכשיו.', 'He said: break this now.')),
  P(('הבן לקח את הצרור בשתי ידיים.', 'The son took the bundle in two hands.'),
    ('הוא משך חזק, ולא קרה כלום.', 'He pulled hard, and nothing happened.'),
    ('הוא ניסה על הברך, ולא הצליח.', 'He tried on his knee, and did not succeed.'),
    ('גם השני ניסה, וגם השלישי.', 'The second also tried, and the third too.'),
    ('הצרור נשאר שלם בידיים שלהם.', 'The bundle remained whole in their hands.')),
  P(('האב פתח את החוט לאט.', 'The father opened the string slowly.'),
    ('הוא נתן מקל אחד לכל בן.', 'He gave one stick to each son.'),
    ('הוא אמר: עכשיו תשברו אותם.', 'He said: now break them.'),
    ('כל אחד שבר את המקל שלו מיד.', 'Each one broke his stick at once.'),
    ('האב אמר: ראיתם? זה הכול.', 'The father said: did you see? That is all.'),
    ('יחד אתם חזקים, לבד אתם נשברים.', 'Together you are strong, alone you break.'))]),
 ('Belling the Cat', 'הפעמון על החתול', [
  P(('בבית גדול גרו הרבה עכברים.', 'In a big house lived many mice.'),
    ('בבית גר גם חתול שקט.', 'In the house lived also a quiet cat.'),
    ('הוא הלך בלי קול על הרצפה.', 'He walked without sound on the floor.'),
    ('העכברים לא שמעו אותו בכלל.', 'The mice did not hear him at all.'),
    ('בכל שבוע נעלם עוד עכבר.', 'Every week another mouse disappeared.')),
  P(('יום אחד הם עשו אספה בחור.', 'One day they held a meeting in the hole.'),
    ('הזקן שבהם אמר: מה נעשה?', 'The oldest among them said: what shall we do?'),
    ('אחד אמר: נצא רק בלילה.', 'One said: we shall go out only at night.'),
    ('אחר אמר: גם בלילה הוא ער.', 'Another said: at night too he is awake.'),
    ('כולם דיברו ולא מצאו פתרון.', 'Everyone spoke and did not find a solution.')),
  P(('ואז קם עכבר צעיר וחכם.', 'And then a young, clever mouse got up.'),
    ('הוא אמר: יש לי רעיון פשוט.', 'He said: I have a simple idea.'),
    ('הוא אמר: נשים פעמון על הצוואר שלו.', 'He said: we shall put a bell on his neck.'),
    ('הוא אמר: ואז נשמע אותו מרחוק.', 'He said: and then we shall hear him from far away.'),
    ('כל העכברים צעקו: רעיון מצוין.', 'All the mice shouted: an excellent idea.')),
  P(('הם שמחו ודיברו זמן רב.', 'They rejoiced and talked a long time.'),
    ('ואז קם העכבר הזקן ביותר.', 'And then the oldest mouse got up.'),
    ('הוא אמר: הרעיון באמת יפה.', 'He said: the idea is really fine.'),
    ('הוא שאל: ומי ישים את הפעמון?', 'He asked: and who will put the bell on?'),
    ('אף אחד לא ענה לו כלום.', 'No one answered him anything.'),
    ('קל לומר, וקשה לעשות.', 'It is easy to say, and hard to do.'))]),
 ('The Fox and the Crow', 'השועל והעורב', [
  P(('עורב מצא חתיכת גבינה בחצר.', 'A crow found a piece of cheese in a yard.'),
    ('הוא לקח אותה ועף לעץ גבוה.', 'He took it and flew to a tall tree.'),
    ('הוא ישב על ענף עם הגבינה בפה.', 'He sat on a branch with the cheese in his mouth.'),
    ('הוא רצה לאכול אותה בשקט.', 'He wanted to eat it quietly.')),
  P(('שועל עבר מתחת לעץ ועצר.', 'A fox passed under the tree and stopped.'),
    ('הוא הרים את הראש והסתכל.', 'He raised his head and looked.'),
    ('הוא הריח את הגבינה מיד.', 'He smelled the cheese at once.'),
    ('הוא חשב: אני רוצה אותה.', 'He thought: I want it.')),
  P(('הוא אמר: שלום, ציפור יפה.', 'He said: hello, beautiful bird.'),
    ('הוא אמר: הנוצות שלך שחורות ויפות.', 'He said: your feathers are black and beautiful.'),
    ('הוא אמר: העיניים שלך חכמות.', 'He said: your eyes are clever.'),
    ('הוא אמר: את בטח מלכת הציפורים.', 'He said: you are surely the queen of the birds.'),
    ('העורב הקשיב ולא זז מהמקום.', 'The crow listened and did not move from the place.')),
  P(('השועל אמר: יש לי רק שאלה אחת.', 'The fox said: I have only one question.'),
    ('הוא אמר: האם גם הקול שלך יפה?', 'He said: is your voice beautiful too?'),
    ('העורב רצה להראות לו מיד.', 'The crow wanted to show him at once.'),
    ('הוא פתח את הפה וצעק בקול.', 'He opened his mouth and cried aloud.'),
    ('הגבינה נפלה ישר לשועל.', 'The cheese fell straight to the fox.'),
    ('השועל אמר: תודה על השיר.', 'The fox said: thank you for the song.'))]),
 ("The Donkey in the Lion's Skin", 'החמור בעור האריה', [
  P(('חמור מצא עור של אריה בשדה.', 'A donkey found a lion’s skin in a field.'),
    ('צייד השאיר אותו שם בבוקר.', 'A hunter left it there in the morning.'),
    ('החמור לבש אותו על הגב.', 'The donkey put it on his back.'),
    ('הוא הסתכל על עצמו במים.', 'He looked at himself in the water.'),
    ('הוא אמר: עכשיו אני אריה.', 'He said: now I am a lion.')),
  P(('הוא הלך לשדה של הכפר.', 'He went to the field of the village.'),
    ('הפרות ראו אותו וברחו מהר.', 'The cows saw him and ran away fast.'),
    ('הכבשים רצו אל בין העצים.', 'The sheep ran among the trees.'),
    ('החמור שמח מאוד וצחק.', 'The donkey was very happy and laughed.'),
    ('הוא הלך מבית לבית בכפר.', 'He went from house to house in the village.')),
  P(('הילדים ברחו וסגרו את הדלתות.', 'The children ran and closed the doors.'),
    ('הנשים צעקו מתוך החלונות.', 'The women shouted from the windows.'),
    ('החמור היה מאושר מאוד.', 'The donkey was very happy.'),
    ('הוא רצה לומר להם משהו.', 'He wanted to say something to them.')),
  P(('הוא פתח את הפה וצעק.', 'He opened his mouth and cried out.'),
    ('הקול שלו היה קול של חמור.', 'His voice was a donkey’s voice.'),
    ('כולם עמדו ואז התחילו לצחוק.', 'Everyone stood and then began to laugh.'),
    ('האיכר בא ולקח לו את העור.', 'The farmer came and took the skin from him.'),
    ('הבגד משנה, והקול לא.', 'The clothing changes, and the voice does not.'))]),
 ("The Wolf in Sheep's Clothing", 'הזאב בעור הכבש', [
  P(('זאב רצה לאכול כבש מהעדר.', 'A wolf wanted to eat a sheep from the flock.'),
    ('הרועה שמר עליהם כל היום.', 'The shepherd guarded them all day.'),
    ('הכלבים ישבו סביב העדר.', 'The dogs sat around the flock.'),
    ('הזאב חיכה ולא מצא דרך.', 'The wolf waited and did not find a way.')),
  P(('יום אחד הוא מצא עור של כבש.', 'One day he found a sheep’s skin.'),
    ('הוא לבש אותו וכיסה את הגוף.', 'He put it on and covered his body.'),
    ('בערב הוא נכנס לתוך העדר.', 'In the evening he went in among the flock.'),
    ('הכלבים הסתכלו ולא אמרו כלום.', 'The dogs looked and did not say anything.'),
    ('הרועה ספר את הכבשים ולא ראה.', 'The shepherd counted the sheep and did not see.')),
  P(('הרועה סגר את כולם בגדר.', 'The shepherd closed them all in the fence.'),
    ('הזאב שכב בפנים וחיכה ללילה.', 'The wolf lay inside and waited for night.'),
    ('הוא חשב: עכשיו הכול שלי.', 'He thought: now everything is mine.'),
    ('הוא כמעט נרדם מרוב שמחה.', 'He almost fell asleep from great joy.')),
  P(('בלילה הרועה חזר לגדר.', 'At night the shepherd came back to the fence.'),
    ('הוא רצה בשר לארוחה מחר.', 'He wanted meat for tomorrow’s meal.'),
    ('הוא בחר את הכבש הגדול ביותר.', 'He chose the biggest sheep.'),
    ('הוא לקח אותו ולא הסתכל.', 'He took it and did not look.'),
    ('מי שמשקר נופל בשקר שלו.', 'Whoever lies falls in his own lie.'))]),
 ('The Boy Who Cried Wolf', 'הילד שצעק זאב', [
  P(('ילד שמר על כבשים על הגבעה.', 'A boy guarded sheep on the hill.'),
    ('הוא ישב שם לבד כל היום.', 'He sat there alone all day.'),
    ('הכבשים אכלו עשב בשקט.', 'The sheep ate grass quietly.'),
    ('לילד היה משעמם מאוד.', 'The boy was very bored.')),
  P(('יום אחד הוא חשב על משחק.', 'One day he thought of a game.'),
    ('הוא עמד וצעק: זאב! זאב!', 'He stood and shouted: wolf! Wolf!'),
    ('כל אנשי הכפר עזבו הכול.', 'All the village people left everything.'),
    ('הם רצו במעלה הגבעה עם מקלות.', 'They ran up the hill with sticks.'),
    ('הילד צחק ואמר: לא היה זאב.', 'The boy laughed and said: there was no wolf.')),
  P(('אחרי שבוע הוא עשה את זה שוב.', 'After a week he did it again.'),
    ('האנשים באו שוב, ורצו מהר.', 'The people came again, and ran fast.'),
    ('הילד צחק חזק יותר מאשר בפעם הראשונה.', 'The boy laughed harder than the first time.'),
    ('הם הלכו וכעסו עליו מאוד.', 'They went and were very angry at him.')),
  P(('בערב אחד בא זאב אמיתי.', 'One evening a real wolf came.'),
    ('הוא נכנס בין הכבשים לאט.', 'It went in among the sheep slowly.'),
    ('הילד צעק: זאב! בואו מהר!', 'The boy shouted: wolf! Come quickly!'),
    ('האנשים בכפר שמעו אותו.', 'The people in the village heard him.'),
    ('הם אמרו: זה המשחק שלו שוב.', 'They said: it is his game again.'),
    ('אף אחד לא עלה לגבעה.', 'No one went up to the hill.'),
    ('מי ששיקר פעמיים לא מקבל אמון.', 'Whoever has lied twice does not receive trust.'))]),
 ('The Milkmaid and Her Pail', 'הנערה ודלי החלב', [
  P(('נערה הלכה מהחווה אל השוק.', 'A girl walked from the farm to the market.'),
    ('היא נשאה דלי חלב על הראש.', 'She carried a pail of milk on her head.'),
    ('הבוקר היה יפה והדרך ארוכה.', 'The morning was beautiful and the road long.'),
    ('היא הלכה לאט וחשבה לעצמה.', 'She walked slowly and thought to herself.')),
  P(('היא אמרה: אני אמכור את החלב.', 'She said: I shall sell the milk.'),
    ('היא אמרה: ובכסף אקנה ביצים.', 'She said: and with the money I shall buy eggs.'),
    ('היא אמרה: מהביצים יהיו אפרוחים.', 'She said: from the eggs there will be chicks.'),
    ('היא אמרה: והאפרוחים יגדלו מהר.', 'She said: and the chicks will grow fast.')),
  P(('היא אמרה: אני אמכור אותם בשוק.', 'She said: I shall sell them at the market.'),
    ('היא אמרה: ואני אקנה לי שמלה חדשה.', 'She said: and I shall buy myself a new dress.'),
    ('היא אמרה: ואלך איתה למסיבה.', 'She said: and I shall go with it to the party.'),
    ('היא אמרה: וכל הבחורים יבואו אליי.', 'She said: and all the young men will come to me.')),
  P(('היא אמרה: ואני לא אסכים לרקוד.', 'She said: and I shall not agree to dance.'),
    ('היא אמרה: אני רק אזיז את הראש.', 'She said: I shall only move my head.'),
    ('היא הזיזה את הראש בדיוק ככה.', 'She moved her head exactly like that.'),
    ('הדלי נפל, והחלב נשפך על הדרך.', 'The pail fell, and the milk spilled on the road.'),
    ('היא חזרה הביתה בלי כלום.', 'She went home with nothing.'),
    ('אל תספור מה שעוד לא קרה.', 'Do not count what has not yet happened.'))]),
 ('The Ant and the Grasshopper', 'הנמלה והחגב', [
  P(('בקיץ החם עבדו הנמלים בשדה.', 'In the hot summer the ants worked in the field.'),
    ('הן לקחו חיטה והכניסו אותם לחור.', 'They took wheat and brought them into the hole.'),
    ('הן עבדו מהבוקר עד הערב.', 'They worked from morning until evening.'),
    ('חגב ישב על עשב וניגן.', 'A grasshopper sat on grass and played music.')),
  P(('הוא קרא לנמלה: בואי אליי.', 'He called to the ant: come to me.'),
    ('הוא אמר: תשבי, ואת תשמעי, ואת תנוחי.', 'He said: sit, and listen, and rest.'),
    ('הנמלה אמרה: אין לי זמן עכשיו.', 'The ant said: I have no time now.'),
    ('היא אמרה: החורף יבוא בקרוב.', 'She said: the winter will come soon.'),
    ('החגב צחק ואמר: יש עוד הרבה זמן.', 'The grasshopper laughed and said: there is still a lot of time.')),
  P(('הקיץ נגמר, ואז בא הסתיו.', 'The summer ended, and then came the autumn.'),
    ('העלים נפלו, והימים נעשו קרים.', 'The leaves fell, and the days became cold.'),
    ('אחר כך התחיל החורף עם הגשם.', 'Afterwards the winter began with the rain.'),
    ('בשדה לא נשאר אוכל בכלל.', 'In the field no food remained at all.')),
  P(('החגב הלך ברוח וחיפש משהו.', 'The grasshopper walked in the wind and looked for something.'),
    ('הוא הגיע אל החור של הנמלים.', 'He reached the hole of the ants.'),
    ('הוא אמר: אני רעב מאוד.', 'He said: I am very hungry.'),
    ('הנמלה שאלה: ומה עשית בקיץ?', 'The ant asked: and what did you do in the summer?'),
    ('הוא אמר: ניגנתי ושרתי כל היום.', 'He said: I played and sang all day.'),
    ('היא אמרה: אז עכשיו לך לרקוד.', 'She said: then now go and dance.'))]),
 ('The Wind and the Sun', 'הרוח והשמש', [
  P(('הרוח והשמש רבו יום אחד.', 'The wind and the sun quarrelled one day.'),
    ('הרוח אמרה: אני חזקה יותר.', 'The wind said: I am stronger.'),
    ('השמש אמרה: אני לא בטוחה.', 'The sun said: I am not sure.'),
    ('הרוח אמרה: אז נבדוק את זה.', 'The wind said: then let us test it.')),
  P(('הן ראו איש הולך בדרך.', 'They saw a man walking on the road.'),
    ('היה לו מעיל כבד על הגוף.', 'He had a heavy coat on his body.'),
    ('הרוח אמרה: מי שמוריד לו את המעיל.', 'The wind said: whoever takes off his coat.'),
    ('השמש אמרה: טוב, תתחילי את.', 'The sun said: good, you begin.')),
  P(('הרוח נשמה חזק על האיש.', 'The wind blew hard on the man.'),
    ('האיש החזיק את המעיל בשתי ידיים.', 'The man held the coat in two hands.'),
    ('הרוח נשמה עוד יותר חזק.', 'The wind blew even harder.'),
    ('האיש סגר את המעיל עד הצוואר.', 'The man closed the coat up to his neck.'),
    ('הרוח התעייפה ועצרה בסוף.', 'The wind grew tired and stopped in the end.')),
  P(('ואז השמש יצאה מאחורי הענן.', 'And then the sun came out from behind the cloud.'),
    ('היא האירה על הדרך בשקט.', 'She shone on the road quietly.'),
    ('האיש הרגיש חום ופתח את המעיל.', 'The man felt warmth and opened the coat.'),
    ('השמש המשיכה עוד קצת.', 'The sun continued a little more.'),
    ('האיש הוריד את המעיל ואז ישב.', 'The man took off the coat and sat down.'),
    ('בטוב אפשר מה שלא אפשר בכוח.', 'With kindness one can do what one cannot by force.'))]),
 ('The Miser and His Gold', 'הקמצן והזהב', [
  P(('לאיש אחד היה הרבה כסף.', 'One man had a lot of money.'),
    ('הוא לא קנה בו שום דבר.', 'He did not buy anything with it.'),
    ('הוא לבש בגדים ישנים ולא שלמים.', 'He wore old, clothes that were not whole.'),
    ('הוא אכל לחם יבש בכל ערב.', 'He ate dry bread every evening.')),
  P(('הוא מכר הכול וקנה זהב.', 'He sold everything and bought gold.'),
    ('הוא עשה מהזהב כדור אחד גדול.', 'He made from the gold one big ball.'),
    ('בלילה הוא יצא לגן שלו.', 'At night he went out to his garden.'),
    ('הוא חפר חור עמוק ליד הגדר.', 'He dug a deep hole beside the fence.'),
    ('הוא שם את הזהב וכיסה באדמה.', 'He put the gold in and covered it with earth.')),
  P(('כל בוקר הוא בא לאותו מקום.', 'Every morning he came to the same place.'),
    ('הוא חפר, והסתכל, וכיסה שוב.', 'He dug, and looked, and covered again.'),
    ('שכן ראה אותו כמה פעמים.', 'A neighbour saw him several times.'),
    ('בלילה אחד השכן בא לגן.', 'On one night the neighbour came to the garden.'),
    ('הוא חפר, ולקח את הזהב, והלך.', 'He dug, and took the gold, and went.')),
  P(('בבוקר האיש בא ומצא חור ריק.', 'In the morning the man came and found an empty hole.'),
    ('הוא ישב על האדמה ובכה חזק.', 'He sat on the ground and wept loudly.'),
    ('חבר שלו עבר ושאל מה קרה.', 'A friend of his passed and asked what happened.'),
    ('האיש סיפר לו את כל הסיפור.', 'The man told him the whole story.'),
    ('החבר אמר: תשים אבן בחור.', 'The friend said: put a stone in the hole.'),
    ('הוא אמר: היא שווה בדיוק אותו דבר.', 'He said: it is worth exactly the same.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('aesop', {'en': "Aesop's Fables", 'he': 'משלי איזופוס'}, 'beginner',
                          CHAPTERS, unit='Fable', unit_he='משל', shelf=2, meta=META))
