#!/usr/bin/env python3
"""מסביב לעולם בשמונים יום — Jules Verne, retold in modern Hebrew, graded to intermediate.

The Hebrew twin of pipeline/book_atw80.py, chapter for chapter. Verne died in 1905 and the
novel is public domain everywhere; this is a retelling from the plot, not a translation of any
edition.

WHY THIS OPENS THE INTERMEDIATE SHELF. It is the first book here with a PLOT that has to be
carried across thirty-eight chapters, and that is the whole difficulty of the tier: the reader
has to hold Fogg's bet in their head from chapter three to chapter thirty-eight, in Hebrew.
Everything else is chosen to make that possible — the same four people in every chapter, the
past tense throughout, and a journey that supplies its own vocabulary as it goes.

Sentences run longer than the beginner shelf's and are meant to: two clauses is where the
tier lives. Deliberately unpointed; the vowels are looked up at ingest.

Run:  python3 pipeline/he_book_atw80.py --lang he            # check
      python3 pipeline/he_book_atw80.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'Around the World in Eighty Days', 'author': 'Jules Verne', 'year': '1872',
        'status': 'public domain — author died 1905'}

CHAPTERS = [
 ('Passepartout Finds a New Master', 'פספרטו מוצא אדון חדש', [
  P(('בבית מספר שבע ברחוב שקט בלונדון גר איש בשם פיליאס פוג.', 'In house number seven on a quiet street in London lived a man named Phileas Fogg.'),
    ('איש לא ידע מאיפה הוא בא, ואיש לא ידע מאיפה הכסף שלו.', 'No one knew where he came from, and no one knew where his money came from.'),
    ('הוא לא עבד, ולא היה נשוי, ולא היו לו ילדים או קרובים.', 'He did not work, and was not married, and had no children or relatives.'),
    ('הוא היה יוצא מהבית בדיוק באותה שעה בכל יום בשנה.', 'He would leave the house at exactly the same hour every day of the year.')),
  P(('הוא היה הולך למועדון, קורא עיתונים, אוכל, ומשחק קלפים בערב.', 'He would go to the club, read newspapers, eat, and play cards in the evening.'),
    ('הוא חזר הביתה בדיוק בחצות, ולא דקה אחת לפני או אחרי.', 'He came home exactly at midnight, and not one minute before or after.'),
    ('הוא כמעט לא דיבר, וכשדיבר, הוא אמר בדיוק מה שצריך.', 'He hardly spoke, and when he spoke, he said exactly what was needed.'),
    ('בבית שלו הכול היה לפי השעון, וגם המים לגילוח.', 'In his house everything was by the clock, and also the water for shaving.')),
  P(('בבוקר ההוא הוא פיטר את המשרת שלו בגלל שתי מעלות.', 'That morning he dismissed his servant because of two degrees.'),
    ('המים לגילוח היו בשמונים וארבע מעלות במקום שמונים ושש.', 'The shaving water was eighty-four degrees instead of eighty-six.'),
    ('בשעה אחת עשרה וחצי נכנס לחדר בחור צרפתי צעיר.', 'At half past eleven a young Frenchman came into the room.'),
    ('הוא היה רחב כתפיים, עם פנים נעימות ועיניים כחולות.', 'He was broad-shouldered, with a pleasant face and blue eyes.')),
  P(('פוג שאל אותו: השם שלך? והוא ענה: פספרטו, אדוני.', 'Fogg asked him: your name? And he answered: Passepartout, sir.'),
    ('פוג שאל: מה עשית עד היום? והוא ענה שהוא עשה הרבה דברים.', 'Fogg asked: what have you done until today? And he answered that he has done many things.'),
    ('הוא היה זמר ברחוב, ומורה להתעמלות, ואיש כיבוי אש בפריז.', 'He was a street singer, and a gymnastics teacher, and a fireman in Paris.'),
    ('הוא אמר: עזבתי את צרפת לפני חמש שנים, ואני רוצה שקט.', 'He said: I left France five years ago, and I want quiet.')),
  P(('פוג הסתכל בשעון ואמר: השעה אחת עשרה ועשרים ותשע דקות.', 'Fogg looked at the clock and said: the hour is eleven twenty-nine.'),
    ('הוא אמר: מעכשיו, בשעה אחת עשרה ושלושים, אתה עובד אצלי.', 'He said: from now, at eleven thirty, you work for me.'),
    ('הוא לקח את הכובע שלו ואז יצא מהבית בלי עוד מילה.', 'He took his hat and went out of the house without another word.'),
    ('פספרטו נשאר לבד בחדר, ולא ידע אם הוא שמח או מפחד.', 'Passepartout remained alone in the room, and did not know whether he is happy or afraid.'))]),
 ('A Servant to His Liking', 'משרת לפי הטעם שלו', [
  P(('פספרטו עבר בבית לאט וראה שהכול נקי ומסודר.', 'Passepartout went through the house slowly and saw that everything is clean and tidy.'),
    ('החדר שלו היה למעלה, ובו מיטה, ושולחן, וארון קטן.', 'His room was upstairs, and in it a bed, and a table, and a small cupboard.'),
    ('על הקיר היה תלוי דף עם כל השעות של היום.', 'On the wall hung a sheet with all the hours of the day.'),
    ('היה כתוב שם מתי להביא תה, ומתי מים, ומתי בגדים.', 'It was written there when to bring tea, and when water, and when clothes.')),
  P(('פספרטו קרא את הדף פעמיים וחייך לעצמו בשקט.', 'Passepartout read the sheet twice and smiled to himself quietly.'),
    ('הוא אמר: זה בדיוק מה שחיפשתי כל השנים האלה.', 'He said: this is exactly what I have been looking for all these years.'),
    ('הוא אמר: כאן אין הפתעות, ואין נסיעות, ואין ריצות.', 'He said: here there are no surprises, and no journeys, and no running about.'),
    ('הוא סידר את הבגדים שלו בארון והתיישב על המיטה.', 'He arranged his clothes in the cupboard and sat down on the bed.')),
  P(('הוא חשב על החיים הקודמים שלו, שהיו מלאים תנועה.', 'He thought about his previous life, which was full of movement.'),
    ('הוא רץ ממקום למקום, ולמד עשר עבודות, ולא נשאר באף אחת.', 'He ran from place to place, and learned ten trades, and stayed in none of them.'),
    ('עכשיו הוא רצה רק לישון בשעה קבועה ולאכול בשעה קבועה.', 'Now he wanted only to sleep at a fixed hour and to eat at a fixed hour.'),
    ('הוא הסתכל בשעון על הקיר ואמר: אנחנו נסתדר יפה.', 'He looked at the clock on the wall and said: we shall get along nicely.')),
  P(('למטה, בבית הריק, לא נשמע שום קול עד הערב.', 'Downstairs, in the empty house, no sound was heard until the evening.'),
    ('פספרטו ירד למטבח ובדק מה יש בארונות ובמגירות.', 'Passepartout went down to the kitchen and checked what there is in the cupboards and the drawers.'),
    ('הכול היה במקום, וכל דבר עמד בדיוק איפה שצריך.', 'Everything was in place, and every thing stood exactly where it should.'),
    ('הוא אמר: הבית הזה נראה כמו שעון גדול מבפנים.', 'He said: this house looks like a big clock from the inside.'))]),
 ('The Bet at the Club', 'ההימור במועדון', [
  P(('באותו ערב ישבו במועדון חמישה אנשים סביב שולחן קלפים.', 'That evening five men sat in the club around a card table.'),
    ('היו שם שני אנשי בנק, ואיש עסקים, ומהנדס, ופיליאס פוג.', 'There were there two bank men, and a businessman, and an engineer, and Phileas Fogg.'),
    ('הם דיברו על גנב שלקח חמישים וחמישה אלף מהבנק.', 'They spoke about a thief who took fifty-five thousand from the bank.'),
    ('העיתונים כתבו שהמשטרה מחפשת אותו בכל נמל באירופה.', 'The newspapers wrote that the police are looking for him in every port in Europe.')),
  P(('אחד אמר: העולם גדול, והוא יימצא מקום להתחבא בו.', 'One said: the world is big, and he will find a place to hide in.'),
    ('פוג אמר בשקט: העולם היה גדול פעם, והיום הוא קטן.', 'Fogg said quietly: the world was big once, and today it is small.'),
    ('הוא אמר: אפשר לעבור אותו כולו בשמונים יום בדיוק.', 'He said: it is possible to go all the way around it in exactly eighty days.'),
    ('הוא אמר: העיתון היום מדפיס את החשבון, ואפשר לקרוא אותו.', 'He said: the newspaper today prints the calculation, and one can read it.')),
  P(('הם צחקו ואמרו: על הנייר כן, ובעולם האמיתי לא.', 'They laughed and said: on paper yes, and in the real world no.'),
    ('הם אמרו: יש סופות, ויש רכבות שמאחרות, ויש מחלות.', 'They said: there are storms, and there are trains that are late, and there are illnesses.'),
    ('פוג אמר: הכול נכנס בחשבון, וגם זה חלק מהתוכנית.', 'Fogg said: everything enters the calculation, and that too is part of the plan.'),
    ('אחד מהם אמר: אז תעשה את זה בעצמך, ולא רק בדיבור.', 'One of them said: then do it yourself, and not only in talk.')),
  P(('פוג אמר: אני מוכן, ואני שם עשרים אלף על זה.', 'Fogg said: I am ready, and I put twenty thousand on it.'),
    ('הוא אמר: זה חצי מכל מה שיש לי בעולם.', 'He said: that is half of everything that I have in the world.'),
    ('הם כתבו הכול על נייר וחתמו עליו באותו רגע.', 'They wrote everything on paper and signed it at that moment.'),
    ('פוג אמר: הרכבת יוצאת הערב בשעה שמונה וארבעים וחמש.', 'Fogg said: the train leaves this evening at eight forty-five.'),
    ('הוא אמר: אני חוזר לכאן בעוד שמונים יום, באותה שעה.', 'He said: I return here in eighty days, at the same hour.'))]),
 ('The Departure', 'היציאה לדרך', [
  P(('פוג חזר הביתה בשעה שבע ועשרה, וזה לא היה רגיל.', 'Fogg came home at ten past seven, and that was not usual.'),
    ('פספרטו שמע את הצעד שלו על המדרגות ולא הבין.', 'Passepartout heard his step on the stairs and did not understand.'),
    ('פוג קרא לו ואמר: אנחנו נוסעים בעוד עשר דקות.', 'Fogg called him and said: we are travelling in ten minutes.'),
    ('הוא אמר: אנחנו נוסעים מסביב לעולם, ואין זמן לדבר.', 'He said: we are travelling around the world, and there is no time to talk.')),
  P(('פספרטו עמד עם הפה פתוח ולא הצליח לומר מילה.', 'Passepartout stood with his mouth open and could not say a word.'),
    ('הוא שאל: מסביב לעולם? ופוג ענה: בשמונים יום.', 'He asked: around the world? And Fogg answered: in eighty days.'),
    ('הוא אמר: קח תיק אחד קטן, ובו שתי חולצות לכל אחד.', 'He said: take one small bag, and in it two shirts for each of us.'),
    ('הוא אמר: את השאר נקנה בדרך, וכל מקום מוכר בגדים.', 'He said: the rest we shall buy on the way, and every place sells clothes.')),
  P(('פספרטו עלה למעלה, ורגליו כמעט לא נשאו אותו.', 'Passepartout went upstairs, and his legs hardly carried him.'),
    ('הוא חשב על החדר השקט שלו ועל הדף שעל הקיר.', 'He thought about his quiet room and about the sheet on the wall.'),
    ('הוא ארז את התיק מהר, וירד, ולא אמר כלום.', 'He packed the bag fast, and came down, and said nothing.'),
    ('פוג לקח שק עם עשרים אלף בשטרות ושם אותו בתיק.', 'Fogg took a bag with twenty thousand in notes and put it in the bag.')),
  P(('הם יצאו מהבית והלכו ברגל אל תחנת הרכבת.', 'They went out of the house and walked on foot to the railway station.'),
    ('בדרך פוג נתן כסף לאישה ענייה שעמדה עם ילדה.', 'On the way Fogg gave money to a poor woman who stood with a child.'),
    ('בתחנה חיכו כל החברים מהמועדון כדי לראות אותו יוצא.', 'At the station all the friends from the club waited in order to see him leave.'),
    ('הרכבת יצאה בשמונה ארבעים וחמש, בדיוק כמו שהוא אמר.', 'The train left at eight forty-five, exactly as he said.'),
    ('ובקרון פספרטו קפץ פתאום וצעק: שכחתי לכבות את הגז!', 'And in the carriage Passepartout suddenly jumped and shouted: I forgot to put out the gas!'))]),
 ('A Stir in London', 'סערה בלונדון', [
  P(('למחרת בבוקר כל העיתונים בלונדון כתבו על ההימור.', 'The next morning all the newspapers in London wrote about the bet.'),
    ('אנשים דיברו על זה בבתי הקפה, וברחוב, ובעבודה.', 'People spoke about it in the coffee houses, and in the street, and at work.'),
    ('רוב האנשים אמרו שזה בלתי אפשרי ושהאיש הזה איבד את דעתו.', 'Most of the people said that it is impossible and that this man has lost his mind.'),
    ('אחרים אמרו: הוא חישב הכול, ואולי הוא באמת יצליח.', 'Others said: he calculated everything, and perhaps he will really succeed.')),
  P(('בבורסה התחילו למכור ולקנות ניירות על שם פוג.', 'On the exchange they began to sell and buy papers in Fogg’s name.'),
    ('בהתחלה המחיר היה גבוה, ואחרי יומיים הוא ירד מאוד.', 'At first the price was high, and after two days it fell a great deal.'),
    ('אנשים זקנים במועדון אמרו שהם מכירים את העולם.', 'Old men at the club said that they know the world.'),
    ('הם אמרו: מספיק שרכבת אחת תאחר, והכול נגמר.', 'They said: it is enough that one train be late, and everything is finished.')),
  P(('ואז, ביום השביעי, יצא בעיתון דבר חדש לגמרי.', 'And then, on the seventh day, something entirely new came out in the newspaper.'),
    ('המשטרה אמרה שהגנב מהבנק הוא איש גבוה ושקט.', 'The police said that the thief from the bank is a tall, quiet man.'),
    ('היה כתוב שהוא יצא מלונדון באותו ערב בדיוק.', 'It was written that he left London on that very evening.'),
    ('אנשים התחילו לשאול אם פוג הוא בכלל האיש הזה.', 'People began to ask whether Fogg is not that very man.')),
  P(('הרעיון תפס מהר, כי הוא הסביר כל דבר שהיה מוזר.', 'The idea caught on fast, because it explained everything that was strange.'),
    ('למה איש יוצא לדרך בערב אחד בלי לקחת מזוודות?', 'Why does a man set out one evening without taking luggage?'),
    ('ולמה הוא לוקח איתו שק גדול מלא בשטרות?', 'And why does he take with him a big bag full of notes?'),
    ('בעיתון היום השמיני היה כתוב שהמשטרה שלחה הודעות לכל נמל.', 'In the newspaper of the eighth day it was written that the police sent messages to every port.'))]),
 ('Fix Waits at Suez', 'פיקס מחכה בסואץ', [
  P(('בנמל סואץ עמד בבוקר איש קטן וצנום ליד המים.', 'At the port of Suez a small, lean man stood in the morning beside the water.'),
    ('שמו היה פיקס, והוא היה בלש מלונדון, ואיש לא ידע.', 'His name was Fix, and he was a detective from London, and no one knew.'),
    ('הוא חיכה לספינה שבאה מאירופה בדרך להודו.', 'He waited for the ship that comes from Europe on the way to India.'),
    ('בכיס שלו הייתה הודעה עם התיאור של הגנב מהבנק.', 'In his pocket was a message with the description of the thief from the bank.')),
  P(('פיקס עמד שם כבר שלושה ימים ובדק כל פנים.', 'Fix had been standing there three days already and checked every face.'),
    ('הוא אמר לעצמו: הוא יעבור כאן, כי אין דרך אחרת.', 'He said to himself: he will pass here, because there is no other way.'),
    ('הוא חשב על הפרס: אלפיים לירות למי שתופס אותו.', 'He thought about the reward: two thousand pounds for whoever catches him.'),
    ('הוא חשב גם על העבודה, ועל מה שיגידו עליו בלונדון.', 'He thought also about the work, and about what they will say about him in London.')),
  P(('בעשר בבוקר הספינה נכנסה לנמל והשליכה חבלים.', 'At ten in the morning the ship entered the port and threw ropes.'),
    ('נוסעים ירדו לרציף, ופיקס עמד והסתכל בכל אחד מהם.', 'Passengers came down to the quay, and Fix stood and looked at each one of them.'),
    ('ואז ירד בחור צרפתי ושאל איפה אפשר לחתום על דרכון.', 'And then a young Frenchman came down and asked where one can sign a passport.'),
    ('פיקס ניגש אליו מיד והתחיל לדבר איתו בנימוס.', 'Fix went up to him at once and began to speak with him politely.')),
  P(('הוא שאל: אתה נוסע לבד, או שיש איתך עוד מישהו?', 'He asked: are you travelling alone, or is there someone else with you?'),
    ('פספרטו אמר: אני עם האדון שלי, והוא נשאר על הספינה.', 'Passepartout said: I am with my master, and he stays on the ship.'),
    ('פיקס שאל: ואיך הוא נראה? והוא ענה: גבוה ושקט מאוד.', 'Fix asked: and what does he look like? And he answered: tall and very quiet.'),
    ('פיקס הרגיש את הלב שלו פועם, אבל הפנים שלו לא זזו.', 'Fix felt his heart beating, but his face did not move.'))]),
 ('Passports and Police', 'דרכונים ומשטרה', [
  P(('פיקס הלך אל המשרד של הקונסול ודיבר איתו בשקט.', 'Fix went to the consul’s office and spoke with him quietly.'),
    ('הוא אמר: האיש הזה מתאים לתיאור בכל פרט ופרט.', 'He said: this man fits the description in every single detail.'),
    ('הקונסול אמר: יש אלף אנשים בעולם שמתאימים לתיאור.', 'The consul said: there are a thousand men in the world who fit the description.'),
    ('פיקס אמר: אבל הוא יוצא בדיוק ביום הנכון מלונדון.', 'Fix said: but he leaves London on exactly the right day.')),
  P(('הקונסול שאל: ואם הוא לא מגיע לחתום על הדרכון?', 'The consul asked: and if he does not come to sign the passport?'),
    ('פיקס אמר: הוא יבוא, כי גנב אוהב שהניירות שלו בסדר.', 'Fix said: he will come, because a thief likes his papers to be in order.'),
    ('אחרי חצי שעה נכנס למשרד איש גבוה ושקט מאוד.', 'After half an hour a tall and very quiet man came into the office.'),
    ('הוא הניח דרכון על השולחן ולא אמר כמעט כלום.', 'He placed a passport on the table and said almost nothing.')),
  P(('הקונסול הסתכל בנייר ואמר: אתה פיליאס פוג מלונדון.', 'The consul looked at the paper and said: you are Phileas Fogg from London.'),
    ('פוג אמר: כן, ואני צריך חתימה כדי להמשיך להודו.', 'Fogg said: yes, and I need a signature in order to continue to India.'),
    ('הקונסול שאל: אתה יודע שאין חובה לחתום כאן?', 'The consul asked: do you know that there is no obligation to sign here?'),
    ('פוג אמר: אני יודע, ובכל זאת אני מבקש חתימה ותאריך.', 'Fogg said: I know, and nevertheless I ask for a signature and a date.')),
  P(('הקונסול חתם, ופוג לקח את הדרכון ואז יצא בלי מילה.', 'The consul signed, and Fogg took the passport and went out without a word.'),
    ('פיקס אמר: ראית? הוא רוצה הוכחה על כל יום שעובר.', 'Fix said: did you see? He wants proof of every day that passes.'),
    ('הקונסול אמר: או שהוא גנב, או שהוא איש מסודר מאוד.', 'The consul said: either he is a thief, or he is a very orderly man.'),
    ('פיקס שלח מברק ללונדון וביקש נייר מעצר להודו.', 'Fix sent a telegram to London and asked for an arrest paper for India.'),
    ('הוא עלה על אותה ספינה, וישן שם באותו מסדרון.', 'He got on that same ship, and slept there in the same corridor.'))]),
 ('Passepartout Talks Too Much', 'פספרטו מדבר יותר מדי', [
  P(('על הספינה פיקס חיפש הזדמנות לדבר עם פספרטו שוב.', 'On the ship Fix looked for an opportunity to speak with Passepartout again.'),
    ('הוא מצא אותו על הסיפון בערב, מסתכל על המים.', 'He found him on the deck in the evening, looking at the water.'),
    ('הוא אמר: איזה מזל, גם אני נוסע לבומביי בדיוק.', 'He said: what luck, I too am travelling to Bombay exactly.'),
    ('פספרטו שמח מאוד, כי לא היה לו עם מי לדבר.', 'Passepartout was very happy, because he had no one to talk with.')),
  P(('הם ישבו יחד וסיפרו סיפורים על מקומות שהם ראו.', 'They sat together and told stories about places that they had seen.'),
    ('פיקס שאל שאלות קטנות, ופספרטו ענה על כל אחת.', 'Fix asked small questions, and Passepartout answered every one.'),
    ('הוא סיפר על הבית בלונדון, ועל השעון, ועל המים לגילוח.', 'He told about the house in London, and about the clock, and about the shaving water.'),
    ('הוא סיפר גם שהם יצאו לדרך בערב אחד בלי שום הודעה.', 'He told also that they set out one evening without any notice.')),
  P(('פיקס שאל: והאדון שלך לוקח איתו הרבה כסף מזומן?', 'Fix asked: and your master takes a lot of cash with him?'),
    ('פספרטו אמר: יש לו תיק, ובתוכו שטרות חדשים לגמרי.', 'Passepartout said: he has a bag, and inside it entirely new notes.'),
    ('הוא אמר: הוא משלם בכל מקום, ולא סופר את הכסף.', 'He said: he pays everywhere, and does not count the money.'),
    ('פיקס הקשיב, ולא אמר כלום, ורק הסתכל על הים.', 'Fix listened, and said nothing, and only looked at the sea.')),
  P(('אחר כך הוא ירד לתא שלו וכתב הכול על נייר.', 'Afterwards he went down to his cabin and wrote everything on paper.'),
    ('הוא כתב: הכסף חדש, כלומר הוא בא ישר מהבנק.', 'He wrote: the money is new, that is, it comes straight from the bank.'),
    ('הוא כתב: המשרת לא יודע כלום, וזה מה שמסבך אותו.', 'He wrote: the servant knows nothing, and that is what entangles him.'),
    ('הוא כתב: אני צריך רק את הנייר מלונדון, ואז זה נגמר.', 'He wrote: I need only the paper from London, and then it is finished.'))]),
 ('The Red Sea and Beyond', 'ים סוף והלאה', [
  P(('הספינה ירדה בים סוף בין שני חופים של אבן וחול.', 'The ship went down the Red Sea between two shores of stone and sand.'),
    ('היה חם מאוד, והאוויר עמד בלי לזוז מעל המים.', 'It was very hot, and the air stood without moving above the water.'),
    ('פוג ישב בחדר שלו וכתב מספרים בפנקס קטן.', 'Fogg sat in his room and wrote numbers in a small notebook.'),
    ('הוא כתב את התאריך, ואת השעה, ואת שם המקום.', 'He wrote the date, and the hour, and the name of the place.')),
  P(('בכל פעם הוא כתב אם הוא מקדים או מאחר, ובכמה.', 'Each time he wrote whether he is early or late, and by how much.'),
    ('עד עכשיו הכול הלך בדיוק לפי החשבון מלונדון.', 'Until now everything went exactly according to the calculation from London.'),
    ('הוא לא יצא לסיפון לראות את הים ואת החופים.', 'He did not go out on deck to see the sea and the shores.'),
    ('פספרטו אמר לו פעם: אדוני, יש שם נוף יפה מאוד.', 'Passepartout said to him once: sir, there is a very beautiful view there.'),
    ('פוג אמר: אני לא נוסע כדי לראות, אני נוסע כדי להגיע.', 'Fogg said: I am not travelling in order to see, I am travelling in order to arrive.')),
  P(('ביום השני עלתה רוח, והספינה התחילה לזוז חזק.', 'On the second day a wind rose, and the ship began to move hard.'),
    ('המפקד אמר שהם יאחרו בשעות, ואולי אפילו ביום.', 'The master said that they will be hours late, and perhaps even a day.'),
    ('פספרטו נבהל מאוד ורץ לספר את זה לאדון שלו.', 'Passepartout was very alarmed and ran to tell it to his master.'),
    ('פוג הרים את הראש מהפנקס ואמר: זה כתוב אצלי.', 'Fogg raised his head from the notebook and said: it is written down with me.')),
  P(('הוא אמר: יש לי שני ימים ריקים לדברים כאלה.', 'He said: I have two empty days for such things.'),
    ('הוא אמר: אם נאחר יום, ניקח אותו בחזרה בהודו.', 'He said: if we are a day late, we shall take it back in India.'),
    ('הרוח ירדה בלילה, והספינה הגיעה לבומביי בזמן.', 'The wind dropped at night, and the ship reached Bombay on time.'),
    ('פיקס ירד ראשון וחיפש את הנייר שלו במשרד הדואר.', 'Fix went down first and looked for his paper at the post office.'),
    ('הנייר לא הגיע, והוא עמד שם עם ידיים ריקות.', 'The paper did not arrive, and he stood there with empty hands.'))]),
 ('Trouble at the Pagoda', 'צרות במקדש', [
  P(('בבומביי הייתה לפוג שעה וחצי עד הרכבת לכלכותה.', 'In Bombay Fogg had an hour and a half until the train to Calcutta.'),
    ('הוא הלך לתחנה, ישב על ספסל, והוציא את הפנקס.', 'He went to the station, sat on a bench, and took out the notebook.'),
    ('פספרטו קיבל רשות ללכת לשוק ולקנות כמה חולצות.', 'Passepartout received permission to go to the market and buy some shirts.'),
    ('הוא הלך ברחובות והסתכל על הצבעים ועל האנשים.', 'He walked in the streets and looked at the colours and at the people.')),
  P(('הוא ראה בניין גדול ויפה עם דלת פתוחה למחצה.', 'He saw a big, beautiful building with a half-open door.'),
    ('הוא נכנס פנימה כדי לראות את הציורים על הקירות.', 'He went inside in order to see the paintings on the walls.'),
    ('הוא לא ידע שאסור להיכנס לשם עם נעליים ברגליים.', 'He did not know that it is forbidden to enter there with shoes on one’s feet.'),
    ('שלושה אנשים באו אליו מהצד וצעקו עליו בכעס.', 'Three men came to him from the side and shouted at him in anger.')),
  P(('הם הפילו אותו על הרצפה והתחילו לקחת את הבגדים.', 'They knocked him to the floor and began to take his clothes.'),
    ('פספרטו היה חזק, והוא קפץ, ודחף שניים מהם הצידה.', 'Passepartout was strong, and he jumped, and pushed two of them aside.'),
    ('הוא רץ החוצה בלי הנעליים ובלי הכובע שלו.', 'He ran outside without his shoes and without his hat.'),
    ('הוא הגיע לתחנה שתי דקות לפני שהרכבת יצאה.', 'He reached the station two minutes before the train left.')),
  P(('פוג הסתכל עליו ושאל: מה קרה לנעליים שלך?', 'Fogg looked at him and asked: what happened to your shoes?'),
    ('פספרטו סיפר הכול, ופוג שמע ולא אמר מילה אחת.', 'Passepartout told everything, and Fogg listened and did not say one word.'),
    ('הוא רק אמר: אני מקווה שזה לא יקרה שוב.', 'He only said: I hope that this will not happen again.'),
    ('מאחוריהם, על הרציף, עמד פיקס וחייך לעצמו.', 'Behind them, on the platform, Fix stood and smiled to himself.'),
    ('הוא אמר: עכשיו יש לי משהו, ואני אשתמש בזה בכלכותה.', 'He said: now I have something, and I shall use it in Calcutta.'))]),
 ('The Elephant', 'הפיל', [
  P(('הרכבת נסעה יום שלם בין שדות, וכפרים, ויערות.', 'The train travelled a whole day among fields, and villages, and forests.'),
    ('בלילה היא עצרה פתאום באמצע מקום ריק לגמרי.', 'At night it stopped suddenly in the middle of an entirely empty place.'),
    ('הכרטיסן עבר בקרונות ואמר: כאן נגמרת המסילה.', 'The conductor passed through the carriages and said: here the track ends.'),
    ('הנוסעים צעקו: אבל הכרטיס שלנו הוא עד כלכותה!', 'The passengers shouted: but our ticket is to Calcutta!')),
  P(('הכרטיסן אמר: העיתונים כתבו שהקו גמור, וזאת טעות.', 'The conductor said: the newspapers wrote that the line is finished, and that is a mistake.'),
    ('הוא אמר: חסרים עוד שמונים קילומטר של מסילה בהרים.', 'He said: another eighty kilometres of track in the mountains are missing.'),
    ('כל הנוסעים ירדו וחיפשו עגלה ובהמה בכפר הקרוב.', 'All the passengers got down and looked for a cart and an animal in the near village.'),
    ('פוג הלך בשקט מבית לבית ושאל מה יש למכור.', 'Fogg walked quietly from house to house and asked what there is to sell.')),
  P(('בחצר אחת עמד פיל גדול, והבעלים שלו לא רצה למכור.', 'In one yard stood a big elephant, and its owner did not want to sell.'),
    ('פוג הציע אלף, ואז אלפיים, ואז ארבעת אלפים.', 'Fogg offered a thousand, and then two thousand, and then four thousand.'),
    ('בסוף הוא שילם הרבה מאוד, והפיל נעשה שלו.', 'In the end he paid a very great deal, and the elephant became his.'),
    ('פספרטו אמר: זה הרבה כסף בשביל חיה אחת, אדוני.', 'Passepartout said: that is a lot of money for one animal, sir.')),
  P(('פוג אמר: כסף עובר, וזמן לא חוזר לעולם.', 'Fogg said: money passes, and time never comes back.'),
    ('הם שכרו מוביל צעיר שהכיר את הדרך בין ההרים.', 'They hired a young driver who knew the road among the mountains.'),
    ('הם עלו על הפיל, ופוג ישב ישר כמו בכיסא בבית.', 'They got on the elephant, and Fogg sat straight as in a chair at home.'),
    ('בדרך הצטרף אליהם קצין אנגלי שהיה על אותה רכבת.', 'On the way an English officer who was on the same train joined them.'),
    ('הם נכנסו ליער עבה, ולא ראו את השמיים בכלל.', 'They entered a thick forest, and did not see the sky at all.'))]),
 ('The Suttee', 'הטקס בלילה', [
  P(('בערב השני שמעו קולות של תופים בין העצים.', 'On the second evening they heard sounds of drums among the trees.'),
    ('המוביל אמר בשקט: תרדו, ואל תזוזו, ואל תדברו.', 'The driver said quietly: get down, and do not move, and do not speak.'),
    ('הם ירדו מהפיל והתחבאו בין השיחים ליד הדרך.', 'They got down from the elephant and hid among the bushes beside the road.'),
    ('בדרך עברו אנשים רבים עם אש, ותופים, וקולות.', 'On the road many people passed with fire, and drums, and voices.')),
  P(('באמצע הלכה אישה צעירה מאוד, בבגדים לבנים.', 'In the middle walked a very young woman, in white clothes.'),
    ('היא הלכה לאט מאוד ולא הסתכלה על אף אחד.', 'She walked very slowly and did not look at anyone.'),
    ('אחריה נשאו גבר זקן שהיה מת, מכוסה בבד.', 'After her they carried an old man who was dead, covered in cloth.'),
    ('הקצין לחש: היא אשתו, והם הולכים לשרוף את שניהם.', 'The officer whispered: she is his wife, and they are going to burn them both.')),
  P(('פספרטו אמר: היא לא רוצה, וזה נראה בפנים שלה.', 'Passepartout said: she does not want it, and it shows in her face.'),
    ('הקצין אמר: נתנו לה משהו לשתות, והיא לא לגמרי כאן.', 'The officer said: they gave her something to drink, and she is not entirely here.'),
    ('הוא סיפר שהיא בת של סוחר עשיר, ושהיא למדה באנגליה.', 'He told that she is the daughter of a rich merchant, and that she studied in England.'),
    ('הוא אמר: קוראים לה אאודה, ואני שמעתי עליה בעיר.', 'He said: her name is Aouda, and I heard about her in the city.')),
  P(('פוג שאל: מתי בדיוק זה יקרה? והקצין ענה: עם השמש.', 'Fogg asked: when exactly will it happen? And the officer answered: with the sun.'),
    ('פוג הסתכל בשעון ואמר: אז יש לנו שש שעות.', 'Fogg looked at the clock and said: then we have six hours.'),
    ('הוא אמר: יש לי שני ימים ריקים בחשבון שלי.', 'He said: I have two empty days in my calculation.'),
    ('הוא אמר: אני חושב שנשתמש באחד מהם הלילה.', 'He said: I think that we shall use one of them tonight.'),
    ('פספרטו הסתכל עליו, ובפעם הראשונה הוא חייך אליו באמת.', 'Passepartout looked at him, and for the first time he really smiled at him.'))]),
 ('The Bold Rescue', 'ההצלה הנועזת', [
  P(('הם התקרבו למקום בלילה ושכבו על האדמה מאחורי עצים.', 'They approached the place at night and lay on the ground behind trees.'),
    ('סביב האש ישבו אנשים רבים, ורבים מהם כבר ישנו.', 'Around the fire many people sat, and many of them were already asleep.'),
    ('האישה שכבה בתוך בניין קטן, ושומרים עמדו בפתח.', 'The woman lay inside a small building, and guards stood at the entrance.'),
    ('פספרטו אמר: אני אכנס מהצד, ואני אעשה את זה לבד.', 'Passepartout said: I shall go in from the side, and I shall do it alone.')),
  P(('פוג אמר: אנחנו ננסה קודם דרך אחרת, ורק אחר כך זה.', 'Fogg said: we shall try another way first, and only afterwards this.'),
    ('הם ניסו לחפור מתחת לקיר, והאדמה הייתה קשה כמו אבן.', 'They tried to dig under the wall, and the earth was hard as stone.'),
    ('הם חיכו עד שהאש ירדה, אבל השומרים לא ישנו.', 'They waited until the fire went down, but the guards did not sleep.'),
    ('כשעלה האור הראשון, הבינו שכל הזמן שלהם נגמר.', 'When the first light rose, they understood that all their time was finished.')),
  P(('הם הוציאו את המת מהבניין ושמו אותו על העץ.', 'They took the dead man out of the building and put him on the wood.'),
    ('האישה הלכה אחריו, וכולם עמדו סביב בשקט גדול.', 'The woman walked after him, and everyone stood around in great silence.'),
    ('האש נגעה בעץ, והעשן עלה למעלה בין העצים.', 'The fire touched the wood, and the smoke rose upwards among the trees.'),
    ('ואז, מתוך העשן, קם המת לאט והרים את הידיים.', 'And then, out of the smoke, the dead man rose slowly and raised his hands.')),
  P(('כל האנשים נפלו על הפנים או ברחו בין העצים.', 'All the people fell on their faces or ran among the trees.'),
    ('המת הרים את האישה בזרועות ורץ איתה אל היער.', 'The dead man lifted the woman in his arms and ran with her to the forest.'),
    ('מאחורי העצים חיכה פוג עם הפיל ועם המוביל.', 'Behind the trees Fogg waited with the elephant and with the driver.'),
    ('המת היה פספרטו, שנכנס בלילה ושכב במקום הגופה.', 'The dead man was Passepartout, who went in at night and lay in the body’s place.'),
    ('פוג אמר רק: יפה מאוד, ועכשיו קדימה, אנחנו מאחרים.', 'Fogg said only: very fine, and now onward, we are late.'))]),
 ('Down to Calcutta', 'במורד הנהר לכלכותה', [
  P(('הם רכבו על הפיל עד לתחנה הקרובה של הרכבת.', 'They rode on the elephant to the near station of the railway.'),
    ('פוג נתן את הפיל במתנה למוביל הצעיר שהוביל אותם.', 'Fogg gave the elephant as a gift to the young driver who led them.'),
    ('הבחור לא האמין, ועמד ליד החיה בלי לומר מילה.', 'The lad did not believe it, and stood beside the animal without saying a word.'),
    ('פספרטו אמר: אדוני, זאת מתנה גדולה מאוד לאיש אחד.', 'Passepartout said: sir, that is a very big gift for one man.')),
  P(('פוג אמר: הוא סיכן את עצמו איתנו, וזה מגיע לו.', 'Fogg said: he risked himself with us, and he deserves it.'),
    ('האישה הצעירה ישבה בקרון, ולא דיברה במשך שעות.', 'The young woman sat in the carriage, and did not speak for hours.'),
    ('לאט לאט היא חזרה לעצמה והתחילה להסתכל סביבה.', 'Slowly slowly she came back to herself and began to look around her.'),
    ('היא דיברה אנגלית יפה, ושאלה איפה היא נמצאת.', 'She spoke fine English, and asked where she is.')),
  P(('הקצין סיפר לה מה קרה בלילה ומי הוציא אותה.', 'The officer told her what happened at night and who took her out.'),
    ('היא הסתכלה על פוג ואמרה תודה בקול נמוך מאוד.', 'She looked at Fogg and said thank you in a very low voice.'),
    ('פוג אמר: אין על מה, וזה היה בדרך שלנו ממילא.', 'Fogg said: it is nothing, and it was on our way anyway.'),
    ('הוא שאל אותה אם יש לה משפחה במקום כלשהו בעולם.', 'He asked her whether she has family somewhere in the world.')),
  P(('היא אמרה: יש לי קרוב עשיר בהונג קונג, אם הוא חי.', 'She said: I have a rich relative in Hong Kong, if he is alive.'),
    ('פוג אמר: אז ניקח אותך להונג קונג, וזה גם בדרך שלנו.', 'Fogg said: then we shall take you to Hong Kong, and that too is on our way.'),
    ('הרכבת הגיעה לכלכותה בבוקר, בדיוק לפי הזמן שלו.', 'The train reached Calcutta in the morning, exactly according to his time.'),
    ('על הרציף עמדו שני שוטרים וחיכו להם ליד הדלת.', 'On the platform two policemen stood and waited for them beside the door.'),
    ('אחד מהם אמר: אתם פיליאס פוג והמשרת שלו, נכון?', 'One of them said: you are Phileas Fogg and his servant, right?'))]),
 ('The Court and the Bail', 'בית המשפט והערבות', [
  P(('הם הובאו לבית משפט קטן, ואולם היה מלא אנשים.', 'They were brought to a small court, and a hall was full of people.'),
    ('השופט ישב למעלה, וקרא ניירות, ולא הרים את הראש.', 'The judge sat above, and read papers, and did not raise his head.'),
    ('פוג עמד בשקט, וידיו מאחורי הגב, כמו במועדון בלונדון.', 'Fogg stood quietly, and his hands behind his back, as in the club in London.'),
    ('פספרטו הסתכל סביבו וניסה להבין על מה מדובר.', 'Passepartout looked around him and tried to understand what it is about.')),
  P(('השופט אמר: אתם נכנסתם למקום קדוש עם נעליים.', 'The judge said: you entered a holy place with shoes.'),
    ('פספרטו נשם ואמר: טוב, זה מה שזה, אני חשבתי משהו אחר.', 'Passepartout breathed and said: ah, that is what it is, I thought something else.'),
    ('השופט אמר: אז אתה מודה, וזה חוסך לנו הרבה זמן.', 'The judge said: then you admit it, and that saves us a lot of time.'),
    ('פספרטו הבין מיד שהוא אמר בדיוק את הדבר הכי לא נכון.', 'Passepartout understood at once that he had said exactly the most wrong thing.')),
  P(('בפינה של האולם ישב פיקס, ולא זז, ולא הסתכל עליהם.', 'In a corner of the hall Fix sat, and did not move, and did not look at them.'),
    ('הוא הביא את שלושת האנשים מבומביי עד לכאן בעצמו.', 'He brought the three men from Bombay all the way here himself.'),
    ('הוא רצה רק דבר אחד: לעצור אותם עד שהנייר יגיע.', 'He wanted only one thing: to hold them until the paper arrives.'),
    ('השופט אמר: המשרת חמישה עשר ימים, והאדון שמונה.', 'The judge said: the servant fifteen days, and the master eight.')),
  P(('פוג אמר בשקט: אני מבקש לשלם ערבות ולצאת היום.', 'Fogg said quietly: I ask to pay bail and to leave today.'),
    ('השופט אמר: אלף לירות לכל אחד, וזה סכום גדול מאוד.', 'The judge said: a thousand pounds for each, and that is a very big sum.'),
    ('פוג פתח את התיק והוציא את השטרות בלי לספור.', 'Fogg opened the bag and took out the notes without counting.'),
    ('הוא הניח אותם על השולחן ואמר: קחו, ואנחנו הולכים.', 'He placed them on the table and said: here, and we are going.'),
    ('פיקס ראה את הכסף הזה ולא יכול היה לשבת בשקט.', 'Fix saw that money and could not sit quietly.'))]),
 ("Fix Doesn't Understand", 'פיקס לא מבין', [
  P(('פיקס יצא לרציף ועמד שם לבד עשר דקות שלמות.', 'Fix went out to the platform and stood there alone ten whole minutes.'),
    ('הוא חשב: איזה גנב זורק אלפיים לירות בשביל יומיים?', 'He thought: what thief throws away two thousand pounds for two days?'),
    ('הוא חשב: ואיזה גנב עוצר באמצע הדרך בשביל אישה?', 'He thought: and what thief stops in the middle of the road for a woman?'),
    ('הוא הוציא את ההודעה מהכיס וקרא אותה עוד פעם.', 'He took the message out of his pocket and read it one more time.')),
  P(('התיאור התאים: גיל, גובה, פנים, ואפילו דרך הדיבור.', 'The description fitted: age, height, face, and even the way of speaking.'),
    ('הוא אמר לעצמו: או שהוא הכי חכם, או שאני טועה.', 'He said to himself: either he is the cleverest, or I am mistaken.'),
    ('אבל אם הוא טועה, הוא נסע לחינם חצי כדור הארץ.', 'But if he is mistaken, he has travelled half the globe for nothing.'),
    ('ואם הוא צודק והוא עוזב עכשיו, הוא מאבד הכול.', 'And if he is right and he leaves now, he loses everything.')),
  P(('הוא החליט להמשיך איתם עד הונג קונג, ולא רחוק יותר.', 'He decided to continue with them to Hong Kong, and not further.'),
    ('הונג קונג הייתה המקום האחרון תחת דגל אנגליה בדרך.', 'Hong Kong was the last place under England’s flag on the way.'),
    ('אחריה בא יפן, ואחריה אמריקה, ושם אין לו כוח.', 'After it came Japan, and after that America, and there he has no power.'),
    ('הוא עלה על הספינה וחיפש מיד את פספרטו על הסיפון.', 'He got on the ship and immediately looked for Passepartout on the deck.')),
  P(('פספרטו ראה אותו וצעק: שוב אתה! איזה עולם קטן!', 'Passepartout saw him and shouted: you again! What a small world!'),
    ('פיקס אמר: אני נוסע בעסקים, וכל פעם באותה דרך.', 'Fix said: I travel on business, and each time by the same road.'),
    ('פספרטו אמר: אז נשתה משהו יחד הערב, כמו חברים.', 'Passepartout said: then we shall drink something together this evening, like friends.'),
    ('פיקס אמר: בשמחה רבה, ואני מזמין את הכוס הראשונה.', 'Fix said: with great pleasure, and I invite the first glass.'))]),
 ('Toward Hong Kong', 'בדרך להונג קונג', [
  P(('הספינה יצאה מכלכותה ופנתה מזרחה אל הים הפתוח.', 'The ship left Calcutta and turned east to the open sea.'),
    ('אאודה ישבה על הסיפון בכל בוקר עם ספר ביד.', 'Aouda sat on the deck every morning with a book in her hand.'),
    ('פוג ישב לידה, וקרא, וכתב, ולא דיבר הרבה.', 'Fogg sat beside her, and read, and wrote, and did not speak much.'),
    ('לפעמים הם דיברו על הודו, ועל אנגליה, ועל הדרך.', 'Sometimes they spoke about India, and about England, and about the road.')),
  P(('היא שאלה אותו פעם: למה אתה עושה את הנסיעה הזאת?', 'She asked him once: why are you making this journey?'),
    ('הוא אמר: יש הימור, והוא נכתב על נייר, ואני עומד בו.', 'He said: there is a bet, and it was written on paper, and I stand by it.'),
    ('היא שאלה: ואם תפסיד? הוא אמר: אז אאבד את הכול.', 'She asked: and if you lose? He said: then I shall lose everything.'),
    ('היא אמרה: ובכל זאת עצרת בשבילי לילה שלם.', 'She said: and nevertheless you stopped a whole night for me.'),
    ('הוא לא ענה, ורק הסתכל על השעון, ואז על המים.', 'He did not answer, and only looked at the clock, and then at the water.')),
  P(('פספרטו ראה את שניהם יושבים יחד והתחיל לחשוב.', 'Passepartout saw the two of them sitting together and began to think.'),
    ('הוא אמר לעצמו: אולי האדון שלי הוא לא רק שעון.', 'He said to himself: perhaps my master is not only a clock.'),
    ('הוא התחיל לאהוב אותו, בלי שהוא הבין מתי זה קרה.', 'He began to love him, without understanding when it happened.'),
    ('הוא הפסיק לספור את הימים ורק רצה שהם יצליחו.', 'He stopped counting the days and only wanted them to succeed.')),
  P(('הספינה הגיעה להונג קונג יום אחד לפני הזמן.', 'The ship reached Hong Kong one day before the time.'),
    ('פוג רשם בפנקס שיש לו עכשיו יומיים ריקים בכיס.', 'Fogg wrote in the notebook that he now has two empty days in his pocket.'),
    ('הם ירדו לחפש את הקרוב של אאודה בעיר הגדולה.', 'They went down to look for Aouda’s relative in the big city.'),
    ('בבית שלו אמרו להם שהוא עזב לאירופה לפני שנתיים.', 'At his house they told them that he left for Europe two years ago.'),
    ('אאודה עמדה ברחוב ולא ידעה לאן ללכת עכשיו.', 'Aouda stood in the street and did not know where to go now.'))]),
 ('Each About His Business', 'כל אחד והעניין שלו', [
  P(('פוג אמר לה: אז את באה איתנו הלאה, עד לונדון.', 'Fogg said to her: then you come with us onward, to London.'),
    ('הוא אמר את זה בלי לחשוב, כאילו זה דבר פשוט.', 'He said it without thinking, as if it is a simple thing.'),
    ('אאודה אמרה: אבל אני מפריעה לך בכל דרך אפשרית.', 'Aouda said: but I disturb you in every possible way.'),
    ('הוא אמר: את לא מפריעה, ויש מקום על כל ספינה.', 'He said: you do not disturb, and there is room on every ship.')),
  P(('פספרטו הלך לנמל לקנות שלושה כרטיסים ליוקוהמה.', 'Passepartout went to the port to buy three tickets to Yokohama.'),
    ('הוא גילה שהספינה יוצאת מוקדם, כבר בערב הזה.', 'He discovered that the ship leaves early, already this evening.'),
    ('הוא שמח מאוד, כי זה נותן להם עוד יום ביד.', 'He was very happy, because that gives them another day in hand.'),
    ('הוא רץ בחזרה למלון כדי לספר את הבשורה הטובה.', 'He ran back to the hotel in order to tell the good news.')),
  P(('בדרך פגש אותו פיקס וביקש ממנו לשבת רגע.', 'On the way Fix met him and asked him to sit a moment.'),
    ('הוא אמר: יש לי משהו חשוב לומר לך, ורק לך.', 'He said: I have something important to say to you, and only to you.'),
    ('הם נכנסו לבית קטן ליד הנמל ואז ישבו בפינה.', 'They went into a small house beside the port and sat in a corner.'),
    ('פיקס הזמין שתייה, והתחיל לדבר לאט מאוד.', 'Fix ordered a drink, and began to speak very slowly.')),
  P(('הוא אמר: אני לא איש עסקים, ואני בלש מלונדון.', 'He said: I am not a businessman, and I am a detective from London.'),
    ('הוא אמר: האדון שלך גנב חמישים וחמישה אלף מבנק.', 'He said: your master stole fifty-five thousand from a bank.'),
    ('פספרטו קם וצעק: זה שקר, והאיש הזה הוא ישר.', 'Passepartout got up and shouted: that is a lie, and this man is honest.'),
    ('פיקס אמר: תעזור לי, ואתה תקבל חלק מהפרס הגדול.', 'Fix said: help me, and you will receive part of the big reward.'),
    ('פספרטו אמר: אני לא מדבר איתך יותר, לעולם.', 'Passepartout said: I do not speak with you any more, ever.'))]),
 ('The Opium Den', 'בית האופיום', [
  P(('פיקס ראה שהוא מאבד אותו וניסה דבר אחר לגמרי.', 'Fix saw that he is losing him and tried something entirely different.'),
    ('הוא אמר: בסדר, שכח את זה, בוא נשתה כמו חברים.', 'He said: fine, forget it, let us drink like friends.'),
    ('הוא הזמין עוד כוס, ואז עוד אחת, ואז עוד אחת.', 'He ordered another glass, and then one more, and then one more.'),
    ('פספרטו שתה, כי הוא כעס, וכי הוא רצה לשכוח.', 'Passepartout drank, because he was angry, and because he wanted to forget.')),
  P(('המקום היה חשוך, ואנשים שכבו על מיטות נמוכות.', 'The place was dark, and people lay on low beds.'),
    ('הם עישנו מקטרות ארוכות, והעשן היה כבד ומתוק.', 'They smoked long pipes, and the smoke was heavy and sweet.'),
    ('פיקס נתן לו מקטרת ואמר: תנסה, זה עוזר לשכוח.', 'Fix gave him a pipe and said: try it, it helps one forget.'),
    ('פספרטו לקח אותה, ואחרי כמה רגעים הראש שלו נפל.', 'Passepartout took it, and after a few moments his head fell.')),
  P(('לפני שנרדם הוא מלמל: הספינה יוצאת בערב הזה.', 'Before he fell asleep he muttered: the ship leaves this evening.'),
    ('פיקס שמע את זה והבין שהוא בדיוק במקום הנכון.', 'Fix heard that and understood that he is exactly in the right place.'),
    ('הוא ידע שעכשיו פוג לא יידע על השעה החדשה.', 'He knew that now Fogg will not know about the new hour.'),
    ('הוא יצא מהמקום והשאיר את פספרטו שוכב שם.', 'He went out of the place and left Passepartout lying there.')),
  P(('בערב פוג ואאודה הגיעו לנמל עם התיק הקטן.', 'In the evening Fogg and Aouda arrived at the port with the small bag.'),
    ('הספינה כבר לא הייתה שם, והמים היו ריקים וחשוכים.', 'The ship was no longer there, and the water was empty and dark.'),
    ('פוג שאל איש בנמל, והוא אמר: היא יצאה לפני שעה.', 'Fogg asked a man at the port, and he said: it left an hour ago.'),
    ('פוג לא אמר כלום, ורק הלך לאורך הרציף לחפש ספינה.', 'Fogg said nothing, and only walked along the quay to look for a ship.'),
    ('פספרטו לא היה שם, וזאת הייתה הפעם הראשונה.', 'Passepartout was not there, and that was the first time.'))]),
 ('Fix Confronts Fogg', 'פיקס מול פוג', [
  P(('בקצה הרציף עמדה ספינה קטנה עם שלושה אנשי צוות.', 'At the end of the quay stood a small ship with three crew men.'),
    ('פוג ניגש אל האיש שעמד עליה ושאל כמה היא שווה.', 'Fogg went up to the man who stood on it and asked how much it is worth.'),
    ('האיש אמר: אני לא מוכר, אבל אני יכול לקחת אתכם.', 'The man said: I do not sell, but I can take you.'),
    ('פוג אמר: אני צריך להגיע ליוקוהמה, ומהר מאוד.', 'Fogg said: I need to get to Yokohama, and very fast.')),
  P(('האיש אמר: זה רחוק מדי בשביל ספינה כזאת, אדוני.', 'The man said: that is too far for such a ship, sir.'),
    ('הוא אמר: אבל אפשר להגיע לשנחאי, ומשם יש קו גדול.', 'He said: but it is possible to reach Shanghai, and from there there is a big line.'),
    ('פוג אמר: מצוין, ואני משלם מאה לכל יום בדרך.', 'Fogg said: excellent, and I pay a hundred for every day on the way.'),
    ('הוא אמר: ואם נגיע בזמן, אני מוסיף עוד מאתיים.', 'He said: and if we arrive on time, I add another two hundred.')),
  P(('באותו רגע הגיע פיקס לרציף בריצה קלה מאוד.', 'At that moment Fix arrived at the quay at a very light run.'),
    ('הוא אמר: אני נוסע גם לשנחאי, אפשר לעלות איתכם?', 'He said: I too am travelling to Shanghai, may I come up with you?'),
    ('פוג אמר: בבקשה, ויש מקום, וזה לא משנה לי.', 'Fogg said: please, and there is room, and it makes no difference to me.'),
    ('פיקס עלה, ואז ישב בקצה, והסתכל על פוג כל הדרך.', 'Fix got on, and sat at the end, and looked at Fogg the whole way.')),
  P(('אאודה שאלה: איפה פספרטו? ופוג אמר: אני לא יודע.', 'Aouda asked: where is Passepartout? And Fogg said: I do not know.'),
    ('הוא אמר: השארתי כסף במלון וכתבתי לו איפה אנחנו.', 'He said: I left money at the hotel and wrote to him where we are.'),
    ('אאודה אמרה: אתה עוזב אותו כאן? הוא אמר: לא.', 'Aouda said: are you leaving him here? He said: no.'),
    ('הוא אמר: אני אחזור בשבילו אם יהיה צריך, אחר כך.', 'He said: I shall come back for him if it is needed, afterwards.'),
    ('הספינה יצאה בלילה, והרוח הייתה חזקה מהצפון.', 'The ship left at night, and the wind was strong from the north.'))]),
 ('The Storm', 'הסופה', [
  P(('ביום השני התחילו הגלים לעלות גבוה מאוד.', 'On the second day the waves began to rise very high.'),
    ('השמיים נעשו אפורים, ואז שחורים, ואז ירד גשם.', 'The sky became grey, and then black, and then rain fell.'),
    ('המפקח על הספינה אמר: אנחנו חייבים להיכנס לחוף.', 'The master of the ship said: we must go in to shore.'),
    ('פוג אמר: לא, אנחנו ממשיכים, ואני משלם על הסיכון.', 'Fogg said: no, we continue, and I pay for the risk.')),
  P(('הרוח קרעה מפרש אחד, והאנשים עבדו כל הלילה.', 'The wind tore one sail, and the men worked all night.'),
    ('פוג עמד על הסיפון ואחז בחבל ולא ירד למטה.', 'Fogg stood on the deck and held a rope and did not go below.'),
    ('אאודה יצאה אליו פעם אחת וראתה אותו רטוב לגמרי.', 'Aouda came out to him once and saw him completely wet.'),
    ('הוא אמר לה: תיכנסי פנימה, כאן זה לא מקום לך.', 'He said to her: go inside, here is not a place for you.')),
  P(('פיקס היה חולה מאוד, ושכב למטה, ולא קם בכלל.', 'Fix was very ill, and lay below, and did not get up at all.'),
    ('הוא חשב: אם הספינה תטבע, גם הפרס שלי יטבע איתה.', 'He thought: if the ship sinks, my reward too will sink with it.'),
    ('הוא חשב: ואם הוא באמת גנב, הוא בורח מצוין.', 'He thought: and if he really is a thief, he escapes excellently.'),
    ('בבוקר השלישי הרוח ירדה, והים נעשה שקט לגמרי.', 'On the third morning the wind dropped, and the sea became entirely calm.')),
  P(('הם הגיעו לשנחאי, וראו את הספינה הגדולה יוצאת.', 'They reached Shanghai, and saw the big ship going out.'),
    ('היא הייתה כבר רחוקה, והעשן שלה עלה מעל המים.', 'It was already far, and its smoke rose above the water.'),
    ('פוג אמר למפקח: תרים דגל, ואתה תרים גם את השני.', 'Fogg said to the master: raise a flag, and raise the second one too.'),
    ('הם ירו ירייה אחת, ואז עוד אחת, וחיכו בשקט.', 'They fired one shot, and then another, and waited quietly.'),
    ('הספינה הגדולה עצרה לאט, והתחילה לחזור אליהם.', 'The big ship stopped slowly, and began to come back to them.'))]),
 ('Passepartout in Japan', 'פספרטו ביפן', [
  P(('פספרטו התעורר על הרצפה בהונג קונג בבוקר.', 'Passepartout woke on the floor in Hong Kong in the morning.'),
    ('הראש שלו כאב, והוא לא זכר כמעט שום דבר.', 'His head hurt, and he remembered almost nothing.'),
    ('הוא רץ אל הנמל, וראה ספינה, ועלה עליה מיד.', 'He ran to the port, and saw a ship, and got on it at once.'),
    ('רק אחרי שעה הוא הבין שהיא נוסעת ליוקוהמה.', 'Only after an hour did he understand that it travels to Yokohama.')),
  P(('לא היה לו כרטיס, ולא היה לו מטבע אחד בכיס.', 'He had no ticket, and did not have one coin in his pocket.'),
    ('הוא הלך אל המפקח וסיפר לו את כל הסיפור.', 'He went to the master and told him the whole story.'),
    ('המפקח אמר: אתה תעבוד כאן עד יפן, וזה התשלום.', 'The master said: you will work here until Japan, and that is the payment.'),
    ('פספרטו עבד בסיפון, ובמטבח, ובכל מקום שביקשו.', 'Passepartout worked on the deck, and in the kitchen, and everywhere they asked.')),
  P(('ביוקוהמה הוא ירד לרציף בבגדים שלו מהודו.', 'At Yokohama he went down to the quay in his clothes from India.'),
    ('הוא הלך ברחובות וחיפש את פוג בכל מלון בעיר.', 'He walked in the streets and looked for Fogg in every hotel in the city.'),
    ('הוא לא מצא אותו, ולא היה לו כסף לאוכל.', 'He did not find him, and he had no money for food.'),
    ('בערב הוא מכר את הבגד שלו וקנה בגד יפני ישן.', 'In the evening he sold his coat and bought an old Japanese garment.')),
  P(('הוא ישב על מדרגה ברחוב ולא ידע מה לעשות.', 'He sat on a step in the street and did not know what to do.'),
    ('ואז הוא ראה שלט גדול על בניין עם ציורים.', 'And then he saw a big sign on a building with pictures.'),
    ('היה שם כתוב שמחפשים אנשים לקבוצה שנוסעת לאמריקה.', 'It was written there that they are looking for people for a company travelling to America.'),
    ('פספרטו אמר לעצמו: אני יודע לעמוד על הידיים.', 'Passepartout said to himself: I know how to stand on my hands.'),
    ('הוא נכנס פנימה ואמר: קחו אותי, אני עשיתי הכול.', 'He went inside and said: take me, I have done everything.'))]),
 ("Passepartout's Long Nose", 'האף הארוך של פספרטו', [
  P(('הקבוצה עשתה מופע גדול באולם מלא אנשים בערב.', 'The company gave a big show in a hall full of people in the evening.'),
    ('היו שם אנשים שהלכו על חבל ואנשים שקפצו באש.', 'There were there men who walked on a rope and men who jumped through fire.'),
    ('בסוף המופע היה מספר אחד שכולם חיכו לו.', 'At the end of the show there was one number that everyone waited for.'),
    ('קבוצה של גברים עמדה זה על זה ובנתה מגדל.', 'A group of men stood one on another and built a tower.')),
  P(('לכל אחד מהם היה אף ארוך מאוד עשוי מעץ.', 'Each one of them had a very long nose made of wood.'),
    ('פספרטו עמד למטה, בשורה הראשונה, והחזיק שניים.', 'Passepartout stood at the bottom, in the first row, and held two.'),
    ('הוא חשב על הבית בלונדון ועל השעון על הקיר.', 'He thought about the house in London and about the clock on the wall.'),
    ('הוא חשב: אם האדון שלי היה רואה אותי עכשיו.', 'He thought: if my master could see me now.')),
  P(('המגדל עלה, שורה אחרי שורה, עד קרוב לתקרה.', 'The tower rose, row after row, until close to the ceiling.'),
    ('כל האולם שתק, וכל אחד הסתכל למעלה ולא נשם.', 'The whole hall was silent, and everyone looked up and did not breathe.'),
    ('ואז פספרטו ראה בשורה הראשונה שני פנים מוכרות.', 'And then Passepartout saw in the first row two familiar faces.'),
    ('פוג ואאודה ישבו שם, ליד השולחן, והסתכלו ישר עליו.', 'Fogg and Aouda sat there, beside the table, and looked straight at him.')),
  P(('פספרטו צעק בקול גדול ושכח לגמרי איפה הוא.', 'Passepartout shouted loudly and forgot entirely where he is.'),
    ('הוא הזיז את הידיים, וכל המגדל התחיל לזוז איתו.', 'He moved his hands, and the whole tower began to move with him.'),
    ('כל האנשים נפלו זה על זה בקול גדול מאוד.', 'All the men fell one on another with a very loud noise.'),
    ('הקהל צחק וחשב שזה החלק הכי טוב בכל המופע.', 'The audience laughed and thought that it is the best part of the whole show.'),
    ('פספרטו יצא מתחת לערמה ורץ ישר אל פוג.', 'Passepartout came out from under the heap and ran straight to Fogg.'))]),
 ('The Reunion', 'המפגש', [
  P(('פוג לא קם מהכיסא, ורק אמר: אתה כאן, יפה מאוד.', 'Fogg did not get up from the chair, and only said: you are here, very fine.'),
    ('אאודה קמה, ואחזה בשתי ידיו, ועיניה היו רטובות.', 'Aouda got up, and held both his hands, and her eyes were wet.'),
    ('פספרטו התחיל לספר, והדברים יצאו ממנו בלי סדר.', 'Passepartout began to tell, and the things came out of him without order.'),
    ('פוג אמר: קודם תלבש בגדים, ואחר כך תספר הכול.', 'Fogg said: first put on clothes, and afterwards tell everything.')),
  P(('הם קנו לו בגדים בחנות ליד הנמל באותו ערב.', 'They bought him clothes at a shop beside the port that evening.'),
    ('בספינה לאמריקה הוא סיפר לפוג על הבלש פיקס.', 'On the ship to America he told Fogg about the detective Fix.'),
    ('פוג הקשיב בשקט ואמר: אז זה מה שהיה בהונג קונג.', 'Fogg listened quietly and said: so that is what happened in Hong Kong.'),
    ('פספרטו אמר: אני אשבור לו את העצמות כשאראה אותו.', 'Passepartout said: I shall break his bones when I see him.')),
  P(('פוג אמר: לא, אתה לא תעשה שום דבר כזה.', 'Fogg said: no, you will not do anything of the sort.'),
    ('הוא אמר: הוא עשה את העבודה שלו, גם אם היא שגויה.', 'He said: he did his work, even if it is mistaken.'),
    ('הוא אמר: וזה עולה לנו זמן, ואת הזמן אני סופר.', 'He said: and it costs us time, and the time I count.'),
    ('פספרטו אמר: ואם הוא יבוא שוב? פוג אמר: שיבוא.', 'Passepartout said: and if he comes again? Fogg said: let him come.')),
  P(('פיקס באמת היה על אותה ספינה, בקומה למטה.', 'Fix really was on that same ship, on the deck below.'),
    ('הוא ידע שבאמריקה אין לו שום כוח לעצור אותם.', 'He knew that in America he has no power at all to stop them.'),
    ('הוא החליט לעזור להם עכשיו, כדי שיגיעו לאנגליה.', 'He decided to help them now, so that they will reach England.'),
    ('הוא אמר לעצמו: בלונדון אני אעצור אותו בעצמי.', 'He said to himself: in London I shall arrest him myself.'),
    ('הוא ניגש לפספרטו ואמר: אני מבקש סליחה, ובאמת.', 'He went up to Passepartout and said: I ask forgiveness, and truly.'))]),
 ('Crossing the Pacific', 'חוצים את האוקיינוס', [
  P(('הספינה יצאה מיוקוהמה ופנתה מזרחה אל הים הגדול.', 'The ship left Yokohama and turned east to the great sea.'),
    ('הדרך הייתה ארוכה, ובמשך ימים לא ראו שום חוף.', 'The road was long, and for days they saw no shore.'),
    ('פוג ישב בכל בוקר עם הפנקס וכתב את החשבון.', 'Fogg sat every morning with the notebook and wrote the calculation.'),
    ('הוא הפסיד יומיים בהונג קונג, ועכשיו הוא שווה בדיוק.', 'He lost two days in Hong Kong, and now he is exactly even.')),
  P(('אאודה ישבה איתו שעות, והם דיברו על דברים רבים.', 'Aouda sat with him for hours, and they spoke about many things.'),
    ('היא סיפרה על הילדות שלה, ועל אנגליה, ועל הים.', 'She told about her childhood, and about England, and about the sea.'),
    ('הוא סיפר מעט מאוד, ורק ענה על מה שהיא שאלה.', 'He told very little, and only answered what she asked.'),
    ('פספרטו הסתכל עליהם מרחוק וחייך בלי לומר כלום.', 'Passepartout looked at them from a distance and smiled without saying anything.')),
  P(('לילה אחד הוא עמד עם פיקס על הסיפון בחושך.', 'One night he stood with Fix on the deck in the dark.'),
    ('הוא אמר: אתה עוד חושב שהוא לקח את הכסף?', 'He said: do you still think that he took the money?'),
    ('פיקס אמר: אני חושב פחות, אבל אני עוד לא בטוח.', 'Fix said: I think it less, but I am not yet sure.'),
    ('פספרטו אמר: אתה תראה, וכל העולם יראה, בסוף.', 'Passepartout said: you will see, and the whole world will see, in the end.')),
  P(('הספינה הגיעה לסן פרנסיסקו בבוקר של יום שלישי.', 'The ship reached San Francisco on the morning of a Tuesday.'),
    ('הם ירדו לרציף, וראו עיר חדשה שנבנתה מהר מאוד.', 'They went down to the quay, and saw a new city that was built very fast.'),
    ('הרחובות היו רחבים, והבתים היו מעץ, וכולם מיהרו.', 'The streets were wide, and the houses were of wood, and everyone hurried.'),
    ('פוג אמר: הרכבת יוצאת בשש, ויש לנו כמה שעות.', 'Fogg said: the train leaves at six, and we have a few hours.'),
    ('הוא אמר: אנחנו הולכים לחתום על הדרכון, כרגיל.', 'He said: we are going to sign the passport, as usual.'))]),
 ('A Glimpse of San Francisco', 'הצצה בסן פרנסיסקו', [
  P(('בדרך למשרד הם עברו ברחוב מלא אנשים וקולות.', 'On the way to the office they passed a street full of people and voices.'),
    ('היו שם שולחנות, ודגלים, ואנשים שעמדו על ארגזים.', 'There were there tables, and flags, and men who stood on boxes.'),
    ('כל אחד צעק שם של מישהו, וכולם צעקו יחד.', 'Each one shouted someone’s name, and everyone shouted together.'),
    ('פספרטו שאל: מה קורה כאן? מישהו ענה: בחירות.', 'Passepartout asked: what is happening here? Someone answered: elections.')),
  P(('שני הצדדים התקרבו זה לזה מרגע לרגע.', 'The two sides drew closer to each other from moment to moment.'),
    ('פוג ואאודה עמדו בצד, ליד קיר, והסתכלו על זה.', 'Fogg and Aouda stood aside, beside a wall, and looked at it.'),
    ('ואז התחיל ריב, וכל הרחוב זז כמו מים בסיר.', 'And then a fight began, and the whole street moved like water in a pot.'),
    ('אנשים דחפו, ונפלו, ועמדו, וצעקו, וזרקו כובעים.', 'People pushed, and fell, and stood, and shouted, and threw hats.')),
  P(('איש גדול אחד דחף את פוג ישר על הכתף.', 'One big man pushed Fogg straight on the shoulder.'),
    ('פוג הסתובב אליו והסתכל בו בלי לומר מילה.', 'Fogg turned to him and looked at him without saying a word.'),
    ('האיש הרים יד, ופספרטו קפץ בין השניים מהר.', 'The man raised a hand, and Passepartout jumped between the two fast.'),
    ('המכה נחתה על פספרטו, והוא נפל אחורה על הרצפה.', 'The blow landed on Passepartout, and he fell backwards on the ground.')),
  P(('פוג הרים אותו, וניקה לו את הבגד, ואמר: קדימה.', 'Fogg lifted him, and cleaned his coat, and said: onward.'),
    ('פספרטו אמר: אדוני, האיש הזה הכה אותך קודם.', 'Passepartout said: sir, this man struck you first.'),
    ('פוג אמר: נכון, ואני זוכר את הפנים שלו היטב.', 'Fogg said: true, and I remember his face well.'),
    ('הוא אמר: כשאחזור לאמריקה, אני אחפש אותו.', 'He said: when I come back to America, I shall look for him.'),
    ('הוא אמר: ועכשיו יש לנו רכבת בעוד שעה וחצי.', 'He said: and now we have a train in an hour and a half.'))]),
 ('Aboard the Pacific Railroad', 'ברכבת הגדולה', [
  P(('הרכבת יצאה מסן פרנסיסקו בשעה שש בדיוק.', 'The train left San Francisco at six exactly.'),
    ('הדרך אל ניו יורק לקחה שבעה ימים ושבעה לילות.', 'The road to New York took seven days and seven nights.'),
    ('הקרונות היו ארוכים, ואפשר היה ללכת בין כולם.', 'The carriages were long, and it was possible to walk among all of them.'),
    ('היו שם מיטות, ושולחנות, ואפילו חדר עם ספרים.', 'There were there beds, and tables, and even a room with books.')),
  P(('ביום הראשון עברו בין הרים גבוהים מכוסים שלג.', 'On the first day they passed among high mountains covered with snow.'),
    ('אחר כך ירדה הרכבת אל מישור גדול ופתוח מאוד.', 'Afterwards the train came down to a big and very open plain.'),
    ('לא היו שם עצים, ולא בתים, ולא דרכים, ולא איש.', 'There were no trees there, and no houses, and no roads, and no one.'),
    ('פספרטו עמד ליד החלון שעות והסתכל על הריק.', 'Passepartout stood beside the window for hours and looked at the emptiness.')),
  P(('פוג ישב ושיחק קלפים עם שני נוסעים ועם פיקס.', 'Fogg sat and played cards with two passengers and with Fix.'),
    ('הוא ניצח כמעט בכל משחק, ולא אמר על זה כלום.', 'He won almost every game, and said nothing about it.'),
    ('אאודה ישבה לידו וקראה, והרימה עיניים לפעמים.', 'Aouda sat beside him and read, and raised her eyes sometimes.'),
    ('פיקס שיחק בלי לחשוב, כי הראש שלו היה במקום אחר.', 'Fix played without thinking, because his head was somewhere else.')),
  P(('בלילה הרכבת עברה על גשר גבוה מעל נהר גדול.', 'At night the train passed on a high bridge above a big river.'),
    ('פספרטו התעורר מהקול ולא הצליח להירדם שוב.', 'Passepartout woke from the sound and could not fall asleep again.'),
    ('הוא ספר בראש את הימים שנשארו עד לונדון.', 'He counted in his head the days that remained until London.'),
    ('הוא אמר לעצמו: אם הכול ילך טוב, אנחנו נצליח.', 'He said to himself: if everything goes well, we shall succeed.'),
    ('הוא אמר: אבל בנסיעה הזאת הכול אף פעם לא הולך טוב.', 'He said: but on this journey everything never goes well.'))]),
 ('A Story Along the Way', 'סיפור בדרך', [
  P(('בקרון האוכל ישב איש מבוגר וסיפר סיפורים לכולם.', 'In the dining carriage an older man sat and told stories to everyone.'),
    ('הוא אמר שהוא עובר בדרך הזאת כבר עשרים שנה.', 'He said that he has been going by this road for twenty years already.'),
    ('הוא סיפר על השנים שבהן לא הייתה כאן מסילה בכלל.', 'He told about the years in which there was no track here at all.'),
    ('הוא אמר: אז נסעו בעגלות, וזה לקח חודשים ארוכים.', 'He said: then they travelled in carts, and it took long months.')),
  P(('הוא סיפר על משפחות שיצאו לדרך ולא הגיעו לעולם.', 'He told about families who set out and never arrived.'),
    ('הוא סיפר על חורף אחד שבו נסגרה הדרך בשלג.', 'He told about one winter in which the road was closed with snow.'),
    ('אאודה שאלה: ולמה אנשים יצאו בכלל לדרך כזאת?', 'Aouda asked: and why did people set out on such a road at all?'),
    ('הוא אמר: כי מעבר להרים סיפרו שיש אדמה טובה.', 'He said: because beyond the mountains they said that there is good land.')),
  P(('פספרטו שאל אותו על השבטים שחיים במישור הזה.', 'Passepartout asked him about the tribes that live on this plain.'),
    ('האיש אמר: הם היו כאן לפנינו, וזאת האדמה שלהם.', 'The man said: they were here before us, and this is their land.'),
    ('הוא אמר: לקחנו את הכול, ואנחנו קוראים לזה קדמה.', 'He said: we took everything, and we call it progress.'),
    ('הוא אמר: לפעמים הם עוצרים רכבת, וזה קורה גם היום.', 'He said: sometimes they stop a train, and that happens even today.')),
  P(('פוג הרים את הראש מהפנקס ושאל: כמה זמן זה לוקח?', 'Fogg raised his head from the notebook and asked: how long does that take?'),
    ('האיש צחק ואמר: אדוני שואל רק על הזמן, תמיד.', 'The man laughed and said: sir asks only about the time, always.'),
    ('פוג אמר: זמן זה הדבר היחיד שאי אפשר לקנות.', 'Fogg said: time is the only thing that one cannot buy.'),
    ('האיש הסתכל בו ואמר: אתה יודע, אתה צודק לגמרי.', 'The man looked at him and said: you know, you are completely right.'))]),
 ('Buffalo on the Track', 'עדר על המסילה', [
  P(('בבוקר השלישי הרכבת עצרה פתאום באמצע המישור.', 'On the third morning the train stopped suddenly in the middle of the plain.'),
    ('הנוסעים ירדו לראות מה קרה ולמה אין תנועה.', 'The passengers got down to see what happened and why there is no movement.'),
    ('לפנינו, על המסילה, עמד עדר גדול מאוד של בהמות.', 'In front, on the track, stood a very big herd of animals.'),
    ('הן עברו לאט מצד אחד לצד השני, בלי למהר.', 'They passed slowly from one side to the other, without hurrying.')),
  P(('פספרטו שאל את הנהג: כמה זמן הן יעברו כאן?', 'Passepartout asked the driver: how long will they pass here?'),
    ('הנהג אמר: לפעמים שעה, ולפעמים שלוש או ארבע.', 'The driver said: sometimes an hour, and sometimes three or four.'),
    ('פספרטו אמר: אז תדחוף אותן, יש לך מנוע גדול.', 'Passepartout said: then push them, you have a big engine.'),
    ('הנהג אמר: הן יפילו את הרכבת, ולא נגיע לשום מקום.', 'The driver said: they will knock the train over, and we shall get nowhere.')),
  P(('פספרטו רץ אל פוג וסיפר לו על העדר על המסילה.', 'Passepartout ran to Fogg and told him about the herd on the track.'),
    ('פוג ישב במקום שלו ולא הרים את הראש בכלל.', 'Fogg sat in his place and did not raise his head at all.'),
    ('הוא אמר: זה כתוב בחשבון שלי, ואין מה לעשות.', 'He said: it is written in my calculation, and there is nothing to do.'),
    ('פספרטו יצא החוצה וצעק על הבהמות בקול גדול.', 'Passepartout went outside and shouted at the animals in a loud voice.')),
  P(('הן לא הסתכלו עליו בכלל והמשיכו לעבור לאט.', 'They did not look at him at all and went on passing slowly.'),
    ('אחרי שלוש שעות עברה האחרונה, והמסילה נשארה ריקה.', 'After three hours the last one passed, and the track remained empty.'),
    ('הרכבת יצאה שוב, אבל שלוש שעות כבר לא חזרו.', 'The train set out again, but three hours no longer came back.'),
    ('פוג רשם בפנקס: שלוש שעות, וזה נכנס במקום הריק.', 'Fogg wrote in the notebook: three hours, and that goes into the empty place.'),
    ('אאודה שאלה: ואם נאחר בסוף? הוא אמר: אז נאחר.', 'Aouda asked: and if we are late in the end? He said: then we shall be late.'))]),
 ('The Broken Bridge', 'הגשר החלש', [
  P(('בערב הרכבת עצרה שוב, והפעם לפני גשר ארוך.', 'In the evening the train stopped again, and this time before a long bridge.'),
    ('הנהג ירד ובדק את העמודים והחזיר את הפנס.', 'The driver got down and checked the pillars and brought back the lamp.'),
    ('הוא אמר לנוסעים: הגשר חלש, והוא לא יחזיק אותנו.', 'He said to the passengers: the bridge is weak, and it will not hold us.'),
    ('הוא אמר: יש לנו שתי אפשרויות, ושתיהן לא טובות.', 'He said: we have two possibilities, and both of them are not good.')),
  P(('הוא אמר: או שנחכה כאן שישה ימים לרכבת אחרת.', 'He said: either we wait here six days for another train.'),
    ('הוא אמר: או שנחזור עשרים קילומטר ואנחנו נעבור בדרך אחרת.', 'He said: or we go back twenty kilometres and pass by another road.'),
    ('הנוסעים התחילו לצעוק, וכל אחד אמר דבר אחר.', 'The passengers began to shout, and each one said a different thing.'),
    ('פוג עמד בשקט ולא אמר כלום במשך כמה דקות.', 'Fogg stood quietly and said nothing for a few minutes.')),
  P(('ואז קם נוסע אחד ואמר: יש דרך שלישית, אדונים.', 'And then one passenger got up and said: there is a third way, gentlemen.'),
    ('הוא אמר: ניסע מהר מאוד, ואנחנו נעבור לפני שהוא נופל.', 'He said: we shall travel very fast, and pass before it falls.'),
    ('הוא אמר: אם המהירות גדולה, המשקל כמעט לא נוגע.', 'He said: if the speed is great, the weight almost does not touch.'),
    ('חצי מהנוסעים אמרו: כן, וחצי אמרו: זה טירוף.', 'Half of the passengers said: yes, and half said: it is madness.')),
  P(('הנהג חשב רגע ואמר: אני מוכן לנסות את זה.', 'The driver thought a moment and said: I am ready to try it.'),
    ('כמה נוסעים ירדו והלכו ברגל אל הצד השני.', 'Some passengers got down and walked on foot to the other side.'),
    ('הרכבת חזרה אחורה, ואז יצאה קדימה במהירות גדולה.', 'The train went backwards, and then set out forward at great speed.'),
    ('היא עברה את הגשר בשנייה אחת, כמו ציפור.', 'It passed the bridge in one second, like a bird.'),
    ('מאחוריהם נשמע קול, והגשר נפל אל תוך הנהר.', 'Behind them a sound was heard, and the bridge fell into the river.'))]),
 ('Fogg Does His Duty', 'פוג עושה את שלו', [
  P(('בלילה ההוא הרכבת נסעה לאט בין גבעות נמוכות.', 'That night the train travelled slowly among low hills.'),
    ('פתאום נשמעו קולות מבחוץ, ואז ירי, ואז קולות.', 'Suddenly voices were heard from outside, and then shooting, and then voices.'),
    ('אנשים עלו על הרכבת מהצדדים בזמן שהיא נסעה.', 'People got on the train from the sides while it was moving.'),
    ('הם נכנסו לקרונות והתחילו לקחת כסף מהנוסעים.', 'They went into the carriages and began to take money from the passengers.')),
  P(('הנוסעים לא נתנו בשקט, והתחיל ריב בכל הרכבת.', 'The passengers did not give quietly, and a fight began in the whole train.'),
    ('פוג הוציא את האקדח שלו ועמד בפתח הקרון.', 'Fogg took out his revolver and stood at the carriage door.'),
    ('אאודה עמדה מאחוריו ולא זזה ולא צעקה בכלל.', 'Aouda stood behind him and did not move and did not shout at all.'),
    ('פספרטו זחל על הרצפה אל הקרון הראשון.', 'Passepartout crawled on the floor to the first carriage in front.')),
  P(('הוא רצה להפריד בין הקרונות ובין המנוע.', 'He wanted to separate the carriages from the engine.'),
    ('הוא עשה את זה, והמנוע נסע קדימה בלי הקרונות.', 'He did it, and the engine went forward without the carriages.'),
    ('הקרונות עצרו לאט, ליד תחנה קטנה עם חיילים.', 'The carriages stopped slowly, beside a small station with soldiers.'),
    ('החיילים ירדו וירו, והאנשים ברחו בין הגבעות.', 'The soldiers came down and fired, and the men fled among the hills.')),
  P(('כשספרו את הנוסעים, שלושה לא היו שם, ואחד מהם פספרטו.', 'When they counted the passengers, three were not there, and one of them Passepartout.'),
    ('הקצין אמר: הם לקחו אותם, וזה קורה כאן לפעמים.', 'The officer said: they took them, and that happens here sometimes.'),
    ('פוג אמר: אני הולך לחפש אותם, ואני צריך שלושים אנשים.', 'Fogg said: I am going after them, and I need thirty men.'),
    ('הקצין נתן לו אנשים, והם יצאו אל השלג בלילה.', 'The officer gave him men, and they went out into the snow at night.'),
    ('אאודה עמדה בתחנה והסתכלה עליהם נעלמים בחושך.', 'Aouda stood at the station and looked at them disappearing in the dark.'))]),
 ('Fix Takes Charge', 'פיקס לוקח אחריות', [
  P(('הרכבת הבאה הייתה אמורה להגיע רק אחרי יומיים.', 'The next train was due to arrive only after two days.'),
    ('אאודה ישבה בתחנה כל הלילה ולא עצמה עין.', 'Aouda sat in the station all night and did not close an eye.'),
    ('פיקס נשאר איתה, והביא לה תה, ולא דיבר הרבה.', 'Fix stayed with her, and brought her tea, and did not speak much.'),
    ('בבוקר חזר המנוע לתחנה, אבל בלי אף אחד.', 'In the morning the engine came back to the station, but without anyone.')),
  P(('בצהריים ראו נקודות שחורות רחוקות על השלג הלבן.', 'At noon they saw far black dots on the white snow.'),
    ('אחרי שעה הבינו שאלה אנשים, והם הולכים לאט.', 'After an hour they understood that these are men, and they walk slowly.'),
    ('פוג הגיע ראשון, ואחריו פספרטו ושני הנוסעים.', 'Fogg arrived first, and after him Passepartout and the two passengers.'),
    ('כולם היו חיים, ורק אחד היה פצוע קל ברגל.', 'All of them were alive, and only one was lightly hurt in the leg.')),
  P(('אאודה רצה אליהם, ואחזה בידיים של פספרטו.', 'Aouda ran to them, and held Passepartout’s hands.'),
    ('פוג הסתכל בשעון ואמר: איחרנו עשרים שעות.', 'Fogg looked at the clock and said: we are twenty hours late.'),
    ('פספרטו אמר: אדוני, בגללי אתה מפסיד את הכול.', 'Passepartout said: sir, because of me you lose everything.'),
    ('פוג אמר: זאת לא אשמתך, ואל תדבר על זה יותר.', 'Fogg said: it is not your fault, and do not speak about it any more.')),
  P(('פיקס אמר: יש כאן איש עם עגלה קלה על שלג.', 'Fix said: there is a man here with a light sledge on snow.'),
    ('הוא אמר: יש לה מפרש, והרוח היום היא מהמערב.', 'He said: it has a sail, and the wind today is from the west.'),
    ('הוא אמר: אפשר להגיע לתחנה הבאה בכמה שעות.', 'He said: it is possible to reach the next station in a few hours.'),
    ('פוג הסתכל בו וראה שהוא באמת רוצה לעזור.', 'Fogg looked at him and saw that he really wants to help.'),
    ('הוא אמר: תודה, ואנחנו יוצאים בעוד עשר דקות.', 'He said: thank you, and we set out in ten minutes.'))]),
 ('Fogg Fights Ill Fortune', 'פוג נלחם במזל הרע', [
  P(('העגלה על השלג נסעה מהר מאוד עם הרוח.', 'The sledge on the snow travelled very fast with the wind.'),
    ('היא עברה שדות לבנים בלי דרך ובלי סימנים.', 'It passed white fields without a road and without signs.'),
    ('הקור היה נורא, וכולם התכסו בכל מה שהיה להם.', 'The cold was terrible, and everyone covered themselves with everything they had.'),
    ('אחרי חמש שעות הם ראו את הבתים של התחנה הבאה.', 'After five hours they saw the houses of the next station.')),
  P(('הם תפסו את הרכבת שם, וזה היה ממש ברגע האחרון.', 'They caught the train there, and it was really at the last moment.'),
    ('הרכבת נסעה מזרחה שני ימים בלי לעצור הרבה.', 'The train travelled east two days without stopping much.'),
    ('הם הגיעו לניו יורק בערב, בשעה שמונה וחמש.', 'They arrived in New York in the evening, at five past eight.'),
    ('הספינה לאנגליה יצאה מהנמל בשעה שמונה ורבע.', 'The ship to England left the port at a quarter past eight.')),
  P(('הם רצו אל הרציף, וראו אותה כבר בתוך המים.', 'They ran to the quay, and saw it already in the water.'),
    ('פספרטו עמד ליד עמוד ולא הצליח לומר מילה.', 'Passepartout stood beside a post and could not say a word.'),
    ('אאודה הסתכלה על פוג וחיכתה שהוא יגיד משהו.', 'Aouda looked at Fogg and waited for him to say something.'),
    ('פוג אמר בשקט: יש עוד ספינות, ואנחנו נמצא אחת.', 'Fogg said quietly: there are other ships, and we shall find one.')),
  P(('הם עברו בנמל ובדקו כל ספינה שעמדה שם.', 'They went through the port and checked every ship that stood there.'),
    ('רוב הספינות נסעו לדרום, או לא נסעו בימים הקרובים.', 'Most of the ships went south, or were not going in the coming days.'),
    ('בסוף מצאו ספינה קטנה שהובילה סחורה לצרפת.', 'In the end they found a small ship that carried goods to France.'),
    ('פוג דיבר עם המפקח והציע לו סכום גדול מאוד.', 'Fogg spoke with the master and offered him a very large sum.'),
    ('המפקח אמר: אני לא מוכר את הספינה שלי, אדוני.', 'The master said: I do not sell my ship, sir.'))]),
 ('Fogg Equal to the Occasion', 'פוג עומד במבחן', [
  P(('פוג אמר: אני לא קונה אותה, ואני שוכר אותה.', 'Fogg said: I do not buy it, and I hire it.'),
    ('הוא אמר: אני משלם לך אלפיים לכל אחד מאיתנו.', 'He said: I pay you two thousand for each one of us.'),
    ('המפקח הסתכל בו ושאל: ולאיזה מקום אתם רוצים ללכת?', 'The master looked at him and asked: and where do you want to go?'),
    ('פוג אמר: לאנגליה, ואם אי אפשר, אז לצרפת.', 'Fogg said: to England, and if it is not possible, then to France.')),
  P(('המפקח אמר: אני נוסע לצרפת, וזה מה שיש לי.', 'The master said: I am travelling to France, and that is what I have.'),
    ('הם עלו על הספינה, והיא יצאה מהנמל בבוקר.', 'They got on the ship, and it left the port in the morning.'),
    ('אחרי יום אחד פוג ירד למטה ודיבר עם הצוות.', 'After one day Fogg went below and spoke with the crew.'),
    ('הוא הציע להם כסף, והם הסכימו לעשות מה שהוא רוצה.', 'He offered them money, and they agreed to do what he wants.')),
  P(('הם סגרו את המפקח בחדר שלו ולא נגעו בו.', 'They shut the master in his room and did not touch him.'),
    ('פוג עצמו הוביל את הספינה צפונה, לכיוון אנגליה.', 'Fogg himself steered the ship north, in the direction of England.'),
    ('פספרטו אמר: אדוני, זה נראה כמו מעשה של גנב.', 'Passepartout said: sir, this looks like the deed of a thief.'),
    ('פוג אמר: אני משלם על הספינה יותר מהמחיר שלה.', 'Fogg said: I pay for the ship more than its price.')),
  P(('ביום השלישי בא איש מהצוות ואמר: אין יותר פחם.', 'On the third day a man from the crew came and said: there is no more coal.'),
    ('פוג אמר: אז נשרוף את מה שיש, וזה גם עץ.', 'Fogg said: then we shall burn what there is, and that is also wood.'),
    ('הוא הוציא את המפקח מהחדר ואמר לו: אני קונה.', 'He took the master out of the room and said to him: I am buying.'),
    ('הוא שילם לו על כל הספינה ואז הוסיף עוד קצת.', 'He paid him for the whole ship and then added a little more.'),
    ('המפקח לקח את הכסף ואמר: היא שלך, תעשה מה שתרצה.', 'The master took the money and said: it is yours, do what you want.'))]),
 ('Burning the Ship', 'שורפים את הספינה', [
  P(('פספרטו והצוות התחילו לשבור את מה שאפשר לשרוף.', 'Passepartout and the crew began to break what can be burned.'),
    ('הם לקחו כיסאות, ושולחנות, ומיטות, ודלתות.', 'They took chairs, and tables, and beds, and doors.'),
    ('הם שרפו הכול בתוך המנוע, שעה אחרי שעה.', 'They burned everything in the engine, hour after hour.'),
    ('הספינה נסעה מהר, ומאחוריה עלה עשן שחור וכבד.', 'The ship travelled fast, and behind it rose black, heavy smoke.')),
  P(('ביום הרביעי הם שברו את הקומה העליונה כולה.', 'On the fourth day they broke the whole upper deck.'),
    ('הספינה נראתה כמו קופסה שטוחה על פני המים.', 'The ship looked like a flat box on the face of the water.'),
    ('המפקח עמד והסתכל, וידיו על הראש שלו.', 'The master stood and looked, and his hands on his head.'),
    ('הוא אמר: היא הייתה יפה, והיום היא רק ברזל.', 'He said: it was beautiful, and today it is only iron.')),
  P(('פוג עמד על הסיפון ולא ישן כמעט בכלל.', 'Fogg stood on the deck and hardly slept at all.'),
    ('אאודה הביאה לו אוכל, והוא אכל בעמידה.', 'Aouda brought him food, and he ate standing.'),
    ('היא אמרה: אתה תיפול, ואז מי ינהג בספינה?', 'She said: you will fall, and then who will steer the ship?'),
    ('הוא אמר: עוד יומיים, ואז זה נגמר לכאן או לכאן.', 'He said: two more days, and then it ends one way or the other.')),
  P(('ביום השישי ראו חוף אפור וארוך מול הספינה.', 'On the sixth day they saw a grey, long shore in front of the ship.'),
    ('פספרטו צעק: זאת אנגליה! זאת באמת אנגליה!', 'Passepartout shouted: it is England! It really is England!'),
    ('הם נכנסו לנמל, והמנוע כבר כמעט לא נשמע.', 'They entered the port, and the engine could hardly be heard any more.'),
    ('פוג הסתכל בשעון ואמר: יש לנו עוד שש שעות.', 'Fogg looked at the clock and said: we have six hours left.'),
    ('הוא אמר: הרכבת ללונדון יוצאת בעוד ארבעים דקות.', 'He said: the train to London leaves in forty minutes.'))]),
 ('The Arrest', 'המעצר', [
  P(('הם ירדו לרציף ומיהרו אל תחנת הרכבת בעיר.', 'They went down to the quay and hurried to the railway station in the city.'),
    ('פספרטו רץ קדימה כדי לקנות ארבעה כרטיסים.', 'Passepartout ran ahead in order to buy four tickets.'),
    ('אאודה הלכה ליד פוג ולא הרפתה מהיד שלו.', 'Aouda walked beside Fogg and did not let go of his hand.'),
    ('פוג הלך בקצב רגיל, כאילו זה בוקר רגיל בלונדון.', 'Fogg walked at a normal pace, as if it is a normal morning in London.')),
  P(('בפתח התחנה עמד פיקס עם עוד שני שוטרים.', 'At the station entrance Fix stood with two more policemen.'),
    ('הוא הוציא נייר מהכיס ואמר: פיליאס פוג, אתה עצור.', 'He took a paper out of his pocket and said: Phileas Fogg, you are under arrest.'),
    ('הוא שם את היד על הכתף שלו וכולם עמדו רגע.', 'He put his hand on his shoulder and everyone stood a moment.'),
    ('פוג לא התנגד, ורק אמר: בשם מה, בבקשה?', 'Fogg did not resist, and only said: in the name of what, please?')),
  P(('פיקס אמר: בשם המלכה, בגלל הכסף שנלקח מהבנק.', 'Fix said: in the name of the queen, because of the money taken from the bank.'),
    ('פספרטו חזר עם הכרטיסים וראה את היד על הכתף.', 'Passepartout came back with the tickets and saw the hand on the shoulder.'),
    ('הוא זרק את הכרטיסים וקפץ על פיקס בשתי ידיים.', 'He threw down the tickets and jumped on Fix with both hands.'),
    ('השוטרים הפרידו ביניהם והכניסו את שניהם פנימה.', 'The policemen separated them and brought both of them inside.')),
  P(('הם סגרו את פוג בחדר קטן עם חלון גבוה אחד.', 'They shut Fogg in a small room with one high window.'),
    ('הוא ישב על הספסל, והוציא את השעון, והסתכל בו.', 'He sat on the bench, and took out the watch, and looked at it.'),
    ('הוא ראה את המחוגים עוברים על השעה של ההימור.', 'He saw the hands passing the hour of the bet.'),
    ('הוא לא אמר כלום, ולא זז, ולא הרים את הראש.', 'He said nothing, and did not move, and did not raise his head.'),
    ('בחוץ אאודה ופספרטו ישבו על המדרגות וחיכו.', 'Outside Aouda and Passepartout sat on the steps and waited.'))]),
 ('Fogg Innocent', 'פוג חף מפשע', [
  P(('אחרי חמישים דקות נפתחה הדלת בקול גדול.', 'After fifty minutes the door opened with a loud noise.'),
    ('פיקס נכנס לחדר, ופניו היו לבנות לגמרי.', 'Fix came into the room, and his face was completely white.'),
    ('הוא אמר: אדוני, אני מבקש סליחה, וזאת טעות.', 'He said: sir, I ask forgiveness, and it is a mistake.'),
    ('הוא אמר: תפסו את הגנב האמיתי לפני שלושה ימים.', 'He said: they caught the real thief three days ago.')),
  P(('פוג קם מהספסל ועמד מולו בלי לומר מילה.', 'Fogg got up from the bench and stood in front of him without saying a word.'),
    ('ואז הוא הרים את היד והכה אותו פעם אחת.', 'And then he raised his hand and struck him one time.'),
    ('פיקס נפל על הרצפה ולא אמר כלום ולא קם מהר.', 'Fix fell on the floor and said nothing and did not get up fast.'),
    ('פוג אמר: זה הכול, ועכשיו אני צריך רכבת ללונדון.', 'Fogg said: that is all, and now I need a train to London.')),
  P(('הרכבת שהם רצו לתפוס יצאה כבר לפני שעה.', 'The train that they wanted to catch had left an hour ago already.'),
    ('פוג שכר רכבת מיוחדת ושילם עליה סכום גדול.', 'Fogg hired a special train and paid a large sum for it.'),
    ('הם נסעו מהר מאוד, אבל לא מספיק מהר.', 'They travelled very fast, but not fast enough.'),
    ('הם הגיעו ללונדון חמש דקות אחרי השעה שנקבעה.', 'They reached London five minutes after the hour that was fixed.')),
  P(('פוג ירד מהרכבת ולא רץ ולא מיהר בכלל.', 'Fogg got off the train and did not run and did not hurry at all.'),
    ('הוא הלך הביתה ברגל, כמו בכל יום רגיל.', 'He walked home on foot, as on every ordinary day.'),
    ('אאודה ופספרטו הלכו אחריו ולא דיברו כלל.', 'Aouda and Passepartout walked after him and did not speak at all.'),
    ('בבית הוא עלה לחדר שלו וסגר את הדלת בשקט.', 'At home he went up to his room and closed the door quietly.'),
    ('הוא הפסיד עשרים אלף, ואת החצי השני הוא הוציא בדרך.', 'He lost twenty thousand, and the second half he spent on the way.'))]),
 ('Fogg Wins Happiness', 'פוג זוכה באושר', [
  P(('כל יום ראשון הוא ישב בחדר שלו ולא ירד למטה.', 'All that Sunday he sat in his room and did not come down.'),
    ('פספרטו עמד מאחורי הדלת ולא העז לדפוק בה.', 'Passepartout stood behind the door and did not dare to knock on it.'),
    ('אאודה ישבה למטה בסלון ולא אכלה שום דבר.', 'Aouda sat downstairs in the sitting room and ate nothing.'),
    ('בערב פוג ירד וביקש ממנה לבוא לחדר שלו.', 'In the evening Fogg came down and asked her to come to his room.')),
  P(('הוא אמר לה: הבאתי אותך לכאן, וזה היה נכון.', 'He said to her: I brought you here, and that was right.'),
    ('הוא אמר: אבל היום אין לי כלום, ואני איש עני.', 'He said: but today I have nothing, and I am a poor man.'),
    ('היא אמרה: אני יודעת, ואני לא ביקשתי כסף.', 'She said: I know, and I did not ask for money.'),
    ('היא אמרה: אני מבקשת רק דבר אחד, ואתה יודע מה.', 'She said: I ask only one thing, and you know what.')),
  P(('הוא הסתכל בה זמן ארוך ואז אמר: אני אוהב אותך.', 'He looked at her a long time and then said: I love you.'),
    ('הוא אמר: אני נשבע שזה נכון מהיום בהודו.', 'He said: I swear that it is true from the day in India.'),
    ('הם קראו לפספרטו ואמרו לו ללכת אל הכומר.', 'They called Passepartout and told him to go to the priest.'),
    ('פספרטו רץ מהר יותר משהוא רץ בכל הנסיעה.', 'Passepartout ran faster than he had run in the whole journey.')),
  P(('אחרי חמש דקות הוא חזר לבית וצעק מהמדרגות.', 'After five minutes he came back to the house and shouted from the stairs.'),
    ('הוא צעק: אדוני! היום הוא לא יום ראשון!', 'He shouted: sir! Today is not Sunday!'),
    ('הוא צעק: היום שבת, ואנחנו הרווחנו יום שלם!', 'He shouted: today is Saturday, and we gained a whole day!'),
    ('פוג הבין הכול ברגע אחד: הם נסעו מזרחה כל הזמן.', 'Fogg understood everything in one moment: they travelled east the whole time.'),
    ('כל יום הם ראו את השמש קצת מוקדם יותר.', 'Every day they saw the sun a little earlier.'),
    ('שמונים פעם קצת מוקדם יותר זה יום אחד שלם.', 'Eighty times a little earlier is one whole day.')),
  P(('הוא רץ למועדון והגיע לשם בשמונה ארבעים וחמש.', 'He ran to the club and arrived there at eight forty-five.'),
    ('החברים ישבו סביב השולחן וספרו את השניות.', 'The friends sat around the table and counted the seconds.'),
    ('הדלת נפתחה, ופוג עמד שם, ואמר: הנני, אדונים.', 'The door opened, and Fogg stood there, and said: here I am, gentlemen.'),
    ('הוא זכה בהימור, וקיבל את הכסף בחזרה באותו ערב.', 'He won the bet, and received the money back that evening.'),
    ('הוא נתן את רוב הרווח לפספרטו ולפיקס בלי לומר למה.', 'He gave most of the gain to Passepartout and to Fix without saying why.'),
    ('הוא הרוויח מהנסיעה הזאת רק דבר אחד, והוא אאודה.', 'He gained from this journey only one thing, and it is Aouda.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('atw80', {'en': 'Around the World in 80 Days',
                                    'he': 'מסביב לעולם בשמונים יום'}, 'intermediate',
                          CHAPTERS, unit='Chapter', unit_he='פרק', shelf=10, meta=META))
