#!/usr/bin/env python3
"""הרפתקאות טום סוייר — Mark Twain, retold in modern Hebrew, graded to intermediate.

The Hebrew twin of pipeline/book_tomsawyer.py, chapter for chapter. Twain died in 1910 and the
book is public domain; this is a retelling from the plot rather than a translation.

WHY IT CLOSES THE INTERMEDIATE SHELF. Everything before it happens somewhere far away — an
island, a voyage, a forest of talking animals. This one happens in a small town where people go
to school, sit in class, get bored, fall out with each other and make up. That is where a
learner's own Hebrew has to work, and it is the hardest vocabulary to come by from adventure
stories: the words for ordinary weeks.

Deliberately unpointed; the vowels are looked up at ingest. The names are declared in
pipeline/he_curated.py.

Run:  python3 pipeline/he_book_tomsawyer.py --lang he            # check
      python3 pipeline/he_book_tomsawyer.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'The Adventures of Tom Sawyer', 'author': 'Mark Twain', 'year': '1876',
        'status': 'public domain'}

CHAPTERS = [
 ('Tom and Aunt Polly', 'טום ודודה פולי', [
  P(('טום! טום!', 'Tom! Tom!'),
    ('אף אחד לא ענה.', 'No one answered.'),
    ('דודה פולי הורידה את המשקפיים על האף והסתכלה סביב החדר.', 'Aunt Polly lowered her glasses on her nose and looked around the room.'),
    ('ואז הרימה אותן על הראש והסתכלה מתחת למשקפיים.', 'And then she pushed them up on her head and looked from under them.'),
    ('היא אף פעם לא הסתכלה על ילד קטן דרך המשקפיים, המשקפיים היו ליופי.', 'She never looked at a small boy through the glasses, the glasses were for show.'),
    ('היא אמרה: אם אני תופסת אותך, אני...', 'She said: if I catch you, I...'),
    ('והיא לא סיימה את המשפט, כי היא הייתה כפופה מתחת למיטה עם המטאטא.', 'And she did not finish the sentence, because she was bent under the bed with the broom.')),
  P(('מתחת למיטה יצא רק חתול.', 'From under the bed came out only a cat.'),
    ('דודה פולי הלכה לדלת, עמדה בגינה, וצעקה: טום!', 'Aunt Polly went to the door, stood in the garden, and shouted: Tom!'),
    ('והיא שמעה קול מאחוריה, הסתובבה, ותפסה ילד בצווארון.', 'And she heard a sound behind her, turned, and caught a boy by the collar.'),
    ('היא אמרה: כאן היית! במזווה! ומה זה על הפה שלך?', 'She said: here you were! In the pantry! And what is that on your mouth?'),
    ('טום אמר: אני לא יודע, דודה.', 'Tom said: I do not know, aunt.'),
    ('היא אמרה: אני יודעת, ריבה, אמרתי לך מאה פעם.', 'She said: I know, jam, I told you a hundred times.'),
    ('והיא הרימה את המקל.', 'And she raised the stick.')),
  P(('טום אמר: דודה! תסתכלי מאחורייך!', 'Tom said: aunt! Look behind you!'),
    ('דודה פולי הסתובבה, ובאותו רגע טום קפץ מעל הגדר ונעלם.', 'Aunt Polly turned, and in that moment Tom jumped over the fence and vanished.'),
    ('הדודה עמדה רגע, ואז צחקה צחוק קטן.', 'The aunt stood a moment, and then gave a small laugh.'),
    ('היא אמרה לעצמה: הילד הזה, כל פעם אותו תרגיל, וכל פעם זה עובד עליי.', 'She said to herself: this boy, every time the same trick, and every time it works on me.'),
    ('הוא הבן של אחותי שמתה, ואני לא יכולה להכות אותו, ולא יכולה לא להכות אותו.', 'He is the son of my sister who died, and I cannot beat him, and cannot not beat him.'),
    ('מחר שבת, ואני אתן לו לעבוד, והוא שונא עבודה יותר מכל דבר.', 'Tomorrow is Saturday, and I will make him work, and he hates work more than anything.')),
  P(('טום חזר הביתה בערב, מאוחר.', 'Tom came home in the evening, late.'),
    ('הוא היה עייף מהמשחקים, הבגדים שלו מלוכלכים, ועל הפנים שלו סימן.', 'He was tired from the games, his clothes dirty, and on his face a scratch.'),
    ('האח הקטן שלו, שהיה שקט ממנו, ישב ליד השולחן בשקט.', 'His little brother, who was quieter than him, sat by the table quietly.'),
    ('דודה פולי שאלה: טום, היה חם היום, נכון? לא הלכת לשחות?', 'Aunt Polly asked: Tom, it was hot today, right? You did not go swimming?'),
    ('טום אמר: לא, דודה.', 'Tom said: no, aunt.'),
    ('היא נגעה בחולצה שלו, היא הייתה יבשה.', 'She touched his shirt, it was dry.'),
    ('אבל האח אמר: אבל החוט שתפרת בו את הצווארון היה לבן, ועכשיו הוא שחור.', 'But the brother said: but the thread you sewed the collar with was white, and now it is black.'),
    ('טום קם, ואמר לאח שלו כשיצא: אתה תשלם על זה.', 'Tom got up, and said to his brother as he went out: you will pay for this.'))]),

 ('The Fence', 'הגדר', [
  P(('הגיעה שבת, השמש זרחה, וכל הילדים בחוץ שיחקו.', 'Saturday came, the sun shone, and all the boys outside played.'),
    ('וטום עמד מול גדר ארוכה, ביד שלו מברשת ודלי צבע לבן.', 'And Tom stood in front of a long fence, in his hand a brush and a bucket of white paint.'),
    ('הגדר הייתה באורך שלושים מטר, וגבוהה, וכולה צריכה צבע.', 'The fence was thirty metres long, and high, and all of it needed paint.'),
    ('הוא צבע קו אחד, הסתכל על מה שנשאר, והוא ישב על האדמה.', 'He painted one line, looked at what remained, and sat on the ground.'),
    ('החיים נהיו בלי טעם.', 'Life had become without taste.')),
  P(('הוא חשב לשלם לילד שיצבע במקומו, אבל היו לו רק אבן, חוט וגולה.', 'He thought of paying a boy to paint instead of him, but he had only a stone, a string and a marble.'),
    ('וברגע הזה בא לו רעיון, רעיון גדול.', 'And in that moment an idea came to him, a great idea.'),
    ('הוא לקח את המברשת, וחזר לצבוע, שקט ומאושר.', 'He took the brush, and went back to painting, calm and happy.'),
    ('ואחרי זמן קצר עבר בן, ביד שלו תפוח, ומשחק שהוא ספינה.', 'And a little later Ben passed, in his hand an apple, playing that he was a ship.'),
    ('בן אמר: היי טום, מה, תפסו אותך? אתה צריך לעבוד?', 'Ben said: hey Tom, what, they caught you? You have to work?'),
    ('טום לא ענה, הוא המשיך לצבוע, זז קצת אחורה, והסתכל על הגדר כמו אמן.', 'Tom did not answer, he kept painting, stepped back a little, and looked at the fence like an artist.')),
  P(('טום אמר: עבודה? זאת לא עבודה, זה לצבוע גדר.', 'Tom said: work? This is not work, this is painting a fence.'),
    ('והוא אמר: כמה ילדים אתה חושב יכולים לצבוע גדר? אחד מאלף?', 'And he said: how many boys do you think can paint a fence? One in a thousand?'),
    ('בן עצר, הסתכל על הגדר, והפסיק לאכול את התפוח.', 'Ben stopped, looked at the fence, and stopped eating the apple.'),
    ('הוא אמר: טום, תן לי לצבוע קצת.', 'He said: Tom, let me paint a little.'),
    ('טום אמר: לא, דודה פולי מאוד אוהבת את הגדר הזאת, לא כל אחד יכול לצבוע אותה.', 'Tom said: no, Aunt Polly loves this fence very much, not everyone can paint it.'),
    ('בן אמר: אני אתן לך את התפוח.', 'Ben said: I will give you the apple.'),
    ('טום חשב, ואמר: טוב, אבל תיזהר.', 'Tom thought, and said: fine, but be careful.')),
  P(('וטום ישב בצל, אכל את התפוח, ובן צבע בשמש, מאושר.', 'And Tom sat in the shade, ate the apple, and Ben painted in the sun, happy.'),
    ('ואחרי בן בא בילי, ושילם עפיפון.', 'And after Ben came Billy, and paid a kite.'),
    ("ואחרי בילי בא ילד אחר, ושילם עכבר מת על חוט.", 'And after Billy came Johnny, and paid a dead mouse on a string.'),
    ('ובערב, הגדר הייתה צבועה שלוש פעמים, וטום היה עשיר.', 'And in the evening, the fence was painted three times, and Tom was rich.'),
    ('שתים עשרה גולות, מפתח, חתיכת גיר, וחתול עם עין אחת.', 'Twelve marbles, a key, a piece of chalk, and a cat with one eye.'),
    ('וטום למד חוק גדול על אנשים.', 'And Tom learned a big law about people.'),
    ('כדי שמישהו ירצה דבר, תעשה אותו קשה.', 'To make someone want a thing, make it hard.'))]),

 ('The New Girl', 'הילדה החדשה', [
  P(('טום הלך לדודה פולי ואמר: סיימתי את הגדר.', 'Tom went to Aunt Polly and said: I finished the fence.'),
    ('היא לא האמינה, יצאה לראות, וראתה את הגדר לבנה כמו שלג.', 'She did not believe, went out to see, and saw the fence white as snow.'),
    ('היא אמרה: טום, אתה יכול לעבוד כשאתה רוצה, אבל אתה רוצה רק לעיתים רחוקות.', 'She said: Tom, you can work when you want, but you want only rarely.'),
    ('והיא נתנה לו תפוח, ושיעור על הערך של העבודה.', 'And she gave him an apple, and a lesson on the value of work.'),
    ('טום לקח את התפוח, גנב עוגה בזמן שהיא דיברה, והוא יצא.', 'Tom took the apple, stole a cake while she talked, and went out.')),
  P(('הוא הלך ברחוב, ועבר ליד הבית של השופט.', 'He walked down the street, and passed by the judge’s house.'),
    ('ובגינה הוא ראה ילדה.', 'And in the garden he saw a girl.'),
    ('ילדה חדשה, שהוא לא ראה קודם, השיער שלה צהוב וקלוע, והשמלה שלה לבנה.', 'A new girl, whom he had not seen before, her hair yellow and braided, and her dress white.'),
    ('וטום, שאהב ילדה אחרת חודשים, שכח אותה ברגע.', 'And Tom, who had loved another girl for months, forgot her in a moment.'),
    ('הוא עמד ליד הגדר, והתחיל לעשות תרגילים.', 'He stood by the fence, and began doing tricks.'),
    ('הוא עמד על הידיים, הלך על הגדר, וזרק את עצמו על האדמה.', 'He stood on his hands, walked on the fence, and threw himself on the ground.'),
    ('והילדה לא הסתכלה עליו.', 'And the girl did not look at him.')),
  P(('ואז, כשהיא נכנסה הביתה, היא עצרה רגע.', 'And then, as she went into the house, she stopped a moment.'),
    ('וזרקה פרח מעל הגדר, ונכנסה.', 'And threw a flower over the fence, and went in.'),
    ('טום רץ לפרח, עמד לידו, ועשה כאילו הוא מחפש משהו.', 'Tom ran to the flower, stood beside it, and acted as if he was looking for something.'),
    ('ואז הרים אותו עם האצבעות של הרגל, שם אותו בכיס, והלך.', 'And then he picked it up with his toes, put it in his pocket, and went.'),
    ('והוא חזר בערב, ועמד מול הבית עד שבא הלילה.', 'And he came back in the evening, and stood in front of the house until night came.'),
    ('ואז שכב מתחת לחלון, ודמיין שהוא מת, והיא בוכה עליו.', 'And then he lay under the window, and imagined that he was dead, and she was crying over him.')),
  P(('ופתאום החלון נפתח, והוא יצא ממנו דלי מים.', 'And suddenly the window opened, and out of it came a bucket of water.'),
    ('הוא נפל על כל טום.', 'It fell on all of Tom.'),
    ('הוא קם, ניער את עצמו, ורץ הביתה רטוב.', 'He got up, shook himself, and ran home wet.'),
    ('ובבית, האח שלו אמר: טום, למה אתה רטוב?', 'And at home, his brother said: Tom, why are you wet?'),
    ('טום לא ענה, אבל בלילה הוא זרק על האח שלו אבנים קטנות בשינה.', 'Tom did not answer, but at night he threw small stones at his brother in his sleep.'),
    ('והרגיש שהוא החזיר לו על החוט השחור.', 'And felt that he had paid him back for the black thread.'))]),

 ('Sunday School', 'בית הספר של יום ראשון', [
  P(('ביום ראשון דודה פולי הלבישה את טום בבגדים הכי טובים שלו.', 'On Sunday Aunt Polly dressed Tom in his best clothes.'),
    ('חליפה צרה, נעליים שכואבות, וצווארון שחונק.', 'A tight suit, shoes that hurt, and a collar that chokes.'),
    ('והיא אמרה: לך לבית הספר של יום ראשון, ואז תלמד פסוקים.', 'And she said: go to Sunday school, and learn verses.'),
    ('בבית הספר של יום ראשון כל ילד למד בעל פה שני פסוקים, וקיבל כרטיס כחול.', 'At Sunday school every child learned two verses by heart, and got a blue ticket.'),
    ('ועשרה כרטיסים כחולים שווים כרטיס אדום, ועשרה אדומים שווים צהוב.', 'And ten blue tickets were worth a red ticket, and ten red were worth a yellow.'),
    ('ועל עשרה צהובים, נותנים לך ספר קדוש, לפני כולם.', 'And for ten yellow, they give you a holy book, in front of everyone.')),
  P(('טום לא ידע אף פסוק.', 'Tom did not know a single verse.'),
    ('אבל היו לו שתים עשרה גולות, מפתח, וחתול עם עין אחת.', 'But he had twelve marbles, a key, and a cat with one eye.'),
    ('הוא עמד ליד הדלת, והתחיל לקנות כרטיסים מהילדים.', 'He stood by the door, and began buying tickets from the boys.'),
    ('כרטיס כחול בגולה, אדום במפתח, וצהוב בחתול.', 'A blue ticket for a marble, a red for the key, and a yellow for the cat.'),
    ('וכשנכנס, היו לו עשרה כרטיסים צהובים.', 'And when he went in, he had ten yellow tickets.'),
    ('לאף אחד בכל בית הספר לא היו כל כך הרבה.', 'No one in the whole school had so many.')),
  P(('ובדיוק ביום הזה היה אורח חשוב: השופט.', 'And on that very day there was an important guest: the judge.'),
    ('ואיתו אשתו, והבת שלו, הילדה עם השיער הצהוב.', 'And with him his wife, and his daughter, the girl with the yellow hair.'),
    ('המורה אמר: למי יש עשרה כרטיסים צהובים?', 'The teacher said: who has ten yellow tickets?'),
    ('טום קם, הלך קדימה, ונתן את הכרטיסים.', 'Tom got up, walked forward, and gave the tickets.'),
    ('המורה לא האמין, וכל הילדים שמכרו לו את הכרטיסים שלהם הבינו, ונשכו את השפתיים.', 'The teacher did not believe, and all the boys who had sold him their tickets understood, and bit their lips.'),
    ('והשופט שם את היד על הראש של טום, ואמר: ילד מצוין.', 'And the judge put his hand on Tom’s head, and said: an excellent boy.'),
    ('ובקי, הבת של השופט, הסתכלה עליו.', 'And Becky, the judge’s daughter, looked at him.')),
  P(('השופט אמר: ילד, בטח אתה יודע את השמות של שנים עשר התלמידים.', 'The judge said: boy, surely you know the names of the twelve disciples.'),
    ('תגיד לנו שניים מהם.', 'Tell us two of them.'),
    ('טום נהיה אדום, והתחיל לחשוב, ולא בא לו אף שם.', 'Tom went red, and began to think, and not one name came to him.'),
    ('המורה אמר: נו, טום, השניים הראשונים.', 'The teacher said: come on, Tom, the first two.'),
    ('טום אמר: דוד... וגוליית!', 'Tom said: David... and Goliath!'),
    ('וכאן אנחנו סוגרים את הווילון על הסצנה הזאת, מרחמים על טום.', 'And here we close the curtain on this scene, out of pity for Tom.'))]),

 ('The Beetle and the Dog', 'החיפושית והכלב', [
  P(('אחרי בית הספר של יום ראשון יש כנסייה, והכנסייה ארוכה מבית הספר.', 'After Sunday school there is church, and church is longer than school.'),
    ('הכומר עמד, והתחיל לדבר, והקול שלו עולה ויורד כמו הגלים.', 'The preacher stood, and began to speak, and his voice rising and falling like the waves.'),
    ('טום ספר את הדפים, ספר את האנשים, ספר את הזבובים על החלון.', 'Tom counted the pages, counted the people, counted the flies on the window.'),
    ('ואז נזכר במשהו בכיס שלו.', 'And then he remembered something in his pocket.'),
    ('חיפושית גדולה, שחורה, עם לסתות כמו מלקחיים, שהוא שם בקופסה.', 'A big beetle, black, with jaws like pincers, that he kept in a box.')),
  P(('הוא פתח את הקופסה, והחיפושית נשכה לו את האצבע קודם כול.', 'He opened the box, and the beetle bit his finger first of all.'),
    ('טום זרק אותה, והיא נפלה במעבר, על הגב, והרגליים באוויר.', 'Tom threw it, and it fell in the aisle, on its back, and its legs in the air.'),
    ('והאנשים סביב התחילו להסתכל עליה במקום על הכומר.', 'And the people around began looking at it instead of at the preacher.'),
    ('ואז בא כלב.', 'And then came a dog.'),
    ('כלב קטן, שנכנס לכנסייה מהדלת הפתוחה, וראה את החיפושית.', 'A small dog, that came into the church through the open door, and saw the beetle.'),
    ('הוא התקרב אליה, הריח אותה, הסתובב סביבה, והוא ישב להסתכל עליה.', 'It approached it, sniffed it, circled it, and sat down to look at it.')),
  P(('ואז החליט לאכול אותה.', 'And then it decided to eat it.'),
    ('הוא פתח את הפה, והחיפושית נשכה אותו בלסתות שלה.', 'It opened its mouth, and the beetle bit it with its jaws.'),
    ('הכלב צעק, קפץ, והתחיל לרוץ במעבר ולצעוק.', 'The dog yelped, jumped, and began running down the aisle and howling.'),
    ('והחיפושית תלויה על האף שלו.', 'And the beetle hanging on its nose.'),
    ('הוא רץ ימינה, ורץ שמאלה, וקפץ על הספסלים, ועל הברכיים של גברת.', 'It ran right, and ran left, and jumped on the benches, and on a lady’s knees.'),
    ('וכל הכנסייה צוחקת, ואף אחד לא יכול להפסיק.', 'And the whole church laughing, and no one could stop.'),
    ('והכומר עומד, הפנים שלו אדומות, ממשיך לדבר, ואף אחד לא שומע אותו.', 'And the preacher standing, his face red, going on speaking, and no one hearing him.')),
  P(('בסוף בעל הכלב הרים אותו, וזרק אותו מהחלון.', 'In the end the dog’s owner picked it up, and threw it out the window.'),
    ('ושמעו אותו צועק כשהוא הולך רחוק ברחוב.', 'And they heard it howling as it went off down the street.'),
    ('טום חזר הביתה מאושר.', 'Tom went home happy.'),
    ('הוא אמר בלב: הכנסייה לא רעה, אם יש בה קצת שינוי.', 'He said to himself: church is not bad, if there is a little change in it.'),
    ('אבל הוא היה עצוב על דבר אחד.', 'But he was sad about one thing.'),
    ('הכלב לקח את החיפושית איתו.', 'The dog took the beetle with it.'))]),

 ('Huck Finn', 'האק', [
  P(('ביום שני טום התעורר אומלל.', 'On Monday Tom woke up miserable.'),
    ('יום שני זה בית ספר, ובית ספר זה שבוע שלם של כלא.', 'Monday means school, and school means a whole week of prison.'),
    ('הוא חשב לעשות את עצמו חולה, בדק את עצמו: כלום.', 'He thought of pretending to be ill, examined himself: nothing.'),
    ('ואז מצא שן שזזה, והחליט להשתמש בה.', 'And then found a loose tooth, and decided to use it.'),
    ('אבל נזכר שאם ידבר על השן, הדודה תוציא אותה.', 'But remembered that if he talked about the tooth, the aunt would pull it out.'),
    ('אז התחיל להשמיע קולות של כאב, ולהגיד שהאצבע של הרגל כואבת לו, ושהוא הולך למות.', 'So he began to groan, and to say that his toe hurt, and that he was going to die.')),
  P(('דודה פולי באה בריצה, הסתכלה על האצבע, ואמרה: האצבע שלך? מה יש בה?', 'Aunt Polly came running, looked at the toe, and said: your toe? What is wrong with it?'),
    ('והיא צחקה, ואז ראתה את השן, והוציאה אותה בחוט ברגע.', 'And she laughed, and then saw the tooth, and pulled it out with a thread in a moment.'),
    ('ושלחה אותו לבית הספר.', 'And sent him to school.'),
    ('אבל בדרך טום גילה שלשן שיצאה יש יתרונות.', 'But on the way Tom discovered that a pulled tooth has advantages.'),
    ('הוא יכול לירוק דרך החור בצורה חדשה, וכל הילדים רצו לנסות.', 'He could spit through the hole in a new way, and all the boys wanted to try.')),
  P(('ומול בית הספר הוא ראה את האק.', 'And in front of the school he saw Huck.'),
    ('האק היה הבן של השיכור של הכפר, ולא הייתה לו אימא, ולא היה לו בית.', 'Huck was the son of the village drunk, and he had no mother, and no house.'),
    ('הוא ישן בחביות כשהיה חורף, ועל המדרגות כשהיה קיץ.', 'He slept in barrels when it was winter, and on the steps when it was summer.'),
    ('והבגדים שלו היו בגדים של גברים גדולים, עם חורים, והמכנסיים שלו קשורים בחבל.', 'And his clothes were clothes of grown men, torn, and his trousers held up with a rope.'),
    ('כל האימהות בכפר שנאו אותו, כי הוא לא הולך לבית ספר ולא לכנסייה.', 'All the mothers in the village hated him, because he goes neither to school nor to church.'),
    ('וכל הילדים בכפר קינאו בו, מאותה סיבה.', 'And all the boys in the village envied him, for the same reason.'),
    ('ואסור היה לכולם לשחק איתו, אז טום שיחק איתו כל פעם שיכול.', 'And everyone was forbidden to play with him, so Tom played with him every time he could.')),
  P(('טום אמר: מה יש לך, האק?', 'Tom said: what have you got, Huck?'),
    ('האק אמר: חתול מת.', 'Huck said: a dead cat.'),
    ('טום אמר: ומה עושים עם חתול מת?', 'Tom said: and what do you do with a dead cat?'),
    ('האק אמר: הוא מרפא יבלות, לוקחים אותו לבית הקברות בחצות, כשקוברים איש רע.', 'Huck said: it cures warts, you take it to the graveyard at midnight, when they bury a wicked man.'),
    ('ובאים השדים לקחת את המת, וזורקים את החתול אחרי השדים, והיבלות הולכות איתם.', 'And the devils come to take the dead man, and you throw the cat after them, and the warts go with them.'),
    ('טום אמר: זה עובד?', 'Tom said: does it work?'),
    ('האק אמר: בטח, והלילה קוברים אחד, אתה בא?', 'Huck said: sure, and tonight they bury one, are you coming?'),
    ('טום אמר: אני בא.', 'Tom said: I am coming.'),
    ('והם קבעו: האק יעשה קול של חתול מתחת לחלון של טום בחצות.', 'And they agreed: Huck would make a cat’s sound under Tom’s window at midnight.'))]),

 ('Tom and Becky', 'טום ובקי', [
  P(('בבית הספר טום הגיע מאוחר, כי הוא עצר לדבר עם האק.', 'At school Tom arrived late, because he stopped to talk with Huck.'),
    ('המורה אמר: טום סוייר! למה איחרת?', 'The teacher said: Tom Sawyer! Why are you late?'),
    ('טום עמד לשקר, אבל הוא ראה משהו.', 'Tom was about to lie, but he saw something.'),
    ('הילדה עם השיער הצהוב, יושבת, ולידה המקום היחיד הריק בצד של הבנות.', 'The girl with the yellow hair, sitting, and beside her the only empty seat on the girls’ side.'),
    ('אז הוא אמר: עצרתי לדבר עם האק.', 'So he said: I stopped to talk with Huck.'),
    ('המורה לא האמין לאוזניים שלו, הכה אותו במקל, ואמר: לך שב עם הבנות!', 'The teacher did not believe his ears, beat him with the stick, and said: go and sit with the girls!'),
    ('וזה בדיוק מה שטום רצה.', 'And that was exactly what Tom wanted.')),
  P(('הוא ישב לידה, והיא זזה ממנו, ושמה את הראש בספר.', 'He sat beside her, and she moved away from him, and put her head in her book.'),
    ('טום שם לפניה אפרסק.', 'Tom put a peach in front of her.'),
    ('היא דחפה אותו, הוא החזיר אותו, היא דחפה אותו, אבל לאט יותר, הוא החזיר אותו, היא לקחה אותו.', 'She pushed it away, he put it back, she pushed it away, but slower, he put it back, she took it.'),
    ('ואז הוא צייר על הלוח בית, והיא הסתכלה.', 'And then he drew a house on his slate, and she looked.'),
    ('היא לחשה: תצייר איש.', 'She whispered: draw a man.'),
    ('הוא צייר איש גבוה מהבית.', 'He drew a man taller than the house.'),
    ('היא לחשה: יפה, ותצייר אותי.', 'She whispered: pretty, and draw me.'),
    ('הוא צייר עיגול, ובו שני מקלות, והשם שלה בקי, והיא הייתה מרוצה.', 'He drew a circle, and in it two sticks, and her name Becky, and she was pleased.')),
  P(('ואז טום כתב על הלוח משהו, וכיסה אותו ביד.', 'And then Tom wrote something on the slate, and covered it with his hand.'),
    ('היא אמרה: תראה לי.', 'She said: show me.'),
    ('הוא אמר: לא.', 'He said: no.'),
    ('היא אמרה: תראה לי, אני לא אגיד לאף אחד.', 'She said: show me, I will not tell anyone.'),
    ('הוא הרים את היד, והיה כתוב: אני אוהב אותך.', 'He lifted his hand, and it was written: I love you.'),
    ('היא הכתה לו על היד, והפנים שלה נהיו אדומות, אבל היא הייתה מרוצה.', 'She slapped his hand, and her face went red, but she was pleased.'),
    ('וברגע הזה יד גדולה תפסה את טום באוזן, הרימה אותו, ולקחה אותו למקום שלו.', 'And in that moment a big hand took Tom by the ear, lifted him, and took him to his place.'),
    ('המורה.', 'The teacher.')),
  P(('בצהריים טום ובקי נפגשו מאחורי בית הספר.', 'At noon Tom and Becky met behind the school.'),
    ('טום אמר: בקי, את אוהבת עכברים?', 'Tom said: Becky, do you like mice?'),
    ('היא אמרה: לא! אני שונאת אותם!', 'She said: no! I hate them!'),
    ('הוא אמר: אני מתכוון מתים, כאלה שמסובבים על חוט.', 'He said: I mean dead ones, the kind you swing on a string.'),
    ('היא אמרה: אני אוהבת מסטיק יותר.', 'She said: I like chewing gum better.'),
    ('והוא הוציא מסטיק, והם חילקו אותו, ולעסו אותו בתורות.', 'And he took out gum, and they shared it, and chewed it in turns.'),
    ('וטום אמר: בקי, את רוצה שנהיה חתן וכלה?', 'And Tom said: Becky, do you want us to be engaged?'),
    ('היא אמרה: מה זה?', 'She said: what is that?'),
    ('הוא אמר: את אומרת לי שאת אוהבת אותי, ואנחנו מתנשקים, וזהו, את לא מתחתנת עם אף אחד אחר.', 'He said: you tell me you love me, and we kiss, and that is it, you marry no one else.'),
    ('והיא לחשה אני אוהבת אותך, והוא נישק אותה, והם היו מאורסים.', 'And she whispered I love you, and he kissed her, and they were engaged.'))]),

 ('At Midnight in the Graveyard', 'בחצות בבית הקברות', [
  P(('אבל האירוסים לא החזיקו חצי שעה.', 'But the engagement did not last half an hour.'),
    ('טום אמר: זה יפה יותר מהפעם הראשונה, כשהייתי מאורס לילדה אחרת.', 'Tom said: this is nicer than the first time, when I was engaged to another girl.'),
    ('בקי קמה, ואמרה: אחרת? אז אני לא הראשונה?', 'Becky got up, and said: another? So I am not the first?'),
    ('והיא בכתה, ולא רצתה לדבר איתו, ויצאה.', 'And she cried, and did not want to talk with him, and left.'),
    ('וטום ישב לבד, והרגיש שהעולם עשה לו עוול.', 'And Tom sat alone, and felt that the world had wronged him.'),
    ('הוא אמר: אני אמות, ואז היא תצטער.', 'He said: I will die, and then she will be sorry.'),
    ('והלך הביתה, וישן מוקדם, וחיכה לחצות.', 'And went home, and slept early, and waited for midnight.')),
  P(('בחצות הוא שמע קול של חתול מתחת לחלון.', 'At midnight he heard a cat’s sound under the window.'),
    ('הוא ירד מהחלון לגג, ומהגג לאדמה, והאק חיכה לו עם החתול המת.', 'He climbed from the window to the roof, and from the roof to the ground, and Huck waited for him with the dead cat.'),
    ('הם הלכו לבית הקברות, על הגבעה, לאט.', 'They walked to the graveyard, on the hill, slowly.'),
    ('בית הקברות היה ישן, הקברים נטויים, והגדר שבורה.', 'The graveyard was old, the graves leaning, and the fence broken.'),
    ('והרוח מזיזה את העצים, והירח פעם יוצא ופעם נעלם.', 'And the wind moving the trees, and the moon now coming out and now vanishing.'),
    ('הם התחבאו מאחורי שלושה עצים, ליד הקבר החדש, וחיכו.', 'They hid behind three trees, by the new grave, and waited.')),
  P(('טום לחש: האק, אתה חושב שהמתים אוהבים שאנחנו באים לכאן?', 'Tom whispered: Huck, do you think the dead like us coming here?'),
    ('האק לחש: אני לא יודע, תשתוק.', 'Huck whispered: I do not know, be quiet.'),
    ('ואז הם שמעו קול.', 'And then they heard a sound.'),
    ('רגליים, ודיבור, ואור של פנס בא מרחוק.', 'Feet, and talk, and the light of a lantern coming from afar.'),
    ('האק לחש: השדים! שלושה!', 'Huck whispered: the devils! Three!'),
    ('והאור התקרב, והם ראו את הפנים.', 'And the light came near, and they saw the faces.'),
    ('לא שדים, שלושה אנשים.', 'Not devils, three men.'),
    ("פוטר, השיכור של הכפר, והרופא הצעיר, וג'ו האינדיאני.", 'Potter, the village drunk, and the young doctor, and Injun Joe.')),
  P(("ג'ו האינדיאני היה האיש הכי מסוכן בכפר.", 'Injun Joe was the most dangerous man in the village.'),
    ('חצי אינדיאני, והפנים שלו לא זזות, והעיניים שלו מפחידות.', 'Half Indian, and his face never moves, and his eyes frighten.'),
    ('והם באו לחפור את הקבר החדש, ולהוציא את המת.', 'And they had come to dig up the new grave, and take out the dead man.'),
    ('הרופא רצה את הגופה כדי ללמוד עליה, ושילם לשניים כסף.', 'The doctor wanted the body to study on it, and had paid the two money.'),
    ('הם חפרו, הוציאו את הארון, ופתחו אותו.', 'They dug, took out the coffin, and opened it.'),
    ('ושמו את הגופה בעגלה.', 'And put the body in a cart.'),
    ("ואז ג'ו האינדיאני אמר: רופא, אתה צריך לשלם עוד.", 'And then Injun Joe said: doctor, you have to pay more.'),
    ('וטום והאק, מאחורי העצים, לא נושמים.', 'And Tom and Huck, behind the trees, not breathing.'))]),

 ('The Oath', 'השבועה', [
  P(('הרופא אמר: שילמתי לכם, אין יותר.', 'The doctor said: I paid you, there is no more.'),
    ("ג'ו האינדיאני אמר: לפני חמש שנים גירשת אותי מהמטבח של אבא שלך, כי ביקשתי אוכל.", 'Injun Joe said: five years ago you drove me from your father’s kitchen, because I asked for food.'),
    ('ונשבעתי אז שאני לא שוכח, ועכשיו התור שלך.', 'And I swore then that I do not forget, and now it is your turn.'),
    ('והוא הרים את היד על הרופא.', 'And he raised his hand against the doctor.'),
    ("הרופא הכה אותו, וג'ו נפל על האדמה.", 'The doctor struck him, and Joe fell on the ground.'),
    ('ופוטר זרק את הסכין שלו, וקפץ על הרופא.', 'And Potter threw down his knife, and jumped on the doctor.'),
    ('והרופא תפס קרש מהקבר, הכה את פוטר על הראש, ופוטר נפל בלי לזוז.', 'And the doctor grabbed a board from the grave, struck Potter on the head, and Potter fell without moving.')),
  P(("וברגע הזה ג'ו האינדיאני קם.", 'And in that moment Injun Joe got up.'),
    ('הוא מצא את הסכין של פוטר על האדמה, לקח אותה, ודקר את הרופא בחזה.', 'He found Potter’s knife on the ground, took it, and stabbed the doctor in the chest.'),
    ('הרופא נפל על פוטר, והדם כיסה את שניהם.', 'The doctor fell on Potter, and the blood covered them both.'),
    ('והירח נעלם מאחורי ענן.', 'And the moon vanished behind a cloud.'),
    ('וטום והאק רצו.', 'And Tom and Huck ran.'),
    ('הם רצו בחושך, בין הקברים, בלי להסתכל אחורה.', 'They ran in the dark, among the graves, without looking back.')),
  P(("ובבית הקברות, ג'ו האינדיאני שם את הסכין ביד של פוטר, ישב לידו, וחיכה.", 'And in the graveyard, Injun Joe put the knife in Potter’s hand, sat beside him, and waited.'),
    ('וכשפוטר התעורר, וראה את הדם ואת הסכין, הוא רעד.', 'And when Potter woke, and saw the blood and the knife, he shook.'),
    ("הוא אמר: ג'ו... מה קרה? אני עשיתי את זה?", 'He said: Joe... what happened? Did I do this?'),
    ("ג'ו האינדיאני אמר: אתה, דקרת אותו בסכין, ואני ראיתי.", 'Injun Joe said: you, you stabbed him with the knife, and I saw.'),
    ('ופוטר, השיכור, האמין.', 'And Potter, the drunk, believed.'),
    ("והוא בכה, ואמר: ג'ו, אל תספר לאף אחד, אני לא זוכר כלום.", 'And he wept, and said: Joe, do not tell anyone, I do not remember anything.'),
    ("וג'ו אמר: אני לא מספר, אני החבר שלך.", 'And Joe said: I do not tell, I am your friend.')),
  P(('טום והאק הגיעו למפעל הנטוש, והם ישבו על הרצפה, נושמים בכבדות.', 'Tom and Huck reached the abandoned factory, and sat on the floor, breathing heavily.'),
    ('טום לחש: האק, מה יקרה?', 'Tom whispered: Huck, what will happen?'),
    ('האק אמר: אם הרופא מת, תולים מישהו.', 'Huck said: if the doctor is dead, they hang someone.'),
    ('טום אמר: ואנחנו מספרים?', 'Tom said: and do we tell?'),
    ("האק אמר: אם נספר, וג'ו האינדיאני לא ייתלה, הוא יהרוג אותנו, כמו שהרג את הרופא.", 'Huck said: if we tell, and Injun Joe is not hanged, he kills us, as he killed the doctor.'),
    ('והם שתקו, ואז טום אמר: נישבע, נכתוב שבועה בדם, ולא נספר.', 'And they were silent, and then Tom said: we swear, we write an oath in blood, and we do not tell.'),
    ('וטום כתב על לוח עץ: טום והאק נשבעים שהם לא מספרים אף פעם, ואם הם מספרים, הם מתים.', 'And Tom wrote on a board: Tom and Huck swear that they never tell, and if they tell, they die.'),
    ('וכל אחד דקר את האצבע שלו במחט, וחתם בדם שלו.', 'And each one pricked his finger with a needle, and signed with his blood.'),
    ('והם קברו את הלוח מתחת לקיר.', 'And they buried the board under the wall.'))]),

 ('Potter in Prison', 'פוטר בכלא', [
  P(('למחרת כל הכפר היה בבית הקברות.', 'The next day the whole village was in the graveyard.'),
    ('הרופא מת, והסכין היא הסכין של פוטר, וכולם יודעים.', 'The doctor dead, and the knife is Potter’s knife, and everyone knows.'),
    ('ובא פוטר בעצמו, רועד, ועמד מול הגופה.', 'And Potter himself came, shaking, and stood before the body.'),
    ('הוא אמר: אני לא עשיתי את זה, אני לא זוכר כלום.', 'He said: I did not do it, I do not remember anything.'),
    ("וג'ו האינדיאני אמר, לפני כולם, בקול שקט: אני ראיתי אותו, הוא זה שדקר אותו.", 'And Injun Joe said, before everyone, in a quiet voice: I saw him, he is the one who stabbed him.'),
    ('והוא סיפר את הסיפור, הפוך.', 'And he told the story, backwards.'),
    ('וטום והאק, עומדים בין האנשים, ושומעים, ושותקים.', 'And Tom and Huck, standing among the people, and hearing, and silent.')),
  P(('הם לקחו את פוטר לכלא, והוא חיכה למשפט.', 'They took Potter to jail, and he waited for the trial.'),
    ('והכפר אומר: תלייה זה מעט מדי בשבילו.', 'And the village says: hanging is too little for him.'),
    ('וטום לא ישן שבוע.', 'And Tom did not sleep for a week.'),
    ('כל לילה הוא חלם על בית הקברות, והתעורר, ודיבר מתוך שינה.', 'Every night he dreamed about the graveyard, and woke, and talked in his sleep.'),
    ('והאח שלו שמע אותו אומר: דם! וסכין! ושאל אותו בבוקר: טום, על מה אתה חולם?', 'And his brother heard him say: blood! And a knife! And asked him in the morning: Tom, what are you dreaming about?'),
    ('וטום אמר: השיניים שלי כואבות, וקשר את הלסת במטפחת, ולא דיבר.', 'And Tom said: my teeth hurt, and tied his jaw with a handkerchief, and did not talk.')),
  P(('וכל יום טום הלך לכלא.', 'And every day Tom went to the jail.'),
    ('הכלא היה חדר קטן מלבנים, וחלון עם סורגים.', 'The jail was a small room of bricks, and a window with bars.'),
    ('והוא היה מעביר לפוטר דרך החלון טבק וגפרורים, ולפעמים אוכל.', 'And he would pass Potter through the window tobacco and matches, and sometimes food.'),
    ('ופוטר היה בוכה, ואומר: טום, אתה היחיד שבא.', 'And Potter would cry, and say: Tom, you are the only one who comes.'),
    ('עזרתי לך לדוג, ותיקנתי לך את העפיפונים, ועכשיו כולם שכחו.', 'I helped you fish, and fixed your kites, and now everyone has forgotten.'),
    ('אבל אתה לא שכחת, ולא האק.', 'But you did not forget, and not Huck.'),
    ('וכל מילה הייתה כמו סכין בלב של טום.', 'And every word was like a knife in Tom’s heart.')),
  P(("וג'ו האינדיאני הלך בכפר חופשי, ואמר שלום לאנשים.", 'And Injun Joe walked the village free, and said hello to people.'),
    ('וכל פעם שטום ראה אותו, הוא התחבא.', 'And every time Tom saw him, he hid.'),
    ("האק אמר: אם נספר, ג'ו הורג אותנו, ואם לא נספר, פוטר נתלה.", 'Huck said: if we tell, Joe kills us, and if we do not tell, Potter hangs.'),
    ('טום אמר: אני יודע.', 'Tom said: I know.'),
    ('האק אמר: ומה נעשה?', 'Huck said: and what do we do?'),
    ('טום אמר: אני לא יודע.', 'Tom said: I do not know.'),
    ('וזאת הפעם הראשונה בחיים שלו שהוא לא ידע.', 'And it was the first time in his life that he did not know.'))]),

 ('Becky Turns Away', 'בקי מסתובבת', [
  P(('ומעל כל זה, בקי לא דיברה איתו יותר.', 'And on top of all that, Becky no longer talked to him.'),
    ('היא עברה לידו בבית הספר, והסתכלה לצד השני.', 'She passed by him at school, and looked the other way.'),
    ('וטום ניסה הכול.', 'And Tom tried everything.'),
    ('הוא עמד על הראש מולה, היא לא הסתכלה.', 'He stood on his head in front of her, she did not look.'),
    ('הוא רב עם ילד מולה, וניצח, היא לא הסתכלה.', 'He fought with a boy in front of her, and won, she did not look.'),
    ('ואז היא חלתה, ונעדרה שבוע, וטום חשב שהיא תמות.', 'And then she fell ill, and was away a week, and Tom thought she would die.'),
    ('והוא לא היה אכפת לו יותר במלחמה ולא בשודדי ים ולא בשום דבר.', 'And he no longer cared about war or pirates or anything.')),
  P(('דודה פולי דאגה לו, כי הוא נהיה חיוור ושקט.', 'Aunt Polly worried about him, because he had become pale and quiet.'),
    ('והיא אהבה תרופות חדשות, וניסתה כל תרופה ששמעה עליה.', 'And she loved new medicines, and tried every medicine she heard of.'),
    ('היא רחצה אותו במים קרים, עטפה אותו בסדינים רטובים, ונתנה לו תרופות בטעם של אש.', 'She washed him in cold water, wrapped him in wet sheets, and gave him medicines with a taste of fire.'),
    ('וטום לא היה אכפת לו.', 'And Tom did not care.'),
    ('ואז היא באה עם תרופה חדשה: משכך כאבים, וטום לקח את הבקבוק.', 'And then she came with a new medicine: a pain-killer, and Tom took the bottle.'),
    ('והתחיל לתת ממנו לחתול, בכפית.', 'And began giving it to the cat, by the spoonful.'),
    ('והחתול עף, והתחיל לרוץ בבית, להפוך כיסאות, ולעלות על הקירות.', 'And the cat flew, and began running around the house, overturning chairs, and climbing the walls.'),
    ('ודודה פולי אמרה: טום! מה עשית לחתול?', 'And Aunt Polly said: Tom! What did you do to the cat?'),
    ('טום אמר: נתתי לו את התרופה, אהבתי אותו כמו שאת אוהבת אותי.', 'Tom said: I gave him the medicine, I loved him the way you love me.'),
    ('והיא צחקה, ובכתה, והפסיקה לתת לו תרופות.', 'And she laughed, and cried, and stopped giving him medicines.')),
  P(('ויום אחד בקי חזרה לבית הספר.', 'And one day Becky came back to school.'),
    ('טום ראה אותה מרחוק, והלב שלו קפץ.', 'Tom saw her from afar, and his heart jumped.'),
    ('והוא התחיל לשחק, ולצעוק, ולקפוץ, ולצחוק, הכול בשבילה.', 'And he began to play, and shout, and jump, and laugh, all for her.'),
    ('והיא עמדה עם ילדה אחרת, הסתכלה עליו, ואמרה בקול רם:', 'And she stood with another girl, looked at him, and said out loud:'),
    ('יש אנשים שחושבים שהם חשובים, הם עושים כל דבר כדי שאנשים יסתכלו עליהם.', 'Some people think they are important, they do anything so that people look at them.'),
    ('וטום עמד במקום, והפנים שלו נהיו אדומות.', 'And Tom stood where he was, and his face went red.'),
    ('והלך, ואמר לעצמו: זהו, אף אחד לא אוהב אותי, אני אהיה שודד ים.', 'And walked off, and said to himself: that is it, no one loves me, I will be a pirate.')),
  P(('שודד ים.', 'A pirate.'),
    ('כלומר ספינה שחורה, ודגל שחור, וחרב, ואנשים שמפחדים כששומעים את השם שלו.', 'That is, a black ship, and a black flag, and a sword, and people who are afraid when they hear his name.'),
    ('ואז הוא חוזר לכפר, אחרי שנים, בבגדים שחורים, ובקי רואה אותו ומצטערת.', 'And then he comes back to the village, after years, in black clothes, and Becky sees him and is sorry.'),
    ("הוא הלך ודיבר עם ג'ו הרפר, החבר שלו, שאימא שלו הכתה אותו על משהו שלא עשה.", 'He went and talked with Joe Harper, his friend, whose mother had beaten him for something he did not do.'),
    ("וג'ו אמר: אני איתך.", 'And Joe said: I am with you.'),
    ('והם הלכו אל האק, והאק אמר: למה לא?', 'And they went to Huck, and Huck said: why not?'),
    ('והם החליטו לברוח בחצות, לאי בנהר, ולהיות שודדי ים.', 'And they decided to run away at midnight, to the island in the river, and be pirates.'))]),

 ('The Pirates Set Out', 'השודדים יוצאים לדרך', [
  P(('בחצות השלושה נפגשו ליד הנהר, מתחת לגבעה.', 'At midnight the three met by the river, below the hill.'),
    ("טום הביא בשר מבושל, ג'ו הרפר הביא לחם, והאק הביא מחבת וטבק.", 'Tom brought cooked meat, Joe Harper brought bread, and Huck brought a pan and tobacco.'),
    ('וכל אחד גנב את מה שהביא, כי שודדי ים לא קונים.', 'And each one had stolen what he brought, because pirates do not buy.'),
    ("טום אמר: אני השחור, האימה של הימים, וג'ו, אתה האימה של האוקיינוס, והאק, אתה היד האדומה.", 'Tom said: I am the Black One, the terror of the seas, and Joe, you are the terror of the ocean, and Huck, you are Red Hand.'),
    ('והייתה רפסודה קטנה קשורה על החוף, של מישהו מהכפר.', 'And there was a small raft tied on the shore, of someone from the village.'),
    ('והם לקחו אותה.', 'And they took it.')),
  P(('הם דחפו את הרפסודה לנהר, והזרם נשא אותם.', 'They pushed the raft into the river, and the current carried them.'),
    ('והכפר ישן, ורק אור או שניים בחלונות.', 'And the village asleep, and only a light or two in the windows.'),
    ('טום עמד באמצע, הידיים על החזה, ואמר בקול נמוך: להוריד את המפרש!', 'Tom stood in the middle, his arms on his chest, and said in a low voice: lower the sail!'),
    ("ולא היה מפרש, אבל ג'ו אמר: כן, מפקד.", 'And there was no sail, but Joe said: yes, captain.'),
    ('והרפסודה עברה מול הכפר, וטום הסתכל על הבית שבקי בו.', 'And the raft passed in front of the village, and Tom looked at the house Becky was in.'),
    ('ואמר בלב: אם היא רק הייתה יודעת.', 'And said to himself: if only she knew.')),
  P(('הם הגיעו לאי אחרי שעתיים, ומשכו את הרפסודה לחוף.', 'They reached the island after two hours, and pulled the raft onto the shore.'),
    ('האי: באורך מיל, ובו יער, ואין בו אף אחד.', 'The island: a mile long, and in it a forest, and no one on it.'),
    ('הם הדליקו אש גדולה, צלו את הבשר, ואכלו כמו זאבים.', 'They lit a big fire, roasted the meat, and ate like wolves.'),
    ("וג'ו אמר: אלה החיים!", 'And Joe said: this is the life!'),
    ('והאק אמר: אין בית ספר, ואין כנסייה, ואין מי שאומר לך לשטוף את הפנים.', 'And Huck said: no school, and no church, and no one who tells you to wash your face.'),
    ('וטום אמר: ושודדי ים לא קמים מוקדם.', 'And Tom said: and pirates do not get up early.'),
    ('והם ישנו סביב האש, והכוכבים מעליהם.', 'And they slept around the fire, and the stars above them.')),
  P(('אבל טום לא נרדם מהר.', 'But Tom did not fall asleep quickly.'),
    ('הוא חשב על הרפסודה הגנובה, ועל הבשר הגנוב.', 'He thought about the stolen raft, and the stolen meat.'),
    ('שודדי ים גונבים, נכון, אבל הם גונבים מאויבים, לא משכנים.', 'Pirates steal, true, but they steal from enemies, not from neighbours.'),
    ('והוא החליט: ממחר, שודדי הים לא גונבים.', 'And he decided: from tomorrow, the pirates do not steal.'),
    ('והוא נרגע, והוא נרדם.', 'And calmed down, and fell asleep.'),
    ("וג'ו נרדם וחשב על אימא שלו.", 'And Joe fell asleep thinking about his mother.'),
    ('והאק נרדם, כי האק נרדם בכל מקום.', 'And Huck fell asleep, because Huck falls asleep anywhere.'))]),

 ('Life on the Island', 'החיים על האי', [
  P(('בבוקר טום התעורר מקול הציפורים, והשמש בין העצים.', 'In the morning Tom woke from the sound of the birds, and the sun between the trees.'),
    ('היה טל על העשב, וסנאי הסתכל עליו מענף.', 'There was dew on the grass, and a squirrel looked at him from a branch.'),
    ('ונמלה גוררת משהו מת גדול ממנה.', 'And an ant dragging something dead bigger than itself.'),
    ('והוא ישב והסתכל, והרגיש שהוא האדם הראשון בעולם.', 'And he sat and looked, and felt that he was the first person in the world.'),
    ('ואז האחרים התעוררו, ושלושת החברים רצו לנהר, ושחו.', 'And then the others woke, and the three of them ran to the river, and swam.')),
  P(('וכשחזרו, הרפסודה לא הייתה.', 'And when they came back, the raft was gone.'),
    ('הזרם לקח אותה בלילה.', 'The current had taken it in the night.'),
    ("ג'ו אמר: ואיך נחזור?", 'Joe said: and how do we go back?'),
    ('טום אמר: שודדי ים לא חוזרים.', 'Tom said: pirates do not go back.'),
    ('והם דגו דגים, צלו אותם, אכלו אותם, וזה היה הדג הכי טעים בחיים שלהם.', 'And they caught fish, roasted them, ate them, and it was the tastiest fish in their lives.'),
    ('כי הרעב הוא הטבח הכי טוב.', 'Because hunger is the best cook.'),
    ('ואחרי האוכל הם הלכו באי, ומצאו בו הכול.', 'And after the food they walked on the island, and found everything on it.'),
    ('עצים, ומעיין, ומערה קטנה, וחוף של חול.', 'Trees, and a spring, and a small cave, and a beach of sand.')),
  P(('ואחרי הצהריים הזמן התחיל ללכת לאט.', 'And in the afternoon the time began to go slowly.'),
    ('הם ישבו על החוף, ואף אחד לא דיבר.', 'They sat on the shore, and no one spoke.'),
    ("טום צייר בחול, ג'ו הסתכל על הנהר, והאק עישן את המקטרת שלו.", 'Tom drew in the sand, Joe looked at the river, and Huck smoked his pipe.'),
    ("וג'ו אמר: אתם חושבים... מה הם עושים עכשיו בכפר?", 'And Joe said: do you think... what are they doing now in the village?'),
    ('טום אמר: בטח מחפשים אותנו.', 'Tom said: surely looking for us.'),
    ("וג'ו אמר: אולי אימא שלי...", 'And Joe said: maybe my mother...'),
    ('ושתק, כי אם היה ממשיך, הוא היה בוכה.', 'And was silent, because if he had gone on, he would have cried.'),
    ('וגם טום חשב על דודה פולי, אבל לא דיבר.', 'And Tom too thought about Aunt Polly, but did not speak.')),
  P(('והאק, שאין לו אימא, היה הכי רגוע.', 'And Huck, who has no mother, was the calmest.'),
    ('הוא אמר: אני מרוצה, כאן יש אוכל, ואף אחד לא מכה אותי.', 'He said: I am content, here there is food, and no one beats me.'),
    ('ובכפר, אין אוכל ואף אחד לא אכפת לו.', 'And in the village, no food and no one cares.'),
    ('וטום שמע, והבין בפעם הראשונה שהאק לא חופשי, אלא לבד.', 'And Tom heard, and understood for the first time that Huck was not free, but alone.'),
    ('ובא הלילה השני, והם הדליקו את האש, וישנו, ואף אחד לא אמר שהוא רוצה לחזור.', 'And the second night came, and they lit the fire, and slept, and no one said that he wanted to go back.'),
    ('אבל כל אחד חשב על זה.', 'But each one thought about it.'))]),

 ('The Sound on the River', 'הקול על הנהר', [
  P(('אחרי הצהריים השני הם שמעו קול מרחוק.', 'On the second afternoon they heard a sound from afar.'),
    ('בום, קול עמוק, מהנהר.', 'Boom, a deep sound, from the river.'),
    ("ג'ו אמר: מה זה?", 'Joe said: what is that?'),
    ('האק אמר: רעם?', 'Huck said: thunder?'),
    ('טום אמר: לא, תקשיבו.', 'Tom said: no, listen.'),
    ('ואחרי דקה, בום עוד פעם.', 'And after a minute, boom again.'),
    ('הם רצו לחוף, והסתכלו על הנהר.', 'They ran to the shore, and looked at the river.')),
  P(('זאת הייתה הספינה הקטנה של הכפר, שטה באמצע הנהר, ועליה הרבה אנשים.', 'It was the village’s little steamboat, sailing in the middle of the river, and on it many people.'),
    ('וכל כמה זמן יוצא עשן מהצד שלה, ואז בום.', 'And every so often smoke comes out of its side, and then boom.'),
    ('האק אמר: הם יורים בתותח על המים!', 'Huck said: they are firing a cannon at the water!'),
    ('טום אמר: אני יודע למה! ככה עושים כשמישהו טובע.', 'Tom said: I know why! That is what they do when someone drowns.'),
    ('הקול של התותח גורם לגופה לעלות למעלה.', 'The sound of the cannon makes the body rise up.'),
    ('ושלושת החברים שתקו, והבינו בבת אחת.', 'And the three were silent, and understood all at once.'),
    ("ג'ו אמר: הם מחפשים אותנו, הם חושבים שטבענו.", 'Joe said: they are looking for us, they think we drowned.')),
  P(('והפנים של טום התחילו להאיר.', 'And Tom’s face began to shine.'),
    ('הוא אמר: כלומר כל הכפר מדבר עלינו!', 'He said: that is, the whole village is talking about us!'),
    ('והאנשים בוכים, והילדים מקנאים בנו, ואנחנו גיבורים!', 'And the people cry, and the boys envy us, and we are heroes!'),
    ('והרגיש שזה הרגע הכי יפה בחיים שלו.', 'And felt that it was the most beautiful moment in his life.'),
    ("אבל ג'ו לא היה מאושר.", 'But Joe was not happy.'),
    ('הוא דמיין את אימא שלו, עומדת על החוף, ובוכה.', 'He imagined his mother, standing on the shore, and crying.'),
    ('והאק חשב: מי יבכה עליי?', 'And Huck thought: who will cry over me?')),
  P(('ובא הלילה, והספינה חזרה, והנהר חזר להיות שקט.', 'And night came, and the boat went back, and the river went back to being quiet.'),
    ('ושניים נרדמו, וטום לא.', 'And two fell asleep, and Tom did not.'),
    ('הוא ישב וחשב על דודה פולי.', 'He sat and thought about Aunt Polly.'),
    ('וכל פעם שחשב, ראה אותה בוכה, ולא יכול היה לסבול את התמונה הזאת.', 'And every time he thought, he saw her crying, and could not bear that picture.'),
    ('ואחרי חצות הוא קם לאט, וכתב משהו על חתיכת קליפה בגיר.', 'And after midnight he got up slowly, and wrote something on a piece of bark in chalk.'),
    ("ושם אותה בכיס, ושם חתיכה שנייה ליד ג'ו.", 'And put it in his pocket, and put a second piece beside Joe.'),
    ('והלך לחוף, וירד למים.', 'And walked to the shore, and went down into the water.'))]),

 ('Tom Goes Home in the Dark', 'טום חוזר בלילה', [
  P(('הנהר בין האי לכפר לא רחב, אבל הזרם חזק.', 'The river between the island and the village is not wide, but the current is strong.'),
    ('טום הלך במים עד המותניים, ואז שחה.', 'Tom walked in the water up to the waist, and then swam.'),
    ('והזרם לקח אותו למטה, אבל הוא היה שחיין טוב.', 'And the current took him down, but he was a good swimmer.'),
    ('הוא הגיע לחוף השני רחוק מהכפר, והלך על הדרך, בחושך.', 'He reached the other bank far from the village, and walked on the road, in the dark.'),
    ('והייתה ספינה קשורה, אז הוא עלה עליה, ושכב בתחתית עד שהיא זזה.', 'And there was a boat tied up, so he got on it, and lay in the bottom until it moved.'),
    ('וכשהגיעה לכפר, הוא ירד, ורץ בין הבתים.', 'And when it reached the village, he got off, and ran between the houses.')),
  P(('הוא הגיע לבית של דודה פולי, וראה אור בחלון.', 'He reached Aunt Polly’s house, and saw a light in the window.'),
    ("הוא הציץ מהחלון: דודה פולי יושבת, והאח שלו, ובת הדודה, והאימא של ג'ו הרפר.", 'He peeked through the window: Aunt Polly sitting, and his brother, and the cousin, and Joe Harper’s mother.'),
    ('וכולן בוכות.', 'And all of them crying.'),
    ('הוא נכנס מהדלת שמאחור, זחל מתחת למיטה, ושמע.', 'He went in through the back door, crawled under the bed, and listened.'),
    ('דודה פולי אמרה: טום לא היה ילד רע, הוא רק עשה שטויות.', 'Aunt Polly said: Tom was not a bad boy, he was only mischievous.'),
    ('והלב שלו טוב יותר מהלב של כל ילד.', 'And his heart is better than the heart of any boy.'),
    ("והאימא של ג'ו אמרה: וגם ג'ו, הכיתי אותו על משהו שהוא לא עשה, שאלוהים יסלח לי.", 'And Joe’s mother said: and Joe too, I beat him for something he did not do, may God forgive me.')),
  P(('והם אמרו שביום ראשון תהיה הלוויה לשלושת החברים.', 'And they said that on Sunday there would be a funeral for the three of them.'),
    ('כי אחרי ארבעה ימים, אף אחד לא יוצא מהנהר.', 'Because after four days, no one comes out of the river.'),
    ('וטום מתחת למיטה, ורוצה לצאת, ורוצה לחבק את דודה פולי.', 'And Tom under the bed, and wanting to come out, and wanting to hug Aunt Polly.'),
    ('אבל הוא לא יצא.', 'But he did not come out.'),
    ('כי בא לו רעיון גדול יותר.', 'Because a bigger idea had come to him.'),
    ('והאורחים הלכו, והדודה נרדמה, מתפללת על טום.', 'And the guests went, and the aunt fell asleep, praying over Tom.')),
  P(('טום יצא מתחת למיטה, ועמד לידה.', 'Tom came out from under the bed, and stood beside her.'),
    ('היא ישנה, והפנים שלה עייפות, ועל הלחי שלה דמעה.', 'She was asleep, and her face tired, and on her cheek a tear.'),
    ('הוא הוציא את חתיכת הקליפה מהכיס, וקרא מה שכתב: אנחנו לא מתים, אנחנו שודדי ים.', 'He took the piece of bark out of his pocket, and read what he had written: we are not dead, we are pirates.'),
    ('והוא עמד לשים אותה לידה.', 'And he was about to put it beside her.'),
    ('אבל הוא חשב על ההלוויה, ועל הרעיון הגדול, והחזיר את הקליפה לכיס.', 'But he thought about the funeral, and about the big idea, and put the bark back in his pocket.'),
    ('ונישק אותה על הלחי, והיא ישנה.', 'And kissed her on the cheek, and she asleep.'),
    ('והוא יצא, וחזר לנהר, ושחה לאי לפני השחר.', 'And went out, and went back to the river, and swam to the island before dawn.'))]),

 ('The Storm', 'הסופה', [
  P(("כשהגיע, הוא מצא את ג'ו ואת האק יושבים על החוף, ועצובים.", 'When he arrived, he found Joe and Huck sitting on the shore, and sad.'),
    ("ג'ו אמר: קראתי את הקליפה, חשבנו שברחת ועזבת אותנו.", 'Joe said: I read the bark, we thought you had run away and left us.'),
    ('טום אמר: אני השודד השחור, אני לא עוזב את האנשים שלי.', 'Tom said: I am the Black Pirate, I do not leave my men.'),
    ('והוא סיפר להם על הלילה, ועל הבכי, ועל ההלוויה.', 'And he told them about the night, and the crying, and the funeral.'),
    ('ואמר: יש לי רעיון, אבל אני עוד לא מספר אותו.', 'And said: I have an idea, but I am not telling it yet.'),
    ("וג'ו אמר: אני רוצה לחזור.", 'And Joe said: I want to go back.'),
    ('וטום אמר: רק עד יום ראשון, תאמין לי.', 'And Tom said: only until Sunday, believe me.')),
  P(('ובאותו לילה באה הסופה.', 'And that night the storm came.'),
    ('קודם רוח, ואז ברק, ואז רעם כמו תותחים.', 'First wind, then lightning, then thunder like cannons.'),
    ('והגשם ירד כאילו הנהר התהפך עליהם מלמעלה.', 'And the rain came down as if the river had been turned over on them from above.'),
    ('הם רצו לאוהל שעשו מהסדין, והרוח לקחה את הסדין.', 'They ran to the tent they had made from the sheet, and the wind took the sheet.'),
    ('הם רצו לעץ הגדול, והברק פגע בעץ.', 'They ran to the big tree, and the lightning struck the tree.'),
    ('הם רצו למערה, והם ישבו בה, רועדים, ורטובים עד העצם.', 'They ran to the cave, and sat in it, shaking, and wet to the bone.'),
    ('וכל הלילה הברק מאיר את האי כמו יום, ואז חושך.', 'And all night the lightning lighting the island like day, and then dark.')),
  P(('ובבוקר הכול נרגע.', 'And in the morning everything calmed.'),
    ('הם יצאו מהמערה, והאי נהיה משהו אחר.', 'They came out of the cave, and the island had become something else.'),
    ('עצים שבורים, וענפים בכל מקום, והאש הלכה.', 'Broken trees, and branches everywhere, and the fire gone.'),
    ('והעץ הגדול שישנו מתחתיו בלילה הראשון, שבור לשניים.', 'And the big tree they had slept under the first night, broken in two.'),
    ('האק אמר: אם היינו מתחתיו.', 'Huck said: if we had been under it.'),
    ('ואף אחד לא סיים את המשפט.', 'And no one finished the sentence.'),
    ('והם מצאו גחלת מתחת לאפר, הדליקו את האש, התייבשו, ואכלו.', 'And they found an ember under the ash, lit the fire, dried off, and ate.')),
  P(('ואחרי האוכל טום אמר: עכשיו אני מספר לכם את הרעיון.', 'And after the food Tom said: now I tell you the idea.'),
    ('והוא סיפר אותו, בקול נמוך, כאילו זה סוד של מלחמה.', 'And he told it, in a low voice, as if it were a secret of war.'),
    ("וג'ו התחיל לצחוק, והאק התחיל לצחוק, ואמרו: זה הרעיון הכי טוב בעולם.", 'And Joe began to laugh, and Huck began to laugh, and they said: this is the best idea in the world.'),
    ("וג'ו אמר: אז אנחנו חוזרים ביום ראשון?", 'And Joe said: so we go back on Sunday?'),
    ('טום אמר: ביום ראשון, אבל לא כמו שהם מצפים.', 'Tom said: on Sunday, but not the way they expect.'))]),

 ('Their Own Funeral', 'הלוויה שלהם', [
  P(('ביום ראשון הכנסייה הייתה מלאה כמו שלא הייתה אף פעם.', 'On Sunday the church was full as it had never been.'),
    ('כל הכפר בא, האנשים שהולכים, ואלה שלא הולכים.', 'The whole village came, the people who go, and those who do not go.'),
    ('דודה פולי, והאח, ובת הדודה, בבגדים שחורים, בשורה הראשונה.', 'Aunt Polly, and the brother, and the cousin, in black clothes, in the first row.'),
    ("והאימא והאבא של ג'ו הרפר לידם.", 'And Joe Harper’s mother and father beside them.'),
    ('ואף אחד בשביל האק, אבל האלמנה בכתה עליו, כי הוא הביא לה לפעמים עצים.', 'And no one for Huck, but the widow cried for him, because he sometimes brought her wood.'),
    ('וכל האנשים שקטים, והפעמון מצלצל לאט.', 'And all the people quiet, and the bell ringing slowly.')),
  P(('הכומר עמד, והתחיל לדבר על השלושה.', 'The preacher stood, and began to speak about the three.'),
    ('הוא דיבר על הטוב שלהם, ועל החכמה שלהם, ועל הלב הנקי שלהם.', 'He spoke about their goodness, and their wisdom, and their clean heart.'),
    ('וסיפר סיפורים עליהם, סיפורים שהאנשים קראו להם שובבות, ועכשיו קראו להם טוב לב.', 'And told stories about them, stories the people had called mischief, and now called kindness.'),
    ('וכל הכנסייה בוכה.', 'And the whole church crying.'),
    ('והכומר בעצמו בכה.', 'And the preacher himself cried.'),
    ('ובסוף הדרשה, הדלת של הכנסייה נפתחה.', 'And at the end of the sermon, the church door opened.'),
    ('ואף אחד לא שם לב, בהתחלה.', 'And no one noticed, at first.')),
  P(('ואז הכומר הרים את העיניים מהנייר, ועצר.', 'And then the preacher raised his eyes from the paper, and stopped.'),
    ('ואז האנשים הסתובבו, שורה אחרי שורה.', 'And then the people turned, row after row.'),
    ('והם ראו.', 'And they saw.'),
    ("השלושה, הולכים במעבר, טום ראשון, ג'ו אחריו, והאק אחרון, ונבוך.", 'The three, walking down the aisle, Tom first, Joe after him, and Huck last, and embarrassed.'),
    ('הם היו מלוכלכים, והבגדים שלהם עם חורים, והפנים שלהם שרופות מהשמש.', 'They were dirty, and their clothes torn, and their faces burned from the sun.'),
    ('הם התחבאו בחדר האחורי, ושמעו את כל ההלוויה שלהם.', 'They had hidden in the back room, and heard their whole funeral.'),
    ('ודודה פולי צעקה, ורצה, ותפסה את טום, ונישקה אותו מאה פעם.', 'And Aunt Polly screamed, and ran, and grabbed Tom, and kissed him a hundred times.'),
    ("והאימא של ג'ו תפסה את ג'ו.", 'And Joe’s mother grabbed Joe.')),
  P(('והאק עמד לבד, ואף אחד לא תפס אותו.', 'And Huck stood alone, and no one grabbed him.'),
    ('וטום אמר: דודה, מישהו צריך לשמוח גם על האק.', 'And Tom said: aunt, someone has to be glad about Huck too.'),
    ('ודודה פולי אמרה: אני שמחה עליו, וחיבקה אותו.', 'And Aunt Polly said: I am glad about him, and hugged him.'),
    ('והאק לא ידע מה לעשות עם הידיים שלו.', 'And Huck did not know what to do with his hands.'),
    ('ואז הכומר צעק: שירו! שירו בכל הלב!', 'And then the preacher shouted: sing! Sing with all your heart!'),
    ('וכל הכנסייה שרה, עד שהגג רעד.', 'And the whole church sang, until the roof shook.'),
    ('וטום עמד באמצע, והאנשים סביבו, ואמר בלב: זה הרגע הכי טוב בחיים שלי.', 'And Tom stood in the middle, and the people around him, and said to himself: this is the best moment in my life.'),
    ('והפעם, הוא צדק.', 'And this time, he was right.'))]),

 ('The Torn Book', 'הספר הקרוע', [
  P(('אחרי ההלוויה טום נהיה הגיבור של הכפר.', 'After the funeral Tom became the hero of the village.'),
    ('הילדים הלכו אחריו, ושאלו אותו על האי, והוא סיפר והוסיף.', 'The boys followed him, and asked him about the island, and he told and added.'),
    ('ובקי? בקי לא דיברה איתו.', 'And Becky? Becky did not talk with him.'),
    ('אבל הפעם טום החליט שהוא לא רוצה אותה.', 'But this time Tom decided that he did not want her.'),
    ('והוא התחיל לדבר עם ילדה אחרת מולה, ולצחוק בקול רם.', 'And he began to talk with another girl in front of her, and to laugh out loud.'),
    ('ובקי התחילה לדבר עם ילד עשיר ומנומס, מול טום.', 'And Becky began to talk with a rich and polite boy, in front of Tom.'),
    ('וכל אחד סבל, ועשה כאילו הוא שמח.', 'And each one suffered, and pretended to be happy.')),
  P(('ובאותו יום קרה משהו בבית הספר.', 'And that day something happened at school.'),
    ('למורה היה ספר שהוא החביא במגירה נעולה.', 'The teacher had a book that he hid in a locked drawer.'),
    ('ספר על גוף האדם, עם תמונות, וכל הילדים רצו לראות אותו.', 'A book about the human body, with pictures, and all the children wanted to see it.'),
    ('ובקי עברה ליד המגירה, ומצאה אותה פתוחה, ולא יכלה להתאפק.', 'And Becky passed by the drawer, and found it open, and could not resist.'),
    ('היא פתחה את הספר, ראתה תמונה, והפנים שלה נהיו אדומות.', 'She opened the book, saw a picture, and her face went red.'),
    ('וברגע הזה טום נכנס מהדלת.', 'And in that moment Tom came in through the door.'),
    ('היא נבהלה, סגרה את הספר מהר, והדף נקרע לשניים.', 'She panicked, closed the book fast, and the page tore in two.')),
  P(('בקי אמרה: טום סוייר, אתה מרגל! אתה תספר!', 'Becky said: Tom Sawyer, you are a spy! You will tell!'),
    ('והיא בכתה, ורצה.', 'And she cried, and ran.'),
    ('וטום עמד במקום, ואמר: לא אמרתי כלום.', 'And Tom stood where he was, and said: I did not say anything.'),
    ('וחשב: עכשיו מישהו יקבל מכות, המורה ישאל את כולם, ואז יידע מהפנים שלה.', 'And thought: now someone gets a beating, the teacher will ask everyone, and know from her face.'),
    ('וחשב גם: ומה אכפת לי? היא לא אוהבת אותי.', 'And thought too: and what do I care? She does not love me.'),
    ('אבל היה אכפת לו.', 'But he cared.')),
  P(('ואחרי הצהריים המורה פתח את המגירה, ראה את הספר, ועצר.', 'And in the afternoon the teacher opened the drawer, saw the book, and stopped.'),
    ('ושאל: מי קרע את הספר הזה?', 'And asked: who tore this book?'),
    ('ושקט.', 'And silence.'),
    ("והתחיל לשאול אחד אחד, בן? לא, ג'ו? לא.", 'And began asking one by one, Ben? No, Joe? No.'),
    ('והגיע לבקי, והפנים של בקי נהיו לבנות, והידיים שלה רועדות.', 'And reached Becky, and Becky’s face went white, and her hands shaking.'),
    ('ולפני ששאל אותה, טום קם, ואמר: אני.', 'And before he asked her, Tom got up, and said: me.'),
    ('וכל בית הספר הסתובב אליו.', 'And the whole school turned to him.'),
    ('והמורה הכה אותו את המכות הכי קשות שהכה בחיים שלו, וטום לא הרגיש.', 'And the teacher gave him the hardest beating he had ever given in his life, and Tom did not feel.'),
    ('כי הוא ראה את הפנים של בקי.', 'Because he saw Becky’s face.'),
    ('ובסוף היום היא לחשה לו: טום, איך אתה יכול להיות כל כך אציל?', 'And at the end of the day she whispered to him: Tom, how can you be so noble?'))]),

 ('Examination Day', 'יום המבחן', [
  P(('הגיע היום האחרון של השנה, יום המבחן.', 'The last day of the year came, examination day.'),
    ('כל ההורים באים, והילדים קוראים שירים, והמורה לובש את הבגדים הכי טובים שלו.', 'All the parents come, and the children recite poems, and the teacher wears his best clothes.'),
    ('והמורה היה איש קשה, שמכה הרבה, והילדים שנאו אותו.', 'And the teacher was a hard man, who beat a lot, and the children hated him.'),
    ('והיה לו סוד: השיער שלו היה פאה, ומתחתיה הראש שלו קירח ומבריק.', 'And he had a secret: his hair was a wig, and under it his head bald and shining.'),
    ('והילדים הגדולים הכינו תוכנית ליום הזה.', 'And the big boys prepared a plan for that day.')),
  P(('המורה היה שותה קצת לפני המבחן, בשביל האומץ.', 'The teacher would drink a little before the examination, for courage.'),
    ('וביום הזה הוא שתה יותר, והילדים ידעו.', 'And on that day he drank more, and the boys knew.'),
    ('המבחן התחיל, ילד קרא שיר, וילדה קראה חיבור.', 'The examination began, a boy recited a poem, and a girl read an essay.'),
    ('וטום קם לקרוא נאום, שכח באמצע, עמד והסתכל על האנשים, והוא ישב.', 'And Tom got up to give a speech, forgot in the middle, stood and looked at the people, and sat down.'),
    ('ואז המורה קם לצייר מפה על הלוח, לגיאוגרפיה.', 'And then the teacher got up to draw a map on the board, for geography.'),
    ('והגב שלו לאנשים, ומעליו, בתקרה, דלת קטנה לעליית הגג.', 'And his back to the people, and above him, in the ceiling, a small door to the attic.')),
  P(('והדלת נפתחה.', 'And the door opened.'),
    ('וירד ממנה חבל, לאט, ובסוף שלו חתול.', 'And down from it came a rope, slowly, and at its end a cat.'),
    ('חתול קשור מהבטן, והפה שלו קשור כדי שלא יצעק.', 'A cat tied around the belly, and its mouth tied so that it would not cry.'),
    ('והוא ירד, וירד, ומזיז את הרגליים באוויר.', 'And it came down, and down, moving its legs in the air.'),
    ('והאנשים רואים, והמורה לא, כי הוא עסוק במפה.', 'And the people see, and the teacher does not, because he is busy with the map.'),
    ('וכשהחתול הגיע מעל הראש שלו, הוא תפס את הפאה בציפורניים.', 'And when the cat reached above his head, it grabbed the wig with its claws.')),
  P(('ומשכו אותו למעלה.', 'And they pulled it up.'),
    ('והפאה איתו.', 'And the wig with it.'),
    ('והמורה עמד מול כל הכפר, והראש שלו קירח, ומבריק, וצבוע בזהב.', 'And the teacher stood before the whole village, and his head bald, and shining, and painted gold.'),
    ('כי הבן של הצייר צבע לו את הראש כשישן מהשתייה.', 'Because the painter’s son had painted his head while he slept off the drink.'),
    ('והאולם התפוצץ.', 'And the hall exploded.'),
    ('וככה נגמרה שנת הלימודים, והתחילה החופשה.', 'And so the school year ended, and the holiday began.'))]),

 ('The Trial', 'המשפט', [
  P(('בחופשה הגיע המשפט של פוטר.', 'In the holiday came Potter’s trial.'),
    ('וכל הכפר דיבר עליו, וטום לא יכול היה לברוח מהדיבורים.', 'And the whole village talked about it, and Tom could not escape the talk.'),
    ('כל לילה הוא הלך להאק, והם דיברו בסוד.', 'Every night he went to Huck, and they talked in secret.'),
    ('האק אמר: טום, סיפרת למישהו?', 'Huck said: Tom, did you tell anyone?'),
    ('טום אמר: לא, אני לא יכול, השבועה.', 'Tom said: no, I cannot, the oath.'),
    ("האק אמר: אף מילה, כי ג'ו האינדיאני יטביע אותנו כמו חתולים.", 'Huck said: not a word, because Injun Joe will drown us like cats.'),
    ('והם נשבעו עוד פעם.', 'And they swore once more.')),
  P(('והלכו לכלא, כמו בכל יום.', 'And went to the jail, as every day.'),
    ('ופוטר אמר מהחלון: ילדים, אתם האנשים הכי טובים בעולם.', 'And Potter said from the window: children, you are the best people in the world.'),
    ('מחר תולים אותי, ומגיע לי, הייתי שיכור, והרגתי.', 'Tomorrow they hang me, and I deserve it, I was drunk, and I killed.'),
    ('אבל תזכרו אותי לטובה, ואל תשתו אף פעם.', 'But remember me kindly, and never drink.'),
    ('והושיט את היד מהסורגים, ותפס את הידיים שלהם.', 'And put his hand through the bars, and held their hands.'),
    ('וטום חזר הביתה, ולא ישן.', 'And Tom went home, and did not sleep.'),
    ('ובחצות הוא יצא מהחלון, והלך למקום מסוים.', 'And at midnight he went out the window, and went to a certain place.')),
  P(('ביום המשפט בית המשפט היה מלא.', 'On the day of the trial the courthouse was full.'),
    ('פוטר יושב, חיוור, ושבור, והכבלים על הידיים שלו.', 'Potter sitting, pale, and broken, and the chains on his hands.'),
    ("וג'ו האינדיאני יושב בין העדים, והפנים שלו כמו אבן.", 'And Injun Joe sitting among the witnesses, and his face like stone.'),
    ('העדים סיפרו: הסכין של פוטר, ופוטר היה בבית הקברות, ופוטר רחץ דם בנהר בבוקר.', 'The witnesses told: Potter’s knife, and Potter was in the graveyard, and Potter washed blood in the river in the morning.'),
    ('ועורך הדין של פוטר לא שאל אף שאלה, והאנשים התפלאו.', 'And Potter’s lawyer asked no question, and the people were surprised.'),
    ('ואז עורך הדין קם, ואמר: אני קורא לטום סוייר.', 'And then the lawyer got up, and said: I call Tom Sawyer.')),
  P(("כל הפנים הסתובבו, וג'ו האינדיאני הסתובב גם.", 'Every face turned, and Injun Joe turned too.'),
    ('טום הלך לדוכן, רועד.', 'Tom walked to the stand, shaking.'),
    ('עורך הדין אמר: טום, איפה היית בלילה של הרצח, בחצות?', 'The lawyer said: Tom, where were you on the night of the murder, at midnight?'),
    ("טום הסתכל על ג'ו האינדיאני, והקול שלו נעלם.", 'Tom looked at Injun Joe, and his voice vanished.'),
    ('ואז הסתכל על פוטר, ואמר: בבית הקברות.', 'And then looked at Potter, and said: in the graveyard.'),
    ('וסיפר, סיפר הכול, מהחתול המת עד הסכין.', 'And told, told everything, from the dead cat to the knife.'),
    ('וככל שסיפר, הקול שלו התחזק, ובית המשפט שתק יותר.', 'And the more he told, the stronger his voice grew, and the more the court was silent.'),
    ("וכשהגיע לדקירה, ואמר: וג'ו האינדיאני לקח את הסכין ו...", 'And when he reached the stabbing, and said: and Injun Joe took the knife and...'),
    ('היה קול של זכוכית.', 'There was a sound of glass.'),
    ("ג'ו האינדיאני קפץ מהחלון, כמו נמר, ונעלם.", 'Injun Joe jumped through the window, like a tiger, and vanished.'))]),

 ('After the Trial', 'אחרי המשפט', [
  P(('טום נהיה גיבור עוד פעם, והפעם גיבור אמיתי.', 'Tom became a hero once more, and this time a real hero.'),
    ('העיתון כתב עליו, והשופט אמר שהוא יהיה איש גדול.', 'The newspaper wrote about him, and the judge said that he would be a great man.'),
    ('ופוטר יצא מהכלא, והאנשים חיבקו אותו, והוא בכה.', 'And Potter came out of the jail, and the people hugged him, and he cried.'),
    ('ביום טום היה הילד הכי מאושר בעולם.', 'By day Tom was the happiest boy in the world.'),
    ('ובלילה הילד הכי מפוחד בעולם.', 'And at night the most frightened boy in the world.'),
    ("כי ג'ו האינדיאני בחוץ, חופשי, והוא יודע מי סיפר.", 'Because Injun Joe was outside, free, and knew who had told.')),
  P(("כל קול בלילה, ג'ו האינדיאני.", 'Every sound at night, Injun Joe.'),
    ("כל פנים ברחוב, ג'ו האינדיאני.", 'Every face in the street, Injun Joe.'),
    ('והמשטרה חיפשה אותו בכל מקום, והביאו בלש מהעיר הגדולה.', 'And the police searched for him everywhere, and brought a detective from the big city.'),
    ('והבלש חיפש שבוע, ואמר: מצאתי רמז.', 'And the detective searched a week, and said: I found a clue.'),
    ('אבל רמז לא תולים.', 'But you do not hang a clue.'),
    ("והבלש הלך, וג'ו האינדיאני נשאר בחוץ.", 'And the detective left, and Injun Joe stayed outside.')),
  P(('והאק פחד יותר מטום.', 'And Huck was more afraid than Tom.'),
    ('הוא אמר: טום, שברת את השבועה.', 'He said: Tom, you broke the oath.'),
    ('טום אמר: לא יכולתי לראות את פוטר נתלה.', 'Tom said: I could not watch Potter hang.'),
    ('האק אמר: אני יודע, ואני לא מאשים אותך, אבל הוא יודע שהייתי איתך.', 'Huck said: I know, and I do not blame you, but he knows I was with you.'),
    ('טום אמר: הוא לא ראה אותנו.', 'Tom said: he did not see us.'),
    ('האק אמר: אבל הוא חושב.', 'Huck said: but he thinks.'),
    ('ושניהם ישבו, וכל אחד מסתכל לחושך מעל הכתף של השני.', 'And the two sat, and each looking into the dark over the other’s shoulder.')),
  P(("ועברו שבועות, וג'ו האינדיאני לא הופיע.", 'And weeks passed, and Injun Joe did not appear.'),
    ('ולאט לאט הפחד נהיה קל יותר.', 'And little by little the fear became lighter.'),
    ('וטום התחיל לחשוב על משהו אחר.', 'And Tom began to think about something else.'),
    ('מטמון.', 'Treasure.'),
    ('כי לכל ילד מגיע זמן שהוא רוצה לחפור ולמצוא מטמון.', 'Because for every boy there comes a time when he wants to dig and find a treasure.'),
    ('והוא הלך להאק, ואמר: האק, אתה רוצה שנהיה עשירים?', 'And he went to Huck, and said: Huck, do you want us to be rich?'),
    ('האק אמר: איך?', 'Huck said: how?'),
    ('טום אמר: חופרים.', 'Tom said: we dig.'))]),

 ('The Haunted House', 'הבית הריק', [
  P(('טום אמר: שודדי ים קוברים מטמונים מתחת לעץ מת, או בבית עם רוחות.', 'Tom said: pirates bury treasures under a dead tree, or in a house with ghosts.'),
    ('האק אמר: ואיך נדע איפה?', 'Huck said: and how do we know where?'),
    ('טום אמר: חופרים בכל מקום עד שמוצאים.', 'Tom said: we dig everywhere until we find.'),
    ('והם חפרו מתחת לעץ מת על הגבעה, יום שלם, ולא מצאו כלום.', 'And they dug under a dead tree on the hill, a whole day, and found nothing.'),
    ('טום אמר: הטעות היא שצריך לחפור בחצות, איפה שנופל הצל של הענף.', 'Tom said: the mistake is that one must dig at midnight, where the shadow of the branch falls.'),
    ('והם חפרו בחצות, ולא מצאו כלום.', 'And they dug at midnight, and found nothing.'),
    ('טום אמר: טוב, הבית עם הרוחות.', 'Tom said: fine, the house with the ghosts.')),
  P(('הבית עם הרוחות היה בקצה הכפר, ריק שנים.', 'The house with the ghosts was at the edge of the village, empty for years.'),
    ('החלונות שלו שבורים, והדלת שלו נטויה, והעשב עולה מהמדרגות.', 'Its windows broken, and its door leaning, and the grass rising from the steps.'),
    ('וכל האנשים אומרים שיש בו רוחות, ואף אחד לא מתקרב אליו.', 'And all the people say that there are ghosts in it, and no one goes near it.'),
    ('הם הלכו ביום, כי רוחות ישנות ביום.', 'They went by day, because ghosts sleep by day.'),
    ('ונכנסו לאט, והדלת חרקה, והלב שלהם דופק.', 'And went in slowly, and the door creaked, and their hearts pounding.'),
    ('החדר למטה: אבק, ועכבישים, ואח שבור.', 'The room below: dust, and spiders, and a broken fireplace.'),
    ('והמדרגות עולות למעלה.', 'And the stairs going up.')),
  P(('הם עלו למעלה, וראו שני חדרים ריקים.', 'They went up, and saw two empty rooms.'),
    ('ושמו את המכוש על הרצפה, ועמדו לרדת לחפור.', 'And put the pick on the floor, and were about to go down to dig.'),
    ('ושמעו קול.', 'And heard a sound.'),
    ('הדלת למטה.', 'The door below.'),
    ('טום לחש: רוחות?', 'Tom whispered: ghosts?'),
    ('האק לחש: ביום?', 'Huck whispered: by day?'),
    ('והם שכבו על הרצפה, והציצו מסדק בין הקרשים.', 'And they lay on the floor, and peeked through a crack between the boards.')),
  P(('שני אנשים.', 'Two men.'),
    ('אחד שלא ראו קודם, מלוכלך, וזקן.', 'One they had not seen before, dirty, and old.'),
    ('והשני, החירש והאילם, שהולך בכפר כבר שבוע, בבגדים ספרדיים, והשיער שלו ארוך.', 'And the other, the deaf and mute one, who has been walking in the village a week, in Spanish clothes, and his hair long.'),
    ('והם ישבו למטה, והתחילו לדבר.', 'And they sat below, and began to talk.'),
    ('והחירש והאילם דיבר.', 'And the deaf and mute one spoke.'),
    ("והקול שלו היה הקול של ג'ו האינדיאני.", 'And his voice was the voice of Injun Joe.'),
    ('וטום והאק, למעלה, לא נשמו.', 'And Tom and Huck, above, did not breathe.'))]),

 ('The Box of Gold', 'ארגז הזהב', [
  P(("ג'ו האינדיאני אמר: העבודה האחרונה, ואחריה אנחנו הולכים דרומה.", 'Injun Joe said: the last job, and after it we go south.'),
    ('הזקן אמר: העבודה מסוכנת, כל הכפר מכיר את הפנים שלך.', 'The old man said: the job is dangerous, the whole village knows your face.'),
    ("ג'ו האינדיאני אמר: ככה הם לא מכירים אותי, ואני לא הולך לפני שאני לוקח את מה שמגיע לי.", 'Injun Joe said: like this they do not know me, and I do not go before I take what is due to me.'),
    ('והם דיברו על כסף שהחביאו, שש מאות דולר, ורצו לקבור אותו בבית.', 'And they talked about money they had hidden, six hundred dollars, and wanted to bury it in the house.'),
    ("וג'ו האינדיאני קם לחפור בפינה, עם הסכין שלו.", 'And Injun Joe got up to dig in the corner, with his knife.'),
    ('ולמעלה, טום והאק, שומעים, וחולמים על שש המאות.', 'And above, Tom and Huck, hearing, and dreaming about the six hundred.')),
  P(('ואז הסכין עצרה על משהו.', 'And then the knife stopped on something.'),
    ("ג'ו אמר: עץ.", 'Joe said: wood.'),
    ('והם חפרו עם המכוש, והוציאו ארגז.', 'And they dug with the pick, and took out a box.'),
    ('ארגז ברזל ישן, כבד, ונעול.', 'An old iron box, heavy, and locked.'),
    ('והם שברו את המנעול, ופתחו אותו.', 'And they broke the lock, and opened it.'),
    ('זהב.', 'Gold.'),
    ('ארגז שלם של מטבעות זהב, אלפים, מבריקים באבק.', 'A whole box of gold coins, thousands, shining in the dust.'),
    ('הזקן אמר: זה המטמון של הכנופיה! הם היו כאן לפני שנים!', 'The old man said: this is the gang’s treasure! They were here years ago!'),
    ("וג'ו האינדיאני אמר: עכשיו לא צריך לעשות את העבודה האחרונה.", 'And Injun Joe said: now we do not need to do the last job.'),
    ('ואז אמר: לא, אני עושה אותה, העבודה היא לא בשביל הכסף, העבודה היא נקמה.', 'And then said: no, I do it, the job is not for the money, the job is revenge.')),
  P(("וברגע הזה ג'ו האינדיאני ראה את המכוש.", 'And in that moment Injun Joe saw the pick.'),
    ('מכוש חדש, ועליו אדמה רכה.', 'A new pick, and on it soft earth.'),
    ('הוא אמר: מי הביא את המכוש הזה?', 'He said: who brought this pick?'),
    ('והסתכל על המדרגות.', 'And looked at the stairs.'),
    ('וטום והאק, למעלה, שמעו את העץ חורק, כשהוא עולה.', 'And Tom and Huck, above, heard the wood creak, as he climbed.'),
    ('מדרגה, שתיים, שלוש.', 'One step, two, three.'),
    ('והם חשבו לקפוץ מהחלון, אבל לא יכלו לזוז.', 'And they thought of jumping from the window, but could not move.')),
  P(('ובמדרגה הרביעית, העץ הרקוב נשבר.', 'And on the fourth step, the rotten wood broke.'),
    ("וג'ו האינדיאני נפל למטה, על הזקן.", 'And Injun Joe fell down, on the old man.'),
    ('והוא קם ומקלל, ואמר: די, אם יש מישהו למעלה, שיישאר למעלה.', 'And he got up cursing, and said: enough, if there is someone above, let him stay above.'),
    ('ומי שרוצה לרדת, יורד.', 'And whoever wants to come down, comes down.'),
    ("והם לקחו את הארגז, וג'ו אמר: לא מחביאים אותו כאן, לוקחים אותו למספר שתיים, מתחת לצלב.", 'And they took the box, and Joe said: we do not hide it here, we take it to Number Two, under the cross.'),
    ('והם יצאו עם השקיעה, ואיתם הזהב.', 'And went out at sunset, and with them the gold.'),
    ('וטום והאק ירדו אחרי שעה, והרגליים שלהם רועדות.', 'And Tom and Huck came down after an hour, and their legs shaking.'),
    ('וטום אמר: מספר שתיים, מתחת לצלב, חייבים למצוא אותו.', 'And Tom said: Number Two, under the cross, we must find it.'))]),

 ('Number Two', 'מספר שתיים', [
  P(('מספר שתיים, מה זה מספר שתיים?', 'Number Two, what is Number Two?'),
    ('בית? אין בתים עם מספרים בכפר.', 'A house? There are no houses with numbers in the village.'),
    ('האק אמר: חדר! במלון!', 'Huck said: a room! At the inn!'),
    ('בכפר שני מלונות, ובכל מלון חדר מספר שתיים.', 'In the village two inns, and in every inn a room number two.'),
    ('במלון הראשון, החדר של עורך דין צעיר, ואין בו סוד.', 'At the first inn, the room of a young lawyer, and no secret in it.'),
    ('במלון השני, החדר נעול תמיד.', 'At the second inn, the room always locked.'),
    ('והבן של בעל המלון אמר לטום: אף אחד לא נכנס אליו חוץ מבלילה, וראיתי בו אור.', 'And the innkeeper’s son said to Tom: no one goes into it except at night, and I saw a light in it.'),
    ('טום אמר: זה הוא.', 'Tom said: that is it.')),
  P(('לחדר הייתה דלת מאחור, לסמטה צרה.', 'The room had a door at the back, to a narrow alley.'),
    ('והם עשו תוכנית: האק שומר על הסמטה כל לילה, וטום מנסה את המפתחות.', 'And they made a plan: Huck watches the alley every night, and Tom tries the keys.'),
    ('טום אסף את כל המפתחות של דודה פולי, וכל מפתח שמצא.', 'Tom gathered all of Aunt Polly’s keys, and every key he found.'),
    ('ובלילה חשוך, בלי ירח, הוא הלך לדלת מאחור, וניסה.', 'And on a dark night, without a moon, he went to the back door, and tried.'),
    ('מפתח, ומפתח, ומפתח.', 'Key, and key, and key.'),
    ('ואז נגע בדלת, והיא הייתה פתוחה.', 'And then touched the door, and it was open.')),
  P(('הוא נכנס, לאט, והאק בחוץ שומר.', 'He went in, slowly, and Huck outside watching.'),
    ('ואחרי שנייה טום יצא בריצה, וצעק: רוץ!', 'And a second later Tom came out running, and shouted: run!'),
    ('והם רצו עד המפעל הנטוש, ועמדו נושמים בכבדות.', 'And they ran to the abandoned factory, and stood breathing heavily.'),
    ('האק אמר: מה ראית?', 'Huck said: what did you see?'),
    ("טום אמר: ג'ו האינדיאני! ישן על הרצפה, לידו בקבוק, והזרוע שלו פתוחה.", 'Tom said: Injun Joe! Asleep on the floor, beside him a bottle, and his arm flung out.'),
    ('כמעט דרכתי על היד שלו.', 'I nearly stepped on his hand.'),
    ('האק אמר: והארגז?', 'Huck said: and the box?'),
    ("טום אמר: לא ראיתי ארגז, ראיתי רק את ג'ו האינדיאני, והכול ברח לי מהראש.", 'Tom said: I did not see a box, I saw only Injun Joe, and everything fled from my head.')),
  P(('טום אמר: אם הוא שיכור, הארגז בחדר, וצריך לחזור.', 'Tom said: if he is drunk, the box is in the room, and we must go back.'),
    ('האק אמר: אני לא חוזר.', 'Huck said: I am not going back.'),
    ('טום אמר: לא הלילה, אבל האק, אתה תשמור על הסמטה.', 'Tom said: not tonight, but Huck, you watch the alley.'),
    ('אם תראה אותו יוצא עם הארגז, בוא תעשה קול של חתול מתחת לחלון שלי.', 'If you see him leave with the box, come and make a cat’s sound under my window.'),
    ('ואם הוא לא יוצא, אני חוזר.', 'And if he does not leave, I go back.'),
    ('והם הסכימו, והאק התחיל לישון ביום, ולשמור בלילה.', 'And they agreed, and Huck began sleeping by day, and watching at night.'),
    ('לילה, ושניים, ושלושה.', 'One night, and two, and three.'))]),

 ('Huck Saves the Widow', 'האק מציל את האלמנה', [
  P(('בלילה הרביעי הדלת מאחור נפתחה.', 'On the fourth night the back door opened.'),
    ("והם יצאו ממנה ג'ו האינדיאני והזקן, ובידיים שלהם משהו.", 'And out of it came Injun Joe and the old man, and in their hands something.'),
    ('לא ארגז, קטן יותר.', 'Not a box, smaller.'),
    ('והם הלכו בסמטה, והאק מאחורי שניהם, יחף, כמו חתול.', 'And they walked in the alley, and Huck after them, barefoot, like a cat.'),
    ('הם הלכו לגבעה, לכיוון הבית של האלמנה.', 'They walked to the hill, toward the widow’s house.'),
    ('והאק חשב: הם קוברים את המטמון אצל האלמנה?', 'And Huck thought: are they burying the treasure at the widow’s?')),
  P(('והם עצרו מתחת לעץ, קרוב לבית, והאק עמד מאחורי שיח, ושמע.', 'And they stopped under a tree, close to the house, and Huck stood behind a bush, and listened.'),
    ('הזקן אמר: יש אור בבית, יש אצלה אנשים.', 'The old man said: there is a light in the house, she has people over.'),
    ("ג'ו האינדיאני אמר: נחכה עד שהם ילכו.", 'Injun Joe said: we wait until they go.'),
    ("הזקן אמר: ג'ו, בוא נעזוב את העבודה הזאת, האלמנה לא עשתה לך כלום.", 'The old man said: Joe, let us leave this job, the widow did nothing to you.'),
    ("ג'ו האינדיאני אמר: בעלה, בעלה היה השופט, ודן אותי למכות, מול הכפר.", 'Injun Joe said: her husband, her husband was the judge, and sentenced me to a beating, in front of the village.'),
    ('הוא מת, והיא תשלם במקומו.', 'He died, and she will pay instead of him.'),
    ('ואני לא רוצה להרוג אותה, אני רוצה לחתוך לה את הפנים.', 'And I do not want to kill her, I want to cut her face.')),
  P(('האק לא חיכה לשמוע את השאר.', 'Huck did not wait to hear the rest.'),
    ('הוא חזר אחורה, לאט, ואז רץ.', 'He went back, slowly, and then ran.'),
    ('רץ על הגבעה לבית של הזקן שיש לו שני בנים.', 'Ran up the hill to the house of the old man who has two sons.'),
    ('ודפק על הדלת בידיים, וצעק: תפתחו! תפתחו מהר!', 'And knocked on the door with his hands, and shouted: open! Open quickly!'),
    ('הזקן פתח, ואמר: מי אתה?', 'The old man opened, and said: who are you?'),
    ('האק אמר: האק, אל תספר לאף אחד שבאתי, אבל תשמע.', 'Huck said: Huck, do not tell anyone that I came, but listen.'),
    ('וסיפר הכול.', 'And told everything.')),
  P(('הזקן והבנים שלו לקחו את הרובים שלהם, והם יצאו לחושך.', 'The old man and his sons took their guns, and went out into the dark.'),
    ('והאק רץ אחרי שניהם עד השיח, ועמד, ושמע.', 'And Huck ran after them to the bush, and stood, and listened.'),
    ('שקט, ואז קול של רובים, וקולות, ורגליים רצות.', 'Silence, and then a sound of guns, and shouts, and running feet.'),
    ('והאק לא חיכה, רץ מהגבעה למטה, ולא עצר עד הכפר.', 'And Huck did not wait, ran down the hill, and did not stop until the village.'),
    ('ובבוקר כל הכפר ידע: מישהו תקף את האלמנה, והזקן גירש אותם.', 'And in the morning the whole village knew: someone had attacked the widow, and the old man had driven them off.'),
    ('אבל אף אחד לא ידע מי הזהיר את הזקן.', 'But no one knew who had warned the old man.'),
    ('חוץ מהזקן, והוא נשבע לשתוק.', 'Except the old man, and he had sworn to keep quiet.'))]),

 ('The Picnic', 'הטיול', [
  P(('באותו יום בקי עשתה טיול לכל הילדים של הכיתה.', 'That day Becky held a picnic for all the children of the class.'),
    ('ספינה, ונהר, ואוכל, ומערה.', 'A boat, and a river, and food, and a cave.'),
    ('והאימהות אמרו: הילדים ישנים אצל חברים אחרי הטיול, כדי שלא יחזרו בלילה.', 'And the mothers said: the children sleep at friends after the picnic, so that they do not come back at night.'),
    ('וטום הלך, כמובן, ובקי לידו, והאירוסים חזרו כמו שהיו.', 'And Tom went, of course, and Becky beside him, and the engagement came back as it had been.'),
    ('והם עלו על הספינה, והם ירדו ליד המערה הגדולה.', 'And they boarded the boat, and got off by the big cave.')),
  P(('המערה: פתח קטן בהר, ובתוכה מעברים וחדרים ודרכים בלי סוף.', 'The cave: a small opening in the mountain, and inside it passages and rooms and ways without end.'),
    ('כל ילד הכיר את המעברים הראשונים.', 'Every child knew the first passages.'),
    ('ואף אחד לא הכיר את הסוף שלה, כי אף אחד לא הגיע לסוף שלה.', 'And no one knew its end, because no one had reached its end.'),
    ('הם נכנסו עם נרות, וכל אחד רץ במעבר, וצעק, וצחק.', 'They went in with candles, and each ran in a passage, and shouted, and laughed.'),
    ('והקול חוזר מהקירות, והצל רוקד.', 'And the sound coming back from the walls, and the shadow dancing.'),
    ('וטום ובקי הלכו יחד, קצת יותר רחוק מהאחרים.', 'And Tom and Becky walked together, a little farther than the others.')),
  P(('ואז יותר רחוק.', 'And then farther.'),
    ('הם מצאו מעבר שאין עליו שמות על הקיר, כלומר אף אחד לא הגיע אליו.', 'They found a passage with no names on the wall, that is, no one had reached it.'),
    ('וטום כתב את השם שלו ואת השם שלה בעשן של הנר.', 'And Tom wrote his name and her name in the smoke of the candle.'),
    ('והם מצאו מעיין, ואגם קטן, ותקרה עם אבנים שמבריקות כמו כוכבים.', 'And they found a spring, and a small lake, and a ceiling with stones that shine like stars.'),
    ('ובקי אמרה: טום, עבר הרבה זמן, בוא נחזור.', 'And Becky said: Tom, a long time has passed, let us go back.'),
    ('וטום אמר: טוב.', 'And Tom said: fine.'),
    ('והם הלכו אחורה.', 'And they walked back.')),
  P(('והלכו, והלכו.', 'And walked, and walked.'),
    ('ולא ראו את השמות על הקיר.', 'And did not see the names on the wall.'),
    ('טום אמר: מכאן, לא, מכאן.', 'Tom said: this way, no, this way.'),
    ('וכל מעבר דומה לזה שלפניו.', 'And every passage like the one before it.'),
    ('ובקי אמרה: טום, אנחנו אבודים?', 'And Becky said: Tom, are we lost?'),
    ('וטום אמר: לא.', 'And Tom said: no.'),
    ('אבל הם היו.', 'But they were.'),
    ('ורחוק, על הספינה, הילדים עלו וחזרו, וכל אחד חשב שטום ובקי אצל מישהו אחר.', 'And far away, on the boat, the children boarded and went back, and each one thought that Tom and Becky were with someone else.'))]),

 ('Lost in the Cave', 'אבודים במערה', [
  P(('בקי בכתה, וטום אמר: בקי, נמצא את הדרך, תאמיני לי.', 'Becky cried, and Tom said: Becky, we will find the way, believe me.'),
    ('והוא צעק: אנשים! והקול חזר מהחושך, כמו צחוק.', 'And he shouted: people! And the sound came back from the dark, like a laugh.'),
    ('והם הלכו, וטום מחזיק את היד שלה, ומסתכל בכל מעבר.', 'And they walked, and Tom holding her hand, and looking into every passage.'),
    ('ואז שם לב לנר.', 'And then noticed the candle.'),
    ('זה היה חצי נר, ואחריו לבקי היה נר אחד.', 'It was half a candle, and after it Becky had one candle.'),
    ('ואחריו, חושך.', 'And after it, darkness.')),
  P(('הם ישבו ליד מעיין, אכלו את חתיכת העוגה האחרונה, ובקי נרדמה על הכתף שלו.', 'They sat by a spring, ate the last piece of cake, and Becky fell asleep on his shoulder.'),
    ('וטום ישב והסתכל על הנר, כשהוא יורד.', 'And Tom sat and looked at the candle, as it went down.'),
    ('וכשבקי התעוררה, היא אמרה: טום, הייתי בבית בחלום.', 'And when Becky woke, she said: Tom, I was at home in the dream.'),
    ('וטום אמר: בקי, אני לא יודע מה השעה, אולי ההורים שלנו כבר מחפשים אותנו.', 'And Tom said: Becky, I do not know what time it is, maybe our parents are already looking for us.'),
    ('ובקי אמרה: אולי, אבל ההורים שלנו חושבים שאנחנו אצל מישהו.', 'And Becky said: maybe, but our parents think that we are at someone’s.'),
    ('והם שתקו, והבינו שעד מחר, אף אחד לא מחפש.', 'And they were silent, and understood that until tomorrow, no one searches.')),
  P(('והנר האחרון כבה.', 'And the last candle went out.'),
    ('חושך, חושך שלא ראו כמוהו בחיים שלהם.', 'Darkness, a darkness they had never seen the like of in their lives.'),
    ('לא יד, ולא פנים, ולא הבדל בין עיניים פתוחות לעיניים סגורות.', 'No hand, and no face, and no difference between open eyes and closed eyes.'),
    ('בקי בכתה, וטום ישב לידה, ותפס את היד שלה, ולא דיבר.', 'Becky cried, and Tom sat beside her, and held her hand, and did not speak.'),
    ('ואחרי שעות, או ימים, הם לא יודעים, הם שמעו קול.', 'And after hours, or days, they do not know, they heard a sound.'),
    ('רחוק, קולות, אנשים.', 'Far away, shouts, people.'),
    ('טום צעק, וצעק, והם רצו בחושך לכיוון הקול.', 'Tom shouted, and shouted, and they ran in the dark toward the sound.'),
    ('ונפלו לבור, והם יצאו, והקול נעלם.', 'And fell into a hole, and got out, and the sound was gone.')),
  P(('הם חזרו למעיין, כי המעיין הדבר היחיד שהם מכירים.', 'They went back to the spring, because the spring was the only thing they knew.'),
    ('וטום הוציא מהכיס חוט של עפיפון, ארוך.', 'And Tom took from his pocket a kite string, long.'),
    ('הוא קשר את הקצה שלו לסלע ליד המעיין, ואמר: בקי, תישארי כאן.', 'He tied its end to a rock by the spring, and said: Becky, stay here.'),
    ('אני הולך במעברים, והחוט מחזיר אותי אלייך.', 'I go into the passages, and the string brings me back to you.'),
    ('היא אמרה: אל תלך רחוק.', 'She said: do not go far.'),
    ('והוא הלך, בחושך, היד שלו על הקיר, והחוט נפתח אחריו.', 'And he went, in the dark, his hand on the wall, and the string unwinding behind him.'))]),

 ('A Face in the Dark', 'פנים בחושך', [
  P(('טום הלך במעבר, והחוט נגמר, וחזר.', 'Tom went down a passage, and the string ran out, and came back.'),
    ('והלך במעבר שני, וחזר.', 'And went down a second passage, and came back.'),
    ('ובמעבר השלישי, הוא ראה אור.', 'And in the third passage, he saw a light.'),
    ('אור קטן, רחוק, זז.', 'A small light, far away, moving.'),
    ('והלב שלו קפץ, והוא צעק: כאן! אנחנו כאן!', 'And his heart jumped, and he shouted: here! We are here!'),
    ('והאור עצר, והתקרב, ועבר את הפינה.', 'And the light stopped, and came closer, and turned the corner.'),
    ('וטום ראה את הפנים מאחורי הנר.', 'And Tom saw the face behind the candle.')),
  P(("ג'ו האינדיאני.", 'Injun Joe.'),
    ('עומד בחושך, והנר ביד שלו, והפנים שלו מבריקות.', 'Standing in the dark, and the candle in his hand, and his face shining.'),
    ('וטום עמד במקום, לא יכול לזוז, ולא לנשום.', 'And Tom stood where he was, unable to move, and unable to breathe.'),
    ("וג'ו האינדיאני הסתכל לחושך, לכיוון הקול.", 'And Injun Joe looked into the dark, toward the sound.'),
    ('ואז הסתובב, ורץ, ונעלם.', 'And then turned, and ran, and vanished.'),
    ("הוא פחד, ג'ו האינדיאני פחד.", 'He was afraid, Injun Joe was afraid.'),
    ('כי הוא לא ידע מי צעק, ובמערה, קול מפחיד כל אחד.', 'Because he did not know who shouted, and in the cave, a voice frightens everyone.')),
  P(('טום חזר לבקי על החוט, ולא סיפר לה.', 'Tom went back to Becky along the string, and did not tell her.'),
    ('הוא אמר: לא מצאתי כלום, אני מנסה עוד פעם.', 'He said: I found nothing, I try once more.'),
    ('ובקי נהייתה חלשה, ולא דיברה הרבה.', 'And Becky had become weak, and did not talk much.'),
    ('היא אמרה: טום, אם אני אמות, תישאר לידי.', 'She said: Tom, if I die, stay beside me.'),
    ('וטום אמר: את לא תמותי, והלך.', 'And Tom said: you will not die, and went.'),
    ('והפעם הוא לקח מעבר רביעי, שלא ניסה.', 'And this time he took a fourth passage, that he had not tried.'),
    ('והלך, והלך, והחוט נגמר.', 'And walked, and walked, and the string ran out.')),
  P(('ובסוף החוט, הוא ראה משהו.', 'And at the end of the string, he saw something.'),
    ('לא אור של נר, אור אחר.', 'Not the light of a candle, another light.'),
    ('אפור, ורחוק, וקבוע.', 'Grey, and far, and steady.'),
    ('הוא עזב את החוט, וזחל לכיוון שלו.', 'He left the string, and crawled toward it.'),
    ('וזה היה סדק בסלע, קטן, בדיוק בשביל ילד.', 'And it was a crack in the rock, small, just for a boy.'),
    ('והוא יצא ממנו, והוא נפל על עשב.', 'And he came out of it, and fell on grass.'),
    ('ומעליו השמיים, והנהר מתחתיו, והשמש שוקעת.', 'And above him the sky, and the river beneath him, and the sun setting.'),
    ('וטום בכה, בפעם הראשונה מזה יומיים.', 'And Tom cried, for the first time in two days.'))]),

 ('Out of the Hill', 'יוצאים מההר', [
  P(('טום חזר בסדק, וזחל על החוט, עד בקי.', 'Tom went back through the crack, and crawled along the string, to Becky.'),
    ('הוא אמר: בקי, מצאתי את הדרך, יש שמש, יש נהר.', 'He said: Becky, I found the way, there is sun, there is a river.'),
    ('ובקי לא האמינה, ואז האמינה, ובכתה.', 'And Becky did not believe, and then believed, and cried.'),
    ('והם הלכו יחד, על החוט, ואז בסדק, והם יצאו.', 'And they walked together, along the string, and then through the crack, and came out.'),
    ('היה לילה.', 'It was night.'),
    ('והם ראו סירה על הנהר, וצעקו, והסירה באה.', 'And they saw a boat on the river, and shouted, and the boat came.'),
    ('והאנשים בה לא האמינו, כי הסדק היה חמישה מיל מהפתח של המערה.', 'And the people in it did not believe, because the crack was five miles from the cave’s opening.')),
  P(('ובכפר, כבר שלושה ימים מחפשים.', 'And in the village, they had been searching for three days.'),
    ('כל הגברים במערה, עם נרות וחבלים, צועקים במעברים.', 'All the men in the cave, with candles and ropes, shouting in the passages.'),
    ('ודודה פולי לא עזבה את המיטה, והשיער שלה נהיה לבן בשלושה ימים.', 'And Aunt Polly had not left the bed, and her hair had gone white in three days.'),
    ('וגם האימא של בקי.', 'And Becky’s mother too.'),
    ('ובחצות הפעמון צלצל, והאנשים צעקו ברחובות: מצאו אותם! מצאו אותם!', 'And at midnight the bell rang, and the people shouted in the streets: they found them! They found them!'),
    ('וכל הכפר יצא בבגדי הלילה, וצועק, וצוחק, ובוכה.', 'And the whole village came out in nightclothes, and shouting, and laughing, and crying.')),
  P(('טום נשאר במיטה שבוע, ובקי יותר.', 'Tom stayed in bed a week, and Becky more.'),
    ('והוא סיפר את הסיפור מאה פעם, וכל פעם ארוך יותר.', 'And he told the story a hundred times, and every time longer.'),
    ('ואחרי שבועיים הוא הלך לבקר את בקי, ופגש את השופט.', 'And after two weeks he went to visit Becky, and met the judge.'),
    ('והשופט אמר: טום, אף אחד לא יאבד יותר במערה הזאת.', 'And the judge said: Tom, no one will get lost in that cave any more.'),
    ('טום אמר: למה?', 'Tom said: why?'),
    ('השופט אמר: כי שמתי על הפתח שלה דלת ברזל, ונעלתי אותה בשלושה מנעולים.', 'The judge said: because I put an iron door on its opening, and locked it with three locks.'),
    ('לפני שבועיים.', 'Two weeks ago.'),
    ('והפנים של טום נהיו לבנות כמו נייר.', 'And Tom’s face went white as paper.'),
    ("הוא אמר: שופט! ג'ו האינדיאני בפנים!", 'He said: judge! Injun Joe is inside!')),
  P(('הם רצו למערה, שתים עשרה סירות, והשופט וטום בראשונה.', 'They raced to the cave, twelve boats, and the judge and Tom in the first.'),
    ('ופתחו את דלת הברזל.', 'And opened the iron door.'),
    ("וג'ו האינדיאני שכב מאחוריה, על הפנים.", 'And Injun Joe lay behind it, on his face.'),
    ('מת.', 'Dead.'),
    ('והפנים שלו אל הסדק מתחת לדלת, איפה שהאור נכנס.', 'And his face to the gap under the door, where the light came in.'),
    ('והסכין שלו שבורה, מהניסיון לחפור מתחת לדלת.', 'And his knife broken, from trying to dig under the door.'),
    ('וסביבו שאריות של נרות שנאכלו.', 'And around him remains of candles that had been eaten.'),
    ('וטום עמד, והרגיש משהו מוזר: לא שמחה, ולא צער.', 'And Tom stood, and felt something strange: not joy, and not grief.'),
    ('הוא הרגיש הקלה.', 'He felt relief.'),
    ('ובפעם הראשונה מהלילה של בית הקברות, טום ישן בלי חלום.', 'And for the first time since the night of the graveyard, Tom slept without a dream.'))]),

 ('The Treasure', 'המטמון', [
  P(('אחרי ההלוויה טום הלך להאק.', 'After the funeral Tom went to Huck.'),
    ('הוא אמר: האק, הזהב במערה.', 'He said: Huck, the gold is in the cave.'),
    ('האק אמר: איך אתה יודע?', 'Huck said: how do you know?'),
    ("טום אמר: מספר שתיים, מתחת לצלב, במערה, במעבר שראיתי בו את ג'ו האינדיאני, יש צלב שמישהו צייר בעשן על הסלע.", 'Tom said: Number Two, under the cross, in the cave, in the passage where I saw Injun Joe, there is a cross drawn in smoke on the rock.'),
    ('ראיתי אותו, ולא הבנתי אז.', 'I saw it, and did not understand then.'),
    ('האק אמר: אבל הדלת נעולה.', 'Huck said: but the door is locked.'),
    ('טום אמר: לא הסדק, את הסדק אף אחד לא מכיר חוץ ממני.', 'Tom said: not the crack, no one knows the crack except me.')),
  P(('הם לקחו נרות ושקים ואוכל, וסירה קטנה, והם ירדו בנהר.', 'They took candles and sacks and food, and a small boat, and went down the river.'),
    ('ונכנסו מהסדק, וזחלו פנימה, והגיעו למעבר, ולצלב.', 'And went in through the crack, and crawled inside, and reached the passage, and the cross.'),
    ('ומתחתיו סלע גדול, הם חפרו סביבו, ומצאו חלל.', 'And under it a big rock, they dug around it, and found a hollow.'),
    ('ובחלל, הארגז.', 'And in the hollow, the box.'),
    ('והם פתחו אותו, וספרו את הזהב לאור הנר.', 'And they opened it, and counted the gold by the light of the candle.'),
    ('שנים עשר אלף דולר.', 'Twelve thousand dollars.'),
    ('יותר ממה שכל הכפר ראה בחיים שלו.', 'More than the whole village had seen in its life.')),
  P(('הם הוציאו את הזהב בשקים, נשאו אותו לסירה, וחזרו לכפר בלילה.', 'They took the gold out in the sacks, carried it to the boat, and went back to the village at night.'),
    ('ובדרך הזקן מהגבעה תפס אותם, ואמר: בואו, האלמנה עושה מסיבה.', 'And on the way the old man from the hill caught them, and said: come, the widow is having a party.'),
    ('ובמסיבה האלמנה אמרה לפני כולם: האק הציל את החיים שלי.', 'And at the party the widow said before everyone: Huck saved my life.'),
    ('כי הזקן סיפר בסוף.', 'Because the old man had told in the end.'),
    ('והיא אמרה: ואני אקח אותו לגור אצלי, ואז אלמד אותו, ואז אכניס אותו לכנסייה.', 'And she said: and I will take him to live with me, and teach him, and bring him into the church.'),
    ('והפנים של האק נהיו אדומות, והוא הרגיש שהחיים נגמרו.', 'And Huck’s face went red, and he felt that life was over.'),
    ('וטום אמר: האק לא עני! האק עשיר!', 'And Tom said: Huck is not poor! Huck is rich!'),
    ('וכולם צחקו, וטום יצא, וחזר עם השקים, ושפך אותם על השולחן.', 'And everyone laughed, and Tom went out, and came back with the sacks, and poured them on the table.')),
  P(('והזהב נכנס לבנק, חצי לטום וחצי להאק.', 'And the gold went into the bank, half for Tom and half for Huck.'),
    ('והשופט אמר שטום יהיה עורך דין או גנרל.', 'And the judge said that Tom would be a lawyer or a general.'),
    ('והאק גר אצל האלמנה שלושה שבועות.', 'And Huck lived at the widow’s for three weeks.'),
    ('בגדים נקיים, ומזלג וסכין, ומיטה, וכנסייה.', 'Clean clothes, and a fork and knife, and a bed, and church.'),
    ('ואז נעלם.', 'And then vanished.'),
    ('וטום מצא אותו אחרי שלושה ימים, בחבית הישנה שלו, בבגדים הישנים שלו, עם המקטרת שלו.', 'And Tom found him after three days, in his old barrel, in his old clothes, with his pipe.'),
    ('האק אמר: טום, העושר לא בשבילי, אני לא יכול לנשום בבתים.', 'Huck said: Tom, riches are not for me, I cannot breathe in houses.'),
    ('טום אמר: האק, אם אתה לא חוזר לאלמנה, אני לא יכול לקחת אותך לכנופיה החדשה שלי.', 'Tom said: Huck, if you do not go back to the widow, I cannot take you into my new gang.'),
    ('בכנופיה כולם אנשים טובים.', 'In the gang everyone is respectable people.'),
    ('והאק חשב הרבה, ואמר: טוב, אני חוזר, אבל חודש.', 'And Huck thought a lot, and said: fine, I go back, but for a month.'),
    ('וככה נגמר הסיפור של טום סוייר.', 'And so ends the story of Tom Sawyer.'),
    ('כי זה סיפור של ילד, וכשהילד גדל, זה נהיה סיפור אחר.', 'Because it is a story of a boy, and when the boy grows up, it becomes another story.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('tomsawyer', {'en': 'The Adventures of Tom Sawyer',
                                        'he': 'הרפתקאות טום סוייר'}, 'intermediate',
                          CHAPTERS, unit='Chapter', unit_he='פרק', shelf=14, meta=META))
