#!/usr/bin/env python3
"""כלילה ודמנה — the animal fables, retold in modern Hebrew, graded to intermediate.

The Hebrew twin of pipeline/book_kalila.py. Ibn al-Muqaffaʿ made the Arabic in the eighth
century from the Sanskrit Panchatantra by way of Persian; it is public domain by age, and these
are retellings from the plots.

WHY IT BELONGS ON A HEBREW SHELF AS MUCH AS AN ARABIC ONE. Kalila and Dimna is one of the few
books that both literatures actually share: Rabbi Joel translated it into Hebrew in the twelfth
century, one of the earliest Hebrew translations of anything, and from his version it went into
Latin and out to the rest of Europe. A learner meeting it in Hebrew is not meeting a foreign
book — they are meeting one that came home.

The frame is a court: a philosopher tells a king a story, and inside it two jackals plot. That
frame is what makes it intermediate rather than beginner — the reader has to hold one story
inside another, which is a grammatical demand as much as a narrative one.

Deliberately unpointed; the vowels are looked up at ingest.

Run:  python3 pipeline/he_book_kalila.py --lang he            # check
      python3 pipeline/he_book_kalila.py --lang he --write    # emit
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from he_bookshelf import P, book                       # noqa: E402

META = {'work': 'Kalila and Dimna', 'author': 'Ibn al-Muqaffaʿ, from the Panchatantra',
        'year': '8th century', 'status': 'public domain — medieval'}

CHAPTERS = [
 ('The Philosopher and the King', 'החכם והמלך', [
  P(('לפני הרבה שנים היה בהודו מלך גדול וחזק.', 'Many years ago there was in India a great, strong king.'),
    ('בהתחלה הוא היה מלך טוב, ואחר כך הוא השתנה.', 'At first he was a good king, and then he changed.'),
    ('הוא נהיה קשה, ושמע רק את הדברים שהוא רצה לשמוע.', 'He became harsh, and heard only the things he wanted to hear.'),
    ('מי שאמר לו לא, הלך לבית הסוהר או מת.', 'Whoever said no to him went to prison or died.'),
    ('אז האנשים שתקו, וכל הארץ הייתה כמו בית שקט מפחד.', 'So the people were silent, and the whole land was like a house silent from fear.')),
  P(('באותה ארץ חי חכם זקן, והיו לו הרבה תלמידים.', 'In that land lived an old sage, and he had many students.'),
    ('יום אחד הוא אסף אותם ואמר: אני הולך אל המלך.', 'One day he gathered them and said: I am going to the king.'),
    ('התלמידים פחדו ואמרו: המורה, הוא יהרוג אותך.', 'The students were afraid and said: teacher, he will kill you.'),
    ('החכם אמר: אם אני רואה סכנה ושותק, בשביל מה למדתי?', 'The sage said: if I see danger and stay silent, what did I learn for?'),
    ('אבל אני לא הולך להתווכח איתו, אני הולך לספר לו סיפור.', 'But I am not going to argue with him, I am going to tell him a story.')),
  P(('החכם הלך לארמון ועמד ליד השער כמה ימים.', 'The sage went to the palace and stood by the gate for some days.'),
    ('בסוף נתנו לו להיכנס, והמלך ישב על הכיסא שלו.', 'At last they let him in, and the king sat on his throne.'),
    ('מסביב עמדו השרים, וכולם שתקו.', 'Around him stood the ministers, and all were silent.'),
    ('המלך שאל: מה אתה רוצה, זקן?', 'The king asked: what do you want, old man?'),
    ('החכם אמר: אני רוצה לספר לך על אריה, על שור ועל שני תנים.', 'The sage said: I want to tell you about a lion, an ox and two jackals.'),
    ('המלך צחק ואמר: חיות? בסדר, תספר.', 'The king laughed and said: animals? Fine, tell.')),
  P(('החכם התחיל לספר, והמלך הקשיב.', 'The sage began to tell, and the king listened.'),
    ('כל יום הוא סיפר סיפור, ובתוך כל סיפור היה עוד סיפור.', 'Every day he told a story, and inside every story was another story.'),
    ('המלך לא כעס, כי הסיפור היה על חיות ולא עליו.', 'The king was not angry, because the story was about animals and not about him.'),
    ('אבל בלילה הוא חשב: למה האריה בסיפור דומה לי?', 'But at night he thought: why does the lion in the story resemble me?'),
    ('לאט לאט הוא הבין שהסיפור הוא עליו.', 'Little by little he understood that the story was about him.'),
    ('הוא אמר לחכם: לא סיפרת לי על חיות, סיפרת לי על עצמי.', 'He said to the sage: you did not tell me about animals, you told me about myself.'),
    ('החכם אמר: סיפור הוא מראה, וכל אחד רואה בה את הפנים שלו.', 'The sage said: a story is a mirror, and everyone sees his own face in it.'),
    ('אלה הסיפורים שהוא סיפר, ואותם תקראו כאן.', 'These are the stories he told, and you will read them here.'))]),

 ('Two Jackals at the Lion’s Gate', 'שני התנים בשער', [
  P(('ביער רחוק חי אריה, והוא היה מלך על כל החיות.', 'In a far forest lived a lion, and he was king over all the animals.'),
    ('הוא היה חזק, אבל הוא גם אהב את מי שאמר לו מילים יפות.', 'He was strong, but he also loved those who said nice words to him.'),
    ('היו לו הרבה משרתים: זאבים, שועלים, עורבים ותנים.', 'He had many servants: wolves, foxes, crows and jackals.'),
    ('כל אחד מהם רצה להיות קרוב למלך יותר מהאחר.', 'Each of them wanted to be closer to the king than the other.')),
  P(('ליד השער של האריה חיו שני תנים, שני אחים.', 'By the lion’s gate lived two jackals, two brothers.'),
    ('הראשון נקרא כלילה, והשני נקרא דמנה.', 'The first was called Kalila, and the second was called Dimna.'),
    ('כלילה היה מסתפק במה שיש, ואמר: מה שיש לי מספיק לי.', 'Kalila was content with what there was, and said: what I have is enough for me.'),
    ('דמנה היה חכם ורצה לעלות גבוה, ולא ישן בלילה ממחשבות.', 'Dimna was clever and wanted to rise high, and did not sleep at night for thinking.'),
    ('הוא הסתכל על השרים שנכנסים אל המלך, וקינא בהם.', 'He watched the ministers going in to the king, and envied them.')),
  P(('יום אחד דמנה אמר לאח שלו: למה אנחנו עומדים ליד השער?', 'One day Dimna said to his brother: why are we standing by the gate?'),
    ('אנחנו חכמים יותר מכל השרים, והם בפנים ואנחנו בחוץ.', 'We are cleverer than all the ministers, and they are inside and we are outside.'),
    ('כלילה אמר: ומה אתה רוצה בפנים?', 'Kalila said: and what do you want inside?'),
    ('מי שמתקרב למלך מתקרב לאש, ומי שמתקרב לאש נשרף.', 'Whoever comes near the king comes near the fire, and whoever comes near the fire gets burned.'),
    ('דמנה אמר: אבל האש גם מחממת.', 'Dimna said: but the fire also warms.'),
    ('מי שמפחד מכל דבר נשאר כל החיים ליד השער.', 'Whoever is afraid of everything stays all his life by the gate.')),
  P(('כלילה אמר: ואיך תגיע אל המלך? הוא לא מכיר אותך.', 'Kalila said: and how will you reach the king? He does not know you.'),
    ('דמנה אמר: אני אחכה להזדמנות.', 'Dimna said: I will wait for the opportunity.'),
    ('המלך הוא כמו כל אחד, יום אחד הוא יצטרך מישהו.', 'The king is like anyone, one day he will need someone.'),
    ('וביום הזה אני אהיה שם.', 'And on that day I will be there.'),
    ('כלילה הזיז את הראש ושתק, כי הוא ידע שאחיו לא מקשיב.', 'Kalila shook his head and was silent, because he knew his brother was not listening.'),
    ('ובאותו לילה הגיעה ההזדמנות שדמנה חיכה לה.', 'And that very night came the opportunity Dimna had waited for.'))]),

 ('The Ox Called Shatraba', 'השור שנשאר בבוץ', [
  P(('סוחר עבר ביער עם עגלה ועם שור גדול וחזק.', 'A merchant passed through the forest with a cart and a big, strong ox.'),
    ('בדרך השור נפל בבוץ ולא הצליח לקום.', 'On the way the ox fell in the mud and could not get up.'),
    ('הסוחר חיכה יום אחד, ואז אמר: הוא ימות כאן, אני ממשיך.', 'The merchant waited one day, and then said: it will die here, I am going on.'),
    ('הוא השאיר את השור בבוץ והמשיך בדרך שלו.', 'He left the ox in the mud and went on his way.'),
    ('אבל אחרי יומיים השור קם, ומצא שדה ירוק ומים.', 'But after two days the ox got up, and found a green field and water.'),
    ('הוא אכל ושתה, והוא נהיה חזק, וכשהיה שמח הוא השמיע קול גדול.', 'It ate and drank, and grew strong, and when it was happy it bellowed loudly.')),
  P(('בלילה האריה שמע קול מוזר מרחוק.', 'At night the lion heard a strange sound from afar.'),
    ('קול גדול וחזק, שהוא לא שמע כמוהו בחיים שלו.', 'A big, strong sound, the like of which he had never heard in his life.'),
    ('האריה פחד, אבל הוא לא רצה שמישהו ידע שהוא פוחד.', 'The lion was afraid, but he did not want anyone to know he was afraid.'),
    ('הוא נשאר במקום שלו ולא יצא לצוד, לא ביום הזה ולא למחרת.', 'He stayed in his place and did not go out to hunt, not that day and not the next.'),
    ('החיות שמו לב, והתחילו ללחוש.', 'The animals noticed, and began to whisper.')),
  P(('דמנה עמד ליד השער וראה את הפחד בעיניים של המלך.', 'Dimna stood by the gate and saw the fear in the king’s eyes.'),
    ('הוא אמר לכלילה: זאת ההזדמנות.', 'He said to Kalila: this is the opportunity.'),
    ('הוא נכנס אל האריה, השתחווה ואמר: המלך, אתה נראה מודאג.', 'He went in to the lion, bowed and said: my king, you look worried.'),
    ('האריה אמר: ומי אתה?', 'The lion said: and who are you?'),
    ('הוא אמר: אני דמנה, המשרת שלך שעומד ליד השער.', 'He said: I am Dimna, your servant who stands by the gate.'),
    ('את הקול ששמעת, אני יכול ללכת ולראות מה הוא.', 'The sound you heard, I can go and see what it is.'),
    ('האריה התפלא, כי אף אחד לא דיבר על הקול לפניו.', 'The lion was surprised, because no one had spoken about the sound in front of him.'),
    ('אבל הוא אמר: לך, ואז תחזור עם תשובה.', 'But he said: go, and come back with an answer.')),
  P(('דמנה הלך לכיוון הקול, עד שהגיע לשדה ירוק.', 'Dimna walked toward the sound, until he reached a green field.'),
    ('שם הוא ראה את השור, השור הכי גדול שראה בחיים שלו.', 'There he saw the ox, the biggest ox he had seen in his life.'),
    ('דמנה צחק בלב ואמר: המלך פוחד משור שאוכל עשב.', 'Dimna laughed inside and said: the king is afraid of an ox that eats grass.'),
    ('הוא התקרב ואמר: אני השליח של האריה, מלך היער.', 'He approached and said: I am the messenger of the lion, king of the forest.'),
    ('הוא רוצה לראות אותך, ואם תבוא איתי אתה תהיה בטוח.', 'He wants to see you, and if you come with me you will be safe.'),
    ('השור פחד בהתחלה, אבל דמנה נשבע לו שלא יקרה לו כלום.', 'The ox was afraid at first, but Dimna swore to him that nothing would happen to him.'),
    ('והם הלכו יחד, השור הגדול והתן הקטן.', 'And they went together, the big ox and the little jackal.')),
  P(('כשהאריה ראה את השור, הוא הבין שהקול לא היה סכנה.', 'When the lion saw the ox, he understood that the sound had been no danger.'),
    ('הוא היה נבוך בגלל הפחד שלו, ובאותו זמן שמח.', 'He was ashamed of his fear, and at the same time glad.'),
    ('הוא אמר לדמנה: עשית מה שאף אחד לא עשה, מהיום אתה קרוב אליי.', 'He said to Dimna: you did what no one did, from today you are close to me.'),
    ('דמנה השתחווה, והלב שלו רקד.', 'Dimna bowed, and his heart danced.'),
    ('אבל הוא לא ידע שהוא הביא איתו את הצרה שתהרוס אותו.', 'But he did not know that he had brought with him the trouble that would destroy him.'))]),

 ('The Friendship That Grew', 'החברות שגדלה', [
  P(('בהתחלה האריה שאל את דמנה על כל דבר.', 'At first the lion asked Dimna about everything.'),
    ('ודמנה היה מאושר, כי הוא היה בפנים אחרי שהיה בחוץ.', 'And Dimna was happy, because he was inside after being outside.'),
    ('אבל האריה אהב לדבר גם עם השור.', 'But the lion loved to talk with the ox too.'),
    ('השור היה חכם, והוא ראה הרבה ארצות עם הסוחר.', 'The ox was wise, and he had seen many lands with the merchant.'),
    ('הוא סיפר על ערים, על שווקים ועל אנשים, והאריה הקשיב ושמח.', 'He told about cities, markets and people, and the lion listened and was glad.')),
  P(('הימים עברו, והאריה והשור ישבו יחד כל יום.', 'The days passed, and the lion and the ox sat together every day.'),
    ('מהבוקר עד הערב, ואף אחד לא יכול היה להיכנס אליהם.', 'From morning to evening, and no one could go in to them.'),
    ('השרים הישנים כעסו, ודמנה כעס יותר מכולם.', 'The old ministers were upset, and Dimna was more upset than all of them.'),
    ('הוא עמד ליד השער ושמע את הצחוק שלהם מבפנים.', 'He stood by the gate and heard their laughter from inside.'),
    ('אותו שער שהוא עמד לידו מההתחלה.', 'The same gate he had stood by from the beginning.')),
  P(('דמנה הלך אל אחיו ואמר: ראית מה קרה?', 'Dimna went to his brother and said: did you see what happened?'),
    ('אני הבאתי את השור בידיים שלי, ועכשיו השור קרוב למלך יותר ממני.', 'I brought the ox with my own hands, and now the ox is closer to the king than I am.'),
    ('פעם המלך שאל אותי, ועכשיו הוא שואל אותו.', 'Once the king asked me, and now he asks him.'),
    ('כלילה אמר: ומי אמר לך להביא אותו?', 'Kalila said: and who told you to bring him?'),
    ('עשית את זה בידיים שלך, אז למה אתה כועס על מישהו אחר?', 'You did it with your own hands, so why are you angry at someone else?')),
  P(('דמנה אמר: נכון, אני עשיתי את זה, ומה שעשיתי אני יכול לפרק.', 'Dimna said: true, I did it, and what I made I can undo.'),
    ('כלילה שאל: מה אתה מתכוון?', 'Kalila asked: what do you mean?'),
    ('דמנה אמר: אני רוצה להפריד בין האריה והשור.', 'Dimna said: I want to separate the lion and the ox.'),
    ('לא בכוח, כי אני חלש משניהם, אלא במילים.', 'Not by force, because I am weaker than both, but with words.'),
    ('כלילה פחד ואמר: אחי, מהדרך הזאת אף אחד לא חוזר.', 'Kalila was afraid and said: brother, from this road no one comes back.'),
    ('דמנה צחק ואמר: הדרך קשה למי שלא יודע ללכת, ואני יודע.', 'Dimna laughed and said: the road is hard for one who cannot walk it, and I can.'),
    ('כלילה שתק, ואז אמר: טוב, תן לי לספר לך סיפור.', 'Kalila was silent, and then said: fine, let me tell you a story.'))]),

 ('The Monkey and the Carpenter', 'הקוף והנגר', [
  P(('כלילה אמר: תקשיב, כי מי שנכנס לעבודה שלא שלו נגמר כמו הקוף.', 'Kalila said: listen, because whoever meddles in work not his own ends up like the monkey.'),
    ('דמנה שאל: איזה קוף?', 'Dimna asked: which monkey?'),
    ('כלילה אמר: היה נגר שעבד בגינה, ליד עץ גדול.', 'Kalila said: there was a carpenter who worked in a garden, by a big tree.'),
    ('ועל העץ ישב קוף, והסתכל עליו כל יום.', 'And in the tree sat a monkey, and watched him every day.')),
  P(('הנגר חתך קרש ארוך עם מסור.', 'The carpenter cut a long plank with a saw.'),
    ('כל פעם שהוא התקדם קצת, הוא שם יתד בחתך, כדי שהקרש יישאר פתוח.', 'Every time he got a little way, he put a wedge in the cut, so the plank would stay open.'),
    ('אחר כך הוא חתך עוד קצת, שם יתד שנייה, והוציא את הראשונה.', 'Then he cut a little more, put in a second wedge, and took out the first.'),
    ('הקוף הסתכל ואמר בלב: עבודה קלה, אני יכול לעשות אותה יותר טוב ממנו.', 'The monkey watched and said to himself: an easy job, I can do it better than him.')),
  P(('בצהריים הנגר הלך לאכול, והשאיר את הקרש ואת היתד במקום.', 'At noon the carpenter went to eat, and left the plank and the wedge where they were.'),
    ('הקוף ירד מהר והוא ישב על הקרש, כמו שהנגר ישב.', 'The monkey came down quickly and sat on the plank, as the carpenter had sat.'),
    ('הרגליים שלו היו בתוך החתך.', 'His legs hung down into the cut.'),
    ('הוא תפס את היתד והתחיל למשוך אותה.', 'He grabbed the wedge and began pulling it.'),
    ('היתד הייתה חזקה, אבל גם הקוף היה חזק, ובסוף היא יצאה.', 'The wedge was firm, but the monkey was strong too, and at last it came out.')),
  P(('רגע אחד, והקרש נסגר.', 'One moment, and the plank closed.'),
    ('הוא נסגר על הרגליים של הקוף ותפס אותו.', 'It closed on the monkey’s legs and held him.'),
    ('הוא צעק וצעק, ואף אחד לא שמע, כי הנגר היה רחוק ואכל.', 'He screamed and screamed, and no one heard, because the carpenter was far away eating.'),
    ('כשהנגר חזר ומצא אותו, הוא לא עזר לו, הוא הכה אותו.', 'When the carpenter came back and found him, he did not help him, he beat him.'),
    ('הוא אמר: לא אמרתי לך לעבוד בעבודה שלי.', 'He said: I did not tell you to work at my job.')),
  P(('כלילה שתק, ואז אמר: זה מה שקורה למי שנכנס לעבודה שלא שלו.', 'Kalila was silent, and then said: this is what happens to whoever meddles in work not his own.'),
    ('אתה תן, והאריה והשור הם לא העניין שלך.', 'You are a jackal, and the lion and the ox are not your business.'),
    ('דמנה אמר: אבל אני לא קוף, אני מבין מה אני עושה.', 'Dimna said: but I am not a monkey, I understand what I am doing.'),
    ('כלילה אמר: גם הקוף חשב ככה.', 'Kalila said: the monkey thought so too.'),
    ('אבל דמנה כבר החליט, והסיפור לא שינה כלום.', 'But Dimna had already decided, and the story changed nothing.'))]),

 ('Dimna Speaks to the Lion', 'דמנה מדבר אל האריה', [
  P(('למחרת דמנה הלך אל האריה והוא ישב לפניו בשקט.', 'The next day Dimna went to the lion and sat before him in silence.'),
    ('הוא לא אמר אף מילה, והפנים שלו היו עצובות.', 'He did not say a word, and his face was sad.'),
    ('האריה היה רגיל לשמוע את הקול שלו, אז הוא התפלא.', 'The lion was used to hearing his voice, so he was surprised.'),
    ('הוא שאל: מה קרה, דמנה? הרבה זמן לא ראיתי אותך.', 'He asked: what is wrong, Dimna? I have not seen you for a long time.'),
    ('דמנה אמר: שום דבר, המלך.', 'Dimna said: nothing, my king.'),
    ('האריה אמר: הפנים שלך אומרות משהו אחר, תדבר.', 'The lion said: your face says something else, speak.')),
  P(('דמנה אמר: יש משהו, אבל אני מפחד להגיד אותו.', 'Dimna said: there is something, but I am afraid to say it.'),
    ('כי אם אני אגיד, אתה תכעס עליי, ואם אני אשתוק, אני בוגד.', 'Because if I say it, you will be angry at me, and if I stay silent, I am a traitor.'),
    ('האריה אמר: אני המלך, ואני מחליט מי בוגד, תדבר.', 'The lion said: I am the king, and I decide who is a traitor, speak.'),
    ('דמנה נשם עמוק ואמר: השור.', 'Dimna sighed and said: the ox.'),
    ('האריה שאל: מה עם השור?', 'The lion asked: what about the ox?')),
  P(('דמנה אמר: השור מדבר עם החיות עליך, ואני שמעתי אותו באוזניים שלי.', 'Dimna said: the ox talks to the animals about you, and I heard him with my own ears.'),
    ('הוא אומר שהוא יותר חזק מהמלך, ושהוא ראה מלכים גדולים יותר במסעות שלו.', 'He says he is stronger than you, and that he saw greater kings than you on his travels.'),
    ('והוא אומר שהיער לא צריך אריה, הוא צריך מישהו חכם.', 'And he says the forest does not need a lion, it needs someone wise.'),
    ('והחיות מקשיבות לו, כי הוא קרוב אליך.', 'And the animals listen to him, because he is close to you.'),
    ('הפנים של האריה איבדו את הצבע, והוא אמר: השור הוא החבר שלי.', 'The lion’s face went pale, and he said: the ox is my friend.'),
    ('דמנה אמר: גם אני חשבתי ככה, ולכן חיכיתי כל כך הרבה זמן.', 'Dimna said: I thought so too, and that is why I waited so long.')),
  P(('האריה אמר: אבל הוא לא עשה כלום.', 'The lion said: but he has done nothing.'),
    ('דמנה אמר: עדיין לא, מי שמדבר היום עושה מחר.', 'Dimna said: not yet, whoever talks today acts tomorrow.'),
    ('ואז תשים לב כשתראה אותו בפעם הבאה.', 'And pay attention when you see him next time.'),
    ('אם הוא לא אשם, הוא יבוא כמו בכל יום.', 'If he is innocent, he will come as on any day.'),
    ('אבל אם הוא יבוא עם עיניים מבריקות והקרניים קדימה, תדע שהוא מתכנן משהו.', 'But if he comes with shining eyes and horns forward, know that he is planning something.'),
    ('האריה שתק הרבה זמן והתחיל לחשוב.', 'The lion was silent a long time and began to think.'),
    ('ומחשבה שנכנסת, קשה להוציא אותה.', 'And a thought that enters is hard to get out.'))]),

 ('Dimna Speaks to the Ox', 'דמנה מדבר אל השור', [
  P(('דמנה יצא מהאריה והלך ישר אל השור.', 'Dimna left the lion and went straight to the ox.'),
    ('השור ישב בשדה ואכל, וכשראה אותו הוא שמח.', 'The ox sat in the field eating, and when he saw him he was glad.'),
    ('הוא אמר: דמנה, החבר הראשון שלי ביער! איפה היית?', 'He said: Dimna, my first friend in the forest! Where were you?'),
    ('דמנה ישב לידו, עשה פנים עצובות, ועשה את אותו הדבר.', 'Dimna sat beside him, made a sad face, and did the same thing.')),
  P(('השור שאל: מה קרה?', 'The ox asked: what is wrong?'),
    ('דמנה אמר: אני החבר שלך, ולכן באתי להזהיר אותך.', 'Dimna said: I am your friend, and that is why I came to warn you.'),
    ('האריה רוצה שאתה תיעלם.', 'The lion wants to be rid of you.'),
    ('שמעתי אותו אומר לשרים: השור נהיה שמן, ומחר אני מזמין אתכם לבשר שלו.', 'I heard him say to the ministers: the ox has grown fat, and tomorrow I invite you to his meat.'),
    ('השור עמד במקום ואמר: לא יכול להיות, הוא החבר שלי.', 'The ox stood where he was and said: impossible, he is my friend.'),
    ('דמנה אמר: אריה הוא אריה, הוא אוכל בשר, ואתה בשר.', 'Dimna said: a lion is a lion, he eats meat, and you are meat.'),
    ('החברות ביניכם הייתה משחק, וכשהמשחק נגמר הוא חוזר לטבע שלו.', 'The friendship between you was a game, and when the game ends he goes back to his nature.')),
  P(('השור לא האמין בהתחלה.', 'The ox did not believe at first.'),
    ('הוא אמר: לא עשיתי לו כלום, למה שהוא יהרוג אותי?', 'He said: I did nothing to him, why would he kill me?'),
    ('דמנה אמר: מלכים לא צריכים סיבה.', 'Dimna said: kings do not need a reason.'),
    ('ואז תשים לב כשתראה אותו בפעם הבאה.', 'And pay attention when you see him next time.'),
    ('אם הוא יבוא עם עיניים אדומות והזנב מכה באדמה, תדע שהוא רוצה להרוג אותך.', 'If he comes with red eyes and his tail beating the ground, know that he means you harm.'),
    ('השור שאל: ואם זה ככה, מה אני עושה?', 'The ox asked: and if it is so, what do I do?'),
    ('דמנה אמר: תגן על עצמך, אתה גדול והקרניים שלך חדות.', 'Dimna said: defend yourself, you are big and your horns are sharp.')),
  P(('דמנה הלך, והשאיר את השור לבד בשדה.', 'Dimna went, and left the ox alone in the field.'),
    ('השור לא ישן באותו לילה, וכל פעם ששמע קול הוא קם.', 'The ox did not sleep that night, and every time he heard a sound he got up.'),
    ('ובצד השני של היער, גם האריה לא ישן.', 'And on the other side of the forest, the lion did not sleep either.'),
    ('כל אחד מהם פחד מהשני.', 'Each of them was afraid of the other.'),
    ('דמנה חזר אל כלילה ואמר: זהו, זרעתי.', 'Dimna went back to Kalila and said: it is done, I have sown.'),
    ('כלילה שאל: ומה תקצור?', 'Kalila asked: and what will you reap?'),
    ('דמנה לא ענה.', 'Dimna did not answer.'))]),

 ('The Fight', 'הקרב', [
  P(('בבוקר השור בא אל האריה כמו בכל יום.', 'In the morning the ox came to the lion as on any day.'),
    ('אבל הפעם הוא הלך לאט, עם הראש למטה והקרניים קדימה.', 'But this time he walked slowly, with his head low and his horns forward.'),
    ('הוא פחד, ומי שמפחד הולך ככה.', 'He was afraid, and one who is afraid walks like that.'),
    ('האריה ראה אותו מרחוק, והוא נזכר במילים של דמנה.', 'The lion saw him from afar, and remembered Dimna’s words.'),
    ('הוא אמר בלב: הקרניים קדימה, אז זה נכון.', 'He said to himself: the horns forward, so it is true.')),
  P(('האריה קם, העיניים שלו נהיו אדומות, והזנב שלו הכה באדמה.', 'The lion got up, his eyes went red, and his tail beat the ground.'),
    ('הוא כעס, ומי שכועס עומד ככה.', 'He was angry, and one who is angry stands like that.'),
    ('השור ראה את העיניים האדומות ואת הזנב, והוא נזכר במילים של דמנה.', 'The ox saw the red eyes and the tail, and remembered Dimna’s words.'),
    ('הוא אמר בלב: העיניים אדומות, אז זה נכון.', 'He said to himself: the eyes are red, so it is true.'),
    ('כל אחד ראה בשני את מה שדמנה אמר לו לראות.', 'Each saw in the other what Dimna had told him to see.'),
    ('ופחד דומה מאוד לשנאה, עד שאף אחד לא מבדיל ביניהם.', 'And fear looks very much like hatred, so that no one tells them apart.')),
  P(('אף אחד לא אמר מילה, ואף אחד לא שאל.', 'No one said a word, and no one asked.'),
    ('אם האריה היה שואל: שור, למה הקרניים שלך קדימה?', 'Had the lion asked: ox, why are your horns forward?'),
    ('השור היה עונה: כי אתה מפחיד אותי.', 'The ox would have answered: because I am afraid of you.'),
    ('ואם השור היה שואל: המלך, למה העיניים שלך אדומות?', 'And had the ox asked: my king, why are your eyes red?'),
    ('האריה היה עונה: כי אתה מפחיד אותי.', 'The lion would have answered: because I am afraid of you.'),
    ('והכול היה נגמר בשאלה אחת, אבל אף אחד לא שאל.', 'And everything would have ended with one question, but no one asked.')),
  P(('האריה קפץ, והשור הכה בקרניים שלו.', 'The lion leapt, and the ox struck with his horns.'),
    ('הם נלחמו בלי שאף אחד מהם רצה את הקרב.', 'They fought without either of them wanting the fight.'),
    ('האבק עלה, והחיות ברחו מהרעש.', 'The dust rose, and the animals fled from the noise.'),
    ('בסוף השור נפל על האדמה ומת.', 'At last the ox fell to the ground and died.'),
    ('והאריה עמד מעליו, ודם ירד מהכתף ומהחזה שלו.', 'And the lion stood over him, and blood ran from his shoulder and his chest.')),
  P(('כשהאבק ירד, האריה ישב ליד השור.', 'When the dust settled, the lion sat beside the ox.'),
    ('הכעס הלך, והצער נשאר לבד.', 'The anger had gone, and only the grief remained.'),
    ('הוא אמר: מה עשיתי? איבדתי את החבר הכי טוב שהיה לי.', 'He said: what have I done? I have lost the best friend I had.'),
    ('ומרחוק, בין העצים, דמנה הסתכל.', 'And from afar, among the trees, Dimna watched.'),
    ('ולידו כלילה, והוא בכה.', 'And beside him Kalila, and he wept.'))]),

 ('The Trial of Dimna', 'המשפט של דמנה', [
  P(('אחרי מה שקרה, האריה לא יצא מהמקום שלו כמה ימים.', 'After what happened, the lion did not leave his place for some days.'),
    ('הוא שאל את עצמו: השור רצה להרוג אותי, או שאני דמיינתי?', 'He asked himself: did the ox want to kill me, or did I imagine it?'),
    ('והחיות דיברו ביניהן בסוד.', 'And the animals talked among themselves in secret.'),
    ('כולן ראו את דמנה הולך וחוזר בין האריה והשור, וכולן הבינו.', 'They had all seen Dimna going back and forth between the lion and the ox, and they all understood.')),
  P(('אבל אף אחד לא העז לדבר, חוץ מאחת: האימא של האריה.', 'But no one dared to speak, except one: the lion’s mother.'),
    ('היא הייתה זקנה וחכמה, ולא פחדה מהבן שלה.', 'She was old and wise, and did not fear her son.'),
    ('היא באה אליו ואמרה: הרגת את החבר שלך בגלל מילה ששמעת ממישהו שאתה לא מכיר.', 'She came to him and said: you killed your friend because of a word you heard from someone you do not know.'),
    ('מי אמר לך שהשור רוצה להרוג אותך?', 'Who told you the ox wanted to kill you?'),
    ('האריה אמר: דמנה.', 'The lion said: Dimna.'),
    ('היא אמרה: ומי אמר לשור שאתה רוצה להרוג אותו?', 'She said: and who told the ox that you wanted to kill him?'),
    ('האריה שתק, ואז הוא הבין.', 'The lion was silent, and then he understood.')),
  P(('האריה ציווה לתפוס את דמנה, והביאו אותו לפני כל החיות.', 'The lion ordered Dimna seized, and they brought him before all the animals.'),
    ('השופט התחיל לשאול אותו, ודמנה ענה בחכמה.', 'The judge began to question him, and Dimna answered cleverly.'),
    ('הוא אמר: אני לא הרגתי אף אחד, האריה הרג את השור, לא אני.', 'He said: I killed no one, the lion killed the ox, not I.'),
    ('אני רק אמרתי מילים, ומילים הן לא חרב.', 'I only said words, and words are not a sword.'),
    ('השופט אמר: מילים הורגות כמו חרב, ולפעמים יותר.', 'The judge said: words kill like a sword, and sometimes more.'),
    ('חרב הורגת אחד, והמילה הרגה את השור, פצעה את האריה והרסה את היער.', 'A sword kills one, and the word killed the ox, wounded the lion and ruined the forest.')),
  P(('באו הרבה עדים, וכל אחד סיפר מה שראה.', 'Many witnesses came, and each told what he had seen.'),
    ('ובסוף דנו את דמנה למוות, וכך היה.', 'And at last they sentenced Dimna to death, and so it was.'),
    ('וכלילה לא יכול היה לחיות אחרי אחיו.', 'And Kalila could not live after his brother.'),
    ('הוא לא היה אשם, אבל הוא ידע ושתק.', 'He was not guilty, but he had known and stayed silent.'),
    ('והוא מת מצער אחרי כמה ימים.', 'And he died of grief after some days.')),
  P(('כאן החכם עצר ושתק.', 'Here the sage stopped and was silent.'),
    ('המלך שאל: ודמנה, למה הוא עשה את זה?', 'The king asked: and Dimna, why did he do it?'),
    ('החכם אמר: כי הוא שמע רק מה שהוא רצה, ואף אחד לא יכול היה לעצור אותו.', 'The sage said: because he heard only what he wanted, and no one could stop him.'),
    ('המלך הבין ולא אמר כלום, ואז אמר: תספר לי עוד.', 'The king understood and said nothing, and then said: tell me more.'))]),

 ('The Fox and the Drum', 'השועל והתוף', [
  P(('החכם אמר: המלך, אני אספר לך על השועל ששמע קול והאמין לו.', 'The sage said: my king, I will tell you about the fox that heard a sound and believed it.'),
    ('היה שועל רעב, שלא אכל שלושה ימים.', 'There was a hungry fox, that had not eaten for three days.'),
    ('הוא הלך ביער וחיפש כל דבר.', 'He walked through the forest and looked for anything at all.'),
    ('פתאום הוא שמע קול גדול ומפחיד: בום, בום, בום.', 'Suddenly he heard a big, frightening sound: boom, boom, boom.'),
    ('השועל עצר במקום, והשיער שלו עמד מפחד.', 'The fox stopped where he was, and his fur stood up in fear.')),
  P(('הוא אמר בלב: קול כזה, בטח יש לו בעלים, חיה גדולה מאוד.', 'He said to himself: a sound like this surely has an owner, a very big animal.'),
    ('וחיה גדולה יש בה הרבה בשר.', 'And a big animal has a lot of meat.'),
    ('הוא התקרב לאט לאט, וכל פעם שהתקרב הקול נהיה חזק יותר.', 'He approached little by little, and every time he came closer the sound grew louder.'),
    ('הוא הגיע לעץ גדול, וראה מה עושה את הקול.', 'He reached a big tree, and saw what was making the sound.'),
    ('זה היה תוף, תוף ישן שתלוי על ענף.', 'It was a drum, an old drum hanging on a branch.'),
    ('כל פעם שהרוח באה, הענף הכה על התוף, והתוף השמיע קול.', 'Every time the wind came, the branch struck the drum, and the drum made a sound.')),
  P(('השועל לא ידע מה זה תוף.', 'The fox did not know what a drum was.'),
    ('הוא אמר: הדבר הזה גדול ועגול והקול שלו חזק, בטח יש בו הרבה בשר.', 'He said: this thing is big and round and its sound is strong, surely there is a lot of meat in it.'),
    ('הוא קפץ על התוף, והתחיל לנשוך אותו בשיניים.', 'He jumped on the drum, and began biting it with his teeth.'),
    ('העור היה יבש וקשה, והשיניים שלו כאבו.', 'The skin was dry and hard, and his teeth hurt.'),
    ('אבל הוא המשיך לנשוך, כי הוא היה רעב.', 'But he kept biting, because he was hungry.')),
  P(('בסוף העור נקרע, והתוף נפתח.', 'At last the skin tore, and the drum opened.'),
    ('השועל הכניס את הראש פנימה, וחיפש.', 'The fox put his head inside, and searched.'),
    ('לא היה שם כלום, ריק, לא בשר, לא עצם, אפילו לא ריח.', 'There was nothing there, empty, no meat, no bone, not even a smell.'),
    ('השועל ישב על האדמה, רעב יותר מקודם, והשיניים שלו כאבו.', 'The fox sat on the ground, hungrier than before, and his teeth hurt.'),
    ('הוא אמר: כמה עבדתי בשביל קול.', 'He said: how hard I worked for a sound.')),
  P(('החכם אמר: הקול הכי גדול יוצא מהדבר הכי ריק.', 'The sage said: the biggest sound comes out of the emptiest thing.'),
    ('ודמנה היה ככה, קול גדול וריק בפנים.', 'And Dimna was like that, a big voice and empty inside.'),
    ('והאריה היה השועל, ששמע את הקול והאמין לו לפני שפתח וראה.', 'And the lion was the fox, that heard the sound and believed it before opening and looking.'),
    ('המלך שאל: ואני?', 'The king asked: and I?'),
    ('החכם אמר: אתה עדיין מקשיב, וזה יותר טוב משניהם.', 'The sage said: you are still listening, and that is better than both of them.'))]),

 ('The Three Fish', 'שלושת הדגים', [
  P(('החכם אמר: בבריכה רחוקה, בין שני הרים, חיו שלושה דגים.', 'The sage said: in a far pond, between two mountains, lived three fish.'),
    ('הם חיו יחד שנים, והיו חברים.', 'They had lived together for years, and were friends.'),
    ('אבל הם היו שונים בשכל.', 'But they were different in mind.'),
    ('הראשון היה חכם, וחשב על הדבר לפני שהוא קורה.', 'The first was wise, and thought about a thing before it happened.'),
    ('השני היה בינוני, וחשב כשהדבר קורה.', 'The second was middling, and thought when the thing happened.'),
    ('והשלישי לא חשב אף פעם.', 'And the third never thought at all.')),
  P(('יום אחד עברו דייגים ליד הבריכה.', 'One day fishermen passed by the pond.'),
    ('הם ראו את המים הנקיים ואת הדגים הגדולים, ושמחו.', 'They saw the clean water and the big fish, and were glad.'),
    ('אחד אמר לשני: היום אין לנו רשתות, מחר נחזור ואז נתפוס את כולם.', 'One said to the other: today we have no nets, tomorrow we come back and catch them all.'),
    ('ושלושת הדגים שמעו כל מילה.', 'And the three fish heard every word.')),
  P(('הדג החכם לא חיכה.', 'The wise fish did not wait.'),
    ('הוא אמר: הסכנה באה, והדרך עדיין פתוחה.', 'He said: the danger is coming, and the road is still open.'),
    ('היה נחל קטן שחיבר את הבריכה לנהר.', 'There was a small stream that joined the pond to the river.'),
    ('הוא שחה בו באותו לילה, יצא לנהר, וניצל.', 'He swam through it that same night, came out into the river, and was saved.'),
    ('הדג הבינוני אמר: נראה מחר, אולי הם לא יחזרו.', 'The middling fish said: we will see tomorrow, perhaps they will not come back.'),
    ('והשלישי אמר: דייגים? אני חי כאן שנים ולא קרה כלום.', 'And the third said: fishermen? I have lived here for years and nothing has happened.')),
  P(('למחרת בבוקר הדייגים חזרו, ואיתם רשתות.', 'The next morning the fishermen came back, and with them nets.'),
    ('והדבר הראשון שעשו, הם סגרו את הנחל באבן.', 'And the first thing they did, they closed the stream with a stone.'),
    ('הדג הבינוני ראה את האבן, והבין שהדרך סגורה.', 'The middling fish saw the stone, and understood the road was closed.'),
    ('הוא חשב מהר ואמר: אני לא יכול לברוח, אבל אני יכול לעשות את עצמי מת.', 'He thought fast and said: I cannot flee, but I can pretend to be dead.'),
    ('הוא התהפך על הגב, צף על המים, ולא זז.', 'He turned on his back, floated on the water, and did not move.'),
    ('הדייג תפס אותו, הריח אותו ואמר: זה מת כבר הרבה זמן.', 'The fisherman caught him, smelled him and said: this one has been dead a long time.'),
    ('הוא זרק אותו על החוף, והדג זחל לנהר וניצל.', 'He threw him on the bank, and the fish crawled to the river and was saved.')),
  P(('והשלישי המשיך לשחות ימינה ושמאלה.', 'And the third kept swimming right and left.'),
    ('כל פעם שהרשת באה, הוא ברח לצד אחד, ומצא רשת אחרת.', 'Every time the net came, he fled to one side, and found another net.'),
    ('ובסוף הוא נתפס.', 'And at last he was caught.'),
    ('החכם אמר: לחשוב לפני הסכנה טוב יותר מלחשוב אחריה.', 'The sage said: to think before the danger is better than to think after it.'),
    ('ולחשוב אחריה טוב יותר מלא לחשוב בכלל.', 'And to think after it is better than not to think at all.'),
    ('המלך שאל: ואיזה דג אני?', 'The king asked: and which fish am I?'),
    ('החכם צחק ואמר: מי ששואל את השאלה הזאת הוא לא השלישי.', 'The sage laughed and said: whoever asks that question is not the third.'))]),

 ('The Hare and the Lion', 'הארנב והאריה', [
  P(('החכם אמר: ביער אחר היה אריה שאכל מהחיות כל יום.', 'The sage said: in another forest there was a lion that ate from the animals every day.'),
    ('הוא לא צד אחד בלבד, הוא הרג הרבה, ואכל אחד.', 'He did not hunt only one, he killed many, and ate one.'),
    ('החיות פחדו שכולן ייגמרו.', 'The animals feared they would all be finished.'),
    ('הן התאספו, באו אליו ואמרו: המלך, יש לנו הצעה.', 'They gathered, came to him and said: my king, we have a proposal.'),
    ('כל יום נשלח לך אחת מאיתנו לבד, ואתה תאכל אותה בלי מאמץ.', 'Every day we send you one of us alone, and you eat it without effort.'),
    ('ואתה לא יוצא לצוד ולא הורג אף אחת אחרת.', 'And you do not go out to hunt and do not kill any other.'),
    ('האריה חשב והסכים, האוכל בא לבד, למה להתאמץ?', 'The lion thought and agreed, the food comes by itself, why make an effort?')),
  P(('הימים עברו, וכל יום אחת הלכה ולא חזרה.', 'The days passed, and every day one went and did not return.'),
    ('ויום אחד הגיע התור של ארנב קטן.', 'And one day the turn came to a small hare.'),
    ('הוא היה קטן, אבל הוא היה החכם ביותר ביער.', 'He was small, but he was the cleverest in the forest.'),
    ('הוא אמר לחיות: אני הולך, אבל תנו לי ללכת לאט.', 'He said to the animals: I am going, but let me go slowly.'),
    ('ואם אני אחזור, כל היער יחזור איתי.', 'And if I come back, the whole forest comes back with me.'),
    ('הן לא הבינו מה הוא מתכוון, אבל נתנו לו ללכת.', 'They did not understand what he meant, but let him go.')),
  P(('הארנב הלך לאט בכוונה, ואיחר עד אחרי הצהריים.', 'The hare went slowly on purpose, and was late until after noon.'),
    ('כשהגיע, האריה היה רעב וכועס.', 'When he arrived, the lion was hungry and angry.'),
    ('הוא צעק בקול גדול: איפה היית? ולמה באת לבד, קטן כזה?', 'He roared: where were you? And why did you come alone, so small?'),
    ('הארנב אמר ברעד: המלך, לא באתי לבד.', 'The hare said, trembling: my king, I did not come alone.'),
    ('שלחו אותי עם ארנב אחר, גדול ושמן ממני.', 'They sent me with another hare, bigger and fatter than me.'),
    ('אבל בדרך יצא עלינו אריה, ולקח אותו.', 'But on the road a lion came out at us, and took him.'),
    ('האריה אמר: אריה? ביער שלי?', 'The lion said: a lion? In my forest?'),
    ('הארנב אמר: והוא אמר שהוא המלך, לא אתה.', 'The hare said: and he said that he is the king, not you.')),
  P(('האריה קם, והשיער שלו עמד, והוא אמר: קח אותי אליו.', 'The lion got up, his mane bristled, and he said: take me to him.'),
    ('הארנב הלך לפניו עד שהגיע לבאר ישנה ועמוקה.', 'The hare walked ahead of him until he reached an old, deep well.'),
    ('הוא אמר: הוא כאן, למטה, מתחבא.', 'He said: he is here, below, hiding.'),
    ('האריה הסתכל לתוך הבאר, וראה אריה למטה.', 'The lion looked into the well, and saw a lion below.'),
    ('זאת הייתה הבבואה שלו במים, אבל הוא לא ידע.', 'It was his own reflection in the water, but he did not know.'),
    ('הוא צעק עליו, והאריה שלמטה צעק גם.', 'He roared at it, and the lion below roared too.'),
    ('והקול חזר מהבאר חזק יותר מהקול שלו.', 'And the sound came back from the well stronger than his own voice.')),
  P(('האריה אמר: אתה צועק עליי? אני המלך!', 'The lion said: you roar at me? I am the king!'),
    ('והוא קפץ על הבבואה שלו.', 'And he leapt at his reflection.'),
    ('הוא נפל לבאר, ולא יצא.', 'He fell into the well, and did not come out.'),
    ('הארנב חזר ליער לבד, ואמר: זהו.', 'The hare went back to the forest alone, and said: it is done.'),
    ('אף אחד לא האמין, עד שהלכו וראו את הבאר.', 'No one believed, until they went and saw the well.'),
    ('החכם אמר: החזק שלא חושב, החלש שחושב הורג אותו.', 'The sage said: the strong one who does not think, the weak one who thinks kills him.'),
    ('והדבר שהורג מלך יותר מכול, זה לראות אויב בכל מקום.', 'And the thing that kills a king most of all is seeing an enemy everywhere.'))]),

 ('The Ringdove and the Net', 'היונה והרשת', [
  P(('החכם אמר: עכשיו אני אספר לך על חברים, כי חברים חשובים יותר ממלך.', 'The sage said: now I will tell you about friends, because friends matter more than a king.'),
    ('היה עץ גדול ליד עיר, ועליו קן של עורב.', 'There was a big tree by a city, and in it a crow’s nest.'),
    ('יום אחד העורב ראה צייד הולך מתחת לעץ, עם רשת ועם חיטה.', 'One day the crow saw a hunter walking under the tree, with a net and with wheat.'),
    ('הצייד פרש את הרשת על האדמה, פיזר עליה חיטה, והתחבא.', 'The hunter spread the net on the ground, scattered wheat over it, and hid.'),
    ('העורב אמר: הוא בא בשביל מישהו, ואני רוצה לראות מי.', 'The crow said: he has come for someone, and I want to see who.')),
  P(('אחרי זמן קצר עברה להקת יונים בשמיים.', 'A little later a flock of doves passed in the sky.'),
    ('בראש עפה יונה גדולה, ועל הצוואר שלה טבעת.', 'At their head flew a big dove, with a ring around her neck.'),
    ('היונים ראו את החיטה מלמעלה ואמרו: אוכל!', 'The doves saw the wheat from above and said: food!'),
    ('היונה הגדולה אמרה: חכו, חיטה באמצע האדמה בלי סיבה?', 'The big dove said: wait, wheat in the middle of the ground for no reason?'),
    ('אבל הן היו רעבות, ולא הקשיבו.', 'But they were hungry, and did not listen.'),
    ('כולן ירדו לאדמה, והיא ירדה איתן, וכולן נפלו ברשת.', 'They all came down to the ground, and she came down with them, and they all fell into the net.')),
  P(('כל יונה התחילה למשוך לכיוון שלה.', 'Every dove began pulling in her own direction.'),
    ('אחת ימינה, אחת שמאלה, אחת למעלה.', 'One to the right, one to the left, one upward.'),
    ('והרשת לא זזה בכלל, כי כל משיכה ביטלה את השנייה.', 'And the net did not move at all, because every pull cancelled the other.'),
    ('והצייד יצא מהמחבוא והתחיל ללכת אליהן, וצחק.', 'And the hunter came out of his hiding place and began walking toward them, laughing.'),
    ('היונה הגדולה אמרה: תקשיבו! אם נמשיך ככה, כולנו נמות.', 'The big dove said: listen! If we go on like this, we all die.'),
    ('אף אחת לא מושכת לבד, כולן יחד, למעלה, באותו רגע.', 'No one pulls alone, all together, upward, at the same moment.'),
    ('כשאני סופרת: אחת, שתיים, שלוש!', 'When I count: one, two, three!')),
  P(('היא ספרה, וכולן משכו יחד.', 'She counted, and they all pulled together.'),
    ('והרשת עלתה מהאדמה, ועפה איתן.', 'And the net rose from the ground, and flew with them.'),
    ('הצייד רץ אחרי היונים, והסתכל על הרשת בשמיים.', 'The hunter ran after them, and looked at the net in the sky.'),
    ('הוא אמר: הן ייפלו, רשת כבדה, ויונים.', 'He said: they will fall, a heavy net, and doves.'),
    ('אבל היונה הגדולה הובילה אותן מעל ההר, למקום שהוא לא הגיע אליו.', 'But the big dove led them over the mountain, to a place he could not reach.'),
    ('והעורב עף אחרי היונים, כי הוא רצה לראות איך הסיפור נגמר.', 'And the crow flew after them, because he wanted to see how the story ended.'))]),

 ('The Mouse Who Cut the Net', 'העכבר שחתך את הרשת', [
  P(('היונים עפו עד שהגיעו לגבעה, ובה חור של עכבר.', 'The doves flew until they reached a hill, and in it a mouse’s hole.'),
    ('העכבר היה חבר של היונה הגדולה מזמן.', 'The mouse had long been a friend of the big dove.'),
    ('היו לו מאה פתחים לחור שלו, כדי לברוח ממאה סכנות.', 'He had a hundred doors to his hole, to escape a hundred dangers.'),
    ('היונה קראה: חבר שלי! חבר שלי!', 'The dove called: my friend! My friend!'),
    ('העכבר יצא מפתח אחד, ראה את הרשת ואת היונים בתוכה, והבין.', 'The mouse came out of one door, saw the net and the doves inside it, and understood.')),
  P(('העכבר רץ אל הרשת, והתחיל לחתוך את החבלים בשיניים.', 'The mouse ran to the net, and began cutting the ropes with his teeth.'),
    ('אבל הוא התחיל מיונה אחרת, לא מהיונה הגדולה.', 'But he began with another dove, not with the big dove.'),
    ('היונה הגדולה אמרה: אני החברה שלך, למה לא ממני קודם?', 'The big dove said: I am your friend, why not from me first?'),
    ('העכבר אמר בזמן שהוא חתך: בדיוק בגלל זה.', 'The mouse said as he cut: exactly because of that.'),
    ('השיניים שלי יתעייפו, ואולי אני אעצור לפני שאני מסיים.', 'My teeth will get tired, and maybe I will stop before I finish.'),
    ('אם אני מתחיל איתך, את תהיי חופשייה והאחרות יישארו תפוסות.', 'If I begin with you, you will be free and the others will stay caught.'),
    ('והן יגידו: המנהיגה הצילה את עצמה ושכחה אותנו.', 'And they will say: the leader saved herself and forgot us.')),
  P(('אבל אם אני מתחיל מהן, אני אמשיך לחתוך עד שאגיע אלייך.', 'But if I begin with them, I will keep cutting until I reach you.'),
    ('כי אני יודע שאת האחרונה, ואני לא אעזוב אותך.', 'Because I know you are the last, and I cannot leave you.'),
    ('היונה הגדולה אמרה: בגלל זה אתה החבר שלי.', 'The big dove said: that is why you are my friend.'),
    ('והעכבר חתך יונה אחרי יונה, והן עפו אחת אחת.', 'And the mouse cut dove after dove, and they flew off one by one.'),
    ('ובסוף הוא חתך את החבל של היונה הגדולה, והיא עפה.', 'And at last he cut the big dove’s rope, and she flew.')),
  P(('החכם אמר: המנהיג משתחרר אחרון.', 'The sage said: the leader is freed last.'),
    ('ומי שיוצא ראשון הוא לא מנהיג, הוא בורח.', 'And whoever gets out first is not a leader, he is a runaway.'),
    ('המלך שאל: והעכבר הזה, מאיפה הוא למד את החכמה הזאת?', 'The king asked: and this mouse, where did he learn this wisdom?'),
    ('החכם אמר: ממאה פתחים, מי שחושב על מאה סכנות חושב על מאה חברים.', 'The sage said: from a hundred doors, whoever thinks of a hundred dangers thinks of a hundred friends.'),
    ('והעורב שהסתכל, החליט משהו.', 'And the crow who had been watching decided something.'))]),

 ('The Four Friends', 'ארבעת החברים', [
  P(('העורב ירד על הגבעה, ועמד לפני החור של העכבר.', 'The crow came down onto the hill, and stood before the mouse’s hole.'),
    ('הוא קרא: עכבר, צא, אני רוצה להיות החבר שלך.', 'He called: mouse, come out, I want to be your friend.'),
    ('העכבר הוציא את הראש מפתח רחוק, ואמר: אתה? אתה עורב!', 'The mouse put his head out of a far door, and said: you? You are a crow!'),
    ('עורבים אוכלים עכברים, איך אתה רוצה להיות החבר שלי?', 'Crows eat mice, how can you want to be my friend?'),
    ('העורב אמר: ראיתי מה עשית בשביל היונים.', 'The crow said: I saw what you did for the doves.'),
    ('ואמרתי: אחד כזה, אני רוצה להיות החבר שלו, לא לאכול אותו.', 'And I said: one like this, I want to be his friend, not eat him.')),
  P(('העכבר אמר: הטבע חזק יותר מהמילים.', 'The mouse said: nature is stronger than words.'),
    ('היום אתה אומר חבר, ומחר כשתהיה רעב, תיזכר שאני עכבר.', 'Today you say friend, and tomorrow when you are hungry, you will remember that I am a mouse.'),
    ('העורב אמר: אני אשנה את הטבע שלי בשבילך.', 'The crow said: I will change my nature for you.'),
    ('ואם אתה לא מאמין, אני אשאר כאן ליד הפתח עד שתאמין.', 'And if you do not believe, I will stay here by the door until you believe.'),
    ('העורב ישב ליד הפתח יום, ויומיים, ושלושה.', 'The crow sat by the door a day, two days, and three.'),
    ('הוא הביא אוכל, שם אותו ליד הפתח, וחזר למקום שלו.', 'He brought food, put it by the door, and went back to his place.'),
    ('וביום הרביעי העכבר יצא והוא ישב לידו.', 'And on the fourth day the mouse came out and sat beside him.')),
  P(('הם נהיו חברים, ועם הימים העכבר התחיל לרכוב על הגב של העורב.', 'They became friends, and with the days the mouse began riding on the crow’s back.'),
    ('הם עפו יחד לבריכה גדולה, ובה צב שהיה חבר של העורב.', 'They flew together to a big pond, and in it a tortoise who was the crow’s friend.'),
    ('הצב היה שקט ואיטי, אבל המילים שלו היו שוות משהו.', 'The tortoise was quiet and slow, but his words were worth something.'),
    ('הוא אמר: ברוך הבא לעכבר, החבר של החבר שלי הוא החבר שלי.', 'He said: welcome to the mouse, the friend of my friend is my friend.'),
    ('ושלושת החברים חיו ליד המים, וכל יום דיברו עד שהשמש שקעה.', 'And the three lived by the water, and every day talked until the sun went down.')),
  P(('ויום אחד צבי בא בריצה אל הבריכה, והוא פחד.', 'And one day a gazelle came running to the pond, and he was afraid.'),
    ('הוא שתה מהר, והסתכל אחורה כל הזמן.', 'He drank quickly, and kept looking behind him.'),
    ('הצב אמר: מה קרה? אין כאן ציידים.', 'The tortoise said: what is wrong? There are no hunters here.'),
    ('הצבי אמר: היו, אני בורח מהם מהבוקר.', 'The gazelle said: there were, I have been fleeing them since morning.'),
    ('העורב אמר: די, תישאר איתנו, כאן בטוח.', 'The crow said: enough, stay with us, here it is safe.'),
    ('והצבי נהיה הרביעי שלהם.', 'And the gazelle became their fourth.'),
    ('החכם אמר: עורב, עכבר, צב וצבי, אף אחד מהם לא דומה לשני.', 'The sage said: a crow, a mouse, a tortoise and a gazelle, none of them resembles the other.'),
    ('וזה מה שהציל אותם.', 'And that is what saved them.'))]),

 ('The Gazelle in the Trap', 'הצבי מציל את הצב', [
  P(('יום אחד הצבי הלך לאכול כמו בכל יום, ולא חזר.', 'One day the gazelle went to graze as on any day, and did not come back.'),
    ('השמש שקעה, והוא עדיין לא היה שם.', 'The sun set, and he still was not there.'),
    ('הצב אמר: הצבי אף פעם לא מאחר, קרה לו משהו.', 'The tortoise said: the gazelle is never late, something has happened to him.'),
    ('העורב אמר: אני אעוף ואז אחפש אותו מלמעלה.', 'The crow said: I will fly and look for him from above.'),
    ('והוא עף מעל היער, וחיפש וחיפש.', 'And he flew over the forest, and searched and searched.')),
  P(('בסוף הוא מצא אותו ליד הדרך, תפוס במלכודת של צייד.', 'At last he found him by the road, caught in a hunter’s trap.'),
    ('החבל היה קשור על הרגל שלו, והוא לא יכול היה לזוז.', 'The rope was tied around his leg, and he could not move.'),
    ('הוא אמר: עורב, לך, הצייד יחזור בבוקר.', 'He said: crow, go, the hunter will come back in the morning.'),
    ('העורב אמר: אני הולך, אבל אני חוזר.', 'The crow said: I am going, but I am coming back.'),
    ('הוא עף לבריכה, לקח את העכבר על הגב, וחזר.', 'He flew to the pond, took the mouse on his back, and came back.'),
    ('והעכבר התחיל לחתוך את החבל בשיניים, חוט אחרי חוט.', 'And the mouse began cutting the rope with his teeth, strand after strand.')),
  P(('אבל הצב לא יכול היה להישאר לבד.', 'But the tortoise could not stay alone.'),
    ('הוא אמר: החבר שלי בסכנה ואני יושב?', 'He said: my friend is in danger and I sit?'),
    ('והוא בא ברגל, לאט, כי הוא איטי.', 'And he came on foot, slowly, because he is slow.'),
    ('כשהגיע, העכבר סיים את החבל, והצבי היה חופשי.', 'When he arrived, the mouse had finished the rope, and the gazelle was free.'),
    ('העורב אמר: צב, למה באת? אתה לא יכול לרוץ!', 'The crow said: tortoise, why did you come? You cannot run!'),
    ('ובאותו רגע הצייד הופיע מרחוק.', 'And in that moment the hunter appeared from afar.')),
  P(('הצבי רץ, העכבר נכנס לחור, והעורב עף.', 'The gazelle ran, the mouse went into a hole, and the crow flew.'),
    ('אבל הצב נשאר במקום.', 'But the tortoise stayed where he was.'),
    ('הצייד מצא את המלכודת ריקה, כעס, ואז ראה את הצב.', 'The hunter found the trap empty, was angry, and then saw the tortoise.'),
    ('הוא אמר: משהו טוב יותר מכלום.', 'He said: something is better than nothing.'),
    ('הוא קשר אותו בחבל, שם אותו בשק, והלך.', 'He tied him with a rope, put him in a sack, and walked on.'),
    ('שלושת החברים ראו מה קרה מרחוק.', 'The three friends saw what happened from afar.'),
    ('העורב אמר: שלושתנו ניצלנו, והרביעי נתפס, אנחנו חייבים להחזיר אותו.', 'The crow said: the three of us are saved, and the fourth is caught, we must get him back.')),
  P(('הם עשו תוכנית.', 'They made a plan.'),
    ('הצבי הלך ועמד לפני הצייד בדרך, ועשה את עצמו צולע.', 'The gazelle went and stood before the hunter on the road, and pretended to be lame.'),
    ('והעורב עמד על הגב שלו, כאילו הוא מנקר בו, כאילו הוא מת.', 'And the crow stood on his back, as if pecking at him, as if he were dead.'),
    ('הצייד אמר: צבי צולע! זה טוב יותר מצב.', 'The hunter said: a lame gazelle! That is better than a tortoise.'),
    ('הוא שם את השק על האדמה ורץ אחריו.', 'He put the sack on the ground and ran after him.'),
    ('וכל פעם שהתקרב, הצבי זז אחורה קצת, ועוד קצת.', 'And every time he came near, the gazelle moved away a little, and a little more.'),
    ('ובזמן הזה, העכבר חתך את החבל של השק, והצב יצא.', 'And in that time, the mouse cut the rope of the sack, and the tortoise came out.'),
    ('כשהצייד חזר בלי צבי, הוא מצא גם את השק ריק.', 'When the hunter came back without a gazelle, he found the sack empty too.'),
    ('החכם אמר: מי שיש לו חברים לא אובד.', 'The sage said: whoever has friends is not lost.'))]),

 ('The Owls and the Crows', 'הינשופים והעורבים', [
  P(('החכם אמר: עכשיו אני אספר לך על האויב, כי מי שלא מכיר את האויב שלו מת.', 'The sage said: now I will tell you about the enemy, because whoever does not know his enemy dies.'),
    ('היה הר, ועל ההר עץ גדול ובו אלף קנים של עורבים.', 'There was a mountain, and on the mountain a big tree with a thousand crows’ nests.'),
    ('וקרוב אליו מערה, ובה אלף ינשופים.', 'And near it a cave, and in it a thousand owls.'),
    ('בין הינשופים והעורבים הייתה שנאה ישנה, ואף אחד לא זכר מאיפה היא באה.', 'Between the owls and the crows there was an old hatred, and no one remembered where it came from.'),
    ('הינשופים רואים בלילה והעורבים ביום.', 'Owls see at night and crows by day.'),
    ('אז כל אחד תקף כשהשני היה עיוור.', 'So each attacked when the other was blind.')),
  P(('לילה אחד הינשופים תקפו את העץ.', 'One night the owls attacked the tree.'),
    ('העורבים ישנו ולא ראו, והינשופים הרגו רבים מהם.', 'The crows were asleep and could not see, and the owls killed many of them.'),
    ('כשהשמש עלתה, הינשופים חזרו למערה, והעורבים ישבו על האדמה ובכו.', 'When the sun rose, the owls went back to the cave, and the crows sat on the ground and wept.'),
    ('מלך העורבים אסף את השרים ואמר: מה נעשה?', 'The king of the crows gathered the ministers and said: what do we do?'),
    ('אחד אמר: נברח להר אחר.', 'One said: we flee to another mountain.'),
    ('אחר אמר: נתקוף אותם ביום.', 'Another said: we attack them by day.'),
    ('שלישי אמר: ניתן להם את העץ ואז נבקש שלום.', 'A third said: we give them the tree and ask for peace.'),
    ('ובכל דעה הייתה טעות.', 'And in every opinion there was a mistake.')),
  P(('היה עורב זקן וחכם, והוא שתק.', 'There was an old, wise crow, and he was silent.'),
    ('המלך אמר: ואתה, מה דעתך?', 'The king said: and you, what do you think?'),
    ('העורב הזקן אמר: אם נברח, הם ירדפו אחרינו, אם נתקוף, הם יהרגו אותנו, אם נבקש שלום, הם ישפילו אותנו.', 'The old crow said: if we flee, they chase us, if we attack, they kill us, if we ask peace, they humiliate us.'),
    ('יש דרך רביעית, אבל אף אחד לא יאהב אותה.', 'There is a fourth way, but no one will like it.'),
    ('המלך אמר: דבר.', 'The king said: speak.'),
    ('הוא אמר: אני חייב להיכנס ביניהם.', 'He said: I must go in among them.'),
    ('וכדי שהם יאמינו לי, אתם חייבים למרוט את הנוצות שלי, להכות אותי, ולזרוק אותי מתחת לעץ.', 'And so that they believe me, you must pluck my feathers, beat me, and throw me under the tree.')),
  P(('העורבים צעקו: לא יכול להיות! אתה הזקן מכולנו!', 'The crows cried: impossible! You are the oldest of us all!'),
    ('העורב הזקן אמר: בגלל זה אני, לצעיר הם לא יאמינו.', 'The old crow said: that is why it is me, a young one they would not believe.'),
    ('וכשתראו אותי זרוק, אל תבכו, תחזרו לקנים שלכם ואז תחכו.', 'And when you see me thrown down, do not weep, go back to your nests and wait.'),
    ('וכך היה, הם מרטו את הנוצות שלו, הכו אותו, וזרקו אותו.', 'And so it was, they plucked his feathers, beat him, and threw him down.'),
    ('והם עפו והשאירו אותו על האדמה, ובכו בשקט.', 'And they flew and left him on the ground, and wept in silence.'),
    ('והלילה בא.', 'And night came.'))]),

 ('The Crow Among the Owls', 'העורב בין הינשופים', [
  P(('בלילה הינשופים באו לתקוף שוב, ומצאו את העורב זרוק מתחת לעץ.', 'At night the owls came to attack again, and found the crow thrown under the tree.'),
    ('הוא היה פצוע ובלי נוצות, ובקושי דיבר.', 'He was wounded and without feathers, and could barely speak.'),
    ('מלך הינשופים אמר: מי אתה? ומי עשה לך את זה?', 'The king of the owls said: who are you? And who did this to you?'),
    ('העורב אמר: אני השר של מלך העורבים.', 'The crow said: I am the minister of the king of the crows.'),
    ('אמרתי לו: הינשופים חזקים מאיתנו, אנחנו חייבים לבקש שלום ולתת להם את העץ.', 'I told him: the owls are stronger than us, we must ask for peace and give them the tree.'),
    ('והוא אמר שאני בוגד, מרט את הנוצות שלי, וזרק אותי.', 'And he said I was a traitor, plucked my feathers, and threw me out.')),
  P(('השרים של הינשופים לא הסכימו ביניהם.', 'The ministers of the owls disagreed among themselves.'),
    ('אחד אמר: תהרגו אותו, עורב הוא עורב, גם אם הוא מדבר יפה.', 'One said: kill him, a crow is a crow, even if he speaks nicely.'),
    ('האויב שאתה מכניס לבית שלך מסוכן יותר מזה שבחוץ.', 'The enemy you bring into your house is more dangerous than the one outside.'),
    ('אבל מלך הינשופים ראה את הפצעים ואמר: זה מסכן, והוא מכיר את הסודות שלהם.', 'But the king of the owls saw the wounds and said: this poor thing knows their secrets.'),
    ('הם לקחו אותו למערה, האכילו אותו, וריפאו אותו.', 'They took him to the cave, fed him, and healed him.'),
    ('והשר שאמר להרוג אותו כעס, עזב את המערה, והלך לחיות לבד.', 'And the minister who had said to kill him was angry, left the cave, and went to live alone.'),
    ('הוא אמר: אני לא ישן עם המוות.', 'He said: I do not sleep with death.')),
  P(('העורב נשאר בין הינשופים חודשים.', 'The crow stayed among the owls for months.'),
    ('הוא שתק, שירת, והסתכל.', 'He was silent, served, and watched.'),
    ('הוא ספר כל פתח במערה וכל ינשוף, וידע איפה הם ישנים ביום.', 'He counted every opening in the cave and every owl, and knew where they slept by day.'),
    ('והנוצות שלו חזרו וצמחו, לאט לאט.', 'And his feathers grew back, little by little.'),
    ('ויום אחד, כשכבר יכול היה לעוף, הוא בא אל מלך הינשופים.', 'And one day, when he could fly again, he came to the king of the owls.'),
    ('הוא אמר: אני רוצה לצאת ולהביא עצים, כדי שיהיה לכם חם בחורף.', 'He said: I want to go out and bring wood, so you will be warm in winter.'),
    ('והוא יצא, והתחיל להביא עצים ולשים אותם ליד פתח המערה.', 'And he went out, and began bringing wood and putting it by the mouth of the cave.'),
    ('כל יום קצת, עד שכל הפתח היה עצים.', 'A little every day, until the whole mouth was wood.')),
  P(('ויום אחד, ביום, כשהינשופים ישנו בפנים, העורב עף אל העץ.', 'And one day, by daylight, when the owls slept inside, the crow flew to the tree.'),
    ('הוא אמר לעורבים: תביאו אש.', 'He said to the crows: bring fire.'),
    ('כל עורב לקח גחלת מהאש של הרועים, והם עפו אל המערה.', 'Every crow took an ember from the shepherds’ fire, and they flew to the cave.'),
    ('הם זרקו את הגחלים על העצים, והעצים נדלקו.', 'They threw the embers on the wood, and the wood caught fire.'),
    ('והינשופים שבפנים לא יכלו לצאת, כי הפתח היה אש, והיום עיוור.', 'And the owls inside could not get out, because the mouth was fire, and the day was blind.'),
    ('וכך נגמרה השנאה הישנה.', 'And so the old hatred ended.'),
    ('החכם אמר: האויב שאתה מכניס לבית שלך מסוכן יותר מזה שבחוץ.', 'The sage said: the enemy you bring into your house is more dangerous than the one outside.'),
    ('והשר שאמר את זה היה היחיד שנשאר בחיים.', 'And the minister who said it was the only one who stayed alive.'))]),

 ('The Monkey and the Tortoise', 'הקוף והצב', [
  P(('החכם אמר: על חוף הים היה עץ תאנה גדול.', 'The sage said: on the seashore there was a big fig tree.'),
    ('ועל העץ חי קוף, שפעם היה מלך הקופים, והזדקן וגירשו אותו.', 'And in the tree lived a monkey, who had once been king of the monkeys, and grew old and was driven out.'),
    ('הוא היה לבד, וכל יום אכל תאנים וזרק את השאריות למים.', 'He was alone, and every day ate figs and threw the leftovers into the water.'),
    ('ויום אחד הוא שמע קול מתחת לעץ שאומר: תודה!', 'And one day he heard a voice from under the tree saying: thank you!'),
    ('זה היה צב, שיצא מהים לאכול את התאנים שנפלו.', 'It was a tortoise, who had come out of the sea to eat the figs that fell.'),
    ('ומהיום הזה הם היו חברים.', 'And from that day they were friends.')),
  P(('כל יום הקוף זרק תאנים לצב, והם דיברו עד הערב.', 'Every day the monkey threw figs to the tortoise, and they talked until evening.'),
    ('והצב התחיל לחזור הביתה מאוחר.', 'And the tortoise began coming home late.'),
    ('אשתו של הצב קינאה, ואמרה לשכנה: לבעלי יש חבר, והוא שכח אותי.', 'The tortoise’s wife was jealous, and said to her neighbour: my husband has a friend, and he has forgotten me.'),
    ('השכנה אמרה: תעשי את עצמך חולה, ואז תגידי שאין תרופה חוץ מלב של קוף.', 'The neighbour said: pretend to be ill, and say there is no cure except a monkey’s heart.'),
    ('וכך היא עשתה, שכבה במיטה, לא אכלה, ואמרה: אני צריכה לב של קוף.', 'And so she did, lay in bed, did not eat, and said: I need a monkey’s heart.')),
  P(('הצב היה בין החבר שלו ובין אשתו.', 'The tortoise was caught between his friend and his wife.'),
    ('הוא אמר: או שהחבר שלי ימות, או שאשתי תמות.', 'He said: either my friend dies, or my wife dies.'),
    ('ובסוף הוא הלך אל הקוף ואמר: בוא לבקר אותי בבית שלי, אני רוצה לארח אותך.', 'And at last he went to the monkey and said: come and visit me at my home, I want to have you as a guest.'),
    ('הקוף אמר: אבל הבית שלך בים, ואני לא יודע לשחות.', 'The monkey said: but your home is in the sea, and I cannot swim.'),
    ('הצב אמר: תעלה על הגב שלי.', 'The tortoise said: get on my back.'),
    ('והקוף עלה, והצב שחה, עצוב ושותק.', 'And the monkey got on, and the tortoise swam, sad and silent.')),
  P(('באמצע הים הצב עצר, ולא יכול היה להמשיך.', 'In the middle of the sea the tortoise stopped, and could not go on.'),
    ('הקוף שאל: מה קרה?', 'The monkey asked: what is wrong?'),
    ('הוא אמר: אשתי חולה, והרופא אמר שאין תרופה חוץ מלב של קוף.', 'He said: my wife is ill, and the doctor said there is no cure except a monkey’s heart.'),
    ('ואני מביא אותך בשביל זה, תסלח לי.', 'And I am bringing you for that, forgive me.'),
    ('הקוף הבין ופחד, אבל לא הראה את זה.', 'The monkey understood and was afraid, but did not show it.'),
    ('הוא אמר בשקט: חבר שלי, למה לא אמרת לי מההתחלה?', 'He said calmly: my friend, why did you not tell me from the start?'),
    ('אנחנו הקופים לא לוקחים את הלב איתנו, אנחנו משאירים אותו על העץ.', 'We monkeys do not take our hearts with us, we leave them in the tree.'),
    ('אם היית אומר לי, הייתי מביא אותו איתי.', 'If you had told me, I would have brought it with me.')),
  P(('הצב שאל: באמת?', 'The tortoise asked: really?'),
    ('הקוף אמר: באמת, תחזור, ואני אעלה, אביא אותו, וארד.', 'The monkey said: really, go back, and I will climb up, bring it, and come down.'),
    ('והצב חזר לחוף, שמח.', 'And the tortoise went back to the shore, glad.'),
    ('הקוף קפץ על העץ, עלה לענף הכי גבוה, והוא ישב.', 'The monkey jumped onto the tree, climbed to the highest branch, and sat.'),
    ('הצב קרא: נו, הבאת אותו?', 'The tortoise called: well, did you get it?'),
    ('הקוף אמר מלמעלה: הלב שלי כאן, ואני כאן, ואנחנו נשארים כאן.', 'The monkey said from above: my heart is here, and I am here, and we are staying here.'),
    ('לך, ואז תגיד שלום לאשתך בשמי.', 'Go, and give my regards to your wife.'),
    ('החכם אמר: מי שניצל מבגידה לא חוזר אליה.', 'The sage said: whoever escapes a betrayal does not go back to it.'))]),

 ('The Ascetic and the Mongoose', 'הנזיר והחיה הנאמנה', [
  P(('החכם אמר: והסיפור האחרון, המלך, הוא על מהירות.', 'The sage said: and the last story, my king, is about haste.'),
    ('היה נזיר שחי בכפר קטן עם אשתו.', 'There was a hermit who lived in a small village with his wife.'),
    ('שנים לא היו להם ילדים, ואז נולד להם בן.', 'For years they had no children, and then a son was born to them.'),
    ('ולפני הבן הייתה להם חיה קטנה, שהנזיר גידל מקטנותה.', 'And before the son they had a small animal, that the hermit had raised from when it was tiny.'),
    ('היא הלכה אחריו בבית כמו כלב, וישנה ליד הילד.', 'It followed him about the house like a dog, and slept beside the child.'),
    ('והנזיר בטח בה כמו שבוטחים בבן.', 'And the hermit trusted it as one trusts a son.')),
  P(('יום אחד האישה הלכה להביא מים מהבאר.', 'One day the wife went to bring water from the well.'),
    ('היא אמרה לנזיר: תישאר עם הילד, אל תעזוב אותו.', 'She said to the hermit: stay with the child, do not leave him.'),
    ('ואחרי זמן קצר בא מישהו מהכפר וקרא לנזיר.', 'And a little later someone from the village came and called the hermit.'),
    ('הוא אמר: בוא מהר, יש מישהו שרוצה לשמוע את הדברים שלך.', 'He said: come quickly, there is someone who wants to hear your words.'),
    ('הנזיר הסתכל על הילד, הוא ישן, והחיה לידו.', 'The hermit looked at the child, he was asleep, and the animal beside him.'),
    ('הוא אמר: שתי דקות ואני חוזר, והוא יצא.', 'He said: two minutes and I am back, and went out.')),
  P(('כשהנזיר היה בחוץ, יצא מסדק בקיר נחש גדול ושחור.', 'While the hermit was outside, a big black snake came out of a crack in the wall.'),
    ('הוא זחל לכיוון הילד הישן.', 'It crawled toward the sleeping child.'),
    ('החיה ראתה אותו, וקפצה עליו.', 'The animal saw it, and leapt on it.'),
    ('הם נלחמו על הרצפה, והילד ישן ולא הרגיש.', 'They fought on the floor, and the child slept and felt nothing.'),
    ('ובסוף החיה הרגה את הנחש, וקרעה אותו.', 'And at last the animal killed the snake, and tore it apart.'),
    ('והיא הלכה לשבת ליד הדלת, כל הפה שלה דם, וחיכתה לנזיר כדי להראות לו.', 'And it went to sit by the door, its whole mouth blood, and waited for the hermit to show him.')),
  P(('הנזיר חזר, והדבר הראשון שראה: החיה ליד הדלת, והפה שלה דם.', 'The hermit came back, and the first thing he saw: the animal by the door, and its mouth bloody.'),
    ('הוא לא חשב, לא שאל, ולא נכנס לראות.', 'He did not think, did not ask, and did not go in to look.'),
    ('הוא אמר: היא אכלה את הילד!', 'He said: it has eaten the child!'),
    ('הוא הרים את המקל שבידו, הכה אותה על הראש, והרג אותה במכה אחת.', 'He raised the stick in his hand, struck it on the head, and killed it with one blow.'),
    ('ואז הוא נכנס.', 'And then he went in.'),
    ('הילד ישן, בריא, ונושם.', 'The child was asleep, safe, and breathing.'),
    ('ולידו נחש שחור גדול, הרוג וקרוע.', 'And beside him a big black snake, killed and torn apart.')),
  P(('הנזיר ישב על הרצפה, הסתכל על החיה, הסתכל על הנחש, והבין.', 'The hermit sat on the floor, looked at the animal, looked at the snake, and understood.'),
    ('והוא בכה, בכה עד שאשתו חזרה.', 'And he wept, wept until his wife came back.'),
    ('היא שאלה: מה קרה?', 'She asked: what happened?'),
    ('הוא אמר: הרגתי את מי שהציל את הבן שלי, כי לא חיכיתי דקה אחת.', 'He said: I killed the one who saved my son, because I did not wait one minute.'),
    ('והבכי לא עזר, מי ששופט מהר מתחרט לאט.', 'And the weeping did not help, whoever judges quickly regrets slowly.'),
    ('והחכם שתק, והסיפורים נגמרו.', 'And the sage was silent, and the stories were finished.'),
    ('והמלך לא אמר כלום באותו לילה.', 'And the king said nothing that night.'),
    ('אבל מהיום למחרת הוא שאל לפני ששפט, והקשיב לפני שדיבר.', 'But from the next day he asked before he judged, and listened before he spoke.'))]),
]

if __name__ == '__main__':
    raise SystemExit(book('kalila', {'en': 'Kalila and Dimna', 'he': 'כלילה ודמנה'},
                          'intermediate', CHAPTERS, unit='Tale', unit_he='מעשה',
                          shelf=12, meta=META))
