#!/usr/bin/env python3
"""Hebrew word lookup -> app/data/he/lexicon.js.

Same file the Arabic side ships (pipeline/lexindex.py), built from a different source and in a
denser encoding, because the two languages hand you opposite problems.

Arabic's index is derived from the CORPUS: only words that actually occur in a text, 5,748 of
them, 1.2 MB. Hebrew has no corpus yet, and would not want that shape anyway -- unpointed
Hebrew is genuinely ambiguous (ספר is sefer / sapar / siper / safar), so resolving an inflected
surface to its pointed dictionary form IS the product. The whole inflection table earns its
place: 12,662 lemmas, 111,327 distinct surface keys.

Written flat, that is 28 MB. Three things bring it to 12.7 MB (2.2 MB gzipped), all measured:

  base rows   -- a surface row carries only what varies (the pointed form, its pronunciation,
                 its analysis) and points at its lemma's row for the rest. 114k surfaces over
                 12.6k lemmas is an 8.6x fan-out, so the gloss and root are written once.
  interning   -- `analysis` has 171 distinct values across 128k rows, `provenance` 2. They are
                 pooled and referenced by index.
  trimming    -- trailing nulls are dropped; the reader pads them back.

Excluding verb forms on the grounds that verbs-conj-*.js already covers them was measured and
rejected: it would drop 16,978 surface keys belonging to the 1,124 verb lemmas that Wiktionary
gives forms for but no full paradigm -- a third of Hebrew verb surfaces, on the language's
hardest lookup.

    python3 pipeline/he_lexicon.py --lang he
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'spike', 'he'))
import paths           # noqa: E402
from build_lex import he_norm   # noqa: E402  -- must match LANG.script.norm in app/lang/he.js

PARQUET = os.path.join(paths.ROOT, 'spike', 'he', 'hebrew_lex.parquet')

# Column order. `base` is new and optional: a row that has it inherits every field the row
# itself leaves empty from the row at that index. Arabic's index simply never sets it.
FIELDS = ['surface', 'lemma', 'vocalized_from', 'form', 'root', 'gloss', 'analysis', 'caphi',
          'maknuune_id', 'provenance', 'base']
INTERN = ('vocalized_from', 'analysis', 'provenance')


# app/app.js: lexRank. Same rule, so the same record wins here as would have won at runtime.
def _rank(r):
    return ((4 if r['GLOSS'] else 0) + (2 if r['ID'] else 0) + (1 if r['PHON'] else 0))


def build(rows_in):
    by_key, by_surf = {}, {}

    def put(m, k, r):
        if not k:
            return
        p = m.get(k)
        if p is None or _rank(r) > _rank(p):
            m[k] = r

    for r in rows_in:
        put(by_key, he_norm(r['LEMMA']), r)
        put(by_surf, he_norm(r['FORM']), r)

    pool = {c: {} for c in INTERN}

    def intern(col, v):
        if v in (None, ''):
            return None
        d = pool[col]
        if v not in d:
            d[v] = len(d)
        return d[v]

    rows, lemma_at, seen = [], {}, {}

    def trim(x):
        while x and x[-1] is None:
            x.pop()
        return x

    def lemma_row(r):
        i = lemma_at.get(r['LEMMA'])
        if i is None:
            i = lemma_at[r['LEMMA']] = len(rows)
            rows.append(trim([None, r['LEMMA'], None, r['LEMMA'], r['ROOT'] or None,
                              r['GLOSS'] or None, None, None, r['ID'] or None,
                              intern('provenance', r['SOURCE']), None]))
        return i

    def ref(r):
        i = seen.get(id(r))
        if i is None:
            base = lemma_row(r)
            i = seen[id(r)] = len(rows)
            rows.append(trim([r['FORM'], None, intern('vocalized_from', r['PHON_SRC']),
                              None, None, None, intern('analysis', r['ANALYSIS']),
                              r['PHON'] or None, None, None, base]))
        return i

    k = {key: ref(r) for key, r in by_key.items()}
    s = {key: ref(r) for key, r in by_surf.items()}
    return {'f': FIELDS,
            'intern': {c: [x for x, _ in sorted(pool[c].items(), key=lambda kv: kv[1])]
                       for c in INTERN},
            'r': rows, 'k': k, 's': s}


def main():
    if not os.path.exists(PARQUET):
        print('missing %s -- run spike/he/build_lex.py first' % os.path.relpath(PARQUET, paths.ROOT))
        return 1
    import pyarrow.parquet as pq
    data = build(pq.read_table(PARQUET).to_pylist())
    p = paths.data('lexicon.js')
    with open(p, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/he_lexicon.py -- do not edit.\n')
        f.write('// Wiktionary (CC BY-SA 4.0) via spike/he/build_lex.py. Rows are positional and\n'
                '// sparse: `f` names the columns, `base` points at the lemma row a surface\n'
                '// inherits from, and the columns in `intern` hold indexes into those pools.\n')
        f.write('window.LEXICON = ')
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    print('lemma keys %d   surface keys %d   rows %d'
          % (len(data['k']), len(data['s']), len(data['r'])))
    print('intern pools: %s' % {c: len(v) for c, v in data['intern'].items()})
    print('-> %s  (%d KB)' % (os.path.relpath(p, paths.ROOT), os.path.getsize(p) // 1024))
    return 0


if __name__ == '__main__':
    sys.exit(main())
