#!/usr/bin/env python3
"""Build the Lessons (native-sourced teaching units) data (+ audio).

Reads texts/lessons/unit-*.json and emits app/data/lessons.js -> window.LESSONS =
{units:[...]}. Each unit is a coherent ~30-45 min teaching unit whose Arabic is copied
VERBATIM from the transcribed reference library (texts/ref/, the user's own native teaching
materials) — per-chunk src fields point at the exact book page. English glosses are the
book's where it had them, the app's where the page was Arabic-only.

With --audio it generates one clip per chunk (and one per reply, for greeting-style pairs)
with the pinned Palestinian voice: app/audio/lessons/<unit>-cNN.mp3 / -cNNr.mp3.

Run:
    python3 pipeline/lessons.py                 # data only
    export ELEVENLABS_API_KEY=...; python3 pipeline/lessons.py --audio
"""
import json, os, sys, glob, argparse, ssl, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
sys.path.insert(0, HERE)
from voice import voice_id

try:
    import certifi
    _SSL = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL = ssl.create_default_context()

SRC_GLOB = os.path.join(ROOT, 'texts', 'lessons', 'unit-*.json')
OUT_JS = os.path.join(ROOT, 'app', 'data', 'lessons.js')
AUDIO_DIR = os.path.join(ROOT, 'app', 'audio', 'lessons')


def tts(text, path, key, voice, model='eleven_multilingual_v2'):
    if os.path.exists(path):
        return True, 'cached'
    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{voice}',
        data=json.dumps({'text': text, 'model_id': model}).encode(),
        headers={'xi-api-key': key, 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=90, context=_SSL) as r:
            open(path, 'wb').write(r.read())
        return True, 'generated'
    except Exception as e:
        return False, str(e)[:100]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--audio', action='store_true', help='generate per-chunk MP3s (needs ELEVENLABS_API_KEY)')
    a = ap.parse_args()

    key, voice = os.environ.get('ELEVENLABS_API_KEY'), voice_id()
    do_audio = a.audio and key and voice
    if a.audio and not do_audio:
        print('!! --audio requested but ELEVENLABS_API_KEY not set; emitting data with no audio\n')
    if do_audio:
        os.makedirs(AUDIO_DIR, exist_ok=True)

    units = []
    for f in sorted(glob.glob(SRC_GLOB)):
        u = json.load(open(f, encoding='utf-8'))
        for i, c in enumerate(u.get('chunks', [])):
            base = '%s-c%02d' % (u['id'], i)
            for suffix, ar in (('', c.get('ar')), ('r', (c.get('reply') or {}).get('ar'))):
                if not ar:
                    continue
                clip = os.path.join(AUDIO_DIR, base + suffix + '.mp3')
                rel = 'audio/lessons/%s%s.mp3' % (base, suffix)
                tgt = c if not suffix else c['reply']
                if os.path.exists(clip):
                    tgt['audio'] = rel
                elif do_audio:
                    ok, how = tts(ar, clip, key, voice)
                    print('  %s%s %-24s %s' % (base, suffix, ar[:22], how))
                    if ok:
                        tgt['audio'] = rel
        units.append(u)

    units.sort(key=lambda u: u.get('n', 99))
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/lessons.py — do not edit by hand.\n')
        f.write('// Teaching units whose Arabic is copied verbatim from the reference library\n')
        f.write('// (texts/ref/ — the native teaching materials); per-chunk src = book page.\n')
        f.write('window.LESSONS = ')
        json.dump({'units': units}, f, ensure_ascii=False, indent=1)
        f.write(';\n')

    n_ch = sum(len(u.get('chunks', [])) for u in units)
    voiced = sum(1 for u in units for c in u.get('chunks', []) if c.get('audio'))
    print('units: %d · %d chunks · audio %d/%d' % (len(units), n_ch, voiced, n_ch))
    print('-> app/data/lessons.js')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
