#!/usr/bin/env python3
"""Precompute the word-lookup index the app used to build from the whole corpus at runtime.

Tapping an Arabic word anywhere outside the reader -- in a grammar lesson, a Bible verse, a
dinner-table line -- goes through lexIndex(), which maps a normalized form to the richest word
record the corpus has for it. The app built that by walking every sentence, which meant every
page made of lookups had to download all 7.3 MB of them.

But the index is far smaller than its input, because it is a DEDUPLICATION: 19,938 word tokens
collapse to 5,748 distinct records, one per lemma key and per surface key. Computing it here
instead ships 1.2 MB rather than 7.3 MB, and the app stops parsing 20,000 tokens on the first
tap.

    corpus.js   7,500,506 raw   1,110,641 gzipped
    lexicon.js  1,215,524 raw     319,277 gzipped

Positional rows rather than objects: repeating fourteen key names 5,748 times is 45% of the raw
file. Gzip hides most of that (332 KB against 270 KB), but raw size is parse time on a phone,
and it is what sits on disk. Factoring the lemma-level fields into a second table on top of this
saves about another tenth once gzipped, which is not worth a second indirection.

THE TWO RULES BELOW MUST MATCH app/app.js AND app/lang/ar.js EXACTLY. `_norm` is LANG.script.norm
and `_rank` is lexRank; if either drifts, the index silently answers differently from the app
that used to build it, which is the kind of bug nobody notices. pipeline/verify_lexindex.py
compares this output against a straight walk of the corpus, and the app asserts the same thing
in the browser -- see the equivalence check in that script's header.
"""
import json
import os
import re

import paths

# app/lang/ar.js: LANG.script.norm -- strip harakat and tatweel, fold the hamza-carrying alefs,
# ta-marbuta and alef-maqsura.
_HARAKAT = re.compile('[ً-ْٰـ]')
_ALEF = re.compile('[أإآٱ]')


def _norm(s):
    s = _HARAKAT.sub('', s or '')
    s = _ALEF.sub('ا', s)
    return s.replace('ة', 'ه').replace('ى', 'ي').strip()


# app/app.js: lexRank -- how good a record is. A gloss is worth more than a lexicon id, which is
# worth more than a pronunciation; ties keep whichever was seen first.
def _rank(r):
    return ((4 if r.get('gloss') else 0)
            + (2 if r.get('maknuune_id') else 0)
            + (1 if (r.get('caphi_urban') or r.get('caphi')) else 0))


FIELDS = ['surface', 'lemma', 'vocalized', 'vocalized_from', 'form', 'root', 'gloss', 'analysis',
          'caphi', 'caphi_urban', 'caphi_raw', 'maknuune_id', 'provenance', 'village']


def build(texts):
    """texts in the SAME ORDER the app sees them -- ties are broken by first-seen."""
    by_key, by_surf = {}, {}

    def put(m, k, r):
        if not k:
            return
        p = m.get(k)
        if p is None or _rank(r) > _rank(p):
            m[k] = r

    for t in texts:
        for s in t.get('sentences', []):
            for w in s.get('words', []):
                if not w.get('lemma'):
                    continue
                put(by_key, _norm(w['lemma']), w)
                put(by_surf, _norm(w.get('surface', '')), w)

    rows, seen = [], {}

    def ref(r):
        i = seen.get(id(r))
        if i is None:
            i = seen[id(r)] = len(rows)
            rows.append([r.get(f) for f in FIELDS])
        return i

    return {'f': FIELDS,
            'r': rows,
            'k': {k: ref(r) for k, r in by_key.items()},
            's': {k: ref(r) for k, r in by_surf.items()}}


def write(texts, note='pipeline/build_app.py'):
    p = paths.data('lexicon.js')
    # Never overwrite a lexicon this file did not write. A language whose lookup comes from a
    # DICTIONARY rather than from its own texts builds this elsewhere -- Hebrew's is 12 MB from
    # pipeline/he_lexicon.py -- and the moment Hebrew got its first news article, "there are
    # texts now" was enough to replace all of it with 24 records derived from four sentences.
    # The file says who made it; that is a better guard than a table of languages kept in step
    # by hand.
    if os.path.exists(p):
        head = open(p, encoding='utf-8').readline()
        if 'lexindex.py' not in head:
            print('   lexicon.js: left alone — %s' % head.strip().lstrip('/ '))
            return None
    data = build(texts)
    with open(p, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/lexindex.py via %s -- do not edit.\n' % note)
        f.write('// The word-lookup index, precomputed. Rows are positional: `f` names the\n'
                '// columns, `k` maps a normalized lemma to a row and `s` a normalized surface.\n')
        f.write('window.LEXICON = ')
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    return {'lexicon.js': os.path.getsize(p), 'rows': len(data['r']),
            'keys': len(data['k']), 'surfaces': len(data['s'])}
