#!/usr/bin/env python3
"""Build the Reactions data (+ audio) the app ships.

Reads texts/reactions.json — curated Palestinian conversational reactions grouped by the job they
do in a conversation — and emits app/data/reactions.js -> window.REACTIONS = {cats, items}. With
--audio it also generates one expressive clip per reaction in the PINNED Palestinian voice
(eleven_v3, the model car_session.py uses for reactions), the same key path as the story audio.
Items flagged provenance:needs-native-validation are still voiced but keep the honest flag; the app
shows a "not native-checked" note.

Run:
    python3 pipeline/reactions.py                 # data only
    export ELEVENLABS_API_KEY=...; python3 pipeline/reactions.py --audio
"""
import json, os, sys, argparse, ssl, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
sys.path.insert(0, HERE)
from voice import voice_id

try:
    import certifi
    _SSL = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL = ssl.create_default_context()

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402  -- where this language's generated data lives

SRC = os.path.join(ROOT, 'texts', 'reactions.json')
OUT_JS = paths.data('reactions.js')
AUDIO_DIR = os.path.join(ROOT, 'app', 'audio', 'reactions')


def tts(text, path, key, voice, model='eleven_v3'):
    if os.path.exists(path):
        return True, 'cached'
    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{voice}',
        data=json.dumps({'text': text, 'model_id': model}).encode(),
        headers={'xi-api-key': key, 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=90, context=_SSL) as r:
            open(path, 'wb').write(r.read())
        return True, 'generated'
    except Exception as e:
        return False, str(e)[:100]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--audio', action='store_true', help='generate MP3s (needs ELEVENLABS_API_KEY)')
    a = ap.parse_args()

    d = json.load(open(SRC, encoding='utf-8'))
    cats, items = d['cats'], []
    key, voice = os.environ.get('ELEVENLABS_API_KEY'), voice_id()
    do_audio = a.audio and key and voice
    if a.audio and not do_audio:
        print('!! --audio requested but ELEVENLABS_API_KEY not set; emitting data with no audio\n')
    if do_audio:
        os.makedirs(AUDIO_DIR, exist_ok=True)
        print(f'generating audio… (voice {voice}, model eleven_v3)')

    for i, it in enumerate(d['items']):
        rid = 'r%d' % i
        rec = {'id': rid, 'ar': it['ar'], 'en': it['en'], 'use': it.get('use', ''),
               'cat': it['cat'], 'provenance': it.get('provenance', 'needs-native-validation')}
        # Which book page corroborates it (pipeline/verify_content.py --apply), so the card can
        # name its evidence instead of just asserting it was checked.
        if it.get('ref_src'):
            rec['ref_src'] = it['ref_src']
        if it.get('reply'):
            rec['reply'] = it['reply']
        # Adopt any clip already on disk whether or not THIS run makes audio, so a keyless data-only
        # rebuild never drops audio that was generated earlier.
        clip = os.path.join(AUDIO_DIR, rid + '.mp3')
        if os.path.exists(clip):
            rec['audio'] = 'audio/reactions/%s.mp3' % rid
        elif do_audio:
            ok, how = tts(it['ar'], clip, key, voice)
            print(f'  {rid} {it["ar"]:16} {how}')
            if ok:
                rec['audio'] = 'audio/reactions/%s.mp3' % rid
        items.append(rec)

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/reactions.py — do not edit by hand.\n')
        f.write('// Curated Palestinian conversational reactions, grouped by function. Items flagged\n')
        f.write('// provenance:needs-native-validation are common but not native-checked.\n')
        f.write('window.REACTIONS = ')
        json.dump({'cats': cats, 'items': items}, f, ensure_ascii=False, indent=1)
        f.write(';\n')

    voiced = sum(1 for it in items if it.get('audio'))
    print(f'reactions: {len(items)} in {len(cats)} categories · audio {voiced}/{len(items)}')
    print('-> app/data/reactions.js')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
