#!/usr/bin/env python3
"""Build the Sounds (Phase-0 pronunciation) data (+ audio).

Reads texts/sounds.json and emits app/data/sounds.js -> window.SOUNDS = {lessons:[...]}. With
--audio it synthesizes a reference clip per example word (and its minimal-pair contrast) in the
PINNED Palestinian voice. Honesty note baked into the app: the gutturals ع/ح and the emphatics are
exactly where TTS is least reliable, so the UI labels clips 'synthesized reference' and leads with
the articulation tip — a wrong sound would be worse than none.

Run:
    python3 pipeline/sounds.py                 # data only
    export ELEVENLABS_API_KEY=...; python3 pipeline/sounds.py --audio
"""
import json, os, sys, argparse, ssl, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
sys.path.insert(0, HERE)
from voice import voice_id

try:
    import certifi
    _SSL = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL = ssl.create_default_context()

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402  -- where this language's generated data lives

SRC = os.path.join(ROOT, 'texts', 'sounds.json')
OUT_JS = paths.data('sounds.js')
AUDIO_DIR = os.path.join(ROOT, 'app', 'audio', 'sounds')


def tts(text, path, key, voice, model='eleven_multilingual_v2'):
    if os.path.exists(path):
        return True, 'cached'
    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{voice}',
        data=json.dumps({'text': text, 'model_id': model}).encode(),
        headers={'xi-api-key': key, 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=90, context=_SSL) as r:
            open(path, 'wb').write(r.read())
        return True, 'generated'
    except Exception as e:
        return False, str(e)[:100]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--audio', action='store_true', help='synthesize reference clips (needs ELEVENLABS_API_KEY)')
    a = ap.parse_args()

    d = json.load(open(SRC, encoding='utf-8'))
    key, voice = os.environ.get('ELEVENLABS_API_KEY'), voice_id()
    do_audio = a.audio and key and voice
    if a.audio and not do_audio:
        print('!! --audio requested but ELEVENLABS_API_KEY not set; emitting data with no audio\n')
    if do_audio:
        os.makedirs(AUDIO_DIR, exist_ok=True)
        print(f'generating audio… (voice {voice})')

    k = [0]

    def clip_for(ar):
        rid = 's%d' % k[0]
        k[0] += 1
        path = os.path.join(AUDIO_DIR, rid + '.mp3')
        if os.path.exists(path):
            return 'audio/sounds/%s.mp3' % rid
        if do_audio:
            ok, how = tts(ar, path, key, voice)
            print(f'  {rid} {ar:12} {how}')
            if ok:
                return 'audio/sounds/%s.mp3' % rid
        return None

    lessons = []
    for L in d['lessons']:
        exs = []
        for ex in L['examples']:
            e = {'ar': ex['ar'], 'tr': ex['tr'], 'en': ex['en']}
            au = clip_for(ex['ar'])
            if au:
                e['audio'] = au
            if ex.get('contrast'):
                c = ex['contrast']
                ce = {'ar': c['ar'], 'tr': c['tr'], 'en': c['en']}
                cau = clip_for(c['ar'])
                if cau:
                    ce['audio'] = cau
                e['contrast'] = ce
            exs.append(e)
        lessons.append({'id': L['id'], 'en': L['en'], 'ar': L['ar'], 'target': L['target'],
                        'tip': L['tip'], 'examples': exs})

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/sounds.py — do not edit by hand.\n')
        f.write('// Phase-0 pronunciation contrasts, urban Palestinian (matches pipeline/subdialect.py).\n')
        f.write('// Audio, when present, is SYNTHESIZED reference — trust the tip for ع/ح/emphatics.\n')
        f.write('window.SOUNDS = ')
        json.dump({'lessons': lessons}, f, ensure_ascii=False, indent=1)
        f.write(';\n')

    voiced = sum(1 for L in lessons for e in L['examples']
                 if e.get('audio')) + sum(1 for L in lessons for e in L['examples']
                                          if e.get('contrast', {}).get('audio'))
    print(f'sounds: {len(lessons)} lessons · {k[0]} words · audio {voiced}/{k[0]}')
    print('-> app/data/sounds.js')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
