#!/usr/bin/env python3
"""Index and bodies: emit each dataset as a small always-loaded part and a large on-demand one.

The app used to load 15.4 MB on every page view, and the home screen -- which shows nothing but
section names and counts -- paid all of it. Measured, almost none of that weight is what the page
is about:

    library.js   7.1 MB    metadata 190 KB (2.7%)   sentences 6.9 MB
    verbs.js     5.2 MB    metadata 777 KB (15%)    paradigms 4.4 MB

So each is written twice over. The INDEX carries everything you can see without opening the
thing -- a story's title, level and word count; a verb's lemma, root, gloss and measure -- and
is what every page loads. The BODIES carry what only that one page needs, and arrive when it is
asked for.

Three shapes of body, one per access pattern:

  text/<id>.js        one story, news article or chapter. The reader opens exactly one, so it
                      should cost exactly one -- ~18 KB rather than 6.9 MB.
  corpus.js           every sentence at once. Not a duplicate for the sake of it: the lexicon,
                      the translator and the placement test all read across the WHOLE corpus,
                      and 384 script tags to assemble it would be far worse than one file.
                      Both write into the same window.CORPUS, so whichever arrives first wins
                      and the app never has to know which path fed it.
  verbs-conj-NN.js    paradigms in blocks of 256 verbs. Opening one verb pulls ~400 KB instead
                      of 4.4 MB; the few readers that need every cell pull every block.

Everything is .js assigning to a global rather than .json, for the reason the whole pipeline
emits .js: on file:// a fetch() of a sibling file is a CORS error, and a <script> tag is not.
"""
import json
import os

import paths

CONJ_CHUNK = 256          # verbs per paradigm file -> ~400 KB each, 13 files

_J = dict(ensure_ascii=False, separators=(',', ':'))


def _dump(path, head, expr):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(head)
        f.write(expr)
    return os.path.getsize(path)


# ---- verbs -----------------------------------------------------------------------------------

def write_verbs(data, note='pipeline/build_verbs.py'):
    """data is the full {'verbs': [...]} with `conj` still attached. Returns a size report."""
    verbs = data['verbs']
    head = '// GENERATED by %s -- do not edit.\n' % note
    index, conj = [], []
    for v in verbs:
        c = v.get('conj')
        row = {k: val for k, val in v.items() if k != 'conj'}
        # The index has to answer "does this verb have a paradigm?" without carrying it: the
        # study plan ranks verbs by it and the section counts report it, and both run on pages
        # that never open a table.
        if c:
            row['hasConj'] = 1
        index.append(row)
        conj.append(c or None)

    sizes = {}
    sizes['verbs.js'] = _dump(
        paths.data('verbs.js'),
        head + '// Paradigms are NOT here -- see verbs-conj-*.js, loaded when a table is opened.\n',
        'window.VERBS = ' + json.dumps({'verbs': index}, **_J) + ';\n')

    n = 0
    for start in range(0, len(conj), CONJ_CHUNK):
        block = {str(start + i): c for i, c in enumerate(conj[start:start + CONJ_CHUNK]) if c}
        if not block:
            continue
        name = 'verbs-conj-%02d.js' % (start // CONJ_CHUNK)
        sizes[name] = _dump(
            paths.data(name),
            head + '// Paradigms for verbs %d-%d, keyed by their index in window.VERBS.verbs.\n'
                   % (start, start + CONJ_CHUNK - 1),
            '(window.VCONJ=window.VCONJ||{}),Object.assign(window.VCONJ,'
            + json.dumps(block, **_J) + ');\n')
        n += 1
    sizes['_chunks'] = n
    return sizes


def read_verbs():
    """The inverse: the full {'verbs': [...]} with `conj` reattached, for pipeline scripts."""
    src = open(paths.data('verbs.js'), encoding='utf-8').read()
    data = json.loads(src[src.index('{'): src.rindex(';')])
    conj = {}
    for start in range(0, len(data['verbs']), CONJ_CHUNK):
        p = paths.data('verbs-conj-%02d.js' % (start // CONJ_CHUNK))
        if not os.path.exists(p):
            continue
        s = open(p, encoding='utf-8').read()
        conj.update(json.loads(s[s.index('Object.assign(window.VCONJ,')
                                 + len('Object.assign(window.VCONJ,'): s.rindex(');')]))
    for i, v in enumerate(data['verbs']):
        v.pop('hasConj', None)
        c = conj.get(str(i))
        if c:
            v['conj'] = c
    return data


# ---- library ---------------------------------------------------------------------------------

def write_library(texts, drills, audio_version, note='pipeline/build_app.py'):
    head = '// GENERATED by %s -- do not edit by hand.\n' % note
    index_t, index_d, bodies = [], [], {}
    for t in texts:
        bodies[t['id']] = t.get('sentences', [])
        index_t.append({k: v for k, v in t.items() if k != 'sentences'})
    for d in drills:
        bodies[d['id']] = d.get('items', [])
        index_d.append({k: v for k, v in d.items() if k != 'items'})

    sizes = {}
    sizes['library.js'] = _dump(
        paths.data('library.js'),
        head
        + '// AUDIO_VERSION changes whenever any clip changes; the app appends it to audio\n'
          '// URLs so a re-voice is never masked by a cached copy of the old voice.\n'
          '// Sentences are NOT here -- see text/<id>.js (one text) and corpus.js (all of them).\n'
          'window.AUDIO_VERSION = "%s";\n' % audio_version,
        'window.LIBRARY = ' + json.dumps({'texts': index_t, 'drills': index_d}, **_J) + ';\n')

    for tid, body in bodies.items():
        _dump(paths.data('text', tid + '.js'),
              head, '(window.CORPUS=window.CORPUS||{})[%s]=%s;\n'
              % (json.dumps(tid), json.dumps(body, **_J)))
    sizes['text/'] = sum(os.path.getsize(paths.data('text', t + '.js')) for t in bodies)

    sizes['corpus.js'] = _dump(
        paths.data('corpus.js'),
        head + '// Every sentence in one file, for the readers that work across the whole corpus:\n'
               '// the lexicon, the translator, the placement test. Same window.CORPUS the\n'
               '// per-text files write into, so either path satisfies the other.\n',
        '(window.CORPUS=window.CORPUS||{}),Object.assign(window.CORPUS,'
        + json.dumps(bodies, **_J) + ');\n')
    sizes['_texts'] = len(bodies)
    return sizes
