#!/usr/bin/env python3
"""Advanced short stories — emit texts/story-adv-NN.json.

Longer narratives (14-18 sentences) with dialogue, idioms and cultural/emotional themes.
Not native-validated; word metadata looked up from Maknuune at ingest.
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402  -- per-language file layout
import json, os
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SRC = ("Advanced short story written in spoken Palestinian by Claude. "
       "NOT native-validated.")

STORIES = [
 ("شجرة الزيتون", "The Olive Tree", [
   ("بوسط أرض جدي، كان في شجرة زيتون كبيرة وقديمة.", "In the middle of my grandfather's land, there was a big, old olive tree."),
   ("جدي كان يقول إنها أكبر منه بكتير.", "My grandfather used to say it was much older than him."),
   ("كل خريف، كانت العيلة كلها تجتمع تحتها لتقطف.", "Every fall, the whole family would gather under it to harvest."),
   ("لما كنت صغير، سألت جدي: ليش هالشجرة مهمة هيك؟", "When I was little, I asked my grandfather: why is this tree so important?"),
   ("ابتسم وقال: هاي الشجرة زرعها أبو جدي بإيده.", "He smiled and said: this tree was planted by my great-grandfather with his own hands."),
   ("قال إنها شافت أجيال وأجيال من عيلتنا.", "He said it had seen generations upon generations of our family."),
   ("كل غصن فيها بيحكي قصة، وكل زيتونة فيها بركة.", "Every branch in it tells a story, and every olive in it is a blessing."),
   ("مرة، إجا رجال وعرض يشتري الأرض والشجرة.", "Once, a man came and offered to buy the land and the tree."),
   ("عرض مصاري كتير، بس جدي رفض على طول.", "He offered a lot of money, but my grandfather refused right away."),
   ("قال: الأرض مش للبيع، والذكريات ما إلها تمن.", "He said: the land is not for sale, and memories have no price."),
   ("بعد سنين، توفى جدي، وورثنا الأرض والشجرة.", "After years, my grandfather passed away, and we inherited the land and the tree."),
   ("وقفت تحت الشجرة وحسيت إنه جدي لسا معي.", "I stood under the tree and felt my grandfather was still with me."),
   ("علمت ولادي نفس الشي اللي علمني ياه.", "I taught my children the same thing he taught me."),
   ("الشجرة ما زالت واقفة، تشهد على محبتنا للأرض.", "The tree is still standing, a witness to our love for the land."),
   ("وكل خريف، بنجتمع تحتها متل زمان.", "And every fall, we gather under it like the old days."),
 ]),
 ("الرسالة", "The Letter", [
   ("زمان، قبل ما يصير في تلفونات، الناس كانت تبعت رسائل.", "Long ago, before there were phones, people used to send letters."),
   ("خالي سافر برا البلد يشتغل ويجمع مصاري.", "My uncle traveled abroad to work and save money."),
   ("كل شهر، كان يبعت رسالة لإمه، جدتي.", "Every month, he would send a letter to his mother, my grandmother."),
   ("جدتي ما كانت تعرف تقرا، فكانت تجيبني أقرالها.", "My grandmother didn't know how to read, so she would bring me to read to her."),
   ("كنت أقعد جنبها وأقرا الرسالة بصوت عالي.", "I would sit next to her and read the letter out loud."),
   ("كانت تسمع وعيونها تدمع من الشوق.", "She would listen and her eyes would water from longing."),
   ("بعدين، كانت تملي عليي الرد، وأنا أكتب.", "Then, she would dictate the reply to me, and I would write."),
   ("مرة، تأخرت رسالة خالي شهرين.", "Once, my uncle's letter was two months late."),
   ("جدتي قلقت كتير وما عادت تنام.", "My grandmother worried a lot and stopped sleeping."),
   ("كل يوم، كانت تسأل: وصلت رسالة؟", "Every day, she would ask: did a letter arrive?"),
   ("وأنا أرد: لسا يا جدتي، بكرا إن شاء الله.", "And I would answer: not yet, grandma, tomorrow, God willing."),
   ("بالآخر، إجت الرسالة، وكان خالي مريض بس طاب.", "Finally, the letter came, and my uncle had been sick but recovered."),
   ("جدتي بكت من الفرح وحضنت الرسالة.", "My grandmother cried from joy and hugged the letter."),
   ("قالت: الحمد لله اللي رجعلي خبر منه.", "She said: thank God that news of him came back to me."),
   ("لهلأ، بحتفظ بهديك الرسائل بصندوق قديم.", "To this day, I keep those letters in an old box."),
   ("كل ما أقراها، بتذكر جدتي وشوقها.", "Every time I read them, I remember my grandmother and her longing."),
 ]),
 ("الضيف الغريب", "The Stranger Guest", [
   ("ليلة شتوية باردة، كنا قاعدين حوالي الصوبا.", "One cold winter night, we were sitting around the heater."),
   ("فجأة، سمعنا دق عالباب.", "Suddenly, we heard a knock on the door."),
   ("أبوي فتح، ولقى رجال غريب مبلول من الشتا.", "My dad opened, and found a strange man soaked from the rain."),
   ("الرجال قال: سيارتي وقفت بالطريق، وأنا تايه.", "The man said: my car broke down on the road, and I'm lost."),
   ("أبوي قاله على طول: تفضل، البيت بيتك.", "My dad said to him right away: come in, my house is your house."),
   ("قعدناه جنب الصوبا وجبناله أواعي ناشفة.", "We seated him by the heater and brought him dry clothes."),
   ("إمي سخنت شوربة وقدمتله عشا.", "My mom heated soup and served him dinner."),
   ("الرجال قال: ما بعرف كيف أشكركم.", "The man said: I don't know how to thank you."),
   ("أبوي رد: هاي واجب، وإحنا بنكرم الضيف.", "My dad replied: this is a duty, and we honor the guest."),
   ("سهرنا معه وحكالنا عن حياته وسفراته.", "We stayed up with him and he told us about his life and travels."),
   ("الصبح، طلعت الشمس ووقفت الشتا.", "In the morning, the sun came out and the rain stopped."),
   ("أبوي ساعده يصلح سيارته.", "My dad helped him fix his car."),
   ("قبل ما يمشي، الرجال قال: مش رح أنساكم أبدا.", "Before he left, the man said: I will never forget you."),
   ("بعد شهر، وصلنا هدية كبيرة وورقة مكتوب فيها شكرا.", "After a month, a big gift arrived with a note saying thank you."),
   ("أبوي قال: الخير اللي بتعمله، بيرجعلك.", "My dad said: the good you do comes back to you."),
   ("من هديك الليلة، تعلمت شو يعني الكرم.", "From that night, I learned what generosity means."),
 ]),
 ("طبخة جدتي", "Grandma's Recipe", [
   ("جدتي كانت أحسن طباخة بالعيلة كلها.", "My grandmother was the best cook in the whole family."),
   ("أكلها كان له طعمة ما في متلها.", "Her food had a taste like no other."),
   ("كل النسوان بالعيلة حاولوا يقلدوا أكلها.", "All the women in the family tried to imitate her cooking."),
   ("بس ولا وحدة قدرت توصل لنفس الطعمة.", "But not one of them could reach the same taste."),
   ("مرة، سألتها إمي: شو سرك يا حجة؟", "Once, my mom asked her: what's your secret, hajjeh?"),
   ("جدتي ضحكت وقالت: السر مش بالبهارات.", "My grandmother laughed and said: the secret isn't in the spices."),
   ("قالت: السر إنك تطبخي وقلبك مليان محبة.", "She said: the secret is that you cook with your heart full of love."),
   ("إمي ما فهمت الحكي بالأول.", "My mom didn't understand the words at first."),
   ("بس بعد ما توفت جدتي، بلشت تفهم.", "But after my grandmother passed away, she began to understand."),
   ("صارت إمي تطبخ لنا نفس الأكلات.", "My mom started cooking us the same dishes."),
   ("وكانت تحط فيها كل محبتها لإلنا.", "And she would put all her love for us into them."),
   ("شوي شوي، صار أكل إمي يشبه أكل جدتي.", "Little by little, my mom's food started to resemble my grandmother's."),
   ("يوم، جربت أكلها وحسيت إنه جدتي رجعت.", "One day, I tried her food and felt my grandmother had come back."),
   ("قلتلها: هيك بالضبط كانت تطبخ جدتي.", "I told her: this is exactly how grandma used to cook."),
   ("إمي دمعت وقالت: عرفت السر أخيرا.", "My mom teared up and said: I finally learned the secret."),
 ]),
 ("العودة عالضيعة", "The Return to the Village", [
   ("بعد عشرين سنة بالغربة، قررت أرجع عالضيعة.", "After twenty years abroad, I decided to return to the village."),
   ("كنت خايف إنه كل شي تغير.", "I was afraid that everything had changed."),
   ("لما وصلت، لقيت الشوارع نفسها بس أضيق.", "When I arrived, I found the same streets but narrower."),
   ("البيوت القديمة لسا واقفة، بس ناسها كبروا.", "The old houses were still standing, but their people had aged."),
   ("مشيت بالحارة، وكل خطوة كانت تفكرني بشي.", "I walked through the neighborhood, and every step reminded me of something."),
   ("لقيت بيت جدي، وقفت قدامه طويل.", "I found my grandfather's house and stood in front of it for a long time."),
   ("الباب كان مسكر، والحديقة صارت يابسة.", "The door was closed, and the garden had become dry."),
   ("جار قديم شافني وعرفني رغم السنين.", "An old neighbor saw me and recognized me despite the years."),
   ("قال: يا هلا فيك، وينك من زمان؟", "He said: welcome back, where have you been all this time?"),
   ("عزمني عالبيت، وقعدنا نتذكر الأيام.", "He invited me to his house, and we sat remembering the old days."),
   ("حكالي مين توفى ومين سافر ومين لسا هون.", "He told me who had passed away, who traveled, and who was still here."),
   ("حسيت إنه الزمن مشى، بس الضيعة ضلت بقلبي.", "I felt that time had passed, but the village stayed in my heart."),
   ("قبل ما أمشي، قطفت زيتونة من شجرة جدي.", "Before I left, I picked an olive from my grandfather's tree."),
   ("حطيتها بجيبي متل الكنز.", "I put it in my pocket like a treasure."),
   ("عرفت يومها إنه الإنسان بيرجع دايما لجذوره.", "That day I learned that a person always returns to their roots."),
 ]),
 ("الأخوين", "The Two Brothers", [
   ("كان في أخوين، الكبير اسمه أحمد والصغير محمود.", "There were two brothers, the elder named Ahmad and the younger Mahmoud."),
   ("لما توفى أبوهم، ترك إلهم أرض وبيت.", "When their father passed away, he left them land and a house."),
   ("بلشوا يتخانقوا مين ياخذ إيش.", "They started arguing over who would take what."),
   ("كل واحد كان بدو الأرض الأحسن.", "Each one wanted the better land."),
   ("الخناق زاد، وصاروا ما يحكوا مع بعض.", "The dispute grew, and they stopped talking to each other."),
   ("العيلة كلها زعلت من هالوضع.", "The whole family was saddened by the situation."),
   ("مرة، مرض أحمد مرض شديد.", "Once, Ahmad became seriously ill."),
   ("محمود سمع الخبر ونسي كل الخناق.", "Mahmoud heard the news and forgot all the fighting."),
   ("ركض على المستشفى وقعد جنب أخوه.", "He ran to the hospital and sat next to his brother."),
   ("أحمد فتح عيونه وشاف أخوه، فبكى.", "Ahmad opened his eyes and saw his brother, and he cried."),
   ("قال: سامحني يا أخوي، الدنيا ما بتسوى خناق.", "He said: forgive me, brother, the world isn't worth fighting over."),
   ("محمود حضنه وقال: إنت أغلى من كل الأرض.", "Mahmoud hugged him and said: you are more precious than all the land."),
   ("من هديك اليوم، رجعوا متل ما كانوا.", "From that day, they went back to how they used to be."),
   ("قسموا الأرض بالعدل وبدون خناق.", "They divided the land fairly and without fighting."),
   ("تعلموا إنه الدم ما بيصير مي.", "They learned that blood doesn't turn to water."),
 ]),
 ("البنت اللي حبت تتعلم", "The Girl Who Loved to Learn", [
   ("بضيعة صغيرة، كان في بنت اسمها ليلى.", "In a small village, there was a girl named Layla."),
   ("ليلى كانت تحب المدرسة أكتر من أي شي.", "Layla loved school more than anything."),
   ("بس المدرسة كانت بعيدة، بساعة مشي.", "But the school was far, an hour's walk away."),
   ("كل الصبح، كانت تصحى بدري وتمشي لحالها.", "Every morning, she would wake up early and walk by herself."),
   ("بالشتا، كانت تمشي تحت المطر والبرد.", "In winter, she would walk under the rain and cold."),
   ("ناس الضيعة قالوا: ليش تتعب حالها هيك؟", "The village people said: why does she tire herself like this?"),
   ("بس أبوها كان يقول: بنتي رح تصير شي كبير.", "But her father would say: my daughter will become something great."),
   ("ليلى كانت الأولى على صفها كل سنة.", "Layla was first in her class every year."),
   ("المعلمين كانوا يفتخروا فيها.", "The teachers were proud of her."),
   ("لما كبرت، راحت عالجامعة بالمدينة.", "When she grew up, she went to the university in the city."),
   ("درست ليل نهار، ونجحت بتفوق.", "She studied day and night, and succeeded with excellence."),
   ("رجعت عالضيعة، بس هالمرة كمعلمة.", "She returned to the village, but this time as a teacher."),
   ("فتحت مدرسة قريبة عشان البنات ما يتعبوا متلها.", "She opened a school nearby so girls wouldn't struggle like her."),
   ("صارت قدوة لكل بنت بالضيعة.", "She became a role model for every girl in the village."),
   ("وأبوها كان أفخر أب بالدنيا.", "And her father was the proudest father in the world."),
 ]),
 ("سنة القحط", "The Year of Drought", [
   ("سنة من السنين، ما نزلت شتا أبدا.", "One year, no rain fell at all."),
   ("الأرض يبست، والزرع مات.", "The land dried up, and the crops died."),
   ("الفلاحين وقفوا حائرين، ما بيعرفوا شو يعملوا.", "The farmers stood bewildered, not knowing what to do."),
   ("الآبار جفت، والمي صارت قليلة.", "The wells ran dry, and water became scarce."),
   ("الناس بلشوا يخافوا عالسنة الجاي.", "The people started to fear for the coming year."),
   ("بهديك السنة، الغني والفقير صاروا سوا.", "In that year, the rich and the poor became the same."),
   ("رجال غني بالضيعة فتح مخزنه للكل.", "A rich man in the village opened his storehouse to everyone."),
   ("قال: اللي عنده، لازم يساعد اللي ما عنده.", "He said: whoever has must help whoever doesn't."),
   ("وزع القمح والزيت عالعيال الفقيرة.", "He distributed wheat and oil to the poor families."),
   ("الناس كلها وقفت مع بعض بهديك الأيام.", "All the people stood together in those days."),
   ("بالآخر، بعد شهور طويلة، نزلت الشتا.", "In the end, after long months, the rain fell."),
   ("الناس طلعوا عالشوارع يرقصوا تحت المطر.", "The people went out to the streets to dance under the rain."),
   ("الأرض شربت، والزرع رجع أخضر.", "The land drank, and the crops turned green again."),
   ("تعلمت الضيعة إنه بالشدة، بيبان معدن الناس.", "The village learned that in hardship, people's true character shows."),
   ("وإنه التعاون بيقهر أصعب الظروف.", "And that cooperation overcomes the hardest of circumstances."),
 ]),
 ("المعلم", "The Teacher", [
   ("لما كنت بالمدرسة، كان في معلم اسمه أستاذ سعيد.", "When I was in school, there was a teacher named Ustaz Sa'id."),
   ("كان مختلف عن باقي المعلمين.", "He was different from the other teachers."),
   ("ما كان بس يعلمنا دروس، كان يعلمنا حياة.", "He didn't just teach us lessons, he taught us life."),
   ("أنا كنت طالب كسلان، ما بحب أدرس.", "I was a lazy student, I didn't like to study."),
   ("مرة، أستاذ سعيد ناداني بعد الدرس.", "Once, Ustaz Sa'id called me after class."),
   ("توقعت إنه رح يوبخني، بس هو ابتسم.", "I expected him to scold me, but he smiled."),
   ("قال: أنا شايف فيك ذكاء، بس إنت مش شايفه.", "He said: I see intelligence in you, but you don't see it."),
   ("حكيه دخل قلبي وغير شي فيي.", "His words entered my heart and changed something in me."),
   ("بلشت أدرس، مش عشان الامتحان، عشان حالي.", "I started to study, not for the exam, but for myself."),
   ("درجاتي تحسنت، وثقتي بحالي كبرت.", "My grades improved, and my confidence in myself grew."),
   ("كل ما كنت أوقع، أستاذ سعيد كان يوقفني.", "Every time I would fall, Ustaz Sa'id would pick me up."),
   ("بعد سنين، تخرجت وصرت مهندس.", "After years, I graduated and became an engineer."),
   ("رجعت عالمدرسة أدور عليه لأشكره.", "I went back to the school to look for him to thank him."),
   ("لقيته كبر بالعمر، بس ابتسامته نفسها.", "I found him aged, but his smile was the same."),
   ("قلتله: إنت السبب إني صرت اللي أنا عليه.", "I told him: you are the reason I became who I am."),
   ("دمعت عيونه وقال: هاي أحلى هدية لمعلم.", "His eyes teared up and he said: this is the nicest gift for a teacher."),
 ]),
 ("الوعد", "The Promise", [
   ("لما كنا صغار، أنا وصاحبي سامي كنا ما ننفصل.", "When we were young, my friend Sami and I were inseparable."),
   ("كل يوم كنا نلعب سوا ونحلم سوا.", "Every day we would play together and dream together."),
   ("مرة، وقفنا عالتلة اللي فوق الضيعة.", "Once, we stood on the hill above the village."),
   ("سامي قال: خلينا نوعد بعض نضل أصحاب للأبد.", "Sami said: let's promise each other to stay friends forever."),
   ("مديت إيدي وقلتله: وعد.", "I extended my hand and told him: promise."),
   ("بس الحياة فرقتنا، هو سافر وأنا ضليت.", "But life separated us; he traveled and I stayed."),
   ("مرت سنين طويلة وما سمعت عنه خبر.", "Long years passed and I heard no news of him."),
   ("كنت أفكر فيه كل ما أطلع عالتلة.", "I would think of him every time I climbed the hill."),
   ("يوم، وأنا قاعد بالبيت، دق التلفون.", "One day, while I was sitting at home, the phone rang."),
   ("صوت قال: بتذكر الوعد اللي وعدناه؟", "A voice said: do you remember the promise we made?"),
   ("عرفت الصوت على طول، كان سامي.", "I recognized the voice right away, it was Sami."),
   ("قال إنه راجع عالضيعة بعد كل هالسنين.", "He said he was returning to the village after all these years."),
   ("اتفقنا نتقابل عالتلة، نفس المكان.", "We agreed to meet on the hill, the same spot."),
   ("لما شفته، عرفته رغم إنه كبر.", "When I saw him, I recognized him even though he had aged."),
   ("عانقنا بعض وضحكنا وبكينا بنفس الوقت.", "We hugged and laughed and cried at the same time."),
   ("قال: قلتلك رح نضل أصحاب للأبد.", "He said: I told you we'd stay friends forever."),
 ]),
 ("العصفور والقفص", "The Bird and the Cage", [
   ("رجال كان عنده عصفور حلو بقفص ذهبي.", "A man had a beautiful bird in a golden cage."),
   ("كان يطعمه أحسن أكل ويهتم فيه كتير.", "He would feed it the best food and care for it a lot."),
   ("بس العصفور ما كان يغني أبدا.", "But the bird never used to sing."),
   ("الرجال حار، ليش عصفوره حزين؟", "The man was puzzled, why was his bird sad?"),
   ("جاب له قفص أكبر وأحلى، بس ما فرقت.", "He got it a bigger and nicer cage, but it made no difference."),
   ("مرة، إجاه ضيف حكيم وشاف العصفور.", "Once, a wise guest came to him and saw the bird."),
   ("قال: هالعصفور ما بيغني لأنه مش حر.", "He said: this bird doesn't sing because it isn't free."),
   ("الرجال قال: بس أنا بحبه وبهتم فيه.", "The man said: but I love it and I care for it."),
   ("الحكيم رد: المحبة الحقيقية إنك تطلق اللي بتحبه.", "The wise man replied: true love is to release the one you love."),
   ("الرجال فكر طويل بهالحكي.", "The man thought for a long time about these words."),
   ("الصبح التاني، حمل القفص وطلع عالحديقة.", "The next morning, he carried the cage and went out to the garden."),
   ("فتح باب القفص وقال: روح، إنت حر.", "He opened the cage door and said: go, you are free."),
   ("العصفور طار عالشجرة القريبة.", "The bird flew to the nearby tree."),
   ("وقف هناك، وبلش يغني أحلى غنا.", "It stood there, and started to sing the most beautiful song."),
   ("الرجال حس بفرح ما حسه من قبل.", "The man felt a joy he had never felt before."),
   ("فهم يومها إنه الحرية أغلى من الذهب.", "That day he understood that freedom is more precious than gold."),
 ]),
 ("ليلة العرس", "The Wedding Night", [
   ("قبل العرس بأسبوع، البيت انقلب رأسا على عقب.", "A week before the wedding, the house turned upside down."),
   ("النسوان كانوا يحضروا والرجال يرتبوا.", "The women were preparing and the men were organizing."),
   ("إمي قالت للعروس: هاي أحلى أيام عمرك.", "My mom said to the bride: these are the best days of your life."),
   ("العروس كانت مبسوطة بس خايفة بنفس الوقت.", "The bride was happy but scared at the same time."),
   ("قالت: رح أوحشكم كتير.", "She said: I'll miss you all a lot."),
   ("ليلة العرس، القاعة كانت مليانة ضو وناس.", "On the wedding night, the hall was full of lights and people."),
   ("الدبكة اشتغلت، والكل صار يرقص.", "The dabke started, and everyone began to dance."),
   ("جدتي، رغم كبر سنها، رقصت شوي.", "My grandmother, despite her old age, danced a little."),
   ("العريس إجا ولابس بدلة وواقف بفخر.", "The groom came wearing a suit and standing proudly."),
   ("لما شاف العروس، عيونه لمعت.", "When he saw the bride, his eyes sparkled."),
   ("الأهل زغردوا، والفرح عم بالمكان.", "The relatives ululated, and joy filled the place."),
   ("أبو العروس وقف يحكي، وصوته كان مخنوق.", "The bride's father stood to speak, and his voice was choked."),
   ("قال: بنتي، بيتك الجديد قريب من قلبنا.", "He said: my daughter, your new home is close to our hearts."),
   ("رقصنا وغنينا لطلوع الفجر.", "We danced and sang until dawn."),
   ("كانت ليلة ما بتننسى، مليانة محبة وفرح.", "It was an unforgettable night, full of love and joy."),
 ]),
 ("الصياد", "The Fisherman", [
   ("بقرية عالبحر، كان في صياد قديم اسمه أبو موسى.", "In a village by the sea, there was an old fisherman named Abu Musa."),
   ("كل الصبح، كان يطلع عالبحر بقاربه الصغير.", "Every morning, he would go out to sea in his small boat."),
   ("كان يعرف البحر متل ما يعرف إيده.", "He knew the sea like he knew his own hand."),
   ("الناس كانوا يقولوا إنه بيحكي مع الموج.", "People used to say he talked to the waves."),
   ("مرة، طلع بيوم والجو صافي.", "Once, he went out on a clear day."),
   ("بس فجأة، هبت ريح قوية وصارت عاصفة.", "But suddenly, a strong wind blew and a storm arose."),
   ("الموج علا، والقارب صار يترنح.", "The waves rose, and the boat began to sway."),
   ("الناس عالشط خافوا عليه كتير.", "The people on the shore were very afraid for him."),
   ("بس أبو موسى ما خاف، لأنه يعرف البحر.", "But Abu Musa wasn't afraid, because he knew the sea."),
   ("مسك الدفة بقوة وصبر عالعاصفة.", "He gripped the rudder tightly and endured the storm."),
   ("بعد ساعات، هدت الريح وصفى الجو.", "After hours, the wind calmed and the weather cleared."),
   ("أبو موسى رجع عالشط، تعبان بس بأمان.", "Abu Musa returned to the shore, tired but safe."),
   ("الناس استقبلوه بالفرح والحمد لله.", "The people welcomed him with joy and thanks to God."),
   ("سألوه: ما خفت تغرق؟", "They asked him: weren't you afraid you'd drown?"),
   ("ضحك وقال: البحر بيحترم اللي بيحترمه.", "He laughed and said: the sea respects those who respect it."),
 ]),
 ("الجار الفقير", "The Poor Neighbor", [
   ("بحارتنا، كان في جار فقير اسمه أبو علي.", "In our neighborhood, there was a poor neighbor named Abu Ali."),
   ("كان يشتغل نهار وليل عشان يطعم ولاده.", "He worked day and night to feed his children."),
   ("رغم فقره، كان دايما مبتسم وطيب.", "Despite his poverty, he was always smiling and kind."),
   ("مرة، مرض ولده وما كان معه مصاري للدوا.", "Once, his child got sick and he had no money for medicine."),
   ("كان محتار ومهموم، ما بيعرف شو يعمل.", "He was confused and worried, not knowing what to do."),
   ("ناس الحارة سمعوا بالخبر.", "The people of the neighborhood heard the news."),
   ("بدون ما يقول حدا، جمعوا مصاري بينهم.", "Without anyone saying so, they collected money among themselves."),
   ("حطوها بمغلف وحطوه تحت باب أبو علي.", "They put it in an envelope and placed it under Abu Ali's door."),
   ("الصبح، أبو علي لقى المغلف واستغرب.", "In the morning, Abu Ali found the envelope and was surprised."),
   ("أخذ ولده عالدكتور واشترى الدوا.", "He took his child to the doctor and bought the medicine."),
   ("الولد طاب، وأبو علي ما عرف مين ساعده.", "The child recovered, and Abu Ali never knew who helped him."),
   ("سأل الجيران، بس محدا اعترف.", "He asked the neighbors, but no one admitted it."),
   ("قال: الله يجازي اللي عمل هالخير.", "He said: may God reward whoever did this good deed."),
   ("من يومها، صار أبو علي يساعد كل محتاج.", "From that day, Abu Ali started helping everyone in need."),
   ("قال: الخير اللي وصلني، لازم أمرره لغيري.", "He said: the good that reached me, I must pass on to others."),
 ]),
 ("الحصاد الأخير", "The Last Harvest", [
   ("جدي كان فلاح طول عمره.", "My grandfather was a farmer his whole life."),
   ("الأرض كانت كل حياته، وهو ما بيعرف غيرها.", "The land was his whole life, and he knew nothing else."),
   ("لما كبر بالعمر، صار الشغل صعب عليه.", "When he grew old, the work became hard for him."),
   ("بس كل موسم، كان يصر يحصد بإيده.", "But every season, he insisted on harvesting with his own hands."),
   ("سنة، حسينا إنه هاي رح تكون آخر حصاد إله.", "One year, we felt this would be his last harvest."),
   ("العيلة كلها إجت تساعده بالحصاد.", "The whole family came to help him with the harvest."),
   ("جدي وقف بوسط الحقل، وعيونه مليانة دموع.", "My grandfather stood in the middle of the field, his eyes full of tears."),
   ("قال: هالأرض عمرتها بعرق جبيني.", "He said: I built up this land with the sweat of my brow."),
   ("قال: خذوا منها العبرة، الأرض ما بتخون.", "He said: take a lesson from it, the land never betrays."),
   ("حصدنا سوا من الصبح للمسا.", "We harvested together from morning to evening."),
   ("جدي كان يعلم الأحفاد كيف يمسكوا المنجل.", "My grandfather taught the grandchildren how to hold the sickle."),
   ("آخر النهار، جلسنا كلنا نأكل تحت الشجرة.", "At the end of the day, we all sat eating under the tree."),
   ("جدي نظر للحقل المحصود وابتسم بارتياح.", "My grandfather looked at the harvested field and smiled with contentment."),
   ("بعد هديك السنة، توفى جدي بهدوء.", "After that year, my grandfather passed away peacefully."),
   ("بس كل موسم حصاد، بنحس إنه معنا بالحقل.", "But every harvest season, we feel he is with us in the field."),
 ]),
 ("المفتاح القديم", "The Old Key", [
   ("لما توفت جدتي، ورثنا بيتها القديم.", "When my grandmother passed away, we inherited her old house."),
   ("بين أغراضها، لقينا مفتاح حديد قديم.", "Among her things, we found an old iron key."),
   ("محدا عرف هالمفتاح لأي باب.", "No one knew which door this key belonged to."),
   ("جربناه على كل أبواب البيت، بس ما فتح.", "We tried it on every door of the house, but it didn't open any."),
   ("إمي تذكرت إنه جدتي كانت تحكي عن صندوق.", "My mom remembered that grandma used to talk about a chest."),
   ("دورنا بالبيت كله لحتى لقينا الصندوق بالعلية.", "We searched the whole house until we found the chest in the attic."),
   ("حطينا المفتاح، ودار، وانفتح الصندوق.", "We put the key in, it turned, and the chest opened."),
   ("جوا، لقينا صور قديمة ورسائل ودفتر.", "Inside, we found old pictures, letters, and a notebook."),
   ("الدفتر كان مذكرات جدتي من أيام شبابها.", "The notebook was my grandmother's diary from her youth."),
   ("قعدنا نقرا، وعرفنا قصص ما سمعناها من قبل.", "We sat reading, and learned stories we'd never heard before."),
   ("عرفنا كيف تعرفت على جدي، وكيف تجوزوا.", "We learned how she met my grandfather, and how they married."),
   ("كل صفحة كانت تحكي عن محبة وصبر.", "Every page spoke of love and patience."),
   ("حسينا إنه جدتي رجعت تحكيلنا بصوتها.", "We felt that grandma had come back to tell us in her voice."),
   ("من يومها، حطينا الصندوق بمكان أمين.", "From that day, we put the chest in a safe place."),
   ("وصار متل الكنز اللي بيربط الأجيال ببعض.", "And it became like a treasure that ties the generations together."),
 ]),
 ("الغريب بالمطر", "The Stranger in the Rain", [
   ("ليلة، كنت راجع عالبيت والشتا نازلة بقوة.", "One night, I was going home while the rain poured heavily."),
   ("عالطريق، شفت رجال كبير واقف تحت المطر.", "On the road, I saw an old man standing under the rain."),
   ("كان مبلول وعم يرتجف من البرد.", "He was soaked and trembling from the cold."),
   ("وقفت جنبه وسألته: عمو، ليش واقف هون؟", "I stopped next to him and asked: uncle, why are you standing here?"),
   ("قال: ضيعت طريقي، وما بعرف وين أروح.", "He said: I lost my way, and I don't know where to go."),
   ("قلتله: يلا معي، ما بينفع تضل بالبرد.", "I told him: come with me, you can't stay in the cold."),
   ("أخذته عالبيت، وإمي سخنتله أكل وشاي.", "I took him home, and my mom heated food and tea for him."),
   ("قعد يتدفى، وحكالنا إنه بيدور على ابنه.", "He sat warming up, and told us he was looking for his son."),
   ("قال إنه ما شاف ابنه من سنين طويلة.", "He said he hadn't seen his son in long years."),
   ("الصبح، ساعدته ندور على عنوان ابنه.", "In the morning, I helped him look for his son's address."),
   ("بعد تعب، لقينا البيت، ودقينا الباب.", "After some effort, we found the house and knocked on the door."),
   ("فتح شاب، وأول ما شاف الرجال، جمد بمكانه.", "A young man opened, and the moment he saw the old man, he froze in place."),
   ("قال بصوت مرتجف: بابا؟ إنت؟", "He said in a trembling voice: dad? is it you?"),
   ("عانقوا بعض وبكوا، ونسيوا كل السنين.", "They hugged and cried, and forgot all the years."),
   ("مشيت من هناك، وقلبي مليان بفرح غريب.", "I walked away from there, my heart full of a strange joy."),
 ]),
 ("حلم البحر", "The Dream of the Sea", [
   ("بضيعة بعيدة عن البحر، عاش ولد اسمه ماجد.", "In a village far from the sea, lived a boy named Majid."),
   ("ماجد ما كان شاف البحر بحياته.", "Majid had never seen the sea in his life."),
   ("بس كان يحلم فيه كل ليلة.", "But he dreamed of it every night."),
   ("جده حكاله عن البحر، عن زرقته واتساعه.", "His grandfather told him about the sea, its blueness and vastness."),
   ("ماجد قال: يوم من الأيام، رح أشوف البحر.", "Majid said: one day, I will see the sea."),
   ("كبر ماجد، واشتغل وجمع مصاري شوي شوي.", "Majid grew up, worked, and saved money little by little."),
   ("لما صار معه كفاية، قرر يسافر عالبحر.", "When he had enough, he decided to travel to the sea."),
   ("الطريق كان طويل، بس قلبه كان طاير من الفرح.", "The road was long, but his heart was flying with joy."),
   ("لما وصل، وقف عالشط وشاف البحر لأول مرة.", "When he arrived, he stood on the shore and saw the sea for the first time."),
   ("وقف صامت، وعيونه مليانة دموع.", "He stood silent, his eyes full of tears."),
   ("البحر كان أكبر وأحلى من كل أحلامه.", "The sea was bigger and more beautiful than all his dreams."),
   ("نزل عالمي، وحس ببرودتها على قدميه.", "He went into the water, and felt its coolness on his feet."),
   ("ضحك متل الولاد، وصرخ من الفرح.", "He laughed like children, and shouted from joy."),
   ("قعد لآخر النهار يتفرج عالموج.", "He sat until the end of the day watching the waves."),
   ("قال لحاله: الأحلام بتتحقق للي بيصبر.", "He said to himself: dreams come true for those who are patient."),
 ]),
 ("الجدة الحكيمة", "The Wise Grandmother", [
   ("بالضيعة، كانت في ست كبيرة الكل يحترمها.", "In the village, there was an old lady everyone respected."),
   ("كانوا يسموها الحجة أم يوسف.", "They called her Hajjeh Um Yusuf."),
   ("لما يصير في مشكلة، الناس تروح تستشيرها.", "When a problem arose, people would go to consult her."),
   ("كانت تسمع الكل بصبر، وبعدين تحكي.", "She would listen to everyone with patience, then speak."),
   ("مرة، جارين اتخانقوا على حد الأرض.", "Once, two neighbors argued over the boundary of the land."),
   ("راحوا عند الحجة، وكل واحد حكى قصته.", "They went to the Hajjeh, and each one told his side."),
   ("الحجة سمعتهم، وبعدين سألت سؤال بسيط.", "The Hajjeh listened to them, then asked a simple question."),
   ("قالت: شو بتسوى الأرض إذا خسرتوا بعض؟", "She said: what is the land worth if you lose each other?"),
   ("الجارين سكتوا وفكروا بالحكي.", "The two neighbors fell silent and thought about the words."),
   ("قالت: الجار قبل الدار، والصاحب قبل الأرض.", "She said: the neighbor before the house, the friend before the land."),
   ("الجارين نظروا لبعض، وحسوا بالخجل.", "The two neighbors looked at each other, and felt ashamed."),
   ("مدوا إيديهم وتصالحوا قدام الحجة.", "They extended their hands and reconciled in front of the Hajjeh."),
   ("الحجة ابتسمت وقالت: هيك بيكون العقلاء.", "The Hajjeh smiled and said: this is how wise people act."),
   ("رجعوا عبيوتهم، والقلوب صافية.", "They returned to their homes, their hearts clear."),
   ("حكمة الحجة ضلت تتناقل بالضيعة لأجيال.", "The Hajjeh's wisdom kept being passed down in the village for generations."),
 ]),
 ("السفر الأول", "The First Journey", [
   ("أول مرة سافرت لحالي، كنت بعمر التمنتعش.", "The first time I traveled alone, I was eighteen years old."),
   ("كنت رايح عالمدينة أكمل دراستي.", "I was going to the city to continue my studies."),
   ("إمي حضرتلي شنطة مليانة أكل وأواعي.", "My mom prepared me a bag full of food and clothes."),
   ("عالمحطة، أبوي حطلي إيده على كتفي.", "At the station, my dad put his hand on my shoulder."),
   ("قال: يا ابني، احترم حالك يحترموك الناس.", "He said: my son, respect yourself and people will respect you."),
   ("إمي بكت، وأنا حاولت ما أبكي قدامها.", "My mom cried, and I tried not to cry in front of her."),
   ("ركبت الباص، وطل رأسي من الشباك أودعهم.", "I got on the bus, and stuck my head out the window to say goodbye."),
   ("الباص مشى، والضيعة صارت تصغر ورايا.", "The bus moved, and the village grew smaller behind me."),
   ("لأول مرة، حسيت إني لحالي بهالدنيا.", "For the first time, I felt I was alone in this world."),
   ("المدينة كانت كبيرة وغريبة ومليانة ناس.", "The city was big and strange and full of people."),
   ("بالأول، تهت وما عرفت وين أروح.", "At first, I got lost and didn't know where to go."),
   ("بس شوي شوي، تعلمت وتعودت.", "But little by little, I learned and got used to it."),
   ("كل ليلة، كنت أتصل بأهلي وأطمنهم.", "Every night, I would call my family and reassure them."),
   ("بعد سنين، تخرجت، ورجعت عالضيعة مهندس.", "After years, I graduated and returned to the village an engineer."),
   ("أبوي وإمي استقبلوني عالباب، وعيونهم تلمع بالفخر.", "My dad and mom welcomed me at the door, their eyes shining with pride."),
 ]),
 ("عصفور الجنة", "The Sparrow", [
   ("بحديقة بيتنا، عشش عصفور صغير عالشجرة.", "In our house garden, a little sparrow nested in the tree."),
   ("كل الصبح، كان يصحينا بغناه الحلو.", "Every morning, it would wake us with its beautiful singing."),
   ("الولاد كانوا يحطولوا فتات خبز ومي.", "The kids would put out bread crumbs and water for it."),
   ("صار العصفور يعرفنا وما يخاف مننا.", "The sparrow came to know us and wasn't afraid of us."),
   ("مرة، هبت عاصفة قوية بالليل.", "Once, a strong storm blew at night."),
   ("الصبح، لقينا العش وقع عالأرض.", "In the morning, we found the nest had fallen to the ground."),
   ("الولاد زعلوا، وخافوا إنه العصفور مات.", "The kids got upset, and feared the sparrow had died."),
   ("بس لقيناه واقف عالغصن، سليم.", "But we found it standing on the branch, safe."),
   ("جمعنا العش وحطيناه بمكان أعلى وأأمن.", "We gathered the nest and put it in a higher, safer place."),
   ("العصفور رجعله، وكأنه بيشكرنا.", "The sparrow returned to it, as if thanking us."),
   ("بعد أسابيع، طلعت من العش عصافير صغيرة.", "After weeks, little sparrows emerged from the nest."),
   ("الولاد فرحوا كأنه في مواليد جداد بالعيلة.", "The kids were as happy as if there were new babies in the family."),
   ("راقبناهم لما كبروا وتعلموا الطيران.", "We watched them until they grew and learned to fly."),
   ("يوم، طاروا كلهم، وضل العش فاضي.", "One day, they all flew away, and the nest stayed empty."),
   ("بس كل ربيع، بيرجع عصفور يعشش بنفس الشجرة.", "But every spring, a sparrow comes back to nest in the same tree."),
 ]),
 ("الدين", "The Debt", [
   ("زمان، كان في رجال طيب اسمه أبو حسن.", "Long ago, there was a kind man named Abu Hasan."),
   ("مرة، ضاق حاله، ودان مصاري من جاره.", "Once, times got hard, and he borrowed money from his neighbor."),
   ("الجار عطاه بدون تردد، وقال: خذ وقتك.", "The neighbor gave it without hesitation, and said: take your time."),
   ("أبو حسن اشتغل ليل نهار عشان يرد الدين.", "Abu Hasan worked day and night to repay the debt."),
   ("كل ما يجمع شوي، كان يصير في حاجة تصرفه.", "Every time he saved a little, some need would spend it."),
   ("بس هو ما نسي دينه أبدا.", "But he never forgot his debt."),
   ("بعد سنة، جمع المبلغ كامل.", "After a year, he gathered the full amount."),
   ("راح لجاره، ومد له المصاري.", "He went to his neighbor, and handed him the money."),
   ("الجار رفض، وقال: أنا سامحتك من زمان.", "The neighbor refused, and said: I forgave you long ago."),
   ("أبو حسن قال: لأ، الدين دين، ولازم يترد.", "Abu Hasan said: no, a debt is a debt, and it must be repaid."),
   ("الجار تأثر من صدقه وأمانته.", "The neighbor was moved by his honesty and integrity."),
   ("أخذ المصاري، بس رجعله نصها هدية.", "He took the money, but gave him back half as a gift."),
   ("قال: هاي مكافأة على أمانتك.", "He said: this is a reward for your integrity."),
   ("من يومها، صاروا أحسن أصحاب.", "From that day, they became the best of friends."),
   ("والحارة كلها حكت عن أمانة أبو حسن.", "And the whole neighborhood spoke of Abu Hasan's integrity."),
 ]),
 ("البيت المهجور", "The Abandoned House", [
   ("بآخر الحارة، كان في بيت قديم مهجور.", "At the end of the neighborhood, there was an old abandoned house."),
   ("الولاد كانوا يخافوا يقربوا منه.", "The kids were afraid to go near it."),
   ("كانوا يقولوا إنه مسكون وفيه أشباح.", "They used to say it was haunted and had ghosts."),
   ("أنا كنت فضولي، وحبيت أعرف الحقيقة.", "I was curious, and wanted to know the truth."),
   ("يوم، جمعت شجاعتي وقربت من البيت.", "One day, I gathered my courage and approached the house."),
   ("الباب كان مفتوح شوي، فدخلت بحذر.", "The door was slightly open, so I entered cautiously."),
   ("جوا، كان في غبار وعناكب وأثاث قديم.", "Inside, there was dust, spiders, and old furniture."),
   ("بس ما كان في أشباح، بس ذكريات قديمة.", "But there were no ghosts, only old memories."),
   ("لقيت صور معلقة عالحيط لعيلة زمان.", "I found pictures hung on the wall of a family from long ago."),
   ("عرفت إنه البيت كان مليان حياة ومحبة.", "I realized the house had been full of life and love."),
   ("سألت جدي عن هالبيت، فحكالي قصته.", "I asked my grandfather about this house, and he told me its story."),
   ("قال إنه أهله سافروا برا وما رجعوا.", "He said its people traveled abroad and never returned."),
   ("حسيت بحزن على بيت نساه أهله.", "I felt sad for a house forgotten by its people."),
   ("من يومها، ما عدت أخاف منه.", "From that day, I was no longer afraid of it."),
   ("عرفت إنه أكتر شي مخيف، هو النسيان.", "I learned that the scariest thing is being forgotten."),
 ]),
 ("صوت العود", "The Sound of the Oud", [
   ("جاري أبو نبيل كان يعزف عود من زمان.", "My neighbor Abu Nabil used to play the oud long ago."),
   ("كل مسا، كنا نسمع صوت عوده من الشباك.", "Every evening, we would hear the sound of his oud from the window."),
   ("اللحن كان حزين حلو، بيلمس القلب.", "The melody was sad and sweet, touching the heart."),
   ("مرة، سألته: ليش ألحانك حزينة يا عمو؟", "Once, I asked him: why are your melodies sad, uncle?"),
   ("حط العود جنبه، وحكالي قصته.", "He put the oud beside him, and told me his story."),
   ("قال إنه كان عنده بنت بتحب الموسيقى.", "He said he had a daughter who loved music."),
   ("كانت تقعد جنبه وتسمعه وهو يعزف.", "She used to sit beside him and listen as he played."),
   ("بس البنت مرضت وتوفت وهي صغيرة.", "But the daughter got sick and passed away while young."),
   ("من يومها، صار يعزف عشانها هي.", "From that day, he started playing for her."),
   ("قال: العزف بيخليها قريبة من قلبي.", "He said: playing keeps her close to my heart."),
   ("سمعت قصته، ودمعت عيوني.", "I heard his story, and my eyes teared up."),
   ("من هديك اليوم، صرت أسمع عزفه بشكل تاني.", "From that day, I began to hear his playing differently."),
   ("كل لحن كان يحكي عن محبة أب لبنته.", "Every melody spoke of a father's love for his daughter."),
   ("قلتله: عزفك بيخلي بنتك حية بقلوبنا كلنا.", "I told him: your playing keeps your daughter alive in all our hearts."),
   ("ابتسم بحزن، ورجع يعزف لحنه الحلو.", "He smiled sadly, and went back to playing his sweet melody."),
 ]),
 ("المطر الأول", "The First Rain", [
   ("بعد صيف طويل وحار، الكل كان يستنى الشتا.", "After a long, hot summer, everyone was waiting for the rain."),
   ("الأرض كانت عطشانة، والزرع كان محتاج مي.", "The land was thirsty, and the crops needed water."),
   ("يوم، صارت السما رمادية، وهبت ريح باردة.", "One day, the sky turned gray, and a cold wind blew."),
   ("ريحة التراب قبل المطر ملت الجو.", "The smell of the earth before the rain filled the air."),
   ("الولاد وقفوا عالشبابيك يستنوا.", "The kids stood at the windows waiting."),
   ("وفجأة، نزلت أول قطرة، وبعدها انهمرت الشتا.", "And suddenly, the first drop fell, and then the rain poured down."),
   ("الولاد صرخوا من الفرح وركضوا عالحديقة.", "The kids screamed with joy and ran to the garden."),
   ("لعبوا تحت المطر وانبلوا كلهم.", "They played in the rain and got completely soaked."),
   ("الكبار وقفوا عالبواب، يتفرجوا ويبتسموا.", "The grown-ups stood at the doors, watching and smiling."),
   ("جدي مد إيده وحس بالمطر على كفه.", "My grandfather extended his hand and felt the rain on his palm."),
   ("قال: هاي بركة من الله عالأرض والناس.", "He said: this is a blessing from God on the land and the people."),
   ("الأرض شربت، وريحتها طلعت حلوة.", "The land drank, and its smell became sweet."),
   ("بالمسا، وقفت الشتا، وطلع قوس قزح.", "In the evening, the rain stopped, and a rainbow appeared."),
   ("الولاد وقفوا يتفرجوا عليه بدهشة.", "The kids stood watching it in wonder."),
   ("كانت أول شتوية، وأحلى يوم بالخريف.", "It was the first rain, and the nicest day of the fall."),
 ]),
 ("الكنز", "The Treasure", [
   ("جدي كان دايما يقول: عنا كنز بالبيت.", "My grandfather always used to say: we have a treasure in the house."),
   ("إحنا الولاد، كنا ندور عليه بكل زاوية.", "We kids used to search for it in every corner."),
   ("فتشنا بالخزاين، وتحت السراير، وبالعلية.", "We searched the cabinets, under the beds, and in the attic."),
   ("بس ما لقينا لا ذهب ولا مصاري.", "But we found neither gold nor money."),
   ("سألنا جدي: وين الكنز؟ ما لقيناه.", "We asked our grandfather: where is the treasure? We didn't find it."),
   ("ضحك جدي وقال: الكنز مش شي بتلاقوه بإيدكم.", "My grandfather laughed and said: the treasure isn't something you find with your hands."),
   ("كبرنا، وكل واحد راح بطريقه.", "We grew up, and each of us went their own way."),
   ("بس كل عيد، كنا نرجع نجتمع ببيت جدي.", "But every holiday, we would come back to gather at grandpa's house."),
   ("كنا نقعد حوالي الطاولة، ونحكي ونضحك.", "We would sit around the table, talking and laughing."),
   ("جدي كان ينظر إلنا، وعيونه مليانة فرح.", "My grandfather would look at us, his eyes full of joy."),
   ("يوم، قبل ما يتوفى، جمعنا كلنا حواليه.", "One day, before he passed away, he gathered us all around him."),
   ("قال: هلأ فهمتوا شو هو الكنز؟", "He said: now do you understand what the treasure is?"),
   ("نظر لوجوهنا، وقال: إنتوا الكنز، عيلتي.", "He looked at our faces, and said: you are the treasure, my family."),
   ("سكتنا كلنا، وحسينا بمعنى كلامه.", "We all fell silent, and felt the meaning of his words."),
   ("من يومها، عرفنا إنه أغلى كنز هو الأهل.", "From that day, we knew that the most precious treasure is family."),
 ]),
 ("الطريق عالمدرسة", "The Road to School", [
   ("زمان، الطريق عالمدرسة كان طويل وصعب.", "Long ago, the road to school was long and hard."),
   ("كنا نمشي نص ساعة بين الحقول والجبال.", "We used to walk half an hour between the fields and mountains."),
   ("بالشتا، الطريق كان يصير طين ومي.", "In winter, the road would turn to mud and water."),
   ("وبالصيف، الشمس كانت تحرقنا.", "And in summer, the sun would burn us."),
   ("بس رغم هيك، كنا نروح كل يوم مبسوطين.", "But despite this, we would go every day happily."),
   ("بالطريق، كنا نلعب ونضحك ونتسابق.", "On the way, we would play, laugh, and race."),
   ("مرة، لقينا كلب صغير تايه وجعان.", "Once, we found a small lost and hungry dog."),
   ("أطعمناه من زوادتنا، وصار يمشي معنا.", "We fed it from our lunch, and it started walking with us."),
   ("كل يوم، كان يستنانا عند نفس الشجرة.", "Every day, it would wait for us by the same tree."),
   ("سميناه صاحب، وصار جزء من طريقنا.", "We named it Sahib, and it became part of our journey."),
   ("لما كبرنا وخلصنا المدرسة، افترقنا.", "When we grew up and finished school, we parted."),
   ("بس لهلأ، بتذكر هديك الطريق وصحابي.", "But to this day, I remember that road and my friends."),
   ("الطريق كان صعب، بس علمنا الصبر.", "The road was hard, but it taught us patience."),
   ("وعلمنا إنه الرفقة بتخفف أصعب طريق.", "And it taught us that companionship eases the hardest road."),
   ("لهلأ، كل ما أشوف مدرسة، بتذكر مشوارنا.", "To this day, every time I see a school, I remember our journey."),
 ]),
 ("الشجرة والفصول", "The Tree and the Seasons", [
   ("قدام بيتنا، كانت في شجرة توت كبيرة.", "In front of our house, there was a big mulberry tree."),
   ("كانت تتغير مع كل فصل بالسنة.", "It would change with every season of the year."),
   ("بالربيع، كانت تلبس ورق أخضر وزهر.", "In spring, it would wear green leaves and blossoms."),
   ("بالصيف، كانت تعطينا ظل وتوت حلو.", "In summer, it would give us shade and sweet mulberries."),
   ("الولاد كانوا يطلعوا عليها ياكلوا التوت.", "The kids would climb it to eat the mulberries."),
   ("بالخريف، ورقها كان يصفر ويوقع.", "In fall, its leaves would yellow and fall."),
   ("كنا نلعب بالورق اليابس ونجمعه.", "We would play with the dry leaves and gather them."),
   ("وبالشتا، كانت تصير عريانة، بس واقفة بقوة.", "And in winter, it would become bare, but standing strong."),
   ("جدي كان يقول: هالشجرة متل الإنسان.", "My grandfather would say: this tree is like a human being."),
   ("قال: بتمر بفصول، حلوة وصعبة.", "He said: it goes through seasons, good and hard."),
   ("قال: المهم تضل واقف متل الشجرة بالشتا.", "He said: what matters is to stay standing like the tree in winter."),
   ("كبرت، وفهمت حكمة جدي أكتر.", "I grew up, and understood my grandfather's wisdom more."),
   ("الحياة إلها فصول، وكل فصل بيعدي.", "Life has seasons, and every season passes."),
   ("والصعب بيروح، متل ما الشتا بيروح.", "And hardship goes away, just as winter goes away."),
   ("والشجرة، متل الأمل، بترجع تخضر من جديد.", "And the tree, like hope, turns green again."),
 ]),
 ("الهدية", "The Gift", [
   ("قرب عيد ميلاد إمي، وأنا كنت صغير.", "My mom's birthday was near, and I was little."),
   ("ما كان معي مصاري أشتريلها هدية.", "I had no money to buy her a gift."),
   ("فكرت كتير، شو ممكن أعطيها.", "I thought a lot about what I could give her."),
   ("قررت أعملها هدية بإيدي.", "I decided to make her a gift with my own hands."),
   ("قعدت أرسم وأكتب لأيام.", "I sat drawing and writing for days."),
   ("عملتلها بطاقة، وكتبت فيها كل محبتي.", "I made her a card, and wrote all my love in it."),
   ("جمعت ورد من الحديقة، وحطيته بالبطاقة.", "I gathered flowers from the garden, and put them in the card."),
   ("يوم عيدها، خبيت الهدية ورا ظهري.", "On her birthday, I hid the gift behind my back."),
   ("قلتلها: إمي، عندي إلك مفاجأة.", "I told her: mom, I have a surprise for you."),
   ("مديت إيدي وعطيتها البطاقة.", "I extended my hand and gave her the card."),
   ("قرأتها، وعيونها امتلت بالدموع.", "She read it, and her eyes filled with tears."),
   ("حضنتني بقوة، وقالت: هاي أحلى هدية بحياتي.", "She hugged me tightly, and said: this is the nicest gift of my life."),
   ("قلتلها: بس هي بسيطة، ما فيها مصاري.", "I told her: but it's simple, it has no money in it."),
   ("قالت: أغلى الهدايا هي اللي من القلب.", "She said: the most precious gifts are the ones from the heart."),
   ("من يومها، عرفت إنه المحبة أغلى من كل مصاري الدنيا.", "From that day, I knew that love is more precious than all the money in the world."),
 ]),
 ("قنديل جدي", "My Grandfather's Lantern", [
   ("قبل ما يوصل الكهربا عالضيعة، كان الناس يستعملوا قناديل.", "Before electricity reached the village, people used lanterns."),
   ("جدي كان عنده قنديل قديم بيضويله الليل.", "My grandfather had an old lantern that lit up his night."),
   ("كل مسا، كان يشعله ويحطه عالطاولة.", "Every evening, he would light it and put it on the table."),
   ("حواليه، كانت العيلة تجتمع تحكي وتضحك.", "Around it, the family would gather to talk and laugh."),
   ("جدي كان يحكينا قصص عالضو الخافت.", "My grandfather would tell us stories by the dim light."),
   ("كنا نسمعه ونحن مشدودين، وظلالنا عالحيط.", "We would listen to him, captivated, our shadows on the wall."),
   ("لما إجت الكهربا، الكل فرح بالضو الجديد.", "When electricity came, everyone was happy with the new light."),
   ("بس جدي ضل يحب قنديله القديم.", "But my grandfather kept loving his old lantern."),
   ("قلتله: يا جدي، الكهربا أحسن وأقوى.", "I told him: grandpa, electricity is better and stronger."),
   ("ابتسم وقال: الضو القوي بيوري كل شي.", "He smiled and said: strong light shows everything."),
   ("قال: بس ضو القنديل بيخلي القلوب تقرب.", "He said: but the lantern's light makes hearts draw closer."),
   ("ما فهمت حكيه وأنا صغير.", "I didn't understand his words when I was young."),
   ("بس هلأ، وكل واحد غارق بتلفونه، فهمت.", "But now, with everyone lost in their phone, I understand."),
   ("لسا محتفظ بقنديل جدي لهلأ.", "I still keep my grandfather's lantern to this day."),
   ("وكل ما أشعله، بترجع تلك الليالي الدافية.", "And every time I light it, those warm nights come back."),
 ]),
]

def main():
    from bookshelf import check_sentences
    rc = check_sentences('advanced stories',
                         [(a, e) for _t, _te, ss in STORIES for a, e in ss])
    if rc:
        return rc
    tdir = paths.texts()
    for i, (t_ar, t_en, sents) in enumerate(STORIES, 1):
        sid = 'story-adv-%02d' % i
        obj = {'id': sid, 'kind': 'story', 'level': 'advanced',
               'title': {'ar': t_ar, 'en': t_en},
               'dialect': 'pal', 'subdialect': 'urban', 'source': SRC,
               'sentences': [{'ar': a, 'en': e} for a, e in sents]}
        json.dump(obj, open(os.path.join(tdir, sid + '.json'), 'w', encoding='utf-8'),
                  ensure_ascii=False, indent=1)
    print('wrote %d advanced stories' % len(STORIES))

if __name__ == '__main__':
    raise SystemExit(main() or 0)
