#!/usr/bin/env python3
"""Intermediate short stories — emit texts/story-int-NN.json.

Past-tense narratives (8-12 sentences) with small plots and connectors. Not
native-validated; word metadata looked up from Maknuune at ingest.
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402  -- per-language file layout
import json, os
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SRC = ("Intermediate short story written in spoken Palestinian by Claude. "
       "NOT native-validated.")

STORIES = [
 ("رحلة عالبحر", "A Trip to the Sea", [
   ("الصيف الماضي، قررنا نروح عالبحر مع العيلة.", "Last summer, we decided to go to the sea with the family."),
   ("صحينا الصبح بكير وحضرنا الأكل والشراب.", "We woke up early in the morning and prepared food and drinks."),
   ("ركبنا السيارة والطريق كان طويل بس حلو.", "We got in the car and the road was long but nice."),
   ("لما وصلنا، الولاد نزلوا عالمي على طول.", "When we arrived, the kids went into the water right away."),
   ("قعدنا تحت الشمس وأكلنا بطيخ بارد.", "We sat under the sun and ate cold watermelon."),
   ("بعد الظهر، الجو صار أبرد شوي.", "In the afternoon, the weather got a bit cooler."),
   ("لعبنا بالرملة وجمعنا صدف.", "We played in the sand and collected seashells."),
   ("قبل ما نرجع، تفرجنا عالغروب.", "Before we went back, we watched the sunset."),
   ("رجعنا عالبيت تعبانين بس مبسوطين.", "We came home tired but happy."),
   ("كان يوم ما بننساه.", "It was a day we won't forget."),
 ]),
 ("أول يوم بالشغل", "First Day at Work", [
   ("أول يوم بالشغل، كنت خايف شوي.", "On my first day at work, I was a bit scared."),
   ("صحيت بكير ولبست أحسن أواعي عندي.", "I woke up early and put on my best clothes."),
   ("وصلت المكتب قبل الوقت بنص ساعة.", "I got to the office half an hour early."),
   ("المدير استقبلني وعرفني عالموظفين.", "The manager welcomed me and introduced me to the employees."),
   ("كانوا كلهم طيبين وساعدوني كتير.", "They were all kind and helped me a lot."),
   ("بالأول ما كنت بعرف وين الأشيا.", "At first I didn't know where things were."),
   ("بس بعد شوي، تعودت عالشغل.", "But after a while, I got used to the work."),
   ("بوقت الغدا، قعدت مع زملائي وحكينا.", "At lunchtime, I sat with my colleagues and we talked."),
   ("آخر النهار، حسيت إني تعلمت كتير.", "At the end of the day, I felt I had learned a lot."),
   ("رجعت عالبيت مبسوط ومتحمس لبكرا.", "I went home happy and excited for tomorrow."),
 ]),
 ("ضاع المفتاح", "The Lost Key", [
   ("يوم من الأيام، رجعت عالبيت ولقيت حالي بدون مفتاح.", "One day, I came home and found myself without a key."),
   ("فتشت بجيبي وبالشنطة بس ما لقيته.", "I searched my pocket and my bag but didn't find it."),
   ("تذكرت إني كنت بالسوق قبل شوي.", "I remembered I had been at the market a little earlier."),
   ("رجعت عالسوق ورحت عند كل دكان زرتها.", "I went back to the market and visited every shop I'd been to."),
   ("سألت البياعين إذا حدا لقى مفتاح.", "I asked the sellers if anyone had found a key."),
   ("واحد منهم ضحك وطلعلي المفتاح من الدرج.", "One of them laughed and took the key out of the drawer."),
   ("قال إني نسيته لما دفعت حق الخضرة.", "He said I forgot it when I paid for the vegetables."),
   ("شكرته كتير ورجعت عالبيت مرتاح.", "I thanked him a lot and went home relieved."),
   ("من يومها، بربط المفتاح بخيط بجيبي.", "Since that day, I tie the key with a string in my pocket."),
 ]),
 ("عرس ابن عمي", "My Cousin's Wedding", [
   ("الأسبوع الماضي، كان في عرس ابن عمي.", "Last week, there was my cousin's wedding."),
   ("العيلة كلها اجتمعت من كل البلاد.", "The whole family gathered from all the towns."),
   ("النسوان حضروا الأكل والحلويات.", "The women prepared the food and the sweets."),
   ("لبسنا أحلى أواعينا ورحنا عالقاعة.", "We put on our nicest clothes and went to the hall."),
   ("كان في دبكة وغنا وناس كتير.", "There was dabke, singing, and lots of people."),
   ("العروس كانت لابسة أبيض وحلوة كتير.", "The bride was wearing white and was very beautiful."),
   ("رقصنا وضحكنا لآخر الليل.", "We danced and laughed until late at night."),
   ("جدتي كانت أسعد وحدة بالعرس.", "My grandmother was the happiest one at the wedding."),
   ("رجعنا عالبيت تعبانين بس القلب مبسوط.", "We went home tired but our hearts were happy."),
 ]),
 ("الجارة أم خالد", "The Neighbor Um Khaled", [
   ("جارتنا أم خالد كانت ست كبيرة وطيبة.", "Our neighbor Um Khaled was an old and kind lady."),
   ("كل يوم كانت تقعد عالباب وتسلم عالناس.", "Every day she used to sit by the door and greet people."),
   ("كانت تعرف كل واحد بالحارة باسمه.", "She knew everyone in the neighborhood by name."),
   ("لما كنت صغير، كانت تعطيني حلوى.", "When I was little, she used to give me sweets."),
   ("وكانت تحكيلي قصص من زمان.", "And she used to tell me stories from the old days."),
   ("مرة، مرضت وقعدت بالبيت أسبوع.", "Once, she got sick and stayed home for a week."),
   ("كل الجيران زاروها وجابولها أكل.", "All the neighbors visited her and brought her food."),
   ("لما طابت، رجعت تقعد عالباب من جديد.", "When she got better, she went back to sitting by the door again."),
   ("أم خالد كانت روح الحارة كلها.", "Um Khaled was the soul of the whole neighborhood."),
 ]),
 ("لما كنت صغير", "When I Was Little", [
   ("لما كنت صغير، كنت أسكن ببيت جدي.", "When I was little, I used to live in my grandfather's house."),
   ("كان البيت قديم وفيه حديقة كبيرة.", "The house was old and had a big garden."),
   ("كل الصبح، كنت أصحى على صوت العصافير.", "Every morning, I would wake up to the sound of birds."),
   ("جدي كان يعلمني كيف أزرع وأسقي الشجر.", "My grandfather used to teach me how to plant and water the trees."),
   ("بعد الظهر، كنت ألعب مع ولاد الحارة.", "In the afternoon, I would play with the neighborhood kids."),
   ("كنا نلعب لآخر النهار ونرجع تعبانين.", "We would play until the end of the day and come back tired."),
   ("بالليل، جدتي كانت تطبخ أكل بيتهني.", "At night, my grandmother would cook delicious food."),
   ("كانت أيام بسيطة بس حلوة كتير.", "They were simple days but very lovely."),
   ("لهلأ، بتذكرها وبشتاقلها.", "To this day, I remember them and miss them."),
 ]),
 ("زيارة الجدة", "Visiting Grandma", [
   ("يوم الجمعة، رحنا نزور جدتي بالضيعة.", "On Friday, we went to visit my grandmother in the village."),
   ("الطريق عالضيعة كان طويل وفيه جبال.", "The road to the village was long and had mountains."),
   ("لما وصلنا، جدتي كانت مستنيتنا عالباب.", "When we arrived, my grandmother was waiting for us at the door."),
   ("عزمتنا على غدا كبير طبخته من الصبح.", "She invited us to a big lunch she had cooked since morning."),
   ("أكلنا مقلوبة وسلطة وشربنا لبن.", "We ate maqluba and salad and drank ayran."),
   ("بعد الغدا، قعدنا بالحديقة نشرب شاي.", "After lunch, we sat in the garden drinking tea."),
   ("جدتي حكتلنا عن أيام زمان.", "My grandmother told us about the old days."),
   ("الولاد لعبوا مع القطط بالحوش.", "The kids played with the cats in the yard."),
   ("قبل ما نرجع، عبتلنا جدتي أكل نوخذه.", "Before we left, my grandmother packed us food to take."),
   ("رجعنا عالبيت والقلب مليان محبة.", "We went home with our hearts full of love."),
 ]),
 ("القطة اللي ضاعت", "The Cat That Got Lost", [
   ("مرة، قطتنا مشمش طلعت من الشباك وضاعت.", "Once, our cat Mishmish went out the window and got lost."),
   ("دورنا عليها بكل الحارة بس ما لقيناها.", "We looked for her all over the neighborhood but didn't find her."),
   ("الولاد زعلوا كتير وبكوا.", "The kids got very upset and cried."),
   ("سألنا الجيران إذا حدا شافها.", "We asked the neighbors if anyone had seen her."),
   ("بعد يومين، سمعنا صوت مواء من عالسطح.", "After two days, we heard a meowing sound from the roof."),
   ("طلعنا لفوق ولقينا مشمش خايفة بالزاوية.", "We went up and found Mishmish scared in the corner."),
   ("نزلناها وأكلناها وسقيناها.", "We brought her down, fed her, and gave her water."),
   ("من يومها، بنسكر الشباك بالليل.", "Since that day, we close the window at night."),
   ("مشمش صارت تقعد جنبنا وما بتحب تطلع.", "Mishmish now stays next to us and doesn't like to go out."),
 ]),
 ("رحلة عالقدس", "A Trip to Jerusalem", [
   ("قررنا نروح رحلة عالقدس مع الاصحاب.", "We decided to take a trip to Jerusalem with our friends."),
   ("ركبنا الباص الصبح والطريق كان مزدحم.", "We took the bus in the morning and the road was crowded."),
   ("لما وصلنا، مشينا بالبلد القديمة.", "When we arrived, we walked through the old city."),
   ("الشوارع كانت ضيقة ومليانة دكاكين.", "The streets were narrow and full of shops."),
   ("اشترينا حلويات وبهارات وريحة الكل حلوة.", "We bought sweets and spices and everything smelled nice."),
   ("قعدنا نشرب قهوة ونتفرج عالناس.", "We sat drinking coffee and watching the people."),
   ("زرنا أماكن قديمة وصورنا صور كتير.", "We visited old places and took many pictures."),
   ("بالمسا، تعشينا فلافل وحمص.", "In the evening, we had falafel and hummus for dinner."),
   ("رجعنا عالبيت متعبين بس اليوم كان بيستاهل.", "We went home tired but the day was worth it."),
 ]),
 ("الامتحان", "The Exam", [
   ("كان عندي امتحان مهم يوم الاتنين.", "I had an important exam on Monday."),
   ("درست طول الأسبوع ونمت قليل.", "I studied all week and slept little."),
   ("ليلة الامتحان، ما قدرت أنام من التوتر.", "The night of the exam, I couldn't sleep from the stress."),
   ("الصبح، شربت قهوة وراجعت شوي.", "In the morning, I drank coffee and reviewed a little."),
   ("لما وصلت المدرسة، كل الطلاب كانوا خايفين.", "When I got to school, all the students were scared."),
   ("المعلمة وزعت الأسئلة وقالت ابدأوا.", "The teacher handed out the questions and said 'begin.'"),
   ("بالأول، حسيت إني نسيت كل شي.", "At first, I felt I had forgotten everything."),
   ("بس بعد شوي، هديت وتذكرت الدروس.", "But after a while, I calmed down and remembered the lessons."),
   ("خلصت الامتحان وطلعت مرتاح.", "I finished the exam and came out relieved."),
   ("بعد أسبوع، طلعت النتيجة وكنت من الأوائل.", "After a week, the results came out and I was among the top."),
 ]),
 ("السيارة اللي وقفت", "The Car That Broke Down", [
   ("كنا رايحين رحلة، وفجأة السيارة وقفت بنص الطريق.", "We were going on a trip, and suddenly the car stopped in the middle of the road."),
   ("أبوي نزل وفتح غطا السيارة يتفرج.", "My dad got out and opened the hood to look."),
   ("قال إنه في مشكلة بالمي ولازم نستنى.", "He said there was a problem with the water and we had to wait."),
   ("الجو كان سخن والولاد بلشوا يزعلوا.", "The weather was hot and the kids started to get upset."),
   ("بعد شوي، وقف جنبنا رجال طيب بسيارته.", "After a while, a kind man stopped next to us in his car."),
   ("سأل شو المشكلة وحاول يساعد أبوي.", "He asked what the problem was and tried to help my dad."),
   ("جاب مي وصلح السيارة بربع ساعة.", "He brought water and fixed the car in fifteen minutes."),
   ("شكرناه كتير وكملنا طريقنا.", "We thanked him a lot and continued on our way."),
   ("تعلمنا يومها إنه لازم نحمل مي زيادة.", "That day we learned we should carry extra water."),
 ]),
 ("صديق قديم", "An Old Friend", [
   ("مرة، كنت ماشي بالسوق وشفت وجه بعرفه.", "Once, I was walking in the market and saw a face I knew."),
   ("قربت شوي وعرفت إنه صاحبي القديم زياد.", "I got a bit closer and realized it was my old friend Ziad."),
   ("ما كنا شفنا بعض من أيام المدرسة.", "We hadn't seen each other since our school days."),
   ("عانقنا بعض وضحكنا وتذكرنا الأيام.", "We hugged and laughed and remembered the old days."),
   ("قعدنا بقهوة قريبة وحكينا ساعتين.", "We sat at a nearby café and talked for two hours."),
   ("حكالي إنه صار عنده عيلة وولاد.", "He told me he now had a family and children."),
   ("وأنا حكيتله عن شغلي وحياتي.", "And I told him about my work and my life."),
   ("قبل ما نفترق، تبادلنا الأرقام.", "Before we parted, we exchanged numbers."),
   ("من يومها، صرنا نشوف بعض كل أسبوع.", "Since that day, we started seeing each other every week."),
 ]),
 ("يوم ممطر", "A Rainy Day", [
   ("يوم من أيام الشتا، نزلت شتا قوية من الصبح.", "One winter day, heavy rain fell from the morning."),
   ("كنت لازم أروح عالشغل بس الطريق كان مليان مي.", "I had to go to work but the road was full of water."),
   ("لبست معطف وحملت شمسية وطلعت.", "I put on a coat, carried an umbrella, and went out."),
   ("الريح كانت قوية وقلبت الشمسية.", "The wind was strong and flipped the umbrella."),
   ("انبليت كلي بس ضحكت على حالي.", "I got completely soaked but laughed at myself."),
   ("لما وصلت الشغل، زملائي جابولي منشفة وشاي سخن.", "When I got to work, my colleagues brought me a towel and hot tea."),
   ("قعدنا نحكي عن الشتا ونضحك.", "We sat talking about the rain and laughing."),
   ("آخر النهار، وقفت الشتا وطلعت الشمس.", "At the end of the day, the rain stopped and the sun came out."),
   ("رجعت عالبيت والدنيا صافية وحلوة.", "I went home and the world was clear and beautiful."),
 ]),
 ("أول مرة طبخت", "The First Time I Cooked", [
   ("أول مرة حاولت أطبخ لحالي، كانت إمي مسافرة.", "The first time I tried to cook by myself, my mom was traveling."),
   ("قررت أعمل مجدرة لأنها سهلة.", "I decided to make mujaddara because it's easy."),
   ("غسلت العدس والرز وقطعت البصل.", "I washed the lentils and rice and cut the onions."),
   ("حطيت الزيت عالنار وقليت البصل.", "I put oil on the fire and fried the onions."),
   ("بس نسيت أخفف النار، والبصل احترق شوي.", "But I forgot to lower the heat, and the onions burned a little."),
   ("خفت إنه الأكل يخرب، بس كملت.", "I was afraid the food would be ruined, but I continued."),
   ("حطيت العدس والرز والمي وستنيت.", "I added the lentils, rice, and water and waited."),
   ("بعد نص ساعة، فتحت الغطا وطلع ريحة حلوة.", "After half an hour, I opened the lid and a nice smell came out."),
   ("جربت الأكل وكان طيب أكتر مما توقعت.", "I tried the food and it was better than I expected."),
   ("لما رجعت إمي، طبختلها وفتخرت فيي.", "When my mom came back, I cooked for her and she was proud of me."),
 ]),
 ("سهرة مع الاصحاب", "An Evening with Friends", [
   ("ليلة الخميس، اتفقنا نسهر عند صاحبنا سامي.", "Thursday night, we agreed to hang out at our friend Sami's place."),
   ("كل واحد جاب شي: واحد حلويات وواحد فواكه.", "Everyone brought something: one sweets and one fruit."),
   ("قعدنا بالصالون نشرب شاي ونحكي.", "We sat in the living room drinking tea and talking."),
   ("حكينا نكت وضحكنا لآخر الليل.", "We told jokes and laughed until late at night."),
   ("سامي طلع العود وصار يعزف ويغني.", "Sami got out the oud and started playing and singing."),
   ("كلنا غنينا معه أغاني قديمة.", "We all sang old songs with him."),
   ("بنص الليل، عملنا قهوة وكملنا السهرة.", "In the middle of the night, we made coffee and continued the evening."),
   ("نسينا الوقت وصرنا نحكي عن المستقبل.", "We lost track of time and started talking about the future."),
   ("رجعنا عبيوتنا الصبح بدري ومبسوطين.", "We went to our homes early in the morning, happy."),
 ]),
 ("الولد اللي ضاع", "The Boy Who Got Lost", [
   ("مرة بالسوق، شفت ولد صغير عم يبكي لحاله.", "Once at the market, I saw a little boy crying by himself."),
   ("قربت منه وسألته وين إمه.", "I got close to him and asked where his mom was."),
   ("قال إنه ضيع إمه بين الناس.", "He said he had lost his mom among the people."),
   ("مسكت إيده وقلتله ما تخاف، رح نلاقيها.", "I held his hand and told him not to be scared, we'd find her."),
   ("مشينا بين الدكاكين وسألنا الناس عنها.", "We walked among the shops and asked people about her."),
   ("بعد شوي، سمعنا ست عم تنادي عاسم الولد.", "After a while, we heard a woman calling the boy's name."),
   ("الولد ركض عليها وعانقها.", "The boy ran to her and hugged her."),
   ("إمه شكرتني كتير ودمعت عيونها.", "His mom thanked me a lot and her eyes teared up."),
   ("مشيت من هناك والقلب مبسوط.", "I walked away from there with a happy heart."),
 ]),
 ("الدكان القديم", "The Old Shop", [
   ("بآخر الحارة، كان في دكان قديم لأبو سمير.", "At the end of the neighborhood, there was an old shop belonging to Abu Samir."),
   ("الدكان كان صغير بس فيه كل شي.", "The shop was small but had everything."),
   ("أبو سمير كان يعرف كل زبون باسمه.", "Abu Samir knew every customer by name."),
   ("لما كنا صغار، كنا نشتري منه حلوى.", "When we were little, we used to buy sweets from him."),
   ("كان دايما يعطينا قطعة زيادة ويضحك.", "He always used to give us an extra piece and smile."),
   ("مرة، ما كان معي مصاري وحبيت شوكولاتة.", "Once, I had no money and wanted chocolate."),
   ("أبو سمير عطاني ياها وقال ادفع بكرا.", "Abu Samir gave it to me and said pay tomorrow."),
   ("بعد سنين، الدكان سكر بس بنتذكره.", "After years, the shop closed but we remember it."),
   ("أبو سمير كان أكتر من بياع، كان صاحب.", "Abu Samir was more than a seller, he was a friend."),
 ]),
 ("رحلة عالجبل", "A Trip to the Mountain", [
   ("قررنا نطلع عالجبل نتمشى بيوم عطلة.", "We decided to climb the mountain to hike on a day off."),
   ("حملنا مي وأكل ولبسنا كنادر مريحة.", "We carried water and food and wore comfortable shoes."),
   ("الطلعة كانت صعبة والجو كان بارد.", "The climb was hard and the weather was cold."),
   ("بس المنظر من فوق كان بيوخذ العقل.", "But the view from the top was breathtaking."),
   ("شفنا الضيع الصغيرة والشجر الأخضر.", "We saw the small villages and the green trees."),
   ("قعدنا عصخرة كبيرة وأكلنا وارتحنا.", "We sat on a big rock, ate, and rested."),
   ("الهوا كان نقي والدنيا هادية.", "The air was fresh and the world was quiet."),
   ("قبل الغروب، بلشنا ننزل عالبيت.", "Before sunset, we started going down home."),
   ("رجعنا تعبانين بس مليانين طاقة.", "We came back tired but full of energy."),
 ]),
 ("جارنا الجديد", "Our New Neighbor", [
   ("الشهر الماضي، سكن جنبنا جار جديد.", "Last month, a new neighbor moved in next to us."),
   ("بالأول، ما كنا نعرف عنه إشي.", "At first, we didn't know anything about him."),
   ("إمي قالت لازم نرحب فيه متل ما بتعمل الناس.", "My mom said we should welcome him like people do."),
   ("طبخت صحن أكل وبعتتني أوديه عنده.", "She cooked a plate of food and sent me to take it to him."),
   ("دقيت الباب وقدمتله الصحن ورحبت فيه.", "I knocked on the door, gave him the plate, and welcomed him."),
   ("فرح كتير وقال إنه لسا جديد بالبلد.", "He was very happy and said he was new to the town."),
   ("بعد يومين، رد علينا بصحن حلويات.", "After two days, he returned the gesture with a plate of sweets."),
   ("من يومها، صار من أحسن جيراننا.", "Since that day, he became one of our best neighbors."),
   ("تعلمنا إنه ترحيب صغير بيفتح قلوب كبيرة.", "We learned that a small welcome opens big hearts."),
 ]),
 ("الكتاب اللي قريته", "The Book I Read", [
   ("صاحبي عطاني كتاب وقال لازم تقراه.", "My friend gave me a book and said I had to read it."),
   ("بالأول، ما كنت متحمس كتير.", "At first, I wasn't very excited."),
   ("بس أول ما بلشت، ما قدرت أوقف.", "But as soon as I started, I couldn't stop."),
   ("القصة كانت عن ولد عاش بضيعة صغيرة.", "The story was about a boy who lived in a small village."),
   ("كل ليلة، كنت أقرا فصل قبل ما أنام.", "Every night, I would read a chapter before sleeping."),
   ("حسيت إني عايش مع الشخصيات بالكتاب.", "I felt like I was living with the characters in the book."),
   ("بالآخر، القصة خلصت بشكل ما توقعته.", "In the end, the story finished in a way I didn't expect."),
   ("سكرت الكتاب وقعدت أفكر فيه.", "I closed the book and sat thinking about it."),
   ("رجعت الكتاب لصاحبي وقلتله شكرا.", "I returned the book to my friend and thanked him."),
   ("من يومها، صرت أحب القراية أكتر.", "Since that day, I started to love reading more."),
 ]),
 ("عزيمة عالغدا", "A Lunch Invitation", [
   ("يوم الجمعة، عزمنا عمي وعيلته عالغدا.", "On Friday, we invited my uncle and his family for lunch."),
   ("إمي قامت الصبح بكير وبلشت تطبخ.", "My mom got up early in the morning and started cooking."),
   ("طبخت مقلوبة وورق عنب وسلطات.", "She cooked maqluba, stuffed grape leaves, and salads."),
   ("ريحة الأكل ملت البيت كله.", "The smell of food filled the whole house."),
   ("لما إجوا، رحبنا فيهم وقعدناهم بالصالون.", "When they came, we welcomed them and seated them in the living room."),
   ("قدمنا القهوة والولاد لعبوا مع بعض.", "We served coffee and the kids played together."),
   ("بوقت الغدا، قعدنا كلنا حول الطاولة.", "At lunchtime, we all sat around the table."),
   ("الأكل كان بيتهني والحكي ما وقف.", "The food was delicious and the talking didn't stop."),
   ("بعد الغدا، شربنا شاي وأكلنا حلويات.", "After lunch, we drank tea and ate sweets."),
   ("راحوا آخر النهار والبيت كان مليان فرح.", "They left at the end of the day and the house was full of joy."),
 ]),
 ("مشوار عالضيعة", "An Errand to the Village", [
   ("مرة، طلب مني جدي أروح عالضيعة أجيبله دوا.", "Once, my grandfather asked me to go to the village to get him medicine."),
   ("ركبت الباص الصبح والطريق كان طويل.", "I took the bus in the morning and the road was long."),
   ("نزلت بالضيعة وسألت عن الصيدلية.", "I got off in the village and asked about the pharmacy."),
   ("رجال طيب دلني عليها ومشى معي شوي.", "A kind man showed me to it and walked with me a bit."),
   ("اشتريت الدوا وشكرت الصيدلي.", "I bought the medicine and thanked the pharmacist."),
   ("قبل ما أرجع، مريت عالسوق وشريت خضرة.", "Before going back, I passed by the market and bought vegetables."),
   ("الناس بالضيعة كانوا بسطاء وطيبين.", "The people in the village were simple and kind."),
   ("رجعت عالبيت بالمسا ومعي الدوا والخضرة.", "I went home in the evening with the medicine and the vegetables."),
   ("جدي فرح فيي كتير ودعالي.", "My grandfather was very happy with me and blessed me."),
 ]),
 ("ليلة العيد", "The Night of Eid", [
   ("ليلة العيد، البيت كان مليان حركة.", "The night of Eid, the house was full of activity."),
   ("إمي كانت تخبز كعك وتحضر الحلويات.", "My mom was baking ka'ak and preparing the sweets."),
   ("إحنا الولاد، كنا نساعد ونذوق سرا.", "We kids used to help and taste secretly."),
   ("أبوي جاب لكل واحد أواعي جديدة.", "My dad brought each of us new clothes."),
   ("الصبح، لبسنا الجديد ورحنا نسلم عالأهل.", "In the morning, we wore the new clothes and went to greet the relatives."),
   ("كل واحد كان يعطينا عيدية ومصاري.", "Everyone would give us Eid gifts and money."),
   ("بعدين، رحنا عالحديقة نلعب مع الولاد.", "Then, we went to the garden to play with the kids."),
   ("بالمسا، اجتمعت العيلة كلها عالعشا.", "In the evening, the whole family gathered for dinner."),
   ("كانت أحلى ليلة بالسنة كلها.", "It was the nicest night in the whole year."),
 ]),
 ("الرحلة عالبيارة", "The Trip to the Orchard", [
   ("بأيام الخريف، رحنا نقطف زيتون ببيارة عمي.", "In the fall days, we went to pick olives at my uncle's orchard."),
   ("صحينا بكير لأنه القطاف بدو وقت.", "We woke up early because picking takes time."),
   ("فرشنا شراشف تحت الشجر وبلشنا نقطف.", "We spread sheets under the trees and started picking."),
   ("الشغل كان تعبان بس الجو كان حلو.", "The work was tiring but the weather was nice."),
   ("بوقت الغدا، أكلنا خبز وزيت وزعتر تحت الشجر.", "At lunchtime, we ate bread, oil, and za'tar under the trees."),
   ("الولاد كانوا يلعبوا ويجمعوا الزيتون اللي وقع.", "The kids were playing and gathering the olives that fell."),
   ("آخر النهار، جمعنا أكياس كتير.", "At the end of the day, we gathered many bags."),
   ("أخذنا الزيتون عالمعصرة نعمله زيت.", "We took the olives to the press to make oil."),
   ("ريحة الزيت الجديد ما في أحلى منها.", "There's nothing nicer than the smell of new oil."),
   ("رجعنا تعبانين بس البيت مليان بركة.", "We came back tired but the house was full of blessing."),
 ]),
 ("يوم بالمستشفى", "A Day at the Hospital", [
   ("مرة، جدتي تعبت ورحنا فيها عالمستشفى.", "Once, my grandmother got sick and we took her to the hospital."),
   ("كنا خايفين عليها كتير.", "We were very worried about her."),
   ("الدكتور فحصها وقال إنه ما في خطر.", "The doctor examined her and said there was no danger."),
   ("قال إنها بس تعبانة وبدها راحة.", "He said she was just tired and needed rest."),
   ("ارتحنا كلنا لما سمعنا الحكي.", "We all felt relieved when we heard that."),
   ("قعدنا جنبها بالغرفة وحكينا معها.", "We sat next to her in the room and talked with her."),
   ("بعد يومين، طابت ورجعناها عالبيت.", "After two days, she got better and we took her home."),
   ("طبخنالها أكل خفيف وقعدنا نهتم فيها.", "We cooked her light food and took care of her."),
   ("بعد أسبوع، رجعت متل ما كانت.", "After a week, she went back to how she was."),
   ("تعلمنا يومها إنه الصحة أغلى شي.", "That day we learned that health is the most precious thing."),
 ]),
 ("القطار", "The Train", [
   ("أول مرة ركبت قطار، كنت متحمس كتير.", "The first time I rode a train, I was very excited."),
   ("وصلت المحطة بكير وقعدت أستنى.", "I got to the station early and sat waiting."),
   ("لما إجا القطار، ركبت وقعدت جنب الشباك.", "When the train came, I got on and sat by the window."),
   ("بلش القطار يمشي والمنظر يتغير.", "The train started moving and the scenery changed."),
   ("شفت حقول وبيوت وجبال بتمر بسرعة.", "I saw fields, houses, and mountains passing by quickly."),
   ("جنبي قعد رجال كبير وحكالي عن سفراته.", "Next to me sat an old man who told me about his travels."),
   ("الوقت مر بسرعة ونحنا عم نحكي.", "Time passed quickly while we were talking."),
   ("لما وصلت، ودعت الرجال وشكرته.", "When I arrived, I said goodbye to the man and thanked him."),
   ("رحلة القطار خلتني أحب السفر أكتر.", "The train trip made me love traveling more."),
 ]),
 ("الفنجان المكسور", "The Broken Cup", [
   ("مرة، كنت بساعد إمي بغسيل الصحون.", "Once, I was helping my mom wash the dishes."),
   ("وأنا بغسل، وقع مني فنجان قهوة وانكسر.", "While washing, a coffee cup fell from me and broke."),
   ("الفنجان كان قديم وغالي على إمي.", "The cup was old and precious to my mom."),
   ("خفت كتير وما عرفت شو أقول.", "I got very scared and didn't know what to say."),
   ("رحت لإمي وقلتلها الحقيقة.", "I went to my mom and told her the truth."),
   ("توقعت إنها تزعل، بس هي بس ابتسمت.", "I expected her to be upset, but she just smiled."),
   ("قالت إنه الأشيا بتنكسر، بس الصدق أهم.", "She said things break, but honesty is more important."),
   ("ارتحت كتير لما سمعت حكيها.", "I felt very relieved when I heard her words."),
   ("من يومها، بحاول أكون صادق دايما.", "Since that day, I try to always be honest."),
 ]),
 ("العصفور", "The Bird", [
   ("صبح يوم، لقينا عصفور صغير وقع من عشه.", "One morning, we found a little bird that had fallen from its nest."),
   ("كان خايف وجناحه موجوع.", "It was scared and its wing was hurt."),
   ("أخذناه عالبيت وحطيناه بعلبة فيها قطن.", "We took it home and put it in a box with cotton."),
   ("أطعمناه فتات خبز وحطينا جنبه مي.", "We fed it bread crumbs and put water next to it."),
   ("كل يوم، كنا نهتم فيه ونتفرج عليه.", "Every day, we took care of it and watched it."),
   ("بعد أسبوع، بلش جناحه يطيب.", "After a week, its wing started to heal."),
   ("وصار يقفز بالعلبة ويحاول يطير.", "It started hopping in the box and trying to fly."),
   ("يوم، فتحنا الشباك وطلعناه عالإيد.", "One day, we opened the window and held it out on our hand."),
   ("طار العصفور بالسما ونحنا عم نتفرج.", "The bird flew into the sky while we watched."),
   ("زعلنا إنه راح، بس فرحنا إنه صار حر.", "We were sad it left, but happy it became free."),
 ]),
 ("الشتوية الأولى", "The First Snow", [
   ("شتا من الشتوات، صحينا ولقينا الدنيا بيضا.", "One winter, we woke up and found the world white."),
   ("نزل تلج بالليل وغطى كل إشي.", "Snow had fallen at night and covered everything."),
   ("الولاد فرحوا كتير وركضوا عالحديقة.", "The kids were very happy and ran to the garden."),
   ("عملوا رجل تلج كبير وحطولوا جزرة.", "They made a big snowman and gave it a carrot."),
   ("تراشقنا بكرات التلج وضحكنا كتير.", "We threw snowballs at each other and laughed a lot."),
   ("إمي عملتلنا شوكولاتة سخنة.", "My mom made us hot chocolate."),
   ("قعدنا حوالي الصوبا نتدفى.", "We sat around the heater to warm up."),
   ("من الشباك، كنا نتفرج عالتلج ينزل.", "From the window, we watched the snow fall."),
   ("كان يوم ما بننساه أبدا.", "It was a day we'll never forget."),
 ]),
 ("يوم بالمكتبة", "A Day at the Library", [
   ("يوم من الأيام، رحت عالمكتبة أدور على كتاب.", "One day, I went to the library to look for a book."),
   ("المكتبة كانت كبيرة وهادية.", "The library was big and quiet."),
   ("الرفوف كانت مليانة كتب من كل نوع.", "The shelves were full of books of every kind."),
   ("مشيت بين الرفوف وقريت عناوين كتير.", "I walked between the shelves and read many titles."),
   ("لقيت كتاب قصص قديمة وقعدت أتصفحه.", "I found a book of old stories and sat leafing through it."),
   ("الوقت مر وأنا ما حسيت فيه.", "Time passed and I didn't feel it."),
   ("الموظفة قالت إنه المكتبة رح تسكر.", "The employee said the library was about to close."),
   ("استعرت الكتاب وطلعت.", "I borrowed the book and left."),
   ("بالطريق، كنت متحمس أبلش أقراه.", "On the way, I was excited to start reading it."),
   ("من يومها، صرت أروح عالمكتبة كل أسبوع.", "Since that day, I started going to the library every week."),
 ]),
]

def main():
    from bookshelf import check_sentences
    rc = check_sentences('intermediate stories',
                         [(a, e) for _t, _te, ss in STORIES for a, e in ss])
    if rc:
        return rc
    tdir = paths.texts()
    for i, (t_ar, t_en, sents) in enumerate(STORIES, 1):
        sid = 'story-int-%02d' % i
        obj = {'id': sid, 'kind': 'story', 'level': 'intermediate',
               'title': {'ar': t_ar, 'en': t_en},
               'dialect': 'pal', 'subdialect': 'urban', 'source': SRC,
               'sentences': [{'ar': a, 'en': e} for a, e in sents]}
        json.dump(obj, open(os.path.join(tdir, sid + '.json'), 'w', encoding='utf-8'),
                  ensure_ascii=False, indent=1)
    print('wrote %d intermediate stories' % len(STORIES))

if __name__ == '__main__':
    raise SystemExit(main() or 0)
