#!/usr/bin/env python3
"""Build the Dinner Table (Phase-6 multi-party listening) data (+ audio).

Reads texts/table.json and emits app/data/table.js -> window.TABLE = {dialogues:[...]}. With
--audio it generates one clip PER LINE. Multi-party voices: give a cast member a "voice" (an
ElevenLabs voice id) in texts/table.json and their lines use it; otherwise the PINNED voice is used
for everyone (single-voice fallback). The app plays the lines back-to-back in one continuous
player, so distinct per-speaker voices turn it into a real multi-voice conversation.

Run:
    python3 pipeline/table.py                 # data only
    export ELEVENLABS_API_KEY=...; python3 pipeline/table.py --audio
"""
import json, os, sys, argparse, ssl, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
sys.path.insert(0, HERE)
from voice import voice_id

try:
    import certifi
    _SSL = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL = ssl.create_default_context()

SRC = os.path.join(ROOT, 'texts', 'table.json')
OUT_JS = os.path.join(ROOT, 'app', 'data', 'table.js')
AUDIO_DIR = os.path.join(ROOT, 'app', 'audio', 'table')


def tts(text, path, key, voice, model='eleven_multilingual_v2'):
    if os.path.exists(path):
        return True, 'cached'
    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{voice}',
        data=json.dumps({'text': text, 'model_id': model}).encode(),
        headers={'xi-api-key': key, 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=90, context=_SSL) as r:
            open(path, 'wb').write(r.read())
        return True, 'generated'
    except Exception as e:
        return False, str(e)[:100]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--audio', action='store_true', help='generate per-line MP3s (needs ELEVENLABS_API_KEY)')
    a = ap.parse_args()

    d = json.load(open(SRC, encoding='utf-8'))
    key, pinned = os.environ.get('ELEVENLABS_API_KEY'), voice_id()
    do_audio = a.audio and key and pinned
    if a.audio and not do_audio:
        print('!! --audio requested but ELEVENLABS_API_KEY not set; emitting data with no audio\n')
    if do_audio:
        os.makedirs(AUDIO_DIR, exist_ok=True)
        print(f'generating audio… (pinned voice {pinned}; per-speaker voices where set)')

    n = [0]
    dialogues = []
    for dg in d['dialogues']:
        voice_of = {c['id']: (c.get('voice') or pinned) for c in dg['cast']}
        lines = []
        for li in dg['lines']:
            rid = 'd%d' % n[0]
            n[0] += 1
            rec = {'sp': li['sp'], 'ar': li['ar'], 'en': li['en']}
            clip = os.path.join(AUDIO_DIR, rid + '.mp3')
            if os.path.exists(clip):
                rec['audio'] = 'audio/table/%s.mp3' % rid
            elif do_audio:
                ok, how = tts(li['ar'], clip, key, voice_of.get(li['sp'], pinned))
                print(f'  {rid} [{li["sp"]}] {li["ar"][:20]:20} {how}')
                if ok:
                    rec['audio'] = 'audio/table/%s.mp3' % rid
            lines.append(rec)
        dialogues.append({'id': dg['id'], 'title': dg['title'], 'level': dg['level'],
                          'scene': dg['scene'], 'cast': dg['cast'], 'lines': lines,
                          'questions': dg.get('questions', [])})

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/table.py — do not edit by hand.\n')
        f.write('// Dinner-table dialogues (spoken Palestinian, written by Claude — NOT native-checked).\n')
        f.write('window.TABLE = ')
        json.dump({'dialogues': dialogues}, f, ensure_ascii=False, indent=1)
        f.write(';\n')

    voiced = sum(1 for dg in dialogues for li in dg['lines'] if li.get('audio'))
    print(f'dialogues: {len(dialogues)} · {n[0]} lines · audio {voiced}/{n[0]}')
    print('-> app/data/table.js')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
