#!/usr/bin/env python3
"""Build the Dinner Table (Phase-6 multi-party listening) data (+ audio).

Reads texts/table.json and emits app/data/table.js -> window.TABLE = {dialogues:[...]}. With
--audio it generates one clip PER LINE, CAST rather than narrated: each speaker is assigned a
voice from the roster in texts/voices.json, matched to the `gender` on their cast entry so the
mother is never read by a man, and held for the whole scene. An explicit `voice` on a cast member
overrides that. With four voices (2m/2f) a scene with three men reuses one within the gender
rather than crossing it — adding a 5th/6th voice clears the remaining collisions. The app plays
the lines back-to-back in one continuous player, which is what makes this multi-party LISTENING
rather than a list of sentences.

Run:
    python3 pipeline/table.py                 # data only
    export ELEVENLABS_API_KEY=...; python3 pipeline/table.py --audio
"""
import json, os, sys, argparse, ssl, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
sys.path.insert(0, HERE)
from voice import voice_id, cast_voices, cast_by_gender

try:
    import certifi
    _SSL = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL = ssl.create_default_context()

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402  -- where this language's generated data lives

SRC = os.path.join(ROOT, 'texts', 'table.json')
OUT_JS = paths.data('table.js')
AUDIO_DIR = os.path.join(ROOT, 'app', 'audio', 'table')


def tts(text, path, key, voice, model='eleven_multilingual_v2'):
    if os.path.exists(path):
        return True, 'cached'
    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{voice}',
        data=json.dumps({'text': text, 'model_id': model}).encode(),
        headers={'xi-api-key': key, 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=90, context=_SSL) as r:
            open(path, 'wb').write(r.read())
        return True, 'generated'
    except Exception as e:
        return False, str(e)[:100]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--audio', action='store_true', help='generate per-line MP3s (needs ELEVENLABS_API_KEY)')
    a = ap.parse_args()

    d = json.load(open(SRC, encoding='utf-8'))
    key, pinned = os.environ.get('ELEVENLABS_API_KEY'), voice_id()
    do_audio = a.audio and key and pinned
    if a.audio and not do_audio:
        print('!! --audio requested but ELEVENLABS_API_KEY not set; emitting data with no audio\n')
    if do_audio:
        os.makedirs(AUDIO_DIR, exist_ok=True)
        print(f'generating audio… (pinned voice {pinned}; per-speaker voices where set)')

    n = [0]
    dialogues = []
    for dg in d['dialogues']:
        # Cast the scene: an explicit `voice` on a cast member always wins; otherwise take the
        # next unused voice of that person's gender, so the mother is never read by a man. When a
        # gender runs out (five at the table, two male voices) reuse within the gender rather than
        # crossing it. Held for the whole conversation.
        byg, allv, used, voice_of = cast_by_gender(), cast_voices(), [], {}
        for c in dg['cast']:
            if c.get('voice'):
                voice_of[c['id']] = c['voice']; used.append(c['voice']); continue
            pool = byg.get((c.get('gender') or '').lower()[:1]) or []
            pick = (next((v for v in pool if v not in used), None)
                    or next((v for v in allv if v not in used and (not pool or v in pool)), None)
                    or (pool[len(used) % len(pool)] if pool else allv[len(used) % len(allv)]))
            voice_of[c['id']] = pick; used.append(pick)
        lines = []
        for li in dg['lines']:
            rid = 'd%d' % n[0]
            n[0] += 1
            rec = {'sp': li['sp'], 'ar': li['ar'], 'en': li['en']}
            clip = os.path.join(AUDIO_DIR, rid + '.mp3')
            if os.path.exists(clip):
                rec['audio'] = 'audio/table/%s.mp3' % rid
            elif do_audio:
                ok, how = tts(li['ar'], clip, key, voice_of.get(li['sp'], pinned))
                print(f'  {rid} [{li["sp"]}] {li["ar"][:20]:20} {how}')
                if ok:
                    rec['audio'] = 'audio/table/%s.mp3' % rid
            lines.append(rec)
        dialogues.append({'id': dg['id'], 'title': dg['title'], 'level': dg['level'],
                          'scene': dg['scene'],
                          'cast': [dict(c, voice=voice_of.get(c['id'])) for c in dg['cast']],
                          'lines': lines,
                          'questions': dg.get('questions', [])})

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/table.py — do not edit by hand.\n')
        f.write('// Dinner-table dialogues (spoken Palestinian, written by Claude — NOT native-checked).\n')
        f.write('window.TABLE = ')
        json.dump({'dialogues': dialogues}, f, ensure_ascii=False, indent=1)
        f.write(';\n')

    voiced = sum(1 for dg in dialogues for li in dg['lines'] if li.get('audio'))
    print(f'dialogues: {len(dialogues)} · {n[0]} lines · audio {voiced}/{n[0]}')
    print('-> app/data/table.js')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
