#!/usr/bin/env python3
"""Generate a per-word Palestinian audio clip for the vocabulary that appears in the app's
content (stories, news, lessons), so memorization cards can play your real Ramallah voice.

Runtime TTS from a public web page would expose your key, so we pre-generate here instead.
Cards whose lemma isn't in the emitted manifest fall back to the browser's built-in voice.

Run:  ELEVENLABS_API_KEY=... python3 pipeline/vocab_audio.py
The voice comes from pipeline/voice.py (ELEVENLABS_VOICE_ID overrides it if you set one).
Without the key it just reports how many clips WOULD be generated and writes nothing.
Clips are cached by content hash, so re-runs only synthesize new words.
"""
import json, os, glob, hashlib, urllib.request, ssl, urllib.error
from voice import voice_id

# macOS python.org builds ship without wired-up CA certs, so HTTPS verification fails with
# CERTIFICATE_VERIFY_FAILED. Use certifi's bundle when it's installed (it is, via pip).
try:
    import certifi
    _SSL = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL = None

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUTDIR = os.path.join(ROOT, 'app', 'audio', 'vocab')
MANIFEST = os.path.join(ROOT, 'app', 'data', 'vocab_audio.js')

def collect():
    """Unique real-word vocabulary from every ingested text: lemma -> vocalized form to speak."""
    vocab = {}
    for p in glob.glob(os.path.join(ROOT, 'build', '*', 'text.json')):
        d = json.load(open(p, encoding='utf-8'))
        for s in d['sentences']:
            for w in s['words']:
                lemma = w.get('lemma')
                if not lemma or not (w.get('maknuune_id') or str(w.get('provenance','')).startswith('curated')):
                    continue
                # Speak the vocalized dictionary form; fall back to the lemma itself.
                vocab.setdefault(lemma, w.get('form') or w.get('vocalized') or lemma)
    return vocab

# eleven_multilingual_v2 is the standard model that handles Arabic and is available on all
# plans; override with ELEVENLABS_MODEL=... (e.g. eleven_v3) if your account has another.
MODEL = os.environ.get('ELEVENLABS_MODEL', 'eleven_multilingual_v2')

def tts(text, out_path, key, voice):
    if os.path.exists(out_path):
        return 'cached'
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice}",
        data=json.dumps({"text": text, "model_id": MODEL}).encode(),
        headers={"xi-api-key": key, "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=90, context=_SSL) as r:
            open(out_path, 'wb').write(r.read())
        return 'generated'
    except urllib.error.HTTPError as e:            # surface ElevenLabs' actual message
        raise RuntimeError('HTTP %s — %s' % (e.code, e.read().decode('utf-8', 'replace')[:300]))

def main():
    vocab = collect()
    key, voice = os.environ.get('ELEVENLABS_API_KEY'), voice_id()
    print('%d unique vocabulary words in content.' % len(vocab))
    if not key:
        print('No ELEVENLABS_API_KEY set — nothing generated.')
        print('Set it and re-run to synthesize your Palestinian voice for each word.')
        return
    print('voice: %s   model: %s' % (voice, MODEL))
    os.makedirs(OUTDIR, exist_ok=True)
    manifest, gen, cached, failed = {}, 0, 0, 0
    items = sorted(vocab.items())
    for n, (lemma, text) in enumerate(items):
        name = hashlib.md5(lemma.encode('utf-8')).hexdigest()[:16] + '.mp3'
        out = os.path.join(OUTDIR, name)
        try:
            status = tts(text, out, key, voice)
            manifest[lemma] = 'audio/vocab/' + name
            gen += status == 'generated'; cached += status == 'cached'
        except Exception as e:
            failed += 1
            print('  !! %s: %s' % (lemma, str(e)[:320]))
            # Don't hammer the API 1400 times if the very first calls all fail — bail with
            # the real error so it can be fixed (bad model, voice, or plan) before retrying.
            if failed >= 3 and gen == 0 and cached == 0:
                print('\nFirst %d requests all failed — stopping so we don’t burn credits.' % failed)
                print('Check the message above (usually the model_id or voice_id, or plan '
                      'limits). Try ELEVENLABS_MODEL=eleven_multilingual_v2 or v1, and confirm '
                      'the voice is saved in your ElevenLabs Voices (not just a Design preview).')
                return
    with open(MANIFEST, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/vocab_audio.py — do not edit by hand.\n')
        f.write('window.VOCAB_AUDIO = ')
        json.dump(manifest, f, ensure_ascii=False)
        f.write(';\n')
    print('generated %d, cached %d, failed %d -> %s (%d clips)' % (
        gen, cached, failed, os.path.relpath(MANIFEST, ROOT), len(manifest)))

if __name__ == '__main__':
    main()
