#!/usr/bin/env python3
"""Generate a per-word Palestinian audio clip for the vocabulary that appears in the app's
content (stories, news, lessons), so memorization cards can play your real Ramallah voice.

Runtime TTS from a public web page would expose your key, so we pre-generate here instead.
Cards whose lemma isn't in the emitted manifest fall back to the browser's built-in voice.

Run:  ELEVENLABS_API_KEY=... ELEVENLABS_VOICE_ID=... python3 pipeline/vocab_audio.py
Without the keys it just reports how many clips WOULD be generated and writes nothing.
Clips are cached by content hash, so re-runs only synthesize new words.
"""
import json, os, glob, hashlib, urllib.request

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUTDIR = os.path.join(ROOT, 'app', 'audio', 'vocab')
MANIFEST = os.path.join(ROOT, 'app', 'data', 'vocab_audio.js')

def collect():
    """Unique real-word vocabulary from every ingested text: lemma -> vocalized form to speak."""
    vocab = {}
    for p in glob.glob(os.path.join(ROOT, 'build', '*', 'text.json')):
        d = json.load(open(p, encoding='utf-8'))
        for s in d['sentences']:
            for w in s['words']:
                lemma = w.get('lemma')
                if not lemma or not (w.get('maknuune_id') or str(w.get('provenance','')).startswith('curated')):
                    continue
                # Speak the vocalized dictionary form; fall back to the lemma itself.
                vocab.setdefault(lemma, w.get('form') or w.get('vocalized') or lemma)
    return vocab

def tts(text, out_path, key, voice):
    if os.path.exists(out_path):
        return 'cached'
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice}",
        data=json.dumps({"text": text, "model_id": "eleven_v3"}).encode(),
        headers={"xi-api-key": key, "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=90) as r:
        open(out_path, 'wb').write(r.read())
    return 'generated'

def main():
    vocab = collect()
    key, voice = os.environ.get('ELEVENLABS_API_KEY'), os.environ.get('ELEVENLABS_VOICE_ID')
    print('%d unique vocabulary words in content.' % len(vocab))
    if not (key and voice):
        print('No ELEVENLABS_API_KEY / ELEVENLABS_VOICE_ID set — nothing generated.')
        print('Set them and re-run to synthesize your Palestinian voice for each word.')
        return
    os.makedirs(OUTDIR, exist_ok=True)
    manifest, gen, cached, failed = {}, 0, 0, 0
    for lemma, text in sorted(vocab.items()):
        name = hashlib.md5(lemma.encode('utf-8')).hexdigest()[:16] + '.mp3'
        out = os.path.join(OUTDIR, name)
        try:
            status = tts(text, out, key, voice)
            manifest[lemma] = 'audio/vocab/' + name
            gen += status == 'generated'; cached += status == 'cached'
        except Exception as e:
            failed += 1
            print('  !! %s: %s' % (lemma, str(e)[:80]))
    with open(MANIFEST, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by pipeline/vocab_audio.py — do not edit by hand.\n')
        f.write('window.VOCAB_AUDIO = ')
        json.dump(manifest, f, ensure_ascii=False)
        f.write(';\n')
    print('generated %d, cached %d, failed %d -> %s (%d clips)' % (
        gen, cached, failed, os.path.relpath(MANIFEST, ROOT), len(manifest)))

if __name__ == '__main__':
    main()
